Добавляет демо в статью load и DOMContentLoaded
doka-guide/content pull request #1042
Opened 2021-06-15 14:43 UTC by skorobaeus

2021-06-15 19:56 UTC, nlopin requested changes

2021-06-15 19:56 UTC, nlopin commented on js/event-load-and-domcontentloaded/demos/basic.html
> +  let diffSpan = document.getElementById('difference');
буду нудеть, что неизменяемые переменные нужно делать `const`

2021-06-15 19:56 UTC, nlopin commented on js/event-load-and-domcontentloaded/demos/overloaded.html
> +<!DOCTYPE html>
@skorobaeus что это за файл на 10 тысяч строк? кажется надо удалить

2021-06-16 08:27 UTC, skorobaeus commented on js/event-load-and-domcontentloaded/demos/overloaded.html
> +<!DOCTYPE html>
@nlopin В этом и смысл. В файле много мусорных стилей, чтобы увеличить разницу между событиями load и DOMContentLoaded. 

Вот оригинальное демо: https://codepen.io/Lopinopulos/pen/ydYMWW Я разбила его на два, потому что при встройке через айфрейм нельзя удалить стили из вкладки CSS и посмотреть, что получится.

2021-06-16 08:39 UTC, skorobaeus commented on js/event-load-and-domcontentloaded/demos/basic.html
> +  let diffSpan = document.getElementById('difference');
diff изменяемая, остальное поменяла

2021-06-16 17:12 UTC, nlopin commented on js/event-load-and-domcontentloaded/demos/overloaded.html
> +<!DOCTYPE html>
понял, я туповат 😬 может просто заменим на гигантскую каринку?

2021-06-17 12:31 UTC, skorobaeus commented on js/event-load-and-domcontentloaded/demos/overloaded.html
> +<!DOCTYPE html>
А она не закэшируется? 🤔

2021-06-17 12:39 UTC, nlopin commented on js/event-load-and-domcontentloaded/demos/overloaded.html
> +<!DOCTYPE html>
Смотря как мы будем ее качать. Я не уверен, что картинка повлияет на срабатывание событий. Давай сделаем микроэксперимент

2021-06-18 08:30 UTC, Windrushfarer commented on js/event-load-and-domcontentloaded/demos/overloaded.html
> +<!DOCTYPE html>
Можете попробовать взять ссылку на картинку и добавлять к ней рандомный хэш в query-параметер. Например `<img src="/path/to/img.jpg?hash=getRandomHash()`, браузер по урлу кэширует, если он постоянно меняется он будет перекачивать. Быстро даже [демку](https://codesandbox.io/s/vibrant-framework-dc3fo?file=/src/index.js) набросал

2021-06-21 17:19 UTC, skorobaeus commented
@nlopin @Windrushfarer Тут такое дело: если открывать демо отдельно в браузере, то работает идеально, картинка каждый раз грузится заново и получается большая разница между событиями.
Но когда я встраиваю демо как айфрейм, мне кажется, что картинка кэшируется. Я попробовала прикрутить хэш даже к ссылке на переход из демки в демку, но это, однако, тычок пальцем в небо 😵

2021-06-22 05:58 UTC, nlopin commented on js/event-load-and-domcontentloaded/demos/basic.html
> +        <a class="button-like blue" href="overloaded.html?hash=${getRandomHash()}">Попробовать с картинкой</a>
Так функция не будет вызываться потому что это не шаблонная строка

2021-06-22 06:11 UTC, nlopin commented
@skorobaeus давай уберём вызов `getRandomHash()`. Я не думаю, что мы его можем как-то подставлять до парсинга html. 

У меня локально даже с кэшем задержка больше, чем совсем без картинки.

2021-06-22 09:33 UTC, skorobaeus commented
Убрала.

2021-07-04 16:45 UTC, nlopin approved these changes

2021-07-04 16:45 UTC, merged