Вносит правила по оформлению инлайнового кода
doka-guide/content pull request #1046
Opened 2021-06-15 20:56 UTC by tachisis

2021-06-16 13:40 UTC, solarrust approved these changes

2021-06-16 13:40 UTC, pepelsbey requested changes
Если мы говорим про CSS-код рядом с примером такого кода, то точку в имени класса важно сохранять:

````md
вложенным в блок с классом `.preview`:

```css
.preview * {
  color: green;
}
```
````

Как это можно систематизировать:

> Добавьте класс `preview` тегу `<div>`, чтобы получилось `<div class="preview">`
> В селекторе `.preview div` класс мы целимся в `div`, вложенный в класс `.preview`

То есть точка или не точка — зависит от контекста.

2021-06-16 15:21 UTC, tachisis commented
@pepelsbey уже даже в твоем примере заметно, что точка нужна, когда нет слова «класс». Когда оно есть, она, по-моему, избыточна.

2021-06-16 15:34 UTC, pepelsbey commented
Я согласен, есть некоторая избыточность, как если писать

> тег `<div>`

Но мы договорились чуть выше, что всегда пишем `<div>` для лучшей узнаваемости — так проще отличить тег от всего остального. Аналогичное справедливо и для классов из CSS.

Плюс это прямое цитирование кода, которое не требует когнитивной нагрузки, чтобы довести название до примера.

Мне кажется, что это допустимая избыточность, которая помогает пониманию, но пока не доходит до уровня канцелярита и не усложняет текст.

2021-06-17 11:19 UTC, tachisis commented
@pepelsbey давай примем одну форму: у тега всегда будут скобки, у класса всегда будет точка. Я исправила все вхождения под это.

2021-06-17 12:59 UTC, pepelsbey commented
Боюсь, что одно решение нам не подойдёт (

Фраза «тег `<p>` с классом `h1`» это буквально пересказ словами `<p class="h1">`. Мы бы не стали писать `<p class=".h1">` — так просто не сработает. По этой же причине не стоит писать «тег `<p>` с классом `.h1`».

Мы не сможем понятно писать, если не будем учитывать контекст. Так что я бы привёл примеры и не пытался придумать единое правило. И уже по смыслу решал бы, как размечать код.

Несколько примеров:

> Чтобы создать тег `<div>`, нужно вызвать метод `createElement()` и передать в него название тега `div`, получится вот так: document.createElement('div').
> …
> Если у нас в разметке есть `<div>` с классом `element`, то чтобы применить к нему стили, нужно в файле стилей написать класс `.element` и описать нужные свойства там.

Видишь, как я иду по контексту?

2021-06-17 13:09 UTC, tachisis commented
@pepelsbey сорри, но я реально не вижу логики, у тебя какое-то свое понимание контекста, видимо. Можешь посмотреть мои правки и внести в них изменения так, как видишь? Может тогда я пойму лучше.

2021-06-17 21:39 UTC, nlopin approved these changes

2021-06-18 03:50 UTC, solarrust commented
С вашего позволения подправляю ошибку рассуждения в примере:
Если у нас в разметке есть `<div>` с классом `element`, то чтобы применить к нему стили, нужно в файле стилей написать ~~класс~~  **селектор** `.element` и описать нужные свойства там.

2021-06-18 08:45 UTC, pepelsbey commented
> нужно в файле стилей написать ~класс~ **селектор** `.element` и описать нужные свойства там.

Это и селектор, и селектор по классу и, собственно, класс. Так говорят люди, думаю, мы тоже можем это себе позволить )

2021-06-23 11:57 UTC, pepelsbey commented
@tachisis поменял классы по следующему принципу, по степени важности:

## Как писать: `.class` или `class`

1. Если текст описывает код, находящийся рядом, то приоритет остаётся за языком кода. Если пример на CSS, то пишем `.class`, если пример на HTML или тут же в тексте упоминяются теги, то `class`.
2. Если рядом нет примеров и упоминание классов в тексте самостоятельное, то следим за применимостью: если речь про CSS, про свойства, значения и около них, то `.class`. Если речь про атрибуты тегов, про добавление или удаление классов с элементов, то `class`.

2021-06-23 14:34 UTC, tachisis commented
@pepelsbey еее, я посмотрела примеры и поняла, ок ок

2021-06-23 14:40 UTC, pepelsbey approved these changes

2021-06-23 14:40 UTC, merged