Добавляет доку про li
doka-guide/content pull request #1055
Opened 2021-06-19 20:43 UTC by nionka

2021-06-20 08:57 UTC, solarrust commented on html/li/index.md
> +contributors:
Мы со Светой пока ничего не законтрибьютили в твою статью, так что этот тег вместе со списком можно пока убрать =)

2021-06-20 08:57 UTC, solarrust commented on html/li/index.md
> +`<li>` - отдельный элемент списка [`<ol>`](/html/ol) , [`<ul>`](/html/ul) или `<menu>`
```suggestion
`<li>` - отдельный элемент списка [`<ol>`](/html/ol) , [`<ul>`](/html/ul) или `<menu>`.
```

2021-06-20 08:57 UTC, solarrust commented on html/li/index.md
> +`<li>` нельзя использовать отдельно. Его родителем **обязательно** должен быть упорядоченный список [`<ol>`](/html/ol) , неупорядоченный список [`<ul>`](/html/ul) или `<menu>`
```suggestion
`<li>` нельзя использовать отдельно. Его родителем **обязательно** должен быть упорядоченный список [`<ol>`](/html/ol), неупорядоченный список [`<ul>`](/html/ul) или `<menu>`.
```

Тут же можно добавить расшифровку собственно li — list item. Многим так проще запоминать теги =)

2021-06-20 08:57 UTC, solarrust commented on html/li/index.md
> +💡Внутрь тега `<li>` можно вкладывать различные элементы, такие как изображения, другие списки, ссылки и т. д.
```suggestion
💡 Внутрь тега `<li>` можно вкладывать различные элементы, такие как изображения, другие списки, ссылки и т. д.
```

2021-06-20 08:57 UTC, solarrust commented on html/li/index.md
> +💡`<li>` является блочным элементом, поэтому пункты будут располагаться друг под другом.
```suggestion
💡 `<li>` является блочным элементом, поэтому пункты будут располагаться друг под другом.
```

По спецификации больше не существует блочных и строчных элементов в строгом понимании. Можно чуть переформулировать. Например, так «тег `<li>` по умолчанию имеет блочные стили». Можно добавить, что это легко меняется через CSS по необходимости.

2021-06-20 08:57 UTC, solarrust commented on html/li/practice/nionka.md
> +🛠️ Для отображения на странице браузеры используют стили по умолчанию. Автоматически добавляются отступы, а также маркеры в маркированном списке [`<ul>`](/html/ul) и цифры в нумерованном списке [`<ol
Пожалуйста, скопируй в начало файла шапку:

```
---
tags:
  - practice
permalink: false
---
```

Это нужно чтобы при сборке не генерировалась отдельная страничка с советом.

2021-06-21 07:01 UTC, solarrust commented
@tachisis @pepelsbey загляните, пожалуйста

2021-06-21 07:03 UTC, solarrust commented on html/li/index.md
> +
Давай добавим блок `## Как пишется` и там напишем про атрибут `value` и про атрибут `type`, но для последнего упомянем, что лучше использовать `list-style-type`.

2021-06-21 09:01 UTC, tachisis reviewed
Пока вроде все хорошо, посмотрю еще раз после правок по запросу Алёны.

2021-06-21 16:04 UTC, pepelsbey requested changes

2021-06-21 16:04 UTC, pepelsbey commented on html/li/index.md
> +
Атрибут `type` может быть только у `<ol>` и `<ul>`, для `<li>` только `value` и то только если он вложен в `<ol>`, [см. описание элемента в спеке](https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element).

2021-06-21 16:04 UTC, pepelsbey commented on html/li/index.md
> +💡 `<li>` по умолчанию имеет блочные стили, поэтому пункты будут располагаться друг под другом. Это поведение легко меняется с помощью CSS.
```suggestion

💡 `<li>` по умолчанию имеет блочные стили, поэтому пункты будут располагаться друг под другом. Это поведение легко меняется с помощью CSS.
```

2021-06-21 16:04 UTC, pepelsbey commented on html/li/index.md
> +`<li>` - сокращение от *list item*.
```suggestion
`<li>` — сокращение от _list item_.
```

2021-06-21 16:04 UTC, pepelsbey commented on html/li/index.md
> +`<li>` - отдельный элемент списка [`<ol>`](/html/ol), [`<ul>`](/html/ul) или `<menu>`.
```suggestion
`<li>` — отдельный элемент списка [`<ol>`](/html/ol), [`<ul>`](/html/ul) или `<menu>`.
```

2021-06-21 16:06 UTC, solarrust commented on html/li/index.md
> +
Еп, именно об этом и надо написать =)

2021-06-27 21:32 UTC, pepelsbey commented on html/li/practice/nionka.md
> +🛠️ Для отображения на странице браузеры используют стили по умолчанию. Автоматически добавляются отступы, а также маркеры в маркированном списке [`<ul>`](/html/ul) и цифры в нумерованном списке [`<ol
```suggestion
🛠️ Для отображения на странице браузеры используют стили по умолчанию. Автоматически добавляются отступы, а также маркеры в неупорядоченном списке [`<ul>`](/html/ul) и цифры в упорядоченном списке [`<ol>`](/html/ol). При необходимости стили можно изменить с помощью CSS.
```

Названия «упорядоченный» и «неупорядоченный» близки к названиям тегов (ordered/unordered) и избавляют от тавтологии «маркеры маркированного».

Но у меня другой вопрос: тут кажется не хватает самого совета: браузеры добавляют стили, их можно изменить. Как именно? :) А зачем вообще использовать списки, если у них проблемы? Может проще дивами. Короче, я бы развил совет, пока он очень скромный.

2021-06-29 08:38 UTC, pepelsbey commented on html/li/practice/nionka.md
> +👆 Чтобы свойства применились ко всем элементам `<li>` в списке, достаточно задать их только внешнему контейнеру (`<ul>` или `<ol>`).
Убрал кавычки с символа и уточнил, как именно он появляется.

```suggestion
🛠️ Для тега `<li>` браузеры по умолчанию добавляют псевдоэлемент `::marker`, который выводит маркер или цифру, в зависимости от типа списка. По умолчанию, в неупорядоченном списке [`<ul>`](/html/ul) — это маркер в виде точки (`disc`), в упорядоченном списке [`<ol>`](/html/ol) — арабская цифра с точкой (`decimal`).

Чтобы стилизовать символ, можно применить стили к `::marker`, а CSS-свойство [`list-style-type`](/css/list-style-type) поможет поменять тип символа или убрать его вовсе (`none`).

Свойство [`list-style-position`](/css/list-style-position) позволяет задать положение символа относительно контента.

А для придания списку большей изюминки символ можно заменить на картинку с помощью [`list-style-image`](/css/list-style-image).

👆 Чтобы свойства применились ко всем элементам `<li>` в списке, достаточно задать их только внешнему контейнеру (`<ul>` или `<ol>`).
```

2021-06-29 13:17 UTC, tachisis reviewed
Немного правочек

2021-06-29 13:17 UTC, tachisis commented on html/li/index.md
> +💡 Внутрь тега `<li>` можно вкладывать различные элементы, такие как изображения, другие списки, ссылки и т. д.
```suggestion
💡 Внутрь тега `<li>` можно вкладывать разные элементы, например, изображения, другие списки, ссылки и т. д.
```

2021-06-29 13:17 UTC, tachisis commented on html/li/practice/nionka.md
> +🛠️ Для тега `<li>` браузеры по умолчанию добавляют псевдоэлемент `::marker`, который выводит маркер или цифру, в зависимости от типа списка. По умолчанию, в неупорядоченном списке [`<ul>`](/html/ul)
```suggestion
🛠️ Для тега `<li>` браузеры добавляют псевдоэлемент `::marker`, который выводит маркер или цифру, в зависимости от типа списка. По умолчанию, в неупорядоченном списке [`<ul>`](/html/ul) это маркер в виде точки (`disc`), в упорядоченном списке [`<ol>`](/html/ol) — арабская цифра с точкой (`decimal`).
```

2021-06-29 13:17 UTC, tachisis commented on html/li/practice/nionka.md
> +Чтобы стилизовать символ, можно применить стили к `::marker`, а CSS-свойство [`list-style-type`](/css/list-style-type) поможет поменять тип символа или убрать его вовсе (`none`).
```suggestion
Чтобы стилизовать маркер, можно применить стили к `::marker`, а CSS-свойство [`list-style-type`](/css/list-style-type) поможет поменять тип маркера или убрать его вовсе (`none`).
```

2021-06-29 13:17 UTC, tachisis commented on html/li/practice/nionka.md
> +Свойство [`list-style-position`](/css/list-style-position) позволяет задать положение символа относительно контента.
```suggestion
Свойство [`list-style-position`](/css/list-style-position) позволяет задать положение маркера относительно контента.
```

2021-06-29 13:17 UTC, tachisis commented on html/li/practice/nionka.md
> +А для придания списку большей изюминки символ можно заменить на картинку с помощью [`list-style-image`](/css/list-style-image).
```suggestion
А для придания списку большей изюминки маркер можно заменить на картинку с помощью [`list-style-image`](/css/list-style-image).
```

2021-06-29 13:17 UTC, tachisis commented on html/li/practice/nionka.md
> +👆 Чтобы свойства применились ко всем элементам `<li>` в списке, достаточно задать их только внешнему контейнеру (`<ul>` или `<ol>`).
```suggestion
👆 Чтобы свойства применились ко всем элементам `<li>` в списке, достаточно задать их внешнему контейнеру (`<ul>` или `<ol>`).
```

2021-06-29 13:17 UTC, tachisis commented on html/li/index.md
> +  - nionka
```suggestion
  - nionka
editors:
  - tachisis
```

2021-06-29 13:23 UTC, pepelsbey approved these changes

2021-06-29 16:26 UTC, solarrust approved these changes
В целях ускорения аппрува приняла правки от @tachisis самолично. 

@nionka поздравляю с первой статьёй! 🥳

2021-06-29 16:29 UTC, merged