Добавляет доку про font-smoothing
doka-guide/content pull request #1062
Opened 2021-06-21 17:05 UTC by solarrust

Закрывает #409

2021-06-21 21:17 UTC, pepelsbey requested changes
Самый первый подход :)

Все картинки к разумнее было бы сделать в PNG: они будут весить меньше (в разы) и выглядеть лучше. Там везде от силы 32 цвета и не нужно сжатие :) Я бы в принципе не использовал JPEG для иллюстрацией, если это не фотка. Надо обсудить с авторами в среду.

Также свойство без префикса везде называется `font-smooth` и только префиксная версия `-*-font-smoothing`. Я бы последовал примеру Can I Use и MDN и назвал бы свойство так же.

2021-06-22 09:07 UTC, solarrust commented
@pepelsbey пофиксила

2021-06-22 12:29 UTC, pepelsbey requested changes
Второй подход:

1. Поправил предупреждение в начале.
2. Засомневался в объяснении свойства (

Если почитать статьи, на которые ссылается MDN, то получается, что всё сильно сложнее, чем просто «включить сглаживание, чтобы было красиво».

https://www.zachleat.com/web/font-smooth/
https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

> сглаживает границы букв, делая их более плавными

Сглаживание и так включено на всех экранах. Но есть разные типы сглаживания, которые по-разному применяются на разных платформах и экранах. В итоге, разработчики обычно пытаются «сделать потоньше» и не учитывают светлые-тёмные темы, особенности разных экранов. И мы можем невольно развить этот миф и спровоцировать плохие решения.

То есть основная идея доки сейчас не передаёт назначение свойства. Мне кажется, нам нужно либо подробно расписать причины существования этого свойства, либо отложить его. Не хочется делать фактических ошибок.

2021-06-22 12:29 UTC, pepelsbey commented on css/font-smoothing/index.md
> +:::
```suggestion
::: callout 🧪

**Осторожно!** Это свойство нестандартное. Используйте его только если вам очень нужно добиться этого эффекта и внимательно проверяйте работу в разных браузерах и на разных платформах. Поддержку можно проверить на [Can I Use](https://caniuse.com/font-smooth).

:::
```

- Отодвинул от разметки колаута
- Смягчил предупреждение, не стоит запрещать — свойство (к сожалению) используется широко

2021-06-22 15:05 UTC, solarrust commented
1. Не писать не можем. Это одна из немногих тем, оставшихся на доске курса.
2. Уходить в дебри рендеринга не хочется. Нужен нелживый минимум. Можно в конце дать ссылки на более подробные статьи.

2021-06-22 15:08 UTC, pepelsbey commented
> что конкретно тебя не устраивает в текущей версии?
> я не хочу уходить вглубь механизма рендеринга. нужен нелживый минимум

Не устраивает, что упрощено до бесполезности и даже потенциального вреда. То есть это такое свойство, применение которого может откровенно навредить, если его просто копипастить «чтобы шрифты были гладкие». Они и так гладкие :)

Я не предлагаю уходить в особенности рендеринга. Но важно честно сказать зачем и как это свойство используется. Например, чтобы переключать один способ сглаживания на другой. Зачем? Потому, что есть разные экраны и разные ОС и где-то так лучше. Можно поискать причины и более точные формулировки [в статье Зака](https://www.zachleat.com/web/font-smooth/).

2021-06-23 16:33 UTC, solarrust commented
@pepelsbey постаралась переформулировать определение и объяснение. На сколько это возможно в условиях этой адской жары =)
Буду рада твоим комментариям!

2021-06-28 07:46 UTC, pepelsbey requested changes
Тут такое дело, что по [Can I use](https://caniuse.com/font-smooth) это свойство работает **только** в десктопных браузерах **только** на macOS. То есть фактически это способ поменять сглаживание шрифтов для пользователей Mac.

Сейчас текст говорит «это работает почти везде, кроме…», но лучше бы сказать «это работает только в…», чтобы не было заблуждений.


<img width="563" alt="Screenshot 2021-06-28 at 10 41 08" src="https://user-images.githubusercontent.com/105274/123598690-7126d480-d7fd-11eb-8ca7-6bf43c62f7ea.png">

2021-06-28 07:46 UTC, pepelsbey commented on css/font-smoothing/index.md
> +Свойство `font-smooth` убирает разницу отображения на разных устройствах, включает один режим сглаживания для всех.
```suggestion
В разных операционных системах и разных браузерах используются разные механизмы сглаживания шрифта. Свойство `font-smooth` может помочь убрать разницу отображения на некоторых платформах, включив один режим сглаживания для всех.
```

Сделал чуть менее уверенно — на мобильных платформах (iOS и Android), свойство в принципе не поддерживается.

2021-06-28 07:46 UTC, pepelsbey commented on css/font-smoothing/index.md
> +По этой причине стоит прибегать к этому методу точечно, ограничивая область действия:
Не очень понятно, что именно происходит в этом примере, как именно ограничивается область действия.

2021-06-29 17:04 UTC, solarrust commented
@pepelsbey поменяла пример на тот, что отсудили — с `@supports`. Потестила в разных браузерах на маке и на винде — работает как надо. Если у тебя будет возможность тоже проверить — будет супер.

2021-07-01 16:55 UTC, tachisis reviewed
Правочки

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +  - solarrust
```suggestion
  - solarrust
editors:
  - tachisis
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +**Осторожно!** Это свойство нестандартное. Используйте его только если вам очень нужно добиться этого эффекта и внимательно проверяйте работу в разных браузерах и на разных платформах. В данный момен
```suggestion
**Осторожно!** Это свойство нестандартное. Используйте его, только если вам очень нужно добиться единого сглаживания, и внимательно проверяйте работу в разных браузерах и на разных платформах. В данный момент свойство работает только на macOS. Поддержку можно проверить на [Can I Use](https://caniuse.com/font-smooth).
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +**Осторожно!** Это свойство нестандартное. Используйте его только если вам очень нужно добиться этого эффекта и внимательно проверяйте работу в разных браузерах и на разных платформах. В данный момен
Честно говоря, хочется этот колаут перенести под блок Кратко

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +В этом примере мы «включаем» среднюю степень сглаживания шрифтов на всём сайте. Поскольку свойство `font-smooth` не стандартное, каждый браузер реализовал его по-своему. Поэтому мы вынуждены писать с
```suggestion
В этом примере мы задаём среднюю степень сглаживания шрифтов на всём сайте. Поскольку свойство `font-smooth` нестандартное, каждый браузер реализовал его по-своему. Так что мы вынуждены писать свойство с [вендорными префиксами](/css/vendor-prefixes) (в работе).
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +При отрисовке текста такая геометричность может доставлять неудобства. Особенно если выбран декоративный шрифт с непрямыми линиями.
```suggestion
При отрисовке текста такая геометричность может доставлять неудобства. Особенно, если выбран декоративный шрифт с непрямыми линиями.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +Свойство `font-smooth` управляет сглаживанием шрифта. Например, значения `antialiased` или `grayscale` окрашивают пиксели, находящиеся по краям буквы в полупрозрачный цвет. Таким образом края буквы к
```suggestion
Свойство `font-smooth` управляет сглаживанием шрифта. Например, значения `antialiased` или `grayscale` окрашивают пиксели, находящиеся по краям буквы, в полупрозрачный цвет. Таким образом края буквы кажутся более плавными.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +![Слово knife набранное дважды, одно без font-smooth, а второе с ним](images/text-example.png)
```suggestion
![Слово «knife», набранное дважды, одно без font-smooth, а второе с ним](images/text-example.png)
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +Из-за того, что свойство `font-smooth` не является частью стандарта CSS каждый браузер реализует его на своё усмотрение.
```suggestion
Из-за того, что свойство `font-smooth` не является частью стандарта CSS, каждый браузер реализует его на своё усмотрение.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +— `auto` — *значение по умолчанию*, позволяет браузеру решить какую степень сглаживания применять.
```suggestion
— `auto` — *значение по умолчанию*, позволяет браузеру решить, какую степень сглаживания применять.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +— `antialiased` — средняя степень сглаживания, пиксели по краям буквы светятся как бы в пол силы, все три лампочки включены. В итоге получается один из оттенков серого.
```suggestion
— `antialiased` — средняя степень сглаживания, пиксели по краям буквы светятся как бы в полсилы, все три лампочки включены. В итоге получается один из оттенков серого.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +— `subpixel-antialiased` — сильная степень сглаживания, пиксели по краям буквы светят в пол силы. Но в отличие от `antialiased` берётся исходный цвет буквы и как бы приглушается. Не имеет аналога для
```suggestion
— `subpixel-antialiased` — сильная степень сглаживания, пиксели по краям буквы светят в полсилы. Но в отличие от `antialiased`, берётся исходный цвет буквы и как бы приглушается. Не имеет аналога для Firefox, а значит, поддерживается ещё меньшим числом устройств, чем само свойство `font-smooth`.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +— `-moz-osx-font-smoothing` для FireFox.
```suggestion
— `-moz-osx-font-smoothing` для Firefox.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +### Значения для FireFox:
```suggestion
### Значения для Firefox:
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +- `auto` — *значение по умолчанию*, позволяет браузеру решить какую степень сглаживания применять.
```suggestion
- `auto` — *значение по умолчанию*, позволяет браузеру решить, какую степень сглаживания применять.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +Идея врубить одинаковое сглаживание на всех операционных системах и во всех браузерах кажется отличной. Но этот подход избыточен, поскольку на устройствах без macOS это свойство не работает.
```suggestion
Идея включить одинаковое сглаживание на всех операционных системах и во всех браузерах кажется отличной. Но этот подход избыточен, поскольку на устройствах без macOS это свойство не работает.
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +По этой причине стоит прибегать к этому методу точечно, ограничивая область действия. Используем директиву [`@supports`](/css/supports) (в работе) для проверки поддерживается ли нужный нам вариант св
```suggestion
По этой причине стоит прибегать к этому методу точечно, ограничивая область действия. Используем директиву [`@supports`](/css/supports) (в работе) для проверки, поддерживается ли нужный нам вариант свойства конкретным браузером. Если поддерживается, то его и будем применять:
```

2021-07-01 16:55 UTC, tachisis commented on css/font-smoothing/index.md
> +Ниже расположено демо, в котором использован этот код, плюс добавлен разный фон страницы для каждого из условий. Если браузер поддерживает `-webkit-font-smoothing: antialiased` то фон страницы будет
```suggestion
Ниже расположено демо, в котором использован этот код, плюс добавлен разный фон страницы для каждого из условий. Если браузер поддерживает `-webkit-font-smoothing: antialiased`, то фон страницы будет синим. Если поддерживается `-moz-osx-font-smoothing: grayscale`, то фон будет розовым. Если не поддерживается ни одно из этих свойств или значений, то фон будет красным.
```

2021-07-08 18:06 UTC, tachisis approved these changes

2021-07-09 01:33 UTC, pepelsbey commented
@tachisis я сильно дописал и местами переписал, приходи смотреть ещё :)

2021-07-09 07:08 UTC, solarrust reviewed
Очень жаль, что не нашлось места для демки, которая по разному светится в зависимости от поддержки свойства в браузере =(

2021-07-09 07:08 UTC, solarrust commented on css/font-smooth/index.md
> +В этом примере мы меняем сглаживание текста на всей странице. Поскольку свойство `font-smooth` нестандартное, каждый браузер реализовал его по-своему: название свойства примерно одинаковое (за исключ
```suggestion
В этом примере мы меняем сглаживание текста на всей странице. Поскольку свойство `font-smooth` нестандартное, каждый браузер реализовал его по-своему: название свойства примерно одинаковое (за исключением [префиксов](/css/vendor-prefixes) (в работе)), но значения разные. Несмотря на это, иногда можно получить одинаковые результаты.
```

Тут нужно добавить «(в работе)» после ссылки на статью, которой пока нет.

2021-07-09 08:59 UTC, pepelsbey commented
> Очень жаль, что не нашлось места для демки, которая по разному светится в зависимости от поддержки свойства в браузере =(

К сожалению, у неё нет практической пользы: применение этих свойств гораздо более прямолинейное — ты их добавляешь и если браузер поддерживает, то он их применяет. Такова природа свойства, его нет смысла проверять. Но такого рода демки очень пригодятся в других статьях, даже про тот же `@supports`, так что думаю она не пропадёт :)

2021-07-09 13:26 UTC, solarrust commented on css/font-smooth/index.md
> +— `subpixel-antialiased` — включает субпиксельное сглаживания, когда в сглаживании участвуют части пикселей, то есть некоторые лампочки могут не гореть.
```suggestion
- `auto` (по умолчанию) — позволяет браузеру решить, какое сглаживание применять.
- `none` — отключает сглаживание.
- `antialiased` — включает сглаживания оттенками серого, когда в сглаживании участвуют целые пиксели, то есть горят все три лампочки.
- `subpixel-antialiased` — включает субпиксельное сглаживания, когда в сглаживании участвуют части пикселей, то есть некоторые лампочки могут не гореть.
```

2021-07-09 13:26 UTC, solarrust commented on css/font-smooth/index.md
> +— `grayscale` — сглаживает по аналогии со значением `antialiased` для WebKit.
```suggestion
- `grayscale` — сглаживает по аналогии со значением `antialiased` для WebKit.
```

А то буллиты неправильно отрисовываются

2021-07-09 13:37 UTC, solarrust commented
Аппрув (словами потому что я, как автор, не могу зааппркувить свой же ПР)

2021-07-09 13:54 UTC, solarrust commented on css/font-smooth/index.md
> +— `-moz-osx-font-smoothing` для Firefox.
```suggestion
- `-webkit-font-smoothing` для браузеров, идущих от движка WebKit (Safari, Chrome, Opera, Edge);
- `-moz-osx-font-smoothing` для Firefox.
```

2021-07-09 14:19 UTC, pepelsbey commented
@solarrust подождём @tachisis или будем мёржить? :)

2021-07-09 14:20 UTC, solarrust commented
Я бы смёржила и добавила статью в списочек на редактирование

2021-07-09 14:32 UTC, pepelsbey approved these changes

2021-07-09 14:32 UTC, merged