Добавляет статью о созидательных шаблонах проектирования
doka-guide/content pull request #1063
Opened 2021-06-22 08:15 UTC by bespoyasov

Закрывает https://github.com/doka-guide/content/issues/526.

2021-06-23 07:30 UTC, Windrushfarer commented on js/design-patterns-creational/index.md
> +    strings: 6,
Здесь навереное ты хотел передать этот параметр
```suggestion
    strings: stringsCount,
```

2021-06-23 09:33 UTC, bespoyasov commented on js/design-patterns-creational/index.md
> +    strings: 6,
Упс! Верно, спасибо!

2021-06-23 10:36 UTC, Windrushfarer approved these changes

2021-07-04 18:45 UTC, nlopin commented on js/design-patterns-creational/index.md
> +Теперь напишем часть приложения, которая резервирует места и инструменты для каждого музыканта в оркестре.
Я не понял переход. Ок, мы хотим резервировать места и инструменты, ок, написали классы `ViolinReservation` и `CelloReservation`, но что с ними дальше делать? Как их вызывать или использовать?

Картинка «зачем» у меня не сложилась. Думаешь, сможем развернуть?

2021-07-05 09:14 UTC, bespoyasov commented on js/design-patterns-creational/index.md
> +Теперь напишем часть приложения, которая резервирует места и инструменты для каждого музыканта в оркестре.
Я переписал эту часть, добавил деталей. Спасибо!

2021-07-06 12:32 UTC, igsekor requested changes
Очень круто написано!

2021-07-06 12:32 UTC, igsekor commented on js/design-patterns-creational/index.md
> +# Порождающие паттерны проектирования
```suggestion
## Порождающие паттерны проектирования
```

2021-07-06 12:32 UTC, igsekor commented on js/design-patterns-creational/index.md
> +- Фабрика и абстрактная фабрика.
```suggestion
- Фабрика
- Абстрактная фабрика.
```

Наверное, так будет лучше (соответствует структуре статьи и не приводит к неправильному восприятию нижних пунктов этого списка)

2021-07-06 12:36 UTC, bespoyasov commented on js/design-patterns-creational/index.md
> +# Порождающие паттерны проектирования
А зачем второй уровень? Это же название статьи 🤔

2021-07-06 12:40 UTC, igsekor commented on js/design-patterns-creational/index.md
> +# Порождающие паттерны проектирования
Так название же из меты берётся. Наверное, вообще тогда нужно убрать его 😇

2021-07-06 12:41 UTC, bespoyasov commented on js/design-patterns-creational/index.md
> +# Порождающие паттерны проектирования
О, эт тогда надо вообще все мои последние статьи обновить 😃

2021-07-06 12:44 UTC, igsekor commented on js/design-patterns-creational/index.md
> +# Порождающие паттерны проектирования
Да! Вот, что получается в текущей версии: https://doka-guide-content-preview-pr-1063.surge.sh/js/design-patterns-creational/

2021-07-06 12:46 UTC, bespoyasov commented on js/design-patterns-creational/index.md
> +# Порождающие паттерны проектирования
Обновил. Пойду займусь остальными.

2021-07-06 12:48 UTC, igsekor approved these changes
Класс! 👍😎

2021-07-11 07:11 UTC, nlopin approved these changes
Класс!

2021-07-11 07:11 UTC, merged