Рефакторинг работы с данными в Eleventy
doka-guide/content pull request #1083
Opened 2021-06-29 05:23 UTC by monochromer

Этот PR связан с [PR для платформы](https://github.com/doka-guide/platform/pull/221)

2021-06-29 10:59 UTC, furtivite requested changes

2021-06-29 10:59 UTC, furtivite commented on css/active/practice/solarrust.md
>  ---
```markdown
---
---
```

Может в практиках совсем мету удалим?

2021-06-29 11:01 UTC, monochromer commented on css/active/practice/solarrust.md
>  ---
Да, можно. "Скобки" остались после прогона скрипта

2021-06-30 07:12 UTC, furtivite approved these changes

2021-06-30 08:33 UTC, pepelsbey approved these changes

2021-07-02 08:25 UTC, solarrust approved these changes

2021-07-02 08:50 UTC, merged