Добавляет action для создания/обновления data-файлов с статей
doka-guide/content pull request #1097
Opened 2021-07-05 10:47 UTC by monochromer

PR связан с [задачей вывода даты последнего редактирования статьи](https://github.com/doka-guide/platform/issues/232)

2021-07-05 11:17 UTC, nlopin approved these changes

2021-07-05 11:48 UTC, igsekor requested changes
Надо бы подправить почту. Кажется, что всё остальное должно работать.

Не мешало бы проверить Action, изменив ветку на `feature/update-field`. Попробуем?

2021-07-05 11:48 UTC, igsekor commented on .github/workflows/updated-at-field.yml
> +          commit_author: Doka Dog <feedback@y-doka.site>
```suggestion
          commit_user_email: hi@doka.guide
          commit_author: Doka Dog <hi@doka.guide>
```

2021-07-05 21:42 UTC, pepelsbey commented on .github/workflows/updated-at-field.yml
> +          token: ${{ secrets.DOKA_BOT_ACCESS_TOKEN }}
```suggestion
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOKA_BOT_ACCESS_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
```

Удивился, что мы используем `node`, но нигде не делаем `actions/setup-node`, что как будто необходимо для такого. Плюс я убрал `strategy.matrix.node-version` просто в строку.

2021-07-06 12:41 UTC, pepelsbey approved these changes

2021-07-06 13:01 UTC, furtivite approved these changes

2021-07-06 14:03 UTC, pepelsbey commented
@igsekor ждём твоего ока :)

2021-07-06 14:06 UTC, igsekor approved these changes
Да будет ок 🙃

2021-07-06 14:29 UTC, merged

2021-07-06 16:38 UTC, monochromer commented
Там еще надо было изменить поле `file_pattern` на `./**/index.11tydata.json`. Не доглядел.

2021-07-06 20:52 UTC, pepelsbey commented
@monochromer ждём второй части ПР :)