Статья по XML
doka-guide/content pull request #1103
Opened 2021-07-05 19:38 UTC by KognitivnayaBuena

2021-07-06 07:46 UTC, Windrushfarer reviewed
Лаконично, но все по делу 👍

Я бы еще в раздел "В работе" добавил несколько строчек про SVG. Это как раз формат который описывает графику в XML-формате.

2021-07-06 07:46 UTC, Windrushfarer commented on js/xml/index.md
> +Не правильный вариант тега. Если не закрыть тег, вся сила утекает из кода.
```suggestion
Неправильный вариант тега. Если не закрыть тег, вся сила утекает из кода.
```

Я тут не понял насчет утекающей силы :) Понимаю что имеется ввиду, но кажется метафора слишком размытая

2021-07-06 11:18 UTC, bespoyasov reviewed
Отлично, докинем деталей и можно в прод.

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +Строка с которой может начинаться любой XML документ — это пролог, который обозначает с какой версией документа происходит работа. Пролог показывает его версию и кодировку, которую мы используем.
```suggestion
Строка с которой может начинаться любой XML документ — это пролог, который обозначает, с какой версией документа мы работаем. Пролог показывает его версию и кодировку, которую мы используем.
```

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +Из знакомого нам варианта - указатель `<!DOCTYPE html>`. Данный пролог используется в файлах формата `*.html`.
Можно превратить в callout :–)

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +Основное правило для написания XML документа - всегда закрывай теги.
Согласно [руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md#стиль-доки), на «ты» обращаемся только в разделе «В работе», в остальных местах — на «вы».

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +Основное правило для написания XML документа - всегда закрывай теги.
```suggestion
Основное правило для написания XML документа - всегда закрывайте теги.
```

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +Документ состоит из разных сущностей, которые состоят из символов. Данные символы разделены на символы разметки и символы данных. К символам разметки, они же символы структуры документа, относятся:
Попробуем представить это в виде изображения? Как в [доке о `window.location`](https://github.com/doka-guide/content/pull/816#issuecomment-859526043).

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +Теги обозначают границы элементов. Теги могут содержать в себе текст, другие атрибуты или элементы или их сочетание. Например определим сущность `petstore` - магазин домашних любимцев. В нем у нас ес
```suggestion
Теги обозначают границы элементов. Они могут содержать в себе текст, другие теги, атрибуты или их сочетание. Например, определим сущность `petstore` — магазин домашних любимцев. В нём у нас есть несколько видов животных — `pet`. Эти два тега содержат в себе дочерние элементы — тоже теги. 

У каждого питомца мы определили разделение на вид атрибутом `category`. У нас есть катерогии: cat, dog, fish. Дополнителная информация о питомце содержится в тегах `name`, `year`, `price`. В них определено текстовое значение, даже цена в формате `485.00`.
```

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +Так как в XML мы сами определям имена для тегов, то есть вероятность возникновения конфликта имен. Если мы определим таблицу в XML тегами из HTML, то будет коллизия имен. Первый XML-код содержит инфо
```suggestion
Так как в XML мы сами определям имена для тегов, то есть вероятность возникновения конфликта имен. Если мы определим таблицу в XML тегами из HTML, то возникнет конфликт. Первый XML-код содержит информацию таблицы HTML, второй — описание кота. Если эти два фрагмента кода были сложены вместе, то возник бы конфликт имён. Они оба определены тегом `table`, но у них разное содержание. XML не знает как подружить эти разные структуры.
```

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +Можно разрешить эту проблему, если определить пространство имен. Для двух этих таблиц нужно добавить атрибут `xmlns` с указанием урла на документ с пространством имен. Нельзя задавать ссылку на локал
Давай расскажем, как работает указанный URL? Какие ограничения он добавит, какие преимущества?

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/index.md
> +  <classic:table xmlns:classic="https://www.w3.org/TR/html51/">
Думаю, стоит пояснить, откуда мы взяли `classic`, потому что выше мы говорили лишь о `xmlns` — будет легко потеряться.

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/practice/KognitivnayaBuena.md
> +- XML был разработан для передачи данных, а не для отображения этих данных.
Здесь можно указать ссылку на [статью об API](https://doka.guide/js/api/#soap).

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/practice/KognitivnayaBuena.md
> +- XML упрощает процесс смены платформы.
Я бы добавил, при каких обстоятельствах нам может понадобиться менять платформу. То есть как его можно использовать в этот момент.

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/practice/KognitivnayaBuena.md
> +- Не дает возможности пользователю создавать свои теги
Добавим [точки в концах пунктов списков](https://github.com/doka-guide/content/blob/main/docs/typography.md)?

2021-07-06 11:18 UTC, bespoyasov commented on js/xml/practice/KognitivnayaBuena.md
> +## Пример
Добавим пояснений? Небольшого абзаца будет вполне достаточно. (Я тут руководствуюсь принципом «Взгляда новичка»: если я открою страницу сразу на этом разделе, то смогу ли найти и понять сразу всё, что в этом разделе есть.)

2021-07-11 07:01 UTC, nlopin commented
@KognitivnayaBuena нужна ли тут помощь?

2021-07-12 09:27 UTC, bespoyasov approved these changes
Перечитал статью, добавил одну идею для улучшения, а в остальном — хорошо! 👍

2021-07-12 09:27 UTC, bespoyasov commented on js/xml/index.md
> +Так как в XML мы сами определяем имена для тегов, то есть вероятность возникновения конфликта имён. Если мы определим таблицу в XML тегами из HTML, то возникнет конфликт. Первый XML-код содержит инфо
Мне кажется, не хватает описания, что произойдёт, если XML не сможет их подружить: «всё сломается», «я не вижу в результате одну из таблиц», «всё будет нормально, но какие-то парсеры не смогут с этим работать». 

То есть хочется видеть масштаб проблемы, с которой имеем дело. Тогда будет мотивация использовать `xmlns` для решения и не забывать о нём.

2021-07-12 10:28 UTC, pepelsbey commented on js/xml/index.md
> +Так как в XML мы сами определяем имена для тегов, то есть вероятность возникновения конфликта имён. Если мы определим таблицу в XML тегами из HTML, то возникнет конфликт. Первый XML-код содержит инфо
Есть хороший пример: если отдать в браузер SVG-файл без `xmlns`, то он его не отобразит. SVG как строгий XML — очень понятный пример для фронтендеров.

2021-07-13 11:24 UTC, pepelsbey commented
@KognitivnayaBuena это интересный ход, но лучше так не надо — затёрлись мои правки в словарь и в тексте снова опечатки.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/105274/125443728-3c0c687e-2feb-4490-9da4-dea959b77381.png">

2021-07-14 12:48 UTC, nlopin commented on tools/xml/index.md
> +XML (Extensible Markup Language) — расширяемый язык разметки. По структуре напоминает HTML. XML отличается тем, что теги для разметки разработчик должен определять самостоятельно.
Давай тут ещё напишем, что его основной сценарий использования — обмен данными между системами

2021-07-14 12:48 UTC, nlopin commented on tools/xml/practice/KognitivnayaBuena.md
> +- Необходимо приложение для данных от XML.
Можешь развернуть, я не понял, что имеется ввиду

2021-07-14 12:49 UTC, nlopin commented on tools/xml/practice/KognitivnayaBuena.md
> +## XML vs HTML
Очень хочется сравнивать с JSON, потому что они решают одинаковые задачи

2021-07-14 12:49 UTC, nlopin commented on tools/xml/practice/KognitivnayaBuena.md
> +- Не даёт возможности пользователю создавать свои теги.
я бы тут ещё добавил, что он очень многословный, нужно писать много текста по сравнению с JSON

2021-07-15 08:12 UTC, nlopin approved these changes

2021-07-15 08:12 UTC, nlopin commented
Ждём Олю

2021-07-15 09:29 UTC, pepelsbey requested changes

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +Из знакомого нам — указатель [`<!DOCTYPE html>`](/html/doctype). Такой пролог используется в файлах формата _html_.
```suggestion
Из знакомого нам — указатель [`<!DOCTYPE html>`](/html/doctype). Такой пролог используется в файлах формата HTML.
```

Думаю, лучше дать название языка, чем отдалённый намёр на расширение файла.

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +```
````suggestion
Основное правило для написания XML-документа — всегда закрывайте теги. Даже одиночные!

Правильно закрытые теги:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<cat>Борись и не сдавайся!</cat>
<dog />
```

Если не закрыть тег, вся сила утекает из кода, и обработка выдаст ошибку:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<cat>Энергия кота Бориса утекает от нас
<dog>
```
````

Стоит упомянуть и одиночные теги.

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +### Теги (tags)
```suggestion
### Теги
```

Кажется это уже настолько понятное всем слово, что приводить оригинальное написание смысла нет.

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +Теги обозначают границы элементов. Одни могут содержать в себе текст, другие — теги, атрибуты или их сочетание. Например, определим сущность `petstore` для магазина домашних любимцев. В нём у нас ест
```suggestion
Теги обозначают границы элементов. Одни могут содержать в себе текст, другие — теги, атрибуты или их сочетание. Например, определим сущность `<petstore>` для магазина домашних любимцев. В нём у нас есть несколько видов животных — `<pet>`. Эти два тега содержат в себе дочерние элементы — тоже теги.
```

Угловые скобки помогают отличать теги от атрибутов.

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +У каждого питомца мы определили его вид с помощью атрибута `category`. У нас есть категории: `cat`, `dog`, `fish`. Дополнительная информация о питомце содержится в тегах `name`, `year`, `price`:
```suggestion
У каждого питомца мы определили его вид с помощью атрибута `category`. У нас есть категории: `cat`, `dog`, `fish`. Дополнительная информация о питомце содержится в тегах `<name>`, `<year>`, `<price>`:
```

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +Атрибуты используются для метаинформации. В основном, это различные свойства и идентификаторы. Данные содержатся в тегах.
```suggestion
::: callout ☝️

Атрибуты используются для метаинформации. В основном, это различные свойства и идентификаторы. Данные содержатся в тегах.

:::
```

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +<pet category='dog "corgi"'>
```suggestion
<pet category="cat" />
<pet category='dog' />
<pet category='dog "corgi"' />
```

А то невалидный XML :)

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +Так как в XML мы сами определяем имена для тегов, то есть вероятность возникновения конфликта имён. Если мы определим таблицу в XML тегами из HTML, то возникнет конфликт. Первый XML-код содержит инфо
```suggestion
Так как в XML мы сами определяем имена для тегов, то есть вероятность возникновения конфликта имён. Если мы определим таблицу в XML тегами из HTML, то возникнет конфликт. Первый XML-код содержит информацию таблицы HTML, второй — описание кота. Если эти два фрагмента кода были сложены вместе, то возник бы конфликт имён. Они оба определены тегом `<table>`, но у них разное содержание. XML не знает как подружить эти разные структуры.
```

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +    <tr>Элемент 3</tr>
```suggestion
    <tr>
      <td>Элемент 1</td>
      <td>Элемент 2</td>
      <td>Элемент 3</td>
    </tr>
```

Лучше показать настоящую таблицу, там нужна другая структура тегов

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +  <table xmlns="https://www.w3.org/TR/html51/" />
```suggestion
<table xmlns="https://www.w3.org/TR/html51/" />
```

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +  <cat />
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
<cat></cat>
<cat />
```

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +  </petstore>
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
<petstore>
  <pet category="cat">
    <name>Борис</name>
    <year>2021</year>
    <price>485.00</price>
  </pet>
  <pet category="dog">
    <name>Плуто</name>
    <year>2020</year>
    <price>2999.99</price>
  </pet>
  <pet category="fish">
    <name>Нэмо</name>
    <year>2021</year>
    <price>100.50</price>
  </pet>
</petstore>
```

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +  </root>
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <tree>
    <leaf>Тут лежит листик</leaf>
    <leaf>Тут лежит листик</leaf>
  </tree>
</root>
```

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/index.md
> +</root>
Этот XML сломан, если открыть в браузере:

```
XML Parsing Error: mismatched tag. Expected: </classic:th>.
Location: file:///Users/pepelsbey/Desktop/index.xml
Line Number 3, Column 28:
    <classic:th>Элемент 1</th>
---------------------------^
```

Плюс не объясняется нотация тегов с через двоеточия: почему `classic:table`, а не `classicTable`?

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- Не даёт возможности пользователю создавать свои теги.
В начале написано

> XML отличается тем, что теги для разметки разработчик должен определять самостоятельно

А тут такое. Я понимаю, что фокус на «пользователя», но не до конца понятно

2021-07-15 09:29 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +  </film>
```suggestion
<film>
  <name>Шрэк</name>
  <description>
    мультфильм, фэнтези, комедия, приключения, семейный
  </description>
  <creationYear>2001</creationYear>
  <butget>60 000 000 $</butget>
</film>
```

2021-07-15 20:56 UTC, pepelsbey commented on tools/xml/index.md
> +После введения атрибута `xmlns` код будет обрабатываться и выглядеть так:
```suggestion
Определим два пространства имён с помощью `xmlns` для разных таблиц: `classic` и `catName`, чтобы из XML можно было корректно считать данные. Пространства определены в ссылках, поэтому наименование строгое и должно соответствовать определению.

После введения атрибута `xmlns` код будет обрабатываться и выглядеть так:
```

Уточняет про XML и разделяет параграфы

2021-07-15 20:57 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +  <butget>60 000 000 $</butget>
```suggestion
  <budget>60 000 000 $</budget>
```

2021-07-15 21:07 UTC, tachisis approved these changes
Апрув на словарь

2021-07-15 21:10 UTC, pepelsbey requested changes

2021-07-15 21:10 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- XML - это расширяемый язык разметки, такой как HTML.
```suggestion
- XML - это расширяемый язык разметки, похожий как HTML.
```
Иначе создаётся впечатление, что HTML тоже расширяемый

2021-07-15 21:10 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- Это простой язык разметки, поддерживающий создание веб-страниц.
```suggestion
- Это простой язык разметки, который выводится в браузерах со стилями по умолчанию.
```
Уточнил пользу, вместо абстрактного «поддерживает создание»

2021-07-15 21:10 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- Гибкий, чтобы поддерживать гипертекстовые ссылки.
```suggestion
- Поддерживает переходы между документами с помощью [гиперссылок](/html/a).
```

2021-07-15 21:10 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- Достаточно обширный, чтобы обеспечить поддержку встраивания мультимедиа в документы.
А вот тут я не понял (

2021-07-15 21:10 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- Достаточно обширный, чтобы обеспечить поддержку встраивания мультимедиа в документы.
```suggestion
- Достаточно обширный, чтобы обеспечить поддержку встраивания мультимедиа в документы.
- В отличие от XML и JSON, браузеры при обработке прощают ошибки и чинят их стандартным образом.
```

2021-07-15 21:10 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- XML отделяет данные от HTML.
Непонятно (

2021-07-15 21:10 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- XML упрощает процесс смены платформы.
Хотелось бы кратко объяснить, как именно.

2021-07-15 21:10 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +- Многословнее чем, например, JSON, придётся написать больше текста.
```suggestion
- Многословнее чем, например, JSON, придётся писать много открывающих и закрывающих тегов.
```
Уточнил, что многословность не в тексте, а в тегах, чтобы не путалось с контентом

2021-07-19 09:55 UTC, pepelsbey requested changes

2021-07-19 09:55 UTC, pepelsbey commented on tools/xml/index.md
> +</root>
Этот XML всё ещё сломан. Закрывающий тег тоже должен быть с неймспейсом:

```xml
<classic:th>Элемент 1</classic:th>
<classic:tr>Элемент 2</classic:tr>
<classic:tr>Элемент 3</classic:tr>
```

2021-07-19 09:55 UTC, pepelsbey commented on tools/xml/index.md
> +После введения атрибута `xmlns` код будет обрабатываться и выглядеть так:
«Выглядит так» кажется недостаточным объяснением, лучше бы сказать, что к тегам нужно добавить префикс с двоеточием. Иначе приходится догадываться, сравнивая имя неймспейса с неожиданными новыми тегами.

2021-07-19 09:55 UTC, pepelsbey commented on tools/xml/index.md
> +</root>
Также здесь стоит воспроизвести корректную таблицу, которую мы сделали выше. Можно и там, и здесь сделать компактнее, всего с двумя строчками.

2021-07-19 09:55 UTC, pepelsbey commented on tools/xml/practice/KognitivnayaBuena.md
> +<?xml version = "1.0">
```suggestion
<?xml version="1.0" encoding="UTF-8"?>
```
Раз уж пишем такой пролог в начале, стоит его сохранить и до конца

2021-07-19 20:27 UTC, pepelsbey approved these changes

2021-07-19 20:36 UTC, merged

2021-07-19 20:36 UTC, pepelsbey commented
Красота!