React и альтернатив
doka-guide/content pull request #1106
Opened 2021-07-06 09:52 UTC by Windrushfarer

Closes #319

2021-07-06 11:37 UTC, bespoyasov reviewed
Круто! Я узнал много нового 😃 

Ещё, думаю, стоит добавить что-то типа заключения. Можно привести сравнение лоб-в-лоб этих фреймворков, у кого что под капотом, что где легче, как они по производительности и т. д. 

А в остальном статья огонь!

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +На текущий момент в мире фронтенда существует множество различных фреймворков для разработки SPA. Большинство из них различаются подходами к разработке и инструментами, которыми они обладают. Но в ос
```suggestion
В мире фронтенда много различных фреймворков для разработки SPA. Большинство из них различаются подходами к разработке и инструментами, которыми они обладают. Но в основе всех этих фреймворков часто лежат одни и те же концепции. Эти концепции и различия в подходах мы рассмотрим в этой статье.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +На текущий момент в мире фронтенда существует множество различных фреймворков для разработки SPA. Большинство из них различаются подходами к разработке и инструментами, которыми они обладают. Но в ос
Расшифруем SPA в первый раз?

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Virtual DOM – объект, который хранит структуру дерева компонентов и их текущее состояние.
Как-то резко сразу в виртуал дом 😃 
Давай добавим какое-нибудь введение аккуратное? 1-2 предложения не больше.

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +React использует Virtual DOM для отслеживания изменений. После каждого изменения состояния, React создаёт новый Virtual DOM и сравнивает его с предыдущем, чтобы узнать какие части приложения изменили
```suggestion
React использует Virtual DOM для отслеживания изменений. После каждого изменения состояния, React создаёт новый Virtual DOM и сравнивает его с предыдущим, чтобы узнать какие части приложения изменились.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Angular не использует Virtual DOM, но патчит браузерный DOM API, чтобы иметь возможность следить из изменением данных. Таким образом, если пользователь взаимодействует со страницей, то Angular провер
Объясним термин «патчить»?

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Все фреймворки стараются следовать принципам [реактивности](/js/reactivity/), но используют разные способы, чтобы организовать её. Различия кроются в том, как фреймворк отслеживает изменения и как пр
Хм, тут бы пояснить, что они стараются сделать реактивным интерфейс, но вот в основе них не всегда реактивность?

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +В React каждое приложение (или отдельные компоненты) имеет состояние. Состояние это данные, за которыми React следит. У React [однонаправленный поток данных](/js/architecture-data-flow) и он предоста
```suggestion
В React каждое приложение (или отдельные компоненты) имеет состояние. Состояние — это данные, за которыми React следит. У React [однонаправленный поток данных](/js/architecture-data-flow) и он предоставляет специальный API для обновления состояния. 

Когда в приложении необходимо обновить состояние, разработчик вызывает функцию для установки нового значения. Благодаря этому API React знает когда начинать перерисовку, потому что реагирует на его вызовы. Такой подход по сути является pull-реактивностью, так как мы явно даём знать React, что данные изменились, но фреймворк сам решит в какой момент времени нужно обновить подписчиков.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Главная особенность React – это Virtual DOM. Когда React только появился это было его главным нововведением. Вся логика отображения, выявления изменений и обновление браузерного DOM строится вокруг V
```suggestion
Главная особенность React – это Virtual DOM. Когда React только появился, это было его главным нововведением. Вся логика отображения, выявления изменений и обновление браузерного DOM строится вокруг Virtual DOM.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Главная особенность React – это Virtual DOM. Когда React только появился это было его главным нововведением. Вся логика отображения, выявления изменений и обновление браузерного DOM строится вокруг V
Можно сделать балдёж и добавить год появления и ссылку на самый первый пост в документации. Но это так, не обязательно 🙂

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Virtual DOM – это легковесный объект, которое описывает собой структуру React-приложения. Объект Virtual DOM сопоставляет дерево компонентов в браузерное [DOM-дерево](/js/dom/). Таким образом React з
```suggestion
Virtual DOM – это легковесный объект, который описывает структуру React-приложения. Объект Virtual DOM сопоставляет дерево компонентов в браузерное [DOM-дерево](/js/dom/). Таким образом React знает, какой компонент соответствует определённым элементам на странице. Это дерево хранится в памяти и обновляется каждый раз в соответствии с изменениями.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Virtual DOM – это легковесный объект, которое описывает собой структуру React-приложения. Объект Virtual DOM сопоставляет дерево компонентов в браузерное [DOM-дерево](/js/dom/). Таким образом React з
(Тут бы добавить в соответствии с какими изменениями или изменениями чего.)

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Когда происходит изменение в приложении (к примеру поменялось состояние), React запускает алгоритм сравнения двух Virtual DOM: старого и нового. Он рекурсивно проходит по всему дереву и пытается найт
```suggestion
Когда происходит изменение в приложении (к примеру поменялось состояние), React запускает алгоритм сравнения двух Virtual DOM: старого и нового. Он [рекурсивно](/js/recursion/) проходит по всему дереву и пытается найти отличия в их структуре. Если различия найдены, то DOM в браузере обновится соответственно. Все это происходит в реальном времени, но работает очень быстро, поэтому пользователь не видит никаких задержек.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Стоит помнить, что факт обновления браузерного DOM не значит, что элементы будут удалятся и создаваться заново (кроме явных случаев). React будут стараться сохранить элемент на странице и производить
```suggestion
Стоит помнить, что факт обновления браузерного DOM не значит, что элементы будут удаляться и создаваться заново, кроме случаев, когда их действительно удалили или добавили. React будет стараться сохранить как можно больше элементов на странице и производить только точечные изменения.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Virtual DOM существует и работает только в рантайме, то есть во время выполнения программы и все своё состояние он хранит в памяти. Большие приложения могут создавать очень большие деревья, а многочи
```suggestion
Virtual DOM существует и работает только в рантайме, то есть во время выполнения программы, и все своё состояние он хранит в памяти. Большие приложения могут создавать очень большие деревья, а многочисленные изменения будут приводить к многократным пересозданиям отдельных поддеревьев и их проверкам с предыдущей версией. Все эти факторы влияют на производительность — чем больше дерево, тем больше работы придётся сделать после его изменений.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Angular, чтобы связывать данные приложения и отображение, использует HTML-подобный синтаксис для своих шаблонов и компилирует эти шаблоны набор инструкций, которые создают браузерные DOM-элементы. An
```suggestion
Angular, чтобы связывать данные приложения и отображение, использует HTML-подобный синтаксис для своих шаблонов и компилирует эти шаблоны в набор инструкций, которые создают браузерные DOM-элементы. Angular не использует Virtual DOM, чтобы хранить дерево компонентов в памяти.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Стандартный механизм обнаружения изменения довольно простой: Angular рекурсивно проходит по дереву компонентов и для каждого выражения, используемого в шаблоне, он сравнивает текущее значение с преды
Стандартный — это который `default` или `onPush`? 🙃

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Стратегия `onPush` заменяет механизм обнаружения изменения. Теперь компонент обновляется только если меняются входные данные, аналогично как работают props в React компонентах. Когда входные данные к
```suggestion
Стратегия `onPush` заменяет механизм обнаружения изменения. При ней компонент обновляется, только если меняются входные данные — примерно как работают props в React компонентах. Когда входные данные компонента изменяются, Angular пройдётся по всему поддереву и обновит дочерние элементы.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Обе стратегии обновления могут использоваться одновременно и часто `onPush` применяют для оптимизации высоконагруженных частей приложения.
🔥

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Помимо отслеживание свойств объектов Vue оборачивает функции в *эффекты*. Эффект – это обёртка вокруг функции, которая формирует порядок вызова и следит какую функцию нужно вызвать.
```suggestion
Vue не только отслеживает свойства объектов, но и оборачивает функции в *эффекты*. Эффект – это обёртка вокруг функции, которая формирует порядок вызова и следит какую функцию нужно вызвать.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +// Обертка, создаяющий эффекты
```suggestion
// Обёртка, создающая эффекты
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Пример выше это приближенный пример как работают эффекты в Vue.
```suggestion
Пример выше — это приближенный пример как работают эффекты в Vue.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Для обновления DOM в браузере Vue тоже использует Virtual DOM. Vue использует свой синтаксис шаблонов похожий на Angular, но при компиляции приложения эти шаблоны преобразуются в вызовы render-функци
```suggestion
Для обновления DOM в браузере Vue тоже использует Virtual DOM. Vue использует свой синтаксис шаблонов, похожий на Angular, но при компиляции приложения эти шаблоны преобразуются в вызовы render-функций, создающих Virtual DOM. Алгоритм обхода и свойства объекта в Virtual DOM во Vue отличаются от React, но основные подходы очень похожи.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Svelte отличаются от других фреймворков тем, что функции для отслеживания изменений формируются во время компиляции приложения.
```suggestion
Svelte отличается от других фреймворков тем, что функции для отслеживания изменений формируются во время компиляции приложения.
```

2021-07-06 11:37 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Svelte имеет свой язык шаблонов как Angular или Vue и благодаря ему компилятор умеет просчитывать все зависимости заранее. В итоге Svelte сформирует набор функций, которая следят только за определённ
```suggestion
Svelte имеет свой язык шаблонов, как Angular или Vue, и благодаря ему компилятор умеет просчитывать все зависимости заранее. В итоге Svelte сформирует набор функций, которые следят только за определёнными значениями и обновляют DOM при их изменениях. Это быстрее подхода Virtual DOM, так как не нужно проверять все дерево, чтобы узнать где произошли изменения, и не нужно хранить все дерево компонентов в памяти.
```

2021-07-06 11:39 UTC, Windrushfarer commented on js/react-and-alternatives/index.md
> +Virtual DOM – объект, который хранит структуру дерева компонентов и их текущее состояние.
Думаю ты прав, я просто решил сразу его описать, чтобы у читателя на было вопросов пока он читает краткое описание по фреймворкам :)

2021-07-06 12:01 UTC, igsekor requested changes
По содержанию статейка очень понравилась! 👍

2021-07-06 12:01 UTC, igsekor commented on js/react-and-alternatives/index.md
> +Код выше это небольшая часть того, что скомпилирует Svelte. Здесь видно как в изначальную функцию добавилась специальная функция `$$invalidate`, которая пометит, что данные изменились и запланирует о
```suggestion
Код выше это небольшая часть того, что скомпилировал Svelte. Здесь видно, как в изначальную функцию добавилась специальная функция `$$invalidate`, которая пометила, что данные изменились, и тем самым запланировала обновление DOM-элемента, где используется это значение.
```

2021-07-07 13:15 UTC, tachisis approved these changes
Апрув на изменения в словаре

2021-07-08 17:13 UTC, Windrushfarer commented on js/react-and-alternatives/index.md
> +На текущий момент в мире фронтенда существует множество различных фреймворков для разработки SPA. Большинство из них различаются подходами к разработке и инструментами, которыми они обладают. Но в ос
Добавлю ссылку лучше и напишу по-русски :)

2021-07-08 17:31 UTC, Windrushfarer commented on js/react-and-alternatives/index.md
> +Стандартный механизм обнаружения изменения довольно простой: Angular рекурсивно проходит по дереву компонентов и для каждого выражения, используемого в шаблоне, он сравнивает текущее значение с преды
И правда, спасибо что указал на это. По тексту неочевидно сразу.

2021-07-08 18:26 UTC, Windrushfarer commented on js/react-and-alternatives/index.md
> +Главная особенность React – это Virtual DOM. Когда React только появился это было его главным нововведением. Вся логика отображения, выявления изменений и обновление браузерного DOM строится вокруг V
Уф, такое тяжело найти что-то

2021-07-08 18:27 UTC, Windrushfarer commented on js/react-and-alternatives/index.md
> +Virtual DOM – объект, который хранит структуру дерева компонентов и их текущее состояние.
Ссылка в разделе, где рассказывается про Virtual DOM :)

2021-07-09 09:20 UTC, bespoyasov approved these changes

2021-07-09 09:20 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +В React каждое приложение (или отдельные компоненты) имеет состояние. Состояние — это данные, за которыми React следит. У React [однонаправленный поток данных](/js/architecture-data-flow) и он предос
```suggestion
В React каждое приложение (или отдельные компоненты) имеет состояние. Состояние — это данные, за которыми React следит. У React [однонаправленный поток данных](/js/architecture-data-flow), и он предоставляет специальный API для обновления состояния.
```

2021-07-09 09:20 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Virtual DOM подход в React и Vue помогает держать актуальное состояние приложения прямо в памяти. Потому можно быстро находить изменения, путём сравнения двух версий. Но большие приложения будут зани
```suggestion
Virtual DOM используется в React и Vue помогает держать актуальное состояние приложения прямо в памяти. Он позволяет быстро находить изменения, путём сравнения двух версий. Большие приложения будут занимать много места в памяти, а частые обновления будут занимать больше времени.
```

2021-07-09 09:20 UTC, bespoyasov commented on js/react-and-alternatives/index.md
> +Svelte является уникальным в плане того, что формирует код, который будет отслеживать изменения, во время сборки приложения. В итоге получается только необходимый для приложения код.
```suggestion
Svelte уникален тем, что формирует код, который будет отслеживать изменения, во время сборки приложения. В итоге получается только необходимый для приложения код.
```

2021-07-12 09:03 UTC, nlopin commented on js/react-and-alternatives/index.md
> +### Virtual DOM
давай сделаем раздел про виртуальный дом общим. Мы с самого начала делим фреймворки по наличию/отсутствию virtual dom, но что это такое объясняем одним предложением. Хочется развернуть, чтобы к обсуждению конкретных фреймворков человек приходил с пониманием что такое виртуальный дом

2021-07-14 06:59 UTC, bespoyasov approved these changes

2021-07-14 08:25 UTC, merged