Переносит статью про Node.js
doka-guide/content pull request #1114
Opened 2021-07-07 09:48 UTC by furtivite

Кажется, забыли статью. Это последняя.

2021-07-07 10:00 UTC, pepelsbey requested changes

2021-07-07 10:00 UTC, pepelsbey commented on tools/nodejs-tooling/index.md
> +```
Прелагаю писать тексты не в коде, а рядом. Здесь очевидно есть нарратив, который зажимается в комментарии, которые неудобно читать.

````suggestion
В таком скрипте много кода, но для понимания принципа работы Node.js-инструментов можно его упростить и посмотреть на принципиальную схему. Это не настоящий ESLint, а просто пример того, как может быть устроен скрипт на Node.js:

```js
const cliOptions = parseCommandLineArguments(process.args)
const configOptions = parseConfigFile(".eslintrs")
const options = mergeConfigs([cliOptions, configOptions])
const files = findFiles(options)
const errors = analyzeFiles(files, options)

for (const error of errors) {
  console.warn(error)
}

if (errors.length > 0) {
  process.exit(1)
} else {
  process.exit(0)
}
```

А теперь разберём его построчно. Получаем аргументы командной строки, чтобы найти файлы которые следует анализировать:

```js
const cliOptions = parseCommandLineArguments(process.args)
```

Читаем файл конфигурации, чтобы решить какие правила анализа нужно применить:

```js
const configOptions = parseConfigFile(".eslintrs")
```

Собираем финальную конфигурацию:

```js
const options = mergeConfigs([cliOptions, configOptions])
```

Находим все файлы, удовлетворящие условию:

```js
const files = findFiles(options)
```

Ищем нарушения правил в каждом файле и пишем о них в консоль:

```js
const errors = analyzeFiles(files, options)

for (const error of errors) {
  console.warn(error)
}
```

Если была найдена хоть одна ошибка, завершаем выполнение с кодом 1. Если ошибок не было, завершаем выполнение с кодом 0:

```js
if (errors.length > 0) {
  process.exit(1)
} else {
  process.exit(0)
}
```
````

2021-07-07 13:19 UTC, tachisis approved these changes
Апрув на изменения в словаре

2021-07-08 08:59 UTC, furtivite commented on tools/nodejs-tooling/index.md
> +```
@nlopin посмотри, пожалуйста.

2021-07-09 09:09 UTC, bespoyasov approved these changes
👍

2021-07-09 09:59 UTC, nlopin approved these changes

2021-07-09 10:01 UTC, merged