article/cryptography
doka-guide/content pull request #1119
Opened 2021-07-07 11:47 UTC by igsekor

Статья освящает темы, согласно #734 и #906.

2021-07-07 13:20 UTC, tachisis approved these changes
Апрув на изменения в словаре

2021-07-07 13:23 UTC, bespoyasov reviewed
Классная статья, всё по делу! 👍 

Давай расскажем про устойчивость шифров: что это, как определяется, как сравнивать по ней шифры между собой и т. д.?

И ещё можно добавить заключение: для каких задач больше подходит симметричное, асимметричное шифрование; когда использовать обратимые шифры, а когда необратимые 😇

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +Шифрование — это способ защитить данные от постороннего взгляда (несанкционированного доступа). Можно положить секретные документы в сундук под замок, и только обладатель ключа сможет добраться до ни
А давай попробуем немного логику вывернуть?

«Шифрование — это способ... с помощью шифра. Шифр — набор действий и операций... для сокрытия. Это можно сравнить с секретными документами в сундуке...»

Мне кажется, что так будет немного последовательнее и проще читать.

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +Интернет (ARPANET) был создан как компьютерная сеть передачи данных военного назначения. Удивительно, но сама по себе сеть Интернет не содержит никаких специальных возможностей для шифрования данных.
```suggestion
Интернет (ARPANET) был создан как компьютерная сеть передачи данных военного назначения. Удивительно, но интернет сам по себе не содержит никаких специальных возможностей для шифрования данных. Вся ответственность и нагрузка по передаче конфиденциальных данных лежит на плечах пользователей сети. Так, письма, веб-страницы, данные пользователей, документы на протяжении большого времени передавались в открытом виде, чем активно пользовались злоумышленники. Только в последние годы ситуация начала меняться.
```

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +Идея симметричного шифрования крайне проста — использование одного и того же ключа для шифрования и дешифровки. Такое шифрование широко применялось в древних и средневековых государствах ([Атбаш](htt
Давай добавим пример с шифром Цезаря? Покажем, что на входе, какой ключ, что на выходе — чтобы было видно, как работает шифрация и дешифрация.

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +- сложность реализации процедуры обмена ключами.
Ещё можно сказать, что зашифрованное сообщение неустойчиво к структурному анализу: если в языке большую часть занимает конкретное слово (the), то на выходе мы получим сообщение, в котором будет часто повторяться одинаковая последовательность символов (rpy) — по которой можно взломать ключ.

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +Ассиметричное шифрование — это использование разных ключей для шифрования и дешифровки. Представьте такой замок, закрыть который можно одним ключом, а открыть — другим. Разновидностью ассиметричного
Можно в коллауте привести пример с RSA, что думаешь? 🤔

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +- нет необходимости предварительно передавать секретный ключ;
А стоит ли про End-to-End шифрование упомянуть? 🤔 

Я просто думаю, если да, то тогда надо будет рассказать про алгоритмы обмена или использования общего секретного ключа (тот же Диффи-Хелман, к примеру).

Но, возможно, это лишнее.

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +- ключи большей длинны;
Либо ключи длиннее, либо количество операций выше. (У [ChaCha](https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant) вроде не очень длинные ключи, но он очень устойчив. Ну... пока рано говорить с полной уверенностью, но всё же 😃)

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +- не повторяться для разных данных (только один пароль может аутентифицировать одного и того же пользователя).
И вроде ещё разные шифруемые данные должны превращаться в строки одинаковой длины. Или я путаю?

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +- существенно отличаться для близких по значению данных (для паролей, которые отличаются, например, на один символ);
```suggestion
- Существенно отличаться для близких по значению данных (для паролей, которые отличаются, например, на один символ).
```

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +- иметь одинаковое количество генерируемых символов для разных данных (разные пароли по количеству и составу символов);
```suggestion
- Иметь одинаковое количество генерируемых символов для разных данных (разные пароли по количеству и составу символов).
```

2021-07-07 13:23 UTC, bespoyasov commented on tools/encoding/index.md
> +- не повторяться для разных данных (только один пароль может аутентифицировать одного и того же пользователя).
```suggestion
- Не повторяться для разных данных (только один пароль может аутентифицировать одного и того же пользователя).
```

2021-07-08 15:35 UTC, igsekor commented on tools/encoding/index.md
> +- не повторяться для разных данных (только один пароль может аутентифицировать одного и того же пользователя).
Я же написал во втором пункте 😇

2021-07-08 15:37 UTC, igsekor commented on tools/encoding/index.md
> +- сложность реализации процедуры обмена ключами.
Ну вот это в симметричных шифрах решили, ещё когда Энигма провалилась.

2021-07-08 15:39 UTC, igsekor commented on tools/encoding/index.md
> +Ассиметричное шифрование — это использование разных ключей для шифрования и дешифровки. Представьте такой замок, закрыть который можно одним ключом, а открыть — другим. Разновидностью ассиметричного
Я думаю, что по шифрам можно написать отдельные статьи, поэтому везде сделал отсылку к Википедии. Хотелось сделать что-то без шифров про шифры как твоя вводная статья о паттернах, а то везде сразу глубокое погружение в шифры. Студентам вот сложно объяснять сразу про шифры, они не понимают, не осознавая такие вот вводные данные.

2021-07-08 15:41 UTC, igsekor commented on tools/encoding/index.md
> +- нет необходимости предварительно передавать секретный ключ;
Саша, я вот всё таки думаю, что лучше потом отдельно написать по интересным всяким шифрам, и ссылки прикрутить на более подробное чтение.

2021-07-08 15:42 UTC, igsekor commented on tools/encoding/index.md
> +- ключи большей длинны;
Да вот в том и дело, что однозначного математического доказательства нет 🙃

2021-07-08 15:42 UTC, igsekor commented on tools/encoding/index.md
> +Идея симметричного шифрования крайне проста — использование одного и того же ключа для шифрования и дешифровки. Такое шифрование широко применялось в древних и средневековых государствах ([Атбаш](htt
Ну давай добавим.

2021-07-09 09:22 UTC, bespoyasov commented on tools/encoding/index.md
> +Ассиметричное шифрование — это использование разных ключей для шифрования и дешифровки. Представьте такой замок, закрыть который можно одним ключом, а открыть — другим. Разновидностью ассиметричного
Да, это хорошая идея!

2021-07-09 09:22 UTC, bespoyasov commented on tools/encoding/index.md
> +- нет необходимости предварительно передавать секретный ключ;
👌

2021-07-09 09:23 UTC, bespoyasov commented on tools/encoding/index.md
> +- не повторяться для разных данных (только один пароль может аутентифицировать одного и того же пользователя).
А, я его совсем не понял :–(

2021-07-09 09:25 UTC, bespoyasov commented on tools/encoding/index.md
> +- не повторяться для разных данных (только один пароль может аутентифицировать одного и того же пользователя).
Может, напишем «генерировать строку-результат одинаковой длины при разных входных данных»? Чтобы было понятнее, что это именно про результат работы функции.

2021-07-09 09:27 UTC, bespoyasov approved these changes
👍

2021-07-09 13:20 UTC, pepelsbey commented on tools/encoding/index.md
> +  - Электронная цифровая подпись (Известные алгоритмы: схема Диффи-Хелмана, ГОСТ Р 34.10-2012, ECDSA, ГОСТ Р 34.10-94, DSA).
Предлагаю развернуть сложный вложенный список в более линейное перечисление.

```suggestion
### Без ключа

Необратимое шифрование: git, целостность данных, отслеживание транзакций, криптовалюты, шифрование паролей.

- Хэш-функции, известные алгоритмы: MD4/5, SHA-1/2/3.
- Блокчейн, известные алгоритмы: ECDSA.

### Один ключ

Симметричное шифрование данных с наибольшей скоростью:

- Подстановочные шифры, известные алгоритмы: Атбаш, шифр Цезаря, шифр Виженера.
- Блочные шифры, известные алгоритмы: Blowfish, Twofish, RC2/5/6, DES, AES, FROG, ГОСТ 28147-89.
- Поточные шифры, известные алгоритмы: RC4, SEAL, A5, Mosquito.

### Два ключа

Шифрование данных с наибольшим удобством для большого количества пользователей:

- Ассиметричное шифрование, известные алгоритмы: RSA, Elgamal, ECC.
- Электронная цифровая подпись, известные алгоритмы: схема Диффи-Хелмана, ГОСТ Р 34.10-2012, ECDSA, ГОСТ Р 34.10-94, DSA.
```

2021-07-09 13:21 UTC, pepelsbey reviewed
Можно упростить :)

2021-07-09 14:18 UTC, pepelsbey requested changes

2021-07-09 14:18 UTC, pepelsbey commented on tools/encoding/index.md
> +Существует специальная наука [криптография](https://ru.wikipedia.org/wiki/Криптография), в рамках которой исследуются существующие шифры и разрабатываются новые. Классификация шифров, исследование па
Слэши пишем слитно

```suggestion
Существует специальная наука [криптография](https://ru.wikipedia.org/wiki/Криптография), в рамках которой исследуются существующие шифры и разрабатываются новые. Классификация шифров, исследование параметров шифров и криптосистем в целом (систем хранения и/или передачи данных с шифрованием) — сферы интересов этой науки.
```

2021-07-09 14:18 UTC, pepelsbey commented on tools/encoding/index.md
> +Для того чтобы разобраться с шифрованием в Интернете, необходимо рассмотреть, какие криптосистемы бывают и какие шифры используются в них.
Кажется мы пишем со строчной. Ведь так @tachisis?

```suggestion
Для того чтобы разобраться с шифрованием в интернете, необходимо рассмотреть, какие криптосистемы бывают и какие шифры используются в них.
```

2021-07-09 14:18 UTC, pepelsbey commented on tools/encoding/index.md
> +Например, если зашифровать сообщение "Привет" смещением на три символа, получится сообщение "Тулезх". С разными шифрами можно поиграть на сайте «Каталог онлайн калькуляторов» в разделе «[Криптография
```suggestion
Например, если зашифровать сообщение «Привет» смещением на три символа, получится сообщение «Тулезх». С разными шифрами можно поиграть на сайте «Каталог онлайн калькуляторов» в разделе «[Криптография](https://planetcalc.ru/search/?section=813)».
```

2021-07-09 14:18 UTC, pepelsbey commented on tools/encoding/index.md
> +Ассиметричное шифрование — это использование разных ключей для шифрования и дешифровки. Представьте такой замок, закрыть который можно одним ключом, а открыть — другим. Разновидностью ассиметричного
```suggestion
Ассиметричное шифрование — это использование разных ключей для шифрования и дешифровки. Представьте такой замок, закрыть который можно одним ключом, а открыть — другим. Разновидностью ассиметричного шифрования является шифрование с открытым ключом, использование которого очень распространено в интернете. Открытый ключ — это ключ, который распространяется свободно. С помощью открытого ключа данные шифруются. А вот расшифровать данные можно только с помощью закрытого ключа, то есть ключа, который должен хранится только у адресата.
```

2021-07-09 14:18 UTC, pepelsbey commented on tools/encoding/index.md
> +Например, если вам необходимо переслать сообщение, вы просите адресата переслать вам открытый ключ. После шифрования, вы отправляете сообщение адресату, и только он сможет расшифровать сообщение, пос
```suggestion
Например, если вам необходимо переслать сообщение, вы просите адресата переслать вам открытый ключ. После шифрования, вы отправляете сообщение адресату, и только он сможет расшифровать сообщение, поскольку только он обладает закрытым ключом. По интернету передаётся открытый ключ, обладание которым не даёт злоумышленнику никакого преимущества.
```

2021-07-09 21:21 UTC, pepelsbey approved these changes

2021-07-11 16:08 UTC, nlopin requested changes
@igsekor планируешь ли сделать схемы?

2021-07-11 16:08 UTC, nlopin commented on tools/encoding/index.md
> +Исходя из преимуществ и недостатков, хорошим решением для современных веб-приложений является следующая схема передачи зашифрованных данных:
Может так?
```suggestion
В современном вебе используются схема передачи зашифрованных данных, в которой ассиметричное шифрование используется только для того, чтобы создать ключ симметричного шифрования:
```

2021-07-11 16:08 UTC, nlopin commented on tools/encoding/index.md
> +Представьте, что вам нужно использовать пароли для аутентификации пользователей. Если хранить их в открытом виде (в виде символов, которые вводит пользователь при заполнении поля пароля) в базе данны
Может так?
```suggestion
Представьте, что вам нужно использовать пароли для аутентификации пользователей. Если хранить их как есть в открытом виде (в виде символов, которые вводит пользователь при заполнении поля пароля) в базе данных или в файлах на сервере, то это будет небезопасно. Злоумышленник, которому удастся получить доступ к базе данных или файлам, получит пароли всех пользователей. В этом случае на помощь приходит необратимое шифрование.
```

2021-07-11 16:08 UTC, nlopin commented on tools/encoding/index.md
> +Для необратимого шифрования используются так называемые хэш-функции. Хэш или хэш-сумма — это просто последовательность символов. Хэш-функция — специальный алгоритм, который позволяет генерировать хэш
```suggestion
Для необратимого шифрования используются так называемые *хэш-функции*. Хэш-функция — специальный алгоритм, который позволяет генерировать хэш для шифруемых данных (в нашем случае паролей). Хэш или хэш-сумма — это просто последовательность символов. 

Последовательность сгенерированных символов должна:
```

2021-07-11 16:08 UTC, nlopin commented on tools/encoding/index.md
> +Другим вариантом применения хэш-функций является подсчёт хэш-сумм для файлов. Для файлов вычисляется хэш, который можно использовать для регистрации изменений. Например, это используется в системе ко
вот тут стоит развернуть, что такое «регистрация изменений»

2021-07-11 16:08 UTC, nlopin commented on tools/encoding/index.md
> +- Не повторяться для разных данных (только один пароль может аутентифицировать одного и того же пользователя).
Стоит ли сказать, что ей желательно быть быстрой?

2021-07-11 17:05 UTC, igsekor commented
> @igsekor планируешь ли сделать схемы?

Нет, думаю обойтись без них. Если мы придём к необходимости описания конкретных шифров, тогда без схем не обойтись.

2021-07-11 21:29 UTC, nlopin commented
Мне кажется будет классно дать схему асимметричного шифрования, но как сделать красиво, я ума не приложу

2021-07-12 06:09 UTC, nlopin commented on tools/encoding/index.md
> +- защищённые протоколы передачи данных;
у нас какое-то время назад [поменялись правила оформления списков](https://github.com/doka-guide/content/blob/main/docs/typography.md#%D0%BE%D1%80%D1%84%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F-%D0%B8-%D0%BF%D1%83%D0%BD%D0%BA%D1%82%D1%83%D0%B0%D1%86%D0%B8%D1%8F), теперь нужна точка в конце.

2021-07-12 09:00 UTC, nlopin commented on tools/encoding/index.md
> +- Хэш-функции, известные алгоритмы: MD4/5, SHA-1/2/3.
а давай тут скажем, что MD5 нельзя использовать для генерации криптоустойчивых хэшей, т.е. для шифрования паролей.

2021-07-12 09:18 UTC, igsekor commented
> Мне кажется будет классно дать схему асимметричного шифрования, но как сделать красиво, я ума не приложу

Добавил две картинки ;)

2021-07-12 09:29 UTC, bespoyasov approved these changes

2021-07-12 18:45 UTC, nlopin commented on tools/encoding/index.md
> +На сегодняшний день не каждый алгоритм обладает достаточной криптостойкостью. Например, MD5 нельзя использовать для шифрования паролей. Подробнее читайте в статье «[Безопасность веб-приложений и расп
в этой статье есть об md5?

2021-07-12 18:53 UTC, igsekor commented on tools/encoding/index.md
> +На сегодняшний день не каждый алгоритм обладает достаточной криптостойкостью. Например, MD5 нельзя использовать для шифрования паролей. Подробнее читайте в статье «[Безопасность веб-приложений и расп
@nlopin ну ты же попросил добавить этот комментарий. Про сам алгоритм нет. Я уже предлагал выше добавить статьи про семейство алгоритмов м сами алгоритмы. Комментарий же уместный вполне, он ни на что ссылается, но даёт возможность задуматься... что скажешь?

2021-07-13 14:32 UTC, nlopin commented on tools/encoding/index.md
> +На сегодняшний день не каждый алгоритм обладает достаточной криптостойкостью. Например, MD5 нельзя использовать для шифрования паролей. Подробнее читайте в статье «[Безопасность веб-приложений и расп
Может сюда? https://ru.wikipedia.org/wiki/MD5#%D0%9A%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7

2021-07-13 18:47 UTC, igsekor commented on tools/encoding/index.md
> +На сегодняшний день не каждый алгоритм обладает достаточной криптостойкостью. Например, MD5 нельзя использовать для шифрования паролей. Подробнее читайте в статье «[Безопасность веб-приложений и расп
> Может сюда? https://ru.wikipedia.org/wiki/MD5#%D0%9A%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7
> 
> Обсуждение алгоритмов это уже глубоко

@nlopin я не понял, что ты хотел сказать ссылкой. В плане просто ссылку сделать?

2021-07-13 19:41 UTC, nlopin commented on tools/encoding/index.md
> +На сегодняшний день не каждый алгоритм обладает достаточной криптостойкостью. Например, MD5 нельзя использовать для шифрования паролей. Подробнее читайте в статье «[Безопасность веб-приложений и расп
да, давай заменим ссылку, потому что в `/js/web-security/` нет ничего об md5

2021-07-18 12:01 UTC, ValyaBro approved these changes
картинки ок

2021-07-19 14:25 UTC, merged