Редактирует статью про селектор вложенности
doka-guide/content pull request #1138
Opened 2021-07-12 20:17 UTC by tachisis

Я довольно сильно переколбасила текст по сути, поскольку эта статья была почему-то про частный случай вложенных селекторов по классу, но комбинатором пробела можно ведь что угодно объединять. В общем, надо разобраться, как это лучше сделать все

2021-07-12 20:37 UTC, pepelsbey requested changes

2021-07-12 20:37 UTC, pepelsbey commented on css/nesting-selector/index.md
> +  /* Черный цвет */
```suggestion
  /* Чёрный цвет */
```

2021-07-12 20:37 UTC, pepelsbey commented on css/nesting-selector/index.md
> +Подробнее можно прочитать в статье [Специфичность в CSS](https://developer.mozilla.org/ru/docs/Web/CSS/Specificity).
```suggestion
Подробнее можно прочитать в статье «[Специфичность в CSS](https://developer.mozilla.org/ru/docs/Web/CSS/Specificity)».
```

2021-07-12 20:37 UTC, pepelsbey commented
Полностью поддерживаю переколбас, случай слишком частный.

2021-07-14 13:27 UTC, pepelsbey approved these changes

2021-07-15 18:14 UTC, solarrust approved these changes

2021-07-15 18:15 UTC, merged