Добавляет статью «Модели сетевого взаимодействия»
doka-guide/content pull request #1139
Opened 2021-07-13 15:41 UTC by igsekor

2021-07-14 07:28 UTC, bespoyasov reviewed
👍 

Я там предложил немного подробить структуру, добавив подзаголовки в модели OSI, чтобы было проще сканировать глазами каждый уровень. 

И кажется, картинка не долетела до гита :–(

А в остальном всё по делу!

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/index.md
> +Физический уровень (physical layer) отвечает за аппаратную реализацию передачи битов информации, то есть обеспечивает работу физических устройств: сетевых адаптеров, концентраторов, повторителей, мед
```suggestion
### Физический уровень

Физический уровень (physical layer) отвечает за аппаратную реализацию передачи битов информации, то есть обеспечивает работу физических устройств: сетевых адаптеров, концентраторов, повторителей, медиаконвертеров (устройств для преобразования сигнала при переходе из сети с одной средой передачи данных в сеть с другой средой). 

На физическом уровне рассматривают среды передачи данных: последовательный или параллельный порт, коаксиальный кабель, витая пара, радиоканал, оптоволокно, спутниковый интернет и т.д. Для передачи данных на физическом уровне существуют свои протоколы, то есть правила, по которым должен быть преобразован и передан сигнал с данными. Вы наверняка встречались с такими протоколами: IEEE 802.15 (Bluetooth), 802.11 Wi-Fi, GSM, DSL.
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/index.md
> +Канальный уровень (data link layer) используется для организации передачи данных по сети между устройствами и для контроля ошибок целостности данных. Если на физическом уровне обеспечивается передача
```suggestion
### Канальный уровень

Канальный уровень (data link layer) используется для организации передачи данных по сети между устройствами и для контроля ошибок целостности данных. Если на физическом уровне обеспечивается передача битов информации, то на канальном — передача [кадров (фреймов)](https://ru.wikipedia.org/wiki/Кадр_(телекоммуникации)). 

Каждый кадр позволяет передать 1446 байтов информации и содержит кроме служебной информации контрольную сумму кадра — [хэш-сумма](https://ru.wikipedia.org/wiki/Контрольная_сумма), которая рассчитывается по данным перед передачей и после передачи позволяет проверить сохранность данных. После получения хэш-сумма вновь рассчитывается по пришедшим данным и должна совпасть с той, которая передаётся в кадре. Если совпадает, можно считать, что данные переданы верно.
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/index.md
> +Сетевой уровень (network layer) позволяет прокладывать путь данных по сети от одного сетевого устройства к другому, то определяет маршрут. Маршрутизация — важная составляющая работы сети. Существуют
```suggestion
### Сетевой уровень

Сетевой уровень (network layer) позволяет прокладывать путь данных по сети от одного сетевого устройства к другому, то есть определяет маршрут. 

Маршрутизация — важная составляющая работы сети. Существуют даже специальные устройства — маршрутизаторы. Наиболее известный разработчикам протокол сетевого уровня — это [IP (Internet Protocol)](https://ru.wikipedia.org/wiki/Internet_Protocol). Он позволяет переправить пакеты от одного сетевого устройства к другому. Пакеты — это контейнеры для данных, реализованные уже не на физическом уровне, как кадры, а на программном. Протокол IP не гарантирует соответствия порядка при доставке пакетов изначальному порядку во время отправки, не гарантирует он и то, что пакеты будут доставлены или не будут продублированы. За это отвечают протоколы более высоких уровней. 

Создатели интернета спроектировали работу сетевых устройств как распределённой системы. Работу такой системы очень сложно парализовать. Путь внутри сети определяется для каждого пакета отдельно. Такая архитектура системы сложна, но обеспечивает устойчивое взаимодействие устройств, которые соединены любым образом в единую сеть.
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/index.md
> +Транспортный уровень (transport layer) обеспечивает необходимую целостность данных и выстраивает пакеты в правильный порядок. Веб-разработчикам чаще всего приходится сталкиваться с протоколами TCP и
```suggestion
### Транспортный уровень

Транспортный уровень (transport layer) обеспечивает необходимую целостность данных и выстраивает пакеты в правильный порядок. 

Веб-разработчикам чаще всего приходится сталкиваться с протоколами TCP и UDP. TCP используется для данных, целостность и порядок которых должны быть гарантирована, UDP — для данных, целостность которых важна только в конкретный момент времени внутри небольшого блока. 

Вы наверняка знакомы с подёргиванием видео или небольшими прерываниями звука, если пользовались потоковыми сервисами (например, YouTube, Apple Music, Spotify и другими), которые используют под капотом в основном UDP. Зато, когда загружается страничка какого-то сайта, потерь нет. Это как раз проверка целостности на уровне протокола TCP.
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/index.md
> +Сеансовый уровень (session layer) позволяет организовать сеанс связи между устройствами сети. Это необходимо для работы приложений. Вы можете знать протокол RPC (Remote Procedure Call Protocol — удал
```suggestion
### Сеансовый уровень

Сеансовый уровень (session layer) позволяет организовать сеанс связи между устройствами сети. Это необходимо для работы приложений. 

Вы можете знать протокол [RPC](/js/api/#rpc) (Remote Procedure Call Protocol — удалённый вызов процедур), если пользовались API на его основе (например, JSON-RPC, GraphQL или gRPC). Однако более распространённый протокол PPTP (Point-to-Point Tunneling Protocol) менее известен широкой аудитории, при этом используется он, например, для организации работы VPN (Virtual Private Network), обеспечивая туннель между компьютером и локальной сетью, имеющей подключение к интернету.
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/index.md
> +Уровень представления (presentation layer) служит для организации преобразования данных (кодирования и декодирования), преобразования протоколов и прочих служебных задач высокого уровня. С помощью пр
```suggestion
### Уровень представления

Уровень представления (presentation layer) служит для организации преобразования данных (кодирования и декодирования), преобразования протоколов и прочих служебных задач высокого уровня. 

С помощью протоколов этого уровня данные в форматах, которые используются на более низких уровнях, преобразуются к формату, который подходит для работы приложений. На этом уровне появляются абстракции представления данных — форматы и структуры данных, что позволяет подготовить данные к пересылки по сети и произвести обратное преобразование. 

Например, преобразование изображений от битов, которые путешествуют по сети, к форматам типа JPEG или TIFF происходит именно на этом уровне.
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/index.md
> +Прикладной уровень (application layer) — уровень приложений, то есть уровень, который обеспечивает максимальный уровень абстракции данных. Протоколы прикладного уровня вам наверняка знакомы: HTTP, SM
```suggestion
### Прикладной уровень

Прикладной уровень (application layer) — уровень приложений, то есть уровень, который обеспечивает максимальный уровень абстракции данных. 

Протоколы прикладного уровня вам наверняка знакомы: HTTP, SMTP, POP3, FTP, SIP, TELNET и другие. Использование сетевых служб (доступ к файлам и базам данных, пересылка электронной почты) позволяет приложениям на разных сетевых устройствах взаимодействовать друг с другом.
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/index.md
> +Иногда из модели OSI выделяют несколько уровней или отдельные семейства протоколов, которые могут использоваться для конкретных практических задач на программном уровне, в отрыве от конкретной на уро
```suggestion
Иногда из модели OSI выделяют несколько уровней или отдельные семейства протоколов, которые могут использоваться для конкретных практических задач на программном уровне, в отрыве от конкретной на уровне аппаратной реализации. Примером могут служить модели [DOD](https://ru.wikipedia.org/wiki/TCP/IP), [IPX/SPX](https://ru.wikipedia.org/wiki/IPX/SPX) или [AppleTalk](https://ru.wikipedia.org/wiki/AppleTalk). Но это лишь удобный с практической точки зрение отсечь всё лишнее, чтобы вести разработку программного обеспечения наиболее эффективным способом.
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/practice/igsekor.md
> +### Мониторинг пакетов
```suggestion
## Мониторинг пакетов
```

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/practice/igsekor.md
> +### Мониторинг пакетов
Наверное, начиная отсюда можем поднять все заголовки на один уровень? Или здесь важна вложенность по структуре?

2021-07-14 07:28 UTC, bespoyasov commented on tools/network-models/practice/igsekor.md
> +![Рабочее окно утилиты Wireshark](images/3.png)
А я картинку не могу найти :–(
Мы её пропустили где-то?

2021-07-14 09:25 UTC, tachisis approved these changes
Апрув на словарь

2021-07-14 13:27 UTC, nlopin commented on tools/network-models/index.md
> +- Модель DOD (Семейство TCP/IP).
Мы говорим про dod и spx в разделе кратко, это такой тизер того, что будем рассказывать. Но в итоге ни про DOD, ни про SPX нет ни абзаца, а только ссылки. 

Предлагаю либо убрать, либо дать хотя бы вводную инфу

2021-07-14 13:41 UTC, pepelsbey requested changes

2021-07-14 13:41 UTC, pepelsbey commented on tools/network-models/index.md
> +- Сетевая модель OSI (The Open Systems Interconnection model).
```suggestion
- Сетевая модель OSI (Open Systems Interconnection).
```
Просто расшифровываем аббревиатуру, без элементов английского языка :)

2021-07-14 13:41 UTC, pepelsbey commented on tools/network-models/practice/igsekor.md
> +Существуют специальные утилиты, которые позволяют просматривать пакеты в сетевом трафике, что позволяет разобраться с работой того или иного сетевого устройства. В Linux и большинстве Unix-подобных с
```suggestion
Существуют специальные утилиты, которые позволяют просматривать пакеты в сетевом трафике, что позволяет разобраться с работой того или иного сетевого устройства. В Linux и большинстве Unix-подобных систем есть консольная утилита _tcpdump_, есть и кросс-платформенная утилита Wireshark с графическим интерфейсом. Эти две утилиты в основном и используются для мониторинга пакетов.
```

2021-07-14 13:41 UTC, pepelsbey commented on tools/network-models/practice/igsekor.md
> +#### `tcpdump`
```suggestion
#### Tcpdump
```

2021-07-14 13:41 UTC, pepelsbey commented on tools/network-models/practice/igsekor.md
> +#### `tcpdump`
@tachisis у меня есть идея правила, что скажешь об этом примере?

2021-07-14 13:41 UTC, pepelsbey commented on tools/network-models/practice/igsekor.md
> +Чтобы прочитать этот файл, можно использовать Wireshark, который поддерживает данные в формате `.pcap`, или тот же `tcpdump`:
```suggestion
Чтобы прочитать этот файл, можно использовать Wireshark, который поддерживает данные в формате PCAP, или тот же _tcpdump_:
```

2021-07-14 13:41 UTC, pepelsbey commented on tools/network-models/practice/igsekor.md
> +Если графический интерфейс не доступен, например, вы настраиваете удалённый сервер, можно использовать `tcpdump`. Чтобы просмотреть трафик, надо набрать команду:
```suggestion
Если графический интерфейс не доступен, например, вы настраиваете удалённый сервер, можно использовать _tcpdump_. Чтобы просмотреть трафик, надо набрать команду:
```

2021-07-14 13:41 UTC, pepelsbey commented on tools/network-models/index.md
> +title: Модели сетевого взаимодействия
```suggestion
title: "Модели сетевого взаимодействия"
```

2021-07-14 15:44 UTC, pepelsbey approved these changes

2021-07-14 16:10 UTC, nlopin commented on tools/network-models/index.md
> +Иногда из модели OSI выделяют несколько уровней или отдельные семейства протоколов, которые могут использоваться для конкретных практических задач на программном уровне, в отрыве от конкретной на уро
тут кажется нужен заголовок второго уровня, если я правильно следовал мысли

2021-07-14 16:10 UTC, nlopin commented on tools/network-models/index.md
> +Безусловно модель OSI очень сложна и не раз подвергалась критики. В то же время эта модель предоставляет наиболее полное представление о том, как передаются данные по сети — от физической среды для п
```suggestion
Безусловно модель OSI очень сложна и не раз подвергалась критике. В то же время эта модель предоставляет наиболее полное представление о том, как передаются данные по сети — от физической среды для передачи данных до особенностей организаций данных в специальные структура, форматы и системы.
```

2021-07-15 23:05 UTC, igsekor commented on tools/network-models/index.md
> +
```suggestion

## Другие модели

```

2021-07-16 07:13 UTC, bespoyasov approved these changes

2021-07-19 16:33 UTC, merged