Редактирует статью про асинхронность в js
doka-guide/content pull request #1140
Opened 2021-07-13 20:02 UTC by tachisis

В соответствии с нашими соглашениями о том, что весь нарратив к коду мы максимально выносим за пределы кода, переколбасила тут очень много примеров, надо посмотреть, что нигде не утрачена суть.

2021-07-13 21:51 UTC, pepelsbey requested changes

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/index.md
> +```js
````suggestion
```
````
Тут не синтаксис JS, а просто абстрактный код, так что язык не нужен

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/index.md
> +Однако с ним могут возникать некоторые проблемы. Представим, что нам нужно выполнить какую-то операцию, требующую некоторого времени — например, напечатать в консоли приветствие, но не сразу, а через
```suggestion
Однако с ним могут возникать некоторые проблемы. Представим, что нам нужно выполнить какую-то операцию, требующую некоторого времени — например, напечатать в консоли приветствие, но не сразу, а через 5 секунд. Ниже псевдокод — синхронная функция задержки `delay()` вымышленная:
```

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/index.md
> +```js
````suggestion
```
````

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/index.md
> +Заметьте, что стек вызовов и очередь задач называются именно стеком и очередью. Потому что вызовы из стека работают по принципу _«последний зашёл, первый вышел»_ (LIFO), а в очереди — по принципу _«п
```suggestion
Заметьте, что стек вызовов и очередь задач называются именно стеком и очередью. Потому что вызовы из стека работают по принципу _«последний зашёл, первый вышел»_ (LIFO: last in, first out), а в очереди — по принципу _«первый зашёл, первый вышел»_ (FIFO: first in, first out).
```

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/index.md
> +Очень хорошо работу цикла событий иллюстрирует [инструмент Loupe](http://latentflip.com/loupe/) Филипа Робертса, а также его доклад [What the heck is the event loop anyway?](https://www.youtube.com/w
```suggestion
Очень хорошо работу цикла событий иллюстрирует [инструмент Loupe](http://latentflip.com/loupe/) Филипа Робертса, а также его доклад «[What the heck is the event loop anyway?](https://www.youtube.com/watch?v=8aGhZQkoFbQ)».
```

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/index.md
> +Однако у колбэков есть неприятный минус, так называемый _ад колбэков_ (callback-hell).
```suggestion
Однако у колбэков есть неприятный минус, так называемый _ад колбэков_ (callback hell).
```

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/practice/bespoyasov.md
> +В переменной values будет массив со значениями каждого из промисов, порядок значений в нём будет соответствовать порядку запросов: `[ [user1, user2], [post1, post2], [comment1, comment2] ]`.
````suggestion
В переменной `values` будет массив со значениями каждого из промисов, порядок значений в нём будет соответствовать порядку запросов:

```js
[
  [user1, user2],
  [post1, post2],
  [comment1, comment2]
]
```
````

Кажется так будет нагляднее, чем в строку

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/practice/bespoyasov.md
> +Выведет каждый url по очереди. Порядок гарантируется — так как код синхронный.
```suggestion
Выведет каждый URL по очереди. Порядок гарантируется — так как код синхронный.
```

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/practice/bespoyasov.md
> +Асинхронный же генератор почти не отличается от обычного, только вместо значений он выбрасывает промисы. И итерировать его придётся через for await ... of:
```suggestion
Асинхронный же генератор почти не отличается от обычного, только вместо значений он выбрасывает промисы. И итерировать его придётся через `for await ... of`:
```

2021-07-13 21:51 UTC, pepelsbey commented on js/async-in-js/practice/bespoyasov.md
> +Асинхронный же генератор почти не отличается от обычного, только вместо значений он выбрасывает промисы. И итерировать его придётся через for await ... of:
Нужно нормализовать как мы пишем такое. Кажется всё же без пробелов: [try...catch](https://y-doka.site/js/doka/try-catch/).

2021-07-14 06:52 UTC, bespoyasov commented
Я думал, что мы заменим таблицы из комментариев на анимацию 😃

(Эта статья ещё из Ноушена, мне казалось, что с ней разобрались. Пойду задачу создам. Если со стеком вызовов ещё как-то понятно, что происходит, то полная таблица без анимаций будет непонятной.)

2021-07-14 06:54 UTC, bespoyasov approved these changes
Я создал задачу в Ноушене на анимацию для статьи, чтобы изменение стека и очереди стало понятным. 

В остальном всё ок.

2021-07-14 09:09 UTC, tachisis commented on js/async-in-js/practice/bespoyasov.md
> +Асинхронный же генератор почти не отличается от обычного, только вместо значений он выбрасывает промисы. И итерировать его придётся через for await ... of:
@bespoyasov помогите определиться?

2021-07-14 09:15 UTC, bespoyasov commented on js/async-in-js/practice/bespoyasov.md
> +Асинхронный же генератор почти не отличается от обычного, только вместо значений он выбрасывает промисы. И итерировать его придётся через for await ... of:
Можно без пробелов, да 👌

2021-07-14 11:24 UTC, bespoyasov approved these changes

2021-07-14 12:59 UTC, nlopin approved these changes

2021-07-14 13:22 UTC, pepelsbey commented
Остались ещё предложенные правки и потом окну на мёрж :)

2021-07-14 15:46 UTC, tachisis commented
Почему-то не показывал мне саджесты из вкладки файлов. Приняла по очереди @pepelsbey

2021-07-14 15:50 UTC, pepelsbey approved these changes

2021-07-14 15:51 UTC, merged