Добавляет статью про тег hr
doka-guide/content pull request #1142
Opened 2021-07-13 22:21 UTC by lenaryan

2021-07-14 11:26 UTC, pepelsbey requested changes
Не очень понятно, почему `<hr>` разделяет строчные элементы. Более естественное место для линейки (так это называется в типографике) между абзацами текста. Вот, например, птички между абзацами [из блога Сары Суайдан](https://www.sarasoueidan.com/blog/tips-for-reader-modes/):

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/105274/125614371-09bb9835-7a57-47c7-8de2-13c928a58c3b.png">

Три звёздочки `***` между абзацами — это тоже, по сути, линейка между абзацами.

В общем, я бы добавил более реальных примеров использования: как в статью, так и в демку.

2021-07-14 11:26 UTC, pepelsbey commented on html/hr/demos/hr.html
> +    }
Шрифт мало подключить, его надо использовать :) Ну и если использовать, то лучше вынести всё как в типичном проекте на корневой элемент, который всё отнаследует.

```suggestion
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
  <style>
    body {
      font-family: 'Roboto', sans-serif;
      font-size: 18px;
    }

    .inline {
      padding: 5px 10px;
    }
```

2021-07-14 11:26 UTC, pepelsbey commented on html/hr/practice/lenaryan.md
> +🛠 `hr` — это блочный элемент, но несмотря на это, при встрече, например, с картинкой, для которой прописано свойство `float`, `hr` ведёт себя как строчный элемент, то есть начинает «обтекать» эту кар
```suggestion
🛠 `<hr>` — это блочный элемент, но несмотря на это, при встрече, например, с картинкой, для которой прописано свойство `float`, `<hr>` ведёт себя как строчный элемент, то есть начинает «обтекать» эту картинку.
```

2021-07-14 11:26 UTC, pepelsbey commented on html/hr/practice/lenaryan.md
> +🛠 `hr` — это блочный элемент, но несмотря на это, при встрече, например, с картинкой, для которой прописано свойство `float`, `hr` ведёт себя как строчный элемент, то есть начинает «обтекать» эту кар
И другая мысль: обтекание не привязано к строчности или блочности. Любой `<div>` начнёт обтекать флоаты. Так что тут кажется совет лишний и больше про флоаты, чем какую-то особенность `<hr>`.

2021-07-14 11:26 UTC, pepelsbey commented on html/hr/practice/lenaryan.md
> +🛠 Внешний вид тега `<hr>` по умолчанию обусловлен именно наличием границы, поэтому для изменения, например, цвета линии достаточно изменить `border-color`.
```suggestion
🛠 Внешний вид тега `<hr>` по умолчанию обусловлен именно наличием рамки, поэтому для изменения, например, цвета линии достаточно изменить `border-color`.
```
Граница — это логическое понятие, а рамка — визуальное (как у картины, скажем). Так что лучше переводить `border` как рамка. FYI, @tachisis.

2021-07-15 06:04 UTC, lenaryan commented on html/hr/practice/lenaryan.md
> +🛠 `hr` — это блочный элемент, но несмотря на это, при встрече, например, с картинкой, для которой прописано свойство `float`, `hr` ведёт себя как строчный элемент, то есть начинает «обтекать» эту кар
Див не обтекает флоаты, он себя ведёт так, будто зафлоаченных элементов вообще нет, как "Какой-то блок" в демке. Либо я просто в край отупела уже на этой жаре.
https://codepen.io/lenaryan/pen/JjEyxpm

2021-07-15 06:08 UTC, lenaryan commented on html/hr/demos/hr.html
> +    }
Кажется, надо переставать писать статьи по ночам... Немного не так донесла мысль

2021-07-15 09:49 UTC, pepelsbey commented on html/hr/practice/lenaryan.md
> +🛠 `hr` — это блочный элемент, но несмотря на это, при встрече, например, с картинкой, для которой прописано свойство `float`, `hr` ведёт себя как строчный элемент, то есть начинает «обтекать» эту кар
Всё чуть сложнее: [он обтекает](https://codepen.io/pepelsbey/pen/eYWvWOG), но не совсем так, как мы ожидаем :)

<img width="514" alt="image" src="https://user-images.githubusercontent.com/105274/125768047-523ca1b5-18a3-4c05-bbce-0bf6bf39cd99.png">

Я бы лучше не углублялся в такое в статье про тег.

2021-07-15 09:57 UTC, pepelsbey commented on html/hr/demos/hr.html
> +  <p>Среди палеонтологов до сих пор идут споры о&nbsp;том, что именно привело к&nbsp;внезапному вымиранию динозавров 66&nbsp;миллионов лет назад. Повинно ли в&nbsp;этом падение астероида или же катас
```suggestion
  <p>Слово «динозавр» означает буквально «ужасный, громадный ящер». Динозавры — это древние доисторические пресмыкающиеся (рептилии), которые принадлежат к подклассу архозавров. Динозавры очень разные: они могли быть размером с кошку и с огромного кита, который является самым большим животным на планете Земля.</p>
  <hr>
  <p>Среди палеонтологов до сих пор идут споры о том, что именно привело к внезапному вымиранию динозавров 66 миллионов лет назад. Повинно ли в этом падение астероида или же катастрофическое извержение множества вулканов?</p>
```

Если хочется типографить, то лучше выбрать «Готовыми символами» (или аналог в других инструментах)

<img width="580" alt="image" src="https://user-images.githubusercontent.com/105274/125769126-3b53b47d-aacc-4cfb-bb67-451ed6370757.png">

2021-07-15 09:58 UTC, pepelsbey commented on html/hr/demos/hr.html
> +  <p>Среди палеонтологов до сих пор идут споры о&nbsp;том, что именно привело к&nbsp;внезапному вымиранию динозавров 66&nbsp;миллионов лет назад. Повинно ли в&nbsp;этом падение астероида или же катас
@tachisis давай зафиксируем в документах про неразрывные пробелы — чтобы записывать их юникодом, а не подстановками.

2021-07-15 12:10 UTC, pepelsbey approved these changes

2021-07-15 18:32 UTC, solarrust commented
@lenaryan вынесла стили из примера прямо в текст, потому что мы обещаем читатель стилизовать `hr`. Надо это показать =)
@pepelsbey добавила пару советов. Сомневаюсь про последний, про скринридеры. Буду рада твоему ревью! 

@tachisis ждём тебя 🦸‍♀️

2021-07-15 20:53 UTC, pepelsbey commented on html/hr/practice/solarrust.md
> +🛠 Тег достался нам по наследству с тех времён, когда способов стилизации HTML было не то чтобы много. Поскольку `<hr>` не несёт никакой смысловой нагрузки, а нужен только для декоративных целей, то у
Вынужден не согласиться :) В спецификации чётко написано, какой из существущих в типографике элементов передаёт горизонтальная линейка.

> The hr element represents a paragraph-level thematic break, e.g. a scene change in a story, or a transition to another topic within a section of a reference book.

То есть это смысловой разделитель, пауза, смена сцены или подобное. То есть он всё же несёт смысловую нагрузку. Можно позже развить статью примерами использования, но я бы сейчас как минимум не давал советов, что он «бесполезный».

2021-07-15 20:53 UTC, pepelsbey commented on html/hr/practice/solarrust.md
> +🛠 Скринридеры произносят «горизонтальный разделитель» («horizontal splitter») когда доходят до тега `<hr>`. Если вы не хотите чтобы тег читался, то добавьте `aria-hidden = "true"` или подумайте о зам
Продолжая размышление выше — если у элемента есть смысл, то зачем его прятать? Если есть пауза, её нужно передать. Иначе два параграфа прочитаются встык и замысел будет потерян.

2021-07-16 18:01 UTC, solarrust commented on html/hr/practice/solarrust.md
> +🛠 Скринридеры произносят «горизонтальный разделитель» («horizontal splitter») когда доходят до тега `<hr>`. Если вы не хотите чтобы тег читался, то добавьте `aria-hidden = "true"` или подумайте о зам
Пока что удалила советы. Позже вернусь, подумаю над формулировками.

2021-07-18 08:35 UTC, solarrust approved these changes

2021-07-18 08:50 UTC, merged