Добавляет статью «SSL-сертификаты»
doka-guide/content pull request #1157
Opened 2021-07-15 16:55 UTC by igsekor

2021-07-15 17:42 UTC, nlopin commented on tools/ssl-certificates/index.md
> +В этой статье мы говорим про шифрование данных. Если вам не очень понятно, зачем оно нужно и как работает, прочитайте статью «[Шифрование](/tools/encoding/)»
Давай поменяем паттерн
```suggestion
В этой статье разбираются детали шифрования данных в интернете. Если хотите узнать больше про шифрование в целом, прочитайте статью «[Шифрование](/tools/encoding/)»
```

2021-07-15 20:25 UTC, tachisis approved these changes
Апрув на словарь

2021-07-15 21:18 UTC, pepelsbey requested changes

2021-07-15 21:18 UTC, pepelsbey commented on tools/ssl-certificates/index.md
> +title: SSL-сертификаты
```suggestion
title: "SSL-сертификаты"
```

2021-07-15 21:18 UTC, pepelsbey commented on tools/ssl-certificates/index.md
> +- Thawte SSL123.>
```suggestion
- Thawte SSL123.
```

2021-07-16 07:22 UTC, bespoyasov reviewed
🚀

2021-07-16 07:22 UTC, bespoyasov commented on tools/ssl-certificates/index.md
> +SSL-сертификат — это набор информации в бумажном или электронном виде, состоящий из:
А давай перед рассказом о том, что такое SSL-сертификат добавим для чего он нужен? Чтобы «Кратко» был не только кратким, но и полным. 

Или это лишнее? 🤔

2021-07-16 07:22 UTC, bespoyasov commented on tools/ssl-certificates/index.md
> +Когда сторона _A_ пересылает стороне _B_ свой сертификат, сторона _B_ сравнивает сгенерированную хэш-сумму на основе содержимого сертификата и хэш-сумму, которая получается при расшифровке электронно
Может, стоит добавить диаграмму или анимацию с процессом общения? Там можно будет показать, в какой момент сообщение становится зашифрованным, как оно «путешествует» между акторами и т. д.

2021-07-16 07:22 UTC, bespoyasov commented on tools/ssl-certificates/index.md
> +Удостоверяющий центр — это организация, которая может выдавать сертификаты и электронные подписи физическим и юридическим лицам. Если клиент и владелец сайта доверяют центру, то использование цифрово
Можно про Let's Encrypt рассказать, но не обязательно 🙃

2021-07-16 07:22 UTC, bespoyasov approved these changes

2021-07-16 10:58 UTC, igsekor commented on tools/ssl-certificates/index.md
> +Когда сторона _A_ пересылает стороне _B_ свой сертификат, сторона _B_ сравнивает сгенерированную хэш-сумму на основе содержимого сертификата и хэш-сумму, которая получается при расшифровке электронно
Согласен! Надо бы!

2021-07-16 10:58 UTC, igsekor commented on tools/ssl-certificates/index.md
> +Удостоверяющий центр — это организация, которая может выдавать сертификаты и электронные подписи физическим и юридическим лицам. Если клиент и владелец сайта доверяют центру, то использование цифрово
Действительно можно! Что-то забыл 😇

2021-07-16 13:52 UTC, bespoyasov approved these changes

2021-07-17 10:16 UTC, pepelsbey approved these changes

2021-07-17 19:44 UTC, merged

2021-07-18 12:03 UTC, ValyaBro reviewed
я не вижу в этой статье картинки, которые я могла бы аппрувить или комментировать

2021-07-18 13:23 UTC, igsekor commented
> я не вижу в этой статье картинки, которые я могла бы аппрувить или комментировать

Секрет прост — нет тут картинок :)

2021-07-26 13:05 UTC, ValyaBro commented
тогда нещадно аппрувлю ))