Редактирует статью про bom
doka-guide/content pull request #1158
Opened 2021-07-15 20:37 UTC by tachisis

2021-07-15 20:38 UTC, tachisis commented on js/bom/index.md
> +- [Ссылка на статью о fetch]().
Пожалуйста, проставьте тут ссылку и сделайте ей какой-то нормальный текст

2021-07-15 21:16 UTC, pepelsbey requested changes

2021-07-15 21:16 UTC, pepelsbey commented on js/bom/index.md
>  `fetch` предоставляет возможность работы с сетью, с его помощью можно отправлять запросы на сервер.
```suggestion
[Fetch](/js/fetch) предоставляет возможность работы с сетью, с его помощью можно отправлять запросы на сервер.
```

2021-07-15 21:16 UTC, pepelsbey commented on js/bom/index.md
> +- [Ссылка на статью о fetch]().
```suggestion
```
Дал ссылку на Fetch в самом начале. Плюс теперь предложение не начинается со строчной )

2021-07-15 21:16 UTC, pepelsbey commented on js/bom/index.md
> +Забавный факт: поле `userAgent` объекта `navigator` часто используется, чтобы определять, в каком именно браузере пользователь смотрит страницу сайта. Но читать его глазами [достаточно трудно](<https
```suggestion
Забавный факт: поле `userAgent` объекта `navigator` часто используется, чтобы определять, в каком именно браузере пользователь смотрит страницу сайта. Но читать его глазами [достаточно трудно](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537503(v=vs.85)), поэтому лучше это дело оставить какому-нибудь парсеру.
```
Чинит и упрощает ссылку

2021-07-16 07:10 UTC, bespoyasov approved these changes

2021-07-16 07:10 UTC, bespoyasov commented on js/bom/index.md
> +- [Ссылка на статью о fetch]().
Принял правки от @pepelsbey, там решили по-другому :–)

2021-07-17 09:35 UTC, pepelsbey approved these changes

2021-07-18 08:00 UTC, merged