Редактирует статью про position
doka-guide/content pull request #1160
Opened 2021-07-15 21:54 UTC by tachisis

2021-07-17 09:25 UTC, pepelsbey requested changes

2021-07-17 09:25 UTC, pepelsbey commented on css/position/index.md
>  .seelctor {
```suggestion
.selector {
```

2021-07-19 10:57 UTC, pepelsbey approved these changes

2021-07-26 09:32 UTC, solarrust approved these changes

2021-07-26 09:36 UTC, merged