Редактирует статью про aside
doka-guide/content pull request #1164
Opened 2021-07-16 13:20 UTC by tachisis

2021-07-17 10:18 UTC, pepelsbey requested changes

2021-07-17 10:18 UTC, pepelsbey commented on html/aside/index.md
> +`aside` размечает блок с дополнительным содержимым. Он может не иметь отношения к главному ([`<main>`](/html/main/)) контенту сайта. Часто используется для боковой колонки на сайте.
```suggestion
Тег `<aside>` размечает блок с дополнительным содержимым. Он может не иметь отношения к главному ([`<main>`](/html/main/)) контенту сайта. Часто используется для боковой колонки на сайте.
```

2021-07-19 10:57 UTC, pepelsbey approved these changes

2021-07-26 09:36 UTC, solarrust approved these changes

2021-07-26 09:36 UTC, merged