Редактирует статью про apache
doka-guide/content pull request #1168
Opened 2021-07-16 15:03 UTC by tachisis

2021-07-17 10:12 UTC, pepelsbey requested changes

2021-07-17 10:12 UTC, pepelsbey commented on tools/apache-web-server/index.md
> +Можно получить конфигурационный файл с помощью сервиса [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org). Проба сгенерировать разные конфигурации позволит разобраться с конкретным
```suggestion
Можно получить конфигурационный файл с помощью сервиса [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org). Попробуйте сгенерировать разные конфигурации, это поможет разобраться с конкретными настройками детальнее.
```

Вздрогнул от «проба сгенерировать», предлагаю оформить в совет.

2021-07-17 10:12 UTC, pepelsbey commented on tools/apache-web-server/index.md
> +У Apache, как и у любого веб-сервера, есть стандартное сообщение об ошибке. Но не всегда хочется использовать стандартное. Кастомизация сообщения возможна простым перенаправлением запроса к несуществ
```suggestion
У Apache, как и у любого веб-сервера, есть стандартное сообщение об ошибке. Но не всегда хочется использовать стандартное. Кастомизация сообщения возможна простым перенаправлением запроса к несуществующей странице на нужный разработчику файл. В примере этот файл называется _404.html_ и находится в директории сайта.
```

2021-07-19 06:58 UTC, bespoyasov approved these changes
Вроде, всё ок. 
@igsekor, посмотри, пожалуйста, тоже?

2021-07-19 08:22 UTC, igsekor commented
> Вроде, всё ок. 
> 
> @igsekor, посмотри, пожалуйста, тоже?

Да! Всё хорошо! Спасибо!

2021-07-19 15:59 UTC, bespoyasov approved these changes

2021-07-19 16:18 UTC, pepelsbey approved these changes

2021-07-19 16:18 UTC, merged