Добавлена статья Element.outerHTML
doka-guide/content pull request #1169
Opened 2021-07-16 19:12 UTC by Windrushfarer

Closes #1093

2021-07-17 10:07 UTC, pepelsbey requested changes

2021-07-17 10:07 UTC, pepelsbey commented on js/element-outerhtml/demos/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap">
```suggestion
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&family=Roboto:wght@400;500&display=swap">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap">
```

На странице нигде не используется Roboto Mono, хотя аж дважды подключается в шапке.

2021-07-17 10:07 UTC, pepelsbey commented on js/element-outerhtml/demos/index.html
> +    'use strict'
Кажется в 2021 уже и не нужно так писать?

2021-07-17 10:07 UTC, pepelsbey commented on js/element-outerhtml/index.md
> +Свойство `Element.outerHTML` позволяет получить HMTL элемент, включая его содержимое, в виде HTML-строки или заменить элемент на новый HTML.
```suggestion
Свойство `Element.outerHTML` позволяет получить HTML-элемент, включая его содержимое, в виде HTML-строки или заменить элемент на новый HTML.
```

2021-07-17 10:07 UTC, pepelsbey commented on js/element-outerhtml/index.md
> +```html
````suggestion
## Пример

```html
````

2021-07-17 10:07 UTC, pepelsbey commented on js/element-outerhtml/index.md
> +```
````suggestion
```js
const section = document.querySelector('section')

console.log(form.outerHTML)
```

В таком случае выведется весь HTML, включая сам элемент:

```html
<section><h1>Введение</h1><p>Параграф с текстом</p><p>Второй параграф с текстом</p></section>
```

Если теперь заменить содержимое новым HTML

```html
section.outerHTML = '<h2>Второй заголовок</h2>'
```

HTML после изменения будет:

```html
<h2>Второй заголовок</h2>
```
````

2021-07-17 10:07 UTC, pepelsbey commented on js/element-outerhtml/index.md
> +```
````suggestion
HTML после изменения будет:

```html
<span class="logo"></span>
```
````

2021-07-18 13:24 UTC, Windrushfarer commented on js/element-outerhtml/demos/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap">
Шрифт используется в css. Но двойное подключение это некруто, спасибо что заметил.

2021-07-18 13:29 UTC, Windrushfarer commented
@pepelsbey спасибо за внимательность на примерах. Применил те же правки и к другому примеру, которой я брал в качестве базы

2021-07-19 07:04 UTC, bespoyasov approved these changes
Вроде, всё по делу! 🚀

2021-07-19 07:04 UTC, bespoyasov commented on js/element-outerhtml/index.md
> +`Element.outerHTML` проще понять в сравнении с другим похожим свойством – [Element.innerHTML](/js/element-innerhtml). `Element.innerHTML` позволяет получить только **содержимое** элемента как HTML-ст
```suggestion
`Element.outerHTML` проще понять в сравнении с другим похожим свойством – [Element.innerHTML](/js/element-innerhtml). 

`Element.innerHTML` позволяет получить только **содержимое** элемента как HTML-строку. В то время как `Element.outerHTML` делает тоже самое, но при этом возвращает и HTML самого элемента. Можно сказать, что вывод будет идентичен `Element.innerHTML`, только в строке будет содержаться открывающий и закрывающий тег самого элемента, у которого было вызвано свойство.
```

2021-07-19 07:04 UTC, bespoyasov commented on js/element-outerhtml/index.md
> +Браузер позволит присвоить новое значение `Element.outerHTML` в `<body>`, но не удалит сам элемент. Вместо этого новое значение будет вставлено внутрь `<body>`, аналогично вызову `Element.innerHTML`.
О, не знал, интересно!

2021-07-19 08:51 UTC, bespoyasov approved these changes

2021-07-19 10:40 UTC, pepelsbey commented on js/element-outerhtml/demos/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap">
В стилях используется только Roboto, это другое семейство.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/105274/126147842-f46db5be-86b2-4e1f-9135-2a3b2bfa19b7.png">

2021-07-20 14:39 UTC, bespoyasov commented
@pepelsbey, тут всё ок? Мёржу?

2021-07-20 14:40 UTC, pepelsbey commented
> @pepelsbey, тут всё ок? Мёржу?

[Я пока не понял](https://github.com/doka-guide/content/pull/1169#discussion_r671666397), где там используется Roboto Mono в демке, а в остальном норм. Дождёмся ответа или правок :)

2021-07-20 14:42 UTC, Windrushfarer commented on js/element-outerhtml/demos/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap">
Точно, обновил ссылку на шрифт

2021-07-20 14:43 UTC, Windrushfarer commented
> [Я пока не понял](https://github.com/doka-guide/content/pull/1169#discussion_r671666397), где там используется Roboto Mono в демке, а в остальном норм. Дождёмся ответа или правок :)

Обновил :)

2021-07-20 21:29 UTC, pepelsbey approved these changes

2021-07-21 05:13 UTC, merged