Редактирует статью про font-face
doka-guide/content pull request #1174
Opened 2021-07-19 19:16 UTC by tachisis

2021-07-19 20:12 UTC, pepelsbey requested changes

2021-07-19 20:12 UTC, pepelsbey commented on css/font-face/index.md
> +Тут важно указать ссылки на файлы в нескольких форматах, чтобы любой браузер — старый или новый — мог загрузить шрифт в понятном ему формате. Принято хранить и подключать шрифты в форматах `woff`, `w
```suggestion
Тут важно указать ссылки на файлы в нескольких форматах, чтобы любой браузер — старый или новый — мог загрузить шрифт в понятном ему формате. Принято хранить и подключать шрифты в форматах WOFF, WOFF2, SVG.
```

2021-07-19 20:12 UTC, pepelsbey commented on css/font-face/index.md
> +Важный момент: если название шрифта состоит из двух и более слов, то его нужно взять в кавычки. Или объединить слова в названии, удалив пробелы. Не `Lexend Peta`, а `"Lexend Peta"` или `LexendPeta`.
```suggestion
```

Вообще кавычки там не нужны, работает и так:

```css
@font-face {
    font-family: FOO BAR;
    font-style: normal;
    font-weight: 400;
    src: url(https://fonts.gstatic.com/s/robotomono/v13/L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vq_ROW-AJi8SJQt.woff) format('woff');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}

body {
    font-family: FOO BAR, monospace;
}
```

Добавлять их или нет — это стиль кода, а не что-то принципиальное.

2021-07-19 20:12 UTC, pepelsbey commented on css/font-face/index.md
> +Первый — использовать разные @-правила для подключения разных начертаний шрифта, называя их разными именами. Например, `"Lexend Peta Regular"`, `"Lexend Peta Bold"` и `"Lexend Peta Italic"`. Выглядет
```suggestion
Первый — использовать разные `@font-face` для подключения разных начертаний шрифта, называя их разными именами. Например, `"Lexend Peta Regular"`, `"Lexend Peta Bold"` и `"Lexend Peta Italic"`. Выглядеть это будет так:
```

2021-07-19 20:12 UTC, pepelsbey commented on css/font-face/practice/solarrust.md
>  [Online @font-face generator](https://transfonter.org/)
```suggestion
- [Font Converter](https://www.font-converter.net/)
- [Online @font-face generator](https://transfonter.org/)
```

2021-07-19 20:12 UTC, pepelsbey commented on css/font-face/practice/solarrust.md
> +🛠 Советую всегда проверять, есть ли шрифт на сайте гуглового сервиса [Google Fonts](https://fonts.google.com/). Если найдёте, то останется только проставить нужные стилей шрифта и подключить одной ст
```suggestion
🛠 Советую всегда проверять, есть ли шрифт на сайте гуглового сервиса [Google Fonts](https://fonts.google.com/). Если найдёте, то останется только проставить нужные стили шрифта и подключить одной строкой вместо кучи `@font-face`. Ах, чудный идеальный мир, где все дизайнеры используют только бесплатные шрифты 🧚‍♀️
```

2021-07-19 21:46 UTC, tachisis commented
@bespoyasov @nlopin я случайно запушила сюда редактуру статьи по js :( Лень резетить, посмотрите, пожалуйста, в этом ПР?

2021-07-20 06:55 UTC, bespoyasov approved these changes

2021-07-20 06:55 UTC, bespoyasov commented
Окнул JS.

2021-07-26 10:13 UTC, solarrust approved these changes

2021-07-26 10:16 UTC, solarrust commented on css/font-face/index.md
> +Важный момент: если название шрифта состоит из двух и более слов, то его нужно взять в кавычки. Или объединить слова в названии, удалив пробелы. Не `Lexend Peta`, а `"Lexend Peta"` или `LexendPeta`.
Убрала

2021-07-27 13:44 UTC, pepelsbey approved these changes

2021-07-27 13:44 UTC, merged