Добаляет статью «Протокол HTTP»
doka-guide/content pull request #1181
Opened 2021-07-21 13:16 UTC by igsekor

2021-07-22 10:20 UTC, bespoyasov reviewed
Если бы так были написаны спеки, то человечество было бы таким 😃 

![d98ee90923438824d326a9f2aea4b682](https://user-images.githubusercontent.com/9102374/126624568-675a852d-6d88-413f-b198-dddcb18c7cd1.jpg)

Добавил пару идей для ссылок и коллаутов, остальное — 👍

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +1. Клиент (user agent) — программа, которая отправляет запросы, получает и обрабатывает ответы от имени пользователя на устройстве пользователя.
```suggestion
1. Клиент (user agent) — программа, которая отправляет запросы, получает и обрабатывает ответы от имени пользователя на устройстве пользователя, например, браузер.
```

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +Протокол HTTP не хранит состояние, поэтому количество соединений не приводит к существенному усложнению взаимодействия между объектами системы. Однако существует понятие _сессии_, с помощью которой м
```suggestion
Протокол HTTP не хранит состояние, поэтому количество соединений не приводит к существенному усложнению взаимодействия между объектами системы. Однако существует понятие _сессии_, с помощью которой можно передавать и хранить необходимые данные, относящиеся в конкретному сеансу связи. Данные сессии сохраняются на клиенте и на сервере. Например, доступен идентификатор сессии, который позволяет не проводить авторизацию клиента при каждом обращении к серверу.

::: callout 🍪

Часто для хранения данных о сессии используются [Cookie](/js/cookie/).

:::
```

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +Формат для HTTP-сообщения используется тестовый. Структура сообщения строго определена:
```suggestion
Формат для HTTP-сообщения используется текстовый. Структура сообщения строго определена:
```

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +2. Заголовки используется для передачи сервисной информации.
```suggestion
2. Заголовки, передают сервисную информацию.
```

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +3. Тело сообщения, которое представляет данные в текстовом виде.
```suggestion
3. Тело сообщения, представляет данные в текстовом виде.
```

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +В заголовках указывается разная необходимая для работы веб-сервера или клиента информация. Например, есть адрес домена, к которому обращается клиент или информация об авторизации пользователя. Также
Можно дать пример со сжатием gzip или brotli: типа что для использования конкретного сжатия, и клиент, и сервер должны уметь его понимать, и это отразится в заголовках.

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +- text/json.
А точно `text/json`, а не `application/json`, или это разные типы? 🤔

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +- `PATCH` — то же, что и `PUT`, но используется для части данных.
```suggestion
- `PATCH` — то же, что и `PUT`, но используется для обновления части данных.
```

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +
Можно пока дать ссылку на https://httpstatuses.com, а потом (когда мы сделаем собственный мини-сервис) заменить на наш 😃

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +Принято заголовки группировать в соответствие со списком выше, и посылать их в соответствующем списку порядке. В стандартах для каждой версии HTTP описано довольно много заголовков, но можно использо
```suggestion
Принято заголовки группировать в соответствии со списком выше и посылать их в соответствующем списку порядке. В стандартах для каждой версии HTTP описано довольно много заголовков, но можно использовать и свои.
```

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +На первом этапе клиент устанавливает соединение с сервером с помощью протокола транспортного уровня TCP. Клиент может переиспользовать одно и то же соединение для работы с сервером или создавать его
Вероятно, будет здорово показать на схеме общение сервера с клиентом? У нас в какой-то из предыдущих статей было нечто подобное, вроде — можем переиспользовать?

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/index.md
> +- Проводить аутентификацию клиентов для управления доступом к ресурсам.
Не уверен, что в тему, но можно привязать рейт-лимитинг и определение подозрительного трафика, сославшись на [«Безопасность веб-приложений»](https://doka.guide/js/web-security/#slowloris). Но это не обязательно 🙃

2021-07-22 10:20 UTC, bespoyasov commented on tools/http-protocol/practice/igsekor.md
> +Символы `*`, `>` и `<` являются маркерами типа информации, отображённой в выводе команды.
А давай поясним, что какой означает? (Или если мы где-то об этом писали, то сошлёмся на статью об этом.)

2021-07-22 11:41 UTC, igsekor commented on tools/http-protocol/index.md
> +На первом этапе клиент устанавливает соединение с сервером с помощью протокола транспортного уровня TCP. Клиент может переиспользовать одно и то же соединение для работы с сервером или создавать его
Мы хотели сделать анимацию, но не сделали пока... Но сделать схему бы надо.

2021-07-22 11:55 UTC, igsekor commented on tools/http-protocol/index.md
> +- text/json.
Ну конечно `application/json`. Очепятка :)

2021-07-22 11:57 UTC, igsekor commented on tools/http-protocol/index.md
> +
Давай! :)

2021-07-22 12:01 UTC, igsekor commented on tools/http-protocol/index.md
> +- Проводить аутентификацию клиентов для управления доступом к ресурсам.
Да, отличный повод для кросс-линка! :)

2021-07-22 12:15 UTC, pepelsbey requested changes
А почему везде используется домен google.co.in? Может быть что-нибудь менее индийское и нейтральное? Или doka.guide или example.com, привычный уже.

2021-07-22 12:15 UTC, pepelsbey commented on tools/http-protocol/practice/igsekor.md
> +* Connection #0 to host google.co.in left intact
Переведём и вынесем коммент?

2021-07-22 12:15 UTC, igsekor commented on tools/http-protocol/index.md
> +В заголовках указывается разная необходимая для работы веб-сервера или клиента информация. Например, есть адрес домена, к которому обращается клиент или информация об авторизации пользователя. Также
Да, классная идея

2021-07-22 12:20 UTC, igsekor commented on tools/http-protocol/practice/igsekor.md
> +Символы `*`, `>` и `<` являются маркерами типа информации, отображённой в выводе команды.
Да, так будет точно лучше!

2021-07-22 12:55 UTC, igsekor commented on tools/http-protocol/practice/igsekor.md
> +* Connection #0 to host google.co.in left intact
Это вывод самой команды, не мой коммент

2021-07-22 12:59 UTC, igsekor commented on tools/http-protocol/practice/igsekor.md
> +```
Да не получится так, у нас есть стратегия с выводом в терминал, когда мы показываем символ `>` для вывода определённой команды. Эта стратегия конфликтует с той, которую ты предлагаешь. Кажется, что мы должны найти компромисс и следовать ему. Сначала я написал именно так — вывел всё и начал описывать. Вот только команду от вывода отделять не очень просто. Стратегия же должна быть направлена на удобство чтения? Или нет?

2021-07-22 13:01 UTC, pepelsbey commented on tools/http-protocol/practice/igsekor.md
> +* Connection #0 to host google.co.in left intact
Тогда это не bash, поскольку там это комментарий

2021-07-22 13:02 UTC, pepelsbey commented on tools/http-protocol/practice/igsekor.md
> +```
Тут главная идея в том, чтобы не писать важный для понимания текст в коде. Можно подумать, как её решить.

2021-07-22 15:38 UTC, igsekor commented on tools/http-protocol/practice/igsekor.md
> +* Connection #0 to host google.co.in left intact
@pepelsbey это комментарий, но не мой.

2021-07-22 15:39 UTC, igsekor commented
> А почему везде используется домен google.co.in? Может быть что-нибудь менее индийское и нейтральное? Или doka.guide или example.com, привычный уже.

Потому что железобетонно вывод команды короткий.

2021-07-23 11:46 UTC, bespoyasov approved these changes
Добавил подзаголовков, в остальном — 🚀

2021-07-23 11:46 UTC, bespoyasov commented on tools/http-protocol/index.md
> +
```suggestion

### Использование заголовков

```

2021-07-23 11:46 UTC, bespoyasov commented on tools/http-protocol/index.md
> +Приведём пример. Для экономии трафика часто используют сжатие данных: архивация данных перед пересылкой и разархивация после пересылки. Для этого применяют несколько алгоритмов сжатия. Например, част
```suggestion
Приведём пример. Для экономии трафика часто используют сжатие данных: архивация данных перед пересылкой и разархивация после пересылки. Для этого применяют несколько алгоритмов сжатия. Например, часто применяется gzip, но наиболее интересным и современным является brotli. 

Для того чтобы пользоваться сжатием, необходимо дать понять клиенту и серверу, что это вообще возможно и какой алгоритм сжатия применять. Выбор конкретного алгоритма обусловлен несколькими специфическими причинами. Например, программная поддержка на клиенте (чаще всего клиентом является браузер), реализация сжатия на сервере, особенности пересылаемых данных. В любом случае клиент должен сообщить серверу, что сжатие поддерживается, сервер должен сообщить клиенту, что данные сжаты и их необходимо распаковать перед использованием.
```

2021-07-23 11:46 UTC, bespoyasov commented on tools/http-protocol/index.md
> +
```suggestion

### Формат сообщения

```

2021-07-23 11:46 UTC, bespoyasov commented on tools/http-protocol/index.md
> +
```suggestion

### Структура передаваемых сообщений

Как мы говорили ранее, сообщение состоит из стартовой строки, заголовков и тела.

```

2021-07-23 11:46 UTC, bespoyasov commented on tools/http-protocol/practice/igsekor.md
> +Вы можете узнать больше о домене с помощью разных сервисов, например, с помощью [domain.glass](https://domain.glass/example.com).
О, крутая штука!

2021-07-26 13:08 UTC, ValyaBro approved these changes
после редизайна картинки пойдут под замену, пока ок

2021-08-08 19:57 UTC, nlopin commented on tools/http-protocol/index.md
> +Подробнее о других уровнях модели сетевого взаимодействия написано в статье «[Модели сетевого взаимодействия](/tools/network-models/)».
предлагаю калаут убрать, а вместо него поставить ссылку на фразу «модели OSI» в разделе «Кратко»

2021-08-08 20:01 UTC, nlopin commented on tools/http-protocol/index.md
> +HTTP был разработан как протокол обмена данными между веб-сервером и веб-браузером. Это протокол прикладного уровня модели OSI, который используется для передачи данных (HTML, CSS, JS, API, картинок,
Я убрал слово «данных», потому что в предыдущем предложение мы уже сказали, что это протокол обмена данными

```suggestion
HTTP был разработан как протокол обмена данными между веб-сервером и веб-браузером. Это протокол прикладного уровня [модели OSI](/tools/network-models), который используется для передачи между клиентом и сервером файлов HTML, CSS, JS, API, картинок, аудио, видео, введённых пользователем данных и прочего. Клиент (веб-браузер) отправляет серверу (веб-серверу) запросы и получает от него ответы. Сервер в рамках протокола HTTP практически всегда занимает пассивную позицию.
```

2021-08-08 20:03 UTC, nlopin commented on tools/http-protocol/index.md
> +2. Сервер (веб-сервер) — программа, которая, работая на сервере, принимает и обрабатывает запросы от клиента, а затем отправляет ответы клиенту. Этой программой является веб-сервер.
У нас на три строки два раза используется «веб-сервер». У них разный смысл или можно одно упоминание удалить?

```suggestion
2. Сервер (веб-сервер) — программа, которая работает на сервере, принимает и обрабатывает запросы от клиента, а затем отправляет ответы клиенту. Этой программой является веб-сервер.
```

2021-08-08 20:03 UTC, nlopin commented on tools/http-protocol/index.md
> +3. Прокси (прокси-сервер) — программа, которая, работая на сервере, пропускает через себя запросы и ответы и выступает в роли посредника между клиентом и сервером.
```suggestion
3. Прокси (прокси-сервер) — программа, которая работает на сервере, пропускает через себя запросы и ответы и выступает в роли посредника между клиентом и сервером.
```

2021-08-08 20:04 UTC, nlopin commented on tools/http-protocol/index.md
> +Подробнее о веб-серверах написано в статье «[Веб-сервер](/tools/web-server/)».
```suggestion
Подробнее о веб-серверах читайте в статье «[Веб-сервер](/tools/web-server/)».
```

2021-08-08 20:05 UTC, nlopin commented on tools/http-protocol/index.md
> +На первом этапе клиент устанавливает соединение с сервером с помощью протокола транспортного уровня TCP. Клиент может переиспользовать одно и то же соединение для работы с сервером или создавать его
```suggestion
На первом этапе клиент устанавливает соединение с сервером с помощью протокола транспортного уровня TCP. Клиент может переиспользовать одно и то же соединение для работы с сервером или создавать его каждый раз. Это зависит от задачи, конфигурации сети и конкретных настроек оборудования. После установки соединения клиент посылает HTTP-сообщение с телом и параметрами запроса. Сервер принимает это сообщение и, на основании логики работы бэкенда, формирует и отправляет HTTP-сообщение ответа.
```

2021-08-08 20:09 UTC, nlopin commented on tools/http-protocol/index.md
> +В случае запроса стартовая строка содержит информацию о методе запроса, относительном адресе и версии протокола в формате `Метод URI HTTP/Версия`. Стартовая строка ответа содержит также версию проток
давай ниже добавим пример

2021-08-08 20:26 UTC, nlopin requested changes
Хочется улучшить структуру, у меня возникало много вопросов, которые надолго подвисали в воздухе. Сейчас повествование время от времени отходит от высокоуровневой картины, а потом возвращается в нее и объясняет снова. Помоги разобраться, возможно я что-то не так понимаю. Попробую проиллюстрировать, что имею ввиду, курсивом мои вопросы:

* начало блока «как понять» — классно рассказываем о цели протокола и высокоуровневой структуре сообщений (стартовая строка, заголовки, тело)
* затем говорим, что стартовая строка сообщения выглядит как «метод URI HTTP/версия», а в ответ прилетает статус (_не показываем пример, не объясняем, что такое метод или статус_)
* говорим про заголовки и показываем пример
* снова говорим про формат сообщения (_тут опять говорим про структуру, но начинаем почему-то с тела, затем прыгаем к методам и статусам ответов_)
* раздел «Структура передаваемых сообщений» (_говорим про заголовки и тело_)

В моей голове почти все заголовки третьего уровня говорят про одно «как выглядит сообщение», но разными словами. 

Давай попробуем альтернативную структуру? Например,

* Формат сообщения (блоки из которых состоит)
* Стартовая строка 
  *  методы
  *  коды ответа
*  Заголовки
*  Тело
*  Примеры

2021-08-09 19:56 UTC, nlopin commented on tools/http-protocol/index.md
> +- Обнаруживать некоторые типы атак на сетевой узел (например, определение подозрительного трафика или DDoS-атаки).
Может эту часть вынести перед заголовком «формат сообщения»? Будет чуть ближе к части, где мы упоминали про прокси

2021-08-09 20:50 UTC, nlopin approved these changes

2021-08-10 09:59 UTC, bespoyasov approved these changes

2021-08-10 22:30 UTC, pepelsbey commented on tools/http-protocol/practice/igsekor.md
> +
```suggestion
```

Предлагаю избежать …, чтобы не запутать тех, кто разбирается. Это выглядит как служебная команда. Можно допустить, что вывод будет чуть другим.

2021-08-19 22:02 UTC, merged