Обновляет Руководство по оформлению
doka-guide/content pull request #1188
Opened 2021-07-22 00:38 UTC by tachisis

- Добавляет пункты про кавычки
- про ударения; 
- уточняет несколько пунктов; 
- превращает списки правил в пункты с заголовками.

2021-07-22 12:45 UTC, pepelsbey requested changes

2021-07-22 12:45 UTC, pepelsbey commented on docs/typography.md
> +  ```
````suggestion
```css
.container {
  display: flex;
}
```
````

2021-07-22 12:45 UTC, pepelsbey commented on docs/typography.md
> +  // потому что JavaScript считает перенос за конец строки
```suggestion
  42
}
// Функция возвращает `undefined`, а не `42`,
// потому что JavaScript считает перенос за конец строки
```

2021-07-22 12:45 UTC, pepelsbey commented on docs/typography.md
> +  }
```suggestion
  42
}
```

2021-07-22 12:45 UTC, pepelsbey commented on docs/typography.md
> +⛔ div/span
Я бы придумал другой пример, этот противоречит тегам в угловых скобках

2021-07-22 12:45 UTC, pepelsbey commented on docs/typography.md
> +Если нужно показать ударение в слове, используем обычный кириллический символ с комбинирующим символом ударения (combining acute accent).
Я бы уточнил, что его нужно ставить после буквы и объяснил, откуда его взять.

2021-07-22 16:09 UTC, tachisis commented on docs/typography.md
> +Если нужно показать ударение в слове, используем обычный кириллический символ с комбинирующим символом ударения (combining acute accent).
А я сама не знаю, откуда :( Расскажешь?

2021-07-22 20:33 UTC, pepelsbey commented on docs/typography.md
> +Если нужно показать ударение в слове, используем обычный кириллический символ с комбинирующим символом ударения (combining acute accent).
На macOS его можно найти в панели Character Viewer (Ctrl Cmd Space): поискать combining acute accent добавить в избранное. На всех платформах [можно нажать на кнопку](https://codepoints.net/U+0301) Copy to Clipboard и вставить куда нужно.

2021-07-23 11:24 UTC, pepelsbey approved these changes

2021-07-23 11:24 UTC, merged