Добавляет ссылки на смежные статьи
doka-guide/content pull request #1196
Opened 2021-07-26 21:42 UTC by igsekor

В этом PR не только небольшое дополнение в статьям. Тренируемся делать PR из форка

2021-07-29 06:48 UTC, furtivite commented on tools/web-server/index.md
> +
@igsekor, я правильно понимаю, что этот фичеринг происходит не вручную, а автоматом? Получается, он появится в конце блока, где упоминалась ссылка?

2021-07-29 06:49 UTC, furtivite commented on tools/web-server/index.md
> +1. «[Веб-сервер Apache](https://doka.guide/tools/apache-web-server/)».
```suggestion
1. «[Веб-сервер Apache](/tools/apache-web-server/)».
```

Было бы классно видеть относительную ссылку.

2021-07-29 23:31 UTC, igsekor commented on tools/web-server/index.md
> +
В этом PR отрабатывается работа из форка. Только и всего.

2021-08-08 19:04 UTC, pepelsbey commented on tools/web-server/index.md
> +2. «[Веб-сервер Nginx](https://doka.guide/tools/nginx-web-server/)».
```suggestion
2. «[Веб-сервер Nginx](/tools/nginx-web-server/)».
```

2021-08-08 19:05 UTC, pepelsbey requested changes
И ещё одна ссылочка

2021-08-08 19:38 UTC, nlopin commented
я не могу качественно отревьюить этот пул реквест. Без контекста не понимаю, что он делает, почему так много изменений в workflows, куда и как мы добавляем ссылки на смежные статьи 🤷

2021-08-08 19:44 UTC, pepelsbey commented
@nlopin это тестовый ПР, в котором @igsekor проверяет работу экшенов из форка. Думаю, это стоило бы добавить в описание. Мол, это эксперимент и мёржить не нужно. Ну или что эксперимент закончен и можно мёржить.

В общем, нам нужны описания для ПР получше.

2021-08-09 12:10 UTC, igsekor commented
@nlopin @pepelsbey я здесь всё отработал и предлагаю просто закрыть этот PR. Сделаю несколько отдельных, в которых всё будет отдельно, правильно описано и последовательно внедрено. Что скажите?

2021-08-13 14:25 UTC, closed without merging