Добавляет статью про details и summary
doka-guide/content pull request #1197
Opened 2021-07-27 07:39 UTC by lenaryan

2021-07-29 07:40 UTC, solarrust commented on html/details/index.md
> +HTML-only «аккордеон».
Пользователь может быть не знаком с понятием «аккордеона» в веб-интерфейсе. Плюс мы «документация на русском языке» и английское слово может не дать полного понимания. Чуть бы развернуть фразу. Что-то вроде: «Раскрывающийся список на чистом HTML. Без JavaScript и прочей магии».

2021-07-29 07:40 UTC, solarrust commented on html/details/index.md
> +`<details>` — это интерактивный элемент, при нажатии на который открывается блок с информацией — текстом и картинками. Нередко такие элементы можно встретить на страницах часто задаваемых вопросов, г
```suggestion
`<details>` — это интерактивный элемент, при нажатии на который открывается блок с информацией — текстом или картинками. Нередко такие элементы можно встретить на страницах с часто задаваемыми вопросами (FAQ), где в легенде написан вопрос, а ответом является содержимое «аккордеона».
```

Что такое «легенда»? Читатель пока не сталкивался с этим понятием.

2021-07-29 07:40 UTC, solarrust commented on html/details/index.md
> +title: "Теги <details> + <summary>"
```suggestion
title: "Теги <details> и <summary>"
```

2021-07-29 07:40 UTC, solarrust commented on html/details/index.md
> +`<details>` — это интерактивный элемент, при нажатии на который открывается блок с информацией — текстом и картинками. Нередко такие элементы можно встретить на страницах часто задаваемых вопросов, г
Если статья про оба тега, то почему мы описываем тут только один из них?

2021-07-29 10:00 UTC, lenaryan commented on html/details/index.md
> +`<details>` — это интерактивный элемент, при нажатии на который открывается блок с информацией — текстом и картинками. Нередко такие элементы можно встретить на страницах часто задаваемых вопросов, г
Но про саммари же тоже написано. Сделать это более явно или как?

2021-07-29 12:59 UTC, solarrust commented on html/details/index.md
> +`<details>` — это интерактивный элемент, при нажатии на который открывается блок с информацией — текстом и картинками. Нередко такие элементы можно встретить на страницах часто задаваемых вопросов, г
В разделе «как понять» лучше было бы описать теорию этого элемента. Типа «иногда не обязательно показать всю информацию сразу, что-то можно скрыть. Это называется аккордеон. Самый простой способ его сделать — этот.»

А уже в разделе «как пишется» расписать про теги =)

2021-07-29 14:20 UTC, tachisis approved these changes
Апрув на словарь

2021-07-31 20:43 UTC, lenaryan commented
> Поле undefined в файле 'html/details/index.md' не на своём месте! Нужно переместить вверх.

Интересно девки пляшут :) Как понимать эту ошибку Фронтматтера?

2021-08-02 08:16 UTC, solarrust commented
@pepelsbey заглядывай

2021-08-02 08:33 UTC, pepelsbey requested changes

2021-08-02 08:33 UTC, pepelsbey commented on html/details/demos/details-open.html
> +    .text {
Я бы и здесь написал селектор по тегу, кажется будет последовательно и достаточно. Ну и из разметки убрать.

2021-08-02 08:33 UTC, pepelsbey commented on html/details/demos/details-summary.html
> +    .text {
Аналогично

2021-08-02 08:33 UTC, pepelsbey commented on html/details/index.md
> +summary:
Кажется мы уже переехали на keywords

2021-08-02 08:33 UTC, pepelsbey commented on html/details/index.md
> +Иногда разработчики скрывают какую-то информацию на странице в специальном блоке. В любой момент мы можем кликнуть на этот блок и развернуть информацию. И свернуть обратно таким же кликом. Такой блок
Я бы чуть иначе повернул:

```suggestion
Иногда нужно скрывать какую-то информацию на странице в специальном блоке. Чтобы в любой момент можно было кликнуть на этот блок и развернуть информацию. И свернуть обратно таким же кликом. Такой блок ещё называют «аккордеоном».
```

Не разработчики придумывают интерфейс обычно, но они его внедряют.

2021-08-02 08:33 UTC, pepelsbey commented on html/details/index.md
> +По умолчанию «аккордеон» закрыт, но если мы хотим, чтобы его содержание показывалось сразу при загрузке страницы, можно добавить к нему атрибут `open`.
```suggestion
По умолчанию «аккордеон» закрыт, но если мы хотим, чтобы его содержание показывалось сразу при загрузке страницы или открывать его из JavaScript, нужно добавить к нему атрибут `open`.
```

2021-08-02 08:33 UTC, pepelsbey commented on html/details/practice/lenaryan.md
> +🛠 До сих пор не поддерживается в IE11.
От этой реплики веет оптимизмом такой силы, что я даже не знаю. Как будто она когда-нибудь появится :)

```suggestion
🛠 Не поддерживается в IE11.
```

2021-08-02 08:33 UTC, pepelsbey commented on html/details/practice/lenaryan.md
> +🛠 Если присутствует тег `<summary>`, то псевдоэлемент `::marker` можно стилизовать — правда, он реагирует не на все свойства, но как минимум вы сможете поменять цвет и размер шрифта. Иногда для его с
```suggestion
🛠 Если присутствует тег `<summary>`, то псевдоэлемент `::marker` можно стилизовать — правда, он реагирует не на все свойства, но как минимум вы сможете поменять цвет и размер шрифта. Раньше для его стилизации нужно было указывать `::-webkit-details-marker`.
```

2021-08-02 16:12 UTC, lenaryan commented on html/details/index.md
> +Иногда разработчики скрывают какую-то информацию на странице в специальном блоке. В любой момент мы можем кликнуть на этот блок и развернуть информацию. И свернуть обратно таким же кликом. Такой блок
fair enough

2021-08-02 16:13 UTC, lenaryan commented on html/details/practice/lenaryan.md
> +🛠 До сих пор не поддерживается в IE11.
Ору чаечкой 🤣

2021-08-03 00:37 UTC, pepelsbey approved these changes

2021-08-03 05:44 UTC, solarrust approved these changes

2021-08-03 05:44 UTC, merged