Редактирует статью про code review
doka-guide/content pull request #1200
Opened 2021-07-27 21:05 UTC by tachisis

2021-07-27 21:23 UTC, pepelsbey requested changes

2021-07-27 21:23 UTC, pepelsbey commented on tools/code-review/index.md
> +Отправка изменений на код-ревью происходит через **пул-реквесты**. Для прохождения код-ревью нужно получить одобрение одного или нескольких коллег. Способ выбора коллег для проведения ревью зависит о
[В словаре Веб-стандартов](https://github.com/web-standards-ru/dictionary/blob/main/git.md#pull-request) у нас пулреквесты в одно слово. Наверное потому, что реквест не очень часто встречается. Правда есть слово «пул». Учитывая, что это цельный термин, который изобрёл Гитхаб, то лучше бы его в одно слово. В любом случае, нормализовать бы :)

2021-07-27 21:23 UTC, pepelsbey commented on tools/code-review/practice/igorkamyshev.md
> +При обзоре чужого решения велик соблазн давать мелкие советы. Это называется _эффектом велосипедного сарая_. Он создаётся, потому что для обсуждения сложных, глубоких вопросов нужно сильно погружатьс
```suggestion
При обзоре чужого решения велик соблазн давать мелкие советы. Это называется _эффектом велосипедного сарая_ ([bikeshedding](https://en.wiktionary.org/wiki/bikeshedding)). Он создаётся, потому что для обсуждения сложных, глубоких вопросов нужно сильно погружаться в контекст внесённых изменений, а это трудно. Намного проще написать десяток комментариев о забытых точках с запятой и спокойно продолжить заниматься своей задачей.
```

2021-07-28 06:31 UTC, bespoyasov approved these changes

2021-07-29 14:56 UTC, tachisis commented on tools/code-review/index.md
> +Отправка изменений на код-ревью происходит через **пул-реквесты**. Для прохождения код-ревью нужно получить одобрение одного или нескольких коллег. Способ выбора коллег для проведения ревью зависит о
Я поисследовала вопрос и, честно говоря, мне кажется, что правильнее все-таки через дефис. Ближе всего к этому следующее правило: «Пишутся через дефис: Сложные существительные, имеющие значение одного слова и состоящие из двух самостоятельно употребляющихся существительных, соединенных без помощи соединительных гласных о и е». Но по вхождениям и так и так встречается, и даже через пробел.

2021-07-29 16:19 UTC, pepelsbey commented on tools/code-review/index.md
> +Отправка изменений на код-ревью происходит через **пул-реквесты**. Для прохождения код-ревью нужно получить одобрение одного или нескольких коллег. Способ выбора коллег для проведения ревью зависит о
Давай тогда нормализуем как считаешь нужным. Главное, не через пробел потому, что _што ито воо бще_

2021-07-30 17:41 UTC, tachisis commented on tools/code-review/index.md
> +Отправка изменений на код-ревью происходит через **пул-реквесты**. Для прохождения код-ревью нужно получить одобрение одного или нескольких коллег. Способ выбора коллег для проведения ревью зависит о
Я прослежу, чтобы в следующих статьях было написано через дефис.

2021-08-02 07:27 UTC, bespoyasov approved these changes

2021-08-02 13:17 UTC, pepelsbey approved these changes

2021-08-02 16:47 UTC, merged