Редактирует статью про button
doka-guide/content pull request #1202
Opened 2021-07-29 16:00 UTC by tachisis

2021-07-29 16:01 UTC, tachisis commented on html/button/index.md
> +- `formnovalidate` — добавьте этот атрибут, чтобы браузер не проверял корректность URL или email, который пользователь отправляет через форму.
А это точно только про проверку URL/email, а не про валидацию формы вообще?

2021-07-29 16:01 UTC, tachisis commented on html/button/index.md
>  💡 Если хочется, чтобы пользователь отправил данные вам на сервер по нажатию кнопки, то `<button>` обязательно должен быть внутри контейнера `<form>`.
Или привязан при помощи айдишника же?

2021-07-29 16:02 UTC, tachisis commented on html/button/index.md
> +💡 Тег `<input>` с атрибутом `type="button | reset | submit"` тоже создаёт кнопку, но `<button>` проще стилизовать, так как внутрь `<button>` можно добавить любой HTML-контент, например, `<em>`, `<str
Кажется, что это слегка сомнительный совет

2021-07-29 16:04 UTC, tachisis commented
@solarrust @pepelsbey здесь довольно мало редакторских правок, но у меня возникли некоторые вопросы по сути. Особенно по разделу practice от vladimir. Хочется попросить внимательно глянуть не только мои правки, но и суть статьи.

2021-07-29 16:22 UTC, pepelsbey commented on html/button/index.md
> +💡 Тег `<input>` с атрибутом `type="button | reset | submit"` тоже создаёт кнопку, но `<button>` проще стилизовать, так как внутрь `<button>` можно добавить любой HTML-контент, например, `<em>`, `<str
В целом — всё так: `<button>` более гибкий, кажется всё адекватно.

2021-07-29 16:28 UTC, pepelsbey requested changes
Предлагаю закончить с редакторской правкой и сделать следующую итерацию технической редактуры. Готов взяться.

2021-07-29 16:28 UTC, pepelsbey commented on html/button/index.md
> +  - `menu`: открывает всплывающее меню, которое задано тегом `<menu>`.
```suggestion
```
В спецификации (уже?) нет типа `menu`, только `submit`, `reset`, `button`.

2021-07-29 16:28 UTC, pepelsbey commented on html/button/index.md
> +- `autofocus` — делает так, чтобы при загрузке страницы кнопка уже была выбрана и подсвечена, так что её можно нажать с клавиатуры клавишей Enter.<br>🤔 В Firefox этот атрибут называется `autoсomplete
Дичь какая-то 🤔

2021-07-29 16:38 UTC, pepelsbey commented on html/button/index.md
> +- `autofocus` — делает так, чтобы при загрузке страницы кнопка уже была выбрана и подсвечена, так что её можно нажать с клавиатуры клавишей Enter. 🤔 В Firefox этот атрибут называется `autoсomplete`.
```suggestion
- `autofocus` — делает так, чтобы при загрузке страницы кнопка уже была выбрана и подсвечена, так что её можно нажать с клавиатуры клавишей Enter.
```

Я бы не стал описывать нестандартную и запрещённую особенность работы Firefox. Я проверил: `autofocus` отлично в нём работает.

2021-08-02 07:45 UTC, solarrust commented on html/button/index.md
> +- `formnovalidate` — добавьте этот атрибут, чтобы браузер не проверял корректность URL или email, который пользователь отправляет через форму.
Есть атрибут `novalidate` для тега `<form>`, он полностью отменяет валидацию всей формы. 
А есть атрибут `formnovalidate` для тега `<button>`. Он отменяет проверку емейлов и юрэлов. Хотя там есть ещё пара сценариев. Допишу =)

2021-08-02 13:16 UTC, pepelsbey approved these changes

2021-08-03 05:43 UTC, solarrust approved these changes

2021-08-03 05:43 UTC, merged