Element.dataset
doka-guide/content pull request #1207
Opened 2021-07-30 19:24 UTC by Windrushfarer

Closes #1094

2021-08-02 07:26 UTC, bespoyasov reviewed
Про использование я бы уточнил: мы сейчас говорим о том, _что_ храним, но я бы ещё упомянул, _зачем_ что-то там хранить, в чём их польза, когда их использовать, а когда нет, стоит ли заменять `id` на них, нужно ли их использовать вместо классов и т. д. 

Также, мне кажется, дата-атрибуты лучше набирать через дефис, потому что слово «дата» уже в языке есть, будет путать. @tachisis, что думаешь?

2021-08-02 07:26 UTC, bespoyasov commented on js/element-dataset/index.md
> +Дата атрибут это пользовательский атрибут на элементе, название которого начинается с `data-`, например `data-testid`. Дата атрибут используются чтобы хранить свои значения на элементах в HTML.
```suggestion
Дата атрибут — это пользовательский атрибут на элементе, название которого начинается с `data-`, например `data-testid`. Дата атрибуты используются, чтобы хранить свои значения на элементах в HTML.
```

2021-08-02 07:26 UTC, bespoyasov commented on js/element-dataset/index.md
> +Обращение к `Element.dataset` вернёт объект со всеми дата атрибутами, которые есть на элементе. Названия полей в объекте будут имена дата атрибутов после префикса `data-`. Например если атрибут равен
```suggestion
Обращение к `Element.dataset` вернёт объект со всеми дата атрибутами, которые есть на элементе. Названиями полей в объекте будут имена дата атрибутов после префикса `data-`. Например если атрибут равен `data-columns`, то название поля в объекте для этого атрибута будет равно `colums`.
```

2021-08-02 07:26 UTC, bespoyasov commented on js/element-dataset/index.md
> +Чтобы добавить дата атрибут к элементу нужно добавить новое поле в объект `Element.dataset`. Название поля так же должно быть без префикса `data-`, браузер автоматически его подставит на элемент. В з
```suggestion
Чтобы добавить дата атрибут к элементу, нужно добавить новое поле в объект `Element.dataset`. Название поля так же должно быть без префикса `data-`, браузер автоматически его подставит на элемент. В значениях атрибутов в HTML могут быть только строки, потому любое значение будет автоматически приведено к строке.
```

2021-08-02 07:26 UTC, bespoyasov commented on js/element-dataset/index.md
> +Это правило работает и в обратную сторону – дата атрибут в названии которого содержится несколько слов, разделённых дефисом, в `Element.dataset` будет иметь название поля записанным `camelCase` в одн
```suggestion
Это правило работает и в обратную сторону – дата атрибут в названии которого содержится несколько слов, разделённых дефисом, в `Element.dataset` будет иметь название поля записанным `camelCase` в одно слово.

```

2021-08-02 07:26 UTC, bespoyasov commented on js/element-dataset/index.md
> +Дата атрибуты появились в HTML5 и добавили возможность разработчикам добавлять свои собственные атрибуты к элементам. Использований таким атрибутам можно придумать множество, чаще всего в дата атрибу
```suggestion
Дата атрибуты появились в HTML5 и добавили возможность разработчикам добавлять свои собственные атрибуты к элементам. Причин для использования таких атрибутов можно придумать множество, чаще всего в дата атрибутах хранят нужные значения, которые используют в CSS или JavaScript.
```

2021-08-02 07:26 UTC, bespoyasov commented on js/element-dataset/practice/windrushfarer.md
> +🛠 Дата атрибуты часто используются в автоматизированном тестировании. Для этого на необходимых элементах расставляют дата атрибуты и тест обращаться к ним
```suggestion
🛠 Дата атрибуты часто используются в автоматизированном тестировании. Для этого на необходимых элементах расставляют дата атрибуты и тест обращается к ним
```

2021-08-02 08:14 UTC, Windrushfarer commented
> Про использование я бы уточнил: мы сейчас говорим о том, что храним, но я бы ещё упомянул, зачем что-то там хранить, в чём их польза, когда их использовать, а когда нет, стоит ли заменять id на них, нужно ли их использовать вместо классов и т. д.

Здравая идея, давай я расширю тогда раздел "Как понять"

2021-08-03 18:18 UTC, tachisis commented on js/element-dataset/index.md
> +Дата атрибут это пользовательский атрибут на элементе, название которого начинается с `data-`, например `data-testid`. Дата атрибут используются чтобы хранить свои значения на элементах в HTML.
Да, надо через дефис

2021-08-05 13:59 UTC, nlopin commented on js/element-dataset/index.md
> +`Element.dataset` позволяет считывать или устанавливать любые дата атрибуты на элемент.
Так кажется точнее
```suggestion
`Element.dataset` позволяет считывать или устанавливать любые дата атрибуты на HTML-элемент.
```

2021-08-05 15:23 UTC, nlopin commented on js/element-dataset/index.md
> +firstItem.dataset // Вернет { id: "1541", episode: "1" }
завернём в `console.log`? если выполнить код в консоли, то этот вывод будет не виден

2021-08-05 15:26 UTC, nlopin commented on js/element-dataset/index.md
> +```
Давай разобьем на два примера:
```suggestion

Обращение к `dataset` элемента вернёт данные всех дата атрибутов:

```js
const items = document.querySelectorAll('li')
const firstItem = items[0]

console.log(firstItem.dataset) // { id: "1541", episode: "1" }
```

Если дата атрибутов нет, то вернётся пустой объект:

```js
const heading = document.querySelector('h1')
console.log(heading.dataset) // {}
```

```

2021-08-05 15:29 UTC, nlopin commented on js/element-dataset/index.md
> +```js
Хочется вводной части, тогда отпадёт необходимость добавлять комментарии:

«Добавим несколько дата атрибутов ко второму ситху из примера выше:»

2021-08-05 15:35 UTC, nlopin requested changes
Хороший материал получился 👍

2021-08-05 15:35 UTC, nlopin commented on js/element-dataset/index.md
> +Если в `Element.dataset` к полю присвоить пустое значение, то будет создан дата атрибут без значения.
```suggestion
Если в `Element.dataset` добавить поле с пустым значением, то в HTML будет создан дата атрибут без значения.
```

2021-08-05 15:35 UTC, nlopin commented on js/element-dataset/index.md
> +```html
Кажется эти примеры напрямую относятся к калауту. Надо либо их туда втащить, либо калаут превратить в заголовок

2021-08-05 15:35 UTC, nlopin commented on js/element-dataset/index.md
> +Удалить дата атрибут можно только с помощью оператора `delete`. Если попытаться присвоить к полю значение `undefined` или `null`, то браузер просто присвоит строку `"undefined"` или `"null"`.
```suggestion
Удалить дата атрибут можно только с помощью оператора `delete`. Если попытаться присвоить к полю значение `undefined` или `null`, то браузер просто присвоит атрибуту строку `"undefined"` или `"null"`.
```

2021-08-05 15:35 UTC, nlopin commented on js/element-dataset/index.md
> +// Получится <div data-testid="undefined">Любое содержимое<div>
вот эти комментарии надо выносить из кода и делать их введением перед примером. Посмотри, пожалуйста, пункт 17 [руководства по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md).

2021-08-05 15:35 UTC, nlopin commented on js/element-dataset/practice/windrushfarer.md
> +🛠 Дата атрибуты часто используются в автоматизированном тестировании. Для этого на необходимых элементах расставляют дата атрибуты и тест обращаться к ним
я бы еще добавил, что их часто называют `data-testid` или что-то такое

2021-08-06 12:19 UTC, Windrushfarer commented on js/element-dataset/index.md
> +```html
@nlopin 
Разве в коллауте они будут нормально отображаться? Я раньше пока свои статьи тестил (когда платформа и контент были едины) мне казалось, что пример в коллауте не будет работать. Потому я их с тех пор пишу всегда внизу и так, кстати говоря, во все моих статьях. Если ты уверен, что втащить можно, я сделаю

2021-08-06 12:22 UTC, Windrushfarer commented on js/element-dataset/index.md
> +// Получится <div data-testid="undefined">Любое содержимое<div>
Принял, спасибо! Я когда пишу примеры часто думаю в контексте кода, потому делаю комментарии и думаю, что так и должно быть

2021-08-07 06:56 UTC, nlopin commented on js/element-dataset/index.md
> +```html
Мне сейчас не нравится, что получается такая структура:

* теория про случай 1
* теория про обратный случай 
* пример про случай 1
* пример про обратный случай

Хочется, чтобы они шли в паре теория+пример

2021-08-08 18:27 UTC, bespoyasov commented on js/element-dataset/index.md
> +Это правило работает и в обратную сторону – дата-атрибут в названии которого содержится несколько слов, разделённых дефисом, в `Element.dataset` будет иметь название поля записанным `camelCase` в одн
```suggestion
Это правило работает и в обратную сторону – дата-атрибут в названии которого содержится несколько слов, разделённых дефисом, в `Element.dataset` будет иметь название поля записанным `camelCase` в одно слово.

```

2021-08-08 18:27 UTC, bespoyasov commented on js/element-dataset/index.md
> +Это правило работает и в обратную сторону – дата-атрибут в названии которого содержится несколько слов, разделённых дефисом, в `Element.dataset` будет иметь название поля записанным `camelCase` в одн
(Без пустой строки не сработает парсер, и коллаут не получится.)

2021-08-08 18:27 UTC, bespoyasov commented on js/element-dataset/index.md
> +Дата-атрибутов на элементе может быть сколько угодно, потому удобно располагать отдельные кусочки данных в свой атрибут. Такого точно нельзя достичь, используя только идентификатор.
Ещё, думаю, стоит описать, почему для этого не стоит использовать классы (классы для стилей, дата-атрибуты для данных: _data_ — данные).

2021-08-08 20:43 UTC, nlopin commented
@tachisis как правильно писать: «Дата-атрибуты» или «дата атрибуты»?

2021-08-08 20:46 UTC, pepelsbey commented
> @tachisis как правильно писать: «Дата-атрибуты» или «дата атрибуты»?

Я не Оля, но дата-атрибуты. Без дефиса можно написать только «датные атрибуты» (то есть сделать определение) но это какая-то ерунда :)

2021-08-08 20:54 UTC, bespoyasov commented
Это уже решено здесь:
https://github.com/doka-guide/content/pull/1207#discussion_r681995827

2021-08-09 08:00 UTC, Windrushfarer commented on js/element-dataset/index.md
> +Дата-атрибутов на элементе может быть сколько угодно, потому удобно располагать отдельные кусочки данных в свой атрибут. Такого точно нельзя достичь, используя только идентификатор.
@bespoyasov честно никогда не подумал бы использовать классы для хранения данных 🤯 Ты уверен, что это не перебор? Может я не понимаю твою мысль?

2021-08-09 08:04 UTC, Windrushfarer commented on js/element-dataset/index.md
> +```html
Лучше давай вынесу это из под коллаута тогда. С ним кажется больше проблем сейчас, а мне нужны все 
эти примеры.

2021-08-09 09:27 UTC, Windrushfarer commented
Кто может подсказать, что за проблема с YaSpeller? Локальный запуск ничего не выдает. Слово "виджет" есть в словаре + я добавил окончание

2021-08-09 09:32 UTC, pepelsbey commented
@Windrushfarer регулярка больше не матчится на слово «виджет», нужно вот так `"виджет(ы|ов|)"` (см. пайп в конце)

2021-08-09 09:47 UTC, Windrushfarer commented
> @Windrushfarer регулярка больше не матчится на слово «виджет», нужно вот так `"виджет(ы|ов|)"` (см. пайп в конце)

Спасибо! Поправлю. Все еще правда странно почему локально работает ¯\_(ツ)_/¯

2021-08-09 10:07 UTC, bespoyasov commented on js/element-dataset/index.md
> +Дата-атрибутов на элементе может быть сколько угодно, потому удобно располагать отдельные кусочки данных в свой атрибут. Такого точно нельзя достичь, используя только идентификатор.
Есть очень тонкая грань между data-active и class=is-active.

Второй удобно использовать, когда есть стили для этого состояния, но в целом однозначного ответа, что использовать, нет. 

Проблема тут, конечно — в экстраполяции: «если я могу использовать классы для булевых значений, почему бы не использовать классы для любых данных?»

Не уверен, что это частая проблема, но я видел код с class=js-filter-value-kek, дебажить такое и поддерживать больно. 

@nlopin, как думаешь, надо что-то добавить сюда про классы?

2021-08-09 10:14 UTC, Windrushfarer commented on js/element-dataset/index.md
> +Дата-атрибутов на элементе может быть сколько угодно, потому удобно располагать отдельные кусочки данных в свой атрибут. Такого точно нельзя достичь, используя только идентификатор.
Спасибо за пример! После `data-active` и `class=is-active` стало гораздо лучше. В целом можно просто сильнее подчеркнуть, что дата-атрибуты отличный способ хранить _данные_ в HTML, например текущее значение селекта и т.д.

2021-08-09 10:20 UTC, bespoyasov commented on js/element-dataset/index.md
> +Дата-атрибутов на элементе может быть сколько угодно, потому удобно располагать отдельные кусочки данных в свой атрибут. Такого точно нельзя достичь, используя только идентификатор.
Да, типа того.

2021-08-09 20:28 UTC, Windrushfarer commented on js/element-dataset/index.md
> +Дата-атрибутов на элементе может быть сколько угодно, потому удобно располагать отдельные кусочки данных в свой атрибут. Такого точно нельзя достичь, используя только идентификатор.
@bespoyasov обновил. Посмотри, так достаточно?

2021-08-10 10:00 UTC, bespoyasov approved these changes

2021-08-10 10:57 UTC, pepelsbey commented
@Windrushfarer я [поправил скопом всякое](https://github.com/doka-guide/content/pull/1207/commits/6c4e8dca08e82f2a328622fb247a07790699b6d1), чтобы не затягивать. Посмотри насколько это адекватно

2021-08-10 11:10 UTC, Windrushfarer commented
@pepelsbey спасибо, все хорошо. Докинул еще правку для словаря.

Мне стоит разобраться почему-то локальные проверки не выявляют этих проблем, не хочется вечно гонять CI.

2021-08-11 20:59 UTC, Windrushfarer commented
@nlopin @pepelsbey здесь чего-то ждём ещё?

2021-08-12 21:44 UTC, pepelsbey approved these changes

2021-08-16 10:04 UTC, nlopin approved these changes

2021-08-18 11:19 UTC, tachisis approved these changes
Апрув на словарь

2021-08-18 11:21 UTC, merged