Добавляет статью про вендорные префиксы
doka-guide/content pull request #1208
Opened 2021-08-03 13:10 UTC by solarrust

Закрывает #406

2021-08-03 13:11 UTC, solarrust commented
@pepelsbey хотела коротко, а получилось как всегда 😅 Буду благодарна, если укажешь на моменты, которые нужно осветить, но я упустила.

@tachisis есть пара сложных абзацев. Быстро переосмыслить и переписать не получилось. Будет круто если ты взглянешь.

2021-08-03 14:25 UTC, pepelsbey requested changes
Несмотря на то, что получился лонгрид, я бы его расширил 😅

Стоит рассказать про префиксы в значениях, в директивах, функциях, псевдоэлементах и селекторах:

```
@-webkit-keyframes
::-moz-range-thumb
-webkit-image-set()
-moz-any()
```

Но кажется это не сильно расширяет:

1. Нужно убедиться, что речь не только про свойства (я уже предложил изменения)
2. Рядом с важностью порядка свойств написать про особенности префиксов в директивах, селекторах и функциях (приходится дублировать).
3. Привести больше примеров с разными местами, где могут быть префиксы

2021-08-03 14:25 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +- `-webkit-` — Chrome, Safari, новые версии Opera, практически все браузеры для iOS.
```suggestion
- `-webkit-` — Safari, Chrome, Opera 15+ и другие браузеры на основе движка WebKit или Blink.
```

2021-08-03 14:25 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +- `-moz-` — Firefox.
```suggestion
- `-moz-` — Firefox и браузеры на движке Gecko.
```

2021-08-03 14:25 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +- `-o-` — старые версии Opera.
```suggestion
- `-o-` — Opera 12 и раньше, на движке Presto.
```

2021-08-03 14:25 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +- `-ms-` — Microsoft Edge и Internet Explorer.
```suggestion
- `-ms-` — Internet Explorer и старый Microsoft Edge 12–18.
```

2021-08-03 14:25 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +Браузеры Microsoft Edge, Opera и FireFox перешли на платформу Chromium. Скорее всего, они откажутся от собственных префиксов `-moz-`, `-o-` и `-ms-` в пользу `-webkit-`.
```suggestion
```
Firefox по-прежнему на Gecko. Ну и когда браузеры переходят на новый движок, у них сразу появляются новые префиксы. Так что я бы эту строчку просто не писал.

2021-08-03 14:25 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +Если браузер уже поддерживает свойство без префиксов, то применится последнее из перечисленных свойств. А если нет, то сработает подходящая запись из списка выше.
```suggestion
Это нужно для того, чтобы браузер использовал самую последнюю стабильную реализацию свойства. Если браузер уже поддерживает свойство без префиксов, то применится последнее из перечисленных свойств. А если нет, то сработает подходящая запись из списка выше.
```

2021-08-03 14:25 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +Иногда случается, что CSS-свойство такое классное, что хочется иметь его во всех браузерах. Но некоторые браузеры вышли раньше, чем появилось это свойство 🤷‍♀️ Вендорные префиксы пригодятся и в такой
> некоторые браузеры вышли раньше, чем появилось это свойство 

Не понял, что здесь имеется в виду, звучит парадоксально 🤔

2021-08-04 05:34 UTC, solarrust commented on css/vendor-prefixes/index.md
> +Браузеры Microsoft Edge, Opera и FireFox перешли на платформу Chromium. Скорее всего, они откажутся от собственных префиксов `-moz-`, `-o-` и `-ms-` в пользу `-webkit-`.
Странное искажение в моей голове: была уверена, что FF тоже уже перешёл на Хромиум

2021-08-04 18:07 UTC, tachisis commented on css/vendor-prefixes/index.md
> +Но чаще всего разработчики не пишут префиксы руками, а используют инструменты автоматизации. Самым популярным из них на сегодня является [Автопрефиксер](https://autoprefixer.github.io/ru/). По ссылке
```suggestion
Но чаще всего разработчики не пишут префиксы руками, а используют инструменты автоматизации. Самым популярным из них на сегодня является [Автопрефиксер](https://autoprefixer.github.io/ru/). По ссылке находится онлайн-версия. Вставляете ваш CSS, указываете, какие браузеры должны поддерживаться, и получаете код с проставленными префиксами там, где это нужно.
```

2021-08-05 11:16 UTC, tachisis approved these changes

2021-08-05 16:21 UTC, solarrust commented
@pepelsbey дописала, приходи почитать

2021-08-06 12:02 UTC, pepelsbey requested changes

2021-08-06 12:02 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +Но чаще всего разработчики не пишут префиксы руками, а используют инструменты автоматизации. Самым популярным из них на сегодня является [Автопрефиксер](https://autoprefixer.github.io/ru/). По ссылке
```suggestion
Но чаще всего разработчики не пишут префиксы руками, а используют инструменты автоматизации. Самым популярным из них на сегодня является [Автопрефиксер](https://github.com/postcss/autoprefixer). Вы можете [попробовать его онлайн](https://autoprefixer.github.io/ru/): вставляете ваш CSS, указываете, какие браузеры должны поддерживаться, и получаете код с проставленными префиксами там, где это нужно.
```

Разделил ссылки на инструмент и онлайн-демо, так удобнее применять. Из демо сложнее найти формальную страницу проекта с документацией.

2021-08-06 13:53 UTC, solarrust commented on css/vendor-prefixes/index.md
> +
Куда должна вести ссылки?

2021-08-06 14:03 UTC, pepelsbey commented on css/vendor-prefixes/index.md
> +
На заголовок про автоматизацию ниже, думаю.

2021-08-06 14:07 UTC, solarrust commented on css/vendor-prefixes/index.md
> +
Главное не забыть его потом добавить =)

2021-08-06 14:07 UTC, pepelsbey approved these changes

2021-08-06 14:08 UTC, pepelsbey commented
@tachisis запросил ещё разок, мы нового понаписали с твоего ревью

2021-08-10 08:04 UTC, solarrust commented
@tachisis слила без финальной редактуры. Закинула в ишью

2021-08-10 08:04 UTC, merged