Создаёт скрипт для формирования шаблона статьи
doka-guide/content pull request #1214
Opened 2021-08-04 15:41 UTC by igsekor

Возникла идея утилиты для формирования шаблона материала для авторов.

Для запуска и проверки работы нужно использовать команду:

```bash
./new.sh
```

2021-08-05 06:20 UTC, bespoyasov reviewed
Это сильно уменьшит количество ошибок, особенно, если мы решим сменить схему или флоу написания статей. Огнище! 🔥 

Я, кстати, думаю насчёт кроссплатформенности: если мы хотим поддержать винду, то нам вероятно потребуется ещё и `.cmd`. Но мы можем сделать политическое решение и попросить использовать WSL.

Скорее всего разработчики с виндой уже давно сидят на WSL, поэтому наверное это не будет такой уж сложностью. Что думаешь?

2021-08-05 06:20 UTC, bespoyasov commented on new.sh
> +read -r -p "$(echo "Введите название папки: ")" FOLDER
А может добавим сюда, что название папки отразится в “URL” или напрямую спросим «адрес страницы»? Чтобы было понятно, зачем папку указывать, и на что это повлияет.

2021-08-05 06:20 UTC, bespoyasov commented on new.sh
> +read -r -p "$(echo "Введите ник на GitHub: ")" AUTHOR
Я не знаю, можно ли сделать такую магию, но будет просто невероятно круто, если мы сможем доставать это из глобального гит-конфига.

Правда, в конфиге, вроде, только почта и имя. Возможно, это невозможно 😃

2021-08-05 06:20 UTC, bespoyasov commented on new.sh
> +    "Статья")
```suggestion
    "Статья — расширенный материал, посвящённый определённому вопросу, с авторским мнением, примерами и рассуждениями")
```

2021-08-05 06:20 UTC, bespoyasov commented on new.sh
> +    "Дока")
```suggestion
    "Дока — справочный материал, кратко и формально описывающий какое-то понятие")
```

2021-08-05 06:20 UTC, bespoyasov commented on new.sh
> +read -r -p "$(echo "Создавать новую ветку git? (y/n) ")" RESPONSE
Мне кажется, лучше создавать новые ветки автоматически, чтобы а) не было конфликтов, когда мы выйдем в опен-сорс б) никто не мог обжечься на том, что не смог запушить в main 😃

2021-08-05 06:20 UTC, bespoyasov commented on new.sh
> +read -r -p "$(echo "Создавать новую ветку git? (y/n) ")" RESPONSE
Но тут мне бы ещё послушать мнение @nlopin и @pepelsbey.

2021-08-05 09:07 UTC, pepelsbey commented
> Я, кстати, думаю насчёт кроссплатформенности: если мы хотим поддержать винду, то нам вероятно потребуется ещё и `.cmd`. Но мы можем сделать политическое решение и попросить использовать WSL.

Я бы тестировал все скрипты во встроенных терминалах на ОС без коробки. И если не работает — искал бы пути. Мы не просто так держим этот репозиторий без package.json, чтобы снизить планку участия.

2021-08-05 10:10 UTC, igsekor commented on new.sh
> +read -r -p "$(echo "Создавать новую ветку git? (y/n) ")" RESPONSE
Давайте решим, нужно ли это делать понудительно 😇

2021-08-05 10:21 UTC, igsekor commented
> > Я, кстати, думаю насчёт кроссплатформенности: если мы хотим поддержать винду, то нам вероятно потребуется ещё и `.cmd`. Но мы можем сделать политическое решение и попросить использовать WSL.
> 
> Я бы тестировал все скрипты во встроенных терминалах на ОС без коробки. И если не работает — искал бы пути. Мы не просто так держим этот репозиторий без package.json, чтобы снизить планку участия.

Я протестирую всё, чтобы было кроссплатформенно) А потом ещё и @furtivite вернётся, и протестируем для большинства кейсов 😎

2021-08-05 12:08 UTC, bespoyasov reviewed
На Маке работает шикарно ^_^ 🚀

2021-08-05 12:08 UTC, bespoyasov commented on new.sh
> +read -r -p "$(echo "Введите ник на GitHub (нажмите Enter, и будет использован $LOGIN): ")" AUTHOR
Может случиться, что на почта на гитхабе и почта локально будут разными. Я бы тогда не выводил скобки, а то получится пустота:
<img width="324" alt="«Screenshot» 2021-08-05 at 15 05 56" src="https://user-images.githubusercontent.com/9102374/128347221-d0c37c2c-5834-4a1b-9b55-45622d0cb490.png">

Согласен, что это совсем уж эджкейс, но мало ли. Подумал, что нам стоит об этом знать.

2021-08-05 15:43 UTC, nlopin approved these changes

2021-08-05 15:43 UTC, nlopin commented on new.sh
> +read -r -p "$(echo "Создавать новую ветку git? (y/n) ")" RESPONSE
согласен с тем, что нужно принудительно создавать. Но, конечно, написать об этом

2021-08-05 15:46 UTC, nlopin commented
@igsekor ты тестил на виндоус? У меня есть беспокойство, что может не завестись

2021-08-06 12:06 UTC, igsekor commented
> @igsekor ты тестил на виндоус? У меня есть беспокойство, что может не завестись
> 
> UPD. увидел сообщение выше

У меня заработало на винде)

2021-08-06 12:13 UTC, pepelsbey commented on new.sh
> +read -r -p "$(echo "Создавать новую ветку git? (y/n) ")" RESPONSE
Автоветки норм!

2021-08-06 12:13 UTC, pepelsbey approved these changes

2021-08-08 18:32 UTC, bespoyasov approved these changes
> Как думаете, нужно напомнить, что нужно контролировать вот эту настройку?

Мне кажется, всё, что можно автоматизировать, лучше автоматизировать 🙂 

Мы ещё обязательно нахлебаемся всяких других проблем с разными окружениями, если CRLF можно решить таким образом, давайте сделаем 😃

2021-08-13 07:16 UTC, furtivite requested changes
У меня завелось и работает на Windows. 

Столкнулся с проблемами по шагам:

## Проблема перезаписи

1. Создаю доку с названием "Статья" и адресом "article" в HTML
2. Меня перекидывает в main-ветку, затем в ветку article/article
3. Переключаюсь в тестовую ветку и создаю статью с названием "Статья" и адресом "article" в CSS
4. Файл index.md из существующей папки article удаляется и перезаписывается

Необходимо:

1. Проверять наличие файла с таким же названием и не перезаписывать его
2. Нужно переключать пользователя на новую ветку и кидать в существующий файл, чтобы он мог сделать правки, добавляя человека в поле `contributors`

## Проблема веток

1. Создаю доку с названием "Статья" и адресом "article" в CSS
2. Меня перекидывает в main-ветку, затем в ветку article/article
3. Переключаюсь в тестовую ветку и создаю статью с названием "Статья" и адресом "article" в CSS
4. Получаю ошибку, что ветка article/article уже существует и меня перекидывает в неё

Необходимо:

1. Проверять наличие ветки и, если ветка уже есть, создавать новую, например article/article-1

## Проблема веток 2

1. Создаю доку с названием "Статья" и адресом "article" в CSS
2. Меня перекидывает в main-ветку, затем в ветку article/article
3. Переключаюсь в тестовую ветку и создаю статью с названием "Статья" и адресом "article" в JS
4. Получаю ошибку, что ветка article/article уже существует и меня перекидывает в неё, файл создаётся

Необходимо:

1. Добавить в название ветки название раздела, чтобы получилось article/js-article или что-то подобное.


---

Первая проблема, на мой взгляд критичная, и её надо исправить до мержа.

2021-08-13 10:58 UTC, pepelsbey approved these changes

2021-08-16 16:01 UTC, furtivite approved these changes
Крутяк!

2021-08-16 16:03 UTC, furtivite commented
@igsekor, кажется, можно зарезолвить все обсуждения и сливать

2021-08-17 09:11 UTC, furtivite commented on new.sh
> +mkdir $(echo "$CATEGORY/$FOLDER")
```suggestion
mkdir $(echo "$CATEGORY/$FOLDER")
mkdir $(echo "$CATEGORY/$FOLDER/images")
mkdir $(echo "$CATEGORY/$FOLDER/demos")
mkdir $(echo "$CATEGORY/$FOLDER/practice")
mkdir $(echo "$CATEGORY/$FOLDER/video")
mkdir $(echo "$CATEGORY/$FOLDER/audio")
```

Есть предложение, сразу создать пользователю кучу нужных подпапок в статье с дефолтными названиями, чтобы не надо было бегать по документации и искать, как мы всё называем. Если папка останется пустой, то она не попадёт в отслеживание гитом и у нас не будет мусора в проекте. Если папка будет с содержимым, то не придётся её переименовывать, в случае ошибки.

2021-08-17 09:38 UTC, furtivite commented on new.sh
> +mkdir $(echo "$CATEGORY/$FOLDER")
И ещё вопрос: а не хотим ли мы заодно проверять наличие папки с `$AUTHOR` в папке `/people` и, если такой папки ещё нет, создавать её и предлагать заполнить? Появится ещё один вопрос: "дай адрес своего сайта для папки пипл".

2021-08-17 09:48 UTC, furtivite commented
Пожалуйста, мержте одновременно с #1274 для тестирования #1177

2021-08-17 11:30 UTC, igsekor commented on new.sh
> +mkdir $(echo "$CATEGORY/$FOLDER")
> Есть предложение, сразу создать пользователю кучу нужных подпапок в статье с дефолтными названиями, чтобы не надо было бегать по документации и искать, как мы всё называем. Если папка останется пустой, то она не попадёт в отслеживание гитом и у нас не будет мусора в проекте. Если папка будет с содержимым, то не придётся её переименовывать, в случае ошибки.

Мне кажется, что это не правильно. Что скажите, @pepelsbey @nlopin @bespoyasov @solarrust?

2021-08-17 11:31 UTC, igsekor commented on new.sh
> +mkdir $(echo "$CATEGORY/$FOLDER")
> И ещё вопрос: а не хотим ли мы заодно проверять наличие папки с `$AUTHOR` в папке `/people` и, если такой папки ещё нет, создавать её и предлагать заполнить? Появится ещё один вопрос: "дай адрес своего сайта для папки пипл".

У нас скрипт для создания статьи, а не для создания автора. Кажется, что это усложнит флоу автора... Что думаете, @pepelsbey @nlopin @bespoyasov @solarrust ?

2021-08-17 11:32 UTC, igsekor commented
> Пожалуйста, мержьте одновременно с #1274 для тестирования #1177

А ведь на проверку этой штуки не повлияет?... Там же нет основания генерит индексный файл? Или есть?

2021-08-18 08:01 UTC, furtivite commented
> > Пожалуйста, мержьте одновременно с #1274 для тестирования #1177
> 
> А ведь на проверку этой штуки не повлияет?... Там же нет основания генерит индексный файл? Или есть?

Я бы всё равно проверил, не сломается ли. А так, да, надо проверить при одновременном заливе нескольких статей дополнительно.

2021-08-20 09:34 UTC, merged