Редактирует статью про dl-dt-dd
doka-guide/content pull request #1216
Opened 2021-08-05 11:32 UTC by tachisis

2021-08-05 11:33 UTC, tachisis commented on html/dl-dd-dt/index.md
> +💡 В отличие от списков [`<ul>`](/html/ul/) и [`<ol>`](/html/ol/), группы терминов и определений с недавних пор можно оборачивать в [`<div>`](/html/div/).
Если тут имеется в виду «вместо DL», то может это приписать?

2021-08-06 13:46 UTC, solarrust commented on html/dl-dd-dt/index.md
> +💡 В отличие от списков [`<ul>`](/html/ul/) и [`<ol>`](/html/ol/), группы терминов и определений с недавних пор можно оборачивать в [`<div>`](/html/div/).
```suggestion
💡 В отличие от списков [`<ul>`](/html/ul/) и [`<ol>`](/html/ol/), группы терминов (`<dd>`) и определений (`<dt>`) с недавних пор можно оборачивать в [`<div>`](/html/div/).
```

2021-08-06 14:07 UTC, pepelsbey requested changes

2021-08-06 14:07 UTC, pepelsbey commented on html/dl-dd-dt/index.md
> +Теги `<dl>`, `<dt>` и `<dd>` используются для вёрстки списка определений («dl» означает «description list»).
```suggestion
Теги `<dl>`, `<dt>` и `<dd>` используются для вёрстки списка описаний («dl» означает «description list»).
```
Это он [раньше был](https://twitter.com/pepelsbey/status/1423282066657972229) definition list, а теперь description list, так что и переводить его стоит по-новому.

2021-08-06 14:07 UTC, pepelsbey commented on html/dl-dd-dt/index.md
> +💡 В отличие от списков [`<ul>`](/html/ul/) и [`<ol>`](/html/ol/), группы терминов (`<dd>`) и определений (`<dt>`) с недавних пор можно оборачивать в [`<div>`](/html/div/).
```suggestion
💡 В отличие от списков [`<ul>`](/html/ul/) и [`<ol>`](/html/ol/), группы терминов (`<dt>`) и описаний (`<dd>`) с недавних пор можно оборачивать в [`<div>`](/html/div/).
```

2021-08-06 14:51 UTC, pepelsbey approved these changes

2021-08-09 07:53 UTC, solarrust approved these changes

2021-08-09 07:53 UTC, merged