Element.removeEventListener
doka-guide/content pull request #1223
Opened 2021-08-06 19:26 UTC by Windrushfarer

2021-08-06 21:48 UTC, pepelsbey requested changes
Кажется файл .DS_Store в статье не используется :)

2021-08-06 21:58 UTC, pepelsbey requested changes

2021-08-06 21:58 UTC, pepelsbey commented on js/element-removeeventlistener/demos/keyboard-events.html
> +      const msg = '<code>' + event.key + '</code>'
Тег `<kbd>` подходит для клавиш лучше, это ведь не код.

```suggestion
    kbd {
      font-family: "Roboto Mono", monospace;
    }

    .container {
      width: 500px;
      margin: auto;
    }

    .event {
      position: relative;
      min-height: 100px;
    }

    .event span {
      position: absolute;
      bottom: 0;
      left: 0;
      right: 0;
      font-style: italic;
    }

    .event kbd {
      font-size: 100px;
      line-height: 1;
    }

    .hint {
      margin-top: 20px;
    }

    .inline-key {
      font-size: 0.9em;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="event" id="output"><span>Нажмите любую клавишу</span></div>

    <div class="hint">Чтобы остановить обработку нажатий клавиатуры нажмите <kbd class="inline-key">Escape</kbd></div>
  </div>

  <script>
    const output = document.getElementById('output')

    function handleKey(event) {
      const msg = '<kbd>' + event.key + '</kbd>'
```

2021-08-06 21:58 UTC, pepelsbey commented on js/element-removeeventlistener/index.md
> +  console.log("Вы нажали на элемент:", event.target)
```suggestion
  console.log('Вы нажали на элемент: ', event.target)
```
Нормализует кавычки, добавляет пробел

2021-08-06 21:58 UTC, pepelsbey commented on js/element-removeeventlistener/index.md
> +  console.log("Вы нажали на элемент:", event.target)
```suggestion
  console.log('Вы нажали на элемент: ', event.target)
```

2021-08-06 21:58 UTC, pepelsbey commented on js/element-removeeventlistener/practice/windrushfarer.md
> +}, { once: true }) // установим опцию once: true
```suggestion
  // установим опцию once: true
}, { once: true })
```

2021-08-06 21:58 UTC, pepelsbey commented on js/element-removeeventlistener/practice/windrushfarer.md
> +Другой пример может быть очищение обработчика по определённому условию. Например добавим обработчик события клавиатуры, но по нажатию клавиши Esc будет очищать его.
```suggestion
Другой пример может быть очищение обработчика по определённому условию. Например добавим обработчик события клавиатуры, но по нажатию клавиши <kbd>Esc</kbd> будет очищать его.
```

2021-08-06 21:58 UTC, pepelsbey commented on js/element-removeeventlistener/practice/windrushfarer.md
> +  console.log('Нажата клавиша:', event.key)
```suggestion
  console.log('Нажата клавиша: ', event.key)
```

2021-08-06 21:58 UTC, pepelsbey commented on js/element-removeeventlistener/index.md
> +Например создадим обработчик события и передадим третьим аргументом в опциях значение `true`. Если попробовать убрать событие, но ничего не передать в `Element.removeEventListener` в третий аргумент,
```suggestion
Например создадим обработчик события и передадим третьим аргументом в опциях значение `true`. Если попробовать убрать событие, но ничего не передать в `Element.removeEventListener` в третий аргумент, но событие не уберётся. Это происходит потому что раз ничего не передали, значит это `undefined`, `undefined` — это falsy значение. В итоге когда браузер ищет обработчик, он сравнивает опции и видит, что `true !== false`, значит обработчик не будет удалён.
```

2021-08-06 21:58 UTC, pepelsbey commented on js/element-removeeventlistener/practice/windrushfarer.md
> +  // Сразу же очищаем после вызова функции, значит обработчие сработает только один раз
```suggestion
  // Сразу же очищаем после вызова функции,
  // значит обработчие сработает только один раз
```

Если уж писать инлайновые комментарии, то хотя бы покороче, чтобы на узких экранах не приходилось крутить

2021-08-08 11:50 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Будет ли на самом деле удалён обработчик события зависит от того какую функцию и опции были переданы вторым и третьим аргументами в `Element.removeEventListener`.
Вот эта часть уже про «Как понимать», давай объяснение как отписываться унесём туда и оставим в этом разделе только пример и стартовое описание

2021-08-08 11:52 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Сначала добавим обработчик на элемент, например будем обрабатывать клики на любые место в окне. Затем уберём обработчик, используя ту же самую функцию.
```suggestion
Добавим обработчик на элемент, а затем уберём его. Например, будем обрабатывать клики на любое место на странице. Затем уберём обработчик, передав в `removeEventListener` те же параметры, что и при добавлении:
```

2021-08-08 12:03 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Убирает с элемента обработчик события, например нажатие клавиатуры, поставленный с помощью [Element.addEventListener](/js/element-addeventlistener).
```suggestion
Убирает с элемента обработчик события, установленный с помощью [Element.addEventListener](/js/element-addeventlistener).
```

2021-08-08 12:05 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Функции относятся к [ссылочным](/js/ref-type-vs-value-type) типам данных, а значит две одинаково написанные функции не являются одной и той же функцией. Потому, если ранее в `Element.addEventListener
сделал ссылку подлиннее:
```suggestion
Функции относятся к [ссылочным типам данных](/js/ref-type-vs-value-type), а значит две одинаково написанные функции будут считаться различными. Поэтому, если ранее в `Element.addEventListener` использовалась анонимная функция, то убрать обработчик с помощью `Element.removeEventListener` не получится.
```

2021-08-08 12:05 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Изменим пример выше и будем использовать анонимную функцию в качестве обработчика:
может демку?

2021-08-08 12:06 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Опции, которые переданы в `Element.removeEventListener`, тоже влияют будет ли удалён обработчик события. Обычно рекомендуют повторять в точности те же параметры, которые использовались в `Element.add
```suggestion
Опции, которые переданы в `Element.removeEventListener`, также влияют на удаление обработчика события. Мы рекомендуем повторять в точности те же параметры, которые использовались в `Element.addEventListener`.
```

2021-08-08 12:07 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Например создадим обработчик события и передадим третьим аргументом в опциях значение `true`. Если попробовать убрать событие, но ничего не передать в `Element.removeEventListener` в третий аргумент,
надо бы еще рассказать, за что отвечает третий аргумент

2021-08-08 12:09 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Очищать обработчики событий важно, потому что каждый обработчик занимает место в памяти и выполняется всякий раз, когда срабатывает событие. Если не убирать вовремя ненужные обработчики событий можно
```suggestion
Очищать обработчики событий важно, потому что каждый обработчик занимает место в памяти и выполняется всякий раз, когда срабатывает событие. Если не убирать вовремя ненужные обработчики событий, то можно столкнуться с неожиданным поведением. Например, один из старых обработчиков может мешать всплытию события наверх, и другой обработчик не будет работать.
```

2021-08-08 12:09 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Хорошим тоном считается убирать обработчик сразу же, как только он перестал быть нужен.
Звучит как калаут

2021-08-08 12:11 UTC, nlopin commented on js/element-removeeventlistener/practice/windrushfarer.md
> +После первого клика событие сработает и обработчик автоматически очистится. В этом случае можно даже использовать анонимную функцию, так как нам не нужно очищать обработчик вручную.
```suggestion
При первом клике обработчик сработает, а затем автоматически удалится. В этом случае можно даже использовать анонимную функцию, так как не нужно очищать обработчик вручную.
```

2021-08-08 12:11 UTC, nlopin commented on js/element-removeeventlistener/practice/windrushfarer.md
> +🛠 Можно написать очищение обработчика в самом обработчике событий
классно, что это подсветил 👍

2021-08-08 12:12 UTC, nlopin commented on js/element-removeeventlistener/practice/windrushfarer.md
> +Когда в браузерах не было возможности использовать опцию `{ once: true }` при установке обработчика события, такое же поведение можно было сделать самостоятельно.
```suggestion
Когда в браузерах не было возможности использовать опцию `{ once: true }` при установке обработчика события, такое поведение делали самостоятельно:
```

2021-08-08 12:13 UTC, nlopin commented on js/element-removeeventlistener/practice/windrushfarer.md
> +  console.log('Нажата клавиша:', event.key)
здесь не нужен пробел, если в `console.log` передается несколько аргументов, он конкатенирует их пробелом автоматически

2021-08-08 12:21 UTC, nlopin requested changes
* Нужно переработать структуру, раздел «Как пишется» содержит детали, которые нужно унести в «как понять»
* в «как понять» нужно добавить описание параметров функции, сейчас мы говорим, о них так, будто читателю про них всё известно (посмотрел, что в `addEventListener` тоже этого нет, добавил задачу #1224)

2021-08-08 18:21 UTC, bespoyasov reviewed
Мне, в общем-то, добавить нечего, за меня всё уже сказали 😃

2021-08-08 20:40 UTC, nlopin commented
> Кажется файл .DS_Store в статье не используется :)

Добавляем в гитигнор?

2021-08-08 20:43 UTC, pepelsbey commented
> @pepelsbey Добавляем в гитигнор?

А также все файлы, которые автор случайно может добавить с помощью `git add .`? :) Мне больше нравится подход, в котором в игноре хранятся релевантные для проекта исключения, а не все файлы в мире.

Но можем обсудить в среду.

2021-08-09 08:08 UTC, Windrushfarer commented
> А также все файлы, которые автор случайно может добавить с помощью `git add .`? :) Мне больше нравится подход, в котором в игноре хранятся релевантные для проекта исключения, а не все файлы в мире.
> 
> Но можем обсудить в среду.

Это может быть необзятально, это первый раз когда я пропустил `.DS_store`, обычно я удаляю его. Тут просочилось

2021-08-09 08:10 UTC, Windrushfarer commented on js/element-removeeventlistener/index.md
> +Изменим пример выше и будем использовать анонимную функцию в качестве обработчика:
Я не очень понимаю как такое делать в демках. Демки это конечно круто, но они больше именно про то как самому что-то покрутить и увидеть визуальный результат. Если бы у нас были демки в сандбоксе каком-нибудь, где слева код, а справа результат, то тогда можно еще.

2021-08-09 22:20 UTC, pepelsbey requested changes

2021-08-09 22:20 UTC, pepelsbey commented on js/element-removeeventlistener/index.md
> +* функция-обработчик, которую нужно убрать с указанного события
```suggestion
`Element.removeEventListener` принимает три аргумента. Первые два обязательные:

- название события в виде строки
- функция-обработчик, которую нужно убрать с указанного события
```

2021-08-09 22:20 UTC, pepelsbey commented on js/element-removeeventlistener/index.md
> +Убирает с элемента обработчик события, установленный с помощью [Element.addEventListener](/js/element-addeventlistener).
```suggestion
Убирает с элемента обработчик события, установленный с помощью [`Element.addEventListener`](/js/element-addeventlistener).
```

2021-08-09 22:20 UTC, pepelsbey commented on js/element-removeeventlistener/index.md
> +Так происходит потому что пустой аргумент равен `undefined`, а `undefined` — это falsy значение. Когда браузер ищет обработчик на удаление, он сравнивает опции и видит, что `true !== false`, значит о
Я бы пояснил, что такое «falsy», это не то, чтобы общее знание среди начинающих.

2021-08-09 22:20 UTC, pepelsbey commented on js/element-removeeventlistener/index.md
> +:::callout 👇
```suggestion
::: callout 👇
```

2021-08-10 10:11 UTC, nlopin commented on js/element-removeeventlistener/index.md
> +Так происходит потому что пустой аргумент равен `undefined`, а `undefined` — это falsy значение. Когда браузер ищет обработчик на удаление, он сравнивает опции и видит, что `true !== false`, значит о
Исправил формулировку

2021-08-10 10:12 UTC, nlopin approved these changes

2021-08-10 10:43 UTC, pepelsbey approved these changes

2021-08-10 14:31 UTC, merged