Добавляет статью «Что может читать сайт, кроме браузера?»
doka-guide/content pull request #1225
Opened 2021-08-09 11:18 UTC by igsekor

В статье содержится информация о том, какие программы / сервисы могут парсить HTML-страницу. Рассмотрены поисковые роботы и скринридеры (предполагается отдельные статьи о доступности, поэтому совсем по верхам).

2021-08-10 10:11 UTC, bespoyasov reviewed
Мне понравилось, особенно количество ссылок на ресурсы и тулзы — круто!

Давай добавим какое-нибудь заключение? А то пост заканчивается как-то обрывисто и внезапно.

2021-08-10 10:11 UTC, bespoyasov commented on tools/site-readers/index.md
> +Современный сайт — это не только интерфейс пользователя. Чтобы сайт «взлетел» нужно многое добавить после реализации макета в вёрстке. Наряду с быстродействием, оптимизацией загрузки контента и кода,
```suggestion
Современный сайт — это не только интерфейс пользователя. Чтобы сайт «взлетел» нужно многое добавить после реализации макета в вёрстке. Наряду с быстродействием, оптимизацией загрузки контента и кода, важно уделить внимание настройке сайта под поисковые системы и социальные сети, отработать вариант использования сайта с помощью скринридеров и другое. 

Для этого необходимо разобраться с тем, как различные сервисы, службы, приложения «читают» ваш сайт, как подготовить его для них и как сделать это правильно.
```

2021-08-10 10:11 UTC, bespoyasov commented on tools/site-readers/index.md
> +Наверняка вы слышали про поисковую оптимизацию (Search Engine Optimization), суть которой заключается в том, чтобы вы сначала появились в поисковом индексе Yandex, Google, Bing и прочих поисковых сис
```suggestion
Наверняка вы слышали про поисковую оптимизацию (Search Engine Optimization), суть которой заключается в том, чтобы вы сначала появились в поисковом индексе Yandex, Google, Bing и прочих поисковых системах, а потом стали приближаться к первой странице выдачи по определённым поисковым запросам пользователей. Соответственно, процесс оптимизации состоит из двух больших этапов:
```

2021-08-10 10:11 UTC, bespoyasov commented on tools/site-readers/index.md
> +По адресам страниц из базы данных регулярно заходит поисковый робот (веб-паук, веб-краулер), основной функцией которого является составить [поисковый индекс](https://ru.wikipedia.org/wiki/Поисковый_и
```suggestion
По адресам страниц из базы данных регулярно заходит поисковый робот (веб-паук, веб-краулер), основной функцией которого является составить [поисковый индекс](https://ru.wikipedia.org/wiki/Поисковый_индекс).

**Индексация** — это составление статистического отчёта о содержимом страницы по определённым правилам. На основе этого отчёта и ряда других факторов определяется положение страницы в рейтинге релевантности по тому или иному поисковому запросу пользователя. Современные поисковые системы содержат тысячи критериев для определения этого положения относительно других страниц. Важно подготовить каждую страницу для встречи с поисковым ботом, результаты этой встречи сильно повлияют на популярность вашего сайта.
```

2021-08-10 10:11 UTC, bespoyasov commented on tools/site-readers/index.md
> +Попасть в индекс — это только первый шаг. Рейтинг вашей страницы в интернете всё время меняется. На положение страницы в рейтинге оказывают влияние не только количество страниц, которые ссылаются на
```suggestion
Попасть в индекс — это только первый шаг. Рейтинг вашей страницы в интернете всё время меняется. На положение страницы в рейтинге оказывают влияние не только количество страниц, которые ссылаются на вашу страницу, но и контент. Большое значение имеет поведение пользователя на страницы. Чем больше пользователь взаимодействует со страницей, тем лучше. Поэтому важно уделять внимание содержимому, дизайну, пользовательскому опыту.
```

2021-08-10 10:11 UTC, bespoyasov commented on tools/site-readers/index.md
> +Веб-краулер регулярно заходит по существующим адресам в базе и проверяет наличие страницы или ответ сервера при запросе страницы. Если статус страницы корректен, а содержимое изменилось, то бот произ
```suggestion
Веб-краулер регулярно проходит по существующим адресам в базе и проверяет наличие страницы или ответ сервера при запросе страницы. Если статус страницы корректен, но содержимое изменилось, то бот производит индексацию заново обновляет информацию о странице в базе данных. Период проверок меняется, как правило, в зависимости от популярности страницы у пользователей.
```

2021-08-10 10:11 UTC, bespoyasov commented on tools/site-readers/index.md
> +В примере первый тег отвечает за заголовок карточки, в виде которой отображается ссылка, второй — задаёт тип карточки, третий — определяет абсолютную ссылку. Доступны и другие возможности. Можно уста
Давай добавим пример, как карточка будет выглядеть?

2021-08-10 10:11 UTC, bespoyasov commented on tools/site-readers/index.md
> +Существует альтернативный способ разметить элементы страницы так, чтобы поисковая система понимала их назначение, — это микроразметка. Это даёт возможность поисковой системе разбираться в контенте то
Тут, наверное, тоже будет полезно привести скриншот ссылки в Гугле на компанию с микроразметкой и без, чтобы "почувствовать разницу" так сказать 😃

2021-08-10 10:50 UTC, tachisis approved these changes
Апрув на словарь

2021-08-10 22:27 UTC, pepelsbey requested changes

2021-08-10 22:27 UTC, pepelsbey commented on tools/site-readers/index.md
> +<meta property="og:url" content="https://www.example.com/" />
```suggestion
<meta property="og:title" content="Заголовок">
<meta property="og:type" content="website">
<meta property="og:url" content="https://www.example.com/">
```

2021-08-10 22:27 UTC, pepelsbey commented on tools/site-readers/index.md
> +</article>
```suggestion
<article itemscope itemtype="http://schema.org/Article">
  <section itemscope itmetype="http://schema.org/Person" itemprop="author">
    <p>
      Автор статьи:
      <span itemprop="givenName">Василий</span>
      <span itemprop="familyName">Иванов</span>
      (<span itemprop="jobTitle">Штатный корреспондент</span>)
    </p>
  </section>
</article>
```

Убрал … и отформатировал понятнее.

2021-08-10 22:27 UTC, pepelsbey commented on tools/site-readers/index.md
> +</head>
```suggestion
<head>
  <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Article",
      "author": {
        "@type": "Person",
        "givenName": "Василий",
        "familyName": "Иванов",
        "jobTitle": "Штатный корреспондент"
      }
    }
  </script>
</head>
```

Убрал … и сделал честный отступ

2021-08-10 22:27 UTC, pepelsbey commented on tools/site-readers/index.md
> +Для людей с нарушениями зрения внешний вид вашего сайта может не иметь никакого значения. Важно, как ваш сайт «звучит». Существуют специальные расширения для браузера (скринридеры), которые позволяют
Я бы сформулировал лучше, что речь не только про незрячих, а всех, кому так удобнее. Например, человек с ДЦП, который не может пользоваться мышкой, но прекрасно видит, может пользоваться скринридером, чтобы удобно перемещаться по экрану.

2021-08-10 22:27 UTC, pepelsbey commented on tools/site-readers/index.md
> +- [NVDA (NonVisual Desktop Access)](https://www.nvaccess.org/about-nvda/), в меру удобный, но бесплатный клиент под Windows.
```suggestion
- [JAWS](https://support.freedomscientific.com/JAWSHQ/JAWSHeadquarters01), удобный платный клиент под Windows и бесплатный под DOS.
- [NVDA](https://www.nvaccess.org/about-nvda/), в меру удобный, но бесплатный клиент под Windows.
```

Мне кажется, что расшифровка названий здесь избыточна. Достаточно их запомнить, тут фокус другой.

2021-08-10 22:27 UTC, pepelsbey commented on tools/site-readers/index.md
> +Существуют специальные атрибуты для тегов, которые начинаются с префикса `aria-`, которые позволяют настроить работу скринридера детальнее, не отдавая всё на откуп автоматики. Подробнее можно ознаком
```suggestion
Существуют специальные атрибуты для тегов, которые начинаются с префикса `aria-`, которые позволяют настроить работу скринридера детальнее, не отдавая всё на откуп автоматики. Подробнее можно ознакомиться в [спецификации](https://www.w3.org/TR/wai-aria/).
```

Кажется такая ссылка будет содержать самую последнюю версию спеки.

2021-08-11 07:33 UTC, igsekor commented on tools/site-readers/index.md
> +Для людей с нарушениями зрения внешний вид вашего сайта может не иметь никакого значения. Важно, как ваш сайт «звучит». Существуют специальные расширения для браузера (скринридеры), которые позволяют
Попробовал дополнить...

2021-08-11 07:45 UTC, igsekor commented on tools/site-readers/index.md
> +Существует альтернативный способ разметить элементы страницы так, чтобы поисковая система понимала их назначение, — это микроразметка. Это даёт возможность поисковой системе разбираться в контенте то
@bespoyasov а как мы это сделаем, если гугл сам решает, когда пользоваться микроразметкой, а когда нет. Будем гадать-искать успешный кейс?

2021-08-11 07:45 UTC, igsekor commented on tools/site-readers/index.md
> +В примере первый тег отвечает за заголовок карточки, в виде которой отображается ссылка, второй — задаёт тип карточки, третий — определяет абсолютную ссылку. Доступны и другие возможности. Можно уста
Ты имеешь в виду Facebook?

2021-08-11 08:11 UTC, igsekor commented
> Давай добавим какое-нибудь заключение? А то пост заканчивается как-то обрывисто и внезапно.

Попробовал добавить в резюме чек-лист того, что нужно протестировать и реализовать. Что скажите?

2021-08-12 12:30 UTC, bespoyasov approved these changes

2021-08-12 12:30 UTC, bespoyasov commented on tools/site-readers/index.md
> +В примере первый тег отвечает за заголовок карточки, в виде которой отображается ссылка, второй — задаёт тип карточки, третий — определяет абсолютную ссылку. Доступны и другие возможности. Можно уста
Можно его, можно ещё что-нибудь: Твитер, ВК. Чтобы просто видно было, зачем тратить силы на это.

2021-08-12 12:30 UTC, bespoyasov commented on tools/site-readers/index.md
> +Существует альтернативный способ разметить элементы страницы так, чтобы поисковая система понимала их назначение, — это микроразметка. Это даёт возможность поисковой системе разбираться в контенте то
Я думаю просто найти страницу, для которой гугл использует микроразметку и сравнить её с любой другой «обычной» страницей.

Типа смотрите: здесь дополнительные ссылки под ссылкой есть, тут текст вот таким красивым островком выделен, тут вот номер телефона подсвечен и т. д. а на обычной странице — нет.

2021-08-12 17:49 UTC, igsekor commented on tools/site-readers/index.md
> +Существует альтернативный способ разметить элементы страницы так, чтобы поисковая система понимала их назначение, — это микроразметка. Это даёт возможность поисковой системе разбираться в контенте то
Хорошо, я подумаю. Идея-то отличная!

2021-08-12 17:50 UTC, igsekor commented on tools/site-readers/index.md
> +В примере первый тег отвечает за заголовок карточки, в виде которой отображается ссылка, второй — задаёт тип карточки, третий — определяет абсолютную ссылку. Доступны и другие возможности. Можно уста
Надо будет сделать)

2021-08-17 14:09 UTC, bespoyasov approved these changes
👍 🚀

2021-08-17 21:40 UTC, pepelsbey approved these changes

2021-08-20 06:56 UTC, merged