Редизайн демо в статье form
doka-guide/content pull request #1232
Opened 2021-08-09 13:58 UTC by skorobaeus

2021-08-09 14:24 UTC, pepelsbey requested changes
И тут rel="stylesheet" попрыгали. Кажется дело в том, что это такой снипет Google Fonts. Предлагаю копировать только строку href="…", чтобы остальное было как в шаблоне.

2021-08-09 14:24 UTC, pepelsbey commented on html/form/demos/email.html
> +
```suggestion
```

2021-08-09 14:24 UTC, pepelsbey commented on html/form/demos/email.html
> +    }
Мы целимся не только в один браузер (Chrome, Safari, Firefox) и лучше не залезать во внутренности контролов форм — это может сломаться и не будет работать везде.

2021-08-09 14:24 UTC, pepelsbey commented on html/form/demos/forms.html
> +    }
Аналогично

2021-08-10 06:15 UTC, skorobaeus commented
> И тут rel="stylesheet" попрыгали. Кажется дело в том, что это такой снипет Google Fonts. Предлагаю копировать только строку href="…", чтобы остальное было как в шаблоне.

Да, это на Google Fonts rel="stylesheet" в конце. Там сейчас ещё одна строка добавилась:

`<link rel="preconnect" href="https://fonts.googleapis.com">`

Но без неё всё работало и работает, так что я не копирую :D

2021-08-10 09:34 UTC, solarrust approved these changes

2021-08-10 09:42 UTC, solarrust approved these changes

2021-08-10 10:59 UTC, pepelsbey approved these changes

2021-08-10 17:07 UTC, merged