Редизайн демо в статьях input и label
doka-guide/content pull request #1238
Opened 2021-08-09 14:17 UTC by skorobaeus

2021-08-09 14:29 UTC, pepelsbey requested changes

2021-08-09 14:29 UTC, pepelsbey commented on html/input/demos/inputs.html
> +      caret-color: #ffffff;
Лучше не надо

2021-08-09 14:29 UTC, pepelsbey commented on html/label/demos/label-input.html
> +    }
Аналогично

2021-08-09 14:41 UTC, skorobaeus commented
Не знаю, что делать со сломанной ссылкой :( 

`Error: [404] html/TODO`

2021-08-10 10:09 UTC, solarrust approved these changes

2021-08-10 10:46 UTC, pepelsbey approved these changes

2021-08-10 17:08 UTC, merged