Редактирует статью про bg-color
doka-guide/content pull request #1243
Opened 2021-08-10 13:16 UTC by tachisis

2021-08-10 13:17 UTC, tachisis commented on css/background-color/index.md
У меня есть сомнения в этом разделе: кажется, что все-таки верный перевод «фоновый цвет». @pepelsbey помоги

2021-08-10 13:25 UTC, pepelsbey requested changes

2021-08-10 13:25 UTC, pepelsbey commented on css/background-color/practice/solarrust.md
> +🛠 Если нужна красивая кнопка (`button`), то не забудьте _сбросить_ фон: укажите для неё `background-color: transparent`. Или тот цвет фона, который нужен по дизайну. По умолчанию у всех кнопок серый
```suggestion
🛠 Если нужна красивая кнопка (`<button>`), то не забудьте _сбросить_ фон: укажите для неё `background-color: transparent`. Или тот цвет фона, который нужен по дизайну. По умолчанию у всех кнопок серый фон с приветом из девяностых.
```

2021-08-10 13:25 UTC, pepelsbey commented on css/background-color/index.md
Ты про заливку абзацем выше?

2021-08-10 13:25 UTC, pepelsbey commented on css/background-color/index.md
Ты про заливку абзацем выше?

2021-08-17 19:06 UTC, tachisis commented on css/background-color/index.md
@pepelsbey я про строчку абзацем ниже: «Слово **color** переводится с английского как цвет. Дословно всё свойство можно перевести как фон-цвет. Говоря человеческим языком — цвет фона».

не нравится она мне

2021-08-17 21:21 UTC, pepelsbey commented on css/background-color/index.md
Согласен, мы там слишком долго идём к тому, что можно сказать проще. Плюс в других статьях мы не переводим названия тегов и свойств. Там сразу после идёт полезная фраза про то, что это свойство делает. Мне кажется, что строчку можно просто убрать.

2021-08-18 06:28 UTC, solarrust commented on css/background-color/index.md
Убрала перевод

2021-08-18 19:29 UTC, solarrust approved these changes

2021-08-18 22:57 UTC, pepelsbey approved these changes

2021-08-19 04:58 UTC, merged