Редактирует статью про autocomplete
doka-guide/content pull request #1255
Opened 2021-08-11 16:36 UTC by tachisis

2021-08-11 16:43 UTC, tachisis commented on html/autocomplete/index.md
> +- ?`autocomplete` — позволяет вводить данные разного вида в зависимости от значения атрибута. Ниже приведены возможные значения в алфавитном порядке.
Не понимаю, почему это первый элемент списка. Это ведь обобщающая фраза? Или такое значение тоже может быть? Тогда надо отрезать предложение про возможные значения.

Вообще я бы этот список предложила дать не в алфавитном порядке, а разбить по категориям — так будет легче восприниматься.

2021-08-12 21:40 UTC, pepelsbey commented on html/autocomplete/index.md
> +    <summary>Список всех возможных значений атрибута</summary>
> Вообще я бы этот список предложила дать не в алфавитном порядке, а разбить по категориям — так будет легче восприниматься.

Поддержу @tachisis. Сейчас у нас как сортировка CSS-свойств по алфавиту: очень понятно, но очень неудобно. Нужно вам поля для адреса насобирать? Удачи (

2021-08-12 21:41 UTC, pepelsbey commented
@tachisis дерзнул и [вытащил описание из списка](https://github.com/doka-guide/content/pull/1255/commits/5e1408e95b9a513413b2cf8ef88fb5858998e338)

2021-08-13 06:47 UTC, solarrust commented
@pepelsbey @tachisis разбила значения на группы. Пожалуйста, посмотрите, норм ли разбивка

2021-08-13 10:54 UTC, pepelsbey requested changes

2021-08-13 10:54 UTC, pepelsbey commented on html/autocomplete/index.md
> +- `impp` - url для доступа к протоколу обмена мгновенными сообщениями, например, _xmpp:username@example.net_.
```suggestion
- `impp` — адрес сервера для мессенджера, например, _xmpp:username@example.net_.
```

2021-08-13 10:54 UTC, pepelsbey commented on html/autocomplete/index.md
> +- `url` — url-адрес сайта.
```suggestion
- `url` — адрес сайта.
```

2021-08-13 10:54 UTC, pepelsbey commented on html/autocomplete/index.md
>  - `language` — язык в формате языкового тега, определённого BCP 47.
```suggestion
- `language` — язык в формате языкового тега из [списка BCP 47](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry).
```

2021-08-13 12:43 UTC, solarrust approved these changes

2021-08-13 13:06 UTC, pepelsbey approved these changes

2021-08-13 13:06 UTC, merged