Редизайн демок в Событиях
doka-guide/content pull request #1259
Opened 2021-08-12 13:56 UTC by skorobaeus

2021-08-16 18:46 UTC, bespoyasov requested changes
Кажется, демки не работают, или я смотрю не туда?

https://user-images.githubusercontent.com/9102374/129614190-b2c25da4-a202-4f1e-95d8-c224e45958a8.mov

2021-08-17 12:26 UTC, skorobaeus commented
> Кажется, демки не работают, или я смотрю не туда?
> 
>  Screenshot.2021-08-16.at.21.45.19.mov

Пока на платформе нет стилей, демка отображается в маленьком окошке. Квадрат, у которого меняется цвет, справа от кнопок и его не видно. Если временно задать для айфремов `width: 100%`, будет видно

2021-08-17 14:01 UTC, bespoyasov commented
А-а, тогда понятно. Сорри :—)

2021-08-17 14:02 UTC, bespoyasov approved these changes

2021-08-23 15:21 UTC, nlopin approved these changes

2021-08-23 15:21 UTC, merged