Добавляет статью про контекст наложения
doka-guide/content pull request #1267
Opened 2021-08-12 17:51 UTC by solarrust

Закрывает #413

2021-08-12 18:21 UTC, solarrust commented
@pepelsbey эта тема оказалась очень сложной для ладного-складного повествования. Буду благодарна за твои советы 🥲

2021-08-12 22:14 UTC, pepelsbey requested changes
Чуть форматнул демки, а так кажется норм :) Просто о сложном

2021-08-12 22:14 UTC, pepelsbey commented on css/stacking-context/index.md
> +Но мы можем не подчиняться стандартным правилам браузера и устанавливать свой порядок наложения элементов друг на друга. Для этого понадобиться свойство [`z-index`](/css/z-index).
```suggestion
Но мы можем не подчиняться стандартным правилам браузера и устанавливать свой порядок наложения элементов друг на друга. Для этого понадобится свойство [`z-index`](/css/z-index).
```

2021-08-12 22:14 UTC, pepelsbey commented on css/stacking-context/demos/z-index.html
> +    }
```suggestion
    .block {
      width: 150px;
      height: 150px;
      border: 5px solid black;
      box-sizing: border-box;
    }

    .first {
      position: relative;
      z-index: 1;
      background-color: #1A5AD7;
    }

    .second {
      margin-top: -50px;
      margin-left: 50px;
      background-color: #c000ff;
    }

    .third {
      margin-top: -50px;
      background-color: #09ff00;
    }
```

2021-08-12 22:14 UTC, pepelsbey commented on css/stacking-context/demos/under-bkg.html
> +    }
```suggestion
    * {
      box-sizing: border-box;
    }

    .block {
      position: relative;
      z-index: 1;
      width: 150px;
      height: 150px;
      padding: 15px;
      border: 5px solid black;
    }

    .parent {
      background-color: #1A5AD7;
    }

    .child {
      width: 50px;
      height: 50px;
      border: 1px dashed;
      background-color: #663613;
    }

    .red {
      margin-top: -25px;
      margin-left: 25px;
      background-color: #cd445d;
    }

    .yellow {
      position: relative;
      z-index: -9999999;
      margin-top: -25px;
      margin-left: 90px;
      background-color: #ffd829;
    }
```

2021-08-12 22:14 UTC, pepelsbey commented on css/stacking-context/demos/parent.html
> +    }
```suggestion
    * {
      box-sizing: border-box;
    }

    .block {
      position: relative;
      z-index: 1;
      width: 150px;
      height: 150px;
      padding: 15px;
      border: 5px solid black;
    }

    .parent {
      background-color: #1A5AD7;
    }

    .child {
      width: 50px;
      height: 50px;
      border: 1px dashed;
      background-color: #663613;
    }

    .red {
      margin-top: -25px;
      margin-left: 25px;
      background-color: #cd445d;
    }

    .yellow {
      position: relative;
      z-index: 9999999;
      margin-top: -25px;
      margin-left: 50px;
      background-color: #ffd829;
    }

    .no-parent {
      margin-top: -50px;
      margin-left: 50px;
      background-color: #c000ff;
    }
```

2021-08-12 22:14 UTC, pepelsbey commented on css/stacking-context/demos/default.html
> +    }
```suggestion
    .block {
      width: 150px;
      height: 150px;
      border: 5px solid black;
      box-sizing: border-box;
    }

    .first {
      background-color: #1A5AD7;
    }

    .second {
      margin-top: -50px;
      margin-left: 50px;
      background-color: #c000ff;
    }
```

2021-08-13 10:57 UTC, pepelsbey requested changes
Только заметил, что в демках нигде не используется текст, так что и подключение шрифтов не нужно :)

2021-08-13 10:57 UTC, pepelsbey commented on css/stacking-context/demos/default.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
```suggestion
```

2021-08-13 10:57 UTC, pepelsbey commented on css/stacking-context/demos/parent.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
```suggestion
```

2021-08-13 10:57 UTC, pepelsbey commented on css/stacking-context/demos/under-bkg.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
```suggestion
```

2021-08-13 10:57 UTC, pepelsbey commented on css/stacking-context/demos/z-index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
```suggestion
```

2021-08-13 13:16 UTC, pepelsbey approved these changes

2021-08-13 13:23 UTC, merged