Добавлена статья Element.getAttribute
doka-guide/content pull request #1272
Opened 2021-08-14 11:50 UTC by Windrushfarer

Fixes #1095

2021-08-14 11:54 UTC, Windrushfarer commented
Немного получилось, больше не смог рассказать ¯\_(ツ)_/¯
Если я упустил какие-либо важные моменты, то подскажите пожалуйста.

Линтер ругается на несуществующие ссылки, но статья про dataset #1207 уже в ревью, а hidden #1096 пишу следующей.

2021-08-14 12:23 UTC, pepelsbey requested changes

2021-08-14 12:23 UTC, pepelsbey commented on js/element-getattribute/index.md
> +<script type="application/json" id=hydration"></script>
```suggestion
<script type="application/json" id="hydration"></script>
```

2021-08-14 12:23 UTC, pepelsbey commented on js/element-getattribute/index.md
> +Существует [большой список](https://www.w3schools.com/tags/ref_attributes.asp) атрибутов для HTML-элементов, но не все атрибуты можно прочитать из объекта [DOM-элемента](/js/element), как например [E
```suggestion
Существует множество HTML-атрибутов, но не все атрибуты можно прочитать из объекта [DOM-элемента](/js/element), как например [`Element.hidden`](/js/element-hidden) или [`Element.dataset`](/js/element-dataset). Разработчики так же могут задавать элементу свои собственные атрибуты.
```

Поправил опечатки. Ссылаться на W3Schools считается грешным, там очень стрёмная документация. Тут либо спецификация, либо попросить Алёну сделать такой док, где есть список всех атрибутов. Особенно, если он пригождается часто.

2021-08-14 14:15 UTC, Windrushfarer commented on js/element-getattribute/index.md
> +Существует [большой список](https://www.w3schools.com/tags/ref_attributes.asp) атрибутов для HTML-элементов, но не все атрибуты можно прочитать из объекта [DOM-элемента](/js/element), как например [E
Не знал этого. Если подскажешь где найти такой список в спеке буду рад. Я вчера из чего-то плюс минус официального смог найти только на W3Schools.

2021-08-14 19:09 UTC, pepelsbey commented on js/element-getattribute/index.md
> +Существует [большой список](https://www.w3schools.com/tags/ref_attributes.asp) атрибутов для HTML-элементов, но не все атрибуты можно прочитать из объекта [DOM-элемента](/js/element), как например [E
W3Schools не имеет отношения к W3C или спецификациям, это такой HTML Book, у которого на порядки больше трафика. Так что это не там даже близко не официальный список и я, к сожалени, не знаю других, кроме MDN. Это хороший вопрос для авторского чата, ссылаемся ли мы на MDN :)

2021-08-14 20:26 UTC, solarrust commented on js/element-getattribute/index.md
> +Существует [большой список](https://www.w3schools.com/tags/ref_attributes.asp) атрибутов для HTML-элементов, но не все атрибуты можно прочитать из объекта [DOM-элемента](/js/element), как например [E
[Ссылочка на MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes)

Маяки если действительно нужен такой список у нас — внесу в план статей =)

2021-08-16 08:28 UTC, Windrushfarer commented on js/element-getattribute/index.md
> +Существует [большой список](https://www.w3schools.com/tags/ref_attributes.asp) атрибутов для HTML-элементов, но не все атрибуты можно прочитать из объекта [DOM-элемента](/js/element), как например [E
@pepelsbey думаю я все-таки уберу ссылку и адаптирую твой предложенный варинат

2021-08-16 08:33 UTC, bespoyasov reviewed
Вроде всё по делу. 

Разве что я бы ещё сравнил в лоб получение стилей с помощью `.style` и `.getAttribute('style')` или там data-атрибутов через `.getAttribute('data-...')` и `dataset.` но это может и не нужно.

2021-08-18 11:39 UTC, pepelsbey approved these changes

2021-08-18 15:55 UTC, bespoyasov approved these changes

2021-08-19 22:53 UTC, nlopin commented on js/element-getattribute/index.md
> +`Element.getAttribute` принимает один аргумент – строка с именем атрибута. В ответ метод возвращает значение атрибута в виде строки или `null`, если атрибута нет на элементе.
```suggestion
`Element.getAttribute` принимает один аргумент – строку с именем атрибута. В ответ метод возвращает значение атрибута в виде строки или `null`, если атрибута нет на элементе.
```

2021-08-19 22:59 UTC, nlopin approved these changes
Всё отлично, но у нас битая ссылка, которая поправится только когда вмёржится #1297

2021-08-20 08:44 UTC, merged