Добавляет плейсхолдер про <base>
doka-guide/content pull request #1281
Opened 2021-08-17 07:27 UTC by solarrust

2021-08-17 19:12 UTC, tachisis commented on html/base/index.md
> +- `_self` — значение по умолчанию если атрибут не прописан. Результат загружается в этом же документе.
```suggestion
- `_self` — значение по умолчанию, если атрибут не прописан. Результат загружается в этом же документе.
```

2021-08-17 21:17 UTC, pepelsbey requested changes

2021-08-17 21:17 UTC, pepelsbey commented on html/base/index.md
> +Определяет, как будут открываться ссылки и формы — тут же, на странице, во всплывающем окне или в новой вкладке.
Про всплывающие окна не совсем понятно, я бы лучше скомбинировал здесь кратко описания из возможных значений.

2021-08-17 21:17 UTC, pepelsbey commented on html/base/index.md
> +Возможные значения:
Насколько я понимаю, у атрибута target могут быть кастомные значения, не только перечисленные ключевые слова. Эти кастомные значения как раз позволяют обращаться к окнам, созданным с помощью window.open, которым при создании дали имя.

2021-08-18 06:25 UTC, solarrust commented on html/base/index.md
> +Возможные значения:
Этой инфы почти нигде нет. Спасибо что обратил внимание!

2021-08-18 06:25 UTC, solarrust commented on html/base/index.md
> +Определяет, как будут открываться ссылки и формы — тут же, на странице, во всплывающем окне или в новой вкладке.
Попробовала реализовать. Надеюсь, верно тебя поняла )

2021-08-18 09:43 UTC, pepelsbey commented on html/base/index.md
> +Если в документе есть несколько тегов `<base>`, то применится только первый из них.
```suggestion
В документе должен быть только один `<base>`. Если их несколько, то применится только первый из них.
```

Более чётко выразил, что должен быть только один

2021-08-18 10:03 UTC, pepelsbey approved these changes

2021-08-18 10:04 UTC, merged