Добавляет плейсхолдер про <meter>
doka-guide/content pull request #1283
Opened 2021-08-17 08:48 UTC by solarrust

2021-08-17 18:52 UTC, tachisis reviewed
Я думаю, что прогресс-бар надо писать через дефис, по аналогии с тем же пул-реквестом.

2021-08-17 18:52 UTC, tachisis commented on html/meter/index.md
> +Тег `<meter>` используется для визуального отображения числового значения в определённом при помощи атрибутов диапазоне. Браузеры, поддерживающие этот тег, отрисовывают его в виде прогрессбара, запол
```suggestion
Тег `<meter>` используется для визуального отображения числового значения в заданном диапазоне. Браузеры, поддерживающие этот тег, отрисовывают его в виде прогресс-бара, заполненного в зависимости от значения атрибута `value` и раскрашенного в разные цвета.
```

2021-08-17 18:52 UTC, tachisis commented on html/meter/index.md
> +- `low` — определяет что считать «низким значением». По умолчанию равно значению `min`.
```suggestion
- `low` — определяет, что считать «низким значением». По умолчанию равно значению `min`.
```

2021-08-17 18:52 UTC, tachisis commented on html/meter/index.md
> +- `high` — определяет что считать «высоким значением». По умолчанию равно значению `max`.
```suggestion
- `high` — определяет, что считать «высоким значением». По умолчанию равно значению `max`.
```

2021-08-17 18:52 UTC, tachisis commented on .yaspeller.json
> +    "прогрессбар(а)",
```suggestion
    "прогресс-бар(а)",
```

2021-08-17 21:24 UTC, pepelsbey commented on .yaspeller.json
> +    "прогрессбар(а)",
Пайп забыли, иначе окончание не сработает

2021-08-17 21:26 UTC, pepelsbey commented on html/meter/index.md
> +Тег `<meter>` используется для визуального отображения числового значения в определённом при помощи атрибутов диапазоне. Браузеры, поддерживающие этот тег, отрисовывают его в виде прогрессбара, запол
Мне кажется, что «разные цвета» слишком свободное описание. Тут скорее «раскрашенного в системные цвета».

2021-08-17 21:26 UTC, pepelsbey requested changes

2021-08-17 21:26 UTC, pepelsbey commented on html/meter/index.md
> +Тег `<meter>` используется для визуального отображения числового значения в определённом при помощи атрибутов диапазоне. Браузеры, поддерживающие этот тег, отрисовывают его в виде прогрессбара, запол
Мне кажется, что «разные цвета» слишком свободное описание. Тут скорее «раскрашенного в системные цвета».

2021-08-18 09:11 UTC, pepelsbey approved these changes

2021-08-18 09:13 UTC, merged