Инструкция для папки people
doka-guide/content pull request #1284
Opened 2021-08-17 09:32 UTC by furtivite

У нас есть папка `/people`, но нигде не написано зачем она. Создаёт небольшое пояснение.

2021-09-06 09:52 UTC, tachisis commented on people/README.md
> +Мы в Доке ценим вклад каждого, кто помог нам создать добрую энциклопедию, поэтому здесь, в папке `/people` у нас находится доска почёта.
```suggestion
Мы ценим вклад каждого, кто помогает нам создавать Доку. Чтобы читатели могли узнать больше о наших авторах, мы храним их описания здесь, в папке _/people_.
```

2021-09-06 09:52 UTC, tachisis commented on people/README.md
> +Мы работаем над созданием новых персональных страниц для каждого, кто сделал вклад. Там можно рассказать о себе, оставить ссылку на свой проект и написать настоящее имя, которое мы сможем использоват
```suggestion
Помимо этого каждый контрибьютор может завести себе личный файл, в котором можно рассказать о себе, оставить ссылку на свой проект и написать имя, которое мы сможем использовать в подписи.
```

2021-09-06 09:52 UTC, tachisis commented on people/README.md
> +1. Создайте в директории `/people` папку с названием, которое вы указали в качестве подписи в статье или доке (обычно совпадает с ником на Гитхабе)
```suggestion
1. Создайте в директории _/people_ папку. Её название должно совпадать с никнеймом, который вы указали в качестве подписи в статье или доке (обычно это ваш ник на Гитхабе).
```

2021-09-06 09:52 UTC, tachisis commented on people/README.md
> +1. Положите в неё файл `index.md` со следующим содержанием
```suggestion
1. Положите в неё файл _index.md_ со следующим содержанием:
```

2021-09-06 09:52 UTC, tachisis commented on people/README.md
> +url: <!-- ссылка на ваш сайт, обычно это ваш твиттер -->
Почему тут подсказка в виде html-комментария, а выше просто строка?

2021-09-12 17:43 UTC, pepelsbey requested changes
Я бы положил файл _people.md_ в _docs/_, ведь именно там мы храним всю документацию. Я понимаю, что индексный ридми — это удобно, если ходишь по папкам, просто мы выбрали другой путь.

Мы можем отдельно обсудить, нужны ли каким-то папкам индексные ридми.

2021-09-13 10:38 UTC, tachisis commented on people/README.md
> +url: <!-- ссылка на ваш сайт, обычно это ваш твиттер -->
@furtivite обрати, плз, внимание еще на этот комментарий

2021-09-14 04:38 UTC, furtivite commented
> Я бы положил файл _people.md_ в _docs/_, ведь именно там мы храним всю документацию. Я понимаю, что индексный ридми — это удобно, если ходишь по папкам, просто мы выбрали другой путь.
> 
> Мы можем отдельно обсудить, нужны ли каким-то папкам индексные ридми.

Можем просто продублировать и там тоже.

2021-09-14 11:03 UTC, pepelsbey commented
@furtivite давай всё же будем хранить документацию в одном месте. Поменяешь этот пул-реквест или откроешь новый?

2021-09-14 11:04 UTC, furtivite commented
Этот поправлю

2021-09-20 09:23 UTC, furtivite commented
@pepelsbey, @tachisis можно смотреть.

2021-09-20 10:18 UTC, pepelsbey approved these changes

2021-09-20 12:19 UTC, tachisis approved these changes

2021-09-20 12:29 UTC, merged