Редактирует статью про работу с формами
doka-guide/content pull request #1327
Opened 2021-08-23 15:32 UTC by tachisis

Прошу автора или ревьюера посмотреть на примеры кода в этой статье. В них очень много крупных куском нарратива в комментариях, который хотелось бы вытащить вовне, чтобы читать было удобнее. Но я не специалист по jsи не могу перестроить примеры сама, так что полагаюсь на вас!

2021-08-23 15:44 UTC, bespoyasov approved these changes
Кажется, всё хорошо. 

Я правда с телефона смотрел, ноутбук в ремонте ¯\_(ツ)_/¯ 

@nlopin, посмотри, пожалуйста, тоже? Вдруг я что-то пропустил.

2021-08-23 20:29 UTC, pepelsbey requested changes
Я бы предварил HTML-код формы тем самым задорным списком полей, которые мы собираем. Что-то вроде:

> В этой форме мы собираем следующие данные:
> 
> - Спрашиваем имя, чтобы знать, как обращаться в ответном письме
> - Спрашиваем почту, чтобы знать, куда это письмо слать
> - Возраст — нужны только молодые, сорри
> …

А дальше то же самое кодом. Если смешивать код и нарратив, то получается раздутый код и нечитаемый текст (

2021-08-24 14:48 UTC, nlopin commented
Перенёс. @tachisis @pepelsbey @bespoyasov оцените , насколько адекватно получилось

2021-08-24 15:48 UTC, bespoyasov approved these changes
Вроде, всё ок.

2021-08-24 16:12 UTC, pepelsbey approved these changes
Огонь!

2021-08-24 17:17 UTC, tachisis reviewed
Спасибо, получилось замечательно!

2021-08-24 17:26 UTC, tachisis commented on js/deal-with-forms/index.md
> +- Возраст — нужны только молодые 🤷‍♂️.
```suggestion
- Возраст — нужны только молодые 🤷‍♂️
```

2021-08-24 17:26 UTC, tachisis commented on js/deal-with-forms/index.md
> +Найдём форму на странице, с помощью [`getElementById`](/js/getelementbyid) и подпишемся на событие submit с помощью [`addEventListener`](/js/element-addeventlistener). Пока мы не будем отправлять фор
```suggestion
Найдём форму на странице, с помощью [`getElementById`](/js/getelementbyid) и подпишемся на событие `submit` с помощью [`addEventListener`](/js/element-addeventlistener). Пока мы не будем отправлять форму, а просто напечатаем в консоль строку «Submit» и убедимся, что механизм работает:
```

2021-08-24 17:26 UTC, tachisis commented on js/deal-with-forms/index.md
> +Чтобы элементы без названия нам не мешались, мы отфильтруем наш набор. Воспользуемся методом [`filter`](/js/array-filter), чтобы отбросить элементы с пустым именем. Так же заменим метод `forEach` на
```suggestion
Чтобы элементы без названия нам не мешались, мы отфильтруем наш набор. Воспользуемся методом [`filter`](/js/array-filter), чтобы отбросить элементы с пустым именем. Также заменим метод `forEach` на [`map`](/js/array-map) — он соберёт нам массив, который хранит объект с именем и значением каждого отфильтрованного элемента.
```

2021-08-24 17:26 UTC, tachisis commented on js/deal-with-forms/index.md
> +Но это свойство мы хотим использовать только на чекбоксе, а не на остальных полях. Это тоже можно сделать. Прочитаем тип элемента и если он `"checkbox"`, то возьмём в качестве значения поле `checked`
```suggestion
Но это свойство мы хотим использовать только на чекбоксе, а не на остальных полях. Это тоже можно сделать. Прочитаем тип элемента и, если он `"checkbox"`, то возьмём в качестве значения поле `checked`:
```

2021-08-24 17:26 UTC, tachisis commented on js/deal-with-forms/index.md
> +Мы должны вызвать `onSuccess` только если форма была отправлена успешна. Для этого добавим проверку на статус ответа сервера — он должен быть 200 в случае успеха (статусы ответа разобраны в [статье п
```suggestion
Мы должны вызвать `onSuccess`, только если форма была отправлена успешна. Для этого добавим проверку на статус ответа сервера — он должен быть 200 в случае успеха (статусы ответа разобраны в [статье про HTTP протокол](/tools/http-protocol)):
```

2021-08-24 17:26 UTC, tachisis commented on js/deal-with-forms/index.md
> +Проверять валидность формы будем с помощью метода `checkValidity()` формы. Он запускает стандартные проверки. Результат проверки будем использовать для того, чтобы установить свойство `disabled` кноп
```suggestion
Проверять валидность формы будем с помощью метода `checkValidity()` формы. Он запускает стандартные проверки. Результат проверки будем использовать для того чтобы установить свойство `disabled` кнопки в значение `true`, если нужно заблокировать, и `false`, если кнопка должна быть доступна.
```

2021-08-24 19:12 UTC, merged