Обновляет демо и рисунки в статье Линейный градиент
doka-guide/content pull request #1341
Opened 2021-08-25 13:54 UTC by skorobaeus

2021-08-25 15:57 UTC, pepelsbey requested changes
Предлагаю развернуть все самые сложные примеры, это всё-таки демки :)

2021-08-25 15:57 UTC, pepelsbey commented on css/linear-gradient/demos/gradient-pattern.html
> +        background: #FFFFFF linear-gradient(to top, #2E9AFF 1px, transparent 1px) repeat 0 -.7rem / 100% 3rem;
```suggestion
        background-color: #FFFFFF;
        background-image: linear-gradient(
          to top,
          #2E9AFF 1px,
          transparent 1px
        );
        background-position: 0 -0.7rem;
        background-size: 100% 3rem;
```

Некоторые свойства лучше разворачивать, их без полбанки не разберёшь. Это всё-таки демка :)

2021-08-25 15:57 UTC, pepelsbey commented on css/linear-gradient/demos/gradient-multiple.html
> +          linear-gradient(336deg, rgba(255,216,41,1), rgba(100,100,255,0) 70.71%);
```suggestion
          linear-gradient(
            217deg,
            rgb(46 154 255 / 1),
            rgb(255 100 100 / 0) 70.71%
          ),
          linear-gradient(
            127deg,
            rgb(244 152 173 / 1),
            rgb(100 255 100 / 0) 70.71%
          ),
          linear-gradient(
            336deg,
            rgb(255 216 41 / 1),
            rgb(100 100 255 / 0) 70.71%
          );
```

Чуть менее склеенно, чуть более развёрнуто.

2021-08-25 15:57 UTC, pepelsbey commented on css/linear-gradient/demos/gradient-repeat.html
> +        background-image: repeating-linear-gradient(-45deg, #2E9AFF, #2E9AFF 10px, #F498AD 10px, #F498AD 20px);
```suggestion
        background-image: repeating-linear-gradient(
          -45deg,
          #2E9AFF,
          #2E9AFF 10px,
          #F498AD 10px,
          #F498AD 20px
        );
```

2021-08-25 15:57 UTC, pepelsbey commented on css/linear-gradient/demos/gradient-stops.html
> +        background-image: linear-gradient(#F498AD 25%, #2E9AFF 25% 50%, #FFD829 75%);
```suggestion
        background-image: linear-gradient(
          #F498AD 25%,
          #2E9AFF 25% 50%,
          #FFD829 75%
        );
```

2021-08-30 13:18 UTC, skorobaeus commented on css/linear-gradient/demos/gradient-direction.html
> +        width: calc(65% - 200px - 50px);
У меня нет мнения по этому поводу :)

2021-08-30 13:33 UTC, pepelsbey approved these changes

2021-08-30 13:34 UTC, pepelsbey approved these changes

2021-09-09 17:52 UTC, solarrust approved these changes

2021-09-09 18:56 UTC, merged