setTimeout и clearTimeout
doka-guide/content pull request #1381
Opened 2021-08-29 19:34 UTC by Windrushfarer

Fixes #1310 #1311

2021-08-29 19:35 UTC, Windrushfarer commented
Я думаю ещё демку добавить 🤔

2021-08-30 00:04 UTC, pepelsbey requested changes

2021-08-30 00:04 UTC, pepelsbey commented on js/element-settimeout/practice/windrushfarer.md
> +Функция все-равно вызовется через секунду. Если возникла необходимость изменить время, то придётся сначала очистить предыдущий таймер и установить новый.
```suggestion
Функция всё равно вызовется через секунду. Если возникла необходимость изменить время, то придётся сначала очистить предыдущий таймер и установить новый.
```

2021-08-30 00:04 UTC, pepelsbey commented on js/element-settimeout/practice/windrushfarer.md
> +// Изанчально 1 секунда
```suggestion
// Изначально 1 секунда
```

2021-08-30 00:04 UTC, pepelsbey commented on js/element-settimeout/practice/windrushfarer.md
> +}, 0) // таймер равен 0
```suggestion
}, 0)
// таймер равен 0
```

2021-08-31 10:02 UTC, pepelsbey approved these changes

2021-08-31 10:07 UTC, nlopin approved these changes
Всё круто. 

Я бы ещё подчеркнул в статье `setTimeout`, что нет гарантии, что вызов произойдёт ровно через указанное время. В зависимости от нагруженности он может произойти и намного позже.

2021-08-31 12:32 UTC, bespoyasov approved these changes
А мы хотим рассказать о минимальном возможном таймауте (мол нет разницы между 0 мс и 1 мс) и `setImmediate` в Node.js, или это всё здесь лишнее? @nlopin

2021-08-31 19:37 UTC, nlopin commented
про ноду точно лишнее

2021-08-31 20:29 UTC, nlopin commented
`setTimeout` не относится к элементу, это глобальный контекст. Переименовал урлы и добавил их в индекс раздела

2021-09-01 08:25 UTC, Windrushfarer commented
Похоже вы уже тут все сделали и без меня :D Спасибо!

2021-09-02 07:59 UTC, merged