Добавляет доку `Array.from`
doka-guide/content pull request #1385
Opened 2021-08-29 22:01 UTC by nlopin

Closes #1335

2021-08-29 22:02 UTC, nlopin commented on js/array-from/index.md
> +При создании массива происходит поверхностное копирование (shallow copy) элементов. Если объект, на основе которого создаётся массив, содержит вложенные структуры данных, то эти вложенные структуры н
@bespoyasov мне тут не очень нравится объяснение. Тебе было понято, когда прочитал?

2021-08-29 22:04 UTC, nlopin commented
Как вам перевод arrayLike → массивоподобный? Альтернативно можно использовать «индексированный», но это не совсем точно, потому что индексированность не гарантирует наличие свойства `length` у объекта

2021-08-30 00:09 UTC, pepelsbey requested changes
Смущают ещё функции-однострочники, кажется это не самая понятная запись из-за нагромождения скобок:

```js
const spacedLetters = Array.from(name).map(function(letter) { return "*" + letter + "*" })
```

2021-08-30 00:09 UTC, pepelsbey commented on js/array-from/index.md
> +* значение, которое будет использоваться как `this` в функции из второго параметра.
```suggestion
- объект, на основе которой создаётся массив.
- функция преобразования элемента перед его добавлением в массив. Работает как метод [`.map()`](/js/array-map).
- значение, которое будет использоваться как `this` в функции из второго параметра.
```

2021-08-30 00:09 UTC, pepelsbey commented on js/array-from/index.md
> +* объект итерируемый, то есть реализует интерфейс `Iterable`. Этим свойством обладают объекты `Set` и `Map`.
```suggestion
- элементы объекта проиндексированы и объект имеет свойство `.length`. Такие объекты называют _массивоподобными_, потому что именно эти свойства присущи массиву. Этим свойством обладают объекты `arguments`, [`NodeList`](/js/collection-and-nodelist), [`HTMLCollection`](/js/collection-and-nodelist).
- объект итерируемый, то есть реализует интерфейс `Iterable`. Этим свойством обладают объекты `Set` и `Map`.
```

2021-08-30 00:09 UTC, pepelsbey commented on js/array-from/practice/nlopin.md
> +🛠 Если вызвать `Array.from()` без аргументов, то произойдёт ошибка `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`
```suggestion
🛠 Если вызвать `Array.from()` без аргументов, то произойдёт ошибка `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))`.
```

2021-08-30 08:11 UTC, tachisis approved these changes
Апрув на словарь

2021-08-30 09:34 UTC, pepelsbey approved these changes

2021-08-31 10:21 UTC, pepelsbey approved these changes

2021-08-31 12:29 UTC, bespoyasov reviewed
Мне всё нравится, но в двух местах моё занудство всё же заиграло.

2021-08-31 12:29 UTC, bespoyasov commented on js/array-from/index.md
> +Массив из объекта `arguments`:
Нам бы тут отметку сделать, что `arguments` уже [считается моветоном](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments). Его хоть и не задепрекетили, но показывать устаревший код в новых статьях я бы не стал.

Лучше упомянуть `...rest` или заменить пример на что-то другое.

2021-08-31 12:29 UTC, bespoyasov commented on js/array-from/index.md
> +При создании массива происходит поверхностное копирование (shallow copy) элементов. Если объект, на основе которого создаётся массив, содержит вложенные структуры данных, то эти вложенные структуры н
Первая часть — да, вторая «При их изменении...» — не очень. Можно перефразировать и вспомнить «передачу по ссылке», хотя это и не очень корректно с точки зрения работы JS.

2021-08-31 20:04 UTC, nlopin commented on js/array-from/index.md
> +Массив из объекта `arguments`:
Спасибо, что напомнил! Убрал этот пример, но оставил упоминание `arguments` в тексте. Там он не так выделяется, да и доку по нему всё равно надо написать. Время от времени его можно встретить в жизни

2021-08-31 20:06 UTC, nlopin commented on js/array-from/index.md
> +При создании массива происходит поверхностное копирование (shallow copy) элементов. Если объект, на основе которого создаётся массив, содержит вложенные структуры данных, то эти вложенные структуры н
Я его добавил, чтобы читателя не смутила фраза «не будут скопированы». Она звучит так, что мы просто выбрасываем эти поля, а это не так.

2021-09-01 12:25 UTC, bespoyasov commented on js/array-from/index.md
> +При создании массива происходит поверхностное копирование (shallow copy) элементов. Если объект, на основе которого создаётся массив, содержит вложенные структуры данных, то эти вложенные структуры н
А у нас нет статьи о глубоком и поверхностном копировании? Сослались бы просто туда, и дело с концом.

2021-09-01 21:03 UTC, nlopin commented on js/array-from/index.md
> +При создании массива происходит поверхностное копирование (shallow copy) элементов. Если объект, на основе которого создаётся массив, содержит вложенные структуры данных, то эти вложенные структуры н
Нет, такой статьи нет. Добавил в бэклог

2021-09-02 08:23 UTC, bespoyasov approved these changes

2021-09-02 08:25 UTC, merged