Добавляет демо в статью select
doka-guide/content pull request #1387
Opened 2021-08-30 13:04 UTC by skorobaeus

2021-08-30 13:06 UTC, skorobaeus commented
#766

2021-08-30 14:10 UTC, pepelsbey requested changes
Было бы хорошо предлагать более кроссбраузерные демки. Сейчас это хорошо выглядит только в Chrome.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/105274/131352493-a45340a3-c98e-4bff-adee-b70d3296af0d.png">

2021-08-30 14:10 UTC, pepelsbey commented on html/select/demos/attributes/index.html
> +    }
Сработает только в Chrome и Safari и это нестандартная фича. Лучше не надо.

2021-09-01 09:35 UTC, skorobaeus commented
> Было бы хорошо предлагать более кроссбраузерные демки. Сейчас это хорошо выглядит только в Chrome.
> 
> <img alt="image" width="1196" src="https://user-images.githubusercontent.com/105274/131352493-a45340a3-c98e-4bff-adee-b70d3296af0d.png">

Я не согласна. Селекты выглядят хорошо в хром-семействе, фаерфокс и эдж (~~невермайнд, это же тоже хромиум~~). Остался сафари — его поправила.

<img src="https://i.gyazo.com/d949ac6beb92fb9e283908a28f2dea52.png">

2021-09-01 09:40 UTC, skorobaeus commented on html/select/demos/attributes/index.html
> +    }
Этот код работает для хром и сафари, в файерфокс за внешний вид скроллов отвечают [scrollbar-color и scrollbar-width](https://caniuse.com/?search=scrollbar-), в итоге в перечисленных браузерах скроллы выглядят одинаково. Чем плохо?

2021-09-01 10:29 UTC, pepelsbey commented
> Для `<option>` в сафари не работает padding и псевдокласс :checked, поэтому внешний вид отличается

Ну вот я примерно о том же — стоит ли предлагать демки, которые не мелочами, а вот принципиально не кроссбраузерные. Safari просто игнорирует часть свойств и получается, что их нельзя испоользовать.

2021-09-01 10:37 UTC, pepelsbey commented on html/select/demos/attributes/index.html
> +    }
В Firefox на macOS это не срабатывает

![image](https://user-images.githubusercontent.com/105274/131657233-4c841d92-f451-4e7a-a20c-69af2fcc7234.png)

2021-09-02 10:20 UTC, skorobaeus commented on html/select/demos/attributes/index.html
> +    }
Не срабатывает, но выглядит скроллбар хорошо :) Я с этой точки вижу два пути:

1. Не стилизовать скроллбары вообще. Получится такой результат:

<a href="https://i.gyazo.com/fe6437a615425446b21a9dbcbde3ae41.png"><img src="https://i.gyazo.com/fe6437a615425446b21a9dbcbde3ae41.png"></a>

Со стилизацией выбивается только мозилла на маке, без стилизации одинаковый результат только в хром-семействе на маке и сафари, в остальных вариантах "кто в лес, кто по дрова". Из двух зол первое мне показалось наименьшим и я выбрала его.

2. Найти и прикрутить библиотечку. Плюсы: одинаковый (надеюсь) вид везде. Минусы: много чужого JS-кода в демке про вёрстку.

2021-09-02 10:29 UTC, skorobaeus commented
> > Для `<option>` в сафари не работает padding и псевдокласс :checked, поэтому внешний вид отличается
> 
> Ну вот я примерно о том же — стоит ли предлагать демки, которые не мелочами, а вот принципиально не кроссбраузерные. Safari просто игнорирует часть свойств и получается, что их нельзя использовать в реальном проекте.

В тексте статьи, кстати, упоминается то, что `<option>`ы почти не поддаются стилизации :)

Здесь тоже два варианта:

1. Использовать только те свойства, которые работают в сафари, результат будет такой:

<img src="https://i.gyazo.com/1a82fde0f2a5b6bc3d684aadeca10f52.png">

Почти одинаковый результат, но снова один браузер выбивается, шо ж ты будешь делать. Вид слегка неказистый, но можно смириться.

2. Стилизовать по хардкору через списки, например.
Можно добиться любого внешнего вида, но "рекомендуется для выпадающих списков оставлять родной вид, потому что такие списки обладают рядом преимуществ перед нестандартными. Например, выпадающий список опций может выходить за границы окна браузера, давая пользователю возможность выбрать нужный элемент." (с) текст статьи

2021-09-02 12:59 UTC, pepelsbey commented
У нас статья про `<select>`, встроенный в HTML элемент. И задача показать, как его более-менее кроссбраузерно можно стилизовать. Библиотеки и скрипты — про другое. Так что я бы не трогал скроллбары и не пытался покрасить и стилизовать то, что не работает в Safari.

Сейчас демка ушла дальше, чем статья. И если очень хочется, то можно развить статью или написать отдельную про стилизацию контролов форм всякими трюками и хаками.

@solarrust что скажешь?

2021-09-02 13:03 UTC, solarrust commented
Я в восхищении от демок @skorobaeus как всегда 🖤
Но стоит думать о читабельности кода для начинающих разработчиков. Хочется код, который можно скопировать и он будет работать везде и без внезапностей. Так что я за кроссбраузерный вариант.

2021-09-06 11:07 UTC, skorobaeus commented
Демки нередко уходят дальше, чем статья, например, [list-style-type](https://doka.guide/css/list-style-type/demos/list-style-type/) или [transform](https://doka.guide/css/transform/demos/playground/). Если бы задача была не использовать в демо никакого кода за пределами статьи, они бы выглядели как на htmlbook :)

@ValyaBro нужно твоё мнение по поводу скроллбаров для баланса :)

2021-09-06 19:29 UTC, ValyaBro commented
вариант предложенный @skorobaeus выглядит очень хорошо. Насколько критично то, что мы используем в коде что-то, что может выйти за рамки понимания пользователя? Если это критично, то нам стоит обсудить параметры того что можно  использовать, а что нельзя.

2021-09-06 19:34 UTC, ValyaBro commented
насколько я понимаю у нас есть два варианта: 

1. в приоритете чистота кода, тогда нам надо собирать демку так, чтобы она выглядела одинаково приемлемо во всех браузерах и при этом не использовать сложные конструкции.
2. в приоритете визуальная консистентность и оформленность, тогда мы используем в коде что-то, что может не понять пользователь.

2021-09-07 08:56 UTC, skorobaeus commented
> 1. в приоритете чистота кода, тогда нам надо собирать демку так, чтобы она выглядела одинаково наименее убого во всех браузерах и при этом не использовать сложные конструкции. @skorobaeus вопрос к тебе: насколько увеличиться время работы над одной демкой, с учётом поиска кроссбраузерного варианта, который прилично выглядит? Заложено ли это в твоей системе стилей? Сколько займёт времени расширить систему стилей до кроссбраузерной?

@ValyaBro Время не увеличится. Я подбирала стили с тем расчётом, чтобы демки можно было верстать быстро и понятно ✌

Некоторые элементы "быстро и понятно" не стилизуются, например скроллбары и выпадающие списки в этой статье. Вот мы и оказались перед выбором, что в приоритете, лаконичный код или визуальное единообразие 🤷‍♀️

2021-09-08 14:47 UTC, ValyaBro commented
ага, это мы решим в ближайшее время я надеюсь ))

2021-09-09 17:56 UTC, solarrust commented
@pepelsbey @skorobaeus вы в итоге о чём-то договорились? Простите, я потерялась =)

2021-09-09 18:00 UTC, pepelsbey commented
К сожалению, стилизовать селекты кроссбраузерно пока нельзя. Не хотелось бы вводить наших читателей в заблуждение. Давайте откатимся до версии, которая достаточно кроссбраузерная.

2021-09-10 12:26 UTC, skorobaeus commented
Вернула `<option>` к кроссбраузерному виду. Чуть-чуть отличаются внешне в лисе, но, выходит, это родная лисья реализация, с которой лучше не бороться.

Давайте решим "да" или "нет" стилизации скроллбаров, они ведь не только в селектах используются.

2021-09-10 14:01 UTC, solarrust commented
@skorobaeus вынесла вопрос на ближайший созвон =)

2021-09-10 14:02 UTC, solarrust approved these changes

2021-09-15 16:35 UTC, ValyaBro commented
@skorobaeus я тут полагаюсь на тебя и твой вкус, и чувство баланса между красотой, стилем и трудоёмкостью реализации <3

2021-09-16 13:19 UTC, skorobaeus commented
Вернула скроллбары в первозданный вид.

(￢_￢)

2021-09-17 12:36 UTC, pepelsbey approved these changes

2021-09-17 13:03 UTC, merged

2021-09-17 14:42 UTC, ValyaBro commented
@skorobaeus сейчас хочется сделать одинаковый отступ у всех списков (выпадающих и нет), как думаешь, мы можем это поправить? 
![image](https://user-images.githubusercontent.com/42911440/133801840-9c89ced7-9957-43f1-bc5a-0162bccf888f.png)

2021-09-17 15:11 UTC, pepelsbey commented
> @skorobaeus сейчас хочется сделать одинаковый отступ у всех списков (выпадающих и нет), как думаешь, мы можем это поправить?

Из-за Safari можно только вот так, если кроссбраузерно.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/105274/133806357-22e4ba5c-4e85-4fe5-a013-efa26fc4d792.png">

2021-09-20 09:12 UTC, ValyaBro commented
выглядит хорошо