Добавляет статью о свойстве `length` массива
doka-guide/content pull request #1394
Opened 2021-08-31 21:45 UTC by nlopin

Related to #1322

2021-08-31 22:08 UTC, pepelsbey requested changes

2021-08-31 22:08 UTC, pepelsbey commented on js/array-length/index.md
> +```
````suggestion
Воспользуемся конструктором, чтобы создать массив без значений:

```js
const myTodos = new Array(Math.pow(2, 32))
const freeTimes = new Array(-9000)
```

Ошибки не будет:

```js
const watchlist = new Array(Math.pow(2, 32) - 1)
```
````

Я бы ещё здесь объяснил, что именно происходит в каждой из ситуаций. Иначе приходится делать выводы самостоятельно.

2021-08-31 22:08 UTC, pepelsbey commented on js/array-length/index.md
> +console.log(series.length) //4
```suggestion
console.log(series.length)
// 4
```

2021-08-31 22:08 UTC, pepelsbey commented on js/array-length/index.md
> +// 2. contribute to Doka
```suggestion
const todos = ['buy milk', 'contribute to Doka']
console.log(todos.length)
// 2

todos.length = 4
console.log(todos)
// ['buy milk', 'contribute to Doka', <2 empty slots>]

todos.forEach(function(todo, index) {
  console.log(`${index + 1}. todo`)
})
// 1. buy milk
// 2. contribute to Doka
```

2021-08-31 22:08 UTC, pepelsbey commented on js/array-length/index.md
> +console.log(emptyArray.length) //100
```suggestion
console.log(emptyArray.length)
// 100
```

2021-08-31 22:08 UTC, pepelsbey commented on js/array-length/index.md
> +console.log(anotherEmptyArray.length) //0
```suggestion
console.log(anotherEmptyArray.length)
// 0
```

2021-08-31 22:08 UTC, pepelsbey commented on js/array-length/index.md
> +// [ "sleep", "eat", "drink", <996 empty slots>, "work"]
```suggestion
console.log(prorities.length)
// 3

prorities[999] = 'work'
console.log(prorities.length)
// 1000
console.log(prorities)
// ['sleep', 'eat', 'drink', <996 empty slots>, 'work']
```

2021-08-31 22:08 UTC, pepelsbey commented on js/array-length/index.md
> +//[ "buy milk", "contribute to Doka", <2 empty slots> ]
```suggestion
const todos = ['buy milk', 'contribute to Doka']
console.log(todos.length)
// 2

todos.length = 4
console.log(todos)
// ['buy milk', 'contribute to Doka', <2 empty slots>]
```

2021-08-31 22:08 UTC, pepelsbey commented on js/array-length/practice/nlopin.md
> +
```suggestion
```

2021-08-31 22:36 UTC, nlopin commented on js/array-length/index.md
> +console.log(series.length) // 0
ок

2021-08-31 22:37 UTC, nlopin commented on js/array-length/index.md
> +Свойство `.length` возвращает количество элементов в массиве. Если элементов нет, то свойство возвращает 0.
Спасибо, что обратил внимание. Действительно вне контекста лучше точку опускать

2021-08-31 22:41 UTC, nlopin commented on js/array-length/index.md
> +```
Я поэтому как раз и не стал выносить коммент про конструктор. Он вырывает из контекста.

2021-08-31 22:45 UTC, nlopin commented on js/array-length/index.md
> +```
предложил новый вариант

2021-09-01 12:30 UTC, bespoyasov approved these changes
Подумал тут, что перезаписываемые свойства структур данных — больше зло, чем добро 😃

2021-09-01 12:30 UTC, bespoyasov commented on js/array-length/index.md
> +```
```suggestion
```js
```

2021-09-01 12:30 UTC, bespoyasov commented on js/array-length/index.md
> +const freeTimes = new Array(-9000)
Я бы тут ошибки привёл, а то непонятно, относится код к предыдущему абзацу как пример, или это что-то уже новое.

2021-09-01 12:30 UTC, bespoyasov commented on js/array-length/index.md
> +Если увеличить значений свойства `length`, то в конец массива добавятся пустые ячейки массива. Значение в них не будет установлено и они будут игнорироваться при обходе массива:
```suggestion
Если увеличить значение свойства `length`, то в конец массива добавятся пустые ячейки массива. Значение в них не будет установлено и они будут игнорироваться при обходе массива:
```

2021-09-01 12:30 UTC, bespoyasov commented on js/array-length/practice/nlopin.md
> +🛠 Свойство `length` используется при обходе массивов с помощью классических циклов [`for`](/js/for) или [`while`](/js/while). На практике такие циклы уже встречаются редко, но это идиоматический код,
А напишем, почему это надо  знать? Что случится, если я не буду этого знать и применю `length` неправильно: к каким проблемам это приведёт?

2021-09-01 12:30 UTC, bespoyasov commented on js/array-length/practice/nlopin.md
> +🛠 Чаще всего к свойству обращаются, когда хотят проверить, пустой ли массив или нет:
```suggestion
🛠 Чаще всего к свойству обращаются, когда хотят проверить, пустой массив или нет:
```

2021-09-01 20:45 UTC, nlopin commented on js/array-length/index.md
> +const freeTimes = new Array(-9000)
добавил

2021-09-01 20:51 UTC, nlopin commented on js/array-length/practice/nlopin.md
> +🛠 Свойство `length` используется при обходе массивов с помощью классических циклов [`for`](/js/for) или [`while`](/js/while). На практике такие циклы уже встречаются редко, но это идиоматический код,
добавил

2021-09-01 20:52 UTC, nlopin commented
> Подумал тут, что перезаписываемые свойства структур данных — больше зло, чем добро 😃

Подумал следом и написал в опыте использования, что так лучше не делать

2021-09-01 20:52 UTC, nlopin commented
@pepelsbey без твоего апрувала не даёт мержить

2021-09-01 20:55 UTC, pepelsbey requested changes
Парочка мелочей :)

2021-09-01 20:55 UTC, pepelsbey commented on js/array-length/index.md
> +title: ".length"
```suggestion
title: "length"
```
Так ведь решили?

2021-09-01 21:01 UTC, nlopin commented on js/array-length/index.md
> +title: ".length"
в тайтле я хочу оставить пока.

Потому что так работать группировка содержания:

```
Array
  |
  |__ .length
  |__ .forEach()
...
```

Это пока рабочая идея, попробую по разному и потом остановлюсь на чём-то одном

2021-09-01 23:32 UTC, pepelsbey approved these changes

2021-09-02 08:22 UTC, merged