Добавляет доку о свойстве `length` строк
doka-guide/content pull request #1395
Opened 2021-08-31 22:25 UTC by nlopin

Related to #1322

2021-08-31 22:50 UTC, pepelsbey requested changes
Здесь тоде вопрос про `.length` vs `length`

2021-08-31 22:50 UTC, pepelsbey commented on js/string-length/index.md
> +Свойство `.length` хранит длину строки в юнитах UTF-16. Это значение совпадает с количеством символов в строке, если строка содержит простой текст.
```suggestion
Свойство `.length` хранит длину строки, которое обычно совпадает с количеством символов в ней. Если в строке есть _непростые_ символы, вроде эмодзи, они могут удлинять строку больше, чем на единицу.
```

Мне кажется, что заходить сходу про юниты и UTF-16, пока не объяснили что это — ошибочно. Это не краткое описание.

2021-08-31 22:50 UTC, pepelsbey commented on js/string-length/index.md
> +console.log(emoji.length) // 5 🤷‍♂️
```suggestion
const phrase = 'Съешь ещё этих мягких французских булок, да выпей же чаю'
console.log(phrase.length)
// 56

const empty = ''
console.log(empty.length)
// 0

const emoji = '👩‍💻'
console.log(emoji.length)
// 5 🤷‍♂️
```

2021-08-31 22:50 UTC, pepelsbey commented on js/string-length/index.md
> +console.log('😀'.length) // 2
```suggestion
console.log('👩‍💻'.length)
// 5
console.log('😀'.length)
// 2
```

2021-08-31 22:50 UTC, pepelsbey commented on js/string-length/practice/nlopin.md
> +console.log(symbols.length) // 3 ✅
```suggestion
const emojiString = '🙈🙉🙊'

console.log(emojiString.length)
// 6 ❌

const symbols = [...emojiString]
console.log(symbols.length)
// 3 ✅
```

2021-09-01 12:23 UTC, bespoyasov approved these changes

2021-09-01 12:23 UTC, bespoyasov commented on js/string-length/index.md
> +Эмодзи состоят из нескольких юнитов. Количество использованных юнитов зависит от эмодзи:
Можно добавить коллаут на [лонгрид об устройстве эмоджи](https://tonsky.me/blog/emoji/).

2021-09-01 12:23 UTC, bespoyasov commented on js/string-length/practice/nlopin.md
> +const symbols = [...emojiString]
О, фигасе, не знал 😃

2021-09-01 13:06 UTC, nlopin commented on js/string-length/index.md
> +Эмодзи состоят из нескольких юнитов. Количество использованных юнитов зависит от эмодзи:
тоже думал про Никиту

2021-09-01 23:33 UTC, pepelsbey approved these changes

2021-09-02 08:21 UTC, merged