Добавляет доку по template
doka-guide/content pull request #1397
Opened 2021-08-31 22:44 UTC by nionka

2021-08-31 23:02 UTC, pepelsbey requested changes

2021-08-31 23:02 UTC, pepelsbey commented on html/template/index.md
> +💡 Тег `<template>` может располагаться практически в любом месте HTML страницы.
Слово «практически» отдаёт загадкой. Такое не подходит для документации, лучше уточнить )

2021-09-01 09:31 UTC, nionka commented on html/template/index.md
> +### `content`
MDN вносит дезинформацию=)

2021-09-01 10:24 UTC, pepelsbey commented on html/template/index.md
> +### `content`
> However, the HTMLTemplateElement has a content property

Да вроде нет: пишут, что есть такое свойство. @nlopin это свойство, не метод?

2021-09-01 11:46 UTC, nionka commented on html/template/index.md
> +### `content`
https://developer.mozilla.org/ru/docs/Web/HTML/Element/template#%D0%B0%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%D1%8B вот здесь, это некорректный русский перевод

2021-09-02 04:38 UTC, solarrust commented on html/template/index.md
> +👆 Хотя большинство современных браузеров имеют поддержку `<template>`, перед его использованием в скрипте это лучше проверить. Проверка осуществляется как раз по наличию свойства `content`
```suggestion
:::callout👆 

Хотя большинство современных браузеров имеют поддержку `<template>`, перед его использованием в скрипте это лучше проверить. Проверка осуществляется как раз по наличию свойства `content`

:::
```
Я бы оформила это коллаутом =) Что думаешь?

2021-09-02 04:39 UTC, solarrust commented on html/template/index.md
> +### `content`
Есть простое правило, помогающее определить свойство перед тобой или метод.
Свойство ничего не делает, только даёт инфу. Метод что-то делает (вырезает, вставляет, меняет).

2021-09-02 04:55 UTC, solarrust commented on html/template/index.md
> +:::callout👆
```suggestion
:::callout👆
```

2021-09-02 04:55 UTC, solarrust approved these changes

2021-09-02 12:47 UTC, pepelsbey approved these changes

2021-09-02 17:28 UTC, merged