Добавляет плейсхолдер про @supports
doka-guide/content pull request #1401
Opened 2021-09-02 14:49 UTC by solarrust

2021-09-02 15:18 UTC, pepelsbey requested changes
Добавил про `selector()`

2021-09-02 15:18 UTC, pepelsbey commented on css/supports/index.md
> +Директива `@supports` позволяет проверить, поддерживает ли браузер свойство, правило, селектор CSS. Проверка происходит внутри круглых скобок и с использованием специальных ключевых слов. Если услови
```suggestion
Директива `@supports` позволяет проверить, поддерживает ли браузер свойство, правило, селектор CSS. Если условие срабатывает, то будет выполнено CSS-код, написанный внутри фигурных скобок.
```
- Лучше не описывать про условия в скобках, а показать на примере (плюс есть нюансы, см. дальше)
- «После директивы» можно прочитать как «после закрывающей скобки», оставил просто «внутри»

2021-09-02 15:18 UTC, pepelsbey commented on css/supports/index.md
> +
```suggestion

Если нужно проверить свойство или значение, нужная конструкция записывается сразу в круглых скобках:

```

2021-09-02 15:18 UTC, pepelsbey commented on css/supports/index.md
> +@supports (transform: perspective(150px)) {  }
````suggestion
@supports (--foo: bar) {
  .block {
    color: var(--color);
  }
}

### Проверка селектора

Если нужно проверить селектор, используется функция `selector()`:

```css
:is(ul, ol) > li {
  color: red;
}

@supports not selector(:is(a, b)) {
  ul > li,
  ol > li {
    color: red;
  }
}
```
````

2021-09-02 15:20 UTC, solarrust commented on css/supports/index.md
> +@supports (transform: perspective(150px)) {  }
`selector()` пока экспериментальный вроде, потому не добавила его изначально

2021-09-02 15:24 UTC, pepelsbey commented on css/supports/index.md
> +@supports (transform: perspective(150px)) {  }
Кажется поддержка неплохая

<img width="903" alt="image" src="https://user-images.githubusercontent.com/105274/131871660-063e05ec-1efe-44d3-bf40-0ddfbb580169.png">

Все браузеры давно, Safari с мая 2021.

2021-09-03 08:16 UTC, tachisis commented on css/supports/index.md
> +Директива `@supports` позволяет проверить, поддерживает ли браузер свойство, правило, селектор CSS. Если условие срабатывает, то будет выполнено CSS-код, написанный внутри фигурных скобок.
```suggestion
Директива `@supports` позволяет проверить, поддерживает ли браузер свойство, правило, селектор CSS. Если условие срабатывает, то будет выполнен CSS-код, написанный внутри фигурных скобок.
```

2021-09-04 08:59 UTC, tachisis approved these changes

2021-09-06 21:01 UTC, pepelsbey approved these changes

2021-09-06 21:02 UTC, merged