Добавляет плейсхолдер для font-stretch
doka-guide/content pull request #1450
Opened 2021-09-02 17:56 UTC by solarrust

2021-09-03 08:18 UTC, tachisis commented on css/font-stretch/index.md
> +- проценты — точное указание процентов в диапазоне от 50 до 200 не включая границы. Отрицательные значения недопустимы.
```suggestion
- проценты — точное указание процентов в диапазоне от 50 до 200, не включая границы. Отрицательные значения недопустимы.
```

2021-09-04 08:59 UTC, tachisis approved these changes

2021-09-06 21:59 UTC, pepelsbey requested changes

2021-09-06 21:59 UTC, pepelsbey commented on css/font-stretch/index.md
> +Свойство `font-stretch` устанавливает узкое, нормальное или широкое начертание шрифта.
```suggestion
Свойство `font-stretch` устанавливает узкое, нормальное или широкое начертание шрифта. Как и в случае [`font-weight`](/css/font-weight), браузер не меняет рисунок шрифта, а выбирает из доступных шрифтов подходящие начертания, если они описаны в `@font-face` или есть в системном шрифте.
```

Это пока ещё редкое свойство, так что добавил пояснение.

2021-09-06 21:59 UTC, pepelsbey commented on css/font-stretch/index.md
> +- `normal` — стандартная ширина шрифта (значение по умолчанию).
```suggestion
- `normal` — нормальная или «текстовая» ширина шрифта (значение по умолчанию).
```

2021-09-07 10:11 UTC, pepelsbey approved these changes

2021-09-07 10:11 UTC, merged