Добавляет плейсхолдер для font-variant
doka-guide/content pull request #1451
Opened 2021-09-02 18:03 UTC by solarrust

2021-09-03 08:20 UTC, tachisis commented on css/font-variant/index.md
> +- `small-caps` — строчные буквы становятся уменьшенной копией строчных букв.
```suggestion
- `small-caps` — строчные буквы становятся уменьшенной копией прописных букв.
```

2021-09-04 08:59 UTC, tachisis approved these changes

2021-09-06 22:03 UTC, pepelsbey requested changes
Это [сокращённое свойство](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant), у него внутри есть несколько:

- font-variant-alternates
- font-variant-caps
- font-variant-east-asian
- font-variant-ligatures
- font-variant-numeric

И только [font-variant-caps](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-caps) отвечает за капитель.

Ну то есть можно записать `font-variant: small-caps`, но это будет как `background: red`.

Думаю, это нужно как-то учесть.

2021-09-07 12:20 UTC, pepelsbey approved these changes

2021-09-07 12:21 UTC, merged