Добавляет плейсхолдер для font-variant-numeric
doka-guide/content pull request #1452
Opened 2021-09-02 18:14 UTC by solarrust

2021-09-03 08:21 UTC, tachisis approved these changes

2021-09-06 21:32 UTC, pepelsbey requested changes

2021-09-06 21:32 UTC, pepelsbey commented on css/font-variant-numeric/index.md
> +- `oldstyle-nums` — набор цифр, в котором 3, 4, 7, 9 немного опущены по отношению к базовой линии.
```suggestion
- `oldstyle-nums` — набор строчных цифр, в котором 3, 4, 7, 9 свешиваются с базовой линии.
```

2021-09-06 21:32 UTC, pepelsbey commented on css/font-variant-numeric/index.md
> +- `tabular-nums` — одинаковый размер каждой цифры.
```suggestion
- `tabular-nums` — одинаковая ширина каждой цифры.
```

2021-09-07 10:16 UTC, pepelsbey approved these changes

2021-09-07 10:16 UTC, merged