Добавляет плейсходлер для font-feature-settings
doka-guide/content pull request #1453
Opened 2021-09-02 18:38 UTC by solarrust

2021-09-03 08:28 UTC, tachisis commented on css/font-feature-settings/index.md
> +Свойство `font-feature-settings` расширяет возможности типографики шрифтов с расширенным набором символов.
```suggestion
Свойство `font-feature-settings` позволяет управлять функциями шрифтов с расширенным набором символов.
```

2021-09-03 08:28 UTC, tachisis commented on css/font-feature-settings/index.md
> +- `onum` — фигуры в старом стиле.
```suggestion
- `onum` — цифры в старом стиле.
```

2021-09-04 09:00 UTC, tachisis approved these changes

2021-09-06 22:05 UTC, pepelsbey requested changes

2021-09-06 22:05 UTC, pepelsbey commented on css/font-feature-settings/index.md
> +- `ss**` — стилистические наборы 01–20.
```suggestion
- `ss**` — стилистические наборы 01–20, например `ss01`, `ss02` и так далее.
```

2021-09-07 10:16 UTC, pepelsbey approved these changes

2021-09-07 10:16 UTC, merged