Добавляет плейсхолдер для font-kerning
doka-guide/content pull request #1454
Opened 2021-09-02 18:50 UTC by solarrust

2021-09-03 08:28 UTC, tachisis approved these changes

2021-09-06 21:27 UTC, pepelsbey requested changes

2021-09-06 21:27 UTC, pepelsbey commented on css/font-kerning/index.md
> +Свойство `font-kerning` позволяет управлять кернингом шрифта. _Кернингом_ называют расстояние между определёнными буквами. При включённом кернинге буквы приближаются друг к другу, что сохраняет гориз
```suggestion
Свойство `font-kerning` позволяет включать или выключать встроенный кернинг шрифта. _Кернингом_ называют расстояние между парами букв. При включённом кернинге буквы приближаются или отдаляются друг от друга, чтобы компенсировать особенности их формы и сохранить горизонтальный ритм текста.
```

2021-09-06 21:27 UTC, pepelsbey commented on css/font-kerning/index.md
> +
```suggestion
- `auto` — браузер сам решает, где включать кернинг, а где нет (значение по умолчанию).
- `normal` — включает кернинг.
- `none` — выключает кернинг.

Как правило, для мелкого шрифта браузер отключает кернинг, а для крупного оставляет. Поэтому значение `auto` разумно менять, только если вы точно уверены, что вам это нужно.
```

Вытащил описание из списка и немного развил.

2021-09-07 10:15 UTC, pepelsbey approved these changes

2021-09-07 10:15 UTC, merged