Добавляет плейсхолдер для font-size-adjust
doka-guide/content pull request #1455
Opened 2021-09-02 18:53 UTC by solarrust

2021-09-04 09:00 UTC, tachisis approved these changes

2021-09-06 22:14 UTC, pepelsbey requested changes
Кажется перепутала с [text-size-adjust](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust)

2021-09-06 22:14 UTC, pepelsbey commented on css/font-size-adjust/index.md
> +Свойство `font-size-adjust` позволяет задать размер шрифта, ориентируясь на размер строчных букв, а не прописных. Это даёт дополнительный контроль над тем, как на некоторых мобильных устройствах буде
```suggestion
Свойство `font-size-adjust` позволяет задать высоту строчных букв относительно прописных, размер которых задаётся с помощью [`font-size`](/css/font-size). Соотношение строчных к прописным — уникальная характеристика шрифта и это свойство помогает компенсировать слишком мелкие или слишком крупные строчные, чтобы комбинировать разные шрифты вместе.
```

2021-09-06 22:14 UTC, pepelsbey commented on css/font-size-adjust/index.md
> +
````suggestion

```css
code {
  font-size: 16px;
  font-size-adjust: 0.5;
}
```

Высота строчных для кода будет 0,5 от размера шрифта, то есть 8 пикселей.

````

2021-09-07 10:15 UTC, pepelsbey approved these changes

2021-09-07 10:15 UTC, merged