Добавляет статью `window.print`
doka-guide/content pull request #1461
Opened 2021-09-03 22:17 UTC by nlopin

Closes #1313

2021-09-06 21:10 UTC, pepelsbey requested changes

2021-09-06 21:10 UTC, pepelsbey commented on js/window-print/index.md
> +Если на странице есть [`iframe`](/html/iframe), то вызов `window.print()` внутри него напечатает только этот айфрейм, а не все содержание вкладки браузера:
```suggestion
Если на странице есть [`<iframe>`](/html/iframe), то вызов `window.print()` внутри него напечатает только этот айфрейм, а не все содержимое вкладки браузера:
```

2021-09-06 21:10 UTC, pepelsbey commented on js/window-print/index.md
> +Такой код делает то же самое, что и системное меню _File→Print_.
```suggestion
Такой код делает то же самое, что и системное меню _File → Print_.
```

2021-09-06 21:10 UTC, pepelsbey commented on js/window-print/index.md
> +// представим, что кнопка имеет id 'print-button'
```suggestion
```
Это комментарий кажется лишним :) Мы не представляем, а просто обращаемся к кнопке с нужным ID.

2021-09-07 06:46 UTC, bespoyasov approved these changes

2021-09-07 10:14 UTC, pepelsbey approved these changes

2021-09-07 10:14 UTC, merged