History API
doka-guide/content pull request #1467
Opened 2021-09-06 19:48 UTC by Windrushfarer

Fixes #1306

2021-09-06 19:48 UTC, Windrushfarer commented
Пишите что я мог забыть и особенно насколько понятно описал примеры :)

2021-09-06 21:27 UTC, nlopin commented on js/history-api/index.md
> +- В первый аргумент-объект можно записать любой объект с любыми данными, главное чтобы объект был сериализуемым. Так же браузеры могут накладывать ограничения на размер такого объекта.
а сериализуемым в какой формат?

2021-09-06 21:44 UTC, nlopin commented on js/history-api/index.md
> +Адрес в браузерной строке снова изменился, но теперь вместо перезагрузки страницы вставьте в строку URL ведущей в раздел JavaScript `https://doka.guide/js/`. После отображения страницы, можно нажать
не понял абзаца. Мне нужно что-то вставить в строку браузера?

2021-09-06 21:49 UTC, nlopin commented on js/history-api/practice/windrushfarer.md
> +  console.log(`Данные навигации: ${JSON.stringify(event.state)}`);
Тут точно `stringify` а не `parse`?

2021-09-07 04:44 UTC, nlopin commented on js/history-api/index.md
> +History API даёт доступ к управлению истории браузере в текущей сессии.
```suggestion
History API даёт доступ к управлению историей браузера в текущей сессии.
```

2021-09-07 07:23 UTC, bespoyasov approved these changes
За меня почти всё сказали 😅 
Я тут просто рядом пару идей докинул.

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +Новая сессия начинается когда открывается новая вкладка или новое окно браузера.
Мне кажется, это можно сделать частью предыдущего параграфа — оно вроде плавно вытекает из первого предложения, а в первом не хватает пояснения, что такое сессия 🙃

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +- `window.history.pushState()` позволяет добавить новую запись в истории сессии
```suggestion
- `window.history.pushState()` добавляет новую запись в истории сессии
```

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +- `window.history.replaceState()` позволяет изменить текущую запись в истории сессии
```suggestion
- `window.history.replaceState()` изменяет текущую запись в истории сессии
```

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +Чтобы переместится по истории вперёд, используется метод `window.history.forward()`. Он работает аналогично кнопке вперёд в браузере.
```suggestion
Чтобы переместиться по истории вперёд, используется метод `window.history.forward()`. Он работает аналогично кнопке вперёд в браузере.
```

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +Метод `window.history.go()` является универсальным методом, чтобы переместится по истории вперёд или назад относительно текущей страницы.
```suggestion
Метод `window.history.go()` является универсальным методом, чтобы переместиться по истории вперёд или назад относительно текущей страницы.
```

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +Метод принимает один аргумент – число, которое определяет на сколько шагов по истории вперёд или назад нужно перейти. Отрицательное значение определяет сколько шагов назад, а положительные – вперёд.
```suggestion
Метод принимает один аргумент – число, которое определяет, на сколько шагов по истории вперёд или назад нужно перейти. Отрицательное значение определяет сколько шагов назад, а положительные – вперёд.
```

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +Метод принимает один аргумент – число, которое определяет на сколько шагов по истории вперёд или назад нужно перейти. Отрицательное значение определяет сколько шагов назад, а положительные – вперёд.
Пояснение про отрицательные числа — 👍 
Прям предугадал, что я хочу спросить 😃

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +Нулевая позиция `0` означает текущую страницу и вызов с нулём обновляет текущую страницу.
Может, добавить коллаут, что для перезагрузки лучше воспользоваться `.reload()`? 🤔

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/index.md
> +С другой стороны есть одностраничные приложения, которые работают без перезагрузки страницы. Все содержимое они отрисовывают с помощью JavaScript, используя DOM API.  Таким образом приложение может п
```suggestion
С другой стороны есть одностраничные приложения, которые работают без перезагрузки страницы. Все содержимое они отрисовывают с помощью JavaScript, используя DOM API. Таким образом приложение может перерисовать всю страницу, но на истории браузера это никак не отобразится.
```

2021-09-07 07:23 UTC, bespoyasov commented on js/history-api/practice/windrushfarer.md
> +Чтобы узнать, когда переход был завершён необходимо подписаться на [событие](/js/events)  `popstate` в Window:
```suggestion
Чтобы узнать, когда переход был завершён необходимо подписаться на [событие](/js/events) `popstate` в Window:
```

2021-09-07 08:29 UTC, nlopin commented on js/history-api/index.md
> +Адрес в браузерной строке снова изменился, но теперь вместо перезагрузки страницы вставьте в строку URL ведущей в раздел JavaScript `https://doka.guide/js/`. После отображения страницы, можно нажать
Тут очень просится демка, мы в рамках айфрейма сможем ходить взад-вперёд в браузере

2021-09-07 09:40 UTC, nlopin commented
@Windrushfarer я немного поправил текст, посмотри, пожалуйста. Я ничего не трогал в повествовании.

Из того, на что стоит обратить внимание в следующих материалах:
* Переименовал «поле» в «свойство» потому что поле это больше про объекты классов
* Когда ссылаемся на методы, достаточно использовать только имя, если рядом есть пример. «Метод `window.history.back()` перемещает пользователя по истории назад.» → «Метод `back` перемещает пользователя по истории назад.»

2021-09-07 09:40 UTC, nlopin commented on js/history-api/index.md
> +Новая сессия начинается когда открывается новая вкладка или новое окно браузера.
Перенёс

2021-09-07 09:49 UTC, nlopin requested changes
Путь поменялся, незакрытые обсуждения актуальны, хотя гитхаб так не считает

2021-09-07 12:12 UTC, pepelsbey requested changes

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +```
```suggestion
- https://example.com/buy
- https://example.com/prices
- https://example.com/about
- https://example.com/
```
Это просто список, не код

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +```
```suggestion
- https://example.com/
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/practice/windrushfarer.md
> +
```suggestion
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/practice/windrushfarer.md
> +
```suggestion
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +- `back` перемещает пользователя по истории на страницу назад
```suggestion
Основные методы:

- `back` перемещает пользователя по истории на страницу назад
```

Это только в тексте выглядит как заголовок списка, но фактически это будет параграф и список. Так что лучше разделять это пустой сторокой, чтобы не было ложных ожиданий :)

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +- используемые для перемещения по истории в текущей сессии.
```suggestion
Сгруппируем методы и свойства History API на две части:

- используемые для перемещения по истории в текущей сессии.
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +- объект состояния, в который можно добавить любые данные, необходимые для навигации;
```suggestion
Оба метода похожи с точки зрения использования и оба принимают три аргумента:

- объект состояния, в который можно добавить любые данные, необходимые для навигации;
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +- В первый аргумент-объект можно записать любой объект с любыми данными, главное чтобы объект был сериализуемым. Браузеры могут накладывать ограничения на размер такого объекта.
```suggestion
У передаваемых аргументов есть ограничения, о которых стоит помнить:

- В первый аргумент-объект можно записать любой объект с любыми данными, главное чтобы объект был сериализуемым. Браузеры могут накладывать ограничения на размер такого объекта.
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +О том для чего вообще может понадобится передавать данные во время навигации смотрите раздел "В работе".
```suggestion
О том для чего вообще может понадобится передавать данные во время навигации смотрите раздел «[В работе](#v-rabote)».
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +Предположим, что мы зашли на страницу `https://doka.guide/js/` с новой вкладки. Добавим новую запись в историю:
```suggestion
Предположим, что мы зашли на страницу https://doka.guide/js/ с новой вкладки. Добавим новую запись в историю:
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +Адрес в браузерной сроке изменился и если нажать кнопку перезагрузки страницы, то мы увидим статью про [var и let](/js/var-let), а не страницу раздела.
```suggestion
Адрес в браузерной сроке изменился и если нажать кнопку перезагрузки страницы, то мы увидим статью про [`var` и `let`](/js/var-let), а не страницу раздела.
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/index.md
> +Помните как мы на предыдущей странице видели статью про var и let? Теперь после перехода назад мы будем видеть страницу раздела HTML. Это произошло потому что мы изменили текущую запись в истории, из
```suggestion
Помните как мы на предыдущей странице видели статью про `var` и `let`? Теперь после перехода назад мы будем видеть страницу раздела HTML. Это произошло потому что мы изменили текущую запись в истории, изменив её URL-адрес. В результате когда мы возвращаемся назад по истории, то уже не застанем предыдущую страницу, а попадём по новой ссылке на другую страницу.
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/practice/windrushfarer.md
> +});
```suggestion
})
```

2021-09-07 12:12 UTC, pepelsbey commented on js/window-history/practice/windrushfarer.md
> +});
```suggestion
  console.log(`Данные навигации: ${JSON.stringify(event.state)}`)
})
```

2021-09-07 16:52 UTC, Windrushfarer commented on js/history-api/index.md
> +Адрес в браузерной строке снова изменился, но теперь вместо перезагрузки страницы вставьте в строку URL ведущей в раздел JavaScript `https://doka.guide/js/`. После отображения страницы, можно нажать
Но проблема с демкой в том, что надо тогда создать несколько страниц и связать их. Я не уверен как это будет работать.
Если у нас уже есть что-то подобное, я буду рад посмотреть и сделаю

2021-09-07 16:54 UTC, Windrushfarer commented on js/history-api/index.md
> +Нулевая позиция `0` означает текущую страницу и вызов с нулём обновляет текущую страницу.
А имеет смысл? Предложение вроде не несёт рекомендательного характера ¯\\\_(ツ)_/¯

2021-09-07 16:56 UTC, Windrushfarer commented on js/history-api/index.md
> +- В первый аргумент-объект можно записать любой объект с любыми данными, главное чтобы объект был сериализуемым. Так же браузеры могут накладывать ограничения на размер такого объекта.
Добавил про JSON для краткости

2021-09-07 16:57 UTC, Windrushfarer commented on js/window-history/practice/windrushfarer.md
> +
Не понял, зачем убирать пустые строки?

2021-09-07 17:03 UTC, Windrushfarer commented
@nlopin я не понял насчёт пути? Мне нужно что-то ещё сделать? Ты ведь поменял уже нас расположение файлов и ссылки

2021-09-07 19:03 UTC, nlopin commented
@Windrushfarer мне сейчас не нравится объяснение примера, часть с «вставьте теперь вот этот урл в строку, но не нажимайте ничего». Хочется его поменять или сделать демку

2021-09-08 09:28 UTC, Windrushfarer commented
@nlopin добавил демку, получилось придумать простой концепт и, надеюсь, оно будет работать в превью 🙏

2021-09-08 09:59 UTC, pepelsbey commented on js/window-history/practice/windrushfarer.md
> +
Потому, что код закончился, зачем там пустая строка?

2021-09-08 10:02 UTC, pepelsbey commented on js/window-history/index.md
> +```
Я думал мы обсудим, почему это код, а не список. А тут просто резолв и тишина, странно 🤔

2021-09-08 14:24 UTC, Windrushfarer commented
Не работает демка :(
На этапе с перезагрузкой страницы все ломается.

2021-09-08 15:51 UTC, nlopin commented on js/window-history/index.md
> +```
очевидно, что это не код

2021-09-08 16:27 UTC, nlopin commented
Поправил демку, в ней использовались абсолютные пути к страницам. Локально у меня всё завелось, проверяю на превью. 

Я пока не осознал, поможет демка читателю или только больше запутает 🤔

2021-09-09 07:36 UTC, Windrushfarer commented
@nlopin мне кажется вполне, по крайней мере можно ощутить как это работает, помимо описания.

2021-09-11 20:54 UTC, nlopin approved these changes

2021-09-12 08:55 UTC, pepelsbey requested changes
У нас сейчас схема работы с демками [описана иначе](https://github.com/doka-guide/content/blob/main/docs/demos.md):

1. Демка — это отдельная папка demos/my-demo
2. Демка — это один файл, в котором есть всё, что нужно

Здесь я понимаю, что все файлы демок нужны для демки (нужно это отразить в документации), но отдельную папку я бы всё же завёл. Чтобы продолжила работать схема и чтобы можно было добавить другие демки и не ломать пути.

2021-09-13 10:33 UTC, tachisis approved these changes
Апрув на словарь

2021-09-14 11:05 UTC, pepelsbey approved these changes

2021-09-14 20:54 UTC, merged