Добавляет статью «Что такое CI/CD?»
doka-guide/content pull request #1477
Opened 2021-09-07 15:14 UTC by igsekor

Планировалось рассказать обзорно о том, что это такое, для чего нужно и как используется.

2021-09-07 19:09 UTC, nlopin commented on tools/ci-cd/index.md
> +description: "Совокупность технологий для автоматизации процесса доставки приложений до потребителей"
офигенное описание

2021-09-08 11:47 UTC, pepelsbey requested changes

2021-09-08 11:47 UTC, pepelsbey commented on tools/ci-cd/index.md
> +CI/CD (Continuous Integration / Continuous Delivery) — непрерывная интеграция и доставка — это подход к разработке программного продукта, при использовании которого задачи сборки, публикации, тестиро
```suggestion
CI/CD (Continuous Integration и Continuous Delivery — непрерывная интеграция и доставка) — это подход к разработке программного продукта, при использовании которого задачи сборки, публикации, тестирования и прочие автоматизированы полностью или частично. Очень часто автоматизация вплетена в бизнес-процессы продуктовой команды или компании, но практики CI/CD могут быть прекрасно внедрены и в проекты, в которых участвует только один разработчик.
```

2021-09-08 11:47 UTC, pepelsbey commented on tools/ci-cd/index.md
> +- «[Мультиконтейнерное приложение и Docker Compose](/tools/docker-compose/)».
```suggestion
- [Что такое Docker?](/tools/docker/).
- [Как устроен Dockerfile](/tools/dockerfile/).
- [Управление данными в Docker](/tools/docker-data-management/).
- [Мультиконтейнерное приложение и Docker Compose](/tools/docker-compose/).
```

Мне кажется, что в таких списках кавычки только добавляют визуальный шум и не помогают. В тексте кавычки выделяют название от предложении, чтобы не было сомнений, а тут незачем. Но дождёмся @tachisis для верности :)

2021-09-08 11:47 UTC, pepelsbey commented on tools/ci-cd/index.md
> +На этом этапе широко применяются интеграционные тесты, e2e тесты, ручное и автоматизированное тестирование UI/UX. Для этого могут использоваться различные инструменты. Например, [jest](https://jestjs
```suggestion
На этом этапе широко применяются интеграционные тесты, E2E-тесты, ручное и автоматизированное тестирование UI/UX. Для этого могут использоваться различные инструменты. Например, [Jest](https://jestjs.io) может покрыть задачи модульного, интеграционного и E2E-тестирования веб-приложения. Для генерации скриншотов веб-приложения и автоматического сравнения с эталоном можно использовать [Selenium](https://www.selenium.dev) или [Puppeteer](https://pptr.dev). При этом можно промоделировать не только загрузку веб-приложения и сохранить скриншоты экранов разных размеров, но и посмотреть с помощью сценариев, как будущий пользователь будет взаимодействовать с приложением.
```

2021-09-08 11:47 UTC, pepelsbey commented on tools/ci-cd/index.md
> +4. В рамках pull request можно проверить все предлагаемые изменения, обсудить решения и прийти к приемлемому решению.
```suggestion
3. Затем формируется пул-реквест — это запрос на слияние в основную ветку.
4. В рамках пул-реквест можно проверить все предлагаемые изменения, обсудить решения и прийти к приемлемому решению.
```

2021-09-08 16:39 UTC, nlopin commented on tools/ci-cd/index.md
> +### Ручное тестирование
Может ты имел ввиду просто «Тестирование»? Во втором абзаце говорится, что всякое тестирование происходит и ручное и автоматическое

2021-09-08 16:42 UTC, nlopin commented
@igsekor может схемку нарисуем? что-то вот такое 
![image](https://user-images.githubusercontent.com/1469636/132549983-4bc784ce-3a48-4d0d-93fe-00d3f7581cb5.png)

Для меня CI это в первую очередь про сборку и автоматическую проверку качества, а CD про выкатку в прод без участия разработчика. Хочется подчеркнуть это

2021-09-08 16:44 UTC, igsekor commented on tools/ci-cd/index.md
> +### Ручное тестирование
Пожалуй, что да!

2021-09-09 06:34 UTC, bespoyasov approved these changes
Огонь! За статьи о бранчинге — жирный лайк 👍

2021-09-09 06:34 UTC, bespoyasov commented on tools/ci-cd/index.md
> +Например, по запросу от пользователей или владельца продукта дизайнеры дорабатывают интерфейс пользователя, разработчики пишут код, исправляют ошибки и внедряют новый функционал. Затем в дело вступаю
```suggestion
Например, по запросу от пользователей или владельца продукта дизайнеры дорабатывают интерфейс пользователя, разработчики пишут код, исправляют ошибки и внедряют новую функциональность. Затем в дело вступают тестировщики, которым приложение приходит в собранном виде, пройдя все необходимые автоматические проверки на качество и правильность работы кода. После успешного тестирования пользователи получают готовый к использованию продукт, отмечают баги и видят, как функциональность может быть ещё расширена. Процесс циклически повторяется вновь и вновь.
```

2021-09-09 06:34 UTC, bespoyasov commented on tools/ci-cd/index.md
> +Например, по запросу от пользователей или владельца продукта дизайнеры дорабатывают интерфейс пользователя, разработчики пишут код, исправляют ошибки и внедряют новый функционал. Затем в дело вступаю
Предлагаю использовать термины так, чтобы нам после запуска не прилетело от математиков 😃

2021-09-09 06:34 UTC, bespoyasov commented on tools/ci-cd/index.md
> +Применение автоматизации процессов разработки снижает риск ошибок, позволяет оперативно чинить то, что не работает. Настройка инструментов CI/CD затрагивает и такую часть разработки, как создание еди
```suggestion
Применение автоматизации процессов разработки снижает риск ошибок, позволяет оперативно чинить то, что не работает. Настройка инструментов CI/CD затрагивает и такую часть разработки, как создание единого окружения, в котором ведётся разработка программного продукта. Для разработчика это крайне важно. 

Например, использование одних и тех же npm-пакетов, их версий и инструментов тестирования позволяет разрабатывать приложение по единым стандартам качества. Случайные ошибки из-за неправильного окружения или другой операционной системы практически исключены.
```

2021-09-09 06:34 UTC, bespoyasov commented on tools/ci-cd/index.md
> +4. В рамках пул-реквест можно проверить все предлагаемые изменения, обсудить решения и прийти к приемлемому решению.
```suggestion
4. В рамках пул-реквеста можно проверить все предлагаемые изменения, обсудить решения и прийти к приемлемому решению.
```

2021-09-09 06:34 UTC, bespoyasov commented on tools/ci-cd/index.md
> +Для автоматизации сборки могут использоваться различные системы, например, [Jenkins](https://www.jenkins.io), [GitLab CI/CD](https://docs.gitlab.com/ee/ci/), [Bitbucket Pipelines](https://bitbucket.o
А может выделим самые популярные и сделаем небольшой список? Я просто думаю, надо ли перечислять все-все 🤔

2021-09-13 15:03 UTC, tachisis approved these changes
Апрув на словарь

2021-09-14 11:26 UTC, pepelsbey approved these changes

2021-09-16 14:51 UTC, nlopin approved these changes

2021-09-16 19:00 UTC, merged