Добавляет плейсхолдер для @font-feature-values
doka-guide/content pull request #1497
Opened 2021-09-09 17:48 UTC by solarrust

@pepelsbey сложна... Нужна помощь с формулировками

2021-09-10 13:59 UTC, pepelsbey requested changes
Проблема этой статьи в том, что никто из нас не использовал эту директиву и до конца не понимаем принципов её работы. Мы не можем её адекватно описать.

Я бы предложил не писать об этом.

2021-09-10 14:06 UTC, solarrust commented on css/font-feature-values/index.md
> +Директива `@font-feature-values` позволяет назначить для каждого шрифта удобное для человека имя и сопоставить его с индексом функций. Используя эти дружественные имена, можно легко включать похожие
Сложность в том, что на эту директиву ссылается другая статья https://doka.guide/css/font-variant-alternates/ =(

2021-09-12 08:57 UTC, pepelsbey commented on css/font-feature-values/index.md
> +Директива `@font-feature-values` позволяет назначить для каждого шрифта удобное для человека имя и сопоставить его с индексом функций. Используя эти дружественные имена, можно легко включать похожие
Можно не ссылаться :)

2021-09-21 22:59 UTC, pepelsbey commented
Ну что, давай может не будем писать про то, чего не знаем и что, вероятно, мало кому пригодится (если вообще работает) и ещё уберём ссылку из другой статьи?

2021-09-22 05:03 UTC, solarrust commented
Ладно =(

2021-09-22 05:03 UTC, closed without merging