Дополняет документ по оформлению кода
doka-guide/content pull request #1511
Opened 2021-09-10 11:37 UTC by igsekor

Выяснилось, что необходимо добавить в документацию список доступных для использования в блоках кода языков.

У нас используется пакет [`highlight.js`](https://highlightjs.org), список поддерживаемых языков доступен по [ссылке](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md) в репозитории.

Предлагается дополнить документацию ссылкой на список и соответствующие псевдонимы.

2021-09-10 11:54 UTC, pepelsbey requested changes

2021-09-10 11:54 UTC, pepelsbey commented on docs/typography.md
> +Доступные для использования языки и их псевдонимы можно найти в [списке](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md).
```suggestion
Доступные для использования языки и их псевдонимы можно найти [в документации Highlight.js](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md).
```

2021-09-11 19:35 UTC, nlopin approved these changes

2021-09-12 18:04 UTC, pepelsbey approved these changes

2021-09-12 18:04 UTC, merged