Добавляет плейсхолдер для touch-action
doka-guide/content pull request #1536
Opened 2021-09-10 16:30 UTC by solarrust

@pepelsbey может быть у тебя будет идея на что заменить слово «панорамировать»

2021-09-12 18:27 UTC, pepelsbey requested changes

2021-09-12 18:27 UTC, pepelsbey commented on css/touch-action/index.md
> +
```suggestion
- `manipulation` — элемент можно cдвигать и зумить. Это сокращение для комбинации `pan-x pan-y pinch-zoom`. Остальные нестандартные жесты, вроде двойного тапа, запрещены.
- `pan-x` — элемент можно сдвигать по оси _x_ с помощью одного пальца. Это сокращение для значений `pan-left` и `pan-right`. Может использоваться в сочетании с `pan-y`, `pan-up`, `pan-down` и `pinch-zoom`.
- `pan-y` — элемент можно смещать по оси _y_ с помощью одного пальца. Это сокращение для значений `pan-up` и `pan-down`. Может использоваться в сочетании с `pan-x`, `pan-left`, `pan-right` и `pinch-zoom`.
- `pan-left` — элемент можно смещать только если начать движение от левого края (эксперимент).
- `pan-right` — элемент можно смещать только если начать движение от правого края (эксперимент).
- `pan-down` — элемент можно смещать только если начать движение снизу вверх (эксперимент).
- `pan-up` — элемент можно смещать только если начать движение сверху вниз (эксперимент).
- `pinch-zoom` — элемент можно зазумить щипком. Можно совместить с `pan-x`, `pan-left`, `pan-right`, `pan-y`, `pan-up`, `pan-down`.
```

2021-09-12 18:27 UTC, pepelsbey commented on css/touch-action/index.md
> +tags —
```suggestion
title: "`touch-action`"
description: ""
authors:
  - doka-dog
tags:
```

2021-09-13 10:37 UTC, solarrust commented on css/touch-action/index.md
> +tags —
ой, автозамена 😅

2021-09-13 11:29 UTC, pepelsbey approved these changes

2021-09-13 11:29 UTC, merged