Вносит правки в Contributing.md
doka-guide/content pull request #1546
Opened 2021-09-13 11:22 UTC by solarrust

Посмотрите, пожалуйста, правки. Какие-то из них стилистические и не принципиальные, а какие-то отражают текущие договорённости. Например, пути до демок и комментарии на отдельных строках.

2021-09-13 11:29 UTC, pepelsbey requested changes

2021-09-13 11:29 UTC, pepelsbey commented on docs/contributing.md
> +Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на GitHub — он поможет вам предложить их в Pull request'е. Если вы пишете
```suggestion
Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на GitHub — он поможет вам предложить их в пул-реквесте. Если вы пишете новую статью или делаете обширные правки, то лучше форкните репозиторий, склонируйте его себе локально и откройте в любимом редакторе кода.
```

Мы уже вроде свободно используем эти термины

2021-09-13 11:29 UTC, pepelsbey commented on docs/contributing.md
> +<iframe title="Блок с рваным краем, но без пробела" src="../demos/shadow/index.html"></iframe>
```suggestion
<iframe title="Блок с рваным краем, но без пробела" src="../demos/shadow/"></iframe>
```

2021-09-13 11:29 UTC, pepelsbey commented on docs/contributing.md
> +<iframe title="Блок с рваным краем, но без пробела" src="../demos/shadow/index.html"></iframe>
```suggestion
<iframe title="Блок с рваным краем, но без пробела" src="../demos/shadow/"></iframe>
```

2021-09-13 12:11 UTC, solarrust commented on docs/contributing.md
> +Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на GitHub — он поможет вам предложить их в Pull request'е. Если вы пишете
А точно через тире? И с одной буквой «л»? Просто уточняю =)

2021-09-13 12:19 UTC, furtivite commented on docs/contributing.md
> +Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на GitHub — он поможет вам предложить их в Pull request'е. Если вы пишете
> А точно через тире? И с одной буквой «л»? Просто уточняю =)

Мы, вроде бы, говорили, что будем придерживаться словаря из Веб-стандартов. [Там "пулреквест"](https://github.com/web-standards-ru/dictionary/blob/main/dictionary.md#pull-request-pr)

2021-09-13 12:50 UTC, tachisis commented on docs/contributing.md
> +Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на GitHub — он поможет вам предложить их в Pull request'е. Если вы пишете
Я не могу сейчас найи источник, поиск по Грамоте чудовищный, но суть в том, что большинство иноязычных треминов, которые в английском языке состоят из двух раздельных слов, в русском языке фиксируются в словарях через дефис. Например, все со словом «веб-»: http://gramota.ru/slovari/dic/?lop=x&bts=x&ro=x&zar=x&ag=x&ab=x&sin=x&lv=x&az=x&pe=x&word=%D0%B2%D0%B5%D0%B1

В каком-то из ПР мы уже обсуждали этот вопрос и пришли к выводу, что будет следовать тенденциям кодификации и примем за верный дефисный вариант. В словаре веб-стандартов это надо поправить, но у меня все еще не дошли руки.

Пример конкретно этого слова в дефисном написании есть, например, в оф. документации Atlassian, что в целом не кот чихнул https://www.atlassian.com/ru/git/tutorials/making-a-pull-request

2021-09-13 12:52 UTC, tachisis commented on docs/contributing.md
> +Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на GitHub — он поможет вам предложить их в Pull request'е. Если вы пишете
P.S. удвоение букв в русском языке тоже опускается при кодификации, например: кол-центр http://gramota.ru/slovari/dic/?lop=x&bts=x&ro=x&zar=x&ag=x&ab=x&sin=x&lv=x&az=x&pe=x&word=%D0%BA%D0%BE%D0%BB-%D1%86%D0%B5%D0%BD%D1%82%D1%80

2021-09-13 13:42 UTC, pepelsbey commented on docs/contributing.md
> +Контент Доки — это текстовые файлы в маркдауне и картинки. Если вы хотите сделать быструю правку, то можно сделать это прямо на GitHub — он поможет вам предложить их в Pull request'е. Если вы пишете
@tachisis закинул [ПР в словарь](https://github.com/web-standards-ru/dictionary/pull/446)

2021-09-14 09:47 UTC, tachisis approved these changes

2021-09-14 11:36 UTC, pepelsbey approved these changes

2021-09-14 11:48 UTC, merged