Вносит исправление во флоу в главном README.md
doka-guide/content pull request #1561
Opened 2021-09-13 19:37 UTC by furtivite

Если контрибутор не входит в организацию @doka-guide, он не сможет сделать вклад без форка. 

- Правит флоу
- Правит пул-реквест -> пулреквест

2021-09-14 11:08 UTC, pepelsbey requested changes

2021-09-14 11:08 UTC, pepelsbey commented on README.md
> +1. Закончили? Создайте пулреквест. Вот и всё! После небольшой проверки ваш материал появится на сайте Доки!
```suggestion
1. Закончили? Создайте пул-реквест. Вот и всё! После небольшой проверки ваш материал появится на сайте Доки!
```

И всё же пул-реквест, [мы договорились](https://github.com/web-standards-ru/dictionary/pull/446)

2021-09-14 11:08 UTC, pepelsbey commented on README.md
> +1. Сделайте Fork [репозитория с контентом](https://github.com/doka-guide/content) и склонируйте его на машину.
```suggestion
1. Форкните [репозитория с контентом](https://github.com/doka-guide/content) и склонируйте его себе.
```

2021-09-14 11:19 UTC, tachisis commented on README.md
> +1. Форкните [репозитория с контентом](https://github.com/doka-guide/content) и склонируйте его себе.
```suggestion
1. Форкните [репозиторий с контентом](https://github.com/doka-guide/content) и склонируйте его к себе.
```

2021-09-20 07:05 UTC, pepelsbey approved these changes

2021-09-20 12:13 UTC, tachisis approved these changes

2021-09-20 12:13 UTC, merged