Добавляет страницу с лицензией
doka-guide/content pull request #1570
Opened 2021-09-15 07:47 UTC by furtivite

Добавляет страницу с лицензией, чтобы в подвале не было битой ссылки

Тексты взяты из [доки в контенте](https://github.com/doka-guide/content/blob/main/docs/license.md), плюс написаны для платформы и особых случаев (особые случаи - это, к примеру, шрифты).

2021-09-15 10:20 UTC, pepelsbey requested changes
Очень полезная страница! Спасибо.

Но я бы предложил её подсушить от лишнего и поджать параграфы плотнее — см. саджесты.

2021-09-15 10:20 UTC, pepelsbey commented on pages/licenses/index.md
> +Это значит, что с содержимым [репозитория](https://github.com/doka-guide/platform) можно делать что угодно, но ни мы, ни те, кто работал с кодом для нас ничего не обещает, не несёт никаких гарантий,
> что эти буквы и цифры могут вас пригодиться для любых ваших задач

Не уверен, что это значит

2021-09-15 10:20 UTC, pepelsbey commented on pages/licenses/index.md
> +Дока — это добрая энциклопедия для веб-разработчиков. Наша цель — сделать документацию по веб-разработке практичной, понятной и не унылой.
```suggestion
```

Хочется оставить на этой странице только полезное и уникальное, это интро здесь ничего не добавляет

2021-09-15 10:20 UTC, pepelsbey commented on pages/licenses/index.md
> +
```suggestion
## Контент в Доке
В Доке есть много текстов и кода, а ещё есть мультимедиа: картинки, видео, анимация.

```

Можно убрать и ничего не изменится :)

2021-09-15 10:20 UTC, pepelsbey commented on pages/licenses/index.md
> +### Как распространяются тексты
```suggestion
## Лицензия на текст
```

2021-09-15 10:20 UTC, pepelsbey commented on pages/licenses/index.md
> +### Как распространяются остальные материалы
```suggestion
## Лицензия на остальное
```

2021-09-15 10:20 UTC, pepelsbey commented on pages/licenses/index.md
> +## Платформа на базе Eleventy
```suggestion
## Лицензия на код
```

2021-09-15 10:20 UTC, pepelsbey commented on pages/licenses/index.md
> +Это значит, что такой контент можно распространять в любом виде, пока вы не изменяете его, сохраняете ссылку на Доку и упоминание наших дизайнеров, плюс не просите за ваш продукт деньги.
```suggestion
Весь остальной контент в Доке, кроме текста, распространяется по лицензии [CC BY-NC-ND 4.0](https://github.com/doka-guide/content/blob/main/LICENSE-ND.md). Его можно распространять в любом виде, пока вы не изменяете его, сохраняете ссылку на Доку и упоминание наших дизайнеров, плюс не просите за ваш продукт деньги.
```

2021-09-15 10:20 UTC, pepelsbey commented on pages/licenses/index.md
> +Это значит, что с содержимым [репозитория](https://github.com/doka-guide/platform) можно делать что угодно, но ни мы, ни те, кто работал с кодом для нас ничего не обещает, не несёт никаких гарантий,
```suggestion
Мы сохранили для платформы на базе [Eleventy](https://www.11ty.dev) лицензию [MIT](https://github.com/doka-guide/platform/blob/main/LICENSE.md). С содержимым [репозитория](https://github.com/doka-guide/platform) можно делать что угодно, но ни мы, ни те, кто работал с кодом для нас ничего не обещает, не несёт никаких гарантий, что эти буквы и цифры могут вас пригодиться для любых ваших задач.
```

2021-09-15 10:38 UTC, furtivite commented on pages/licenses/index.md
> +Это значит, что с содержимым [репозитория](https://github.com/doka-guide/platform) можно делать что угодно, но ни мы, ни те, кто работал с кодом для нас ничего не обещает, не несёт никаких гарантий,
> Не уверен, что это значит

Ну я имел в виду всё то, что находится в репозитории с платформой, т.е. рассматривал продукт не как готовый сервис, а как набор символов. Можно переиначить.

2021-09-15 10:39 UTC, furtivite commented on pages/licenses/index.md
> +## Платформа на базе Eleventy
Вот тут я не совсем согласен, потому что код у нас есть в качестве примеров в статьях, он будет распространяться по лицензии на контент. Тут лучше к @tachisis, как мне кажется.

2021-09-17 19:33 UTC, tachisis commented on pages/licenses/index.md
> +Это значит, что с содержимым [репозитория](https://github.com/doka-guide/platform) можно делать что угодно, но ни мы, ни те, кто работал с кодом для нас ничего не обещает, не несёт никаких гарантий,
Согласна, что надо переделать. Смысл абзаца ускользает.

2021-09-17 19:34 UTC, tachisis commented on pages/licenses/index.md
> +
+1, необязательно описывать, что там есть.

2021-09-17 19:35 UTC, tachisis commented on pages/licenses/index.md
> +## Платформа на базе Eleventy
«Лицензия на код платформы»

2021-09-17 19:36 UTC, tachisis commented on pages/licenses/index.md
> +Это значит, что с содержимым [репозитория](https://github.com/doka-guide/platform) можно делать что угодно, но ни мы, ни те, кто работал с кодом для нас ничего не обещает, не несёт никаких гарантий,
Тут надо так же, как выше, внести правку в формулировку.

2021-09-18 08:31 UTC, furtivite commented on pages/licenses/index.md
> +Это значит, что с содержимым [репозитория](https://github.com/doka-guide/platform) можно делать что угодно, но ни мы, ни те, кто работал с кодом для нас ничего не обещает, не несёт никаких гарантий,
```suggestion
Это значит, что с содержимым [репозитория](https://github.com/doka-guide/platform) можно делать что угодно, но вы не получаете гарантий, что код подойдёт для решения ваших задач. 
```

@tachisis @pepelsbey

2021-09-20 12:12 UTC, tachisis commented on pages/licenses/index.md
> +На этой странице мы простым языком рассказываем о том, что можно делать с Докой, а что нет. Юридически значимые тексты находятся в репозиториях, и вы найдёте ссылки на этой странице.
```suggestion
На этой странице мы рассказываем о том, что можно делать с Докой, а что нет, простым языком. Юридически значимые тексты находятся в репозиториях, ссылки на них даны ниже.
```

2021-09-20 12:12 UTC, tachisis commented on pages/licenses/index.md
> +Контент в Доке и платформа распространяется по разным правилам.
```suggestion
Контент в Доке и платформа лицензированы по-разному.
```

2021-09-20 12:12 UTC, tachisis commented on pages/licenses/index.md
> +Это значит, что тексты можно изменять, править и распространять в любом виде, пока вы сохраняете лицензию, ссылку на Доку и упоминание наших авторов, плюс не просите за ваш продукт деньги.
```suggestion
Это значит, что тексты можно изменять и распространять в любом виде, пока вы сохраняете лицензию, ссылку на Доку и упоминание наших авторов, а также не просите за ваш продукт деньги.
```

2021-09-20 12:12 UTC, tachisis commented on pages/licenses/index.md
> +Весь остальной контент в Доке, кроме текста, распространяется по лицензии [CC BY-NC-ND 4.0](https://github.com/doka-guide/content/blob/main/LICENSE-ND.md). Его можно распространять в любом виде, пока
```suggestion
Весь остальной контент в Доке, кроме текста, распространяется по лицензии [CC BY-NC-ND 4.0](https://github.com/doka-guide/content/blob/main/LICENSE-ND.md). Его можно распространять в любом виде, пока вы не изменяете его, сохраняете ссылку на Доку и упоминание наших дизайнеров, а также не просите за ваш продукт деньги.
```

2021-09-20 12:12 UTC, tachisis commented on pages/licenses/index.md
> +Мы можем использовать в Доке материалы из общественного достояния, либо распространяемые по другим лицензиям. Мы обязательно напишем об этом на странице, где они используются в контенте, плюс размест
```suggestion
Мы можем использовать в Доке материалы из общественного достояния, либо распространяемые по другим лицензиям. Мы обязательно напишем об этом на странице, где они используются в контенте, плюс разместим в наших репозиториях полные тексты лицензий, по которым распространяются эти части.
```

2021-09-20 12:12 UTC, tachisis commented on pages/licenses/index.md
> +Если какие-либо из этих лицензий предполагают уникальное право для Доки на использование этих частей кода, мы просим их не переиспользовать в своих проектах. Но мы стараемся сделать весь наш труд нас
```suggestion
Если какие-либо из этих лицензий предполагают уникальное право Доки на использование материала, мы просим не переиспользовать их в своих проектах. Однако мы стараемся сделать Доку настолько свободной, насколько это возможно.
```

2021-09-20 12:12 UTC, tachisis commented on pages/licenses/index.md
> +Правообладателям и по всем остальным вопросам с командой можно связаться по почте [hi@doka.guide](mailto:hi@doka.guide).
```suggestion
По всем вопросам, в том числе по вопросам правообладания, с командой можно связаться по почте [hi@doka.guide](mailto:hi@doka.guide).
```

2021-09-20 12:30 UTC, furtivite commented on pages/licenses/index.md
> +Если какие-либо из этих лицензий предполагают уникальное право для Доки на использование этих частей кода, мы просим их не переиспользовать в своих проектах. Но мы стараемся сделать весь наш труд нас
@tachisis не совсем согласен со словом «материал» тут, потому что эта часть текста должна касаться не только того, что мы разместили в Доке, но и шрифтов. 

```suggestion
Если какие-либо из этих лицензий предполагают уникальное право Доки на использование каких-либо частей кода, мы просим не переиспользовать их в своих проектах. Однако мы стараемся сделать Доку настолько свободной, насколько это возможно.
```

2021-09-20 13:04 UTC, tachisis commented on pages/licenses/index.md
> +Если какие-либо из этих лицензий предполагают уникальное право для Доки на использование этих частей кода, мы просим их не переиспользовать в своих проектах. Но мы стараемся сделать весь наш труд нас
Но ведь шрифты это не код. И это могут быть не только шрифты. Нужно найти какое-то общее слово.

2021-09-20 13:05 UTC, furtivite commented on pages/licenses/index.md
> +Если какие-либо из этих лицензий предполагают уникальное право для Доки на использование этих частей кода, мы просим их не переиспользовать в своих проектах. Но мы стараемся сделать весь наш труд нас
> Но ведь шрифты это не код. И это могут быть не только шрифты. Нужно найти какое-то общее слово.

Согласен, нужно другое общее слово. Но по факту, всё, что есть на сайте можно назвать кодом, и шрифты, и картинки.

2021-09-20 13:07 UTC, tachisis commented on pages/licenses/index.md
> +Если какие-либо из этих лицензий предполагают уникальное право для Доки на использование этих частей кода, мы просим их не переиспользовать в своих проектах. Но мы стараемся сделать весь наш труд нас
Как вам слово «ресурсы»?

2021-09-21 12:44 UTC, tachisis approved these changes

2021-09-21 22:50 UTC, merged