Добавляет доку про <pre>
doka-guide/content pull request #1571
Opened 2021-09-15 08:57 UTC by nionka

2021-09-16 06:04 UTC, solarrust reviewed
Классно получилось, спасибо! 🖤

2021-09-16 06:04 UTC, solarrust commented on html/pre/index.md
> +💡 Для демонстрации внутри тега `<pre>` HTML-кода могут возникнуть проблемы с отображением тегов в угловых скобках – браузер не будет их выводить, т. к. посчитает служебными. Чтобы решить проблему, во
```suggestion
💡 Для демонстрации внутри тега `<pre>` HTML-кода могут возникнуть проблемы с отображением тегов в угловых скобках – браузер не будет их выводить, т. к. посчитает служебными. Чтобы решить проблему, воспользуйтесь символами Юникода: `&lt;` для левой угловой скобки; `&gt` для правой угловой скобки.
```

2021-09-16 17:10 UTC, solarrust commented
@pepelsbey заглядывай поредачить )

2021-09-16 17:56 UTC, pepelsbey requested changes

2021-09-16 17:56 UTC, pepelsbey commented on html/pre/index.md
> +<pre>
```suggestion
<pre aria-label="Изображение кота, собранное из текстовых символов.">
```

2021-09-16 17:56 UTC, pepelsbey commented on html/pre/index.md
> +
```suggestion

```

2021-09-16 17:56 UTC, pepelsbey commented on html/pre/index.md
> +Тег `<pre>` хорошо подходит для отображения стихотворений или демонстрации примера кода.
```suggestion
Тег `<pre>` хорошо подходит для отображения стихотворений или демонстрации примеров кода.
```

Раз уже стихотворений во множественном.

2021-09-16 17:56 UTC, pepelsbey commented on html/pre/index.md
> +💡 По умолчанию для отображения текста в теге `<pre>` браузеры используют шрифты _monospace_.
```suggestion
💡 По умолчанию для отображения текста в теге `<pre>` браузеры используют моноширинные системные шрифты под общим названием _monospace_.
```

2021-09-16 17:56 UTC, pepelsbey commented on html/pre/index.md
> +```
````suggestion
💡 При демонстрации внутри тега `<pre>` HTML-кода могут возникнуть проблемы с отображением тегов в угловых скобках — браузер посчитает их настоящими тегами. Чтобы решить проблему, воспользуйтесь мнемоническими подстановками:

- `&lt;` (less than — знак «меньше») для левой угловой скобки;
- `&gt;` (greater than — знак «больше») для правой угловой скобки.

```html
<pre><code>
  &lt;div&gt;Какой-то текст&lt;/div&gt;
</code></pre>
```
````

2021-09-16 17:56 UTC, pepelsbey commented on html/pre/index.md
> +
```suggestion

💡 Для вывода кода нужно дополнительно обернуть содержимое тега `<pre>` в тег [`<code>`](/html/code), чтобы подчеркнуть, что внутри именно код, а не схематичный котик или стихотворение.

```

2021-09-16 17:56 UTC, pepelsbey commented on html/pre/index.md
> +При отображении на странице браузер схлопывает все рядом стоящие пробелы в один, а переносы игнорирует.
```suggestion
В HTML-коде браузер схлопывает все пробелы в один и игнорирует переносы строк.
```

Чуть развернул предложение, чтобы не прозвучало проще.

2021-09-17 08:29 UTC, pepelsbey approved these changes

2021-09-17 08:32 UTC, solarrust approved these changes

2021-09-17 08:32 UTC, merged