Обновляет демо в Подгрузке контента при прокрутке
doka-guide/content pull request #1572
Opened 2021-09-15 14:45 UTC by skorobaeus

2021-09-15 16:17 UTC, nlopin approved these changes

2021-09-16 08:57 UTC, bespoyasov approved these changes

2021-09-16 08:59 UTC, bespoyasov commented on js/infinite-scroll/demos/switter/index.html
> +        <button type="button" class="button button-like"></button>
Я не уверен, надо ли, но можно добавить `aria-label`, чтобы кнопки подписаны были.

2021-09-16 10:12 UTC, nlopin commented on js/infinite-scroll/demos/switter/index.html
> +        <button type="button" class="button button-like"></button>
хорошо бы

2021-09-16 10:37 UTC, pepelsbey requested changes
Тут @bespoyasov предложил доступно подписать кнопки без очевидного контента. Вот, предлагаю так.

Нужно ещё докрутить JS, чтобы в шаблон подставлялось корректное описание. Чтобы не склонять, можно делать: «лайков: 20».

2021-09-16 10:37 UTC, pepelsbey commented on js/infinite-scroll/demos/switter/index.html
> +          <button type="button" class="button button-resweet">20</button>
```suggestion
          <button type="button" class="button button-like" aria-label="20 лайков">20</button>
          <button type="button" class="button button-resweet" aria-label="20 ресвитов">20</button>
```

2021-09-16 10:37 UTC, pepelsbey commented on js/infinite-scroll/demos/switter/index.html
> +          <button type="button" class="button button-resweet">69</button>
```suggestion
          <button type="button" class="button button-like" aria-label="42 лайка">42</button>
          <button type="button" class="button button-resweet" aria-label="69 ресвитов">69</button>
```

2021-09-16 10:37 UTC, pepelsbey commented on js/infinite-scroll/demos/switter/index.html
> +          <button type="button" class="button button-resweet">20</button>
```suggestion
          <button type="button" class="button button-like" aria-label="4 лайка">4</button>
          <button type="button" class="button button-resweet" aria-label="20 ресвитов">20</button>
```

2021-09-16 10:37 UTC, pepelsbey commented on js/infinite-scroll/demos/switter/index.html
> +        <button type="button" class="button button-like"></button>
```suggestion
        <button type="button" class="button button-like" aria-label="Лайкнуть"></button>
```

2021-09-16 10:37 UTC, pepelsbey commented on js/infinite-scroll/demos/switter/index.html
> +        <button type="button" class="button button-resweet"></button>
```suggestion
        <button type="button" class="button button-resweet" aria-label="Ресвитнуть"></button>
```

2021-09-16 12:46 UTC, skorobaeus commented on js/infinite-scroll/demos/switter/index.html
> -        <h2>Заголовок поста</h1>
Упс x_x

2021-09-16 13:11 UTC, skorobaeus commented
Приняла правки, подкрутила JS.

2021-09-16 14:49 UTC, nlopin approved these changes

2021-09-16 16:13 UTC, pepelsbey approved these changes

2021-09-16 18:55 UTC, merged