Удаляет обложки со старым дизайном
doka-guide/content pull request #1573
Opened 2021-09-15 15:07 UTC by furtivite

@ValyaBro попросила удалить обложки.

- найденные новые *.png обложки, перезаливаются в *.svg

2021-09-15 15:22 UTC, nlopin approved these changes

2021-09-15 15:38 UTC, pepelsbey requested changes
Меня смущает, что удаляются не только картинки, но и альты. Их придётся выковыривать из истории и возвращать. Может удалить только поля с картинками или… вообще не удалять?

2021-09-15 15:42 UTC, furtivite commented
> Меня смущает, что удаляются не только картинки, но и альты. Их придётся выковыривать из истории и возвращать. Может удалить только поля с картинками или… вообще не удалять?

Я специально удалил альты, потому что идея и реализация картинок может измениться. Когда я буду заливать новые картинки, опишу их заново.

2021-09-15 15:46 UTC, pepelsbey approved these changes

2021-09-15 16:12 UTC, nlopin commented
Если захотим альты, то можно будет revert commit сделать и только поменять пути на новые

2021-09-15 16:27 UTC, ValyaBro commented
сейчас картинки выглядят плохо, их надо спрятать с сайта. альты можно сохранить, мы скорее всего не будем менять самую идею иллюстраций. Будем тоже самое перерисовывать в новом стиле.

2021-09-15 16:32 UTC, ValyaBro approved these changes
картинки выглядят не ок, их надо спрятать. Основная идея меняться не будет, старые альты подойдуьт к будущим картинкам

2021-09-16 17:07 UTC, solarrust approved these changes

2021-09-16 18:09 UTC, pepelsbey commented
Если сейчас просто вернуть (оставить) альты, то в платформе выведутся битые картинки. Тут либо нужно поменять проверку в платформе, либо возвращать альты потом. Нужно понять, как будет проще сделать. @furtivite решай, вроде ты хотел этим заниматься.

2021-09-17 06:28 UTC, furtivite commented
> Если сейчас просто вернуть (оставить) альты, то в платформе выведутся битые картинки. Тут либо нужно поменять (сравнительно простую) проверку в платформе (doc.njk), либо возвращать альты потом. Нужно понять, как будет проще сделать. @furtivite решай, вроде ты хотел этим заниматься.

Сейчас стоит удалить альты полностью, я их напишу заново, когда картинки будут готовы. Иначе, как сказал @pepelsbey будет некорректно срабатывать проверка.

2021-09-17 06:30 UTC, merged