Добавляет статью про спреды
doka-guide/content pull request #1584
Opened 2021-09-15 23:31 UTC by nlopin

2021-09-15 23:32 UTC, nlopin commented
@tachisis у меня сложности с написанием слова спред. Не знаю, ок ли писать кириллицей, русского аналога я не нашёл, это жаргонизм. В итоге по статье где-то писал кириллицей, где-то латиницей

Нужен твой совет, как сделать лучше

2021-09-16 09:23 UTC, bespoyasov approved these changes
Вроде, всё достаточно доступно и понятно 🚀

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +Спред синтаксис решает задачу создания нового массива с использованием данных из другого массива. Без этого синтаксиса очень неудобно создавать массив, который содержит элементы другого. Приходится л
```suggestion
Спред синтаксис решает задачу создания нового массива с использованием данных из другого массива. Без него неудобно создавать массив, который содержит элементы другого. Приходится либо использовать методы массива, например, `concat`:
```

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +Спред синтаксис решает задачу создания нового массива с использованием данных из другого массива. Без этого синтаксиса очень неудобно создавать массив, который содержит элементы другого. Приходится л
Кажется, «либо» здесь лишнее, потому что второго варианта дальше нет.

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +### При вызове функции
Добавим коллаут, что в функциях также есть rest arguments и их не стоит путать со спред-оператором? Или это само по себе запутает? 😃

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +const persona = { name: 'Иван', lastName: 'Объектов'}
```suggestion
const person = { name: 'Иван', lastName: 'Объектов'}
```

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +const userData = Object.assign({ username: 'killer3000' }, persona)
```suggestion
const userData = Object.assign({ username: 'killer3000' }, person)
```

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +const persona = { name: 'Иван', lastName: 'Объектов'}
```suggestion
const person = { name: 'Иван', lastName: 'Объектов'}
```

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +const userData = { username: 'killer3000' , ...persona }
```suggestion
const userData = { username: 'killer3000' , ...person }
```

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +const persona = { name: 'Иван', lastName: 'Объектов'}
```suggestion
const person = { name: 'Иван', lastName: 'Объектов'}
```

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +const userData = { name: 'Николай' , ...persona }
```suggestion
const userData = { name: 'Николай' , ...person }
```

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +const persona = { name: 'Иван', lastName: 'Объектов'}
```suggestion
const person = { name: 'Иван', lastName: 'Объектов'}
```

2021-09-16 09:23 UTC, bespoyasov commented on js/spread/index.md
> +const userData = { ...persona, name: 'Николай' }
```suggestion
const userData = { ...person, name: 'Николай' }
```

2021-09-16 10:08 UTC, nlopin commented on js/spread/index.md
> +### При вызове функции
я это хочу дописать или отдельной статьей или добавить в статью про функции. Потом добавить параграф сюда, что их не стоит путать

2021-09-16 11:40 UTC, tachisis reviewed
Заодно отредактировала. @nlopin я думаю, что «спред» нормально. Такой термин уже есть в русском языке в финансовой области, можно ориенитроваться на его написание.

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +description: "Упрощает создание объектов и массив на основе других объектов и массивов"
```suggestion
description: "Упрощает создание объектов и массивов на основе других объектов и массивов"
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +  - nlopin
```suggestion
  - nlopin
editors:
  - tachisis
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +  - спрэд
```suggestion
  - спред
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +Спред (spread) синтаксис `...` позволяет передавать итерируемые коллекции (например, массивы или строки) как список аргументов функции или добавлять содержащиеся в них элементы в новый массив.
```suggestion
Спред-синтаксис (spread) `...` позволяет передавать итерируемые коллекции (например, массивы или строки) как список аргументов функции или добавлять содержащиеся в них элементы в новый массив.
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +Спред синтаксис — одна из вещей в JavaScript, которую легче всего изучать на примерах. Есть три контекста, где применяется синтаксис.
```suggestion
Спред-синтаксис легче всего изучать на примерах. Есть три контекста, в которых он применяется.
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +Часто встречается ситуация, когда мы хотим использовать данные из итерируемой коллекции в качестве аргументов функции. Чаще всего такая коллекция — массив. Если функция не умеет принимать массив аргу
```suggestion
Часто встречается ситуация, когда мы хотим использовать данные из итерируемой коллекции в качестве аргументов функции. Чаще всего такая коллекция — массив. Если функция не умеет принимать массив аргументом, то придётся доставать элементы вручную:
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +Если элементов становится больше, то руками доставать значения становится неудобно. Чтобы решить эту проблему в старых версиях языка использовали метод `apply`. Этот метод принимает первым аргументом
```suggestion
Если элементов становится больше, доставать значения вручную становится неудобно. Чтобы решить эту проблему, в старых версиях языка использовали метод `apply`. Этот метод принимает первым аргументом значение `this`, а вторым — список аргументов для вызова функции:
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +Такой синтаксис сложно читается, его нельзя использовать при создании объектов с помощью конструктора `new`. Его упростили до spread синтаксиса. В этом случае как бы выкладываются из списка в нужном
```suggestion
Такой синтаксис сложно читается, его нельзя использовать при создании объектов с помощью конструктора `new`. Его упростили до спред-синтаксиса. В этом случае элементы как бы выкладываются из списка в нужном порядке:
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +Спред синтаксис решает задачу создания нового массива с использованием данных из другого массива. Без него неудобно создавать массив, который содержит элементы другого. Приходится использовать методы
```suggestion
Спред-синтаксис решает задачу создания нового массива с использованием данных из другого массива. Без него неудобно создавать массив, который содержит элементы другого. Приходится использовать методы массива, например, `concat`:
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +При использовании спред синтаксиса элементы массива копируются только на один уровень вложенности. Если массив содержит объекты, то это будут те же самые объекты, что и в исходном массиве. Для глубок
```suggestion
При использовании спред-синтаксиса элементы массива копируются только на один уровень вложенности. Если массив содержит объекты, то это будут те же самые объекты, что и в исходном массиве. Для глубокого копирования пользуйтесь библиотеками, например, [lodash](https://lodash.com/docs/4.17.15#cloneDeep)
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +По аналогии с массивами, спред синтаксис решает проблему копирования свойств в новый объект. В версии языка без спреда для копирования использовался метод `Object.assign`, который принимал два объект
```suggestion
По аналогии с массивами, спред-синтаксис решает проблему копирования свойств в новый объект. В версии языка без спреда для копирования использовался метод `Object.assign`, который принимал два объекта — куда копировать свойства и откуда:
```

2021-09-16 11:40 UTC, tachisis commented on js/spread/index.md
> +При использовании спред синтаксиса свойства объекта копируются только на один уровень вложенности. Для глубокого копирования пользуйтесь библиотеками, например, [lodash](https://lodash.com/docs/4.17.
```suggestion
При использовании спред-синтаксиса свойства объекта копируются только на один уровень вложенности. Для глубокого копирования пользуйтесь библиотеками, например, [lodash](https://lodash.com/docs/4.17.15#cloneDeep)
```

2021-09-16 12:13 UTC, nlopin commented on js/spread/index.md
> +  - спрэд
тут я хотел как раз альтернативное написание указать, потому что «спред» уже есть в тексте статьи и поисковик его найдет и так

2021-09-16 23:03 UTC, pepelsbey requested changes

2021-09-16 23:03 UTC, pepelsbey commented on js/spread/practice/nlopin.md
> +🛠 Спред на объектах используют во [фреймворке React](reactjs.org/). Программист может передать в функцию объект с произвольными свойствами, но мы хотим запретить устанавливать некоторые из них. В это
```suggestion
🛠 Спред на объектах используют в [библиотеке React](https://reactjs.org/). Программист может передать в функцию объект с произвольными свойствами, но мы хотим запретить устанавливать некоторые из них. В этом случае создаётся новый объект, в который сначала копируются присланные значения, а потом значения «запрещённых» свойств. В этом случае даже если запрещённое свойство было передано, оно будет перезаписано:
```

2021-09-17 15:16 UTC, tachisis approved these changes

2021-09-17 15:35 UTC, pepelsbey approved these changes

2021-09-17 15:43 UTC, merged