Добавляет практики в `<picture>` и в `<source>`
doka-guide/content pull request #1589
Opened 2021-09-16 12:40 UTC by furtivite

Кажется, может быть полезным.

2021-09-16 16:19 UTC, pepelsbey requested changes
Я бы не стал дублировать контент для всех статей. Лучше выбрать ту, к которой хочешь добавить совет и остановиться на этом. Что скажешь, @solarrust?

2021-09-16 16:19 UTC, pepelsbey commented on html/picture/practice/furtivite.md
> +    <img src="image.png">
```suggestion
    <!-- Картинка для тёмной темы -->
    <source srcset="image-dark.png" media="(prefers-color-scheme: dark)">
    <!-- Картинка по-умолчанию для светлой темы -->
    <img src="image-light.png" alt="">
```

Лучше не писать лишний код, а выбрать фолбэк и переписать его либо в светлую, либо в тёмную тему.

2021-09-16 17:00 UTC, solarrust reviewed
Поддерживаю предыдущего оратора. Лучше выбрать одну статью и не дублировать совет. Мне кажется, что лучше оставить его в статье про `<picture>`.

2021-09-17 08:32 UTC, pepelsbey approved these changes

2021-09-17 08:33 UTC, solarrust approved these changes

2021-09-17 08:33 UTC, merged