Добавляет статью «Паттерны Gateway и Backend-for-Frontend»
doka-guide/content pull request #1593
Opened 2021-09-16 20:28 UTC by igsekor

Статья определяет основные архитектурные решения для паттернов Gateway и Backend-for-Frontend.

2021-09-16 23:13 UTC, pepelsbey approved these changes

2021-09-17 13:18 UTC, tachisis approved these changes
Апрув на словарь

2021-09-17 15:35 UTC, nlopin commented
Мне кажется мы сейчас немного не про то рассказываем. Мы быстро говорим про концепцию, а потом рассказываем про выбор архитектуры.

Думаю стоит начать с проблемы, сейчас она не описана. А затем рассказать, как паттерны проблему решают. Высокоуровнево повестование в разделе «как понять», как мне кажется, будет лучше таким:

* проблема — у нас есть куча микросервисов и фронтенд должен знать про каждый, про его контракты, да ещё и вызывать сразу несколько, чтобы собрать разрозненные данные
* шаг 1 — gateway сервис, который становится единой точкой контакта для фронта, но он только проксирует запросы в нужные микросервисы
* шаг 2 — BFF сервис, который умеет агрегировать данные из нескольких мест и даже содержать какую-то минимальную логику

архитектуру я бы поджал и сослался на уже существующие статьи про [трёхслойную/чистую архитектуру](https://doka.guide/js/clean-architecture/) и [MVC](https://doka.guide/js/architecture-mvc/)

2021-09-17 15:36 UTC, nlopin requested changes
Мне кажется мы сейчас немного не про то рассказываем. Мы быстро говорим про концепцию, а потом рассказываем про выбор архитектуры.

Думаю стоит начать с проблемы, сейчас она не описана. А затем рассказать, как паттерны проблему решают. Высокоуровнево повестование в разделе «как понять», как мне кажется, будет лучше таким:

* проблема — у нас есть куча микросервисов и фронтенд должен знать про каждый, про его контракты, да ещё и вызывать сразу несколько, чтобы собрать разрозненные данные
* шаг 1 — gateway сервис, который становится единой точкой контакта для фронта, но он только проксирует запросы в нужные микросервисы
* шаг 2 — BFF сервис, который умеет агрегировать данные из нескольких мест и даже содержать какую-то минимальную логику

архитектуру я бы поджал и сослался на уже существующие статьи про [трёхслойную/чистую архитектуру](https://doka.guide/js/clean-architecture/) и [MVC](https://doka.guide/js/architecture-mvc/)

2021-09-17 20:54 UTC, igsekor commented
> архитектуру я бы поджал и сослался на уже существующие статьи про [трёхслойную/чистую архитектуру](https://doka.guide/js/clean-architecture/) и [MVC](https://doka.guide/js/architecture-mvc/)

В указанных статьях описана архитектура фронтенд приложения или приложения с прицелом на пользовательский интерфейс. Я посмотрел, хотел сослаться на них, но там нет нужной информации. Поджать можно, но я итак выжал только самое нужное. Готов всё поправить, но не достаёт понимания твоего видения в части описания архитектуры. В начале задачу поставил (действительно странно выглядело без этого).

2021-09-19 06:10 UTC, nlopin commented
При чтении имел какое-то смутное чувство, что что-то со статьей не то. Думаю схемы точно привнесут больше понятности, мы же про архитектуру говрим. Как ты считаешь?

Имею ввиду схемы:

- один фронтенд напрямую шлёт запросы многим микросервисам
- фронтенд шлет запросы через gateway
- фронтенд шлет запросы через DFF

2021-09-19 22:03 UTC, nlopin approved these changes

2021-09-20 08:30 UTC, bespoyasov reviewed
Всё нравится :–)

Может, нам в конце сделать заключение, обобщив всё? Есть ощущение, будто статья внезапно обрывается.

2021-09-20 08:30 UTC, bespoyasov commented on tools/gateway-bff/index.md
> +description: "Gateway — единое окно для разных API. Backend-for-Frontend использует Gateway для обработки запросов и подготовки ответов, предназначенных для фронтенда"
Описание 👍

2021-09-20 08:30 UTC, bespoyasov commented on tools/gateway-bff/index.md
> +Современное веб-приложение состоит их фронтенда, который непосредственно видит пользователь, и бэкенда, который пользователь не видит. Бэкенд может быть устроен по-разному, всё зависит от задачи. Бэк
```suggestion
Современное веб-приложение состоит из фронтенда, который непосредственно видит пользователь, и бэкенда, который пользователь не видит. Бэкенд может быть устроен по-разному, всё зависит от задачи. Бэкенд крупных веб-приложений обычно довольно сложно устроен. 

Как правило, бэкенд — это совокупность разных программ (микросервисы) или одна большая программа (монолит). В современном вебе всё чаще используется микросервисный подход, о котором вы можете прочитать в статье «[Микросервисы](/tools/microservices/)». Проблема такого сложного бэкенда состоит в том, что каждый микросервис предоставляет уникальный [программный интерфейс](/js/api). Фронтенду приходится работать с каждым микросервисом отдельно и помнить API каждого. Это неудобно, создаёт жёсткую связь между фронтендом и бэкендом, требует много знаний о внутреннем устройстве бэкенда. Решение этой проблемы состоит в том, чтобы сделать один унифицированный интерфейс, который в свою очередь будет обращаться ко всем микросервисам.
```

2021-09-20 08:30 UTC, bespoyasov commented on tools/gateway-bff/index.md
> +Одним из первых таких решений был Gateway, который является, как правило, прокси-сервером и предоставляет единое окно для доступа к данным по определённому программному интерфейсу (Application Progra
```suggestion
Одним из первых таких решений был Gateway, который является, как правило, прокси-сервером и предоставляет единое окно для доступа к данным по определённому программному интерфейсу (Application Programmable Interface — API), пересылая данные от фронтенда к нужному микросервису и обратно. Внешний вид приложения пользователя меняется, бизнес-логика меняется, клиентское приложение меняется, может меняться и контракт, но на остальные API это никак не влияет. Gateway пересылает запросы со стороны клиентов на другие API, учитывая разницу в контрактах, и этим позволяет снизить зацепление бэкенда и фронтенда в веб-приложении. Как правило, на стороне Gateway частые запросы могут кэшироваться, может быть реализована простая бизнес-логика, которая обеспечивает контроль над набором пересылаемых данных между клиентом и внешним API.
```

2021-09-20 08:32 UTC, bespoyasov commented
Как вариант, если успеем, можно проиллюстрировать проблему и её решение с помощью небольшого проекта внутри. Как демка, только больше про код, а не про UI.

Можно показать, как BFF решает проблему зацепления API, чтобы было понятнее, зачем нам это может понадобиться.

Мне кажется, это решит проблему, о которой писал @nlopin выше, но я не уверен.

2021-09-20 09:14 UTC, nlopin commented
@bespoyasov у меня подозрение, что без объяснения этот код будут мало читать. А объяснять текстом проект — сложная задача. Круто объяснять скринкастом, как Андрей Мелихов в девшахте объясняет

2021-09-20 09:14 UTC, nlopin commented on tools/gateway-bff/index.md
> +Одним из первых таких решений был Gateway, который является, как правило, прокси-сервером и предоставляет единое окно для доступа к данным по определённому программному интерфейсу (Application Progra
ох уж эти термины 😂

2021-09-20 09:15 UTC, bespoyasov commented
Тогда отбой 😃

2021-09-20 13:57 UTC, igsekor commented
> Тогда отбой 😃

Кажется, нужно делать либо скринкаст, либо отдельную статью. Там много материала получится. Я уже попробовал упихнуть всё сюда, но нет( Эхх...

2021-09-20 14:57 UTC, igsekor commented
Сделал два ишью: #1627 и #1628

2021-09-20 14:58 UTC, bespoyasov approved these changes

2021-09-20 14:59 UTC, merged