Добавляет доку про overflow-wrap
doka-guide/content pull request #1595
Opened 2021-09-16 21:51 UTC by solarrust

Close #598

2021-09-16 22:55 UTC, pepelsbey requested changes
Добавить бы `font-family`, раз уж шрифт подключается и не цитировать бы Can I Use, раз там сомнительные данные. В остальном норм :)

2021-09-16 22:55 UTC, pepelsbey commented on css/overflow-wrap/demos/default/index.html
> +    p {
```suggestion
    body {
      font-family: Roboto, sans-serif;
    }

    p {
```

2021-09-16 22:55 UTC, pepelsbey commented on css/overflow-wrap/demos/values/index.html
> +    p {
```suggestion
    body {
      font-family: Roboto, sans-serif;
    }

    p {
```

2021-09-16 22:55 UTC, pepelsbey commented on css/overflow-wrap/index.md
> +
Эта часть в какой-то момент устареет (Safari), но уже сейчас сомнительной релевантности (IE особенно, но Opera 64 на Chromium должна поддерживать, просто данные MDN некорректные, скорее всего). Так что я бы оставил просто заметку, мол, проверяйте совместимость и дал ссылку на Can I Use.

2021-09-16 23:08 UTC, pepelsbey requested changes
Ещё было бы клёво сделать более компактный пример в маркдауне. Так он не будет выпрямляться в строчку и ручные переносы помогут лучше обратить внимание на то, что бы хочешь показать. И точки в конце :)

2021-09-16 23:08 UTC, pepelsbey commented on css/overflow-wrap/index.md
> +<p>Работал у нас на заводе как-то отменный профессионал — автомотовелофототелерадиомонтёр</p>
```suggestion
<p>
  Работал у нас на заводе
  как-то отменный профессионал —
  автомотовелофототелерадиомонтёр.
</p>
```

2021-09-16 23:08 UTC, pepelsbey commented on css/overflow-wrap/demos/values/index.html
> +  <p class="anywhere">Работал у нас на заводе как-то отменный профессионал — <!-- yaspeller ignore:start -->автомотовелофототелерадиомонтёр<!-- yaspeller ignore:end --></p>
```suggestion
  <p class="normal">Работал у нас на заводе как-то отменный профессионал — <!-- yaspeller ignore:start -->автомотовелофототелерадиомонтёр.<!-- yaspeller ignore:end --></p>
  <p class="break-word">Работал у нас на заводе как-то отменный профессионал — <!-- yaspeller ignore:start -->автомотовелофототелерадиомонтёр.<!-- yaspeller ignore:end --></p>
  <p class="anywhere">Работал у нас на заводе как-то отменный профессионал — <!-- yaspeller ignore:start -->автомотовелофототелерадиомонтёр.<!-- yaspeller ignore:end --></p>
```

2021-09-16 23:08 UTC, pepelsbey commented on css/overflow-wrap/demos/default/index.html
> +  <p>Работал у нас на заводе как-то отменный профессионал — <!-- yaspeller ignore:start -->автомотовелофототелерадиомонтёр<!-- yaspeller ignore:end --></p>
```suggestion
  <p>Работал у нас на заводе как-то отменный профессионал — <!-- yaspeller ignore:start -->автомотовелофототелерадиомонтёр.<!-- yaspeller ignore:end --></p>
```

2021-09-17 13:31 UTC, tachisis commented on css/overflow-wrap/index.md
> +  - solarrust
```suggestion
  - solarrust
editors:
  - tachisis
```

2021-09-17 13:31 UTC, tachisis commented on css/overflow-wrap/index.md
> +Свойство `overflow-wrap` управляет переносом слов, которые не помещаются по длине в родительский элемент. Раньше в спецификации не было подобного свойства и браузеры на своё усмотрение реализовали [`
```suggestion
Свойство `overflow-wrap` управляет переносом слов, которые не помещаются по длине в родительский элемент. Раньше в спецификации не было подобного свойства, и браузеры на своё усмотрение реализовали [`word-wrap`](/css/word-wrap), однако оно не было описано в спецификации.
```

2021-09-17 13:31 UTC, tachisis commented on css/overflow-wrap/index.md
> +Свойство `overflow-wrap` управляет переносом слов, которые не помещаются по длине в родительский элемент. Раньше в спецификации не было подобного свойства и браузеры на своё усмотрение реализовали [`
Вообще кажется, что лучше переформулировать, не очень ясен смысл — раньше был `word-wrap`, у которого не было спецификации? И поэтому браузеры реализовали его на свое усмотрение? А теперь вместо него появилось свойство `overflow-wrap`? Если я правильно угадала логику, то лучше бы так последовательность и развернуть.

2021-09-17 13:31 UTC, tachisis commented on css/overflow-wrap/index.md
> +- `normal` — длинные слова или строки с неразрывным пробелом не переносятся даже если выходят за границы родителя (значение по умолчанию).
```suggestion
- `normal` — длинные слова или строки с неразрывным пробелом не переносятся, даже если выходят за границы родителя (значение по умолчанию).
```

2021-09-17 13:31 UTC, tachisis commented on css/overflow-wrap/index.md
> +- `break-word` — слово разбивается в любом месте если не помещается в размеры, заданные родительскому элементу. Правила мягкого переноса не учитываются.
```suggestion
- `break-word` — слово разбивается в любом месте, если не помещается в размеры, заданные родительскому элементу. Правила мягкого переноса не учитываются.
```

2021-09-17 13:31 UTC, tachisis commented on css/overflow-wrap/index.md
> +- `anywhere` — как и при значении `break-word` слово разбивается в любом месте, но во внимание берутся правила мягкого переноса. Это сильно заметно если родителю в качестве значения ширины задано `mi
```suggestion
- `anywhere` — как и при значении `break-word`, слово разбивается в любом месте, но во внимание берутся правила мягкого переноса. Это сильно заметно, если родителю в качестве значения ширины задано `min-content`. Браузер расставляет мягкие переносы на своё смотрение.
```

2021-09-17 13:31 UTC, tachisis commented on css/overflow-wrap/index.md
> +В разных языках существуют разные правила, по которым можно переносить слова на новую строку. Например, в русском языке можно переносить слова по слогам. Места, в которых по правилам языка может быть
```suggestion
В разных языках существуют разные правила, по которым можно переносить части слова на новую строку. Например, в русском языке можно переносить слова по слогам. Места, в которых по правилам языка может быть разорвано слово, называются _мягкими переносами_.
```

2021-09-17 13:31 UTC, tachisis commented on css/overflow-wrap/index.md
> +В разных языках существуют разные правила, по которым можно переносить слова на новую строку. Например, в русском языке можно переносить слова по слогам. Места, в которых по правилам языка может быть
А это точно правильная дефиниция? Насколько я вижу, существует «символ мягкого переноса» в компьютерной типографике, но не «место». Возможно, тут будет вернее сказать, «Мягкие переносы — это переносы, соответствующие правилам языка, на котором написан текст»?

2021-09-17 14:00 UTC, pepelsbey approved these changes

2021-09-17 15:31 UTC, solarrust commented on css/overflow-wrap/index.md
> +Свойство `overflow-wrap` управляет переносом слов, которые не помещаются по длине в родительский элемент. Раньше в спецификации не было подобного свойства и браузеры на своё усмотрение реализовали [`
Логика такая, да. Но не хочется в первом предложении упоминать другое свойство. Всё же статья не о нём.

2021-09-17 15:33 UTC, solarrust commented on css/overflow-wrap/index.md
> +В разных языках существуют разные правила, по которым можно переносить слова на новую строку. Например, в русском языке можно переносить слова по слогам. Места, в которых по правилам языка может быть
Мне пришлось погуглить определение слова «дефиниция» 🥲  Да, термин сбивает с толку.  Я вчера час вчитывалась в спецификацию чтобы понять, что это не символы мягкого переноса типа `&shy;`, а именно что правила переноса в языке =)

2021-09-20 09:52 UTC, merged