Добавляет доку про pointer-events
doka-guide/content pull request #1602
Opened 2021-09-17 17:14 UTC by solarrust

@pepelsbey есть сомнения нужно ли описать 8 возможных значений, применимых только к SVG.

2021-09-17 22:32 UTC, pepelsbey commented on css/pointer-events/index.md
> +У HTML-элементов предусмотрены разные доступные события. Например, у тега [`<div>`](/html/div) по умолчанию нет события наведения курсора или фокуса. А у [`<button>`](/html/button) если события навед
```suggestion
```

Это всё-таки не так. У HTML-элементов нет событий, пока их не назначить из JS. Другое дело, что с ними можно как-то взаимодействовать. И свойство `pointer-events` как раз запрещает это взаимодействие с помощью указателя (pointer), но с клавиатуры вполне можно сфоркусироваться на ссылке, у которой такое назначено. Или, скажем, `div:active { color: red }` покрасит див при клике, но если туда добавить `pointer-events: none`, то не покрасит.

В общем, я могу дописать пару абзацев, если хочешь, чтобы объяснить принцип.

2021-09-17 22:39 UTC, pepelsbey requested changes
Предлагаю заменить «событие» на «указатель».

2021-09-17 22:39 UTC, pepelsbey commented on css/pointer-events/index.md
> +Свойство `pointer-events` управляет тем, как элемент будет реагировать на различные события: наведение курсора мыши и клик, тап на сенсорном экране, [события из JavaScript](/js/events).
```suggestion
Свойство `pointer-events` управляет тем, как элемент будет реагировать на указатель (pointer): наведение или клик курсора мыши, тап на сенсорном экране, [соответствующие события из JavaScript](/js/events).
```

2021-09-17 22:39 UTC, pepelsbey commented on css/pointer-events/index.md
> +Элемент не будет реагировать на события:
```suggestion
Элемент не будет реагировать на указатель:
```

2021-09-17 22:39 UTC, pepelsbey commented on css/pointer-events/index.md
> +- `inherit` — элемент наследует реакцию на события от родителя.
```suggestion
- `none` — запрещает элементу реагировать на указатель.
- `auto` — элемент реагирует на указатель (значение по умолчанию).
```

Я бы предложил не указывать для свойств значения inherit, revert и подобные, которые не специфичны этому свойству, а просто ключевые слова для всего CSS.

2021-09-17 22:39 UTC, pepelsbey commented on css/pointer-events/index.md
> +В примере ниже есть два абзаца текста с наложенным поверх них псевдоэлементом с градиентом. В первом случае если попытаться выделить текст с нижней строки, то ничего не получится. Псевдоэлемент не пр
```suggestion
В примере ниже есть два абзаца текста с наложенным поверх них псевдоэлементом с градиентом. В первом случае если попытаться выделить текст с нижней строки, то ничего не получится. Псевдоэлемент не пропустит указатель ниже, перехватит его. Второму абзацу прописано `pointer-events: none;` и поэтому псевдоэлемент становится _невидимым_ для указателя, текст можно выделить и, например, скопировать.
```

2021-09-17 22:39 UTC, pepelsbey commented on css/pointer-events/index.md
> +<iframe title="События на элементе отключены" src="demos/none/" height="150"></iframe>
```suggestion
<iframe title="Указатель на элементе отключен" src="demos/none/" height="150"></iframe>
```

2021-09-17 22:39 UTC, pepelsbey commented on css/pointer-events/demos/none/index.html
> +  <title>События на элементе отключены — pointer-events — Дока</title>
```suggestion
  <title>Указатель на элементе отключен — pointer-events — Дока</title>
```

2021-09-17 22:41 UTC, solarrust commented on css/pointer-events/index.md
> +У HTML-элементов предусмотрены разные доступные события. Например, у тега [`<div>`](/html/div) по умолчанию нет события наведения курсора или фокуса. А у [`<button>`](/html/button) если события навед
You are welcome 👍

2021-09-20 09:52 UTC, solarrust commented
@pepelsbey загляни, пожалуйста

2021-09-20 09:59 UTC, pepelsbey approved these changes

2021-09-20 10:00 UTC, pepelsbey commented
@solarrust я [объяснил про указатель и клавиатуру](https://github.com/doka-guide/content/pull/1602/commits/086f5178ed6739e743eb8a79d8b6dc6991fe74e1) вокруг примера. Если норм — давай мёржить :)

2021-09-20 12:14 UTC, tachisis approved these changes
Апрув на словарь, редактировать буду потом

2021-09-20 12:56 UTC, merged