Добавляет доку про border-style
doka-guide/content pull request #1603
Opened 2021-09-17 18:10 UTC by solarrust

2021-09-17 22:47 UTC, pepelsbey requested changes

2021-09-17 22:47 UTC, pepelsbey commented on css/border-style/index.md
> +- `double` — рамка состоит из двух сплошных линий с небольшим нерегулируемым отступом между ними. Если рамка тонкая, например, 1 пиксель, то внешне это значение почти не будет отличаться от `solid`.
Предлагаю утащить совет в конец доки к другому совету, а тут оставить краткое описание значения.

2021-09-17 22:47 UTC, pepelsbey commented on css/border-style/index.md
> +💡 Достаточно определить стиль рамки для того, чтобы она появилась вокруг элемента. Остальные значения будут установлены в значения по умолчанию: ширина рамки 3 пикселям, а цвет чёрным.
```suggestion
💡 Достаточно определить стиль рамки для того, чтобы она появилась вокруг элемента. Остальные значения будут установлены в значения по умолчанию: ширина рамки 3 пикселя, а цвет такой же, как унаследованный цвет текста (по умолчанию — чёрный).
```

2021-09-17 22:47 UTC, pepelsbey commented on css/border-style/index.md
> +- `solid` — сплошная рамка. Этот стиль используется чаще всего.
```suggestion
- `none` — отключает рамку (значение по умолчанию).
- `solid` — сплошная рамка. Этот стиль используется чаще всего.
- `dotted` — рамка состоит из точек с пробелами между ними.
- `dashed` — рамка состоит из коротких чёрточек с пробелами между ними.
```

2021-09-20 09:53 UTC, solarrust commented on css/border-style/index.md
> +- `double` — рамка состоит из двух сплошных линий с небольшим нерегулируемым отступом между ними. Если рамка тонкая, например, 1 пиксель, то внешне это значение почти не будет отличаться от `solid`.
Вынесла в конец статьи

2021-09-20 10:10 UTC, pepelsbey approved these changes

2021-09-20 10:10 UTC, merged