Добавляет статью «Протоколы TCP и UDP»
doka-guide/content pull request #1607
Opened 2021-09-18 20:46 UTC by igsekor

Описал основные вещи по протоколу.

2021-09-19 05:50 UTC, nlopin commented on tools/tcp-udp-protocols/index.md
> +description: "Протоколы транспортного уровня обеспечивают для веб-приложения передачу данных между сервером и браузером пользователя"
```suggestion
description: "Протоколы транспортного уровня обеспечивают передачу данных между сервером и браузером пользователя"
```

2021-09-19 05:53 UTC, nlopin commented on tools/tcp-udp-protocols/index.md
> +Протоколы транспортного уровня используются для передачи данных по сети. Данные передаются в виде пакетов установленного размера. Протокол TCP (Transmission Control Protocol) формирует поток передачи
Про потерянные данные нужно уточнить
```suggestion
Протоколы транспортного уровня используются для передачи данных по сети. Данные передаются в виде пакетов установленного размера. Протокол TCP (Transmission Control Protocol) формирует поток передачи данных, предварительно установив соединение. Если часть данных потеряно, то протокол автоматически повторно запрашивает утерянные данные и передаёт их от отправителя к получателю. TCP также устраняет дубликаты и информирует отправителя о результате передачи. Протокол UDP (User Datagram Protocol) не предоставляет таких гарантий, не требует установления соединения —  просто пересылает пакеты с данными на адрес сетевого узла. Рассмотрим оба протокола с точки зрения взаимодействия клиента (сетевого узла, на котором работает браузер) и сервера.
```

2021-09-19 05:55 UTC, nlopin commented on tools/tcp-udp-protocols/index.md
> +При разработке веб-приложения важно учитывать множество факторов, в том числе и как оно будет взаимодействовать с браузером пользователя. Передача данных между сервером и браузером опирается на прото
Давай еще чуть смысла нальём. Что самое важное нужно знать о TCP и UDP? 

Я бы точно ввернул что-то такое «TCP гарантирует доставку сообщения ценой скорости, UCP наоборот — быстрый, но гарантий доставки нет»

2021-09-19 05:56 UTC, nlopin commented on tools/tcp-udp-protocols/index.md
> +После рукопожатия отправитель посылает поток данных получателю. Отправитель может посылать данные сразу после посылки ACK пакета, получатель же должен подождать прихода этого пакета перед приёмом пот
```suggestion
После рукопожатия отправитель посылает поток данных получателю. Отправитель может посылать данные сразу после посылки ACK пакета, получатель же должен подождать прихода этого пакета перед приёмом потока данных. Такой механизм рукопожатия и отправки данных обязателен для каждого соединения при общении по протоколу TCP. _Пакет TCP_ — это блок данных, который передаётся в потоке. Порядок пакетов строго определён и не может быть нарушен.
```

2021-09-19 05:59 UTC, nlopin commented on tools/tcp-udp-protocols/index.md
> +Существует решение этой проблемы — технология [TCP Fast Open](https://datatracker.ietf.org/doc/html/rfc7413). Это технология позволяет передавать данные уже на этапе передачи пакета SYN. Конечно, ест
> В среднем загрузку сайта можно ускорить на 10-15%.

Откуда такой вывод? Хочется развернуть. Если она по умолчанию используется, то кажется выигрыш у всех приложений, а не только у тех, кто это знает. Или это про 14,6 килобайт?

2021-09-19 06:01 UTC, nlopin commented on tools/tcp-udp-protocols/index.md
> +Проблему нехватки IP-адресов решают путём отделения внутренних сетей от публичных IP-адресов сети интернет с помощью Network address translation (NAT). NAT — это специальный протокол, который при пер
из предыдущего повествования этот параграф никак не вытекает. Он точно здесь должен быть? Нигде выше про проблему нехватки адресов не написано

2021-09-19 06:05 UTC, nlopin requested changes
все круто 👍

2021-09-19 11:25 UTC, igsekor commented on tools/tcp-udp-protocols/index.md
> +Проблему нехватки IP-адресов решают путём отделения внутренних сетей от публичных IP-адресов сети интернет с помощью Network address translation (NAT). NAT — это специальный протокол, который при пер
Это обоснование того, что написано дальше. Переформулирую

2021-09-19 11:27 UTC, igsekor commented on tools/tcp-udp-protocols/index.md
> +Существует решение этой проблемы — технология [TCP Fast Open](https://datatracker.ietf.org/doc/html/rfc7413). Это технология позволяет передавать данные уже на этапе передачи пакета SYN. Конечно, ест
Разверну

2021-09-19 11:27 UTC, igsekor commented on tools/tcp-udp-protocols/index.md
> +При разработке веб-приложения важно учитывать множество факторов, в том числе и как оно будет взаимодействовать с браузером пользователя. Передача данных между сервером и браузером опирается на прото
Ок

2021-09-19 22:14 UTC, nlopin approved these changes

2021-09-20 08:46 UTC, bespoyasov approved these changes

2021-09-20 08:46 UTC, bespoyasov commented on tools/tcp-udp-protocols/index.md
> +1. Отправитель генерирует случайное число _x_ и передаёт его получателю в пакете SYN. В этом же пакете могут указываться какие-то специальные флаги для настройки соединения.
Думаю, стоит объяснить, что такое SYN и ACK, или расшифровать 🙃

2021-09-20 08:46 UTC, bespoyasov commented on tools/tcp-udp-protocols/index.md
> +Рукопожатие может существенно замедлить передачу данных по протоколу TCP, если, например, данные передаются небольшими порциями. Чем больше нужно соединений, тем медленнее общая передача. Загрузка ве
Тут можно наверное рассказать про `rel="preconnect"` — я же правильно понимаю, что он позволяет «прогреть» соединение заранее?

2021-09-20 08:46 UTC, bespoyasov commented on tools/tcp-udp-protocols/index.md
> +В заголовке датаграммы протокола UDP содержится только адрес сетевого узла, которому нужно передать данные. Часто встречаются связанные с этим коллизии, например, из-за наличия узлов с одинаковыми ад
Вот тут, я думаю, было бы круто нарисовать, как работает NAT, и как может возникнуть коллизия. Но это необязательно, текст в принципе достаточно понятен :–)

2021-09-20 08:46 UTC, bespoyasov commented on tools/tcp-udp-protocols/index.md
> +### Сравнение TCP и UDP
Отлично 🔥

2021-09-20 08:46 UTC, bespoyasov commented on tools/tcp-udp-protocols/practice/igsekor.md
> +**Чек-лист оптимизации скорости веб-приложения передачи данных по протоколу TCP**:
Шик! 🚀

2021-09-20 12:13 UTC, tachisis approved these changes
Апрув на словарь

2021-09-20 14:10 UTC, igsekor commented on tools/tcp-udp-protocols/index.md
> +В заголовке датаграммы протокола UDP содержится только адрес сетевого узла, которому нужно передать данные. Часто встречаются связанные с этим коллизии, например, из-за наличия узлов с одинаковыми ад
Может лучше отдельную статью на тему NAT?

2021-09-20 14:46 UTC, nlopin commented on tools/tcp-udp-protocols/index.md
> +В заголовке датаграммы протокола UDP содержится только адрес сетевого узла, которому нужно передать данные. Часто встречаются связанные с этим коллизии, например, из-за наличия узлов с одинаковыми ад
вынесем в отдельную статью 👍

2021-09-20 14:46 UTC, merged

2021-09-20 14:58 UTC, igsekor commented
Добавил ишью #1626