Исправляет чеклист в статье «Что может читать сайт»
doka-guide/content pull request #1649
Opened 2021-09-20 21:11 UTC by nlopin

Получается как-то так:
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/1469636/134076238-b825e7ee-9386-43c7-86bf-38c115693274.png">

Closes #1648

2021-09-20 22:22 UTC, pepelsbey requested changes
Я понимаю, что это припарка мёртвому, но так:

1. У чекбокса появляется доступное описание
2. Можно нажать на текст и зачекать

2021-09-20 22:22 UTC, pepelsbey commented on tools/site-readers/index.md
> +<input type="checkbox"> Доступность.
```suggestion
<label><input type="checkbox"> Скорость загрузки</label>.
<label><input type="checkbox"> Семантику</label>.
<label><input type="checkbox"> Адаптивность</label>.
<label><input type="checkbox"> Валидность вёрстки</label>.
<label><input type="checkbox"> Последовательность кода</label>.
<label><input type="checkbox"> Доступность</label>.
```

2021-09-20 22:22 UTC, pepelsbey commented on tools/site-readers/index.md
> +<input type="checkbox"> Сделать микроразметку в синтаксисе JSON-LD.
```suggestion
<label><input type="checkbox"> Принять необходимость перечисленных ниже пунктов</label>.
<label><input type="checkbox"> Сделать сайт адаптивным</label>.
<label><input type="checkbox"> Сделать сайт контрастным</label>.
<label><input type="checkbox"> Сформировать структуру заголовков</label>.
<label><input type="checkbox"> Сделать ссылки доступными</label>.
<label><input type="checkbox"> Сделать контентные картинки доступными</label>.
<label><input type="checkbox"> Сделать аудио и видео доступными</label>.
<label><input type="checkbox"> Сделать формы доступными</label> (если есть формы).
<label><input type="checkbox"> Сделать таблицы доступными (если есть таблицы)</label>.
<label><input type="checkbox"> Сделать заголовки страниц</label> (тег `<title>`).
<label><input type="checkbox"> Сделать описания страниц</label> (тег `<meta name="description" content="...">`).
<label><input type="checkbox"> Сделать мета-описание в рамках OpenGraph</label>.
<label><input type="checkbox"> Сделать мета-описание в рамках Twitter</label> (если необходимо).
<label><input type="checkbox"> Сделать микроразметку в синтаксисе JSON-LD</label>.
```

2021-09-21 04:50 UTC, nlopin commented
> Я понимаю, что это припарка мёртвому, но так:
> 
>     1. У чекбокса появляется доступное описание
> 
>     2. Можно нажать на текст и зачекать

Классная находка, спасибо!

2021-09-21 07:18 UTC, bespoyasov approved these changes

2021-09-21 22:15 UTC, pepelsbey approved these changes

2021-09-21 22:15 UTC, merged