Добавляет статью про filter
doka-guide/content pull request #1650
Opened 2021-09-20 22:59 UTC by lenaryan

2021-09-20 23:58 UTC, pepelsbey requested changes

2021-09-20 23:58 UTC, pepelsbey commented on css/filter/index.md
> +Подробнее о том, за что отвечает каждая функция, можно прочитать [здесь](/css/filter-functions)
```suggestion
Подробнее о том, за что отвечает каждая функция, можно прочитать в статье «[Функции фильтров](/css/filter-functions)».
```

2021-09-21 06:36 UTC, solarrust reviewed
Спасибо что получилось быстро дописать эту статью!
Думаю, что стоит допилить ту крутую демку, над которой ты работала. Она отлично подойдёт для статьи про функции фильтров и будет нагладной сразу и для этой статьи про `filter` и для второй статьи про `backdrop-filter`.

2021-09-21 06:36 UTC, solarrust commented on css/filter/index.md
> +Подробнее о том, за что отвечает каждая функция, можно прочитать [здесь](/css/filter-functions)
```suggestion
Подробнее о том, за что отвечает каждая функция, можно прочитать в статье «[Функции фильтров](/css/filter-functions)».
```

2021-09-21 06:36 UTC, solarrust commented on css/filter/practice/lenaryan.md
> +🛠 Не поддерживается в IE11.
Это достойно того, чтобы перенести в раздел «Подсказки»

2021-09-21 06:36 UTC, solarrust commented on css/filter/practice/lenaryan.md
> +🛠 Можно применять не только к изображениям.
Стоит развернуть подсказку. К чему ещё можно применить фильтры?

2021-09-21 06:36 UTC, solarrust commented on css/filter/practice/lenaryan.md
> +🛠 Можно указать несколько функций через пробел.
Можно перенести в «Подсказки» и уточнить, что в зависимости от порядка будет разный результат.

2021-09-21 06:36 UTC, solarrust commented on css/filter/index.md
> +Фильтры без Фотошопа и Инстаграма на чистом CSS.
Давай уточним для чего именно можно использовать фильтры.

2021-09-21 12:42 UTC, tachisis approved these changes
Апрув на словарь

2021-09-29 15:21 UTC, solarrust commented
@pepelsbey заглядывай =)

2021-09-30 09:13 UTC, pepelsbey requested changes
Применимость фильтров очень сужается, лучше переформулировать некоторые части, чтобы не прятать возможности, применимые к любым блокам, особенно отбрасывание тени.

2021-09-30 09:13 UTC, pepelsbey commented on css/filter/index.md
> +Иногда во время вёрстки страницы нужно немного поправить картинку — изменить цветовую гамму, настроить яркость или контрастность. Но не всегда есть время или желание делать это в Фотошопе. В таких сл
Мне кажется, что это фантазийный пример использования. Ну вот правда, разве есть у разработчиков задачи поправить картинку без Фотошопа? Я бы описал что-нибудь реальное, например, есть дизайн, в котором картинки покрашены в ч/б или сепию, а при наведении становятся цветными. Или нужно отбросить тень иконкой не по квадрату блока, а по её форме (drop-shadow).

Вот это действительно поможет понять, зачем нужны фильтры.

2021-09-30 09:13 UTC, pepelsbey commented on css/filter/index.md
> +В скобках передаём числа, с помощью которых можно регулировать, насколько сильно фильтр искажает изображение. Для фильтра размытия (`blur`) передаём положительное число в любых единицах измерения, кр
```suggestion
В скобках передаём числа, с помощью которых можно регулировать, насколько сильно фильтр изменяет блок. Для фильтра размытия (`blur`) передаём положительное число в любых единицах измерения, кроме процентов. Для фильтра контрастности (`contrast`) и насыщенности (`saturate`) можно использовать значения больше 100%. В фильтр тени (`drop-shadow`) передаются значения, которые используются для обычной тени — сдвиг по осям X и Y, радиус размытия и цвет.
```

Не только картинки, не только искажает :)

2021-09-30 09:13 UTC, pepelsbey commented on css/filter/index.md
> +Фильтры с нулевым значением никак не влияют на изображение.
```suggestion
Фильтры с нулевым значением никак не влияют на результат.
```

2021-09-30 09:13 UTC, pepelsbey commented on css/filter/index.md
> +💡 Можно применять не только к изображениям, но и ко всем остальным элементам. К SVG и его внутренним тегам, кроме `<defs>` — тоже можно.
Этот совет стоит встроить в статью, чтобы не возникло заблуждения, что это только «Инстаграм в браузере».

2021-09-30 09:13 UTC, pepelsbey commented on css/filter/index.md
> +Фильтры без Фотошопа и Инстаграма на чистом CSS. Чаще всего применяются к изображениям.
Интро бы тоже поменять: это не только стили для картинок, это ещё и отбрасывание тени. Я бы тут говорил про графические фильтры и не напирал на перекрашивание, как основную задачу.

2021-11-15 13:22 UTC, solarrust commented
@pepelsbey @tachisis дописала статью с учётом комментариев, добавила пример. Поревьюёте, пожалуйста, хочется добить

2021-11-15 13:48 UTC, skorobaeus approved these changes

2021-11-15 17:20 UTC, tachisis reviewed
Правочки ✍️ А также как-то разорвало во многих местах предложения по разным строкам, может так не надо?

2021-11-15 17:20 UTC, tachisis commented on css/filter/demos/base/index.html
> +  <img src="../images/like.png" alt="Схматичное изображение собаки с сердечками вместо глаз.">
```suggestion
  <img src="../images/like.png" alt="Схематичное изображение собаки с сердечками вместо глаз.">
```

2021-11-15 17:20 UTC, tachisis commented on css/filter/index.md
> +Фильтры — очень мощный инструмент, помогающий реализовывать многие дизайнерские задумки в одну
```suggestion
Фильтры — очень мощный инструмент, он позволяет реализовать многие дизайнерские идеи при помощи одной строчки кода.
```

2021-11-15 17:20 UTC, tachisis commented on css/filter/index.md
> +  - solarrust
```suggestion
  - solarrust
editors:
  - tachisis
```

2021-11-15 17:20 UTC, tachisis commented on css/filter/index.md
> +Например, перекрасить элемент в сепию, добавить ему причудливую тень или использовать SVG в качестве
```suggestion
Например, перекрасить элемент в сепию, добавить ему необычную тень или использовать SVG в качестве
```

2021-11-15 17:20 UTC, tachisis commented on css/filter/index.md
> +Фильтры можно применить не только к картинкам, но к любым непустым элементам.
```suggestion
Фильтры можно применить не только к картинкам, но и к любым непустым элементам.
```

2021-11-15 17:20 UTC, tachisis commented on css/filter/index.md
> +строку, а не путём сложных манипуляций.
```suggestion
```

2021-11-15 17:20 UTC, tachisis commented on css/filter/index.md
> +В использовании фильтров удобно то, что исходная картинка или элемент никак не изменяются по факту.
```suggestion
В использовании фильтров удобно то, что исходная картинка или элемент никак не изменяются сами по себе.
```

2021-11-15 17:20 UTC, tachisis commented on css/filter/index.md
> +В качестве значения можно использовать любые [функции фильтров](/css/filter-functions) либо
```suggestion
В качестве значения можно использовать любые [функции фильтров](/css/filter-functions), либо
```

2021-11-15 17:20 UTC, tachisis commented on css/filter/index.md
> +использовать ключевое слово `none` для отключения любых фильтров.
```suggestion
ключевое слово `none` для отключения любых фильтров.
```

2021-11-17 09:00 UTC, solarrust commented
> Правочки ✍️ А также как-то разорвало во многих местах предложения по разным строкам, может так не надо?

Да, редактор задурил и включил автоперенос при 100 символах. Убрала.

2021-11-23 07:50 UTC, pepelsbey approved these changes

2021-11-23 07:52 UTC, solarrust approved these changes

2021-11-23 07:55 UTC, merged