Добавляет описание зафичереным материалам JS и Tools
doka-guide/content pull request #1676
Opened 2021-09-21 21:13 UTC by nlopin

Вдохновился #1674

2021-09-21 21:48 UTC, igsekor requested changes
Классно!

2021-09-21 21:48 UTC, igsekor commented on js/how-the-browser-creates-pages/index.md
> +description: "Какие этапы проходит HTML, CSS и JS код перед тем, как станет веб-страницей"
```suggestion
description: "Как обрабатывается HTML, CSS и JS код перед тем, как станет веб-страницей"
```

Может так? 😇

2021-09-21 21:48 UTC, igsekor commented on tools/cli/index.md
> +description: "Отдаём команды компьютеру с помощью текста"
```suggestion
description: "Отдаём команды компьютеру с помощью текста и становимся продуктивнее"
```

Показалось, что это важно подчеркнуть 🙃

2021-09-22 06:58 UTC, bespoyasov commented on js/async-in-js/index.md
> +description: "Как организовать взаимодействие с сервисами, которые не дают мгновенный обратный ответ"
Не совсем. Статья там больше о том, как в JS асинхронность работает под капотом, о сторонних сервисах там почти ничего нет. 

Может, стоит название поменять 🤔

2021-09-22 06:58 UTC, bespoyasov commented on js/deal-with-forms/index.md
> +description: "Как отправлять формы без перезагрузки страницы"
Тут тоже не до конца :—) 

Отправка без перезагрузки там есть, но основная идея статьи — показать, как вообще общаться с формами в JS: что есть специальные методы и свойства для доступа к значениям, проверке валидности и т. д.

2021-09-22 06:58 UTC, bespoyasov commented on js/async-in-js/index.md
> +description: "Как организовать взаимодействие с сервисами, которые не дают мгновенный обратный ответ"
Может, «Как устроен и работает асинхронный код в JS»?

2021-09-22 06:58 UTC, bespoyasov commented on js/how-to-test-and-why/index.md
> +description: "Разбираемся, как тесты помогают писать чистый новый код и увереннее редактировать старый"
```suggestion
description: "Как тесты помогают писать чистый новый код и увереннее редактировать старый"
```

2021-09-22 06:58 UTC, bespoyasov commented on js/deal-with-forms/index.md
> +description: "Как отправлять формы без перезагрузки страницы"
Может, «Как обрабатывать формы, валидировать их и отправлять без перезагрузки страницы с помощью JS»?

2021-09-22 09:03 UTC, nlopin commented on js/async-in-js/index.md
> +description: "Как организовать взаимодействие с сервисами, которые не дают мгновенный обратный ответ"
Мне хотелось избежать слова асинхронность

2021-09-22 11:12 UTC, bespoyasov commented on js/async-in-js/index.md
> +description: "Как организовать взаимодействие с сервисами, которые не дают мгновенный обратный ответ"
Мне просто не хочется, чтобы описание вводило в заблуждение и составляло неправильные ожидания. 

Может, «Как устроена асинхронность под капотом: что такое Event loop и очередь событий, причём здесь Web API, и как работают промисы и async/await»?

Да, мы повторяемся, но лишь для того, чтобы зонтично подвести к деталям.

2021-09-22 12:56 UTC, nlopin commented on js/async-in-js/index.md
> +description: "Как организовать взаимодействие с сервисами, которые не дают мгновенный обратный ответ"
давай так, мне нравится

2021-09-22 13:12 UTC, bespoyasov approved these changes

2021-09-22 15:37 UTC, tachisis commented on js/async-in-js/index.md
> +description: "Как устроена асинхронность под капотом: что такое Event loop и очередь событий, причём здесь Web API, и как работают промисы и async/await"
```suggestion
description: "Как устроена асинхронность: что такое Event loop и очередь событий, при чём здесь Web API, и как работают промисы и async/await"
```

2021-09-22 15:37 UTC, tachisis commented on tools/cli/index.md
> +description: "Отдаём команды компьютеру с помощью текста и становимся продуктивнее"
Мне, ээ, не очень нравится формулировка по сути — она какая-то упрощающая, как детям. Но я не знаю, что предложить взамен :( Может быть, призовем кого-нибудь еще подумать?

2021-09-22 15:37 UTC, tachisis commented on tools/static-types/index.md
> +description: "Рассказ про место TypeScript в современной разработке"
```suggestion
description: "Роль TypeScript в современной разработке"
```

2021-09-22 15:37 UTC, tachisis commented on tools/static-types/index.md
> +description: "Рассказ про место TypeScript в современной разработке"
А вообще хотелось бы чуть более развернуто, а то дескрипшен фактически дублирует название. Возможно, по примеру описаний Форм и Асинхронности: дать небольшой перечень, о чем там

2021-09-25 20:33 UTC, nlopin commented on tools/cli/index.md
> +description: "Отдаём команды компьютеру с помощью текста и становимся продуктивнее"
@tachisis что думаешь о нейтральном «Что такое командная строка и какие команды можно отдавать компьютеру»?

2021-09-27 12:14 UTC, tachisis commented on tools/cli/index.md
> +description: "Отдаём команды компьютеру с помощью текста и становимся продуктивнее"
@nlopin отлично, мне нравится

2021-09-27 21:41 UTC, merged