Обновляет схему в JS/API, удаляет нерелевантную картинку
doka-guide/content pull request #1695
Opened 2021-09-22 12:49 UTC by furtivite

- Получил новую схему, обновил. 
- Удалил нерелеватное изображение банкомата.

2021-09-22 12:59 UTC, nlopin approved these changes

2021-09-22 13:00 UTC, nlopin requested changes

2021-09-22 13:00 UTC, nlopin commented on js/api/index.md
>  Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
Кажется эту строку тоже надо убрать @furtivite

2021-09-22 13:06 UTC, furtivite commented on js/api/index.md
>  Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
@nlopin  Так я её убрал же, разве нет?

2021-09-22 13:14 UTC, bespoyasov approved these changes

2021-09-22 13:39 UTC, pepelsbey commented on js/api/index.md
>  Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
Это дифф, строки уже нет :)

2021-09-22 13:39 UTC, pepelsbey approved these changes

2021-09-22 17:14 UTC, nlopin commented on js/api/index.md
>  Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
Я про строку «Пользователь не видит, что происходит внутри, для него доступно только API калькулятора»

@bespoyasov удаляем?

2021-09-22 18:50 UTC, furtivite commented on js/api/index.md
>  Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
> Я про строку «Пользователь не видит, что происходит внутри, для него доступно только API калькулятора»

А! А я не понял просто сразу. Сорян.

2021-09-22 19:27 UTC, bespoyasov commented on js/api/index.md
>  Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
А, @nlopin, да, спасибо, что заметил.

2021-09-23 06:18 UTC, furtivite commented on js/api/index.md
>  Пользователь не видит, что происходит внутри, для него доступно только API «калькулятора».
Удалил.

2021-09-23 10:08 UTC, nlopin approved these changes

2021-09-23 10:08 UTC, merged