Редактирует часть о нашем флоу
doka-guide/content pull request #1704
Opened 2021-09-22 16:32 UTC by tachisis

Немного изменила названия веток, сделала, чтобы нумерованный список не рассыпался.

2021-09-22 16:35 UTC, furtivite requested changes
Сделал предложение, но если не хотим, то просто заапрувлю.

2021-09-22 16:35 UTC, furtivite commented on docs/contributing.md
> +    - исправления — `fix/название-статьи`.
Мы точно не хотим оставить `issue/number-название ветки`, где _number_ - это номер issue чтобы было проще отследить без привязки к issuе, если пиаров много?

Плюс я бы хотел иметь ветку `picture/название-статьи` для заливки любых картинок от дизайнеров

2021-09-22 16:42 UTC, tachisis commented on docs/contributing.md
> +    - исправления — `fix/название-статьи`.
У нас далеко не на все пиары есть ишью, кажется.

2021-09-22 16:43 UTC, furtivite commented on docs/contributing.md
> +    - исправления — `fix/название-статьи`.
> У нас далеко не на все пиары есть ишью, кажется.

Это да, но если issue есть, разве не хорошо было бы к нему привязаться?

2021-09-22 23:56 UTC, pepelsbey commented on docs/contributing.md
> +    - исправления — `fix/название-статьи`.
> Это да, но если issue есть, разве не хорошо было бы к нему привязаться?

Лучший способ привязаться к ишью — это слинковать его или написать _fix #N_. Я бы лучше такое поощрял, чем сложный нейминг.

2021-09-23 00:00 UTC, pepelsbey approved these changes

2021-09-23 06:37 UTC, furtivite commented on docs/contributing.md
> +    - исправления — `fix/название-статьи`.
Да, `fix/#N` мне полностью подходит, линковка в большинстве случаев особенно. А картинки — это просто `update`?

2021-09-23 08:45 UTC, furtivite approved these changes

2021-09-23 10:10 UTC, merged