Добавляет плейсхолдер для inset
doka-guide/content pull request #1771
Opened 2021-09-29 14:17 UTC by solarrust

2021-09-29 14:32 UTC, tachisis commented on css/inset/index.md
> +Свойство `inset` заменяет собой сразу 4 свойства: `top`, `right`, `bottom` и `left`. Позволяет указать смещение [позиционированного элемента](/css/position) сразу со всех четырёх сторон.
```suggestion
Свойство `inset` заменяет собой сразу четыре свойства: `top`, `right`, `bottom` и `left`. Позволяет указать смещение [позиционированного элемента](/css/position) сразу со всех четырёх сторон.
```

2021-09-29 14:32 UTC, tachisis commented on css/inset/index.md
> +Можно указать от одного до 4 значений через пробел. Значения применяются к четырём сторонам соответственно по часовой стрелке начиная с верхнего края.
```suggestion
Можно указать от одного до четырёх значений через пробел. Значения применяются к четырём сторонам соответственно, по часовой стрелке, начиная с верхнего края.
```

2021-09-29 14:32 UTC, tachisis commented on css/inset/index.md
> +Очень частая ситуация когда нужно задать позиционированному элементу 0 в качестве значения для свойств `top`, `right`, `bottom` и `left`. Можно написать на старый лад:
```suggestion
Очень часто встречается ситуация, когда нужно задать позиционированному элементу 0 в качестве значения для свойств `top`, `right`, `bottom` и `left`. Можно написать на старый лад:
```

2021-09-29 14:59 UTC, pepelsbey requested changes
Это свойство не просто замена top, right, bottom, left. Это шорткат для:

- inset-block-start
- inset-block-end
- inset-inline-start
- inset-inline-end

То есть это логическое свойство и привязка позиционирования будет к направлению письма, а не сторонам экрана. Об этом важно сказать :)

2021-09-29 15:43 UTC, tachisis approved these changes

2021-09-29 16:11 UTC, pepelsbey requested changes

2021-09-29 16:11 UTC, pepelsbey commented on css/inset/index.md
> +Свойство `inset` заменяет собой сразу четыре свойства: `top`, `right`, `bottom` и `left`. Позволяет указать смещение [позиционированного элемента](/css/position) сразу со всех четырёх сторон. Важно з
```suggestion
Свойство `inset` заменяет собой сразу четыре свойства: `top`, `right`, `bottom` и `left`. Позволяет указать смещение [позиционированного элемента](/css/position) сразу со всех четырёх сторон. Это логическое свойство, а значит позиционирование будет опираться не на стороны окна браузера, а на [направления письма](/css/writing-mode) и будет меняться вместе с ним.
```

2021-09-30 09:40 UTC, pepelsbey approved these changes

2021-09-30 09:43 UTC, merged