Добавляет статью for...of
doka-guide/content pull request #2097
Opened 2021-10-22 11:03 UTC by Windrushfarer

Fixes #1464

2021-10-29 20:20 UTC, nlopin commented on js/for-of/index.md
> +Цикл `for...of` — это один из способов обойти массив ли строку по порядку. Это возможно потому что массивы и строки реализуют специальный интерфейс итераторов. Большинство массивоподобных объектов в
да, они на очереди

2021-10-29 20:29 UTC, nlopin commented on js/for-of/index.md
> +Цикл `for...of` — это один из способов обойти массив ли строку по порядку. Это возможно потому что массивы и строки реализуют специальный интерфейс итераторов. Большинство массивоподобных объектов в
@Windrushfarer давай сошлёмся пока на MDN, там подробная статья

2021-10-29 20:57 UTC, nlopin commented on js/for-of/index.md
> +`for...of` позволяет пройти в [цикле](/js/loop) по любому перечисляемому объекту.
насколько я понимаю спеку, это неверное утверждение. Фор-оф обходит что угодно, что реализует интерфейс `Iterable`. Перечисляемые свойства обходит `for...in`

[Записал видосик, куда я смотрю в спеке](https://www.loom.com/share/ae9ce3ea92514fe78e0ca35b94bce5e9)

2021-10-29 20:58 UTC, nlopin commented on js/for-of/index.md
> +`for...of` позволяет пройти в [цикле](/js/loop) по любому перечисляемому объекту.
https://www.loom.com/share/ae9ce3ea92514fe78e0ca35b94bce5e9

2021-10-29 21:09 UTC, nlopin commented on js/for-of/index.md
> +Перечисляемые объекты в JavaScript – это строки и массивы.
Согласен с Сашей. Эта фраза выглядит как факт, но фактом не является. Есть ещё set, map и typed arrays
<img width="493" alt="image" src="https://user-images.githubusercontent.com/1469636/139501763-648d1c4b-9b1c-43d6-a5d2-09be4cbe84d5.png">

давай добавим их, чтобы всё чётенько было

2021-10-29 21:25 UTC, nlopin requested changes
Материал мне нравится, но нужно поправить фактологические ошибки

2021-10-29 21:25 UTC, nlopin commented on js/for-of/index.md
> +Схематично структура создания выглядит следующим образом:
```suggestion
Схематично структура создания цикла выглядит следующим образом:
```

2021-10-29 21:25 UTC, nlopin commented on js/for-of/index.md
> +Цикл `for...of` — это один из способов обойти массив ли строку по порядку. Это возможно потому что массивы и строки реализуют специальный интерфейс итераторов. Большинство массивоподобных объектов в
```suggestion
Цикл `for...of` — это один из способов обойти массив или строку по порядку. Это возможно потому что массивы и строки реализуют специальный интерфейс итераторов. Большинство массивоподобных объектов в API браузера и Node.js реализуют этот интерфейс, потому для них `for...of` тоже применяется.
```

тут кажется нужно отойти от конкретного примера или явно подчеркнуть, что не только массив или строка можеть быть

2021-10-29 21:25 UTC, nlopin commented on js/for-of/index.md
> +В JavaScript существует конструкция `for await...of`, это вариация `for...of`, которая умеет проходить по асинхронным итераторам.
предлагаю выделить под это подраздел. показать пример и рассказать, когда это может пригодиться

2021-10-29 21:25 UTC, nlopin commented on js/for-of/index.md
> +### Порядок перечисления
вот тут нам надо быть точными и сказать, что порядочек рулится реализацией итератора. Ну и рассказать про порядок у встроенных

2021-10-29 21:25 UTC, nlopin commented on js/for-of/index.md
> +`for...of` позволяет пройти в [цикле](/js/loop) по любому перечисляемому объекту.
Ещё давай тут скажем про асинхронную версию

2021-10-29 21:25 UTC, nlopin commented on js/for-of/index.md
> +Перечисляемые объекты в JavaScript – это строки и массивы.
Есть ещё итераторы, которые возвращают методы `map.values()`

2021-11-10 14:04 UTC, nlopin commented
@Windrushfarer тебя ждать или мне забрать статью на доработку?

2021-11-15 20:15 UTC, Windrushfarer commented
> @Windrushfarer тебя ждать или мне забрать статью на доработку?

Виноват, пропустил последние уведомления. Я добью на этой неделе

2022-02-03 11:20 UTC, Windrushfarer commented
С учетом появления статьи про итераторы я просто убрал ненужное и добавил ссылок :)

2022-02-04 11:47 UTC, bespoyasov reviewed
Согласен с @nlopin о порядке перечисления. В остальном 👍

2022-02-10 19:54 UTC, nlopin commented on js/for-of/index.md
> +Перечисляемые объекты в JavaScript – это все что реализует протокол [`Symbol.iterator`](/js/iterator/).
Мне кажется, что неверно говорить про протокол symbol.iterator. «Протокол итератора» мне кажется правильным

2022-02-10 19:54 UTC, nlopin commented on js/for-of/index.md
> +Для цикла необходимо объявить название переменной и указать значение, которое надо обойти в цикле. В объявленной переменной будет храниться значение в текущей итерации:
```suggestion
Для цикла необходимо объявить переменную и указать значение, которое надо обойти в цикле. В объявленной переменной будет храниться значение в текущей итерации:
```

2022-02-10 19:54 UTC, nlopin commented on js/for-of/index.md
> +// Порядок вывода:
```suggestion
```

2022-02-14 19:20 UTC, nlopin commented on js/for-of/index.md
> +### Порядок перечисления
@Windrushfarer что скажешь? Насколько я понимаю, у объектов порядок определяет внутренний вызов [ownPropertyKeys](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys), а он описывает чёткий порядок

2022-02-14 19:22 UTC, nlopin commented on js/for-of/index.md
> +### Порядок перечисления
<img width="598" alt="image" src="https://user-images.githubusercontent.com/1469636/153931800-99b25cf2-4b04-4ddc-816f-d0c651ec2400.png">

2022-02-15 07:40 UTC, nlopin commented
@Windrushfarer  я тут осознал, что у нас уже есть статья [for..in](https://doka.guide/js/for-in/). Эта заявлена, как `for...of`, но по факту она про for...in 🤔  Что будем с ней делать?

2022-02-15 08:19 UTC, Windrushfarer commented
> @Windrushfarer  я тут осознал, что у нас уже есть статья [for..in](https://doka.guide/js/for-in/). Эта заявлена, как `for...of`, но по факту она про for...in 🤔  Что будем с ней делать?

Я что-то не понял. В PR изначально я делал for..of. Изменения в for..in ты добавил в предыдущем коммите. Не понимаю почему она про for..in, это ведь разные операторы

2022-02-15 09:10 UTC, Windrushfarer commented on js/for-of/index.md
> +### Порядок перечисления
Я не очень понимаю зачем сюда приплетать `for..in`? Мы не говорим здесь про перечисления ключей объектов, если хочется это указать, можно сделать сноску (или callout). `for..of` тесно связан именно с протоколом итератора, и был добавлен вместе с ним в es6.
Плюс я уже указал в последнем предложении, что порядок может зависеть от [реализации итератора](https://github.com/doka-guide/content/pull/2097/files#diff-6e2895fdc432c993a22d0bcbe1c16ad02a252f2a0ffbe2d598427ddb6f99982fR53):

2022-11-27 12:20 UTC, heboq commented on js/for-in/index.md
> +Необходимо объявить переменную и указать объект, свойства которого нужно обойти. В объявленной переменной будет храниться имя свойства во время итерации.
```suggestion
Необходимо объявить переменную и указать объект, свойства  которого нужно обойти. В объявленной переменной будет храниться имя свойства во время итерации.
```
тест

2022-11-27 12:24 UTC, heboq requested changes
Тест

2022-11-27 12:55 UTC, heboq approved these changes

2022-12-07 10:14 UTC, HellSquirrel commented
Кажется тут уже давно не было активности. Я закрою этот PR, но если любой из авторов решит продолжить, но приходите обязательно и переоткрывайте :)

2022-12-07 10:14 UTC, closed without merging

2023-04-17 16:54 UTC, reinadiez commented
@Windrushfarer, привет! Я Настя, развиваю Доку, и мы хотим познакомиться с авторами поближе :)

Если ты не против поговорить о том, почему решил делиться знаниями, оставь, пожалуйста, ссылку на свой Телеграм, напишу.