Добавляет статьи про `column-rule` и его составляющие
doka-guide/content pull request #2207
Opened 2021-10-28 15:59 UTC by xpleesid

Fix #2173, Fix #2174, Fix #2175, Fix #2176 
Поскольку статьи получились однотипными и небольшими, объединил их в рамках одной ветки. Если получилось слишком много для одного ПРа, то разобью на куски поменьше

2021-11-02 10:04 UTC, solarrust reviewed
Очень мне нравятся демки ко всем твоим статьям, прямо супер. 

Остался небольшой вопрос.

2021-11-02 10:04 UTC, solarrust commented on css/column-rule/index.md
> +Прослеживается сходство со свойством [`border`](/css/border). Действительно, межколоночная линия описывается так же, как и рамка.
Остался вопрос: а какие из значений являются обязательными? А какие могут принимать значение по умолчанию и указать их не обязательно?

2021-11-02 18:57 UTC, xpleesid commented
Добавил информацию про обязательность значений и про значения по умолчанию там, где они есть

2021-11-03 09:24 UTC, solarrust approved these changes
Идеально 🥳

2021-11-03 09:36 UTC, skorobaeus approved these changes

2021-11-03 12:26 UTC, pepelsbey requested changes
В демках для хранения значений используется экзотический вариант:

```html
    <li data-style="groove">
      <input id="groove" type="radio" name="style">
```

Мне кажется, было бы лучше хранить их прямо в `value` радиокнопки.

```html
    <li>
      <input id="groove" type="radio" name="style" value="groove">
```

Небольшая правка, но демки станут проще и понятнее.

2021-11-03 17:34 UTC, xpleesid commented
Подправил код

2021-11-03 21:29 UTC, pepelsbey approved these changes
Красота!

2021-11-03 21:29 UTC, merged