Редактирует раздел о методах и свойствах на примитивах
doka-guide/content pull request #2220
Opened 2021-10-29 06:46 UTC by bespoyasov

Закрывает https://github.com/doka-guide/content/issues/2215.

@nlopin, а хотим ли мы добавить [деталей об `Object.prototype.toString`](https://262.ecma-international.org/5.1/#sec-15.2.4.2), или здесь это будет лишнее? 

Я посчитал, что строчное представление в виде `[object Null / Undefined]` нам здесь ни о чём не скажет, и пользы не принесёт. Но можем добавить, если ты считаешь иначе.

2021-10-31 07:54 UTC, nlopin requested changes
Давай заменим фразы «функция-примитив» на «обёртку примитивного типа», чтобы сохранить терминологию.

В [отдельных статьях](https://doka.guide/js/number-wrapper/) мы пишем «обёртка»

2021-10-31 07:58 UTC, nlopin commented on js/objects-objects-everywhere/index.md
> +```
нам это важно сказать здесь? на мой вкус это отступление вырывает из контекста и затем часть про `undefined` кажется потерянной

2021-11-01 06:49 UTC, bespoyasov commented on js/objects-objects-everywhere/index.md
> +```
Убрал.

2021-11-01 10:23 UTC, tachisis approved these changes

2021-11-01 12:36 UTC, nlopin approved these changes

2021-11-01 12:36 UTC, merged