Добавляет доку про column-span
doka-guide/content pull request #2226
Opened 2021-10-29 17:02 UTC by xpleesid

Fix #687

2021-10-29 19:06 UTC, pepelsbey requested changes
Я ждал продолжения! Немного мелочей:

- Бы бы привёл начало заголовков и параграфов вместо комментариев
- Файл index.11tydata.json добавится автоматически, его стоит удалить
- Чуть форматнул :)

2021-10-29 19:40 UTC, xpleesid commented
Поправил)

2021-10-29 19:43 UTC, pepelsbey approved these changes

2021-11-01 08:25 UTC, solarrust reviewed
Круто, как всегда!

Один момент: я увидела, чем чревато это свойство. А вот зачем оно может быть нужно я не очень поняла. Можем добавить пример где оно может пригодиться?

2021-11-01 12:19 UTC, xpleesid commented
Честно говоря, кроме текущих примеров, где column-span используется, чтобы выносить заголовки на всю ширину, мне больше ничего в голову не приходит(

2021-11-02 10:08 UTC, solarrust approved these changes
По поводу других примеров использования поняла. Мне тоже не приходит в голову какой-то более очевидный сценарий.

Спасибо, как всегда прекрасно! 🙏

2021-11-02 10:13 UTC, skorobaeus approved these changes

2021-11-02 10:33 UTC, merged