Редактирует практику веб-сервера (#1963)
doka-guide/content pull request #2231
Opened 2021-10-30 13:20 UTC by mbelsky

Привет!

Добавляет изменения обсуждённые в https://github.com/doka-guide/content/issues/1963

2021-10-30 22:05 UTC, pepelsbey requested changes

2021-10-30 22:05 UTC, pepelsbey commented on tools/web-server/practice/igsekor.md
> +В браузере вы можете видеть свой сайт по адресу [http://localhost:8080](http://localhost:8080). Сайт будет доступен и в локальной сети. Если смартфон, планшет, ноутбук или десктоп находится в одной л
Адрес `http://localhost:8080` не заработает на смартфонах, нужно воспользоваться IP-адресом локальной сети, который выдаёт Browsersync. Тут стоит развернуть, если хочется об этом рассказать.

2021-10-31 07:41 UTC, nlopin approved these changes

2021-10-31 13:55 UTC, igsekor approved these changes
С учётом комментария @pepelsbey. Спасибо, получилось сделать лучше 😇

2021-11-01 10:26 UTC, tachisis commented on tools/web-server/practice/igsekor.md
> +`browser-sync` удобно использовать и при разработке, и при тестировании проектов, потому что избавляет разработчиков от необходимости повторять рутинные действия вручную на нескольких экранах или уст
```suggestion
`browser-sync` удобно использовать и при разработке, и при тестировании проектов, потому что это избавляет разработчиков от необходимости повторять рутинные действия вручную на нескольких экранах или устройствах. При взаимодействии пользователя с сайтом на одном из устройств все действия будут немедленно воспроизводиться и на других устройствах. Например, если вы прокрутили страницу на смартфоне, она прокрутится и на других устройствах в сети. То же случится, если вы перейдёте на другую страницу сайта или будете взаимодействовать с формами.
```

2021-11-05 06:54 UTC, nlopin commented
@pepelsbey чекни, я добавил про адрес в локальной сети

2021-11-05 11:25 UTC, pepelsbey requested changes
Предлагаю немного поменять формулировки.

2021-11-05 11:25 UTC, pepelsbey commented on tools/web-server/practice/igsekor.md
> +В браузере вы можете видеть свой сайт по адресу [http://localhost:8080](http://localhost:8080) или [http://127.0.0.1:8080](http://127.0.0.1:8080).
```suggestion
В браузере вы можете видеть свой сайт по адресу [http://localhost:8080](http://localhost:8080) или [http://127.0.0.1:8080](http://127.0.0.1:8080). Это специальный адрес локального сервера на вашем компьютере.
```

2021-11-05 11:25 UTC, pepelsbey commented on tools/web-server/practice/igsekor.md
> +Сайт будет доступен и в локальной сети. Если смартфон, планшет, ноутбук или десктоп находится в одной локальной сети, например, подключены к одному WiFi, то на всех устройствах сайт будет доступен. Ч
```suggestion
Ваш локальный сервер не будет видно в интернете, но вы можете открыть его на устройствах, подключенных к одной и той же локальной сети, например, по Wi-Fi. Для этого нужно воспользоваться IP-адресом, который ваш роутер выдал компьютеру, на котором запущен сервер.
```

2021-11-05 11:25 UTC, pepelsbey commented on tools/web-server/practice/igsekor.md
> +  http://192.168.1.221:8080
```suggestion
Available on:
  http://127.0.0.1:8080
  http://192.168.1.56:8080
```

Первый адрес доступен только для компьютера с сервером, второй — для всех устройств сети.

2021-11-07 21:16 UTC, pepelsbey approved these changes

2021-11-07 21:16 UTC, merged

2021-11-07 21:17 UTC, pepelsbey commented
Спасибо!