Добавляет доку про column-fill
doka-guide/content pull request #2235
Opened 2021-10-30 16:14 UTC by xpleesid

Fix #2234 
Нужно мержить **после** #2207, иначе ссылка на column-rule будет вести в никуда)

2021-10-30 16:24 UTC, xpleesid commented
Еще в процессе написания возник вопрос - помимо прочего есть еще значение balance-all, в спеке оно уже есть, но еще никто не имплементировал. Как обрабатывать такие случаи? Просто не писать об этом, или указывать что такое есть и ссылку на caniuse, мол, посмотрите, если в момент чтения там уже что-то позеленело, то можете пойти проверить?

2021-10-30 21:55 UTC, pepelsbey requested changes

2021-10-30 21:55 UTC, pepelsbey commented on css/column-fill/index.md
> +Можно указать одно из 2 ключевых слов - `auto` или `balance`. `balance` – значение по умолчанию.
```suggestion
Можно указать одно из двух ключевых слов:

- `auto`;
- `balance` (значение по умолчанию).
```

2021-10-30 21:55 UTC, pepelsbey commented
> Еще в процессе написания возник вопрос - помимо прочего есть еще значение balance-all

Я бы так и написал: есть ещё третье значение, но его пока не внедрили. Причём лучше не в списке значений, а отдельным абзацем.

2021-10-31 12:29 UTC, xpleesid commented
Готово)

2021-10-31 16:38 UTC, pepelsbey approved these changes

2021-11-01 08:30 UTC, solarrust reviewed
Мне всё очень нравится!

Микроскопическая правка и можно мёржить =)

2021-11-01 08:30 UTC, solarrust commented on css/column-fill/index.md
> +Ещё есть третье значение – `balance-all`, но его пока ещё никто не внедрил. За процессом внедрения можно следить на [Can I use](https://caniuse.com/?search=balance-all).
```suggestion
Ещё есть третье значение – `balance-all`, но его пока не внедрил ни один из браузеров. За процессом внедрения можно следить на [Can I use](https://caniuse.com/?search=balance-all).
```

2021-11-01 09:57 UTC, skorobaeus approved these changes

2021-11-02 09:26 UTC, solarrust approved these changes
Заодно добавила статью в индекс CSS.

Спасибо большое за работу! Всегда приятно получать пул-реквесты от тебя 👍

2021-11-02 09:26 UTC, merged