Обновляет var/let статью
doka-guide/content pull request #2237
Opened 2021-10-30 20:49 UTC by ruslauz

Предложение по обновлению статьи про `var\let`. Что думаете на счет идеи объединения текущей статьи со статьей о `const`  под одним названием "Типы переменных" (либо как-нибудь по другому, на ваш вкус).

2021-10-30 21:09 UTC, nlopin commented on js/var-let/index.md
> +В случае применения `let` вместо `var` данный код выполнится с ошибкой - _"ReferenceError: Cannot access 'a' before initialization"_. Причиной такого поведения является существование у `let` и `const
очень крутое объяснение! я не уверен, что оно будет хорошо восприниматься начинающими. Давай его уберем в `details` с саммари «почему так?»

2021-10-30 21:12 UTC, nlopin commented
про объединение хороший вопрос. Создашь ишью, чтобы обсудить отдельно?

2021-10-30 21:13 UTC, ruslauz commented
> про объединение хороший вопрос. Создашь ишью, чтобы обсудить отдельно?

Хорошо. Создам.

2021-10-30 21:26 UTC, ruslauz commented on js/var-let/index.md
> +В случае применения `let` вместо `var` данный код выполнится с ошибкой - _"ReferenceError: Cannot access 'a' before initialization"_. Причиной такого поведения является существование у `let` и `const
Перенёс

2021-10-30 23:26 UTC, ruslauz commented
- [ ] добавить информацию про области видимости
- [ ] Обращение через var к одноименной переменной
- [ ] var и глобальный объект

2021-10-31 08:31 UTC, nlopin commented
@ruslauz не мёржить, пока тудушки не закроются? Я могу поставить тебя автором статьи?

2021-10-31 08:54 UTC, bespoyasov reviewed
Спасибо!
Я добавил ниже идею для улучшения кода.

> добавить информацию про области видимости

Об областях видимости можно также сослаться на [статью об этом](https://doka.guide/js/closures/).

2021-10-31 08:54 UTC, bespoyasov commented on js/var-let/index.md
> +console.log(Foo)
Разделим этот скрипт на два? Если запустить этот кусок кода сразу, то получим ошибку: 
> Uncaught SyntaxError: Identifier 'Foo' has already been declared

2021-10-31 08:54 UTC, bespoyasov commented on js/var-let/index.md
> +console.log(Foo)
Можно каждый из будущих кусков предварить текстом с описанием того, что произойдёт, чтобы подготовить читателя к тому, на что обратить внимание.

Например:

> Например, если мы попробуем вывести в консоль класс до его инициализации, получим ReferenceError:
> ... код
> А с функциями такой ошибки не будет:
> ...код

2021-10-31 10:13 UTC, ruslauz commented
> @ruslauz не мёржить, пока тудушки не закроются? Я могу поставить тебя автором статьи?

Да, я сделал пометки, чтобы не забыть. На счет авторства - на твоё усмотрение.

2021-10-31 15:55 UTC, ruslauz commented
В последнем коммите попробовал создать статью объединяющую описание var, let, const под названием - Типы переменных

2021-10-31 16:00 UTC, ruslauz commented on js/var-let/index.md
> +console.log(Foo)
Сделал

2021-11-01 07:16 UTC, bespoyasov reviewed
У меня есть ощущение, что мы не объяснили, почему `var` устарел и почему надо пользоваться `let` и `const` :–( 

То есть мы говорим, что есть TDZ и что инициализация проходит там, где `let` объявлен, но не говорим о том, почему это важно и как этим пользоваться в жизни. 

Думаю, стоит добавить:
- К чему может привести неосторожное использование `var`;
- Как может помочь `let` (хотя бы на знаменитом примере с циклом);
- Почему мы рекомендуем использовать `const` по умолчанию (@nlopin, а мы рекомендуем же? 😃)

2021-11-01 07:16 UTC, bespoyasov commented on js/var-let/index.md
> +// 5 10 15
Мне кажется, этот пример слегка... misleading. Есть ощущение, что он больше говорит [о времени инициализации](https://262.ecma-international.org/9.0/#sec-let-and-const-declarations).

Тут дело в том, что функция вызывается после того, как переменные объявлены. Но разница на самом деле вот в этом:

```js
console.log(a); 
var a = 10
// undefined

console.log(b); 
let b = 10
// Uncaught ReferenceError: Cannot access 'b' before initialization
```

В качестве примера для поднятия можно показать разницу между работой `var` и `let`, например.
Но это, может, мне только кажется. @nlopin, что думаешь ты?

2021-11-01 07:16 UTC, bespoyasov commented on js/var-let/index.md
>  var a = 10
Хочется показать, что будет, если я вызову `var a = 10`, но внутри функции:

```
var a = 5;

function b() {
  var a = 10;
}

console.log(a)
// 5
```

...и коротко объяснить разницу между двумя примерами. Можно также сослаться на области видимости.

2021-11-01 09:55 UTC, ruslauz commented on js/var-let/index.md
> +title: "Типы переменных"
Да, согласен. Можно переименовать в виды, или разновидности, или просто "Переменные"

2021-11-01 10:15 UTC, ruslauz commented on js/var-let/index.md
> +// 5 10 15
Да, можно немного изменить пример, убрав из него функцию
```js
var byVar = 5
let byLet = 10
const byConst = 15
```

Но оставить картинки которые показывают, что в начале скрипта они равны `undefined`, а в конце скрипта приобретают свое значение, ну и конечно то что `var`   у нас сразу же находится в _Global_, а `let`, `const` в  _Script_.

Пример с функцией я использовал чтобы показать, что переменные объявленные любым способом могут быть использованы например в функциях выше их объявления, главное чтобы вызов функции находился ниже их инициализации. Возможно он нуждается в разъяснении, либо могу  и в самом деле будет лучше убрать функцию, чтобы не путать читателя.

2021-11-01 10:19 UTC, ruslauz commented on js/var-let/index.md
>  var a = 10
То есть изменить пример таким образом?
```js
var a = 5;

function b() {
  console.log(a)
  // undefined

  var a = 10;
  console.log(a)
  // 10
}

console.log(a)
// 5
```

2021-11-01 10:29 UTC, ruslauz commented
> У меня есть ощущение, что мы не объяснили, почему `var` устарел и почему надо пользоваться `let` и `const` :–(
> 
> То есть мы говорим, что есть TDZ и что инициализация проходит там, где `let` объявлен, но не говорим о том, почему это важно и как этим пользоваться в жизни.
> 
> Думаю, стоит добавить:
> 
> * К чему может привести неосторожное использование `var`;
> * Как может помочь `let` (хотя бы на знаменитом примере с циклом);
> * Почему мы рекомендуем использовать `const` по умолчанию (@nlopin, а мы рекомендуем же? 😃)

Полностью согласен, на самом деле я не стал подробно все описывать следуя рекомендации от сюда https://github.com/doka-guide/content/issues/2238#issuecomment-955672168

2021-11-01 11:08 UTC, bespoyasov reviewed
> @bespoyasov полностью согласен, на самом деле я не стал подробно все описывать следуя рекомендации @pepelsbey от сюда #2238 (comment)

Ага. Тогда, мне кажется, будет достаточно одного абзаца, который расскажет коротко о том, что `let` и `const` безопаснее, чем `var`, подтвердив одним небольшим примером, а после — сославшись на соответствующие статьи с подробным описанием особенностей каждого служебного слова.

(Если статей пока нет, то ссылки на них добавим после написания.)

Просто совсем без объяснения «...Но почему мне надо использовать `let`?» статья выглядит не основательно, как будто мы советуем, но даже не говорим, зачем 😃

2021-11-01 11:08 UTC, bespoyasov commented on js/var-let/index.md
> +// 5 10 15
> Но оставить картинки которые показывают, что в начале скрипта они равны undefined, а в конце скрипта приобретают свое значение, ну и конечно то что var у нас сразу же находится в Global, а let, const в Script.

Да, верно — это как раз очень полезно 👍 

> Пример с функцией я использовал чтобы показать, что переменные объявленные любым способом могут быть использованы например в функциях выше их объявления, главное чтобы вызов функции находился ниже их инициализации. Возможно он нуждается в разъяснении, либо могу и в самом деле будет лучше убрать функцию, чтобы не путать читателя.

Я перечитал ещё раз, и мне кажется, что если _объяснить намерение и описать этот блок кода заранее_ — грубо говоря подготовить ожидания читателя от этого кода — то можно будет функцию даже не убирать 🤔 

Можем попробовать :–)

2021-11-01 11:08 UTC, bespoyasov commented on js/var-let/index.md
>  var a = 10
Лучше отдельным контр-примером добавить. 

То есть первый пример (нынешний) показывает, что можно переопределить переменную, использовав ещё раз `var`. А второй (новый, будущий) будет показывать, что внутри функции `var` создаст локальную переменную и не переопределит старую из-за областей видимости. (И тут ссылка на них как раз подойдёт хорошо.)

2021-11-01 11:09 UTC, bespoyasov commented
А в остальном мне всё нравится :—)

2021-11-01 11:26 UTC, ruslauz commented
@nlopin, @bespoyasov Надо ли описывать ситуацию когда переменная объявляется и ей присваивается какое-либо значение, вообще без использования var, let, const?

2021-11-01 11:29 UTC, bespoyasov commented
> Надо ли описывать ситуацию когда переменная объявляется и ей присваивается какое-либо значение, вообще без использования var, let, const?

Думаю, это можно описать в отдельной статьей, посвящённой `var`. 

Так как мы предупредим, что `var` не такой безопасный, можно будет сказать, что «примеры не очевидного поведения мы собрали в отдельной статье → ...».

Хочу, однако, уточнить это у @nlopin 😃

2021-11-07 19:05 UTC, ruslauz commented
Изменил название статьи, добавил примеров, постарался выполнить все ваши пожелания.

2021-11-08 06:51 UTC, bespoyasov approved these changes
👍 

@nlopin, глянешь тоже, пожалуйста?

2021-11-10 06:08 UTC, nlopin commented on js/var-let/index.md
> +title: "Переменные в JavaScript"
Предлагаю ключевые слова поместить в заголовок, чтобы их нашли поиском по странице:

```suggestion
title: "`const`, `let` и `var`"
```

2021-11-10 06:26 UTC, nlopin commented on js/var-let/index.md
> +Переменные `let` и `const` появились в версии EcmaScript 2015 года (ES6), на смену устаревшему `var`. В отличии от `var` имеют блочную область видимости и не становятся частью глобального объекта. В
отправлять в начало статьи не стоит. Во-первых, нужно скролить и потом возвращаться. Во-вторых, непонятно, на какую картинку смотреть, а поиском по тексту не найти.

2021-11-10 06:33 UTC, nlopin requested changes
Извини, что я так долго делал ревью. 

Мне нравится материал. Хочется изменить структуру статьи, чтобы она продвигала правильные практики. Сейчас повествование унаследовано от старой статьи: как работает var → подробности работы var → let-const. Такое повестование много рассказывает про var, будто эти знания чрезвычайно важны для каждодневной работы и надо использовать его.

Давай перестроим структуру, чтобы мы говорили про актуальное вначале:
- расскажем про концепцию переменной
- const
- let
- var со всем своим мясом
- на практике (рассказать когда что выбирать)

2021-11-10 06:37 UTC, nlopin commented
Я по-другому понимаю сообщение от @pepelsbey. Эта статья должна рассказать важные факты о трёх ключевых словах, чем они отличаются и как выбирать какое использовать. Така обзорная статья по верхам. Отдельные статьи, если понадобится, стоит делать для разжёвывания деталей каждого ключевого слова. 

Пока считаем, что есть одна статья для всего. Если и понадобится отдельная, то это новая итерация

2021-11-17 07:20 UTC, nlopin commented
@ruslauz прйти на помощь?

2021-11-17 10:50 UTC, ruslauz commented
> @ruslauz прйти на помощь?
Пока не надо, постараюсь на днях отредактировать статью.

2021-11-22 10:56 UTC, ruslauz commented
Осталось добавить еще один подраздел:

- на практике (рассказать когда что выбирать)

2021-11-23 06:23 UTC, nlopin commented on js/var-let/index.md
> +const date = new Date()
`date` слишком общее понятие, чтобы быть говорящим. Предлагаю такой вариант:

```suggestion
const now = new Date()
```

2021-11-23 07:03 UTC, nlopin requested changes
Мы приближаемся к финишу. Статья важная, поэтому хочется её сделать максимально понятной.

Призвал редактора на помощь.

2021-11-23 07:03 UTC, nlopin commented on js/var-let/index.md
> +```
надо подвинуть пример вверх, над пунктом «переменные const ...». Он вроде про значение `undefined`

2021-11-23 07:03 UTC, nlopin commented on js/var-let/index.md
> +![код со всплытием переменных](images/scopes-start.png)
Как ещё можно объяснить этот пример? Может у тебя в голове есть идея схемы или демки?

мне не очень нравится показывать скриншоты дебаггера, потому что новичку будет непонятно, куда смотреть

2021-11-28 17:11 UTC, ruslauz commented on js/var-let/index.md
> +
Такой пример не свалится [пример](https://replit.com/@ruslauz/PotableInvolvedPrograms?v=1)

2021-11-28 18:23 UTC, ruslauz commented on js/var-let/index.md
> +![код со всплытием переменных](images/scopes-start.png)
Честно сказать не знаю как еще обяснить, так как сонсоль логи показывают чему на самом деле равна переменная `a` прямо в примере, а далее ниже я  пошалого в тексте все это объясняю и для наглядности показываю скрины из дебаггера. То есть идет тройное обяснение примера. К тому же дебаггер наверное самый главный инструмент для разработчика (даже начинающего), так как иногда некоторые неочевидные моменты можно разобрать в нем и лучше понять как то или иное работает. На скриншотах я красным виделил то, куда надо обратить внимание.

2021-12-09 14:14 UTC, ruslauz commented
@nlopin Привет. Не смотрел последний вариант статьи?

2021-12-10 20:23 UTC, nlopin commented
@ruslauz привет! Вот пришёл смотреть. Спасибо, что не бросаешь

2021-12-10 21:07 UTC, nlopin commented on js/var-let/index.md
> +
Я и предлагаю расскзаать про всплытие там, где рассказываем про tdz. В текущем повествовании это слишком резкий переход к сложному концепту. Мы в прошлом абзаце говорили как переменные именовать, а тут уже про всплытие рассказываем.

Я вижу структуру так:
* что такое переменные как концепт
* как объявлять переменные
* что такое `const` (однократная запись, чтение)
* что такое `let` (многократная запись, чтение)
* что такое `var` 
* всплытие в деталях

@bespoyasov как бы ты рассказывал?

2021-12-10 21:25 UTC, bespoyasov commented on js/var-let/index.md
> +
Фактически прав @ruslauz, структура повествования логичнее выглядит у @nlopin.

Может, если не полностью повторить структуру, то всплытие можно перенести. 

Оно и правда сложнее, как идея. Чем плавнее подведём к нему читателей, тем лучше.

2021-12-11 10:18 UTC, nlopin commented on js/var-let/index.md
> +
> Может, если не полностью повторить структуру, то всплытие можно перенести.

Можешь тут развернуть?

2021-12-11 18:52 UTC, nlopin commented on js/var-let/index.md
> +В начале скрипта все переменные равны `undefined`:
давай здесь ещё раз подчеркнём, что переменные уже объявлены сразу, несмотря на то, что по тексту они объявляются ниже

2021-12-11 18:53 UTC, nlopin commented on js/var-let/index.md
> +В конце скрипта, после того как произошли инициализация и присвоение значений, переменные равны `5`, `10` и `15`:
Что такое инициализация здесь? инициализация значений? 

Смущает, что это слово не встречается в тексте выше и мы подразумеваем, что читатель знает, что это такое. А он может и не знать

2021-12-11 19:04 UTC, nlopin commented on js/var-let/index.md
> +Объявление переменной с именем, которое уже используется, приведёт к ошибке.
это не относится к смене значений, думаю можно вынести выше во вступление. Перед тем, как про блочную область видимости или в отдельный раздел, перед «значение по умолчанию»

2021-12-16 18:10 UTC, ruslauz commented on js/var-let/index.md
> +В начале скрипта все переменные равны `undefined`:
вижу ты уже исправил)

2021-12-17 19:28 UTC, ruslauz commented on js/var-let/index.md
> +В конце скрипта, после того как произошли инициализация и присвоение значений, переменные равны `5`, `10` и `15`:
Отрефакторил статьи. Изменил текст относящийся к всплытию.  Видимо я ошибался по этому поводу.

2021-12-17 19:29 UTC, ruslauz commented
@nlopin  привет, отрефакторил статью, пересмотрел некоторые моменты. Посмотри, что ты думаешь.

2021-12-22 20:29 UTC, nlopin commented
@ruslauz я привёл повествование про let/const и var к одной последовательности. Если тебе ок, то я готов смёржить

2021-12-22 20:29 UTC, nlopin approved these changes

2021-12-22 21:28 UTC, ruslauz commented
@nlopin, привет, небольшая правка с моей стороны, мне в роде бы все ок.

2021-12-23 06:00 UTC, merged

2021-12-23 06:01 UTC, nlopin commented
Это была самая сложная статья, над которой я работал в этом году. Спасибо @ruslauz, что довёл до конца. Следующие статьи точно будут публиковаться быстрее