Добавляет раздел "Детали реализации" для статьи про Math.random
doka-guide/content pull request #2246
Opened 2021-10-31 17:07 UTC by corocoto

В этом разделе ведется рассказ о том, как устроена функция под капотом. Также дано базовое определение генераторам псевдослучайных чисел.

2021-10-31 17:11 UTC, corocoto commented
@bespoyasov, @nlopin, @pepelsbey
Пока писал этот раздел, в голову пришла мысль, что можно посвятить отдельную страницу ГПСЧ (генераторам псевдослучайных чисел). Что думаете на этот счет?

2021-10-31 21:55 UTC, pepelsbey requested changes

2021-10-31 21:55 UTC, pepelsbey commented on js/math-random/index.md
> +За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** (их также называют **генераторами псевдослучайных чисел**).
```suggestion
На самом деле, эта функция не генерирует случайное число. Это лишь иллюзия. За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** (их также называют **генераторами псевдослучайных чисел**).
```

2021-10-31 21:55 UTC, pepelsbey commented on js/math-random/index.md
> +Поэтому числа, генерируемые `Math.random()`, можно предугадать. И именно поэтому вместо него предпочтительней использовать `crypto.getRandomValues()` для формирования ключа доступа, потому как послед
```suggestion
Любой **PRNG**-алгоритм генерирует числа, которые, в конечном счёте, будут повторяться. Поэтому числа, генерируемые `Math.random()`, можно предугадать. И именно поэтому вместо него предпочтительней использовать `crypto.getRandomValues()` для формирования ключа доступа, потому как последний криптографически устойчив.
```

2021-10-31 21:55 UTC, pepelsbey commented on js/math-random/index.md
> +>Но какой алгоритм используется для нашей функции, их же много?
```suggestion
_Но какой алгоритм используется для нашей функции, их же много?_
```

Это всё же не цитата, достаточно курсива для драматичности :)

2021-10-31 22:00 UTC, nlopin commented on js/math-random/index.md
> +Поэтому числа, генерируемые `Math.random()`, можно предугадать. И именно поэтому вместо него предпочтительней использовать `crypto.getRandomValues()` для формирования ключа доступа, потому как послед
криптоустойчивые ключи медленно генерируются. если мне нужен номер для того, чтобы добросить в конец ссылки для обхода кэша, то мне и псевдослучайного хватит. Важно сказать, что нужно отталкиваться от задачи и если она не связана с криптоштуками, то псевдослучайного числа хватит за глаза

2021-11-01 06:53 UTC, bespoyasov reviewed
Спасибо! 🙌 
Добавил пару идей для улучшений.

2021-11-01 06:53 UTC, bespoyasov commented on js/math-random/index.md
> +За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** (их также называют **генераторами псевдослучайных чисел**).
Я бы расшифровал аббревиатуру — она новая и незнакомая, хочется, чтобы читатель знал не только перевод, но и оригинальное название.

2021-11-01 06:53 UTC, bespoyasov commented on js/math-random/index.md
> +Разработчики браузерных движков сами определяют, какой алгоритм будет применяться в их среде. Но начиная с 2015 года, большинством используется **xorshift128+**. В этот список входят: Firefox, Safari
Думаю, стоит сослаться на страницу с описанием алгоритма, чтобы не приходилось гуглить руками 😃

2021-11-03 16:44 UTC, corocoto commented on js/math-random/index.md
> +Разработчики браузерных движков сами определяют, какой алгоритм будет применяться в их среде. Но начиная с 2015 года, большинством используется **xorshift128+**. В этот список входят: Firefox, Safari
@bespoyasov,  на русском информации не нашел, поэтому прикрепил ссылку на доступную pdf-книгу. Решил ее к себе в список для чтения добавить 🙂

2021-11-03 16:45 UTC, corocoto commented on js/math-random/index.md
> +За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** (их также называют **генераторами псевдослучайных чисел**).
@bespoyasov, добавил

2021-11-03 16:46 UTC, corocoto commented on js/math-random/index.md
> +Поэтому числа, генерируемые `Math.random()`, можно предугадать. И именно поэтому вместо него предпочтительней использовать `crypto.getRandomValues()` для формирования ключа доступа, потому как послед
@nlopin, спасибо, подредактировал этот абзац

2021-11-04 06:10 UTC, bespoyasov approved these changes

2021-11-04 06:10 UTC, bespoyasov commented on js/math-random/index.md
> +_Генератор псевдослучайных чисел (ГСПЧ)_ — метод генерации чисел арифметическим способом.
```suggestion
_Генератор псевдослучайных чисел (ГПСЧ)_ — метод генерации чисел арифметическим способом.
```

2021-11-04 06:10 UTC, bespoyasov commented on js/math-random/index.md
> +На самом деле, функция не генерирует случайное число. Это лишь иллюзия. За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** (их также называют _генерато
Всё же хочется расшировать аббревиатуру PRNG. Другие понятия мы поясняем, а это — нет, получается непоследовательно.

2021-11-04 06:10 UTC, bespoyasov commented on js/math-random/index.md
> +💡 Если ваша задача не подразумевает работу с криптографией (например, вычисление [кодов аутентичности](https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%B8%D1%82%D0%BE%D0%B2%D1%81%D1%82%D0%B0%D0%B2%D0%BA
```suggestion
💡 Если ваша задача не подразумевает работу с криптографией (например, вычисление [кодов аутентичности](https://ru.wikipedia.org/wiki/Имитовставка)) — вам будет достаточно псевдослучайных чисел. Но если такая потребность всё же есть — используйте [`crypto.getRandomValues()`](https://developer.mozilla.org/ru/docs/Web/API/Crypto/getRandomValues) вместо `Math.random()`.
```

2021-11-04 06:10 UTC, bespoyasov commented on js/math-random/index.md
> +На самом деле, функция не генерирует случайное число. Это лишь иллюзия. За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** (их также называют _генерато
```suggestion
На самом деле, функция не генерирует случайное число. Это лишь иллюзия. За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** — pseudorandom number generator, их также называют _генераторами псевдослучайных чисел_.
```

2021-11-04 08:10 UTC, corocoto commented on js/math-random/index.md
> +На самом деле, функция не генерирует случайное число. Это лишь иллюзия. За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** (их также называют _генерато
@bespoyasov, думаю, этот блок можно закрывать, потому как ты предложил улучшения ниже

2021-11-04 08:12 UTC, corocoto commented on js/math-random/index.md
> +За генерацию подобных чисел отвечают специальные алгоритмы, которые относятся к категории **PRNG** (их также называют **генераторами псевдослучайных чисел**).
https://github.com/doka-guide/content/pull/2246#discussion_r742610987

2021-11-04 18:30 UTC, bespoyasov approved these changes

2021-11-04 18:31 UTC, bespoyasov commented
@nlopin, глянешь тоже, пожалуйста?

2021-11-04 20:07 UTC, corocoto commented
Сейчас ci падает на этапе проверки орфографии, так как не распознает аббревиатуру "ГПСЧ". Можно добавить флаг [`--ignore-text <regexp>`](https://github.com/hcodes/yaspeller/blob/master/README.ru.md#--ignore-text-regexp) для yaspeller, чтобы не проверять эту фразу. 

В качестве альтернативы первому варианту, можно попробовать добавить комментарий[ `yaspeller ignore`](https://github.com/hcodes/yaspeller/blob/master/README.ru.md#исключение-части-текста-из-проверки) в нужной части markdown-файла.

P.S. Отмел вариант с использованием флага [--ignore-uppercase](https://github.com/hcodes/yaspeller/blob/master/README.ru.md#--ignore-uppercase), потому как слово, написанное капсом, может быть написано орфографически неверно, и проверки на ci уже не будет

2021-11-04 20:08 UTC, bespoyasov commented
@tachisis, мы же просто [добавляем незнакомые аббревиатуры в словарь](https://github.com/doka-guide/content/blob/main/docs/speller.md#как-добавлять-слова-в-словарь-исключений), верно?

2021-11-05 07:19 UTC, nlopin commented
исключения такого рода я бы просто обернул в инструкцию игнорирования. Мы так делаем с фамилиями, например

2021-11-06 09:07 UTC, nlopin approved these changes

2021-11-06 12:49 UTC, pepelsbey commented
@nlopin если есть шанс, что сокращение встретится ещё, то я бы лучше добавил в словарь. Кажется, что шанс есть.

Подождём @tachisis.

2021-11-08 13:19 UTC, tachisis commented
Давайте в словарь

2021-11-09 15:11 UTC, tachisis approved these changes
Апрув на словарь

2021-11-10 07:11 UTC, merged