Добавляет статью про Promise.allSettled
doka-guide/content pull request #2247
Opened 2021-10-31 18:56 UTC by vadymstebakov

2021-10-31 21:53 UTC, pepelsbey requested changes

2021-10-31 21:53 UTC, pepelsbey commented on js/promise-allSettled/index.md
> +});
```suggestion
Promise.allSettled(promises)
  .then(([response1, response2, response3]) => {
    console.log(response1)
    // { status: 'fulfilled', value: 3 }
    console.log(response2)
    // { status: 'rejected', reason: 'error' }
    console.log(response3)
    // { status: 'fulfilled', value: 1 }
})
```

2021-10-31 21:53 UTC, pepelsbey commented on js/promise-allSettled/index.md
> +  ```
````suggestion
Если промис выполнился успешно, то мы на выходе получаем объект следующего вида (где `value` - это значение, которое передали в `resolve`):

```js
{ status: 'fulfilled', value: <someValue> }
```

Если промис выполнился с отказом, то мы на выходе получаем объект следующего вида (где `reason` - это значение, которое передали в `reject`):

```js
{ status: 'rejected', reason: <someValue> }
```
````

Мы стараемся избегать вкладывать в списки что-то сложнее текста, так что пусть будут просто абзацы :)

2021-10-31 21:53 UTC, pepelsbey commented on js/promise-allSettled/practice/vadymstebakov.md
> +Этот метод появился в спецификации языка недавно, а именно [ES2020](https://habr.com/ru/company/plarium/blog/485362/), возможно вам понадобится [полифил](https://www.npmjs.com/package/promise.allsett
```suggestion
Примерно так можно использовать метод `allSettled`. Этот метод появился в спецификации языка недавно, а именно [ES2020](https://habr.com/ru/company/plarium/blog/485362/), возможно вам понадобится [полифил](https://www.npmjs.com/package/promise.allsettled).
```

Это отрендерится как один абзац, так это лучше и записать.

2021-10-31 21:53 UTC, pepelsbey commented on js/promise-allSettled/practice/vadymstebakov.md
> +  });
```suggestion
const urls = [
  'https://jsonplaceholder.typicode.com/todos/1',
  'https://jsonplaceholder.typicode.org/i_need_an_error',
];
const arrayFetchData = urls.map(url => fetch(url).then(res => res.json()))

Promise.allSettled(arrayFetchData)
  .then((res) => {
    // res — массив результатов выполнения промисов
    res.forEach(item => {
      if (item.status === 'fulfilled') {
          console.log(item)
          // { status: 'fulfilled', value: { userId: 1, id: 1, ... } }
      } else if (item.status === 'rejected') {
        console.log(item)
        // { status: 'rejected', reason: TypeError: Failed to fetch... }
      }
    })
  })
```

Мы в Доке не пишем точки с запятой в конце строки в JS. Пока правим вручную, но работаем над решением :)

2021-11-01 07:23 UTC, bespoyasov reviewed
Спасибо! 🙌 
Предложил пару улучшений :–)

2021-11-01 07:23 UTC, bespoyasov commented on js/promise-allSettled/index.md
> +Метод `allSettled` — это один из статических методов объекта `Promise`, очень похож на метод [`all`](/js/promise-all/). Метод `allSettled` используют, когда нужно запустить несколько промисов паралле
```suggestion
Метод `allSettled` — это один из статических методов объекта `Promise`, очень похож на метод [`all`](/js/promise-all/). Метод `allSettled` используют, когда нужно запустить несколько промисов параллельно и дождаться их выполнения, но в отличии от метода [`all`](/js/promise-all/#odin-iz-promisov-zavershilsya-oshibkoy), он ждёт выполнения всех промисов, не важно завершились они успешно или с ошибкой.
```

2021-11-01 07:23 UTC, bespoyasov commented on js/promise-allSettled/practice/vadymstebakov.md
> +      if (item.status === 'fulfilled') {
Сделаем пример попроще? Я бы убрал условия и оставил лишь перебор результатов и вывод их в консоль:

```js
// ...
res.forEach(item => {
  console.log(item);
});
// ...
```

А после показал бы, что выведется в консоль:

```js
// { status: 'fulfilled', value: { userId: 1, id: 1, ... } }
// { status: 'rejected', reason: TypeError: Failed to fetch... }
```

Это будет проще читать, потому что читателю не придётся «парсить код» в голове и разбираться в условиях внутри цикла :–)

2021-11-01 22:34 UTC, nlopin requested changes
Спасибо за работу! получается отличная статья

2021-11-01 22:34 UTC, nlopin commented on js/promise-allSettled/index.md
> +
сюда нужен раздел «Как пишется» с описанием сигнатуры метода так же, как и в [Promise.all](https://doka.guide/js/promise-all/#kak-pishetsya)

2021-11-01 22:34 UTC, nlopin commented on js/promise-allSettled/index.md
> +Метод `allSettled` — это один из статических методов объекта `Promise`, очень похож на метод [`all`](/js/promise-all/). Метод `allSettled` используют, когда нужно запустить несколько промисов паралле
Вот тут мы предполагаем, что читатель уже знаком с методом `Promise.all`. Давай не будем исходить из этого и в первую очередь расскажем, как работает метод, а уже затем сравним его с `Promise.all`

2021-11-01 22:34 UTC, nlopin commented on js/promise-allSettled/index.md
> +authors:
надо добавить описание для соцсеточек
```suggestion
description: "Статический метод Promise.allSettled используют, чтобы запустить несколько промисов параллельно и дождаться, когда они все выполнятся."
authors:
```

2021-11-01 22:34 UTC, nlopin commented on js/promise-allSettled/index.md
> +Создадим массив промисов и передадим его в `Promise.allSettled()`:
```suggestion
Создадим массив промисов и передадим его в `Promise.allSettled()`. Один из созданных промисов завершится ошибкой:
```

2021-11-01 22:34 UTC, nlopin commented on js/promise-allSettled/index.md
> +{ status: 'fulfilled', value: <someValue> }
русифицируем, чтобы не расшифровывать
```suggestion
{ status: 'fulfilled', value: значение }
```

2021-11-01 22:34 UTC, nlopin commented on js/promise-allSettled/index.md
> +Если промис выполнился успешно, то мы на выходе получаем объект следующего вида (где `value` - это значение, которое передали в `resolve`):
давай тут опишем объект: 
```suggestion
Если промис выполнился успешно, то на выходе получаем объект с двумя свойствами — `status` и `value`. `status` будет содержать строку `'fulfilled'`, а `value` — значение, которое передали при вызове `resolve` у промиса:
```

2021-11-01 22:34 UTC, nlopin commented on js/promise-allSettled/index.md
> +Если промис выполнился с отказом, то мы на выходе получаем объект следующего вида (где `reason` - это значение, которое передали в `reject`):
```suggestion
Если промис выполнился с отказом, то на выходе получаем объект с двумя свойствами — `status` и `reason`. `status` будет содержать строку `'rejected'`, а `reason` — значение, которое передали при вызове `reject` у промиса:
```

2021-11-01 22:34 UTC, nlopin commented on js/promise-allSettled/practice/vadymstebakov.md
> +Примерно так можно использовать метод `allSettled`. Этот метод появился в спецификации языка недавно, а именно [ES2020](https://habr.com/ru/company/plarium/blog/485362/), возможно вам понадобится [по
давай сошлёмся на спеку

2021-11-02 09:08 UTC, bespoyasov approved these changes

2021-11-06 20:10 UTC, nlopin commented on js/promise-allSettled/index.md
> +Метод `allSettled` возвращает массив значений всех переданных промисов, при этом сохраняя порядок оригинального (переданного) массива, но не порядок выполнения.
Я тут осознал, что он возвращает промис массивов, а не массив. Поправлю сам

2021-11-06 20:46 UTC, nlopin approved these changes

2021-11-07 07:54 UTC, nlopin commented
@vadymstebakov переименуй пожалуйста папку из `allSettled` в `allsettled`, я не могу это сделать без боли, потому что у мака регистронезависимая файловая система

2021-11-07 11:20 UTC, vadymstebakov commented
> @vadymstebakov переименуй пожалуйста папку из `allSettled` в `allsettled`, я не могу это сделать без боли, потому что у мака регистронезависимая файловая система

@nlopin готово

2021-11-07 16:45 UTC, nlopin commented
Огонь! Если в понедельник @pepelsbey не посмотрит, то вечером солью в мейн! Отличная работа, спасибо за участие 🖤

2021-11-07 20:31 UTC, pepelsbey approved these changes

2021-11-07 20:32 UTC, merged

2021-11-07 20:32 UTC, pepelsbey commented
Спасибо!