Добавляет дизайн для демо в Number.isNaN
doka-guide/content pull request #2260
Opened 2021-11-01 11:37 UTC by skorobaeus

2021-11-01 12:33 UTC, nlopin requested changes
предложил несколько улучшений, давай обсудим

2021-11-01 12:33 UTC, nlopin commented on js/number-is-nan/demos/index/index.html
> +    document.querySelector('#discount').value = "Скидок нет"
давай их укажем в НTML?

2021-11-01 12:33 UTC, nlopin commented on js/number-is-nan/demos/index/index.html
> +      const d = document.querySelector('#discount').value
давай здесь сделаем читаемо? что-то типа `priceInput` и `discoutInput`

ещё обратил внимание, что мы в одном случае храним элемент, а в другом — число. Предлагаю в обоих случаях хранить что-то одинаковое

2021-11-01 12:33 UTC, nlopin commented on js/number-is-nan/demos/index/index.html
> +        total.innerText = p.value - (p.value / 100 * d).toFixed(2)
мы считаем то же самое в обеих ветках. кажется это можно вынести за if

Предлагаю немного реорганизовать код, чтобы не было такой большой вложенности:

```js
let discount = p.value - (p.value / 100 * d).toFixed(2)

if (isNaN(discount)) {
          if (isNaN(p.value)) {
            p.classList.add("error")
          } else if (!p.value) {
            discount = 0
          } else {
            discount = p.value
          }
        }

total.innerText = discount

```

2021-11-02 10:56 UTC, ruslauz commented on js/number-is-nan/demos/index/index.html
> +          if (isNaN(priceValue)) {
В примере используется `isNaN()`, не будет ли более правильным, исходя из содержания статьи, заменить ее на `Number.isNaN()`.

2021-11-02 11:00 UTC, skorobaeus commented on js/number-is-nan/demos/index/index.html
> +        total.innerText = p.value - (p.value / 100 * d).toFixed(2)
@nlopin предложения внесла ✌

2021-11-02 11:01 UTC, skorobaeus commented on js/number-is-nan/demos/index/index.html
> +          if (isNaN(priceValue)) {
Вам виднее. Этот код унаследован из оригинального демо :)

2021-11-02 11:13 UTC, skorobaeus commented on js/number-is-nan/demos/index/index.html
> +          if (isNaN(priceValue)) {
Результат отличается, кстати:

![image](https://user-images.githubusercontent.com/29401439/139836178-62b9bac5-bbd7-4c07-aaf4-ad3d18fd9328.png)

Я не понимаю тонкую разницу между `isNaN()` и `Number.isNaN()` 🤷‍♀️

2021-11-02 18:16 UTC, ruslauz commented on js/number-is-nan/demos/index/index.html
> +          if (isNaN(priceValue)) {
Попробуй это код
```js
    function check() {
      const priceInput = document.querySelector('#price')
      const priceValue = +document.querySelector('#price').value
      const discountValue = +document.querySelector('#discount').value
      const checkNaN = document.querySelector('#checkNaN').checked
      const total = document.querySelector('#total')

      priceInput.classList.remove("error")

      let discount = priceValue - (priceValue / 100 * discountValue).toFixed(2)
      if (checkNaN) {
        if (Number.isNaN(discount)) {
          discount = priceValue
        }
        if (Number.isNaN(priceValue)) {
          discount = 0
        }
      }
      total.innerText = discount
    }

    check()
```

2021-11-02 22:14 UTC, nlopin commented on js/number-is-nan/demos/index/index.html
> +          if (isNaN(priceValue)) {
Я тоже про это подумал, когда смотрел статью. У нас нет договорённости, что демки должны содержать демонстрируемые функции. Они должны визуально обьяснять материал

@skorobaeus разница между функциями в том, что isNaN пытается привести переданный аргумент к числу и потом проверить на NaN, а Number.isNaN не пытается, а сразу возвращает false для нечисловых аргументов.

2021-11-03 09:03 UTC, skorobaeus commented on js/number-is-nan/demos/index/index.html
> +          if (isNaN(priceValue)) {
@ruslauz @nlopin обновила ✌

2021-11-05 07:14 UTC, nlopin commented on js/number-is-nan/demos/index/index.html
> +      const priceValue = +document.querySelector('#price').value
@skorobaeus зачем плюсики?

2021-11-08 09:24 UTC, skorobaeus commented on js/number-is-nan/demos/index/index.html
> +      const priceValue = +document.querySelector('#price').value
@nlopin это @ruslauz предложил. Поменяла на Number()

2021-11-10 07:11 UTC, nlopin approved these changes

2021-11-10 07:11 UTC, merged