Обновляет информацию о <sub> и <sup>
doka-guide/content pull request #2277
Opened 2021-11-01 16:52 UTC by xpleesid

Fix #553 , Fix #569 
Получилось очень похоже, поэтому объединил в один ПР )

2021-11-01 21:00 UTC, pepelsbey requested changes
Здорово, что вы взялись расширить статью! Но мне кажется, что вы теряете по пути хорошие вещи, которые в ней уже были:

- Заменяете одни примеры на другие
- Склеиваете примеры в одну строку

Попробуйте написать свои демки, чтобы их было удобно читать и понимать. Даже тем, кто пока не очень ловко отслеживает теги в разметке.

А ещё я бы вывел формулы не псевдокодом, а как их учат на алгебре, с правильной типографикой:

2 × log<sub>3</sub>(Z<sup>2</sup>)
2*log<sub>3</sub>(Z<sup>2</sup>)

Правда первое лучше? Не склеивается и понятно зачем делать красивые надстрочные.

2021-11-01 23:16 UTC, xpleesid commented
Устранил замечания, спасибо за правки 👍

2021-11-02 09:09 UTC, solarrust reviewed
Спасибо огромное за работу!

Оставила несколько комментариев. 
Поддержу @pepelsbey, хочется больше весёлых (на сколько это возможно в рамках такой темы) демок =)

2021-11-02 09:09 UTC, solarrust commented on html/sub/demos/basic/index.html
> +  <title>Формула воды — sub — Дока</title>
```suggestion
  <title>Формула воды — <sub> — Дока</title>
```

2021-11-02 09:09 UTC, solarrust commented on html/sub/demos/nested/index.html
> +  <title>Вложенные теги — sub — Дока</title>
```suggestion
  <title>Вложенные теги — <sub> — Дока</title>
```

2021-11-02 09:09 UTC, solarrust commented on html/sub/demos/sup/index.html
> +  <title>Пример с sup — sub — Дока</title>
```suggestion
  <title>Пример с <sup> — <sub> — Дока</title>
```

2021-11-02 09:09 UTC, solarrust commented on html/sub/demos/variables/index.html
> +  <title>Сумма массива — sub — Дока</title>
```suggestion
  <title>Сумма массива — <sub> — Дока</title>
```

2021-11-02 09:09 UTC, solarrust commented on html/sub/demos/variables/index.html
> +    <var>X<sub>N</sub></var>
```suggestion
  <p>
    Сумма массива может быть вычислена последовательным сложением всех его элементов:<br>
    sum := <var>X<sub>1</sub></var> + <var>X<sub>2</sub></var> + ... + <var>X<sub>N</sub></var>
```

2021-11-02 09:09 UTC, solarrust commented on html/sub/index.md
> +
Здесь я бы дала самый очевидный пример использования тега. А все примеры ниже переместила бы в раздел «Как пишется» и озаглавила своими подзаголовками.

Не стоит забывать, что, как правило, человек будет приходить быстро узнать что за тег и как его писать и редко захочет погрузиться в частные случаи.

2021-11-02 09:09 UTC, solarrust commented on html/sup/demos/basic/index.html
> +  <title>Теорема Пифагора — sup — Дока</title>
```suggestion
  <title>Теорема Пифагора —  <sup> — Дока</title>
```

2021-11-02 09:09 UTC, solarrust commented on html/sup/demos/nested/index.html
> +  <title>Вложенные теги — sup — Дока</title>
```suggestion
  <title>Вложенные теги — <sup> — Дока</title>
```

2021-11-02 09:09 UTC, solarrust commented on html/sup/demos/sub/index.html
> +  <title>Пример с sub — sup — Дока</title>
```suggestion
  <title>Пример с <sub> — <sup> — Дока</title>
```

2021-11-02 09:09 UTC, solarrust commented on html/sup/demos/variables/index.html
> +  <title>Квадрат суммы — sup — Дока</title>
```suggestion
  <title>Квадрат суммы — <sup> — Дока</title>
```

2021-11-02 09:09 UTC, solarrust commented on html/sup/index.md
> +
Аналогичное предложение — тут дать самый очевидный пример использования, а все случаи, описанные ниже, перенести в «Как пишется»

2021-11-02 09:10 UTC, solarrust commented
Просьба резолвить те обсуждения, по которым были внесены правки, которые уже не актуальны. Чтобы было сразу понятно, что ещё актуально, а что уже нет =)

2021-11-02 11:11 UTC, pepelsbey approved these changes

2021-11-02 13:06 UTC, skorobaeus commented on html/sub/demos/sup/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap">
```suggestion
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
```

Моноширинное начертание для кода, а в этих демо обычный текст.

2021-11-02 13:07 UTC, skorobaeus commented on html/sub/demos/basic/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap">
```suggestion
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
```

Моноширинное начертание для кода. В этом демо и в других простой текст.

2021-11-02 13:09 UTC, skorobaeus commented on html/sub/demos/basic/index.html
> +      font-family: "Roboto Mono", monospace;
```suggestion
      font-size: 24px;
      font-family: "Roboto", sans-serif;
```

Демо состоит из одной строки, на размере шрифта не экономим :)

2021-11-02 13:14 UTC, skorobaeus commented on html/sub/demos/nested/index.html
> +      font-family: "Roboto Mono", monospace;
Здесь тоже лучше переключить на Roboto и 24px

2021-11-02 13:19 UTC, skorobaeus commented on html/sub/demos/sup/index.html
> +    }
```suggestion

    var {
      font-style: normal;
    }
```

На мой взгляд, курсив здесь только затрудняет чтение, и не способствует выразительности.

2021-11-02 13:19 UTC, skorobaeus commented on html/sub/demos/variables/index.html
> +    }
И здесь тоже убрала бы курсив у `<var>`

2021-11-02 13:20 UTC, skorobaeus requested changes
Привет! Большое спасибо за демки и за поддержку их стиля!

Давайте, пожалуйста, выровняем текст по центру по вертикали и горизонтали.

2021-11-02 18:25 UTC, xpleesid commented on html/sub/demos/variables/index.html
> +    <var>X<sub>N</sub></var>
А раньше @pepelsbey предложил сделать ровно наоборот) мне кажется лучше оставить как сейчас, чтобы было удобнее на телефонах смотреть

2021-11-02 18:26 UTC, xpleesid commented
Спасибо за замечания, поправил)

2021-11-02 19:57 UTC, pepelsbey commented on html/sub/demos/variables/index.html
> +    <var>X<sub>N</sub></var>
Я полагаю, что @solarrust предлагает в статье отформатировать развёрнуто, а в самой демке — проще.

2021-11-02 20:11 UTC, xpleesid commented on html/sub/demos/variables/index.html
> +    <var>X<sub>N</sub></var>
А, теперь понял о чем шла речь \*facepalm\*

2021-11-03 09:22 UTC, solarrust reviewed
Всё практически идеально! 👍

От меня буквально одна маленькая правка и аппрув =)

2021-11-03 09:22 UTC, solarrust commented on html/sub/index.md
> +Помимо описанного выше примера, можно использовать тег `<sub>` внутри тега [`<var>`](/html/var) для вывода индекса переменных, например, элементов массива или матрицы.
У нас (пока) нет статьи про `var`. Ссылка поведёт на 404 страницу 😔

2021-11-03 12:57 UTC, pepelsbey commented on html/sub/index.md
> +Помимо описанного выше примера, можно использовать тег `<sub>` внутри тега [`<var>`](/html/var) для вывода индекса переменных, например, элементов массива или матрицы.
Уже есть!

2021-11-03 12:58 UTC, solarrust commented on html/sub/index.md
> +Помимо описанного выше примера, можно использовать тег `<sub>` внутри тега [`<var>`](/html/var) для вывода индекса переменных, например, элементов массива или матрицы.
Ты путаешь функцию `var()` в CSS и тег `<var>` в HTML =)

2021-11-03 12:59 UTC, pepelsbey commented on html/sub/index.md
> +Помимо описанного выше примера, можно использовать тег `<sub>` внутри тега [`<var>`](/html/var) для вывода индекса переменных, например, элементов массива или матрицы.
Ауч

2021-11-03 13:03 UTC, pepelsbey approved these changes

2021-11-03 13:03 UTC, solarrust approved these changes

2021-11-08 11:17 UTC, skorobaeus approved these changes

2021-11-09 19:30 UTC, solarrust commented
🔥
Очень классно получилось!

2021-11-09 19:31 UTC, merged