Добавляет доку про тернарный оператор
doka-guide/content pull request #2285
Opened 2021-11-02 12:59 UTC by Ginger-Raccoon

Fix #2136

2021-11-02 13:00 UTC, Ginger-Raccoon commented
Это было сложнее чем я думал, любые правки и комментарии приветствуются

2021-11-02 16:03 UTC, pepelsbey reviewed
Спасибо, что взялись!

Я не настоящий программист, но у меня есть мысли :)

2021-11-02 16:03 UTC, pepelsbey commented on js/ternary-operator/index.md
> +Тернарный (условный) оператор — единственный оператор с тремя аргументами. Первый аргумент это условие, если оно истинно (true) — оператор вернёт второй аргумент (выражение 1). В ином случае (false)
```suggestion
Тернарный оператор позволяет записать условие и выражения очень компактно, буквально в одну строку.
```

Мне кажется, что в «кратко» нужно очень кратко выразить суть. А то сейчас начинается пересказ того, что уже есть в «как пишется». Ценность того, что это единственный оператор с тремя аргументами — ну, тоже кажется небольшая.

2021-11-02 17:13 UTC, bespoyasov requested changes
Спасибо за работу! 👍 
Получается отличная статья :–) 

Я добавил несколько улучшений по тексту и коду. Большая часть — небольшие по объёму.

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +Результат возвращаемый тернарным оператором можно записать в переменную (как в примере выше) или вернуть с помощью `return` внутри функции:
Здесь можно добавить коллаут с описанием того, что раз можно записать в переменную, то это — выражение, и сослаться на [статью о разнице между ними](https://doka.guide/js/expressions-vs-statements/) или [спецификацию](https://262.ecma-international.org/6.0/#sec-conditional-operator) 🙃

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +можно записать как:
```suggestion
...Можно записать как:
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +При выборе между [`if...else`](/js/if-else) и тернарным оператором в приоритет нужно ставить читабельность. Чем код нагляднее и понятнее, тем проще с ним в дальнейшем работать.
Хочется пару примеров:
- один с простым тернарником, который читается и можно использовать;
- второй — с дикой дичью, в которой ничего непонятно, чтобы показать насколько это больно 😃

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +  return (name) ? `Рад видеть, ${name}!` : 'Привет, друг!'
```suggestion
  return name ? `Рад видеть, ${name}!` : 'Привет, друг!'
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +Так же поддерживается вложенность:
```suggestion
Также поддерживается вложенность нескольких условий:
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +Так же поддерживается вложенность:
Сюда стоит дописать, как читать вложенный тернарник: чего ожидать, как записывать. Можно использовать форматирование кода, чтобы показать, в каком порядке будут проверяться условия.

Также можно под `details` пояснить понятие «ассоциативности справа», но не обязательно.

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +const result = (num > 10) ? 'Число больше 10' : (num = 10) ? 'Число равно 10' : 'Число меньше 10'
```suggestion
const result = num > 10 ? 'Число больше 10' : num === 10 ? 'Число равно 10' : 'Число меньше 10'
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +let salutation = function(name) {
```suggestion
const salutation = function(name) {
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +let num = 10
```suggestion
const num = 10
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +let num = 10
```suggestion
const num = 10
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +const result = (num > 10) ? 'Число больше 10' : 'Число меньше или равно 10'
```suggestion
const result = num > 10 ? 'Число больше 10' : 'Число меньше или равно 10'
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +По механике работы оператор похож на конструкцию [`if...else`](/js/if-else), но позволяет писать меньше кода, например:
```suggestion
По механике работы оператор похож на конструкцию [`if...else`](/js/if-else), но позволяет писать меньше кода или записать результат сравнения в переменную. Например:
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +let num = 10
```suggestion
const num = 10
```

2021-11-02 17:13 UTC, bespoyasov commented on js/ternary-operator/index.md
> +Обратите внимание, во втором примере мы используем `const` вместо `let`.
```suggestion
Обратите внимание, во втором примере мы уже используем `const` вместо `let`, потому что переприсвоения значения переменной уже нет.
```

2021-11-02 17:16 UTC, bespoyasov commented on js/ternary-operator/index.md
> +Результат возвращаемый тернарным оператором можно записать в переменную (как в примере выше) или вернуть с помощью `return` внутри функции:
Под коллаутом я имею в виду вот такую врезку, как в [статье о выражениях](https://doka.guide/js/expressions-vs-statements/):

<img width="936" alt="«Screenshot» 2021-11-02 at 20 14 19" src="https://user-images.githubusercontent.com/9102374/139913402-da90c6f5-2c05-4394-9dec-836e9352a3f6.png">

В исходниках задаётся тегом `aside`:

<img width="593" alt="«Screenshot» 2021-11-02 at 20 15 56" src="https://user-images.githubusercontent.com/9102374/139913643-38ccef75-f0ec-44c4-ba9c-cc677a3d481b.png">

2021-11-02 18:59 UTC, Ginger-Raccoon commented
@pepelsbey Я полагаю более настоящий чем я :-)  Спасибо за правки, буду улучшать!

2021-11-02 19:02 UTC, Ginger-Raccoon commented on js/ternary-operator/index.md
> +Результат возвращаемый тернарным оператором можно записать в переменную (как в примере выше) или вернуть с помощью `return` внутри функции:
Принял, буду править :+1:

2021-11-02 19:03 UTC, Ginger-Raccoon commented on js/ternary-operator/index.md
> +При выборе между [`if...else`](/js/if-else) и тернарным оператором в приоритет нужно ставить читабельность. Чем код нагляднее и понятнее, тем проще с ним в дальнейшем работать.
Принято!)

2021-11-02 19:03 UTC, Ginger-Raccoon commented on js/ternary-operator/index.md
> +Так же поддерживается вложенность:
Сначала поясню себе, потом другим :D

2021-11-02 20:13 UTC, pepelsbey approved these changes

2021-11-10 06:57 UTC, nlopin commented on js/ternary-operator/index.md
> +title: "Тернарный оператор"
Надо добавить краткое описание для соцсеточек. Предлагаю такой вариант: 
```suggestion
title: "Тернарный оператор"
description: "Что такое тернарный оператор и как он заменяет короткие if"
```

2021-11-10 07:10 UTC, nlopin requested changes
Классно, мне очень нравится, что текст короткий, но с кучей примеров. Ждём правок!

2021-11-10 07:10 UTC, nlopin commented on js/ternary-operator/index.md
> +Где A — оператор, B — первое выражение, C — второе выражение.
разве А оператор, а не условие?

2021-11-10 07:10 UTC, nlopin commented on js/ternary-operator/index.md
> +Если первый аргумент A истинно (true) — оператор вернёт первое выражение B, в ином случае (false) он вернёт второе выражение C.
Так как тернарный оператор — это оператор, то он работает с операндами, которых ему нужно три. (бинарным операторам, например, оператору сложения `+` нужно два операнда, чтобы вычислить результат 5+3)

```suggestion
Если первый операнд A вычисляется в истинное выражение (`true`), то оператор вернёт выражение B, если в `false` — вернёт выражение C.
```

2021-11-10 07:10 UTC, nlopin commented on js/ternary-operator/index.md
> +По механике работы оператор похож на конструкцию [`if...else`](/js/if-else), но позволяет писать меньше кода или записать результат сравнения в переменную. Например:
```suggestion
По механике работы оператор похож на инструкцию [`if...else`](/js/if-else), но позволяет писать меньше кода или записать результат сравнения в переменную. Например:
```

2021-11-10 07:10 UTC, nlopin commented on js/ternary-operator/index.md
> +...Можно записать как:
```suggestion
Можно заменить тернарным оператором и уменьшить код:
```

2021-11-14 18:45 UTC, Ginger-Raccoon commented
Прошу прощения что так затянул, вышла не самая нелегкая неделя, обещаю до конца недельки исправиться :raised_hands:

2021-11-14 19:22 UTC, Ginger-Raccoon commented on js/ternary-operator/index.md
> +...Можно записать как:
Круто, так информативнее, разве что я бы предложил не "уменьшить код" а "сократить код", мне кажется так будет лучше читаться, как счиатешь?

2021-11-16 06:12 UTC, nlopin commented
No pressure, ты уже сделал много и ничего нам не должен 👍 

Если совсем не будет получаться, то дай нам знать — дополируем сами

2021-11-23 22:08 UTC, Ginger-Raccoon commented
Накинул немного правок, осталось поработать над примерами

2021-11-24 12:59 UTC, Ginger-Raccoon commented
Готовченко!

2021-11-24 15:11 UTC, bespoyasov approved these changes
Отличная статья 👍

2021-11-24 15:11 UTC, bespoyasov commented on js/ternary-operator/index.md
> +  💡 Раз результат работы тернарного оператора можно записать в переменную, то смело делаем вывод, тернарный оператор - выражение. Подробнее можно прочитать [тут](/js/expressions-vs-statements)
```suggestion
  💡 Раз результат работы тернарного оператора можно записать в переменную, то смело делаем вывод, тернарный оператор — выражение. Подробнее о разнице между выражениями и инструкциями можно прочитать [тут](/js/expressions-vs-statements).
```

2021-11-24 15:11 UTC, bespoyasov commented on js/ternary-operator/index.md
> +В данном примере сначала будет проверяться второе условие `num === 10 ? 'Число равно 10' : 'Число меньше 10'`. В случае если `num !=== 10` результатом вычисления станет `'Число меньше 10'` и первое у
```suggestion
В данном примере сначала будет проверяться второе условие `num === 10 ? 'Число равно 10' : 'Число меньше 10'`. В случае если `num !== 10` результатом вычисления станет `'Число меньше 10'` и первое условие приобретёт вид `num > 10 ? 'Число больше 10' : 'Число меньше 10'`
```

2021-11-24 15:11 UTC, bespoyasov commented on js/ternary-operator/index.md
> +  <summary>Ассоциативность справа</summary>
```suggestion
  <summary>Такой порядок проверки — это следствие ассоциативности справа.</summary>
```

2021-11-24 15:11 UTC, bespoyasov commented on js/ternary-operator/index.md
> +// Все еще не страшно? Тогда приправим все это функциями
Пример — огонь 😃

2021-11-24 18:05 UTC, tachisis approved these changes
Апрув на изменения в словаре

2021-12-22 17:27 UTC, nlopin commented on js/ternary-operator/index.md
> +В данном примере сначала будет проверяться второе условие `num === 10 ? 'Число равно 10' : 'Число меньше 10'`. В случае если `num !== 10` результатом вычисления станет `'Число меньше 10'` и первое ус
Можешь дать пруф вот тут? [спека](https://262.ecma-international.org/#sec-conditional-operator) говорит, что тернарник работает как `if`. Сначала вычисляется условие, потом одна из веток. То есть ничего не применяется до проверки условия.

Текущее описание подразумевает, что сначала будет проверка на равенство, и только затем — `num > 10`, кажется это неверно, потому что вот такой код должен выдавать `Число равно 10`, но он выдает `Число больше 10`:

```js
num === 10 ? 'Число больше 10' : (num === 10 ? 'Число равно 10' : 'Число меньше 10')
```

2021-12-22 18:06 UTC, nlopin approved these changes
Извини, что затянул с мёржем. Льем в прод 👍

2021-12-22 18:38 UTC, merged