Добавляет доку про <cite>
doka-guide/content pull request #2301
Opened 2021-11-03 23:27 UTC by xpleesid

Fix #561

2021-11-04 10:08 UTC, pepelsbey approved these changes
Спасибо за доку! Получилось понятно и интересно :) Есть идеи, как улучшить.

2021-11-04 10:08 UTC, pepelsbey commented on html/cite/demos/good/index.html
> +    — За актуальными новостями можно следить на сайте <cite>https://stephenking.com/upcoming/</cite>.
```suggestion
    — За актуальными новостями можно следить на сайте
    <cite>
      <a href="https://stephenking.com/upcoming/">Стивена Кинга</a>
    </cite>.
```

2021-11-04 10:08 UTC, pepelsbey commented on html/cite/index.md
> +`<cite>` не стоит использовать для оформления самих цитат, для этого подойдёт тег [`q`](/html/q).
```suggestion
`<cite>` не стоит использовать для оформления самих цитат, для этого подойдёт тег [`<q>`](/html/q).
```

2021-11-04 10:08 UTC, pepelsbey commented on html/cite/index.md
> +```
````suggestion
Название произведения:

```html
<p>
  — Только что дочитал цикл <cite>Тёмная башня</cite>.
  Я впечатлён! Где можно узнать о выходе новых книг?
</p>
```

Ссылка на сайт:

```html
<p>
  — За актуальными новостями можно следить на сайте
  <cite>
    <a href="https://stephenking.com/upcoming/">
      Стивена Кинга
    </a>
  </cite>.
</p>
```

Название картины:

```html
<p>
  — Спасибо! Я так впечатлился, что хочу подарить ему
  оригинал <cite>Утра в сосновом бору</cite>.
  Вы знаете, когда у него день рождения?
</p>
```

Ссылка на раздел:

```html
<p>
  — Вы можете найти ответ на том же сайте в разделе <cite>FAQ</cite>.
</p>
```
````

2021-11-04 10:08 UTC, pepelsbey commented on html/cite/index.md
> +```
````suggestion
Автор не должен указываться как источник, нужно приводить ссылку на конкретный материал:

```html
<p>
  — Только что дочитал цикл «Тёмная башня»
  за авторством <cite>Стивена Кинга</cite>.
</p>
```

Для цитирования подойдет тег `<q>`:

```html
<p>
  — Фраза <cite>Смерть, Стрелок, но не твоя</cite>
  навсегда засела у меня в памяти.
</p>
```
````

2021-11-04 10:08 UTC, pepelsbey commented on html/cite/demos/basic/index.html
> +    Из  всех произведений Стивена Кинга мне больше всего нравится цикл <cite>Тёмная башня</cite>.
```suggestion
    Из всех произведений Стивена Кинга мне больше всего нравится цикл <cite>Тёмная башня</cite>.
```

2021-11-04 10:08 UTC, pepelsbey requested changes
Ой, я имел в виду

2021-11-05 11:41 UTC, pepelsbey approved these changes

2021-11-05 14:34 UTC, solarrust approved these changes
Спасибо за классную доку =)

2021-11-07 21:02 UTC, merged