Добавляет статью про conic-gradient
doka-guide/content pull request #2306
Opened 2021-11-04 08:15 UTC by Mitorun

Fix #675

2021-11-04 10:48 UTC, solarrust commented
Ура! Поздравляю с первым PR'ом! 
Пошла читать =)

2021-11-04 11:53 UTC, solarrust reviewed
Немного порефакторила демки, убрала лишнее, поправила отступы. 

Сама статья хорошая получилась, спасибо большое за неё!

Оставила пару предложений с исправлениями. Под теми, с которыми ты согласен, можно нажать кнопку «Add suggestion to batch», а потом тут же, в интерфейсе залить всё одним коммитом.

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/index.md
> +Для более простого создания повторяющихся конических градиентов существует функция `repeating-conic-gradient()`.
Я бы вынесла это в блок «Как пишется» и немного развернула объяснение. По аналогии с [повторяющимся линейным градиентом](https://doka.guide/css/linear-gradient/#povtoryayushchiysya-gradient).

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +<iframe title="Цветовой круг" src="demos/color-circle/" height="390"></iframe>
```suggestion
<iframe title="Цветовой круг" src="../demos/color-circle/" height="390"></iframe>
```

Практика лежит в отдельной папке, путь до демки будет чуть длиннее

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +<iframe title="Круговая диаграмма" src="demos/pie-chart/" height="390"></iframe>
```suggestion
<iframe title="Круговая диаграмма" src="../demos/pie-chart/" height="390"></iframe>
```

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +<iframe title="Пирамида сверху" src="demos/pyramid/" height="390"></iframe>
```suggestion
<iframe title="Пирамида сверху" src="../demos/pyramid/" height="390"></iframe>
```

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +🛠 В комбинации со свойством `background-size` можно создавать различные повторяющиеся паттерны, например сделать шахматную доску:
```suggestion
🛠 В комбинации со свойством [`background-size`](/css/background-size) можно создавать различные повторяющиеся паттерны, например сделать шахматную доску:
```

Хорошо добавлять ссылки на другие статьи Доки. Вдруг читатель ещё не знает про это свойство?

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +<iframe title="Шахматные клетки" src="demos/chess-board/" height="390"></iframe>
```suggestion
<iframe title="Шахматные клетки" src="../demos/chess-board/" height="390"></iframe>
```

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +🛠 Этот рисунок солнца состоит из всего-лишь одного элемента, к которому применены сразу и радиальный и конический градиенты:
```suggestion
🛠 Этот рисунок солнца состоит из всего-лишь одного элемента, к которому применены сразу и [радиальный](/css/radial-gradient) и конический градиенты:
```

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +<iframe title="Солнце с лучами" src="demos/sun/" height="390"></iframe>
```suggestion
<iframe title="Солнце с лучами" src="../demos/sun/" height="390"></iframe>
```

2021-11-04 11:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +  background: radial-gradient(yellow 5%, gold 31% 32%, transparent 32.5% 50%, lightskyblue 70%),
@pepelsbey нужен твой намётанный глаз чтобы красиво отформатировать этот кусочек 🙏

2021-11-04 11:59 UTC, Mitorun commented on css/conic-gradient/index.md
> +Для более простого создания повторяющихся конических градиентов существует функция `repeating-conic-gradient()`.
Для `repeating-conic-gradient()` стоит сделать свою отдельную статью (а также для `repeating-linear/radial-gradient()`). А в этой статье мне кажется уместным именно такое упоминание этого свойства, а в будущем сделать его ссылкой на полноценную статью.

2021-11-04 12:13 UTC, Mitorun commented on css/conic-gradient/practice/mitorun.md
> +  background: radial-gradient(yellow 5%, gold 31% 32%, transparent 32.5% 50%, lightskyblue 70%),
Имеется ввиду как красивей цвета в свойстве `background` расположить? Я у себя такие длинные свойства делаю в одну строку, а код переносится (вместо появления горизонтального скролла). Ну а на доке другой подход, для таких случаев нужно выбрать свои правила. Можно в одну строку, можно каждый цвет с новой строки (мне кажется это перебор), я выбрал средний вариант и перенес второй градиент на новую строку. Как лучше сделать не мне решать.

```css
.sun {
  background: radial-gradient(yellow 5%, gold 31% 32%, transparent 32.5% 50%, lightskyblue 70%), repeating-conic-gradient(yellow 0% 1%, transparent 4% 6%, yellow 9% 10%);
}
```

2021-11-04 12:22 UTC, Mitorun commented
> «Add suggestion to batch», а потом тут же, в интерфейсе залить всё одним коммитом.

Правки с принял с «Add suggestion to batch», а вот как залить коммитом не знаю(

2021-11-04 12:29 UTC, Mitorun commented on css/conic-gradient/practice/mitorun.md
> +<iframe title="Цветовой круг" src="demos/color-circle/" height="390"></iframe>
Боже, почему я только сейчас догадался, что можно было просто посмотреть как оформлены файлы в других статьях доки))) Сэкономил бы пару часов и нервов

2021-11-04 12:51 UTC, solarrust commented on css/conic-gradient/index.md
> +Для более простого создания повторяющихся конических градиентов существует функция `repeating-conic-gradient()`.
Но пока отдельной статьи нет можно дать хотя бы короткую справку и пример использования. Когда в планах будет отдельная статья можно будет взять этот кусочек за основу, развить его, а в этой статье подставить ссылку.

2021-11-04 12:53 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +  background: radial-gradient(yellow 5%, gold 31% 32%, transparent 32.5% 50%, lightskyblue 70%),
В одну строку точно не стоит располагать. Тогда на мобильном телефоне придётся долго-долго скроллить в бок чтобы увидеть весь пример кода. Надо подумать как расположить код компактно, чтобы ни на десктопе ни на мобильном не появлялось горизонтального скролла.

2021-11-04 12:54 UTC, solarrust commented
> > «Add suggestion to batch», а потом тут же, в интерфейсе залить всё одним коммитом.
> 
> Правки с принял с «Add suggestion to batch», а вот как залить коммитом не знаю(

![CleanShot 2021-11-04 at 15 50 18](https://user-images.githubusercontent.com/13676514/140316761-41ebba8b-4a74-4ef0-bb0e-1fc805cbf51f.png)

Вверху появляется кнопка «Commit suggestions». Нажимаем на неё → меняем комментарий → нажимает «Commit changes». Правки появляются в файлах =)

2021-11-04 12:59 UTC, Mitorun commented on css/conic-gradient/index.md
> +Для более простого создания повторяющихся конических градиентов существует функция `repeating-conic-gradient()`.
Ну а зачем откладывать, возьмусь за написание статей про `repeating-X-gradient`)
Описывать в одном свойстве другое - неправильно как-то.

2021-11-04 13:01 UTC, solarrust commented on css/conic-gradient/index.md
> +Для более простого создания повторяющихся конических градиентов существует функция `repeating-conic-gradient()`.
Если чувствуешь в себе силы и желание написать и эти статьи тоже — я буду счастлива и благодарна безмерно 🖤 Тогда да, не будем городить временные решения и в ближайшее время напишем отдельные статьи. Поставь, пожалуйста, задачки =)

2021-11-04 13:14 UTC, Mitorun commented on css/conic-gradient/index.md
> +Для более простого создания повторяющихся конических градиентов существует функция `repeating-conic-gradient()`.
Возьмусь, теперь уже легче будет писать. Еще я бы хотел в будущем поделать статьи про теги <svg>.

2021-11-04 23:10 UTC, pepelsbey commented on css/conic-gradient/practice/mitorun.md
> +    repeating-conic-gradient(yellow 0% 1%, transparent 4% 6%, yellow 9% 10%);
```suggestion
  background:
    radial-gradient(
      yellow 5%,
      gold 31% 32%,
      transparent 32.5% 50%,
      lightskyblue 70%
    ),
    repeating-conic-gradient(
      yellow 0% 1%,
      transparent 4% 6%,
      yellow 9% 10%
    );
```

Я бы оформил все примеры кода в таком стиле для лучше читаемости, причём не только в примерах, но и в самих демках. Читатели скажут вам спасибо :)

2021-11-05 05:20 UTC, Mitorun commented on css/conic-gradient/practice/mitorun.md
> +    repeating-conic-gradient(yellow 0% 1%, transparent 4% 6%, yellow 9% 10%);
Демки не минифицируются и не форматируются? Комментарии в коде там тоже остаются?  Про это нужно написать в руководстве.

2021-11-05 06:23 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +    repeating-conic-gradient(yellow 0% 1%, transparent 4% 6%, yellow 9% 10%);
Если посмотреть внимательно на статьи с демками, то можно увидеть ссылку "открыть демо в новом окне". Мы это сделали чтобы те, кому интересно могли открыть пример и его код и посмотреть внутри. Поэтому код демок никак не минифицируется, не обфусцируется, не меняется. Чтобы он оставался человекочитабельным.

2021-11-05 06:59 UTC, Mitorun commented on css/conic-gradient/practice/mitorun.md
> +    repeating-conic-gradient(yellow 0% 1%, transparent 4% 6%, yellow 9% 10%);
Кстати на MDN немного более компактное оформление кода:
```css
{
   background: **repeating-conic-gradient(**
    from 3deg at 25% 25%,
    hsl(200, 100%, 50%) 0deg 15deg,
    hsl(200, 100%, 60%) 10deg 30deg**);**
}
```
Может так будет лучше делать или название функции и закрывающие скобки всегда переносить на новую строку?

2021-11-06 09:33 UTC, solarrust reviewed
Ещё чуть-чуть предложений по улучшению. Почти идеально ☺️

2021-11-06 09:33 UTC, solarrust commented on css/conic-gradient/index.md
> +description: "Функция CSS конический градиент создаёт фоновое изображение из цветовых переходов, повёрнутых вокруг центральной точки. Формы записи и примеры использования функции."
```suggestion
description: "CSS-функция создаёт конический градиент — фоновое изображение из цветовых переходов, повёрнутых вокруг центральной точки. Формы записи и примеры использования функции."
```

2021-11-06 09:33 UTC, solarrust commented on css/conic-gradient/index.md
> +
Давай сюда добавим блок кода с полным синтаксисом функции, где используются упомянутые в тексте конструкции. Быстро сложно представить, в каком месте их ставить. А так будет наглядно

2021-11-06 09:33 UTC, solarrust commented on css/conic-gradient/index.md
> +Можно указывать любое количество цветов в любом доступном формате. Если цвета просто перечислять через запятую, то они равномерно распределятся по кругу, плавно переходя один в другой. Можно задать с
```suggestion
Можно указывать любое количество цветов в любом [доступном формате](/css/web-colors). Если цвета просто перечислять через запятую, то они равномерно распределятся по кругу, плавно переходя один в другой. Можно задать свои границы расположения цветов с помощью тех же единиц измерения, что и для задания начального угла градиента, плюс ещё используется значение в процентах. Например в `conic-gradient(white, grey 25%, black)` середина серого цвета будет на 25%.
```

2021-11-06 09:33 UTC, solarrust commented on css/conic-gradient/index.md
> +
Тут очень хочется наглядный пример чтобы понять в чём разница между разными средними точками смешения цвета.

2021-11-06 09:33 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +}
```suggestion
  background: 
    radial-gradient(
      yellow 5%, 
      gold 31% 32%, 
      transparent 32.5% 50%, 
      lightskyblue 70%
    ),
    conic-gradient(
      transparent 3%, 
      yellow 5% 8%, 
      transparent 10% 13%, 
      yellow 15% 17%, 
      transparent 20% 23%, 
      yellow 25% 28%, 
      transparent 30% 33%, 
      yellow 35% 38%, 
      transparent 40% 43%, 
      yellow 45% 48%, 
      transparent 50% 53%, 
      yellow 55% 58%, 
      transparent 60% 63%, 
      yellow 65% 68%, 
      transparent 70% 73%, 
      yellow 75% 78%, 
      transparent 80% 83%, 
      yellow 85% 88%, 
      transparent 90% 93%, 
      yellow 95% 98%, 
      transparent
    );
}
```

2021-11-06 09:33 UTC, solarrust commented on css/conic-gradient/practice/mitorun.md
> +}
Отформатировала по аналогии с примером ниже. Ух, жесть портянка получилось =) @pepelsbey давай придумаем, как это можно пристойно показать?

2021-11-06 09:54 UTC, Mitorun commented on css/conic-gradient/index.md
> +
Я хочу сюда добавить иллюстрации, которые наглядно покажут расположение углов и расположение центральной точки. А также для центральной точки цвета и центра перехода (это про текст далее). Ну и блок с примером кода также можно добавить. Наброски уже сделал, но нужно это получше продумать. Предлагаю пока выпустить статью как есть, а потом я подготовлю эти дополнения вместе с тремя новыми статьями.

2021-11-06 09:58 UTC, Mitorun commented on css/conic-gradient/practice/mitorun.md
> +}
В данном конкретном примере не так важно точно показать запись для каждого цвета, главное суть передать как это сделано, поэтому можно и скрыть как-нибудь (в скролл).

2021-11-08 11:35 UTC, skorobaeus approved these changes
Демки — огонь!

2021-11-09 19:35 UTC, solarrust commented on css/conic-gradient/index.md
> +
Завела ишью #2364, чтобы не забыть про эти дополнения к статье.

2021-11-09 19:36 UTC, solarrust approved these changes
Супер, мне всё нравится! 🙌
Буду ждать следующие статьи =)

2021-11-10 11:32 UTC, pepelsbey requested changes
Получается отличная дока с интересной практикой :)

Предложил несколько улучшений.

2021-11-10 11:32 UTC, pepelsbey commented on css/conic-gradient/index.md
> +По умолчанию начало градиента (первый цвет в списке) будет проходить линией через центральную и верхнюю точки элемента (как стрелки круговых часов в 12:00) и далее цвета будут следовать по кругу по ч
````suggestion
По умолчанию начало градиента (первый цвет в списке) будет проходить линией через центральную и верхнюю точки элемента (как стрелки круговых часов в 12:00) и далее цвета будут следовать по кругу по часовой стрелке.

Компактная запись `white, black` на самом деле скрывает несколько умолчаний: начальный угол, положение центра и координаты цветов: 

```css
.element {
  background-image: conic-gradient(from 0turn at 50% 50%, white 0%, black 100%);
}
```
````

Я бы здесь развернул описание.

2021-11-10 11:32 UTC, pepelsbey commented on css/conic-gradient/index.md
> +}
```suggestion
.element-2 {
  background-image: conic-gradient(
    from 45deg at 25% center,
    white,
    #d6f78a 25%,
    0.45turn,
    rgb(127, 235, 235)
    210deg 5.9rad,
    hsl(278, 81%, 79%)
    361grad
  );
}
```

Так будет проще читать

2021-11-10 11:32 UTC, pepelsbey commented on css/conic-gradient/practice/mitorun.md
> +  background-image: conic-gradient(peru 25%, cornsilk 25% 50%, peru 50% 75%, cornsilk 75%);
```suggestion
  background-image: conic-gradient(
    peru 25%,
    cornsilk 25% 50%,
    peru 50% 75%,
    cornsilk 75%
  );
```

2021-11-10 11:32 UTC, pepelsbey commented on css/conic-gradient/practice/mitorun.md
> +  background-image: conic-gradient(from -0.125turn, #bbb 0.25turn, #999 0.25turn 0.5turn, #bbb 0.5turn 0.75turn, #eee 0.75turn);
```suggestion
  background-image: conic-gradient(
    from -0.125turn,
    #bbb 0.25turn,
    #999 0.25turn 0.5turn,
    #bbb 0.5turn 0.75turn,
    #eee 0.75turn
  );
```

2021-11-10 11:32 UTC, pepelsbey commented on css/conic-gradient/practice/mitorun.md
> +  background-image: conic-gradient(coral 27deg, palegreen 27deg 150deg, skyblue 150deg);
```suggestion
  background-image: conic-gradient(
    coral 27deg,
    palegreen 27deg 150deg,
    skyblue 150deg
  );
```

2021-11-10 11:32 UTC, pepelsbey commented on css/conic-gradient/practice/mitorun.md
> +  background: conic-gradient(red, orange, yellow, green, blue, purple, red);
```suggestion
  background: conic-gradient(
    red,
    orange,
    yellow,
    green,
    blue,
    purple,
    red
  );
```

2021-11-10 12:03 UTC, Mitorun commented on css/conic-gradient/index.md
> +По умолчанию начало градиента (первый цвет в списке) будет проходить линией через центральную и верхнюю точки элемента (как стрелки круговых часов в 12:00) и далее цвета будут следовать по кругу по ч
Фраза "на самом деле скрывает несколько умолчаний" выглядит неудачной, она сбивает с толку что "тут что-то скрывается и на самом деле все не так как кажется".

Также может будет лучше записать "(как стрелки круглых механических часов в 12:00)", не знаю как такие часы правильнее назвать.

2021-11-13 08:32 UTC, pepelsbey commented on css/conic-gradient/index.md
> +По умолчанию начало градиента (первый цвет в списке) будет проходить линией через центральную и верхнюю точки элемента (как стрелки круговых часов в 12:00) и далее цвета будут следовать по кругу по ч
@Mitorun обновил предложение, убрал детектив )

2021-11-15 13:56 UTC, merged