Добавляет статью про подключение стилей
doka-guide/content pull request #2308
Opened 2021-11-04 11:52 UTC by kanishev

Fix #2279

2021-11-04 12:40 UTC, solarrust reviewed
Спасибо большое за статью! Отличное начало 👍

Совершила первый подход к ревью. Оставила несколько комментариев по улучшению. 

@pepelsbey приходи поревьюить!

2021-11-04 12:40 UTC, solarrust commented on .yaspeller.json
> +  "excludeFiles": ["people/**/index.md"],
Эти правки не относятся к статье. Было бы круто их убрать из текущего ПРа. Если они и правда нужны лучше прислать их отдельно.

2021-11-04 12:40 UTC, solarrust commented on css/installation/demos/vars/index.html
> +    <title>Дока</title>
Демки у нас принято именовать в формате: «Название демки — статья, к которой она относится — Дока».

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +  - doka
```suggestion
  - article
```

Формат доки это небольшие предельно атомарные статьи про конкретные теги, свойства или значения.
Для этого документа больше подойдёт формат статьи (article)

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Стилизовать страницу можно разными способами: определить стили глобально, разместив их в HTML, подключить внешний css файл, определить стили с помощью JavaScript, либо стилизовать элемент отдельно, и
Формально стилизовать страницу можно только одним способом: при помощи CSS. А вот совместить этот самый CSS с разметкой можно разными способами.

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Стилизовать страницу можно разными способами: определить стили глобально, разместив их в HTML, подключить внешний css файл, определить стили с помощью JavaScript, либо стилизовать элемент отдельно, и
```suggestion
Стилизовать страницу можно разными способами: определить стили глобально, разместив их в HTML, подключить внешний CSS-файл, определить стили с помощью JavaScript, либо стилизовать элемент отдельно, используя внутренние стили.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Среди разработчиков хорошим тоном считается писать стили в отдельном файле и затем подключать их с помощью тега «[link](/html/link)». А вот внутренние стили стараются избегать, хотя их применение так
```suggestion
Среди разработчиков хорошим тоном считается писать стили в отдельном файле и затем подключать их с помощью тега [`<link>`](/html/link). А вот внутренних стилей стараются избегать, хотя их применение также бывает полезно.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Обо всём по порядку.
```suggestion
```

Кмк,  это лишняя фраза =)

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +### Способ 1. Подключение стилей из внешнего файла.
```suggestion
### Подключение стилей из внешнего файла
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +При использовании такого подхода описание CSS свойств производится в отдельном файле с расширением `.css`. Для связывания документа с этим файлом применяется тег `<link>`, который помещается в `<head
```suggestion
При использовании такого подхода описание CSS-свойств производится в отдельном файле с расширением _.css_. Для связывания документа с этим файлом применяется тег `<link>`, который помещается в [`<head>`](/html/head):
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +    />
Эти строки не имеют явного отношения к тому, о чём идёт речь в тексте. Но их отсутствие сделает блок кода легче =)

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +    <link rel="stylesheet" href="/assets/styles/main.css" />
```suggestion
    <link rel="stylesheet" href="main.css">
```

Я бы предложила максимально упростить путь до файла. Пример кода от этого не станет менее наглядным

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +    <link rel="stylesheet" href="/assets/styles/main.css" />
И да, мы не закрываем одиночные теги )

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Атрибуты `rel="stylesheet"` и `type="text/css"` указывают, что данный файл является таблицей стиля в формате CSS. В качестве значения `href` указывается путь к CSS-файлу. Он может быть задан как отно
Даже в вашем примере нет `type="text/css"` )

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Таким образом можно подключать таблицу стилей, которая находится на другом сайте. В примере выше мы подключаем шрифт `Roboto` с сайта Google Fonts.
```suggestion
Таким образом можно подключать таблицу стилей, которая находится на другом сайте. В примере выше мы подключаем шрифт Roboto с сайта [Google Fonts](https://fonts.google.com).
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +### Преимущества данного подхода:
```suggestion
### Преимущества данного подхода
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +- Возможность использования одного `css` файла для стилизации на нескольких страницах. При изменении стиля в одном единственном файле, стиль автоматически применяется ко всем страницам, где есть на н
```suggestion
- Возможность использования одного CSS-файла для стилизации на нескольких страницах. При изменении стиля в одном единственном файле, стиль автоматически применяется ко всем страницам, где есть на него ссылка.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +- Внешние стили позволяют гибко использовать псевдоклассы и псевдоэлементы.К примеру разработчик может задать интерактивные состояния отдельно выбранным кнопкам, стилизовать каждый чётный элемент спи
```suggestion
- Внешние стили позволяют гибко использовать [псевдоклассы](/css/pseudoclasses) и [псевдоэлементы](/css/pseudoelements). К примеру разработчик может задать интерактивные состояния отдельно выбранным кнопкам, стилизовать каждый чётный элемент списка или выполнить другие задачи.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Внешний CSS также открывает доступ к «[кастомным](/css/custom-properties)» свойствам.
```suggestion
Внешний CSS также открывает доступ к [кастомным свойствам](/css/custom-properties).
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +<iframe title="Пример использования var" src="demos/vars/" height="375" ></iframe>
```suggestion
<iframe title="Пример использования var" src="demos/vars/" height="375"></iframe>
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +### Преимущества данного подхода:
Я бы предложила не делать эту строку заголовком. В данный момент она будет в боковом меню на одном уровне с заголовками способов подключения. Кажется, это контринтуитивно

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +### Преимущества данного подхода:
Может быть выделим блок с преимуществами так?

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +- Поскольку код добавляется непосредственно в HTML файл, браузеру нет необходимости загружать сторонние файлы, что позволяет отрисовать страницу быстрее.
```suggestion
- Поскольку код добавляется непосредственно в HTML-файл, браузеру нет необходимости загружать сторонние файлы, что позволяет отрисовать страницу быстрее.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +- Глобальные стили работают изолированно, и применяются непосредственно к данной странице. В таком подходе можно смело использовать классы или идентификаторы, не задумываясь о проблемах каскада.
```suggestion
- Глобальные стили работают изолированно, и применяются непосредственно к данной странице. В таком подходе можно смело использовать классы или идентификаторы, не задумываясь о проблемах [каскада](/css/cascade).
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +- С каждым новым правилом вес HTML файла будет увеличиваться. Это приводит к росту потребляемого трафика и уменьшению скорости загрузки страницы.
```suggestion
- С каждым новым правилом вес HTML-файла будет увеличиваться. Это приводит к росту потребляемого трафика и уменьшению скорости загрузки страницы.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +При использовании `inline стилей` мы зачастую будем вынуждены добавлять встроенный стиль к каждому элементу, который необходимо стилизовать. В том случае, если элементов на странице много, прописыват
```suggestion
При использовании инлайн-стилей мы зачастую будем вынуждены добавлять встроенный стиль к каждому элементу, который необходимо стилизовать. В том случае, если элементов на странице много, прописывать стили вручную станет неудобно. К тому же это нарушает принцип «разделения содержимого и оформления».
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +### Восприятие кода.
```suggestion
### Восприятие кода
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Если писать стили внутри атрибута `style`, то HTML становится трудночитаемым. Логическая структура исчезает и стили размываются по всему коду.И чем крупнее проект, тем сложнее управлять стилизацией.
```suggestion
Если писать стили внутри атрибута `style`, то HTML становится трудночитаемым. Логическая структура исчезает и стили размываются по всему коду. И чем крупнее проект, тем сложнее управлять стилизацией.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +</html>
```suggestion
<h1 style="сolor: yellow; margin: 10px 20px 15px 10px;">Заголовок</h1>
<div style="border: 1px solid red; max-widht: 500px; margin: auto">
  <p>У моей кошки <span style="color: lightblue;">светло синие</span> глаза.</p>
</div>
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +</html>
```suggestion
<h1 class="title">Заголовок</h1>
<div class="wrapper">
  <p>У моей кошки <span class="eyes">светло синие</span> глаза.</p>
</div>
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +### Способ 4. Импорт CSS.
```suggestion
### Импорт CSS
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Основное отличие данного метода в том, что `импорт` позволяет подключить одну таблицу стилей в другую.
```suggestion
Основное отличие данного метода в том, что импорт позволяет подключить одну таблицу стилей в другую.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +В таком случае содержимое стороннего файла импортируется с помощью команды `@import`.
```suggestion
В таком случае содержимое стороннего файла импортируется с помощью команды [`@import`](/css/import).
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Чтобы подключить один внешний файл таблиц стилей к другому, в последнем необходимо объявить команду `@import` и указать `URL` путь к этому файлу.
```suggestion
Чтобы подключить один внешний файл таблиц стилей к другому, в последнем необходимо объявить команду `@import` и указать URL-путь к этому файлу.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +После ключевого слова @import указывается путь к стилевому файлу одним из двух приведённых способов — с помощью `URL` либо без него.
```suggestion
После ключевого слова `@import` указывается путь к стилевому файлу одним из двух приведённых способов — с помощью функции `url()` либо без неё.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +</html>
```suggestion
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Дока</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap');
      h1 {
        font-family: "Roboto", sans-serif;
        color: green;
      }
    </style>
  <body>
    <h1 class="title">Заголовок</h1>
    <div class="wrapper">
      <p>У моей кошки <span class="eyes">светло синие</span> глаза.</p>
    </div>
  </body>
</html>
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +По мере того как ваш проект растёт в размерах и сложности, поддержка CSS файлов, может стать трудной. `@import` помогает разбить массивную таблицу на более понятные и логичные части.
```suggestion
По мере того как ваш проект растёт в размерах и сложности, поддержка CSS-файлов, может стать трудной. `@import` помогает разбить массивную таблицу на более понятные и логичные части.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +Чтобы проиллюстрировать это, достаточно сделать ссылку на CSS-файл через тег `<link>` , например:
```suggestion
Чтобы проиллюстрировать это, достаточно сделать ссылку на CSS-файл через тег `<link>`, например:
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +<link href="/styles/main.css" rel="stylesheet" type="text/css" />
```suggestion
<link href="/styles/main.css" rel="stylesheet" type="text/css">
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/index.md
> +- При нормальных обстоятельствах загрузка файлов CSS с использованием метода @import может значительно увеличить время загрузки страницы, поскольку css-файлы ссылаются один за другим. Как правило `@i
```suggestion
- При нормальных обстоятельствах загрузка файлов CSS с использованием директивы `@import` может значительно увеличить время загрузки страницы, поскольку CSS-файлы ссылаются один за другим. Как правило, `@import` увеличивает количество соединений с сервером, поскольку файл, на который идёт ссылка, также нужно скачать и проанализировать.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/practice/kanishev.md
> +🛠 Одна из самых распространённых областей применений `inline-стилей` - email рассылки.
```suggestion
🛠 Одна из самых распространённых областей применений инлайн-стилей — email-рассылки.
```

2021-11-04 12:40 UTC, solarrust commented on css/installation/practice/kanishev.md
> +Вот так может выглядеть обычная html-разметка при вёрстке email рассылки:
```suggestion
Вот так может выглядеть HTML-разметка при вёрстке email-рассылки:
```

2021-11-05 15:15 UTC, kanishev commented
Спасибо за правки. Впредь буду знать про нюансы. Не совсем понимаю что мне теперь сделать. Зарезолвить правки? Или исправить и запушить снова?

2021-11-06 09:51 UTC, solarrust commented
> Спасибо за правки. Впредь буду знать про нюансы. Не совсем понимаю что мне теперь сделать. Зарезолвить правки? Или исправить и запушить снова?

Те комментарии, по которым правки внесены, можно зарезолвить. Если с какими-то из них не согласен можем пообсуждать.

2021-11-06 13:02 UTC, kanishev commented
Сделал несколько исправлений по вашим замечаниям. Так думаю будет лучше :)

2021-11-06 13:40 UTC, pepelsbey requested changes
Привет! Спасибо :) Первый подход: немного поформатировал и поправил.

2021-11-06 13:40 UTC, pepelsbey commented on css/installation/demos/vars/style.css
> +  --blue-lighten: #64b5f6
```suggestion
  --blue-lighten: #64b5f6;
```

2021-11-06 13:40 UTC, pepelsbey commented on css/installation/index.md
> +</html>
```suggestion
<head>
  <link rel="stylesheet" href="main.css">
</head>
```

Атрибут `type="text/css"` довольно бесполезен, а пример можно сфокусировать ещё, чтобы не было лишнего кода. Подключаем в шапке? Шапка и подключение :)

2021-11-06 13:40 UTC, pepelsbey commented on css/installation/index.md
> +Атрибуты `rel="stylesheet"` и `type="text/css"` указывают, что данный файл является таблицей стиля в формате CSS. В качестве значения `href` указывается путь к CSS-файлу. Он может быть задан как отно
```suggestion
Атрибуты `rel="stylesheet"` указывает, что данный файл является таблицей стиля в формате CSS. В качестве значения `href` указывается путь к CSS-файлу. Он может быть задан как относительно, так и абсолютно.
```

2021-11-06 13:40 UTC, pepelsbey commented on css/installation/index.md
> +```
````suggestion
В данном случае CSS-свойства описываются в самом HTML-документе внутри тега [`<style>`](/html/style) и располагаются в шапке страницы:

```html
<head>
  <style>
    h1 {
      color: tomato;
    }

    p {
      font-size: 24px;
    }
  </style>
</head>
```
````

2021-11-07 21:33 UTC, pepelsbey requested changes
У вас получилось хорошее введение в способы подключать и писать стили, но кажется тут нужно добавить небольшую прививку реальности, чтобы читатели не наделали ошибок и не ухудшили перфоманс.

Главные вопросы есть к разделу «Импорт CSS». К сожалению, импорты — это антипаттерн. То есть использовать импорты в коде на продакшене имеет мало смысла:

- Если указывать их в разметке, то лучше использовать `<link>` (у него больше возможностей, об этом ниже)
- Если указывать в уже подключённых стилях, браузер зря заблокирует отрисовку сайта, пока не загрузится.

Также я не очень понял вот эту часть:

> Кроме того, с использованием такого способа имеется возможность привязать внешние таблицы стилей к внутренней таблице стилей документа.

Вместо такого импорта разумнее будет подключить `<link>`, особенно потому, что в таком случае можно будет добавить дополнительные атрибуты, вроде `preload`.

Импорты имеют смысл только в рабочем окружении, а для продакшена такие файлы нужно собирать. Ровно так, как устроена платформа Доки:

- У нас есть [index.css](https://github.com/doka-guide/platform/blob/main/src/styles/index.css)
- Но потом в проде он превращается в [index-9fac2bf749.css](https://doka.guide/styles/index-9fac2bf749.css)

Было бы здорово переформулировать эту часть с учётом этих мыслей. Так статья станет гораздо полезнее и не придётся прятать важную информацию в блок «На практике», ведь его могут пропустить.

2021-11-08 06:46 UTC, kanishev commented
Мне кажется тогда лучше исключить раздел про "Импорты" в принципе, тем более уже есть отдельная статья про них. Насчет названия файлов - согласен

2021-11-08 07:49 UTC, solarrust commented
> Мне кажется тогда лучше исключить раздел про "Импорты" в принципе, тем более уже есть отдельная статья про них. Насчет названия файлов - согласен

Я бы не стала удалять этот раздел потому что без него статья будет не полной. Читатель ожидает, что увидит в статье все возможные способы подключения стилей, а мы оп и скрыли от него один из них. 

Можно не углубляться в технические подробности, а дать ссылку на статью про `@import`. В рамках статьи я бы рассмотрела _моральные_ стороны такого способа подключения =)

2021-11-08 11:00 UTC, skorobaeus commented on css/installation/demos/vars/index.html
> +    <p>Какой-нибудь важный текст</p>
Напишите сюда какую-нибудь приятную связную фразу. Так добрее <3

2021-11-08 11:03 UTC, skorobaeus commented on css/installation/demos/vars/index.html
> +    />
```suggestion
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap">
```

В демках не используется 100-ый вес. 400 для обычного текста и 500 для заголовков.

2021-11-08 11:04 UTC, skorobaeus commented on css/installation/demos/vars/style.css
> +  font-size: 50px;
```suggestion
  font-size: 30px;
  font-weight: 500;
```

2021-11-08 11:04 UTC, skorobaeus commented on css/installation/demos/vars/style.css
> +  font-weight: bold;
```suggestion
  font-size: 18px;
```

Жирный шрифт для параграфов лучше не надо.

2021-11-08 15:08 UTC, kanishev commented
> Привет! Большое спасибо за статью!
> 
> Я добавила несколько комментариев по шрифтам ✌
> 
> Мы стараемся делать демки простыми и наглядными, а разметку, стили и скрипты хранить в одном файле. Перенесите, пожалуйста, стили из style.css в тег `<style>` в index.html. Если нужно, шаблон демки можно подглядеть [в статье](https://github.com/doka-guide/content/blob/main/html/div/demos/div/index.html) про `<div>`, например.

Благодарю! Сделал несколько исправлений по вашим замечаниям. Так думаю будет лучше :)

2021-11-09 20:13 UTC, solarrust reviewed
Второй подход к редактуре. 

Предлагаю перенести блок про онлайн стили в конце статьи, чтобы блок «Почему инлайн-стили это плохо» шёл после него и не нарушал повествование.

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +При использовании такого подхода описание CSS-свойств производится в отдельном файле с расширением _.css_. Для связывания документа с этим файлом применяется тег `<link>`, который помещается в [`<hea
```suggestion
При использовании такого подхода описание CSS-свойств производится в отдельном файле с расширением _.css_. Такие стили ещё называют связанными.

Для связывания документа с этим файлом применяется тег `<link>`, который помещается в [`<head>`](/html/head):
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +Такие стили ещё называют связанными.
```suggestion
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +### Подключение стилей из внешнего файла
```suggestion
## Подключение стилей из внешнего файла
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +### Преимущества данного подхода
```suggestion
### Преимущества
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +  --grey-darken: #424242;
```suggestion
  --main-bg-color: #2196f3;
  --main-text: #000000;
  --grey-darken: #424242;
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +<iframe title="Пример использования var" src="demos/vars/" height="375"></iframe>
В примере нужно будет поменять код так, чтобы он совпадал с кодом в статье

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +### Подключение глобальных стилей
```suggestion
## Подключение глобальных стилей
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +**Преимущества данного подхода**:
```suggestion
### Преимущества
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +- Глобальные стили работают изолированно, и применяются непосредственно к данной странице. В таком подходе можно смело использовать классы или идентификаторы, не задумываясь о проблемах [каскада](/cs
```suggestion
- Глобальные стили работают изолированно и применяются непосредственно к странице, на которой прописаны. В таком подходе можно смело использовать классы или идентификаторы, не задумываясь о проблемах [каскада](/css/cascade).
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +### Подключение внутренних стилей
```suggestion
## Подключение внутренних стилей
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +Внутренние стили имеют наивысший приоритет, их нельзя переопределить с помощью селекторов по [идентификатору](/css/id-selector), [классу](/css/class-selector) или [тегу](/css/tag-selector) во внешнем
```suggestion
Внутренние стили имеют [наивысший приоритет](https://doka.guide/css/specificity/#atribut-style), их нельзя переопределить с помощью селекторов по [идентификатору](/css/id-selector), [классу](/css/class-selector) или [тегу](/css/tag-selector) во внешнем CSS. Единственный способ это сделать — добавить [`!important`](/css/important) к значению свойства. Но этот приём тоже считается плохой практикой.
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +Ещё одним недостатком встроенных стилей является невозможность определить и стилизовать «[псевдоклассы](/css/pseudoclasses)» и «[псевдоэлементы](/css/pseudoelements)» .
```suggestion
Ещё одним недостатком встроенных стилей является невозможность определить и стилизовать [псевдоклассы](/css/pseudoclasses) и [псевдоэлементы](/css/pseudoelements).
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +### Импорт CSS
```suggestion
## Импорт CSS
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +### Преимущества данного подхода:
```suggestion
### Преимущества
```

2021-11-09 20:13 UTC, solarrust commented on css/installation/index.md
> +### Недостатки:
```suggestion
### Недостатки
```

2021-11-10 13:05 UTC, solarrust reviewed
Ещё пара мелких правочек. 

@tachisis приглашаю тебя поревьюить 🙌

2021-11-10 13:05 UTC, solarrust commented on css/installation/demos/vars/index.html
> +    <title>Пример использования var — installation — Дока</title>
```suggestion
    <title>Пример использования кастомных стилей — Подключение стилей — Дока</title>
```

2021-11-10 13:05 UTC, solarrust commented on css/installation/index.md
> +### Недостатки:
```suggestion
### Недостатки
```

2021-11-10 13:05 UTC, solarrust commented on css/installation/index.md
> +### Преимущества данного подхода:
```suggestion
### Преимущества
```

2021-11-12 17:38 UTC, tachisis reviewed
Немного правочек и комментариев

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +По мере того как ваш проект растёт в размерах и сложности, поддержка CSS-файлов, может стать трудной. `@import` помогает разбить массивную таблицу на более понятные и логичные части.
```suggestion
По мере того как ваш проект растёт в размерах и сложности, поддержка CSS-файлов тоже усложняется. `@import` помогает разбить массивную таблицу стилей на более мелкие и понятные части.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Чтобы проиллюстрировать это, достаточно сделать ссылку на CSS-файл через тег `<link>`, например:
```suggestion
Посмотрим, как это делается. Даём ссылку на CSS-файл через тег `<link>`:
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Затем эта таблица стилей ссылается уже на несколько других вспомогательных таблиц:
```suggestion
Затем в _main.css_ импортируем несколько других CSS-файлов, _header.css_ для шапки сайта, _navbar.css_ для меню, и так далее:
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +- При нормальных обстоятельствах загрузка файлов CSS с использованием директивы `@import` может значительно увеличить время загрузки страницы, поскольку CSS-файлы ссылаются один за другим. Как правил
```suggestion
- Подключение CSS-файлов при помощи директивы `@import` может значительно увеличить время загрузки страницы. CSS-файлы подключаются один за другим, и для каждого устанавливается отдельное соединение с сервером, каждый файл нужно скачать и проанализировать.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +- При нормальных обстоятельствах загрузка файлов CSS с использованием директивы `@import` может значительно увеличить время загрузки страницы, поскольку CSS-файлы ссылаются один за другим. Как правил
Возможно, нужно дать пояснение, что с HTTP2 этой проблемы не будет? (Если это так, я не вдавалась в подробности).

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +- Данный способ не рекомендуется использовать, так как он не гарантирует последовательную загрузку файлов CSS.
```suggestion
- А еще этот способ не гарантирует последовательную загрузку файлов CSS.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +## Подключение внутренних стилей
```suggestion
## Инлайн-стили
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +## Подключение внутренних стилей
Я убираю слово «подключение», потому что формально это не подключение, как и в случае со встроенными стилями

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +В таком случае элементам на странице, которые необходимо стилизовать, добавляется атрибут [`style`](/html/global-attrs/#style). Значением этого атрибута могут быть свойства и значения CSS, которые бу
```suggestion
В этом варианте элементам, которые необходимо оформить, добавляется атрибут [`style`](/html/global-attrs/#style). Значением этого атрибута могут быть свойства и значения CSS, которые и применятся к элементу:
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Стили, заданные через атрибут `style` также называют _инлайн-стилями_.
```suggestion
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +- В случае с инлайн-стилями, по аналогии с глобальными, браузеру нет необходимости делать дополнительный запрос на сервер, чтобы загрузить файл стилей.
```suggestion
- В случае с инлайн-стилями, как и со встроенными, браузеру нет необходимости делать дополнительный запрос на сервер, чтобы загрузить файл стилей.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +- Встроенные стили легко и быстро добавлять. Не нужно беспокоиться о написании правильного селектора, поскольку они добавляются непосредственно к элементу, который вы хотите изменить.
```suggestion
- Инлайн-стили легко и быстро добавлять. Не нужно беспокоиться о правильном написании селектора, потому что они применяются непосредственно к элементу, в атрибут которого вы их пишете.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +- Такие стили бывают удобны, если стилизация задана с помощью сторонних библиотек или через CMS. Это удобно для тестирования, предварительного просмотра изменений или для выполнения быстрых исправлен
```suggestion
- Такие стили пригождаются, когда оформление делается с помощью сторонних библиотек или через CMS. Это удобно для тестирования, предварительного просмотра изменений или для выполнения быстрых исправлений.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +- Данный подход может помочь написать сайт в максимально короткие сроки. Это может быть удобно, если сайт небольшой, а времени на его написание не особо много.
```suggestion
- Инлайн-стили могут помочь создать сайт быстро, когда он небольшой, а времени на его создание мало.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +- Данный подход может помочь написать сайт в максимально короткие сроки. Это может быть удобно, если сайт небольшой, а времени на его написание не особо много.
Сомнительный тезис, конечно

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +## Почему инлайн-стили — это плохо?
```suggestion
### Недостатки
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +## Почему инлайн-стили — это плохо?
Понимаю резоны, но предлагаю все-таки не взрывать структуру.

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +
```suggestion

Однако несмотря на преимущества, инлайн-стили — это антипаттерн. Недостатков у этого подхода слишком много.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +### Приоритет
```suggestion
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Внутренние стили имеют [наивысший приоритет](https://doka.guide/css/specificity/#atribut-style), их нельзя переопределить с помощью селекторов по [идентификатору](/css/id-selector), [классу](/css/cla
```suggestion
**Приоритет**. У инлайн-стилей [наивысший приоритет](https://doka.guide/css/specificity/#atribut-style), их нельзя переопределить с помощью селекторов по [идентификатору](/css/id-selector), [классу](/css/class-selector) или [тегу](/css/tag-selector) во внешнем CSS. Единственный способ это сделать — добавить [`!important`](/css/important) к значению свойства. Но этот приём тоже считается плохой практикой.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +### Переиспользование
```suggestion
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +При использовании инлайн-стилей мы зачастую будем вынуждены добавлять встроенный стиль к каждому элементу, который необходимо стилизовать. В том случае, если элементов на странице много, прописывать
```suggestion
**Переиспользование.** При использовании инлайн-стилей мы будем вынуждены добавлять встроенный стиль к каждому элементу, который необходимо стилизовать. Если элементов на странице много, прописывать стили вручную станет неудобно.

**Всё в одну кучу.** Оформление при помощи инлайн-стилей нарушает принцип «разделения содержимого и оформления».
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +При использовании инлайн-стилей мы зачастую будем вынуждены добавлять встроенный стиль к каждому элементу, который необходимо стилизовать. В том случае, если элементов на странице много, прописывать
И я бы слегка развернула, что это за принцип, почему он таков.

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +### Псевдоклассы и псевдоэлементы
```suggestion
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Ещё одним недостатком встроенных стилей является невозможность определить и стилизовать [псевдоклассы](/css/pseudoclasses) и [псевдоэлементы](/css/pseudoelements).
```suggestion
**Псевдоклассы и псевдоэлементы.** В инлайн-стилях нельзя использовать [псевдоклассы](/css/pseudoclasses) и [псевдоэлементы](/css/pseudoelements).
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Атрибут `style` определяет свойства стиля для конкретного HTML-элемента. Псевдоклассы и псевдоэлементы в атрибуте не встречаются, поэтому нельзя определить и стилизовать их встроенно.
```suggestion
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Атрибут `style` определяет свойства стиля для конкретного HTML-элемента. Псевдоклассы и псевдоэлементы в атрибуте не встречаются, поэтому нельзя определить и стилизовать их встроенно.
Не совсем верное объяснение, но верное было бы слишком длинным, поэтому предлагаю просто выпилить.

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +### Восприятие кода
```suggestion
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Если писать стили внутри атрибута `style`, то HTML становится трудночитаемым. Логическая структура исчезает и стили размываются по всему коду. И чем крупнее проект, тем сложнее управлять стилизацией.
```suggestion
**Восприятие кода.** Если писать стили внутри атрибута `style`, то HTML становится трудно читать. Логическая структура перестаёт быть видна, стили размазываются по всему коду. И чем крупнее проект, тем сложнее управлять оформлением.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +Нежели этот:
```suggestion
...чем этот:
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +  <p>У моей кошки <span class="eyes">светло синие</span> глаза.</p>
```suggestion
  <p>У моей кошки <span class="eyes">светло-синие</span> глаза.</p>
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/index.md
> +  <p>У моей кошки <span style="color: lightblue;">светло синие</span> глаза.</p>
```suggestion
  <p>У моей кошки <span style="color: lightblue;">светло-синие</span> глаза.</p>
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/practice/kanishev.md
> +🛠 Одна из самых распространённых областей применений инлайн-стилей — email-рассылки.
```suggestion
🛠 Одна из самых распространённых областей применения инлайн-стилей — email-рассылки.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/practice/kanishev.md
> +По соображениям безопасности почтовые службы блокируют загрузку внешних ресурсов, включая файлы стилей. Например, этим принципам следуют почтовые клиенты Яндекс.Почта или Gmail. Поэтому разработчикам
```suggestion
По соображениям безопасности почтовые службы (например, Яндекс.Почта или Gmail) блокируют загрузку внешних ресурсов, в том числе и файлы стилей. Поэтому разработчикам ничего не остаётся, кроме как использовать инлайн-стили.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/practice/kanishev.md
> +🛠 Одна из самых распространённых областей применений инлайн-стилей — email-рассылки.
```suggestion
🛠 Одна из самых распространённых областей применений инлайн-стилей — почтовые рассылки.
```

2021-11-12 17:38 UTC, tachisis commented on css/installation/practice/kanishev.md
> +Вот так может выглядеть HTML-разметка при вёрстке email-рассылки:
```suggestion
Вот так может выглядеть HTML-разметка при вёрстке письма:
```

2021-11-13 09:34 UTC, solarrust commented on css/installation/index.md
> +Таким образом можно подключать таблицу стилей, которая находится на другом сайте. В примере выше мы подключаем шрифт Roboto с сайта [Google Fonts](https://fonts.google.com).
Убрала эту строку и снова поправила пример

2021-11-13 09:37 UTC, solarrust commented
Внесла немного правок, убрала пример с кастомными свойствами. Он не относится напрямую к теме статьи. Чуть убавила количество кода в примере с вёрсткой почтовой рассылки, а то даже на десктопе появлялся скролл у блока кода.

Надо будет ещё развернуть этот совет: https://github.com/doka-guide/content/pull/2308#discussion_r748419902

Пожалуйста, резолви только те обсуждения, по которым были внесены правки. А то сейчас приходится проводить целое расследование, чтобы понять, что правка действительно внесена.

@tachisis добавила тег редактора 🙌

@pepelsbey приходи поревьюить ещё раз.

2021-11-15 17:09 UTC, tachisis commented
Посмотрела, но апрувить финально буду после отмашки @solarrust , что статья полностью готова

2021-11-17 09:18 UTC, solarrust reviewed
Ещё разок перечитала статью и придралась к мелочам =)

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +## Почему это важно знать
```suggestion
## Почему это важно
```

Можно обойтись без «знать»

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- Можно использовать один CSS-файл для нескольких страниц. Изменение стилей в таком файле автоматически применится ко всем страницам, на которые он подключён.
```suggestion
- Можно использовать один CSS-файл для нескольких страниц. Изменение стилей в таком файле автоматически применится ко всем страницам, к которым он подключен.
```

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- При первой загрузке страницы файл со стилями кэшируется, и в следующие разы она открывается быстрее.
```suggestion
- При первой загрузке страницы файл со стилями кэшируется и в следующие разы она открывается быстрее.
```

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- При первой загрузке страницы файл со стилями кэшируется, и в следующие разы она открывается быстрее.
@tachisis тут не уверена на счёт запятой

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- Во внешних стилях можно свободно использовать [псевдоклассы](/css/pseudoclasses) и [псевдоэлементы](/css/pseudoelements). Например, задавать интерактивные состояния отдельно выбранным кнопкам, стил
```suggestion
- Во внешних стилях можно свободно использовать [псевдоклассы](/css/pseudoclasses) и [псевдоэлементы](/css/pseudoelements). Например, задавать интерактивные состояния отдельно выбранным кнопкам, стилизовать каждый чётный элемент списка и тому подобное.
```

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- Встроенные стили работают изолированно и применяются непосредственно к странице, на которой прописаны.
```suggestion
- Встроенные стили работают изолированно и применяются непосредственно к странице, на которой прописаны.
- Можно использовать [псевдоклассы](/css/pseudoclasses) и [псевдоэлементы](/css/pseudoelements).
```

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- С каждым новым правилом вес HTML-файла будет увеличиваться. Вырастет трафик, и страница будет загружаться медленнее.
```suggestion
- С каждым новым правилом вес HTML-файла будет увеличиваться и страница будет загружаться медленнее.
```

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- Со временем такие же стили могут понадобиться на других страницах, и CSS придётся дублировать.
```suggestion
- Со временем такие же стили могут понадобиться на других страницах и CSS придётся дублировать.
```

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- Подключение CSS-файлов при помощи директивы `@import` может значительно увеличить время загрузки страницы. CSS-файлы подключаются один за другим, и для каждого устанавливается отдельное соединение
```suggestion
- Подключение CSS-файлов при помощи директивы `@import` может значительно увеличить время загрузки страницы. CSS-файлы подключаются один за другим, и для каждого устанавливается отдельное соединение с сервером, каждый файл браузер скачивает и анализирует.
```

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- А еще этот способ не гарантирует последовательную загрузку файлов CSS.
Чем это опасно или мешает? Нужно буквально предложение, поясняющее этот недостаток

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- Инлайн-стили легко и быстро добавлять. Не нужно беспокоиться о правильном написании селектора, потому что они применяются непосредственно к элементу, в атрибут которого вы их пишете.
```suggestion
- Не нужно думать о написании селектора, потому что стили применяются непосредственно к элементу, в атрибут которого вы их пишете.
```

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +- Инлайн-стили могут помочь создать сайт быстро, когда он небольшой, а времени на его создание мало.
Ни разу не использовала инлайн-стили в таком ключе. Правда помогают?

2021-11-17 09:18 UTC, solarrust commented on css/installation/index.md
> +**Приоритет**. У инлайн-стилей [наивысший приоритет](/css/specificity/#atribut-style), их нельзя переопределить с помощью селекторов по [идентификатору](/css/id-selector), [классу](/css/class-selecto
```suggestion
**Приоритет.** У инлайн-стилей [наивысший приоритет](/css/specificity/#atribut-style), их нельзя переопределить с помощью селекторов по [идентификатору](/css/id-selector), [классу](/css/class-selector) или [тегу](/css/tag-selector) во внешнем CSS. Единственный способ это сделать — добавить [`!important`](/css/important) к значению свойства. Но этот приём тоже считается плохой практикой.
```

2021-11-22 08:27 UTC, solarrust commented
@kanishev пожалуйста, зарезолви те обсуждения, по которым внесены правки. И давай обсудим открытые вопросы =)

2021-11-22 12:58 UTC, kanishev commented
> @kanishev пожалуйста, зарезолви те обсуждения, по которым внесены правки. И давай обсудим открытые вопросы =)

Я ведь зарезолвил правки и оставил те, на которые даю комментарий. Вы же их видите? Давайте обсудим!

2021-11-22 13:00 UTC, solarrust commented
Я вижу заданные вопросы, но не вижу на них ответы 🤔
Может быть что-то пошло не так в техническом плане. Не сложно написать комменты ещё раз?

![CleanShot 2021-11-22 at 15 59 35](https://user-images.githubusercontent.com/13676514/142866160-0bd2e283-b883-43f3-a6ab-bcb3dda78291.png)

2021-11-22 13:04 UTC, kanishev commented
> 

Ого :(
Сейчас попробую еще раз.

2021-11-22 13:11 UTC, kanishev commented
> Я вижу заданные вопросы, но не вижу на них ответы 🤔 Может быть что-то пошло не так в техническом плане. Не сложно написать комменты ещё раз?
> 
> Скриншот

Сейчас видно?

2021-11-22 13:13 UTC, solarrust commented
Вижу только то, что обсуждения теперь зарезолвлены, закрыты. Но комментариев в них не появилось.

![CleanShot 2021-11-22 at 16 12 31](https://user-images.githubusercontent.com/13676514/142867762-16e1512b-0b2d-442d-9292-4614f60c8b8d.png)

2021-11-22 13:15 UTC, kanishev commented
> Вижу только то, что обсуждения теперь зарезолвлены, закрыты. Но комментариев в них не появилось.
> 
> ![CleanShot 2021-11-22 at 16 12 31](https://user-images.githubusercontent.com/13676514/142867762-16e1512b-0b2d-442d-9292-4614f60c8b8d.png)

Стоит статус pending
![image](https://user-images.githubusercontent.com/50417170/142868067-4471f60e-dfd3-43c2-aedc-e8ce756bae52.png)

Может я что-то не так сделал?

2021-11-23 08:13 UTC, solarrust commented
А какую кнопку ты нажимаешь, оставляя комментарии? Нужно "add a single comment" или как-то так =)

2021-11-23 15:40 UTC, kanishev commented
> А какую кнопку ты нажимаешь, оставляя комментарии? Нужно "add a single comment" или как-то так =)

![image](https://user-images.githubusercontent.com/50417170/143055384-ffa67f17-1cca-41e8-bec9-bae4f6b651c5.png)

Вот так. Неважно, отвечаю ли я на ваш комментарий или сам добавляю.

2021-11-23 17:43 UTC, kanishev commented
Сейчас должны быть видны комментарии.

2021-11-29 12:52 UTC, kanishev commented
Ребят, на чём мы в итоге останавливаемся?

2021-11-30 15:18 UTC, solarrust commented
@kanishev прости, пожалуйста, что ревью чуть затянулось. Сейчас ждём @pepelsbey чтобы он почитал =)

2021-12-04 09:07 UTC, pepelsbey requested changes
Последний заход и получится отличная статья!

Предложил важную формулировку, переставил пример, предложил пару мелочей.

2021-12-04 09:07 UTC, pepelsbey commented on css/installation/index.md
> +- А ещё этот способ не гарантирует последовательную загрузку файлов CSS.
```suggestion
Подключение стилей при помощи CSS-файла, в котором директивы `@import` подключают другие файлы, может значительно увеличить время отрисовки страницы. Браузер узнает о существовании других CSS-файлов слишком поздно, а если и в них окажутся импорты, то всё будет ещё хуже.

Если вам очень нужно подключить несколько файлов, лучше добавить несколько элементов `<link>`.

Иногда так всё же делают при разработке сайтов, чтобы не тратить время на сборку многих файлов и просто подключать их одним файлом с кучей импортов. Но перед публикацией сайта все эти импорты «склеиваются» в один файл для более эффективной загрузки.
```

Развернул чуть более корректно, почему это проблема.

2021-12-04 18:30 UTC, pepelsbey requested changes
Можно немного лучше перечислить преимущества инлайн-стилей.

И вопрос про мои предыдущие предложения: они зарезолвлены и не внесены. Это потому, что вы не согласны?

2021-12-04 18:30 UTC, pepelsbey commented on css/installation/index.md
> +- Инлайн-стили могут помочь создать сайт быстро, когда он небольшой, а времени на его создание мало.
Последние два пункта повторяют друг друга, формулировки остальных немного упростил:

```suggestion
- Как и со встроенными стилями, браузеру не нужно запрашивать файл, что ускоряет рендеринг.
- Не нужно писать селекторы, потому что стили применяются сразу к нужному элементу.
- Удобно отлаживать код или делать быстрые правки прямо в админке, без разворачивания проекта.
```

2021-12-04 18:33 UTC, kanishev commented on css/installation/index.md
> +- Инлайн-стили могут помочь создать сайт быстро, когда он небольшой, а времени на его создание мало.
Нет, все ок. Отвлекся на другую часть статьи, забыл внести изменения. Сейчас поправлю :)

2021-12-04 18:56 UTC, kanishev commented
> Можно немного лучше перечислить преимущества инлайн-стилей.
> 
> И вопрос про мои предыдущие предложения (подвинуть пример повыше): они зарезолвлены и не внесены. Это потому, что вы не согласны?

Нет, я согласен. Я почему-то вижу все изменения. Пример стоит выше, как вы и предлагали. Возможно, опять что-то с github приключилось.

2021-12-05 00:15 UTC, pepelsbey approved these changes
Ура! Всё красиво :)

2021-12-06 11:20 UTC, solarrust approved these changes
Огонь! Спасибо огромное за отличную работу!

Осталось дождаться одобрения от @tachisis

2021-12-06 11:22 UTC, skorobaeus approved these changes

2021-12-06 21:34 UTC, tachisis commented on css/installation/practice/kanishev.md
> +🛠 Одна из самых распространённых областей применений инлайн-стилей — почтовые рассылки.
```suggestion
🛠 Одна из самых распространённых областей применения инлайн-стилей — почтовые рассылки.
```

2021-12-06 21:38 UTC, tachisis approved these changes

2021-12-07 09:11 UTC, merged

2021-12-07 09:11 UTC, solarrust commented
Очень кайф, спасибо огромное за такую полезную статью! 🔥
Пиши ещё! 🙌