Добавляет доку про <bdi>
doka-guide/content pull request #2316
Opened 2021-11-04 16:34 UTC by xpleesid

Fix #562

2021-11-05 14:41 UTC, solarrust reviewed
Обалденно, не побоюсь этого слова 🥳

Оставила пару микро-комментариев =)

2021-11-05 14:41 UTC, solarrust commented on html/bdi/demos/basic/index.html
> +      font-size: 20px;
Ниже размер текста переопределён. Нужна ли эта строка?

2021-11-05 14:41 UTC, solarrust commented on html/bdi/demos/userlist-b/index.html
> +      font-size: 20px;
Аналогичный вопрос

2021-11-05 14:41 UTC, solarrust commented on html/bdi/demos/userlist-b/index.html
> +    <li>Пользователь <b>شاب رائع</b>: 133 комментария.
Да, фактически мы можем не закрывать теги `<li>` и браузер сам закроет их где надо. Но лучше явно закрывать пункты списка для наглядности и чтобы не испытывать удачу =)

2021-11-06 15:43 UTC, xpleesid commented on html/bdi/demos/userlist-b/index.html
> +    <li>Пользователь <b>شاب رائع</b>: 133 комментария.
А это я скопировал из [спеки](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-bdi-element) и даже не заметил) забавно, никому нельзя доверять)

2021-11-07 21:14 UTC, pepelsbey requested changes
Спасибо! Ещё буду читать внимательно, но сходу вижу во всех демках неудачные дефолты:

```css
html, body {
  height: 100%;
  margin: 0;
  box-sizing: border-box;
}

body {
  /* … */
}
```

Кажется так будет лучше:

```css
html, body {
  height: 100%;
}

body {
  margin: 0;
  /* … */
}
```

Потому, что `box-sizing` не используется в демках, а `margin` есть только у `body`.

2021-11-08 10:51 UTC, skorobaeus approved these changes

2021-11-09 20:15 UTC, solarrust approved these changes
Убрала треугольные скобочки из тайтлов айфреймов чтобы скринридер их не проговаривал. В остальном аппрув! 🔥

2021-11-09 20:15 UTC, solarrust commented on html/bdi/index.md
> +<iframe title="Список пользователей с <b>" src="demos/userlist-b/" height="170"></iframe>
```suggestion
<iframe title="Список пользователей с b" src="demos/userlist-b/" height="170"></iframe>
```

2021-11-09 20:15 UTC, solarrust commented on html/bdi/index.md
> +<iframe title="Список пользователей с <bdi>" src="demos/userlist-bdi/" height="170"></iframe>
```suggestion
<iframe title="Список пользователей с bdi" src="demos/userlist-bdi/" height="170"></iframe>
```

2021-11-10 21:33 UTC, pepelsbey approved these changes

2021-11-10 21:33 UTC, merged

2021-11-10 21:35 UTC, pepelsbey commented
Спасибо! Получилось очень интересно :)