Добавляет статью про Markdown
doka-guide/content pull request #2334
Opened 2021-11-06 10:53 UTC by cergmin

Fix #2213

2021-11-06 11:02 UTC, cergmin commented
Не совсем понимаю, почему возникает ошибка при проверке "Ярлыков". Пишет, что нет файла people/cergmin/index.md, хотя по факту он есть.

2021-11-06 12:46 UTC, pepelsbey commented
> Не совсем понимаю, почему возникает ошибка при проверке "Ярлыков". Пишет, что нет файла people/cergmin/index.md, хотя по факту он есть (точнее добавляется).

Сбоит автоматика, к сожалению. У вас всё в порядке :)

2021-11-06 13:06 UTC, cergmin commented
Перед тем как рассмотреть этот pull request, лучше сначала проверить и принять тот: https://github.com/doka-guide/platform/pull/726, он исправляет проблему отображения одного примера кода из этой статьи.

2021-11-07 10:47 UTC, bespoyasov approved these changes
Текст отличный! Я принёс пару небольших предложений, но по большей части мне всё нравится 👍 

Я бы только, наверное, убрал неразрывные пробелы в виде `&nbsp;`. Если я правильно помню, у нас в планах было сделать автоматическое типографирование текста, верно, @nlopin, @pepelsbey?

2021-11-07 10:47 UTC, bespoyasov commented on tools/markdown/index.md
> +- Заголовок первого уровня для названия.
Я бы поменял местами этот список и код ниже, потому что сейчас есть ощущение, что этот список _и есть маркдаун_. 

Предлагаю после «Давайте посмотрим на пример одного из таких:» поставить сразу пример, а этот список переместить под пример, предварив его описанием, нечто вроде «Код выше содержит...».

2021-11-07 10:47 UTC, bespoyasov commented on tools/markdown/index.md
> +Параграф это одна или несколько подряд идущих строчек текста, отделённых одной (или&nbsp;несколькими) пустыми строчками. Если строка содержит только пробелы или табы, то&nbsp;она всё равно считается
```suggestion
Параграф это одна или несколько подряд идущих строчек текста, отделённых одной или&nbsp;несколькими пустыми строчками. Если строка содержит только пробелы или табы, то&nbsp;она всё равно считается пустой.
```

2021-11-07 10:47 UTC, bespoyasov commented on tools/markdown/index.md
> +```
Может быть, стоит показать это на иллюстрации? Сейчас сложно распарсить текст в голове 🤔

2021-11-07 10:47 UTC, bespoyasov commented on tools/markdown/practice/cergmin.md
> +Не стоит использовать два пробела для жёсткого переноса строк в параграфе, потому что во многих проектах для IDE включена опция trim_trailing_whitespace, которая стирает все пробелы, стоящие в конце
👍

2021-11-07 11:17 UTC, cergmin commented on tools/markdown/index.md
> +```
Да, действительно. Попробую сделать иллюстрацию или интерактивный пример, чтобы лучше было понятно.

2021-11-07 11:37 UTC, cergmin commented
Хотел ещё уточнить, насколько правильно приняты некоторые решения по демо.
1. Были вынесены стили в отдельный общий файл, потому что везде они почти одинаковые. Это не соответствует рекомендациям, но мне показалось, что так будет правильнее. 
2. Добавлено подстраивание под тему Доки (светлая, авто, тёмная) через чтение значения из localStorage и media выражения. Так комфортнее читать статью, потому что она вся в одних тонах, но других статьях такого нет, поэтому возник вопрос: "Нужно ли было это добавлять?"

2021-11-07 21:42 UTC, pepelsbey requested changes
У нас весь нейминг файлов по kebab-case, а у вас camelCase. Поправьте, пожалуйста :)

2021-11-07 21:47 UTC, pepelsbey commented
> Были вынесены стили в отдельный общий файл, потому что везде они почти одинаковые

Мы стараемся делать демки автономными, даже если это приводит к повторению кода. Такое дублирование кода часто недопустимо для рабочего проекта, который развивается и меняется. Но для демок — это нормально.

> Добавлено подстраивание под тему Доки через чтение значения из localStorage

И тут опять про автономность: демкам важно жить отдельно от платформы. Сайт поменяет ключи для тем или способ темизации и демки сломаются. Мы пока исходим из того, что демки тему не меняют. Только если в демке не идёт речь про смену темы.

Ещё одна важная мысль: чем проще код демки, чем ближе он фокусируется на рассматриваемой технологии, чем лучше. Лучше не запонять код переключателями и лишними вещами.

2021-11-08 10:38 UTC, skorobaeus requested changes
Я в полном восторге от статьи и демок! <3

Можно, пожалуйста, заменить CSS-файл на неминимизированный? Пользователь Доки может в любой момент покопаться в коде демо и мы стараемся этому не препятствовать.

2021-11-08 13:13 UTC, cergmin commented
Спасибо за приятные слова. В ближайшие дни внесу правки и вернусь с коммитом.

2021-11-08 21:22 UTC, pepelsbey commented
> Не до конца понял, что делать с `&nbsp;`. Оставлять или убирать?

Мы пока не типографим тексты неразрывными пробелами — планируем это автоматизировать. Так что да, давайте уберём :)

2021-11-09 15:11 UTC, cergmin commented
Внёс правки:
- Теперь стили прописаны в каждом index.html
- Перевёл названия из camelCase в kebab-case
- Убрал `&nbsp;`
- Убрал смену темы
- Добавил интерактивное демо про отступы вложенных списков
- В "Примере" поменял местами список и код

2021-11-09 15:24 UTC, bespoyasov approved these changes
Апрув на контент статьи 👍

2021-11-10 10:26 UTC, pepelsbey submitted a review, later dismissed
Очень подробная и крутая статья получилась :) Я сначала сомневался, что под каждый пример нужны демки, но теперь понимаю, что так очень наглядно.

Другое дело, что в этом случае, как мне кажется, демки должны быть максимально простыми. Хочется показать, что маркдаун конвертируется в простой HTML: без классов, без стилей, без лишних атрибутов. А сейчас в демках много дополнительного для красоты:

- Атрибуты align в таблицах
- Обёртки, классы и стили для подсветки кода
- Дополнительные стили для цитат
- и так далее.

То есть я взял бы буквальный вывод маркдауна во всех случаях и добавил бы только базовые стили: фон страницы, шрифт на body, да и всё.

В таком случае не останется сомнений в том, что действительно делает маркдаун. Ну и получится сфокусировать статью.

Кстати, о фокусе: на мой взгляд, демка с регулируемыми отступами конечно крутая, но вываливается из статьи. Не очень понятно, как она относится и как помогает понять. Я бы лучше её убрал и подумал, как показать статически количество пробелов прямо в теле статьи.

2021-11-10 12:00 UTC, cergmin commented
Я согласен с тем, что стилей получилось многовато, но у меня есть опасения, что без "красоты" не будет понятно чем, например, цитата отличается  от обычного параграфа, потому что `<blockquote>` никак особо не стилизуется браузерами. 

Подсветка синтаксиса показывает зачем нужно указывать язык программирования после бэктиков. Есть ощущение, что без неё не будет понятно чем отличаются эти два фрагмента:
````md
```
let a = 5;
```

```javascript
let a = 5;
```
````
Хотя с другой стороны, это может ввести читателя в заблуждения, потому что после конвертации в HTML он не увидит раскрашенного кода, только класс `language-[язык]` у `<code>`. Можно попробовать напрямую написать, что разница только в наличии/отсутствии класса, что само по себе никак код не подсвечивает, но позволяет легко подключить, например, highlight.js.

Атрибут align добавляется сам при конвертации.

Попробую упростить стили и подумаю, как можно понятнее показать какое количество пробелов нужно для создания вложенного списка.

2021-11-10 17:07 UTC, pepelsbey commented
> Атрибут align добавляется сам при конвертации
> только класс language-[язык]

А вот тут же вопрос: чем вы конвертируете в HTML? Есть разные движки и их настройки. Я бы предложил написать документацию достаточно универсальную, чтобы не было сюрпризов. Не уверен, к примеру, что в классической реализации макрдауна добавлялись какие-то атрибуты или классы.

2021-11-10 21:23 UTC, cergmin commented
Классическая реализация Markdown не поддерживает таблицы. Синтаксис таблиц описан в спецификации Github Flavored Markdown.
https://github.github.com/gfm/#tables-extension-

Она даёт возможность не просто размечать таблицы, но и указывать выравнивание столбиков при желании.
```md

2021-11-10 21:48 UTC, pepelsbey commented
Мне кажется, что в статье-введении в маркдаун не стоит касаться нюансов реализаций в различных движках. Таблицы и блоки с кодом — довольно популярные расширения, которые реализованы во всех движках. Но вот атрибуты, классы и прочие красоты — это очень индивидуальная вещь.

Про теги с языками для блоков кода я бы в принципе написал — мол, позволяет текстовым редакторам подсвечивать внутри маркдауна и помогает дополнительным плагинам делать подсветку кода. Не стоит показывать конкретные реализации, это уже не введение.

2021-11-11 07:19 UTC, nlopin commented
Это самая крутая и полная статья, что я читал за последнее время 🔥

2021-11-11 07:23 UTC, nlopin commented on tools/markdown/practice/cergmin.md
> +Не стоит использовать два пробела для жёсткого переноса строк в параграфе, потому что во многих проектах для IDE включена опция `trim_trailing_whitespace`, которая стирает все пробелы, стоящие в конц
давай тут ещё скажем, что стоит использовать вместо пробелов. У нас осталось две возможных опции из статьи и я бы сказал, что `<br>` самый наглядный

2021-11-11 07:40 UTC, nlopin approved these changes

2021-11-11 07:40 UTC, nlopin commented on tools/markdown/index.md
> +Функция `alert()`
В статье бэктики подсвечиваются не очень:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/1469636/141255789-e1d50265-b46a-4c30-a09b-19c49addac49.png">

Давай уберём `md` у бэктиков, чтобы всё стало черно-белым:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/1469636/141256815-9f46b297-fb4f-4fe7-a27f-5166984f2f23.png">

2021-11-11 07:44 UTC, nlopin commented on tools/markdown/index.md
> +Функция `alert()`
изменил сам, @cergmin тебе ок или подсветка была задумана?

2021-11-11 10:51 UTC, cergmin commented on tools/markdown/index.md
> +Функция `alert()`
Если не указывать язык, то помимо подсветки исчезает и нумерация строк, из-за чего блоки кода становятся плохо отличимыми от обычных параграфов, поэтому кажется, что минимальная подсветка лучше, чем её отсутствие. Плюс есть надежда, что кто-нибудь когда-нибудь это поправит (или у самого дойдут руки до того, чтобы разобраться в Prism и внести PR).

2021-11-11 10:52 UTC, cergmin commented on tools/markdown/index.md
> +Функция `alert()`
А вообще, есть сомнения по поводу того, как правильно поступить, потому что проблемы с подсветкой наблюдаются не только у бэктиков, но и у некоторых setext-styled заголовков, что может запутать читателя.
![image](https://user-images.githubusercontent.com/21996065/141283702-9bd2641d-2915-45f2-97c3-94df8f3cc935.png)

2021-11-11 10:56 UTC, skorobaeus approved these changes

2021-11-11 12:06 UTC, nlopin commented on tools/markdown/index.md
> +Функция `alert()`
Мне подсветка только мешала, в одном блоке она вообще разорвала текст. Я совсем не заметил, что исчезли номера строк, а их хочется

2021-11-11 21:20 UTC, nlopin commented on tools/markdown/index.md
> +Функция `alert()`
Нашёл способ. Нужно указать, `text` как язык блока и тогда грамматика не включается. Возможно стоит все блоки так сделать. Номера строк будут присутствовать.
<img width="600" alt="Screenshot 2021-11-11 at 22 18 18" src="https://user-images.githubusercontent.com/1469636/141370616-647caa95-6eb4-4cfd-8777-ea8591842208.png">

2021-11-12 09:48 UTC, cergmin commented on tools/markdown/index.md
> +Функция `alert()`
Спасибо, способ действительно рабочий, заменил md на text ещё у блока с setext-styled заголовками. По поводу того, чтобы сделать такую замену у всех блоков, мне кажется, что лучше оставить подсвечивание кода там, где это происходит корректно.

2021-11-13 09:21 UTC, cergmin commented
Внёс правки:
- Упростил демки, но оставил обёртку содержимого в виде простого div'а, потому что используются псевдоклассы `:first-child`, `:last-child`. Если её убрать, то скрипты, которые инжектятся на страницу (например от BrowserSync), будут ломать вёрстку.
- Добавил рекомендацию к использованию `<br>` для жёсткого переноса
- Добавил параграф, который поясняет, зачем нужно указывать ЯП после бэктиков
- Заменил интерактивное демо на картинку (надеюсь она понятнее)

2021-11-14 15:56 UTC, nlopin approved these changes

2021-11-14 16:06 UTC, merged

2021-11-14 16:07 UTC, nlopin commented
Большое спасибо за вклад в проект! Получил удовольствие от твоего профессинального и обстоятельного подхода к материалу 👍