Добавляет возможность обновление дат статей вручную
doka-guide/content pull request #2356
Opened 2021-11-09 00:29 UTC by vaiil

Написал скрипт, который проверяет дату изменения файлов в папке статьи по гиту и изменения индексного файла по нему же, и если нужно обновляет

Работает скрипт вроде как не долго (локально &mdash; пару секунд). В корректности файлика workflow не уверен, так как с CI/CD Github-а не работал.  

Вот ссылка где можно посмотреть как скрипт файлы меняет:
https://github.com/vaiil/content/pull/1/files

2021-11-09 00:30 UTC, vaiil commented
Ссылка на ишью https://github.com/doka-guide/platform/issues/652

2021-11-09 08:43 UTC, pepelsbey commented on .github/scripts/manual-update-dates.js
> +const contentDirectories = ['css', 'js', 'tools']
```suggestion
const contentDirectories = ['html', 'css', 'js', 'tools']
```

2021-11-09 14:01 UTC, vaiil commented
Поправил

2021-11-12 09:52 UTC, vaiil commented
@igsekor посмотрите?

2021-11-12 12:41 UTC, igsekor requested changes
Да, вроде бы скрипт работает. Ошибок не приметил. Предлагаю сделать иначе. Давайте преобразуем скрипт `update-dates.js` вместо того, чтобы писать отдельный скрипт. Тогда достаточно будет триггер правильный добавить в существующий экшен, и всё заработает. Что скажите? И расскажите, пожалуйста, почему возникла идея создания нового скрипта? Может быть была какая-то мысль, которую я не уловил.

2021-11-12 13:08 UTC, vaiil commented
@igsekor старый скрипт ставит дату только для файлов последнего коммита и ставит дату на основе времени запуска скрипта, этот скрипт берет дату из гита (по факту дату ПР), что позволяет проверить и обновить дату для всех статей. В теории можно его запускать на каждый ПР, вместо старого

2021-11-12 13:24 UTC, igsekor commented
> @igsekor старый скрипт ставит дату только для файлов последнего коммита и ставит дату на основе времени запуска скрипта, этот скрипт берет дату из гита (по факту дату ПР), что позволяет проверить и обновить дату для всех статей.

Это всё понятно. Не стоит ли тогда поменять старый на новый? Существующее решение менее избирательно. Попробуете?

> В теории можно его запускать на каждый ПР, вместо старого

Наверное и нужно было бы бегать только по файлам пиара, чтобы оптимизировать флоу. В ветке `main` такой экшен слишком долго выполняется, да и ещё и при каждом паше, да и ещё и некорректно (опираясь на ишью). Вы сможете добавить такое поведение? В качестве триггера можно было бы использовать `pull_request`. Этого должно хватить по правам, вроде бы.

2021-11-12 14:05 UTC, monochromer commented
Если уж не привязываться к коммиту, то можно хотя бы получить от git список файлов, который изменился за последние полчаса-час и исходить от него.

Ну и неплохо бы понять истинную причину исходного бага - action просто не запустился.

2021-11-12 15:09 UTC, vaiil commented
@monochromer из того что я видел, там были проблемы состояния гонки. То есть когда выкатывают сразу несколько статей, экшен вызванный коммитом А срабатывал на мастере уже после того как туда долетели коммиты Б, и соответственно последний коммит был не А. По-поводу оптимизации, действительно ли она нужна при времени работы скрипта в несколько секунд? Не будет ли это лишним усложнением кода?

2021-11-12 15:19 UTC, monochromer commented
Оптимизация нужна, так как машины Github Actions в среднем слабже, чем ноутбук разработчика, и что будет, когда статей станет около 1000.

2021-11-12 16:11 UTC, vaiil commented
Ок, посмотрю у себя в репе как сейчас по скорости работает, подумаю как можно оптимизировать. Логично смотреть на изменения между запусками action-а, то есть между коммитами в мастер с изменениями даты (возможно как-то помечать эти коммиты, чтобы в дальнейшем их находить)

2021-11-12 16:13 UTC, vaiil commented
Как мне кажется, запускать обновления дат внутри ПР, может быть не очень, так как будет много конфликтов между ПР-ами в одни и те же статьи

2021-11-12 16:22 UTC, igsekor commented
> Как мне кажется, запускать обновления дат внутри ПР, может быть не очень, так как будет много конфликтов между ПР-ами в одни и те же статьи

Ну можно смотреть при каждом пуше разницу между `main` и PR. Если в `main` более свежий вариант, значит не менять, а если нет, то надо. Можно поставить такой экшен на премёрдж изи PR.

2021-11-12 16:23 UTC, igsekor commented
> Ок, посмотрю у себя в репе как сейчас по скорости работает, подумаю как можно оптимизировать. Логично смотреть на изменения между запусками action-а, то есть между коммитами в мастер с изменениями даты (возможно как-то помечать эти коммиты, чтобы в дальнейшем их находить)

Как-то помечать? А зачем?

2021-11-12 17:22 UTC, vaiil commented
Как я понимаю pull_request будет срабатывать при создании pr и при его обновлении? И если двое будут параллельно редактировать статью, то в обоих PR-ах дата обновиться, и при мерже будут конфликты. Поэтому как мне кажется нужно оставлять обновление в main, тем более что пуши в main -- это только закрытые PR-ы (а не все пуши PR-а). Помечать, чтобы находить от какого коммита смотреть изменения.

2021-11-12 18:19 UTC, igsekor commented
> Как я понимаю pull_request будет срабатывать при создании pr и при его обновлении? И если двое будут параллельно редактировать статью, то в обоих PR-ах дата обновиться, и при мерже будут конфликты. Поэтому как мне кажется нужно оставлять обновление в main, тем более что пуши в main -- это только закрытые PR-ы (а не все пуши PR-а). Помечать, чтобы находить от какого коммита смотреть изменения.

Ну я уже ответил выше. Надо просто с веткой `main` сравнивать. Можно это делать при слиянии. Так будет наиболее верно. Но сравнивать надо. Для этого можно использовать условие для запуска джоба: `if: github.event.pull_request.merged == 'true'`.

2021-11-13 18:50 UTC, vaiil commented
Запустил скрипт в github-е, из проблем, для корректной работы нужно фетчить всю историю.

[Запуск, когда есть что обновлять](https://github.com/vaiil/content/runs/4199352481?check_suite_focus=true)
[Запуск, когда уже все обновлено](https://github.com/vaiil/content/runs/4199357770?check_suite_focus=true)

@igsekor вижу следующую доработку. Оставляем старый скрипт, но берем для определения измененных статей `diff-tree` не последнего коммита, а всех исключая первый (то есть на глубину `fetchDepth - 1`), и берем определение даты из нового скрипта. Запуск делаем после успешного мержа ПР в `main`, чтобы не запускать для коммитов с обновлениями дат, возможно `fetchDepth` делаем на 5-10 коммитов, чтобы  уменьшить вероятность багов с последовательностью пушей в `main`. Также делаем ручной флоу запуска по всей истории, чтобы иметь возможность текущие некорректные даты. Что думаете?

2021-11-17 11:21 UTC, igsekor commented
> Запуск, когда уже все обновлено

Мне кажется это правильным. Ручной запуск предлагаю сделать с помощью добавления триггера. Это позволит не плодить сущности сверх меры.

2021-12-20 20:02 UTC, igsekor commented
@vaiil мы что-то отвлеклись. Намечается другой подход, наверное мы откажемся от экшенов для вычисления дат. Но решение примем после небольшого исследования. Ставим этот PR на паузу, пока не разрешится судьба вот [этого](https://github.com/doka-guide/platform/pull/810).

2023-02-03 05:32 UTC, solarrust commented
Привет! Пока закрою этот пиар. Он давно висит без апдейтов. Если будут ещё идеи по улучшению Доки — приноси, пожалуйста! 🙏

2023-02-03 05:32 UTC, closed without merging