Дока для элемента `<time>`
doka-guide/content pull request #2371
Opened 2021-11-10 10:41 UTC by slavarazum

Дока для [семантического элемента `<time>`](https://developer.mozilla.org/ru/docs/Web/HTML/Element/time). Давайте сделаем даты и время распознаваемыми 📅 ⏰

2021-11-10 10:50 UTC, slavarazum commented
Судя по всему, где-то ещё нужно поставить ссылку. Добавлял в `html/index.md`

2021-11-10 11:37 UTC, skorobaeus commented on html/time/demos/index.html
> +  <script src="https://unpkg.com/tailwindcss-jit-cdn"></script>
Мы стараемся делать демки максимально простыми и автономными. Использовать внешнюю библиотечку для стилизации аватарки, имени и времени последнего визита довольно избыточно.

Предлагаю оставить только необходимые стили и разместить их в теге `<style></style>`

2021-11-10 11:39 UTC, skorobaeus requested changes

2021-11-10 11:39 UTC, skorobaeus commented on html/time/demos/index.html
> +        <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q
А картинку положить в папку _images_ рядом с _index.html_

2021-11-10 12:43 UTC, slavarazum commented on html/time/demos/index.html
> +  <script src="https://unpkg.com/tailwindcss-jit-cdn"></script>
Приветствую. Без проблем, перенесу.
Давайте будем считать, что я закинул это в качестве идеи для стилизации демок в целом 🙂  Файлики будут выглядеть чище и JIT версия не тянет за собой лишних стилей, а только те, которые присутствуют на странице.

2021-11-10 12:46 UTC, slavarazum commented on html/time/demos/index.html
> +        <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q
Хорошо.
Увидел что не брезгуем подключать шрифты из google fonts, по этому оставил ссылкой.

2021-11-10 12:49 UTC, solarrust reviewed
Привет! 

Спасибо большое за статью! 🔥
Оставила несколько предложений и комментариев =)

2021-11-10 12:49 UTC, solarrust commented on html/time/demos/index.html
> +  <title>Document</title>
Демки мы называем в формате «Название демки → Название статьи → Дока»

2021-11-10 12:49 UTC, solarrust commented on html/time/demos/index.html
> +<html lang="en">
```suggestion
<html lang="ru">
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Дока вышла в релиз <time datetime="2021-10-12">12-го Октября, 2021</time>
```suggestion
Дока вышла в релиз <time datetime="2021-10-12">12 Октября, 2021</time>
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Элемент `<time>` служит для оформления дат, времени или периода времени – так что бы было понятно машине. Поисковому роботу точно понравится 🙂
```suggestion
Элемент `<time>` служит для оформления дат, времени или периода времени — так что бы было понятно машине. Поисковому роботу точно понравится 🙂
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +<time datetime="2013-02-15T09:20+06:00">15-го Февраля 2013 около 09:20</time>
```suggestion
<time datetime="2013-02-15T09:20+06:00">15 Февраля 2013 около 09:20</time>
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Тоже самое что дата и время, только с временной зоной. И снова, “T” можно заменить на пробел “ ”.
```suggestion
Тоже самое что дата и время, только с временной зоной. И снова, `T` можно заменить пробелом.
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Начинается с плюса или минуса. Двоеточие не обязательно. +00:00, или UTC время, можно указать большой буквой “Z”.
```suggestion
Начинается с плюса или минуса. Двоеточие не обязательно. +00:00, или UTC время, можно указать большой буквой `Z`.
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Комбинация даты и времени, разделяется заглавной “T” либо пробелом “ ”.
```suggestion
Комбинация даты и времени, разделяется заглавной `T` или пробелом.
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Сначала год, потом количество недель после большой “W”.
```suggestion
Сначала год, потом количество недель после большой `W`.
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Заглавная “P”, день (необязательно), заглавная “T”, дальше необязательные часы, минуты и секунды. Все буквы должны быть заглавные.
```suggestion
Заглавная `P`, день (необязательно), заглавная `T`, дальше необязательные часы, минуты и секунды. Все буквы должны быть заглавными.
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Неделя (w), День (d), Час (h), Минута (m), и Секунда (s). Буквы могут быть маленькими и большими. Пробелы не обязательны.
```suggestion
Неделя (`w`), день (`d`), час (`h`), минута (`m`) и секунда (`s`). Буквы могут быть маленькими и большими. Пробелы не обязательны.
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Вы можете дополнить элемент `<time>`, с помощью атрибута `title`, в котором можно указать более детальную информацию. То есть данные о времени можно представлять сразу в трёх видах:
```suggestion
Вы можете дополнить элемент `<time>` атрибутом `title`, в котором можно указать более детальную информацию. То есть данные о времени можно представлять сразу в трёх видах:
```

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +Все мы работаем с датами: напоминания, сообщения, события... Представьте что браузер или любой другой html-интерпретатор сможет распознать существующие даты на странице и предложить добавить событие
```suggestion
Все мы работаем с датами: напоминания, сообщения, события... Представьте что браузер или любой другой HTML-интерпретатор сможет распознать существующие даты на странице и предложить добавить событие в календарь или перевести в формат настроенный пользователем.
```

2021-11-10 12:49 UTC, solarrust commented on html/time/demos/index.html
> +<!DOCTYPE html>
Внутри папки _demos/_ нужно создать подпапку для этой конкретной демки.

2021-11-10 12:49 UTC, solarrust commented on html/time/index.md
> +> Варианты использования однозначного указания даты придумать нетрудно. Браузер может предложить пользователю добавить событие на странице в его календарь. Браузер в Таиланде может автоматически прео
Было бы очень круто взять эту цитату за основу, но перефразировать её и объяснить как же действительно браузер работает с этим тегом, что может произойти благодаря нему. Что будет если его не проставить. Собственно всё то, что поможет действительно понять, как же это работает. 

И стоит перенести этот раздел в начало документа, до длинного перечисления возможных форматов. Чтобы человек мог быстро пробежаться глазами и понять нужен ему тег или нет.

2021-11-10 22:06 UTC, pepelsbey requested changes
Спасибо за подробное объяснение синтаксиса datetime! Мне кажется, было бы хорошо добавить что-нибудь о том, как его вывести программно. Например, как получить нужный формат в JS. Мне кажется мало кто будет писать значение атрибута руками.

Ну и предложил как немного улучшить демку.

2021-11-10 22:06 UTC, pepelsbey commented on html/time/index.md
> +<iframe title="Обычный textarea" src="demos/basic/" height="150"></iframe>
```suggestion
<iframe title="Точное время" src="demos/basic/" height="150"></iframe>
```

2021-11-10 22:06 UTC, pepelsbey commented on html/time/index.md
> +Секунды не обязательно. Доли можно указать тремя цифрами после точки.
```suggestion
Час, минуты, потом секунды. Секунды не обязательно. Доли можно указать тремя цифрами после точки.
```

2021-11-12 18:06 UTC, slavarazum commented
> Спасибо за подробное объяснение синтаксиса datetime! Мне кажется, было бы хорошо добавить что-нибудь о том, как его вывести программно. Например, как получить нужный формат в JS. Мне кажется мало кто будет писать значение атрибута руками.

Хорошая идея с примерами форматирования на JS. Нативным объектом `Date` в пару строк это не сделать или может я что-то упускаю?
По идее проще всего будет с использованием библиотеки, может есть идеи как обойтись без этого.

2021-11-13 08:53 UTC, pepelsbey commented
> Нативным объектом `Date` в пару строк это не сделать или может я что-то упускаю?

Да, есть современные API для `Date`, котрые позволяют вывести нужный формат очень просто и без библиотек.

[Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)

2021-11-13 10:42 UTC, slavarazum commented
> Да, есть современные API для `Date`, котрые позволяют вывести нужный формат очень просто и без библиотек.
> 
> [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)

Насколько я вижу с `DateTimeFormat` API тоже будет не просто сгенерировать 10 подходящих форматов без дополнительных манипуляций. Нельзя указать разделитель в виде `-` или подобрать формат близкий к ISO8601. Может есть пример?

2021-11-15 20:36 UTC, nlopin commented
Вывод даты через `DateTimeFormat` опирается на локаль пользователя. В зависимости от неё и выбираются разделители. Дефис вставить быстро не получится, нужно получать отформатированные данные массивом и склеивать их. (есть ещё вариант собрать кастомную локаль)

В русской локали в качестве разделителя в датах используются точки `31.12.2021`.

ISO8601 универсальный формат, ему не нужна локализация, поэтому он доступен как общий метод `(new Date()).toISOString()`

2021-11-15 20:41 UTC, slavarazum commented
@pepelsbey Есть ощущение, что примеры на JS будут избыточны в такой реализации, что думаете?

2021-11-16 05:52 UTC, nlopin commented
Согласен, создал задачу на новую статью в разделе JS (#2416)

2021-11-17 09:20 UTC, solarrust commented
Тогда предлагаю сейчас не давать примеры на JS, а при появлении статьи дать на неё ссылку. Пометку в задачке оставила. 

Пожалуйста, зарезолви те обсуждения, которые уже не актуальны, чтобы было понятно, что по ним правки уже внесены.

2021-11-17 10:19 UTC, slavarazum commented
Актуализировал состояние.
Остался один комментарий по поводу нюансов работы, только информации мало. Как с ним работает браузер деталей не нашёл.

2021-11-18 08:32 UTC, solarrust commented
> Актуализировал состояние.
> Остался один комментарий по поводу нюансов работы, только информации мало. Как с ним работает браузер деталей не нашёл.

Используй всё то, что сказано в цитате. Можно ещё дополнить найденными примерами, если есть. Просто не хочется вставлять такую большую цитату от третьего лица.

2021-11-26 07:14 UTC, solarrust commented
@slavarazum привет! Планируешь добить этот пул-реквест?

2021-11-29 09:32 UTC, solarrust commented
@slavarazum дай, пожалуйста, знать, будешь ли ты заканчивать работу над статьёй. Очень жду =)

2021-11-29 10:10 UTC, slavarazum commented
@solarrust привет! Да, сегодня отправлю 🙂

2021-11-29 20:46 UTC, slavarazum commented
@solarrust Переформатировал раздел. Добавил список, убрал цитирование. Что думаешь?

2021-11-30 15:15 UTC, solarrust reviewed
В целом мне уже очень нравится! 

Предложила уточнить один момент про валидность значения. 

И ещё вопрос: как ты считаешь, точно ли нужно каждый пример делать под своим заголовком? Поясню свои сомнения. В текущем варианте все заголовки попадают в боковое меню. Это то поведение, которое предполагалось? Если нет, то можно заголовки заменить на жирный текст. Давай обсудим =)

2021-11-30 15:15 UTC, solarrust commented on html/time/index.md
> +Который можно опустить, если внутри тэга валидное значение атрибута `datetime`:
Вот тут упоминается «валидное значение», но нигде нет пояснения что машина почитает валидным. Давай допишем буквально предложение с валидным синтаксисом. Типа «Валидным значением считается YYYY-MM-DD». Чтобы даже если ни один из примеров, приведённых в статье, не подошёл всё же можно было составить собственное значение.

2021-12-04 08:38 UTC, pepelsbey submitted a review, later dismissed
Осталось немного, чтобы дожать :)

2021-12-04 08:38 UTC, pepelsbey commented on html/time/index.md
> +## 10 способов указать время правильно
Этот заголовок отваливается от контента статьи. Он какой-то слишком кликбейтный и не выдержит появление ещё одного способа в списке. Лучше бы

```suggestion
## Примеры в машинном формате

Содержимое атрибута `datetime` для машин чаще всего и генерируется машиной, но если вы человек и вам нужно указать его самостоятельно, либо написать скрипт для такого вывода, эти примеры для вас.
```

А дальше лучше показать более расширенные примеры, в контексте:

````md
### Год и месяц

```html
Холодный <time datetime="2014-06">июнь 14-го</time>
```

Год перед месяцем.
````

2021-12-06 18:18 UTC, slavarazum commented
@solarrust Да, согласен 👍 Отформатировал жирным. Не сильно шумно получилось?

@pepelsbey Поменял заголовок, так действительно лучше.
Только я сомневаюсь насчёт примеров. По идее этот раздел показывает конкретно форматы и есть ощущение, что примеры с html будут лишними. Также этот раздел станет похожим на раздел "Пример".

Ещё смущает оформление примеров в одну строку блочным кодом, т.к. он добавляет дополнительные элементы как: язык, скопировать, номер строки который всегда будет 1:
<img width="837" alt="CleanShot 2021-12-06 at 20 13 37@2x" src="https://user-images.githubusercontent.com/5820718/144899654-c8dfcf7c-dfcf-417a-a62e-600b25bfbd04.png">

Может это будет слишком громоздко для этого раздела?

2021-12-07 09:09 UTC, solarrust commented
> может стоит добавить полное описание помимо общей строки, например:

Мне нравится это предложение. Такое пояснение поможет научиться читать и писать любые нужные даты =)

2021-12-07 16:28 UTC, slavarazum commented
@solarrust Супер 👍 Есть предложения по поводу форматирования этого списка? Оформление примеров, кратких описаний или в таком формате хорошо? :)

2021-12-08 16:08 UTC, solarrust commented
Кажется, в случае с _расшифровкой_ частей будет удобен именно список.

2021-12-09 17:13 UTC, slavarazum commented
Залил детальный разбор.
Добавил форматирование для обозначений, что бы лучше визуально разделить.

2021-12-13 08:57 UTC, solarrust commented on html/time/index.md
> +- `T`: Разделитель даты и времени;
```suggestion
- `T`: разделитель даты и времени;
```

2021-12-13 08:57 UTC, solarrust commented on html/time/index.md
> +- `TZD`: Time Zone Designator (прим. +02:00 для Каира).
По русски бы обозвать =)

2021-12-13 08:57 UTC, solarrust commented on html/time/index.md
> +- `T`: Разделитель даты и времени;
Можно прямо тут упомянуть о замене на пробел м дальше в тексте не повторяться.

2021-12-14 11:31 UTC, skorobaeus commented on html/time/demos/basic/index.html
> +      font-size: 16px;
```suggestion
      font-size: 18px;
```

2021-12-14 11:32 UTC, skorobaeus commented on html/time/demos/basic/index.html
> +      height: 40px;
```suggestion
      width: 50px;
      height: 50px;
```

2021-12-14 11:32 UTC, skorobaeus commented on html/time/demos/basic/index.html
> +      font-size: 14px;
```suggestion
      font-size: 22px;
```

2021-12-14 11:34 UTC, skorobaeus commented on html/time/demos/basic/index.html
> +      font-size: 14px;
```suggestion
      font-size: 18px;
```

2021-12-14 11:34 UTC, skorobaeus commented on html/time/demos/basic/index.html
> +      font-size: 12px;
```suggestion
      font-size: 18px;
```

2021-12-14 11:35 UTC, skorobaeus commented on html/time/index.md
> +<iframe title="Точное время" src="demos/basic/" height="150"></iframe>
```suggestion
<iframe title="Точное время" src="demos/basic/" height="200"></iframe>
```

2021-12-14 11:38 UTC, skorobaeus requested changes
Демка класс!
Я предлагаю увеличить размеры шрифта и аватарки. Дизайн сайта щедрый, более крупные элементы демки будут выглядеть органичнее.

2021-12-14 12:30 UTC, solarrust approved these changes
Собственно, осталось только демку добить и можно публиковать =)
Спасибо!

2021-12-14 13:54 UTC, slavarazum commented
@skorobaeus Спасибо 🙂 Увеличил размеры.

@solarrust Получается готово 🎉

2021-12-14 14:06 UTC, solarrust commented
Ну прямо кайф! Осталось добавить в папку _people/_ файлик с твоим ником, в котором будет твоё имя и ссылочка на любую соц.сеть. Чтобы в блоке с автором статьи красиво выводилось =)

2021-12-14 14:21 UTC, slavarazum commented
@solarrust 🧡
А я думаю, почему ссылочка не оформляется :)
Готово.

2021-12-14 14:24 UTC, solarrust commented
Получилось космически круто! Пиши ещё =)

2021-12-14 14:25 UTC, merged

2021-12-14 14:35 UTC, slavarazum commented
Спасибо всем участникам за помощь в оформлении и рекомендации 👍
Также спасибо команде за современную доку по фронтенд-технологиям, этого точно не хватало сообществу!

Было приятно принять участие, не буду упускать такую возможность и в будущем 🙂