Добавляет статью про коллекцию forms
doka-guide/content pull request #2424
Opened 2021-11-16 13:19 UTC by vchychuzhko

Fix #2131

2021-11-16 14:54 UTC, tachisis approved these changes
Апрув на изменения в словаре.

2021-11-17 06:47 UTC, nlopin requested changes
Классный материал. Дополируем структуру и будет вообще огнище

2021-11-17 06:47 UTC, nlopin commented on js/forms/index.md
> +## Подсказки
В разделе JS не используется раздел «подсказки», давай превратим его в раздел «На практике» и выберем туда только практические советы, а остальной материал включим в статью

2021-11-17 06:47 UTC, nlopin commented on js/forms/index.md
> +💡 Коллекция является доступной только для чтения. Любые попытки что-то добавить или переопределить не будут иметь эффекта.
это очень важная информация, давай её перенесём в раздел «Кратко»:

> Поле объекта `document`, которое хранит коллекцию всех элементов [`<form>`](/html/form) содержащихся на текущей странице.
> Коллекция доступна только для чтения.

2021-11-17 06:47 UTC, nlopin commented on js/forms/index.md
> +💡 В коллекции хранятся все формы страницы, но лишь к тем, у которых прописан атрибут `name` или `id`, можно обращаться по имени или идентификатору соответственно.
про это мы рассказали выше, думаю не стоит повторяться

2021-11-17 06:47 UTC, nlopin commented on js/forms/index.md
> +💡 Формы, которым указывается атрибут `name`, также попадают и в сам объект `document`. В таком случае, к ним можно обращаться и напрямую, в обход коллекции всех форм: `document.myFormName`.
это классный инсайт, предлагаю унести в раздел «В работе»

2021-11-17 06:47 UTC, nlopin commented on js/forms/index.md
> +💡 Важно отметить, что имя и идентификатор не конфликтуют, позволяя обращаться к форме обоими способами.
Непонятно, что тут подразумевается под конфликтом. Если у меня будет одна форма с id="test", а другая с name="test", то конфликт будет и, если я не ошибаюсь, победит айдишник:

> Returns the specific node whose ID or, as a fallback, name matches the string specified by name.

2021-11-17 06:47 UTC, nlopin commented on js/forms/index.md
> +## Пример
Пример выпадает из повествования и повторяет то, что мы уже рассказали выше. Давай сольем этот раздел («Пример» и «Доступ к формам») с разделом «Как пользоваться» и заменим тот пример, что есть там сейчас.

Так у нас и пример будет большой, и полный рассказ про доступ к формам

2021-11-17 06:47 UTC, nlopin commented on js/forms/index.md
> +```
Это надо унести в раздел «На практике». Пройтись можно и не преобразовывая в массив, с помощью for...of:

```js
for (const form of document.forms) {
  // do stuff
}
```

2021-11-17 06:47 UTC, nlopin commented on js/forms/index.md
> +В результате обращения к полю, мы получим коллекцию [HTMLCollection](/js/htmlcollection-and-nodelist), которая очень напоминает массив, но позволяет также обращаться к элементам по их имени или идент
Думаю, здесь важно подчеркнуть, что коллекция не статическая: 

```suggestion
В результате обращения к полю, мы получим живую коллекцию [HTMLCollection](/js/htmlcollection-and-nodelist), которая очень напоминает массив, но позволяет также обращаться к элементам по их имени или идентификатору.
```

2021-11-17 07:11 UTC, vchychuzhko commented on js/forms/index.md
> +💡 Важно отметить, что имя и идентификатор не конфликтуют, позволяя обращаться к форме обоими способами.
Подразумевалось, что один из них не будет выключать другой, а ситуация с одинаковыми значения в принципе не конфликтная, потому что визуально не важно используется имя или идентификатор - обращение все равно виглядит одинаково.
Но в целом согласен, могу уточнить формулировку. Или лучше вовсе убрать?

2021-11-17 07:13 UTC, vchychuzhko commented on js/forms/index.md
> +💡 Формы, которым указывается атрибут `name`, также попадают и в сам объект `document`. В таком случае, к ним можно обращаться и напрямую, в обход коллекции всех форм: `document.myFormName`.
имеешь ввиду перенести в раздел "На практике"? сохраняя текст, как обычный абзац, верно?

2021-11-17 07:16 UTC, vchychuzhko commented on js/forms/index.md
> +## Пример
а как в таком случае стоит оформить пример? разве он не должен служить наглядным закреплением выше описаной информации - по моему, без повторения не обойтись. И возможно в случае переноса блок "Как пишется" станет слишком большим и громоздким.

2021-11-21 19:34 UTC, nlopin commented on js/forms/index.md
> +💡 Формы, которым указывается атрибут `name`, также попадают и в сам объект `document`. В таком случае, к ним можно обращаться и напрямую, в обход коллекции всех форм: `document.myFormName`.
Да, это раздел «на практике»

2021-11-21 19:35 UTC, nlopin commented on js/forms/index.md
> +💡 Важно отметить, что имя и идентификатор не конфликтуют, позволяя обращаться к форме обоими способами.
Можно не убирать, но кажется aside оно точно не заслуживает

2021-11-21 19:37 UTC, nlopin commented on js/forms/index.md
> +## Пример
Так как у нас взаимодействие меджу html и js, то думаю негромоздкого примера не выйдет — нужно показать и то, и другое, чтобы понять, как они связаны.

Давай я его перенесу сам?

2021-11-21 21:14 UTC, vchychuzhko commented on js/forms/index.md
> +## Пример
я кажись понял, что ты имеешь ввиду, сейчас попробую реструктурировать

2021-11-22 17:03 UTC, vchychuzhko commented on js/forms/index.md
> +## Пример
@nlopin просмотри теперь, пожалуйста.(просто не могу повторно запросить ревью)

2021-11-23 07:09 UTC, nlopin commented on html/form/index.md
> +  - vchychuzhko
Тут, к сожалению, слишком маленький вклад, чтобы считаться контрибьютором. Контрибьютором считается тот, кто внёс значительные изменения в статью/добавил демку/схему


```suggestion
```

2021-11-23 07:12 UTC, nlopin approved these changes
Огнище!

2021-11-23 07:17 UTC, vchychuzhko commented on html/form/index.md
> +  - vchychuzhko
я также вносил дополнения по атрибуту novalidate в рамках пулл реквеста по одноименной статье, все раноне считается?(

2021-11-23 07:18 UTC, nlopin commented on html/form/index.md
> +  - vchychuzhko
@solarrust помоги

2021-11-23 07:40 UTC, solarrust commented on html/form/index.md
> +  - vchychuzhko
Привет! Ты автор статьи про `novalidate`. Там твой вклад неоспорим! 🤗
В этом пул-реквесте добавляется только предложение со ссылкой. Это существенно не меняет суть статьи, не дополняет её. Я очень благодарная за эту правку, но в контрибьюторах статьи мы отмечаем существенный вклад в материал. Иначе этот список сильно разрастётся за счёт тех, кто правит опечатки или расставляет запятые. Надеюсь на твоё понимание 🙏

2021-11-23 08:19 UTC, bespoyasov approved these changes
Отличная статья! 👍 

Я подумал, а стоит ли нам добавить отдельную практику с получением родительской формы через свойство `.form` на элементе формы, @nlopin?

Я имею в виду такой случай:

```html
<form>
  <input id="input" type="text">
</form>
```

```js
const form = document.getElementById('input').form;
// HTMLFormElement, родительская форма.
```

2021-11-23 19:14 UTC, nlopin commented
> добавить отдельную практику с получением родительской формы через свойство .form 

Да, в практике классно будет

2021-11-23 19:23 UTC, vchychuzhko commented
> > добавить отдельную практику с получением родительской формы через свойство .form
> 
> Да, в практике классно будет смотреться. @vchychuzhko добавишь? И уже публиковать будем

но ведь это не относится к полю document, или я что-то упускаю? это нужно уже к самим елементам добавлять (Element.form !== document.forms)

2021-11-23 19:35 UTC, nlopin commented
Согласен, можно пролинковать, когда появится статья о поле `form`

2021-11-23 19:37 UTC, solarrust approved these changes

2021-11-24 05:43 UTC, merged