Добавляет статью про Pixel Perfect
doka-guide/content pull request #2428
Opened 2021-11-16 15:05 UTC by xpleesid

Fix #390 
Касательно выводов про требования к точности при использовании pixel perfect получилось, имхо, слегка холиварно. жду комментариев)

2021-11-17 08:49 UTC, solarrust commented
Привет! Спасибо большое за статью!
Первое, на что обратила внимание — не там разместил файлы статьи. Это всё же не про инструменты, а про подходы и принципы вёрстки. Пожалуйста, переложи статью из _tools/_ в _html/_.

2021-11-18 08:21 UTC, solarrust reviewed
Привет! Спасибо за статью 🔥
Получилось очень субъективно, прямо чувствуется твоя нелюбовь к этой парадигме =)
Давай попробуем сделать эту статью чуть менее эмоциональной. 

Я бы кроме упомянутого расширения (хоть оно и самое удобное) добавила способ с наложением картинки. Поговорила бы о том, как делать PP вёрстку при адаптиве. Упомянула бы о здравом смысле. Бывают ситуации, когда рука дизайнера дрогнула и это не повод городить подгоняющие стили, а повод спросить у дизайнера, точно ли важно, что везде кнопки 15 пикселей, а тут 18.
Сказала бы как важно искать закономерности в макете, в размерах и отступах. 
Стоит донести важность освоения этого подхода на начальных этапах обучения, со временем вырабатывается глазомер.
Мне понравилась с этой точки зрения [вот эта статья](https://htmlacademy.ru/blog/boost/tools/pixel-perfect). Там, например, даны конкретные значения допустимых расхождений.

Что думаешь? Давай обсудим =)

2021-11-18 08:21 UTC, solarrust commented on html/pixel-perfect/index.md
> +А нужно ли вообще постоянно стремиться к идеалу? Вопрос достаточно холиварный. Есть два противоположных мнения — кто-то считает, что любая вёрстка должна идеально совпадать с макетом, а иначе какой с
Тут я бы сказала, что всё зависит от требований того, кто задачу ставит. У вас могут быть разные мнения, но для того, чтобы работа была принята ты будешь вынужден соблюсти требования заказчика.

2021-11-18 08:21 UTC, solarrust commented on html/pixel-perfect/index.md
> +А нужно ли вообще постоянно стремиться к идеалу? Вопрос достаточно холиварный. Есть два противоположных мнения — кто-то считает, что любая вёрстка должна идеально совпадать с макетом, а иначе какой с
И для разных видов проектов вёрстка пиксель-в-пиксель имеет разную важность. Если это презентационный вау-проект, где все положения элементов реально обоснованы и выверены, то там нужно стремиться к максимальному совпадению. А вот в какой-нибудь админке достаточно чтобы было аккуратно.

2021-11-18 08:21 UTC, solarrust commented on html/pixel-perfect/index.md
> +3. Обговорите требования к точности перед началом работы. При необходимости объясните коллегам, почему абсолютное совпадение макета и вёрстки не всегда достижимо, и что в этом нет ничего сильно страш
```suggestion
1. Используйте Pixel Perfect подход, чтобы найти отличия получившейся вёрстки от исходного макета.
1. Не страдайте излишним перфекционизмом — обращайте внимание только на значимые отличия.
1. Обговорите требования к точности перед началом работы. При необходимости объясните коллегам, почему абсолютное совпадение макета и вёрстки не всегда достижимо, и что в этом нет ничего сильно страшного.
```

2021-11-18 08:21 UTC, solarrust commented on html/pixel-perfect/index.md
> +
```suggestion
- Если скорость разработки сильно важна. Например, мы делаем стартап, и если завтра не выйдем на рынок, то это сделают конкуренты. В таком случае _какая-нибудь_ вёрстка, но сделанная быстро, гораздо лучше идеальной, на полировку которой ушли драгоценные часы.
- Если точность вёрстки не важна вообще. Например, мы делаем прототип продукта, который потом будет ещё 10 раз переделываться. Если на каждой итерации вылизывать вёрстку до идеала, то мы потратим кучу времени, которое могло бы пойти на разработку нового функционала.
- Если все участники процесса понимают, для чего нужен Pixel Perfect и чего с его помощью мы пытаемся добиться. Иногда бывает, что в макете случайно съехал в сторону один из пунктов меню, и от разработчиков требуют добавлять отступ, чтобы было «в точности как на макете». И тогда появляется ужасный код вида `.list-item:nth-child(4) { margin-left: 1px; }` — так делать, конечно, не стоит.
- Если точная вёрстка в принципе достижима. Например, у графических редакторов, таких как фотошоп, рендеринг шрифтов может отличаться от браузерного. И тогда мы не сможем _адекватно_ добиться, чтобы текст в браузере выглядел в точности так, как в фотошопе — придётся играться с [`letter-spacing`](/css/letter-spacing/), разделять текст на лишние блоки и заниматься прочей уличной магией. Таких манипуляций тоже стоит избегать.

```

2021-11-18 08:21 UTC, solarrust commented on html/pixel-perfect/index.md
> +- Если все участники процесса понимают, для чего нужен Pixel Perfect и чего с его помощью мы пытаемся добиться. Иногда бывает, что в макете случайно съехал в сторону один из пунктов меню, и от разраб
Вот это странно. Случайно съехал → пойди и найди причину почему съехал. Зачем костыли?

2021-11-19 17:08 UTC, xpleesid commented
Привет, спасибо за комментарии! поправил в соответствии с ними, но пока не стал резолвить обсуждения, чтобы их не потерять. возможно, мы к ним еще вернемся)

2021-11-19 17:10 UTC, xpleesid commented on html/pixel-perfect/index.md
> +- Если все участники процесса понимают, для чего нужен Pixel Perfect и чего с его помощью мы пытаемся добиться. Иногда бывает, что в макете случайно съехал в сторону один из пунктов меню, и от разраб
да, изначально я не совсем ясно этот сценарий описал. немного переписал этот пункт, чтобы был понятен контекст. основано на реальных событиях, к сожалению)

2021-11-22 09:56 UTC, solarrust reviewed
Покомментировала ещё.

@pepelsbey очень хочу услышать твоё мнение об общем тоне статьи. Приходи, как будет минутка =)

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +- Во-первых, хотя практически весь текст немного смещён, в этом нет ничего криминального. Дело в том, что в графических редакторах, в которых создаётся дизайн, процесс рендеринга шрифтов может отлича
```suggestion
Во-первых, небольшое смещение текста допустимо. Процесс рендеринга шрифта в графических редакторах и в браузерах отличается. Из-за этого заголовки карточек визуально отличаются, хотя и в макете и в вёрстке у них одинаковые параметры.
```

Важную мысль лучше выносить вперёд, а потом пояснять её. Не надо оставлять её на последнее предложение.

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +- Во-вторых, основной целью Pixel Perfect подхода является, как бы это парадоксально не звучало, не идеальная, а _приемлемая_ точность. Нам не нужно добиваться полного совпадения, нам нужно добиватьс
```suggestion

Во-вторых, критичны только серьёзные расхождения. Основной целью Pixel Perfect подхода является, как бы это парадоксально не звучало, не идеальная, а _приемлемая_ точность. Не нужно добиваться полного совпадения, нужно добиться результата, при котором расхождения не заметны для пользователя. Сейчас у большинства людей стоят мониторы размером 1920 на 1080 пикселей. Если заголовок займёт, допустим, не 187, а 189 пикселей в ширину, большинство людей этого не заметит. Обращайте внимание на отступы между блоками, выравнивание, размеры иконок и так далее.
```

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +Когда мы заметили все отличия, давайте теперь устраним их. Для большей наглядности также слегка сожмём заголовки при помощи [`letter-spacing`](/css/letter-spacing/) — как упоминалось ранее, это абсол
```suggestion
Исправим критичные расхождения. Для наглядности применим к заголовкам [`letter-spacing`](/css/letter-spacing/). Это не критично, но для наглядности будет полезно.
```

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +В итоге получим такой результат:
```suggestion
Результат:
```

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +Получилось практически идеально:
```suggestion
При сравнении с макетом видно, что вёрстка совпадает с ним практически идеально:
```

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +Зачастую наш сайт должен адаптироваться под разные разрешения — обычно это мобильные экраны (шириной до 480px), планшеты (до 1024px), ноутбуки (до 1400px) и десктопы. В таком случае дизайнер делает н
```suggestion
Современный сайт должен адаптироваться под разные разрешения экранов. Обычно это мобильные экраны, планшеты, ноутбуки и десктопы. В таком случае дизайнер делает по одному макету на каждое необходимое разрешение. Используйте инструменты разработчика чтобы проверить вёрстку на разных разрешениях. Их можно открыть несколькими способами:
```

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +- <kbd>Control + Shift + I</kbd> — на Linux
```suggestion
- <kbd>Control</kbd> + <kbd>Command</kbd> + <kbd>I</kbd> — на macOS;
- <kbd>F12</kbd> — на Windows;
- <kbd>Control</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> — на Linux.
```

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +Затем нам нужно установить необходимое разрешение. Можно задать его вручную или выбрать один из предустановленных шаблонов.
```suggestion
Нажимаем на иконку включения отзывчивого дизайн и выбираем нужный размер экрана. Можно задать размер вручную или выбрать один из предустановленных шаблонов.
```

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +![Адаптив](images/adaptive.jpg)
```suggestion
![Окно браузера с открытыми инструментами разработчика и включенным режимом отзывчивого дизайна](images/adaptive.jpg)
```

2021-11-22 09:56 UTC, solarrust commented on html/pixel-perfect/index.md
> +После чего делаем всё так же, как раньше. Открываем расширение и добавляем картинку для соответствующего разрешения, после чего ищем отличия в вёрстке.
```suggestion
После чего делаем всё так же, как раньше. Открываем расширение и добавляем картинку макета для соответствующего разрешения, после чего ищем отличия в вёрстке.
```

2021-11-23 16:31 UTC, xpleesid commented on html/pixel-perfect/index.md
> +1. И такой способ есть. Браузерные расширения, такие как [PerfectPixel](https://www.welldonecode.com/perfectpixel/) берут эту рутину на себя. PerfectPixel доступен для установки в Chrome, Opera, Edge
Выделил в абзацы, мне кажется, выделять в подразделы будет оверкиллом, так как первые два способа (надеюсь) никто не будет использовать на практике, а про расширения дальше подробно раскрыто

2021-11-24 17:53 UTC, tachisis approved these changes
Апрув на изменения в словаре

2021-12-03 19:23 UTC, pepelsbey requested changes
Полезная статья! Спасибо :)

@solarrust, мне кажется, что тон не слишком критический, достаточно взвешенный.

Можно правда его чуть облегчить, добавить понимания, что ли :) Я бы добавил где-то, что это один из самых простых способов проверить соответствие макету, если у заказчика нет подходящих знаний, чтобы оценить вёрстку фрилансера как-нибудь иначе. То есть начинающий или просто плохой верстальщик не сумеет сделать похоже на макет и это его выдаст. Это конечно не защищает от отстутствия системы в коде, но хоть что-то.

Также под заголовком «Всегда ли нужен Pixel Perfect» получаются очень массивные списки и даже тяжёлый однострочный пример кода. Я бы разбил это просто на отдельные абзацы. Всё сразу станет чуть легче и появится место для вставки блока кода.

2021-12-03 19:23 UTC, pepelsbey commented on html/pixel-perfect/index.md
> +## Всегда ли нужен Pixel Perfect
```suggestion
После чего делаем всё так же, как раньше. Открываем расширение и добавляем картинку макета для соответствующего разрешения, после чего ищем отличия в вёрстке.

## Всегда ли нужен Pixel Perfect
```

2021-12-03 19:23 UTC, pepelsbey commented on html/pixel-perfect/index.md
> +- Мы делаем презентационный вау-проект, когда положение каждого элемента выверено до миллиметра.
```suggestion
- Мы делаем презентационный вау-проект, когда положение каждого элемента выверено до пикселя.
```

2021-12-08 16:09 UTC, solarrust approved these changes
От меня аппрув, мне всё нравится!

2021-12-13 15:05 UTC, pepelsbey commented
@solarrust [сделал правки](https://github.com/doka-guide/content/pull/2428/commits/f8cdff4b245272a9d7ee7c7dc7390c62a3a841f0), глянь, плиз:

- Отпилил шутку про суслика, её уже могут не знать, а дальше будет только хуже.
- Расписал альты получе.
- Поправил название панели в DevTools.

2021-12-13 15:06 UTC, pepelsbey approved these changes

2021-12-14 12:29 UTC, solarrust approved these changes

2021-12-14 13:05 UTC, solarrust reviewed
По совету @tachisis переименовала статью в соответствии с правилами русского языка =)

2021-12-14 13:05 UTC, solarrust commented on html/pixel-perfect/index.md
> +title: "Pixel Perfect"
```suggestion
title: "Подход «Pixel Perfect»"
```

2021-12-14 13:05 UTC, solarrust commented on html/pixel-perfect/demos/incorrect/index.html
> +  <title>Вёрстка с незначительными отклонениями — Pixel Perfect — Дока</title>
```suggestion
  <title>Вёрстка с незначительными отклонениями — Подход «Pixel Perfect» — Дока</title>
```

2021-12-14 13:05 UTC, solarrust commented on html/pixel-perfect/demos/correct/index.html
> +  <title>Вёрстка с исправлениями — Pixel Perfect — Дока</title>
```suggestion
  <title>Вёрстка с исправлениями — Подход «Pixel Perfect» — Дока</title>
```

2021-12-14 13:14 UTC, merged

2021-12-14 13:14 UTC, solarrust commented
Ура! Спасибо за крутую статью! Пиши ещё 🖤