Редактирует статью про области видимости
doka-guide/content pull request #2441
Opened 2021-11-17 20:45 UTC by tachisis

2021-11-17 20:47 UTC, tachisis commented on js/closures/index.md
>  // Объявление переменной a «поднялось» наверх,
В это примере кода я не осилила разобрать его на нарратив и собственно код. @bespoyasov может быть, ты сможешь?

2021-11-17 20:48 UTC, tachisis commented on js/closures/index.md
>  ### IIFE
Этому разделу хотелось бы более информативный заголовок и подводку. Я не поняла, почему здесь рассказывается о таких функциях.

2021-11-17 20:52 UTC, tachisis commented on js/closures/index.md
> +## «Поднятие» переменных (hoisting)
В этом разделе подзаголовки use sctrict и let и const тоже какие-то неинформативные. Может быть, не стоит вообще выделать их как подзаголовки, а просто цельным текстом рассказать о борьбе со всплытием под заголовком «Как бороться» или типа того?

2021-11-17 20:53 UTC, tachisis commented
Также у этой статьи раздел практики полностью дублирует то, что есть уже в самой статье, тем более, что один автор. Мне кажется, это излишне. Если там есть какие-то детали, их лучше перенести в тело статьи, а практику удалить.

2021-11-18 16:27 UTC, bespoyasov approved these changes
Пару идей вкинул, но в целом согласен 👍

2021-11-18 16:27 UTC, bespoyasov commented on js/closures/index.md
> +Переменная в примере сейчас находится в глобальной области видимости.
Может тогда перенесём описание в «над кодом»? Мне кажется, предварять код описанием лучше, чем объяснять после, потому что мы так можем «прогреть» читателей, им придётся меньше парсить кода в голове самим.

2021-11-18 16:27 UTC, bespoyasov commented on js/closures/index.md
> +Глобальный объект `window` — это объект, который даёт доступ к Web API браузера. `window` рекурсивно «содержит сам себя», потому что все глобальные объекты находится в `window`:
```suggestion
Глобальный объект `window` — это объект, который даёт доступ к Web API браузера. `window` рекурсивно «содержит сам себя», потому что все глобальные объекты находятся в `window`:
```

2021-11-18 16:27 UTC, bespoyasov commented on js/closures/index.md
>  ### IIFE
IIFE часто использовались для изоляции разных модулей. Мы можем, наверное, так в заголовке и написать 🤔

2021-11-18 16:27 UTC, bespoyasov commented on js/closures/index.md
> +## «Поднятие» переменных (hoisting)
Можно и так, да.

2021-11-18 16:27 UTC, bespoyasov commented on js/closures/index.md
>  // Объявление переменной a «поднялось» наверх,
Если «объявить» переменную в функции без ключевого `var`, то JS «создаст» этот `var` в начале снаружи функции, а внутри функции просто присвоит значение. 

Если же использовать `var` внутри функции, то такого не произойдёт, переменная будет локальной. 

До переменной в первом случае можно достучаться «извне» функции, потому что она как бы «есть снаружи» из-за поднятия. Во втором — нельзя, потому что переменная локальная для функции.

2021-11-18 16:27 UTC, bespoyasov commented on js/closures/index.md
>  // Объявление переменной a «поднялось» наверх,
Hope this makes sense 😃

2021-11-18 19:32 UTC, tachisis commented on js/closures/index.md
> +Переменная в примере сейчас находится в глобальной области видимости.
Да, размещай нарратив так, как тебе кажется правильным, автору виднее!

2021-11-18 19:35 UTC, tachisis commented on js/closures/index.md
>  ### IIFE
Да, если так и написать в заголовке, будет понятнее!

2021-11-18 19:37 UTC, tachisis commented on js/closures/index.md
> +## «Поднятие» переменных (hoisting)
Пожалуйста, можешь сам поменять заголовки и объединить нарратив? Там может придется как-то текст чутка изменить для слитности, автору виднее, как это сделать.

2021-11-18 19:37 UTC, tachisis commented on js/closures/index.md
>  // Объявление переменной a «поднялось» наверх,
И вот тут тоже можешь сам внести правку, пожалуйста?

2021-11-19 07:55 UTC, nlopin commented on js/closures/index.md
> +Переменная в примере сейчас находится в глобальной области видимости.
тут будет правка?

2021-11-21 16:44 UTC, nlopin commented on js/closures/index.md
> +## «Поднятие» переменных (hoisting)
@tachisis я поменял заголовки на «Проблема» (говорим, почему это плохо) и «Как бороться» (use strict, let, const). Так норм?

2021-11-21 17:40 UTC, nlopin commented
@tachisis я поправил текст. Посмотри на адекватность, пожалуйста

2021-11-21 19:33 UTC, nlopin approved these changes

2021-11-22 06:06 UTC, bespoyasov requested changes

2021-11-22 06:06 UTC, bespoyasov commented on js/closures/practice/bespoyasov.md
> -Используйте скобки, чтобы обозначить блок вычислений в `switch`, если он большой:
Давайте последний комит откатим и вернём практику в изначальном виде?

Мне кажется, не стоит отсюда ничего убирать. Не все знают про скобки, очень мало знают про IIFE. Тем более, что это _практика_, а не текст статьи. Ничего страшного, если будет чуть-чуть повтора. 

Скобками я чуть ли не каждый день пользуюсь. Ну и let / const и «не сойти с ума» лучше держать в конце, потому что это панчлайн :—)

2021-11-22 20:51 UTC, tachisis commented on js/closures/practice/bespoyasov.md
> -Используйте скобки, чтобы обозначить блок вычислений в `switch`, если он большой:
По итогам нашего сегодняшнего контентного созвона все-таки хочу настоять на том, что дублировать информацию в разделе «На практике» излишне. Мы договорились, что там у нас будут только авторские мнения, авторские советы и рецепты. При этом если эти советы уже даны в тексте статьи, зачем же их дублировать? Это все же не отдельный обособленный блок, это полноценная часть статьи, вряд ли кто-то ходит и читает исключительно разделы «на практике».

Но давайте для третьего мнения призовем @pepelsbey

2021-11-23 18:57 UTC, nlopin commented on js/closures/practice/bespoyasov.md
> -Используйте скобки, чтобы обозначить блок вычислений в `switch`, если он большой:
@tachisis мы вообще хотим в статьях раздел «на практике»? Ведь статья — это не просто справочная информация, там уже в задумке сидит мнение автора

2021-11-23 19:15 UTC, bespoyasov commented on js/closures/practice/bespoyasov.md
> -Используйте скобки, чтобы обозначить блок вычислений в `switch`, если он большой:
Для меня практики в статье — это «подытог» без объяснений в виде того, что надо вынести из статьи в каждодневную работу.

2021-11-24 18:01 UTC, tachisis commented on js/closures/practice/bespoyasov.md
> -Используйте скобки, чтобы обозначить блок вычислений в `switch`, если он большой:
Смотрите, мы по итогам https://github.com/doka-guide/content/issues/2266 на контентом созвоне с лидами договорились, что в разделе «На практике» у нас — _мнения, рецепты и советы из личной практики разработчика, часто с примерами кода или демками._

Может быть, нам просто немного переписать этот раздел, чтобы это было личное мнение? Вот как ты, Саша, выше и написал: «Например, скобками я чуть ли не каждый день пользуюсь. IIFE тоже бывает иногда приходится». Тогда мы убьем двух зайцев — оставим раздел, но он не будет просто дублированием информации, а будет личным мнением. Может быть в процессе переписывания тебе даже захочется его чуть расширить, рассказать, в каких случаях ты сталкиваешься с этим?

2021-11-24 20:29 UTC, bespoyasov commented on js/closures/practice/bespoyasov.md
> -Используйте скобки, чтобы обозначить блок вычислений в `switch`, если он большой:
> Тогда мы убьем двух зайцев — оставим раздел, но он не будет просто дублированием информации, а будет личным мнением. Может быть в процессе переписывания тебе даже захочется его чуть расширить, рассказать, в каких случаях ты сталкиваешься с этим?

Да, звучит хорошо. Займусь этим.

2021-11-25 08:36 UTC, bespoyasov commented on js/closures/practice/bespoyasov.md
> -Используйте скобки, чтобы обозначить блок вычислений в `switch`, если он большой:
Добавил. @tachisis, @nlopin, посмотрите, пожалуйста?

2021-11-25 16:46 UTC, tachisis commented on js/closures/practice/bespoyasov.md
> +Используйте IIFE для изолированных модулей или для эмуляции top-level await там, где его ещё нет:
@bespoyasov тут не надо ничего завернуть в бэктики?

2021-11-25 16:46 UTC, tachisis commented on js/closures/practice/bespoyasov.md
> -Используйте скобки, чтобы обозначить блок вычислений в `switch`, если он большой:
Мне нравится, спасибо!

2021-11-25 19:38 UTC, bespoyasov commented on js/closures/practice/bespoyasov.md
> +Используйте IIFE для изолированных модулей или для эмуляции top-level await там, где его ещё нет:
Не, top-level await здесь не код, поэтому можно не укутывать в бэктики :–) 

(Можно перевести как «верхнеуровневый await», но я хз, надо ли.)

2021-11-26 20:15 UTC, tachisis commented
@bespoyasov я все зарезолвила! Помержи, когда будешь готов!

2021-11-29 07:42 UTC, bespoyasov approved these changes
Спасибо!

2021-11-29 07:43 UTC, merged