Добавляет пример в раздел "На практике"
doka-guide/content pull request #2445
Opened 2021-11-18 15:10 UTC by RomanBarannickov

в #2136 упоминалась данная конструкция. Решил добавить)

2021-11-18 16:12 UTC, bespoyasov reviewed
Спасибо за дополнение!

Я выразил пару опасений и предложений, возможно, они будут полезны. На всякий случай предлагаю сперва услышать мнение @nlopin, вдруг ничего не придётся править 😃

2021-11-18 16:12 UTC, bespoyasov commented on js/if-else/practice/RomanBarannickov.md
> +isTuesday && someFunction(); // если isTuesday === true произойдет вызов функции справа от &&
Хочется объяснить, почему так происходит: рассказать, как работает выполнение кода в этом случае, почему не сработает вызов функции, если `isToday` будет `false`. Думаю, стоит упомянуть, что это называется short circuit evaluation, чтобы читатели потом могли без проблем отыскать этот термин в литературе.

Как ты думаешь, @nlopin?

2021-11-18 16:12 UTC, bespoyasov commented on js/if-else/practice/RomanBarannickov.md
> +isTuesday && someFunction(); // если isTuesday === true произойдет вызов функции справа от &&
Я ещё не уверен, что это прям best practice, но так как это раздел «На практике», и такую запись часто используют, думаю, что ок 😃

2021-11-19 08:15 UTC, nlopin commented on js/if-else/practice/RomanBarannickov.md
> +isTuesday && someFunction(); // если isTuesday === true произойдет вызов функции справа от &&
Такая запись вполне норм, но важно сказать, что такая запись работает из-за short circuit eval (создал задачу, чтобы про это рассказать в статье о логических операторах #2453)

2021-11-19 08:16 UTC, nlopin commented on js/if-else/practice/RomanBarannickov.md
> +🛠 Так же частым случаем бывает вызов функции по условию используя логическое И `&&`
```suggestion
🛠 Можно использовать логическое И `&&`, чтобы вызывать функцию по условию:
```

2021-11-19 08:17 UTC, nlopin commented on js/if-else/practice/RomanBarannickov.md
> +
можно функцию опустить, мы показали её устройство в предыдущем блоке

2021-11-19 08:20 UTC, nlopin commented on js/if-else/practice/RomanBarannickov.md
> +isTuesday && someFunction(); // если isTuesday === true произойдет вызов функции справа от &&
Давай комментарий поднимем из кода в описание сверху. Вместо «Более короткая и лаконичная запись» получится что-то типа: «Можно вызвать функцию по условию с помощью оператора &&. При такой записи вызов функции произойдёт только если `isTuesday` будет `true`:»

2021-11-19 08:21 UTC, nlopin requested changes
совет хороший, нужно дополировать представление

2021-11-19 08:27 UTC, RomanBarannickov commented on js/if-else/practice/RomanBarannickov.md
> +isTuesday && someFunction(); // если isTuesday === true произойдет вызов функции справа от &&
@nlopin спасибо, подкорректирую!
только вопрос, статьи сейчас на доке нет, привести ссылку на mdn про  `short circuit eval` или всё таки как то более развернуто описать про этот механизм в примере?

2021-11-21 19:39 UTC, nlopin commented on js/if-else/practice/RomanBarannickov.md
> +isTuesday && someFunction(); // если isTuesday === true произойдет вызов функции справа от &&
ссылка на MDN будет ок, потом заменим

2021-12-22 20:32 UTC, nlopin commented
@RomanBarannickov добьешь?

2022-09-09 19:18 UTC, nlopin approved these changes

2022-09-09 19:30 UTC, nlopin commented
так, я тут что-то намудрил с ребейзом, [смёржил в `main`](https://github.com/doka-guide/content/commit/7c6817ed3a3bad891953064f1fb16098202d9de2)

2022-09-09 19:30 UTC, closed without merging