Сделать цвета менее "вырвиглазными"
doka-guide/content pull request #2476
Opened 2021-11-23 20:33 UTC by Ortiz1221

2021-11-24 09:54 UTC, solarrust commented
@skorobaeus а загляни, пожалуйста, в этот пр. Может разом поменяем тут все цвета на наши, красивые? Нужен твой совет =)

2021-11-29 10:39 UTC, skorobaeus requested changes
Привет!

Согласна, если менять цвета, то тогда сразу на наши фирменные. В этом разделе используется `#2E9AFF` в паре с `#F498AD`. Для текста поверх — чёрный цвет.

В этой статье 3 демо, предлагаю поменять цвета в двух оставшихся тоже :)

2021-12-02 10:03 UTC, solarrust commented
Attention: переименовала папка с этой статьёй. Там была ошибка в названии. Надо будет порешать конфликт =)

2021-12-06 11:04 UTC, solarrust commented
@Ortiz1221 очень бы хотелось поменять цвета всех демок в этой статье разом чтобы не возвращаться к этой задачке несколько раз. Понимаю, что у тебя может не быть на это времени прямо сейчас. Я закрою этот пул-реквест. Если у тебя появится возможность добить эту задачку — открой, пожалуйста, новый 🖤

2021-12-06 11:04 UTC, closed without merging