Добавляет имена насыщенности в статье про font-weight
doka-guide/content pull request #2505
Opened 2021-11-27 01:56 UTC by rusakovdenis

Fix #2466

2021-11-29 10:26 UTC, solarrust reviewed
Спасибо! Предложила переместить совет в отдельный файл =)

2021-11-29 10:26 UTC, solarrust commented on css/font-weight/practice/solarrust.md
> +🛠 Примерно у каждого значения насыщенности есть свои имена:
Я бы не хотела присваивать совет другого автора =) 
Если хочется добавить этот блок именно как часть раздела «На практике», то лучше создать в подпапке _practice/_ файл со своим ником и вписать совет туда.

2021-11-29 19:25 UTC, rusakovdenis commented on css/font-weight/practice/solarrust.md
> +🛠 Примерно у каждого значения насыщенности есть свои имена:
Понял, принял)

2021-11-30 17:37 UTC, solarrust reviewed
А когда эта информация может пригодится? Давай попробуем дополнить совет примером, в котором эта информация потребуется =) Или объясним текстом.

2021-11-30 17:37 UTC, solarrust commented on css/font-weight/practice/rusakov.md
> +- `950` - Extra Black (Ultra Black)
```suggestion
```

В стандартных шрифтах нет такого значения — 950. Оно относится к вариативным шрифтам.

2021-11-30 17:37 UTC, solarrust commented on css/font-weight/practice/rusakov.md
> +- `950` - Extra Black (Ultra Black)
Предлагаю перевести названия на русский и в скобках дать английское название там, где оно нужно.

2021-12-01 09:19 UTC, rusakovdenis commented on css/font-weight/practice/rusakov.md
> +- `950` - Extra Black (Ultra Black)
Хорошо, добавлю

С примером подумаю, но идей пока нет)

могу лишь сказать, что альтернативное название насыщенности выглядет более понятно, но если не знать этих названий, то интуитивно более понятны цифры, т.к. чем выше цифры, тем больше и насыщенность

2021-12-02 09:47 UTC, solarrust commented on css/font-weight/practice/rusakov.md
> +- `950` - Extra Black (Ultra Black)
Просто на моей практике я редко смотрю на название шрифта. В любом графическом редакторе, в котором создан макет, можно посмотреть вес шрифта и его же применить в коде при помощи числовых значений. Вот и интересно, где же могут пригодиться названия весом при учёте, что они не совпадают с ключевыми словами в CSS и не редко не совпадают с фактическим названием шрифта.

2021-12-04 23:04 UTC, rusakovdenis commented on css/font-weight/practice/rusakov.md
> +- `950` - Extra Black (Ultra Black)
Спасибо за идею)
Написал все мысли по данной теме, но все аргументы перевешивают в сторону цифровых значений.

2021-12-06 10:49 UTC, solarrust reviewed
Предложила небольшие изменения и написала свои ощущения от этого совета.

Призову @pepelsbey. Скажи, пожалуйста, своё мнение по поводу добавления имён начертаний в эту статью.

2021-12-06 10:49 UTC, solarrust commented on css/font-weight/practice/rusakov.md
> +- `900` - Black / Heavy (Чёрный)
```suggestion
- `100` — тонкое начертание (Thin / Hairline);
- `200` — сверхсветлое (Extra Light / Ultra Light);
- `300` — светлое (Light);
- `400` — нормальное (Normal / Regular / Book);
- `500` — среднее (Medium);
- `600` — полужирное (Semi Bold / Demi Bold);
- `700` — жирное (Bold);
- `800` — сверхжирное (Extra Bold / Ultra Bold);
- `900` — тяжёлое (Black / Heavy).
```

Всё же мы русскоязычный справочник, лучше поставить русские названия на первое место.

2021-12-06 10:49 UTC, solarrust commented on css/font-weight/practice/rusakov.md
> +Чтобы использовать все 9 начертаний (100 - 900), шрифт должен их поддерживать. В противном случае браузер будет подбирать ближайшее подходящее начертание из тех, что есть в подключаемом шрифте и поэт
Не уловила логику почему ключевое слово надёжнее чем цифровое? Если в шрифте не будет этого начертания, то ключевое слово никак не решит эту проблему. 🤔 Расскажи, пожалуйста, что именно ты здесь имеешь в виду?

2021-12-06 10:49 UTC, solarrust commented on css/font-weight/practice/rusakov.md
> +Также можно отметить, что ключевые слова _проще_ воспринимать и не нужно запоминать магические числа.
Сочетание имён, приведённых в этом совете и текста самого совета создаёт ощущение, что можно использовать имена начертаний в качестве ключевых слов в CSS. Но это не так. Чтобы не создавать запутанности лучше разделить эти два совета на два, если хочется сказать и про то и про другое.

2021-12-07 11:38 UTC, pepelsbey commented on css/font-weight/practice/rusakov.md
> +Чтобы использовать все 9 начертаний (100 - 900), шрифт должен их поддерживать. В противном случае браузер будет подбирать ближайшее подходящее начертание из тех, что есть в подключаемом шрифте и поэт
>  В большинстве графических редакторов насыщенность шрифта для блока с текстом указана в цифрах, поэтому _удобнее_ использовать в коде цифровое значение.

Я ни разу не встречал графических редакторов с цифрами 🤷🏻‍♂️

2021-12-07 11:57 UTC, pepelsbey requested changes
Спасибо за дополнение! Получился хороший список, но комментарии к ней надо дожать, чтобы по ним было понятно, что именно происходит.

2021-12-07 11:57 UTC, pepelsbey commented on css/font-weight/practice/rusakov.md
> +- `900` - Black / Heavy (Чёрный)
@solarrust подредактировал твой совет под кириллическую типографику: запятые, строчные.

2021-12-07 11:57 UTC, pepelsbey commented on css/font-weight/practice/rusakov.md
> +В большинстве графических редакторов насыщенность шрифта для блока с текстом указана в цифрах, поэтому _удобнее_ использовать в коде цифровое значение.
Я ни разу не встречал графических редакторов с цифрами 🤷🏻‍♂️

2021-12-07 11:57 UTC, pepelsbey commented on css/font-weight/practice/rusakov.md
> +Чтобы использовать все 9 начертаний (100 - 900), шрифт должен их поддерживать. В противном случае браузер будет подбирать ближайшее подходящее начертание из тех, что есть в подключаемом шрифте и поэт
Согласен с Алёной, здесь не совсем чёткий совет. По-хорошему, нужно ведь использовать те значения, которые прописаны при подключении шрифта через `@font-face`. Иначе получается путаница и логики в этом мало: 200 в Roboto браузер приводит к 100 (вниз), а 800 — к 900 (наверх), это почему так?

Я бы лучше дал совет использовать значения из `@font-face`. Ведь там вы, на самом деле, сами описываете шрифт. Можно что любое начертание описать как нужно и оно будет подключаться именно по вашему описанию, а не по характеристикам шрифта. Об этом бы рассказать.

2021-12-07 18:38 UTC, rusakovdenis commented on css/font-weight/practice/rusakov.md
> +В большинстве графических редакторов насыщенность шрифта для блока с текстом указана в цифрах, поэтому _удобнее_ использовать в коде цифровое значение.
Figma же)

2021-12-13 08:52 UTC, solarrust commented on css/font-weight/practice/rusakov.md
> +- `200` — сверх светлое (extra light, ultra light);
Пишется слитно тут и ниже

2021-12-14 17:50 UTC, rusakovdenis commented on css/font-weight/practice/rusakov.md
> +Также можно отметить, что ключевые слова _проще_ воспринимать и не нужно запоминать магические числа.
думаю, что лишнее предложение написал поэтому убираю

2021-12-14 22:30 UTC, pepelsbey requested changes
Пара мелочей и будет совсем красиво :)

2021-12-14 22:30 UTC, pepelsbey commented on css/font-weight/practice/rusakov.md
> +Чтобы использовать все 9 начертаний (100 - 900), шрифт должен их поддерживать. В противном случае браузер будет подбирать ближайшее подходящее начертание из тех, что есть в подключаемом шрифте и поэт
```suggestion
Чтобы использовать все 9 начертаний (100–900), шрифт должен их поддерживать. В противном случае браузер будет подбирать ближайшее подходящее начертание из тех, что есть в подключаемом шрифте и поэтому _надёжнее_ использовать то значение `font-weight`, которое вы указали в директиве [`font-face`](/css/font-face/).
```

2021-12-14 22:30 UTC, pepelsbey commented on css/font-weight/practice/rusakov.md
> +  <summary>Распространённые имена насыщенности</summary>
```suggestion
🛠 У каждого значения насыщенности есть своё название, принятое в типографике.

<details>
  <summary>Распространённые названия насыщенности</summary>
```

2021-12-15 16:59 UTC, tachisis approved these changes
Апрув на словарь

2021-12-17 19:40 UTC, pepelsbey approved these changes

2021-12-18 10:20 UTC, solarrust approved these changes
Классно получилось! 👍
Спасибо большое @rusakovdenis. Пиши ещё =)

2021-12-18 10:20 UTC, merged