Дополняем теги i и b, добавляем операторы сравнения js
doka-guide/content pull request #2508
Opened 2021-11-28 13:54 UTC by gkhabada

Fix #543
Fix #545
Fix #1325

Дополняем теги i и b,
Выносим операторы сравнения в отдельную статью

2021-11-29 08:00 UTC, bespoyasov requested changes
Привет! Спасибо за статью 🙌 
Я оставил несколько комментариев по статье о сравнении. 

(О части из них хочется ещё услышать мнение @nlopin.)

2021-11-29 08:46 UTC, solarrust commented
Привет!
Немного сложно ориентироваться в этом пул-реквесте — аж три разные статьи в нём правятся. Давай, пожалуйста, разделим его на три разных. По одному для каждой статьи и задачи. Так будет удобнее ревьюить =)

2021-12-07 08:58 UTC, solarrust commented
Я откатила правки в статьях про `<i>` и `<b>`. Оставила только правки в статью по JS. Пожалуйста, создай отдельные пул-реквесты на изменения в других статьях. 
Спасибо! 🙌

2021-12-12 14:44 UTC, nlopin commented on js/operators-equality/comparison_operator.md
> +Все операторы сравнения возвращают булево значение, `true` или `false`.
Давай поднимем это перед абзацем про строгое неравенство. Это предложение отнится ко всем операторам, пусть будет рядом с перечислением

2021-12-12 14:53 UTC, nlopin requested changes
Всё хорошо, нужно немного доработать. @gkhabada нужна ли помощь?

2021-12-12 14:53 UTC, nlopin commented on js/operators-equality/comparison_operator.md
> +Все операторы сравнения возвращают булево значение, `true` или `false`.
Давай поднимем это перед абзацем про строгое неравенство. Это предложение отнится ко всем операторам, пусть будет рядом с перечислением

2021-12-12 14:53 UTC, nlopin commented on js/operators-equality/comparison_operator.md
> +Неявное преобразование также используется, когда мы сравниваем значения через нестрогое равенство `==`.
Согласен, есть ощущение, что потерялся абзац про строгое неравенство. Может быть это часть, которая есть в разделе «Кратко»?

2021-12-12 14:53 UTC, nlopin commented on js/operators-equality/comparison_operator.md
> +В отличие от строгого равенства (`===`), в нём интерпретатор пробует привести типы к одному, чтобы сравнить.
тут фактическая ошибка, интерпретатор не приводит к одному типу при использовании строго сравнения

2021-12-12 14:53 UTC, nlopin commented on js/operators-equality/comparison_operator.md
> +Чтобы определить, что одна строка больше другой, JavaScript использует «алфавитный» или «лексикографический» порядок. Другими словами, строки сравниваются посимвольно.
Согласен, давайте в явном виде скажем, что строчные буквы меньше заглавных, а первые буквы алфавита меньше последних

2021-12-12 14:53 UTC, nlopin commented on js/operators-equality/comparison_operator.md
> +При сравнении значений разных типов JavaScript приводит каждое из них к числу.
Можешь дать пруф?

2021-12-12 14:53 UTC, nlopin commented on js/typecasting/index.md
> -Сравнение бывает строгим и нестрогим. При строгом сравнении (`===`) интерпретатор учитывает типы сравниваемых значений.
Согласен оставить, но нужно прямо до минимума сократить. Думаю ок сказать что есть строгое и нестрогое равенство, чем они отличаются, оставить рекомендацию про строгое равенство. Ну и сослаться на новую статью.

2021-12-12 14:55 UTC, gkhabada commented
@nlopin Сейчас буду переделывать, если нужна будет помощь, то сюда писать?

2021-12-12 17:48 UTC, gkhabada commented
Те исправления, указанные тут сделать локально и создать новый пулл реквест или это по другому делается?

2021-12-13 18:35 UTC, nlopin commented
Да, правь локально в этой ветке и делай пуш. Нам прийдут уведомления об обновлении и мы сможем увидеть инкремент

2022-02-15 07:38 UTC, closed without merging