Добавляет статью про Clipboard API
doka-guide/content pull request #2510
Opened 2021-11-28 19:38 UTC by rusakovdenis

Fix #1317

2021-11-29 08:09 UTC, bespoyasov reviewed
Спасибо за статью! 👀 
Я добавил несколько правок-примеров в оформление и пару идей для повествования.

2021-11-29 08:09 UTC, bespoyasov commented on js/clipboard/index.md
> +title: "`Clipboard API`"
```suggestion
title: "Clipboard API"
```

2021-11-29 08:09 UTC, bespoyasov commented on js/clipboard/index.md
> +`Clipboard API` предоставляет операции для переопределения действий с буфером обмена по умолчанию (*вырезание*, *копирование* и *вставка*), а также выполнять асинхронные *запись/чтение* в системный б
```suggestion
Clipboard API предоставляет операции для переопределения действий с буфером обмена по умолчанию (_вырезание_, _копирование_ и _вставка_), а также выполнять асинхронную _запись или чтение_ в системный буфер обмена.
```

2021-11-29 08:09 UTC, bespoyasov commented on js/clipboard/index.md
> +- *Clipboard* (Async Clipboard API) — предоставляет интерфейс для *чтения/записи* текста и данных в буфер обмена
Добавим текстовое введение в раздел? Сейчас непонятно, что такое интерфейсы и зачем они нужны. (Раздел нестандартный, в других доках такого не встречается.)

2021-11-29 08:09 UTC, bespoyasov commented on js/clipboard/index.md
> +Методы:
Без примеров очень сложно воспринимать техническую информацию о методах. Хочется как-то сразу увидеть, как ими пользоваться, как они пишутся.

2021-11-29 08:09 UTC, bespoyasov commented on js/clipboard/index.md
> +- *write* — записывает произвольные данные в буфер обмена. Эта асинхронная операция сигнализирует о завершении путём разрешения возвращённого [`promise`](/js/promise/).
```suggestion
- *write* — записывает произвольные данные в буфер обмена, возвращает [`promise`](/js/promise/).
```

2021-11-29 08:09 UTC, bespoyasov commented on js/clipboard/index.md
> +💡 Кроме того, методы *read* и *write* по умолчанию отключены, и для их включения требуется изменить настройки разрешений в браузере.
```suggestion
<aside>
💡 Кроме того, методы *read* и *write* по умолчанию отключены, и для их включения требуется изменить настройки разрешений в браузере.
</aside>
```

2021-11-29 08:09 UTC, bespoyasov commented on js/clipboard/index.md
> +## Важность
Кажется, этот раздел больше об отличиях или особенностях Clipboard API? 🤔

2021-12-07 08:00 UTC, bespoyasov commented on js/clipboard/index.md
> +Методы:
```suggestion
Позволяет писать текст или другие данные в буфер и читать из него.
```

2021-12-07 08:00 UTC, bespoyasov commented on js/clipboard/index.md
> +- _write_ — записывает произвольные данные в буфер обмена, возвращает [`promise`](/js/promise/).
```suggestion
Метод _write_ записывает произвольные данные в буфер обмена, возвращает [`promise`](/js/promise/).
```

2021-12-07 08:02 UTC, bespoyasov commented on js/clipboard/index.md
> +- _write_ — записывает произвольные данные в буфер обмена, возвращает [`promise`](/js/promise/).
Если список «разрывается» чем-то (примером, как у нас), то [лучше превратить его в набор абзацев](https://github.com/doka-guide/content/blob/main/docs/styleguide.md). 

Думаю, остальные пункты этого списка можно поправить таким же образом. Здесь достаточно текста между ними, чтобы слово «метод» не резало ухо повторениями.

2021-12-07 08:03 UTC, bespoyasov commented on js/clipboard/index.md
> +Запишем изображение в буфер обмена:
```suggestion
В качестве примера запишем изображение в буфер обмена:
```

2021-12-07 08:04 UTC, bespoyasov commented on js/clipboard/index.md
> +  .read();
```suggestion
  .read()
```

2021-12-07 08:04 UTC, bespoyasov commented on js/clipboard/index.md
> +- _readText_ — запрашивает текст из буфера обмена. Возвращает [`promise`](/js/promise/), которое разрешается с помощью _DOMString_, содержащего текст буфера обмена, когда он доступен.
```suggestion
- _readText_ — запрашивает текст из буфера обмена. Возвращает [`promise`](/js/promise/), который разрешается с помощью _DOMString_, содержащего текст буфера обмена, когда он доступен.
```

2021-12-07 08:05 UTC, bespoyasov commented on js/clipboard/index.md
> +- _readText_ — запрашивает текст из буфера обмена. Возвращает [`promise`](/js/promise/), которое разрешается с помощью _DOMString_, содержащего текст буфера обмена, когда он доступен.
Попробуем переформулировать это предложение? Сейчас получается очень сложно. Вероятно, поможет распилить его на несколько предложений попроще.

2021-12-07 08:06 UTC, bespoyasov commented on js/clipboard/index.md
> +💡 Кроме того, методы _read_ и _write_ по умолчанию отключены, и для их включения требуется изменить настройки разрешений в браузере.
```suggestion
💡 Кроме того, методы _read_ и _write_ по умолчанию отключены, и для их включения требуется изменить настройки разрешений в браузере.
</aside>

<aside>
```

2021-12-07 08:07 UTC, bespoyasov commented on js/clipboard/index.md
> +Современный API позволяет работать не только с текстом, но и с картинками, а также копировать смешанный контент.
Возможно, стоит добавить пример и развернуть понятие смешанного контента: что это, что не является смешанным контентом и т. д.

2021-12-07 08:08 UTC, bespoyasov commented on js/clipboard/practice/rusakov.md
> +🛠 Вы можете использовать данное API на вашем сайте с целью повышения удобства пользования.
```suggestion
🛠 Clipboard API может упростить взаимодействие с сайтом в ситуациях, когда пользователю нужно что-то скопировать:
```

2021-12-09 15:24 UTC, rusakovdenis commented on js/clipboard/index.md
> +Современный API позволяет работать не только с текстом, но и с картинками, а также копировать смешанный контент.
добавил определение, над пример еще подумаю. Можно сделать пример, где есть картинка, которая загружается с сайта с HTTP и например ссылка на ютуб, где HTTPS.

2021-12-10 07:07 UTC, bespoyasov commented on js/clipboard/index.md
> +Современный API позволяет работать не только с текстом, но и с картинками, а также копировать смешанный контент.
Звучит, как план! 👍

2021-12-10 07:07 UTC, bespoyasov approved these changes

2021-12-10 07:08 UTC, bespoyasov commented
@nlopin, посмотришь, пожалуйста, тоже?

2021-12-12 19:20 UTC, nlopin requested changes
Ты очень классно покрыл Clipboard API, супер, что есть много примеров.

По структуре статьи очень просится раздел про события `cut`, `copy` и `paste`. Мы про них говорим в начале, но в тексте статьи нет ни одного примера.

2021-12-12 19:20 UTC, nlopin commented on js/clipboard/index.md
> +[Интерфейс прикладного программирования, API](/js/api) —  это способ подружить разные части системы между собой. В нашем случае — код и задачи программиста и язык с веб-платформой, которые дают возмо
Мне кажется этот абзац здесь не даёт нужного контекста. Думаю, в качестве вступления лучше сказать, что Clipboard API — это объединение нескольких API, которые работают с буфером обмена. Так мы лучше подведём к списку этих апи

2021-12-12 19:20 UTC, nlopin commented on js/clipboard/index.md
> +const items = await navigator.clipboard
мне кажется это не заработает. В `items` будет `undefined`, который неявно вернёт последний `then`. Могу ошибаться, конечно

2021-12-12 19:20 UTC, nlopin commented on js/clipboard/practice/rusakov.md
> +🛠 Clipboard API может упростить взаимодействие с сайтом в ситуациях, когда пользователю нужно что-то скопировать:
Давай приведём пример. Мейчас это предложение слишком общее и «упростить» не считывается в действие, которое можно выполнить. Например, можно написать, что можно сделать копирование важного текста по нажатию кнопки

2021-12-12 19:20 UTC, nlopin commented on js/clipboard/index.md
> +Позволяет писать текст или другие данные в буфер и читать из него.
Тут ещё просится сказать, что это API доступно через `navigator.clipboard`

2021-12-15 12:04 UTC, pepelsbey approved these changes
Поформатировал всякое, см. коммиты. С этой точки зрения — апрув :)

2021-12-23 20:43 UTC, nlopin commented on js/clipboard/index.md
> +<details>
Я еще раз перечитал и не понимаю, к чему это относится. К событиям? В саммари написано с методом paste 🤔

2021-12-23 20:58 UTC, nlopin commented on js/clipboard/index.md
> +const items = await navigator.clipboard
Я проверил, у меня не сработало, предлагаю альтернативный код

2021-12-23 21:00 UTC, nlopin commented on js/clipboard/index.md
> +const text = await (new Response(textBlob)).text();
Кажется остальные примеры тоже не будут работать из-за top level await. Надо либо переформатировать, либо дополнить, чтобы они работали при простом перекопировании в консоль

```suggestion
navigator.clipboard
  .read()
  .then((data) => {
    console.log(`Прочитан буфер ${data}`)
    return data[0].getType('text/plain')
  })
  .then((blob) => {
    return (new Response(blob)).text()
  })
  .then((text) => {
    console.log(`Текст в буфере обмена "${text}"`)
  })
  .catch(function (error) {
    console.error('Ошибка:', error)
  })
```

2021-12-23 21:00 UTC, nlopin commented
@rusakovdenis нужна ли помощь? 

Из ключевого осталось: 

- [ ] раздел про события cut, copy и paste. Мы про них говорим в начале, но в тексте статьи нет ни одного примера.
- [ ] уточнить описание про блоки details, они сейчас выпадают. возможно они как раз встанут в раздел про события
- [ ] дотюнить примеры кода, посмотри на свежий комментарий, пожалуйста

2022-03-24 20:27 UTC, rusakovdenis commented
> @rusakovdenis нужна ли помощь?
> 
> Из ключевого осталось:
> 
> * [ ]  раздел про события cut, copy и paste. Мы про них говорим в начале, но в тексте статьи нет ни одного примера.
> * [ ]  уточнить описание про блоки details, они сейчас выпадают. возможно они как раз встанут в раздел про события
> * [ ]  дотюнить примеры кода, посмотри на свежий комментарий, пожалуйста

у меня не будет возможности добить статью, если кто то может дописать, то было- бы круто, т.к. хочется чтобы она увидела свет

2022-03-24 21:37 UTC, nlopin commented
Привет Денис, обязательно добьём 👍 Спасибо за работу

2022-12-07 10:15 UTC, HellSquirrel commented
Временно закрываю это PR, но, как говорил Коля, постараемся его добить :)

2022-12-07 10:15 UTC, closed without merging