Поправил демку в html/nav
doka-guide/content pull request #2532
Opened 2021-12-03 18:03 UTC by devcustrom

2021-12-06 10:32 UTC, solarrust commented
Очень классно, наглядно получилось. Спасибо большое! 

@skorobaeus глянь, пожалуйста. На первый взгляд кажется, что можно убрать веса у подключаемого шрифта.

2021-12-06 10:32 UTC, solarrust approved these changes

2021-12-06 11:11 UTC, skorobaeus commented on html/nav/index.md
> +<iframe title="Хлебные крошки" src="demos/breadcrumbs/bikes" height="280"></iframe>
```suggestion
<iframe title="Хлебные крошки" src="demos/breadcrumbs/bikes/bmx/jump-bike-3000" height="280"></iframe>
```

Предлагаю встроить здесь самую последнюю страницу в цепочке (про байк), т.к. код в теле статьи описывает реализацию уже готовых "хлебных крошек" и содержит разметку этой страницы.

2021-12-06 11:15 UTC, skorobaeus requested changes
Привет! Это очень круто! Оставила пару комментариев 👆

@solarrust если убрать веса, то не подключится 500-ый, а он используется для заголовков :)

2021-12-06 16:05 UTC, devcustrom commented on html/nav/demos/breadcrumbs/bikes/bmx/index.html
> +    <a href="./jump-bike-3000/">Jump Bike 3000</a>
Да вполне

2021-12-06 16:05 UTC, devcustrom commented on html/nav/index.md
> +<iframe title="Хлебные крошки" src="demos/breadcrumbs/bikes" height="280"></iframe>
Сам хотел сделать и забыл)

2021-12-07 10:27 UTC, skorobaeus commented
@devcustrom привет! Я вижу, что обсуждения зарезолвлены, но стилей для ссылок в файлах пока нет.

2021-12-07 11:04 UTC, devcustrom commented
> @devcustrom привет! Я вижу, что обсуждения зарезолвлены, но стилей для ссылок в файлах пока нет.

Мне добавить? Я думал вы уже добавили) Сейчас сделаю

2021-12-07 11:09 UTC, devcustrom commented
Сделал

2021-12-09 09:32 UTC, skorobaeus approved these changes

2021-12-09 12:44 UTC, solarrust commented
Класс! Спасибо большое за ценное дополнение! 👍

2021-12-09 12:45 UTC, merged