Добавляет доку про `<code>`
doka-guide/content pull request #2549
Opened 2021-12-08 13:04 UTC by xpleesid

Fix #556

2021-12-08 15:59 UTC, solarrust reviewed
Великолепно как всегда! 👍

Оставила пару предложений по улучшению.

2021-12-08 15:59 UTC, solarrust commented on html/code/index.md
> +Этот пример кода был обёрнут в теги [`pre`](/html/pre/) и `<code>` (вы можете проверить это, выбрав фрагмент в инспекторе элементов), а подсветку синтаксиса обеспечила библиотека PrismJS.
```suggestion
Этот пример кода был обёрнут в теги [`<pre>`](/html/pre/) и `<code>` (вы можете проверить это, выбрав фрагмент в инспекторе элементов), а подсветку синтаксиса обеспечила библиотека PrismJS.
```

2021-12-08 15:59 UTC, solarrust commented on html/code/index.md
> +Если мы хотим красивого форматирования и подсветки синтаксиса, мы должны использовать сторонние инструменты и дополнительно пометить код, например, при помощи атрибута [`class`](/html/class/). Для эт
```suggestion
Если мы хотим красивого форматирования и подсветки синтаксиса, мы должны использовать сторонние инструменты и дополнительно пометить код, например, при помощи атрибута [`class`](/html/class/). Для этого обычно используются библиотеки, такие как [`HighlightJS`](https://highlightjs.org/) и [`PrismJS`](https://prismjs.com/).
```

Убрала последнее предложение на случай, если завтра мы поменяем библиотеку, а в тексте останется старая инфа =) Кажется, смысл от этого не потерялся.

2021-12-08 15:59 UTC, solarrust commented on html/code/index.md
> +Этот пример кода был обёрнут в теги [`pre`](/html/pre/) и `<code>` (вы можете проверить это, выбрав фрагмент в инспекторе элементов), а подсветку синтаксиса обеспечила библиотека PrismJS.
Можно добавить прямо блок с HTML-разметкой для этого кода чуть выше, над самим блоком кода.

2021-12-08 15:59 UTC, solarrust commented on html/code/index.md
> +## Пример
```suggestion
## Подсветка синтаксиса
```

Это частный случай использования тега. Я бы выделила этот блок под отдельный соответствующий заголовок

2021-12-08 15:59 UTC, solarrust commented on html/code/index.md
> +`<code>` используется для вывода любой информации, которая может быть обработана компьютером как программный код. Помимо непосредственно кода, сюда также относятся названия файлов, конфигурационные ф
Стоит ещё упомянуть тут что тег строчный по умолчанию и что внутри него не сохраняется форматирование.

2021-12-08 15:59 UTC, solarrust commented on html/code/index.md
> +`<code>` используется для вывода любой информации, которая может быть обработана компьютером как программный код. Помимо непосредственно кода, сюда также относятся названия файлов, конфигурационные ф
У нас, например, не принято оборачивать в код названия файлов, технологий. Где-то встречается явная рекомендация это делать?

2021-12-09 13:32 UTC, YooPita commented
> Fix #556

Не понятно зачем в формуле Эйнштейна каждая переменная формулы обрамляется тегом, если можно обрамить всю формулу целиком, что было бы правильно, так как знак "=" тоже часть формулы.

2021-12-09 13:40 UTC, solarrust commented
@YooPita привет. Кажется, твой комментарий не относится к текущей статье. Если я правильно догадалась, то вопрос относится к статье про `<var>`. Пожалуйста, создай отдельный ишью с этим вопросом [тут](https://github.com/doka-guide/content/issues)

2021-12-13 12:54 UTC, xpleesid commented on html/code/index.md
> +`<code>` используется для вывода любой информации, которая может быть обработана компьютером как программный код. Помимо непосредственно кода, сюда также относятся названия файлов, конфигурационные ф
Да, в спеке приводят в качестве одного из вариантов использования https://html.spec.whatwg.org/multipage/text-level-semantics.html#:~:text=XML%20element%20name%2C-,a%20filename,-%2C%20a%20computer%20program

2021-12-14 11:31 UTC, solarrust reviewed
Буквально один момент осталось порешать и в очередная крутая статья готова! 🔥

2021-12-14 11:31 UTC, solarrust commented on html/code/index.md
> +<code class="block-code__highlight">
В тексте ниже мы говорим, что код оборачивается ещё и в `<pre>`, но в примере его нет

2021-12-14 11:31 UTC, solarrust commented on html/code/index.md
> +<code class="block-code__highlight">
@pepelsbey приходи, пожалуйста, посмотреть на этот раздел про подсветку кода.

2021-12-14 23:22 UTC, pepelsbey requested changes
Спасибо за хороший старт! Я немного поредачил мелочи, но тут нужно учесть ещё кое-что. Пока в доке совсем теряется идея, что `<code>` сделан для вывода кода во фразовом контексте. Другими словами, внутри предложения, а не на уровне абзацев.

То есть если нужно показать блок кода — нужно написать:

```html
<pre><code>
  my_code;
</code></pre>
```

Мне кажется, что важно, чтобы статья про [`<pre>`](https://doka.guide/html/pre/) и эта работали вместе и не противоречили друг другу.

2021-12-17 14:54 UTC, xpleesid commented
Спасибо за комментарии! Добавил отсылку к pre и указал про фразовый контекст и вывод блоков кода

2021-12-17 18:16 UTC, pepelsbey approved these changes

2021-12-18 10:22 UTC, solarrust approved these changes
Спасибо большое! Как всегда топ 🔥
Пиши ещё =)

2021-12-18 10:22 UTC, merged