SEO правки
doka-guide/content pull request #2550
Opened 2021-12-08 18:01 UTC by devcustrom

2021-12-12 07:28 UTC, bespoyasov approved these changes
Апрув на JS. 
Спасибо!

2021-12-13 08:34 UTC, solarrust commented
Привет. Не писать заголовки «Комментарии в CSS» и «Комментарии в HTML» было осознанным решением. Расскажи, пожалуйста, подробнее, почему следует делать именно так, как ты предлагаешь? 
@tachisis @pepelsbey мы с вами когда-то обсуждали этот момент. Присоединяйтесь =)

2021-12-13 08:37 UTC, furtivite commented on js/set-keys/index.md
> +description: "set.keys() возвращает итератор для обхода значений коллекции Set"
@bespoyasov, а может лучше оборачивать код в `<code>` через бэктики?

```suggestion
description: "`set.keys()` возвращает итератор для обхода значений коллекции Set"
```

Мимо проходил.

2021-12-13 08:47 UTC, bespoyasov commented on js/set-keys/index.md
> +description: "set.keys() возвращает итератор для обхода значений коллекции Set"
Если поле description используется не только для соцсетей, то наверное да.

2021-12-13 09:07 UTC, furtivite commented on js/set-keys/index.md
> +description: "set.keys() возвращает итератор для обхода значений коллекции Set"
> Если поле description используется не только для соцсетей, то наверное да.

Оно выводится на главной, если обложки нет.

2021-12-13 12:48 UTC, bespoyasov commented on js/set-keys/index.md
> +description: "set.keys() возвращает итератор для обхода значений коллекции Set"
Ну тогда да, стоит в бэктики обернуть.

2021-12-13 12:57 UTC, furtivite requested changes

2021-12-13 12:57 UTC, furtivite commented on js/set-values/index.md
> +description: "set.values() возвращает итератор для обхода значений коллекции Set"
```suggestion
description: "`set.values()` возвращает итератор для обхода значений коллекции Set"
```

2021-12-13 16:06 UTC, devcustrom commented
> Привет. Не писать заголовки «Комментарии в CSS» и «Комментарии в HTML» было осознанным решением. Расскажи, пожалуйста, подробнее, почему следует делать именно так, как ты предлагаешь? @tachisis @pepelsbey мы с вами когда-то обсуждали этот момент. Присоединяйтесь =)

Мета данные такие как  h1, title и description Должны быть уникальны и информативны, а с такими метаданными поисковикам сложно увидеть отличия этих страниц, ну и title состоящий из одного слова плохая практика

2021-12-13 18:01 UTC, nlopin commented on js/set-values/index.md
> +description: "set.values() возвращает итератор для обхода значений коллекции Set"
Если резолвишь комментарии, пиши, пожалуйстаь, почему. Бэктики нужны, потому что мы используем описание как тизеры для статей и там нужна разметка. Для SEO бэктики вырезаются при сборке

2021-12-13 18:09 UTC, nlopin approved these changes

2021-12-14 10:00 UTC, solarrust approved these changes

2021-12-14 23:26 UTC, pepelsbey approved these changes

2021-12-16 07:11 UTC, merged