tag b
doka-guide/content pull request #2559
Opened 2021-12-12 15:31 UTC by gkhabada

Fix #543

2021-12-13 08:28 UTC, solarrust reviewed
Спасибо большое и за эту статью 🙌
Предложила несколько улучшений. Давай ещё где-то явно проговорим, что тег не несёт семантической нагрузки, ничего не значит.

2021-12-13 08:28 UTC, solarrust commented on html/b/index.md
> +  - gkhabada
Давай тут тоже поставим тебя автором статьи =)

2021-12-13 08:28 UTC, solarrust commented on html/b/index.md
>  Тег `<b>` используется для привлечения внимания к части текста, без добавления какой-то важности или изменения тона: ключевые слова, названия продуктов в обзорах, лиды статей.
«лиды статьей» — не самое распространённое понятие, не все могут его понять. Давай заменим?

2021-12-13 08:28 UTC, solarrust commented on html/b/index.md
> +Согласно спецификации HTML5, тег `<b>` должен быть использован в качестве последнего средства, когда нет других тегов являющихся более целесообразными.
```suggestion
Согласно спецификации HTML5, тег `<b>` должен быть использован как последнего средства, когда нет других более подходящих тегов.
```

2021-12-15 11:49 UTC, pepelsbey requested changes
Спасибо за развитие статьи! Есть несколько идей, как сделать точнее и лучше :)

2021-12-15 11:49 UTC, pepelsbey commented on html/b/index.md
> +Согласно спецификации HTML5, тег `<b>` должен быть использован в качестве последнего средства, когда нет других тегов являющихся более целесообразными.
Спецификацию HTML5 уже несколько лет назад заменила спецификация [HTML](https://html.spec.whatwg.org/multipage/) и она редиректит туда. Так что лучше сказать «согласно спецификации HTML». И если уж упоминается спецификация, хорошо бы сослаться [на раздел про тег b](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-b-element).

2021-12-15 11:49 UTC, pepelsbey commented on html/b/index.md
> +<p><b>ВНИМАНИЕ!</b> Не злите собаку!</p>
```suggestion
<p>
  <b>Внимание!</b>
  Не злите собаку!
</p>
```

Прописные буквы лучше писать в стилях (`text-transform: uppercase`), не будем рекомендовать плохое.

2021-12-15 11:49 UTC, pepelsbey commented on html/b/index.md
> +Теги `<b>` и [`<strong>`](/html/strong) внешне похожи: оба по умолчанию имеют жирный стиль. Тег [`<strong>`](/html/strong) используется для выделения важного, а тег `<b>` просто изменяет стиль.
```suggestion
Теги `<b>` и [`<strong>`](/html/strong) внешне похожи: оба по умолчанию имеют жирный стиль. Тег [`<strong>`](/html/strong) используется для выделения важного, а тег `<b>` просто изменяет стиль.

В этом примере правильным элементом был бы `<strong>`, а не `<b>`:
```

2021-12-15 11:49 UTC, pepelsbey commented on html/b/index.md
> +В предыдущем примере правильным элементом для использования было бы `<strong>`, а не `<b>`.
```suggestion
```

Перенёс описание примера выше, чтобы читатель понял — пример неправильный.

2021-12-27 06:44 UTC, solarrust commented
@pepelsbey @gkhabada внесла правки. Хочется добить статью до НГ. Посмотрите, нужно ли ещё что-то добавить или поправить?

2021-12-31 08:37 UTC, gkhabada commented
> @pepelsbey @gkhabada внесла правки. Хочется добить статью до НГ. Посмотрите, нужно ли ещё что-то добавить или поправить?

У меня больше нет правок. Спасибо за внесенные изменения.

2022-01-05 22:29 UTC, pepelsbey approved these changes

2022-01-05 22:29 UTC, pepelsbey commented
Заменил «лид» на «вводную часть». Думаю можно мёржить :)

2022-01-10 06:02 UTC, solarrust approved these changes

2022-01-10 06:02 UTC, solarrust commented
Класс! Большое спасибо. Пиши ещё! 🔥

2022-01-10 06:02 UTC, merged