Fix #2568 Дополняет практику для if-else - ??
doka-guide/content pull request #2590
Opened 2021-12-15 16:49 UTC by saharok

Добавляет очень короткое обоснование использования Nullish coalescing operator (??)  вместо || и адаптирует пример из кода выше.
Добавил 3 ссылки: 1 внутренняя и 2 внешние, если перебор или что-то не то - поправьте.

2021-12-16 08:02 UTC, bespoyasov approved these changes
Привет! 

Это отличный совет, спасибо!
Я думаю, это даже достойно отдельной практики с авторством :–) 

Как считаешь, @nlopin?

2021-12-16 11:50 UTC, pepelsbey requested changes

2021-12-16 11:50 UTC, pepelsbey commented on js/if-else/practice/nlopin.md
> +// и только если externalValue === null или undefined, значение value установится в 42
Было бы круто из кучи текста вокруг одной строчки кода сделать предложение, которое объясняет как она работает. Сейчас оно только в исходнике смотрится плюс-минус понятно, на сайте будет сильно сложнее, что уж говорить про мобильные экраны.

2021-12-16 14:46 UTC, saharok commented on js/if-else/practice/nlopin.md
> +// и только если externalValue === null или undefined, значение value установится в 42
Переделал и немного допилил. Надеюсь я правильно понял что нужно.
Т.к. это практика к статье **if-else**, то текста с объяснением работы **??** решил написать по минимуму, но логику работы описал в комментариях к коду и оставил ссылку на [learn.javascript.ru].
Изначально, идея была **минимально дополнить существующие примеры** (всего один оператор в коде || -> ??) и существенно больше значений можно передавать (именно так и появился на свет ?? в дополнение к ||).
В дальнейшем были планы подготовить полноценную статью про ??, x ??= y, x &&= y, x II= y и тут сделать внутреннюю ссылку на неё.

2021-12-16 14:51 UTC, pepelsbey commented on js/if-else/practice/nlopin.md
> +// и только если externalValue === null или undefined, значение value установится в 42
@saharok да, всё так, спасибо :) Развернул [ещё немного](https://github.com/doka-guide/content/pull/2590/commits/02752ea55b25fd73cec8d7782e4665fc2fc1a54c).

2021-12-16 14:51 UTC, pepelsbey approved these changes

2021-12-16 15:32 UTC, saharok commented on js/if-else/practice/nlopin.md
> +// и только если externalValue === null или undefined, значение value установится в 42
Ok, но на мой вкус это уже перебор и шаг в сторону, я ведь сознательно тот текст в комментарий поместил:).

2021-12-17 08:58 UTC, nlopin approved these changes
Огнище 👍

2021-12-17 09:00 UTC, nlopin commented
@saharok добавь себя в папку `people`, пожалуйста. Я тогда смогу вынести этот совет из под своего авторства под твоё

2021-12-17 10:10 UTC, saharok commented
[Добавил](https://github.com/doka-guide/content/pull/2599/commits/64188b59d7c959247987b388dbf3cd3727377a3c)

2021-12-17 20:47 UTC, nlopin commented
@saharok запилил табличку ещё в конец совета:
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1469636/146605869-4c363fec-abba-43e6-a9dd-8a2ba72fb5d1.png">

2021-12-17 20:52 UTC, merged

2021-12-17 21:19 UTC, saharok commented
Супер! Очень наглядно. Я уже смирился с мыслью, что просто дописать **одну** стоку кода меняющую **один** оператор, хоть и с комментариями в добрую доку не получится, если уж дополнять, то по полной программе)) Ещё на этапе "разворота" Вадимом комментария в пример. Краткость - сестра злого таланта, а у нас добрый!