Добавлен комментарий "на практике" для статьи про markdown
doka-guide/content pull request #2605
Opened 2021-12-18 20:01 UTC by ilfa

Добавлен комментарий о поддержке видео и новый автор.

2021-12-18 20:12 UTC, ilfa commented
Странно, но в сборке к pr комментарий не появился https://doka-guide-content-pr-2605.surge.sh/tools/markdown/

2021-12-19 20:22 UTC, nlopin commented on tools/markdown/practice/ilfa.md
> +Markdown не предполагает специального синтаксиса для встраивания видео, но и использование html тегов тоже не запрещает. Самый популярный [вопрос](https://stackoverflow.com/questions/11804820/how-can
Мне кажется польза от ссылки на стековерфлоу минимальна. Давай лучше расскажем о проблеме и сразу дадим решения:
```suggestion
Markdown не предполагает специального синтаксиса для встраивания видео, но и использование HTML-тегов тоже не запрещает. Есть два основных пути добавить видео в Markdown:
```

2021-12-19 20:25 UTC, nlopin commented on tools/markdown/practice/ilfa.md
> +1. Более каноничный, 100% рабочий и допустимый на сторонних площадках вроде GitHub: использовать обложку видео со ссылкой на внешнюю платформу.
Тут действие вперёд, чтобы было понятно «что»

```suggestion
1. Использовать обложку видео со ссылкой на внешнюю платформу. 100% рабочий и допустимый на сторонних площадках вроде GitHub способ.
```

2021-12-19 20:27 UTC, nlopin commented on tools/markdown/practice/ilfa.md
> +2. Использовать hmtl разметку и вставить `iframe`, например тот что генерирует YouTube в диалоге "поделиться".
```suggestion
2. Использовать HTML-разметку и вставить [`iframe`](/html/iframe), например тот, что генерирует YouTube в диалоге "поделиться".
```

2021-12-19 20:28 UTC, nlopin requested changes
Большое спасибо за совет, я сам часто задаю себе этот вопрос. Сделал минорные изменения, если тебе они ок, то принимай и смёржим 💪

2021-12-20 09:34 UTC, devcustrom commented on tools/markdown/practice/ilfa.md
> +2. Использовать hmtl разметку и вставить `iframe`, например тот что генерирует YouTube в диалоге "поделиться".
Ссылку нужно поправить `(/html/iframe/)`

2021-12-20 11:40 UTC, igsekor requested changes
Поправил ещё форматирование, согласно нашему линтеру.

2021-12-20 11:40 UTC, igsekor commented on tools/markdown/practice/ilfa.md
> + allowfullscreen></iframe>
```suggestion
  width="560"
  height="315"
  src="https://www.youtube.com/embed/y-_nXfKkI3w"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen></iframe>
```

2021-12-23 12:32 UTC, ilfa commented
Спасибо за ваши правки, со всем согласен, принял!

2021-12-24 09:56 UTC, nlopin approved these changes

2021-12-24 11:12 UTC, igsekor approved these changes

2021-12-24 11:13 UTC, merged