Article/performance
doka-guide/content pull request #2607
Opened 2021-12-19 09:22 UTC by mighty-peach

Привет.
Написал статейку про performance.api
https://github.com/doka-guide/content/issues/488 (почему то сам не могу привязать задачку к ПРу)

Там наверняка косяки, подскажите, пожалуйста, что стоит поправить

2021-12-20 09:02 UTC, bespoyasov reviewed
Спасибо! Получается отличная статья :–) 

По тексту мне почти всё нравится, я предложил только пару минорных улучшений, но в остальном апрув.

2021-12-20 14:02 UTC, mighty-peach commented on js/performance/index.md
> +description: ""
добавил

2021-12-20 14:08 UTC, mighty-peach commented on js/performance/index.md
> +Создаём именованную метку времени
добавил больше описания и пример

2021-12-20 14:14 UTC, mighty-peach commented on js/performance/index.md
> +Мы можем очистить записанные метки и измерения разными методами:
Добавил пример использования: если имена создаются в рантайме – мы можем хотеть перезаписывать значения с одним и тем же именем во избежания дублирования

2021-12-20 14:22 UTC, mighty-peach commented on js/performance/index.md
> +Когда нужно проверить скорость работы кода, провести тесты производительности или найти узкие места — удобнее всего использовать `Performance.API` с его удобными методами и точностью измерений.
Хорошая идея, добавил

2021-12-20 14:25 UTC, mighty-peach commented on js/performance/index.md
> +performance.clearMarks()
добавил и в пример и в описание методов

2021-12-20 14:28 UTC, mighty-peach commented on js/performance/index.md
> +## Пример
тут сначала ждём ответа?

2021-12-20 18:39 UTC, pepelsbey requested changes
По контенту вам уже всё рассказали, а я про форматирование зашёл сказать :)

2021-12-20 18:39 UTC, pepelsbey commented on js/performance/index.md
> +1. `performance.getEntriesByType(entryType)` - возвращает список из сущностей заданного типа, например, “mark” или “measure”.
```suggestion
1. `performance.getEntriesByType(entryType)` - возвращает список из сущностей заданного типа, например, _mark_ или _measure_.
```

Кажется кавычки здесь не нужны, особенно такие

2021-12-20 18:39 UTC, pepelsbey commented on js/performance/practice/mighty-peach.md
> +🛠 `performance` полезно использовать для поиска "узких" мест вашей программы. Рассмотрим пример, когда у нас есть две функции `function_1()` и `function_2()` и мы хотим выяснить какая из функций торм
```suggestion
🛠 `performance` полезно использовать для поиска узких мест вашей программы. Рассмотрим пример, когда у нас есть две функции `function_1()` и `function_2()` и мы хотим выяснить какая из функций тормозит нашу программу.
```

Это вполне устоявшаяся идиома, можно и без кавычек

2021-12-22 08:42 UTC, bespoyasov commented on js/performance/index.md
> +## Пример
Думаю, да. Чтобы не делать того, о чём не успели договориться :–)

2021-12-27 17:56 UTC, mighty-peach commented on js/performance/index.md
> +## Пример
Ещё ждём или может поправим как то? Или пока всё ок по времени? 😃

2021-12-29 09:45 UTC, bespoyasov commented on js/performance/index.md
> +## Пример
У узнал у @nlopin, можем править 😃 
Структуру можно взять примерно такую, как выше обсудили. Если появятся идеи, как сделать лучше — я только за.

2021-12-29 14:04 UTC, mighty-peach commented on js/performance/index.md
> +## Пример
@bespoyasov, на всякий случай, ты предлагаешь блоки "пример" и "как понять" поменять местами? А то сел писать и что-то запутался 😅

2021-12-30 14:25 UTC, nlopin commented on js/performance/index.md
> +## Пример
В целом для доки структура правильная: кратко → пример → как пишется → как понять

Я думаю проблема сейчас скорее с тем, что у нас не совсем дока, а скорее обзорная статья. Если в доках примеры очень краткие, то тут примеров много и к ним нужна подводка.

Давай поднимем «Как понять» над примерами, а сами примеры разобъем заголовками

2021-12-30 14:26 UTC, nlopin commented on js/performance/practice/mighty-peach.md
> +🛠 Из примера видим, что `function_1()` работает медленнее, а значит мы можем оптимизировать её для ускорения программы.
Я бы ещё добавил, что есть и другие способы следить за перформансом. Например, вкладка Performance в инструментах разработчика

2021-12-30 14:29 UTC, nlopin commented on js/performance/index.md
> +⏱ Для измерения времени мы можем так же использовать класс `Date` с его методом `Date.now()`, возвращающий `timestamp` – текущее время в миллисекундах. Сохранив в переменные два вызова `Date.now()` (
ты уверен в слове «на порядок»? Это подразумевает точность выше в 10 раз. Если уверенности нет, то давай просто уберём на порядок

2021-12-30 14:30 UTC, nlopin commented on js/performance/index.md
> +Метка - время со старта навигации на страницу до создания метки в миллисекундах.
я не могу уложить в голове, что значит «со старта навигации». Это с какого-то события? или с загрузки страницы? Можем тут уточнить?

2021-12-30 14:31 UTC, nlopin commented on js/performance/index.md
> +1. `performance.getEntries()` - получаем список всех меток и измерений, включая записываемые браузером.
Вот тут интересно, какие метки записывает сам браузер? Может оформим этот список в тег `details`?

2021-12-30 14:38 UTC, nlopin commented on js/performance/demos/functions-measure/index.html
> +<!DOCTYPE html>
Давай в пример ещё добавим единицы измерения и сделаем тёмный фон. Можно стащить стили с [демки scrollTo](https://doka.guide/js/element-scroll-scrollto/)

2021-12-30 14:41 UTC, nlopin commented on js/performance/index.md
> +description: "Performance.API — это API браузера, позволяющее измерять время работы программы при помощи различных методов."
у нас поменялся подход к описанию, теперь это скорее тизер. Предлагаю так:
```suggestion
description: "Изучаем, какие инструменты предоставляет браузер для измерения времени работы программ и функций"
```

2021-12-30 15:44 UTC, mighty-peach commented on js/performance/index.md
> +## Пример
Так, вроде всё

2021-12-30 16:01 UTC, mighty-peach commented on js/performance/index.md
> +⏱ Для измерения времени мы можем так же использовать класс `Date` с его методом `Date.now()`, возвращающий `timestamp` – текущее время в миллисекундах. Сохранив в переменные два вызова `Date.now()` (
Убрал совсем

2021-12-30 16:15 UTC, mighty-peach commented on js/performance/demos/functions-measure/index.html
> +<!DOCTYPE html>
Сделал

2021-12-30 16:30 UTC, mighty-peach commented on js/performance/practice/mighty-peach.md
> +🛠 Из примера видим, что `function_1()` работает медленнее, а значит мы можем оптимизировать её для ускорения программы.
Добавил про вкладку Performance и счётчик ФПС

2021-12-30 16:33 UTC, mighty-peach commented on js/performance/index.md
> +Метка - время со старта навигации на страницу до создания метки в миллисекундах.
Ну там модель расчётов не самая простая – но если кратко, когда пользователь кликнул на ссылку или после ввода урла нажал "enter". Попробую распространить этот кусочек

2021-12-30 17:00 UTC, mighty-peach commented on js/performance/index.md
> +1. `performance.getEntries()` - получаем список всех меток и измерений, включая записываемые браузером.
Тут нужно ревью – просто верхнеуровнево описать не прикольно, кажется, так как инфа там важная. Но подробное описание тянет на статью про отслеживание рендера странички. Попытался найти баланс, посмотри, пожалуйста

2022-01-31 20:08 UTC, nlopin commented
@mighty-peach посмотрим этот PR на этой неделе, он как-то затерялся в новогоднем движе

2022-02-04 20:08 UTC, nlopin commented
у меня вызовы `measure` возвращают `undefined`  в фаерфоксе. В хроме возвращается измерение. Нужно это подчеркнуть и сделать пример, который будет работать везде

2022-02-04 21:16 UTC, nlopin approved these changes
Можно сливать

2022-02-04 21:18 UTC, nlopin commented
@bespoyasov прочитай, пожалуйста. Если тебе ок, то влей плз

2022-02-05 04:56 UTC, mighty-peach commented
@nlopin Спасибо за то, что привёл статью в порядок :)

2022-02-07 07:59 UTC, merged