Добавляет статью про caret-color
doka-guide/content pull request #2608
Opened 2021-12-19 21:34 UTC by Misha-Mad

Fix #640

2021-12-20 08:34 UTC, tachisis approved these changes
Апрув на словарь

2021-12-20 11:26 UTC, solarrust requested changes
Привет! Спасибо большое за хорошую статью 🙌
Оставила несколько предложений по улучшению. 

Давай ещё где-то скажем, что свойство наследуется, а значит его можно прописать глобально или для формы и не писать отдельно для каждого поля ввода.

Ещё было бы интересно рассказать о том, к каким тегам в каких случаях можно его применять. Например, сработает ли оно, если мы зададим для `<p>` атрибут [`contenteditable`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable)? Можно про это поговорить в разделе «На практике» поскольку это, скорее, частный случай, чем распространённая задача.

2021-12-20 11:26 UTC, solarrust commented on css/caret-color/index.md
> +`caret-color` задаёт цвет текстового курсора в полях ввода, например, `input` или `textarea`.
```suggestion
Свойство `caret-color` задаёт цвет текстового курсора в полях ввода, например, [`<input>`](/html/input/) или [`<textarea>`](/html/textarea/).
```

Можно ещё коротко сказать что такое текстовый курсор. Что-то вроде «текстовый курсор — это моргающая вертикальная палочка.»

2021-12-20 11:26 UTC, solarrust commented on css/caret-color/index.md
> +pre {
Точно у `<pre>` можно поменять это свойство?
Давай дадим реальный наглядный коротенький пример из жизни с фреймом результата.

2021-12-20 11:26 UTC, solarrust commented on css/caret-color/index.md
> +
```suggestion
Значением для `caret-color` может быть любое поддерживаемое `CSS` [обозначение цвета](/css/web-colors/). Кроме того доступны ключевые слова:
-  `auto` — значение по умолчанию, 
- `transparent`.

```

Надо расписать какой результат дают ключевые слова. Точно ли `transparent` можно отнести к специфичному ключевому слову для этого свойства?

2021-12-20 11:26 UTC, solarrust commented on css/caret-color/index.md
> +<iframe title="Примеры использования" src="demos/paint-the-caret" height="220"></iframe>
```suggestion
<iframe title="Как красить каретку" src="demos/paint-the-caret" height="220"></iframe>
```

2021-12-20 11:26 UTC, solarrust commented on css/caret-color/index.md
> +Простое `CSS` свойство, служащее единственному назначению, кастомизации цвета для текстового курсора в полях ввода.
```suggestion
Простое CSS-свойство, служащее единственной цели — кастомизации цвета текстового курсора в полях ввода.
```

2021-12-20 18:55 UTC, pepelsbey commented on css/caret-color/demos/paint-the-caret/index.html
> + <input class="blueviolet" type="text" placeholder="blueviolet caret">
А я бы оставил `type="text"`, он более явно говорит, что это за поле. А оптимизацией строк пусть занимаются роботы :)

2021-12-27 07:09 UTC, solarrust commented
@Misha-Mad привет! Успеем закончить до НГ?

2021-12-29 09:59 UTC, solarrust commented
@Misha-Mad пожалуйста, напиши что-нибудь чтобы мы знали, что ты планируешь продолжить работу над статьёй =)

2021-12-29 16:15 UTC, Misha-Mad commented
@solarrust , да, я обязательно доведу статью до ума, в первых числах января, приношу извинения, не всегда возможно найти время.

2022-01-18 05:18 UTC, solarrust commented
@Misha-Mad пинг! Планируешь закончить статью?

2022-01-24 10:49 UTC, solarrust commented on css/caret-color/index.md
> + input {
```suggestion
input {
```

2022-01-24 10:52 UTC, solarrust commented
@mimimad внесла несколько небольших правок. Пожалуйста, посмотри всё ли ОК на твой взгляд =)

2022-01-24 11:14 UTC, solarrust commented on css/caret-color/index.md
> +Простое CSS-свойство, служащее единственной цели — кастомизации цвета для текстового курсора в полях ввода. Текстовый курсор — это видимый маркера, в который будет вставлен следующий введенный символ
```suggestion
Простое CSS-свойство, служащее единственной цели — кастомизации цвета для текстового курсора в полях ввода. Текстовый курсор — это видимый маркера, в который будет вставлен следующий введённый символ. Свойство является наследуемым, поэтому его можно указать глобально или для формы, и не указывать каждому полю ввода отдельно.
```

2022-01-27 21:10 UTC, mimimad commented
> @mimimad внесла несколько небольших правок. Пожалуйста, посмотри всё ли ОК на твой взгляд =)

Спасибо за помощь, думаю всё в порядке теперь. )

2022-01-28 16:55 UTC, solarrust approved these changes
Крутая получилась статья! Спасибо тебе 🙌
Пиши ещё!

2022-01-28 16:55 UTC, merged