Добавляет доку про итератор
doka-guide/content pull request #2619
Opened 2021-12-22 18:36 UTC by kanishev

Fix #2228

2021-12-22 18:42 UTC, kanishev commented
Представляю доку про итератор. Старался писать, придерживаясь плана, который описал в ишью(#2228). Изначально была идея расписывать все подробно (в частности про то как работает сам протокол итератора, про перебираемые объекты). В итоге понял что это слишком скудно и тяжело воспринимается. Думаю, саму суть я передал, что в принципе и планировалось. 
Жду критики и review! Готов работать дальше, с учетом общего мнения.

2021-12-27 09:05 UTC, bespoyasov reviewed
Спасибо за статью!

Получается хорошо 👌 
Я поправил одну ошибку и предложил несколько улучшений по тексту и оформлению.

2021-12-27 09:05 UTC, bespoyasov commented on js/iterator/index.md
> +**Деструктуризация**.
Тут хочется превратить это в подзаголовки, а ещё — согласовать падеж с предыдущим предложением. (Либо закончить предыдущее предложение, чтобы не было ощущения «оборванности».)

2021-12-27 09:05 UTC, bespoyasov commented on js/iterator/index.md
> +[`Array.from()`](js/array-from) позволяет конвертировать итерируемый объект в Array:
```suggestion
[`Array.from()`](/js/array-from) позволяет конвертировать итерируемый объект в Array:
```

2021-12-27 09:05 UTC, bespoyasov commented on js/iterator/index.md
> +Как только метод _next_ завершает перебор, то возвращается _{ done: true }_. Это является сигналом, что итерирование завершено.
```suggestion
Как только метод `next()` завершает перебор, то возвращается `{ done: true }`. Это является сигналом, что итерирование завершено.
```

2021-12-27 14:25 UTC, kanishev commented on js/iterator/index.md
> +title: "Итератор"
Согласен. Не обратил на это внимание. "В ES6 представлена совершенно новая концепция, которая позволяет обеспечить перебор коллекций непосредственно в ядро языка." - подойдет ли такое описание как вариант?

2021-12-27 14:25 UTC, kanishev commented on js/iterator/index.md
> +**Деструктуризация**.
Предлагаю сделать отдельный заголовок "##Где еще встречается итератор" и под ним подзаголовки

2021-12-27 14:56 UTC, pepelsbey requested changes
Спасибо за статью :) Ребята тут всё расскажут про JS, а если про форматирование, то было бы круто:

- Подкрутить стиль кода JS: одиночные кавычки и без точек с запятой
- Сделать  вместо `**жирных параграфов**` обычные `### заголовки`
- Чуть полегче с курсивом, он здесь часто скорее код или просто не нужен

2021-12-29 08:27 UTC, bespoyasov commented on js/iterator/index.md
> +title: "Итератор"
Думаю, можно сократить до «Итераторы перебирают элементы коллекций по одному за раз, отслеживая своё положение». Передадим суть и не вылезем за пределы в 140 символов :–)

2021-12-29 08:27 UTC, bespoyasov commented on js/iterator/index.md
> +**Деструктуризация**.
Да, хорошая идея 👍

2021-12-29 12:37 UTC, kanishev commented on js/iterator/index.md
> +        return { done: false, value: this.from++ };
Определил локальные переменные. Так думаю будет правильно

2021-12-30 14:24 UTC, pepelsbey approved these changes
Немного [поформатировал](https://github.com/doka-guide/content/pull/2619/commits/affdd5ca361ebc5be9d7ab6f1ba0d181e7e160bb), как у нас принято :)

2022-01-10 08:24 UTC, bespoyasov approved these changes
🚀

2022-01-10 08:24 UTC, bespoyasov commented on js/iterator/index.md
> +Чтобы сделать такой объект итерируемым (и позволить `for..of` работать с ним), в нем нужно определить `Symbol.iterator`:
```suggestion
Чтобы сделать такой объект итерируемым (и позволить `for..of` работать с ним), в нём нужно определить `Symbol.iterator`:
```

2022-01-14 07:24 UTC, nlopin commented on js/iterator/index.md
> +Предположим, у нас есть объект `range`, который представляет диапазон чисел:
Какой ещё пример мы можем привести? Смущает, что аналогичный пример используется у learn.javascript.ru

2022-01-14 07:42 UTC, nlopin requested changes
Получилась отличная статья, мы почти готовы её мержить.

Хочется привести пример, который не встречается в популярных учебниках. Давай подумаем, какие варианты у нас есть.

Мне в голову пришло:
- выводить буквы алфавита по порядку (a-z)
- номер банковской карты строкой "1234 4567 2316 1278" выводить в итераторе блоками по 4 символа
- создать объект и написать итератор к нему (например, аккаунт пользователя или что-то более очевидное для итерации)
- просто создать сложный объект с вложенным массивом и итерироваться по этому массиву при попытке итерирования по объекту

2022-01-16 12:28 UTC, kanishev commented
> Получилась отличная статья, мы почти готовы её мержить.
> 
> Хочется привести пример, который не встречается в популярных учебниках. Давай подумаем, какие варианты у нас есть.
> 
> Мне в голову пришло:
> 
> * выводить буквы алфавита по порядку (a-z)
> * номер банковской карты строкой "1234 4567 2316 1278" выводить в итераторе блоками по 4 символа
> * создать объект и написать итератор к нему (например, аккаунт пользователя или что-то более очевидное для итерации)
> * просто создать сложный объект с вложенным массивом и итерироваться по этому массиву при попытке итерирования по объекту

На мой взгляд нужно показать что-нибудь простое, чтобы читатель акцентировал внимание именно на итераторе, без необходимости разбирать, как работает код и за что отвечает. Предлагаю создать простой объект (например user), определить его свойства (например: имя, возраст, пол и т.д.). Или поинтереснее пример. Показать как сделать такой объект итерируемым, с возможность перебирать его через for-of. Что думаете?

2022-01-17 07:57 UTC, bespoyasov commented
Кажется, я вижу «пересечение множеств» в двух последних комментариях — объект `user` с итерацией по его полям :–) 

@nlopin, ты не против?

2022-01-17 21:02 UTC, nlopin commented
Да, мне кажется норм пример 👍

2022-01-18 14:55 UTC, bespoyasov approved these changes

2022-01-18 14:55 UTC, bespoyasov commented on js/iterator/index.md
> +        let result = { done: false, value: person[properties[count]] }
```suggestion
        const key = properties[count]
        let result = { done: false, value: person[key] }
```

2022-01-18 14:55 UTC, bespoyasov commented on js/iterator/index.md
> +        let result = { done: false, value: person[properties[count]] }
Чтобы в голове не приходилось разворачивать слишком много уровней вложенности ↑

2022-01-18 14:56 UTC, bespoyasov commented on js/iterator/index.md
> +        let result = { done: false, value: person[properties[count]] }
В остальном у меня вопросов, вроде, нет :–)

2022-01-18 18:48 UTC, kanishev commented on js/iterator/index.md
> +        let result = { done: false, value: person[properties[count]] }
Да, так будет супер!

2022-01-19 20:34 UTC, nlopin approved these changes
Огонь 👍

2022-01-19 20:35 UTC, nlopin commented on js/iterator/index.md
> +};
```suggestion
  }
}
```

2022-01-19 20:35 UTC, nlopin commented on js/iterator/index.md
> +  console.log(x);
```suggestion
  console.log(x)
```

2022-01-19 20:35 UTC, nlopin commented on js/iterator/index.md
> +description: "Итераторы перебирают элементы коллекций по одному за раз, отслеживая своё положение"
```suggestion
description: "Разбираемся, как сделать перебор элементов коллекций в порядке, котором хочется"
```

2022-01-19 20:39 UTC, merged

2022-01-20 07:00 UTC, kanishev commented
Спасибо за работу, было интересно. Вы огонь!