Добавляет статью про метод массива findIndex
doka-guide/content pull request #2627
Opened 2021-12-24 14:02 UTC by cergmin

Fix #2533

2021-12-27 08:46 UTC, bespoyasov reviewed
Спасибо за статью! 
По содержанию почти всё хорошо, я добавил несколько идей к тексту и повествованию :–)

2021-12-27 08:46 UTC, bespoyasov commented on js/array-find-index/index.md
> +Метод `findIndex` возвращает **индекс** первого найденного в [массиве](/js/arrays) элемента, который подходит под условие в переданной колбэк-функции. Если же ни одного подходящего элемента не найдёт
```suggestion
Метод `findIndex` возвращает _индекс_ первого найденного в [массиве](/js/arrays) элемента, который подходит под условие в переданной колбэк-функции. Если же ни одного подходящего элемента не найдётся, то метод вернёт `-1`.
```

2021-12-27 08:46 UTC, bespoyasov commented on js/array-find-index/index.md
> +Метод `findIndex` пробегается по массиву и возвращает индекс первого элемента, который подходит под условие функции-предиката. Если так получилось, что ничего не подошло, то он возвращает `-1`.
Мне кажется, если мы используем термин «предикат», то в начале тоже стоит использовать «предикат» вместо «колбек». Иначе получается несогласованно, что может запутать.

2021-12-27 08:46 UTC, bespoyasov commented on js/array-find-index/index.md
> +Предикативная функция _(функция-предикат)_ — это самая обычная функция, которая просто проверяет значение на соответствие какому-то условию, а затем возвращает `true` или `false`.
```suggestion
Предикативная функция _(функция-предикат)_ — это функция, которая проверяет значение на соответствие какому-то условию, а затем возвращает `true` или `false`.
```

2021-12-27 08:46 UTC, bespoyasov commented on js/array-find-index/practice/cergmin.md
> +Кажется, что метод `indexOf` проще в использовании, и это действительно так, но из-за своей простоты, он уступает методу `findIndex` по функционалу.
```suggestion
Кажется, что метод `indexOf` проще в использовании, и это действительно так, но из-за своей простоты, он уступает методу `findIndex` в функциональности.
```

2021-12-27 08:46 UTC, bespoyasov commented on js/array-find-index/practice/cergmin.md
> +Например, если мы хотим осуществить поиск по массиву объектов, то `indexOf` вряд ли сможет нам помочь, потому что значения в данном случае [хранятся по ссылками](/js/ref-type-vs-value-type).
Здесь лучше пояснить, почему именно хранение по ссылкам будет мешать. Если смотреть «взглядом новичка», то мы здесь добавляем новое понятие, не объясняя его. Это может запутать.

2021-12-27 15:01 UTC, cergmin commented on js/array-find-index/index.md
> +Предикативная функция _(функция-предикат)_ — это самая обычная функция, которая просто проверяет значение на соответствие какому-то условию, а затем возвращает `true` или `false`.
Это была попытка подчеркнуть, что предикативная функция действительно простая штука, несмотря на страшное название. Видимо неудачная.

2021-12-27 15:02 UTC, pepelsbey requested changes
Спасибо за статью :) Было бы круто нормализовать использование кавычек в JS-коде: сейчас там микс одиночных и двойных. Ну и по мелочи прямо в комментариях.

2021-12-27 15:02 UTC, pepelsbey commented on js/array-find-index/demos/index/index.html
> +</pre>
```suggestion
      <pre><code>
const names = ["Даня", "Саша", "Юля", "Лиза", "Егор", "Лиза"]<br>
function isLisa(element) {
  return element === "Лиза"
}
</code></pre>
```

2021-12-27 15:02 UTC, pepelsbey commented on js/array-find-index/index.md
> +<iframe title="Работа метода findIndex — [].findIndex — Дока" src="demos/index" height="790"></iframe>
```suggestion
<iframe title="Работа метода findIndex" src="demos/index" height="790"></iframe>
```

2021-12-27 15:02 UTC, pepelsbey commented on js/array-find-index/index.md
> +Функция, которую мы передаём в метод `findIndex`, может принимать три параметра:
```suggestion
Функция, которую мы передаём в метод `findIndex`, может принимать три параметра:

```

2021-12-27 15:02 UTC, pepelsbey commented on js/array-find-index/index.md
> +## Как понять
```suggestion
## Как понять

```

2021-12-29 13:34 UTC, cergmin commented on js/array-find-index/index.md
> +Метод `findIndex` пробегается по массиву и возвращает индекс первого элемента, который подходит под условие функции-предиката. Если так получилось, что ничего не подошло, то он возвращает `-1`.
Решил просто убрать «колбек», потому что определение функции-предиката даётся только через 2 параграфа.

2021-12-30 14:34 UTC, pepelsbey approved these changes
[Немного поредактировал](https://github.com/doka-guide/content/pull/2627/commits/118cc633cb542584c48f32b84c540bd05de72588):

- Переименовал путь к демке в более описательный
- Поформатировал JS как у нас принято

2022-01-10 08:33 UTC, bespoyasov approved these changes

2022-01-10 08:33 UTC, bespoyasov commented on js/array-find-index/index.md
> +Напишем код, который позволит найти мою подругу в списке гостей мероприятия. Для этого определим функцию, которая будет сверять имя из массива участников с константой `nameOfMyFrined`, в которую мы з
```suggestion
Напишем код, который позволит найти по имени человека в списке гостей. Для этого определим функцию, которая будет сверять имя из массива участников с константой `nameOfMyFrined`, в которую мы запишем «Лиза». Затем передадим эту функцию в метод `findIndex`.
```

2022-01-10 08:33 UTC, bespoyasov commented on js/array-find-index/index.md
> +Напишем код, который позволит найти мою подругу в списке гостей мероприятия. Для этого определим функцию, которая будет сверять имя из массива участников с константой `nameOfMyFrined`, в которую мы з
Добавил деталей про «поиск по имени», удалил детали, которые мне _кажутся_ лишними. Но это просто мнение, можно этот комментарий проигнорировать.

2022-01-10 08:33 UTC, bespoyasov commented on js/array-find-index/index.md
> +Метод `findIndex` пробегается по массиву и возвращает индекс первого элемента, который подходит под условие функции-предиката. Если так получилось, что ничего не подошло, то он возвращает `-1`.
```suggestion
Метод `findIndex` пробегается по массиву и возвращает индекс первого элемента, который подходит под условие функции-предиката. Если ничего не подошло, то он возвращает `-1`.
```

2022-01-10 08:33 UTC, bespoyasov commented on js/array-find-index/index.md
> +Предикативная функция _(функция-предикат)_ — это функция, которая проверяет значение на соответствие какому-то условию, а затем возвращает `true` или `false`.
```suggestion
<aside>

💡 Предикативная функция _(функция-предикат)_ — это функция, которая проверяет значение на соответствие какому-то условию, а затем возвращает `true` или `false`.

</aside>
```

2022-01-10 08:33 UTC, bespoyasov commented on js/array-find-index/index.md
> +Давайте определим функцию `isEven`, которая проверяет, является ли число чётным, то есть делится на два без остатка. А затем найдём в массиве индекс первого такого числа через `findIndex`.
```suggestion
Определим функцию `isEven`, которая проверяет, является ли число чётным, то есть делится на два без остатка. А затем найдём в массиве индекс первого такого числа через `findIndex`.
```

2022-01-22 14:19 UTC, cergmin commented
@nlopin, глянь, пожалуйста, нужен последний апрув :)

2022-01-30 18:46 UTC, nlopin approved these changes
Сергей, всё круто 👍 

Извини, что процесс затянулся. Я немного поправил структуру и добавил подсказку

2022-01-30 18:49 UTC, merged

2022-01-31 03:25 UTC, cergmin commented
@nlopin, увидел, что строчки типа:
```js
// Возвращает: -1
// Элемент не найден
meetingGuests.findIndex(isWantedGuest)
```

превратились в:
```js
console.log(meetingGuests.findIndex(isWantedGuest))
// -1 (так как совпадений нет)
```

Примеры с `console.log(...)` часто встречаются и в других доках. Хотел спросить, почему так, зачем обёртывать функцию в console.log? Кажется, что из-за этого пример выглядит менее понятным и удобочитаемым.