Добавляет доку про [].flat
doka-guide/content pull request #2651
Opened 2022-01-02 21:39 UTC by AgarkovRoman

2022-01-05 22:02 UTC, pepelsbey requested changes
Привет! Спасибо за доку :)

Есть идея: может два сложных блока кода с нарративом в комментах и сложными логами превратить в текст с примерами? Что-то вроде:

> Например, у нас есть такой массив
>
> [входной массив]
>
> Давайте вызовем метод
>
> [метод]
>
> Тогда в переменной будет
>
> [выходной массив]

Такой текст будет понятнее и не нужно будет ломать глаза в бледных комментариях.

Ну и конечно развернуть все эти массивы, чтобы структура была наглядной, даже если читаешь с мобилки.

2022-01-05 22:02 UTC, pepelsbey commented on js/array-flat/index.md
> +// ['первый уровень', 'первый уровень', 'второй уровень', 'второй уровень', ['третий уровень', 'третий уровень']]
Здесь конечно тоже можно развернуть, то это всё потом нужно прятать в комментарии.

2022-01-05 22:02 UTC, pepelsbey commented on js/array-flat/index.md
> +В этот метод можно передать числовое значение `depth` — оно обозначает на какое количество уровней уменьшается вложенность. Дефолтное значение — 1.
```suggestion
Метод `Array.flat` уменьшает вложенность массива. В этот метод можно передать числовое значение `depth` — оно обозначает на какое количество уровней уменьшается вложенность. Дефолтное значение — 1.
```

2022-01-08 20:21 UTC, AgarkovRoman commented on js/array-flat/index.md
> +В этот метод можно передать числовое значение `depth` — оно обозначает на какое количество уровней уменьшается вложенность. Дефолтное значение — 1.
Поправил

2022-01-08 20:22 UTC, AgarkovRoman commented on js/array-flat/index.md
> +const nested = ['первый уровень', 'первый уровень', ['второй уровень', 'второй уровень', ['третий уровень', 'третий уровень']]]
Согласен, так выглядит намного лучше! 😊

2022-01-08 20:24 UTC, AgarkovRoman commented
@pepelsbey Привет! Идея разбить примеры с кодом хорошая. Мне кажется теперь стало понятнее 👍🏻

2022-01-10 08:14 UTC, bespoyasov approved these changes
Спасибо за статью! 👍 
Всё хорошо, только добавим описание в мета-данных (подробнее в комментариях).

2022-01-10 08:14 UTC, bespoyasov commented on js/array-flat/index.md
> +title: "`[].flat`"
В мета-информации сейчас не хватает `description` для соцсетей и описания на странице статьи. Добавим короткое (<140 символов) описание?

2022-01-10 08:14 UTC, bespoyasov commented on js/array-flat/index.md
> +Например, у нас есть такой массив
```suggestion
Например, у нас есть многоуровневый массив:
```

2022-01-10 08:14 UTC, bespoyasov commented on js/array-flat/index.md
> +Тогда в переменной будет
```suggestion
Тогда в переменной `flat` будет:
```

2022-01-10 08:14 UTC, bespoyasov commented on js/array-flat/index.md
> +Этот метод позволяет уменьшить вложенность массива на заданное количество уровней.
Думаю, можно дописать, что метод не мутирует массив, а возвращает новый. Разработчики часто ищут ответ на этот вопрос, мы можем ответить на него в первой же строке.

2022-01-10 21:36 UTC, AgarkovRoman commented on js/array-flat/index.md
> +Этот метод позволяет уменьшить вложенность массива на заданное количество уровней.
Согласен, добавил

2022-01-10 21:37 UTC, AgarkovRoman commented on js/array-flat/index.md
> +title: "`[].flat`"
Добавил

2022-01-10 21:39 UTC, AgarkovRoman commented
@bespoyasov, внёс правки, глянешь на формулировку description и описание в блоке "Кратко"?

2022-01-10 22:14 UTC, pepelsbey requested changes
Я бы ещё дожал, чтобы не прятать в комментах самое важное.

@bespoyasov @nlopin что скажете?

2022-01-10 22:14 UTC, pepelsbey commented on js/array-flat/index.md
> +*/
```suggestion
[
  'первый уровень',
  'первый уровень',
  'второй уровень',
  'второй уровень',
  [
    'третий уровень',
    'третий уровень'
  ]
]
```

Мне кажется, что лучше чётко и понятно показать структуру, а не как её в консоль выводить. Пока по подсветке именно так — лог первичный, массив вторичный.

2022-01-10 22:14 UTC, pepelsbey commented on js/array-flat/index.md
> +*/
```suggestion
[
  'первый уровень',
  'первый уровень',
  'второй уровень',
  'второй уровень',
  'третий уровень',
  'третий уровень',
  'четвертый уровень',
  'четвертый уровень'
]
```

2022-01-11 15:53 UTC, AgarkovRoman commented on js/array-flat/index.md
> +*/
Тоже подумал, что это может быть неочевидным, но, думаю, можно описать словами, как ты предложил.

2022-01-12 19:11 UTC, AgarkovRoman commented on js/array-flat/index.md
> +*/
Убрал console.log и раскомментировал массив

2022-01-12 19:12 UTC, AgarkovRoman commented on js/array-flat/index.md
> +*/
Тут тоже поправил

2022-01-12 19:12 UTC, AgarkovRoman commented
@pepelsbey я дожал 😊

2022-01-30 18:03 UTC, nlopin approved these changes
Класс! Я чуть поправил структуру, чтобы она следовала рекомендациям: кратко → пример → как пишется → как понять

Извини, что ревью затянулось. Это целиком моя вина 🙇‍♂️

2022-01-30 18:04 UTC, merged