Добавляет обзорную статью про Map
doka-guide/content pull request #2654
Opened 2022-01-05 21:58 UTC by vitalybaev

Решает #1384

Постарался рассказать об основных моментах не раздувая статью, а дальше можно детализировать как в статьях про `Set` и его методы.

2022-01-10 09:08 UTC, bespoyasov reviewed
Спасибо за статью!
Я добавил несколько уточнений, идей для улучшения и факт-чек, но в целом — 👍

2022-01-10 09:08 UTC, bespoyasov commented on js/map/index.md
> +При использовании непримитивных типов в качестве ключей стоит помнить, что они [хранятся по ссылке](/js/ref-type-vs-value-type/), поэтому для доступа к заданному с помощью объекта ключу, необходимо п
Здесь нужно ещё упомянуть, что можно искать по `NaN`-ключу, и это сработает, хотя `NaN !== NaN`.

2022-01-10 09:08 UTC, bespoyasov commented on js/map/index.md
> +При использовании непримитивных типов в качестве ключей стоит помнить, что они [хранятся по ссылке](/js/ref-type-vs-value-type/), поэтому для доступа к заданному с помощью объекта ключу, необходимо п
(Возможно, в коллауте также можно сослаться на спецификацию и алгоритм `sameValueZero`.)

2022-01-10 09:08 UTC, bespoyasov commented on js/map/index.md
> +### Работа с коллекцией
Добавим ещё проверку на существование значения через `.has()`:

```
const map = new Map();
map.has('kek');
// false
```

2022-01-10 09:08 UTC, bespoyasov commented on js/map/index.md
> +map.forEach((key, value) => {
Тут, думаю, стоит добавить коллаут, в котором обратить внимание, что аргументы в колбеке именно `key, value`. (Нет индексов, нет самой коллекции.)

2022-01-10 09:14 UTC, vitalybaev commented on js/map/index.md
> +При использовании непримитивных типов в качестве ключей стоит помнить, что они [хранятся по ссылке](/js/ref-type-vs-value-type/), поэтому для доступа к заданному с помощью объекта ключу, необходимо п
Кстати хороший поинт насчет `sameValueZero`. Я еще создавал ишью #2642 с таким посылом - хочется один раз написать что такое например `sameValueZero` и на него ссылаться или еще каким-либо образом "использовать".
Иначе у нас будет достаточно много повторений.

2022-01-10 09:15 UTC, bespoyasov commented on js/map/index.md
> +При использовании непримитивных типов в качестве ключей стоит помнить, что они [хранятся по ссылке](/js/ref-type-vs-value-type/), поэтому для доступа к заданному с помощью объекта ключу, необходимо п
@nlopin, что думаешь?

2022-01-10 11:32 UTC, vitalybaev commented on js/map/index.md
> +- `set(key, value)` — сохраняет значение
Выберу первый вариант. Стоит ли добавить пояснение "Устанавливает значение для ключа `key`"?

2022-01-11 08:27 UTC, vitalybaev commented on js/map/index.md
> +## Как понять
Тоже думал насчет таблицы, но решил рассказать об отличиях в разных местах.

Поменяю на таблицу.

Один вопрос - что за отличие, что свежесозданный `Map` не имеет никаких ключей? Я ошибаюсь или ровно такое поведение и у объекта? И если мы говорим про скрытые ключи, то по идее они и у `Map` присутствуют поскольку это тоже объект

2022-01-12 07:31 UTC, bespoyasov commented on js/map/index.md
> +## Как понять
Я имел в виду, что у `Map` только те ключи, которые мы явно добавляем, а у объекта можно перетереть дефолтные:

```js
// Object:
const a = {};

a.toString = 'kek';
// 'kek'

a.toString();
// Uncaught TypeError: a.toString is not a function


// Map:
const b = new Map();

b.set('toString', 'kek');
b.toString();
// '[object Map]'

b.get('toString')
// 'kek'
```

2022-01-26 06:49 UTC, nlopin commented on js/map/index.md
> +description: "Коллекция для хранения данных"
Думаю тут важно дать конкретики, потому что массив тоже коллекция, которая хранит данные:

```suggestion
description: "Коллекция для хранения данных по ключу"
```

2022-01-26 06:50 UTC, nlopin commented on js/map/index.md
> +- `set(key, value)` — сохраняет значение
Уточнение не нужно, но вот параметры я бы на русский язык перевёл

2022-01-26 06:52 UTC, nlopin commented on js/map/index.md
> +`Map` - коллекция для хранения данных любого типа в виде пар `[ключ, значение]`. Причём в качестве ключей тоже принимаются значения любого типа.
Давай добавим фразочку, что значение хранится и получается по ключу, чтобы подчеркнуть смысл ключа

2022-01-26 06:59 UTC, nlopin commented on js/map/index.md
> +А можно сразу передать начальные значения. Для этого нужно передать первым аргументом конструктора массив, состоящий из других массивов (каждый длиной ровно в 2 элемента), каждый из которых описывает
Сложное предложение про структуру массива получилось. Вот так мне кажется проще следить за требованиями к массиву:

```suggestion
А можно сразу передать начальные значения. Для этого в конструктор нужно передать массив, состоящий из других массивов. Эти массивы должны состоять из двух элементов: первый элемент — ключ, а второй — значение:
```

2022-01-26 07:03 UTC, nlopin commented on js/map/index.md
> +Получить значение можно при помощи метода `get()` единственным аргументом которого передаём ключ, данные которого хотим получить:
Тут нужно добавить, что возвращает этот метод. Кажется он возвращает либо значение, либо `undefined`

2022-01-26 07:06 UTC, nlopin commented on js/map/index.md
> +Удалять конкретное значение можно методом `delete()`, который также принимает ключ в качестве аргумента, а полностью очищает коллекцию метод `clear()`:
что будет если я удалю ключ, которого нет? Метод `delete()` возвращает булевое значение, был ли такой ключ в коллекции или нет

2022-01-26 07:08 UTC, nlopin commented on js/map/index.md
> +### Особенности ключей
Давай явно пропишем, что у нас тут сравнение с объектами

```suggestion
### Отличия от объектов
```

2022-01-26 07:10 UTC, nlopin commented on js/map/index.md
> +При использовании непримитивных типов в качестве ключей стоит помнить, что они [хранятся по ссылке](/js/ref-type-vs-value-type/), поэтому для доступа к заданному с помощью объекта ключу, необходимо п
да, мы пока не решили, как с такими штуками быть. Давай пока напишем тут в details?

2022-01-26 07:13 UTC, nlopin commented on js/map/index.md
> +// Мы на самом деле в двух разных переменных ссылаемся на один и тот же объект в памяти
Давай это вынесем в текст над примером.

«Создадим две переменные, которые указывают на один и тот же объект и добавим их ключами в `Map`:»

2022-01-26 07:14 UTC, nlopin commented on js/map/index.md
> +А вот если мы возьмём два не связанных объекта, хоть и с одинаковым содержимым, то мы получим два разных ключа:
```suggestion
А вот если мы возьмём два отдельных объекта с одинаковым содержимым, то мы получим два разных ключа:
```

2022-01-26 07:17 UTC, nlopin requested changes
Спасибо за статью и классные примеры. Нужно уточнить возвращаемые значения у методов и кажется всё готово.

MDN как отличие от объектов приводит ещё фразу:

>  Map performs better in scenarios involving frequent additions and removals of key-value pairs. 

Вот тут интересное поле для микроисследования, действительно ли это так.

2022-01-26 07:20 UTC, nlopin commented on js/map/index.md
> +- `forEach(callback)` — перебирает ключи и значения коллекции
Нам для полноты не хватает `.keys()`, `.values()` и `entries()`. Давай их допишем сюда, но в основной текст можно не добавлять

2022-01-26 07:22 UTC, nlopin commented
@vitalybaev прости, что ревью заняло так много времени — это целиком моя вина. Если ты уже не готов дорабатывать статью, то это нормально. Дай нам знать и мы дошлифуем сами.

2022-01-26 08:10 UTC, vitalybaev commented
@nlopin Нет, всё огонь! Я обязательно доработаю статью в самое ближайшее время. Я просто моргнул, а уже январь заканчивается :)

2022-01-26 08:15 UTC, vitalybaev commented
> Map performs better in scenarios involving frequent additions and removals of key-value pairs.

Такое мнение я встречал и не только на MDN. Но простой синтетический тест пока меня [не убедил](https://perf.link/#eyJpZCI6Im1sOWpwc3QzMG1hIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXSIsInRlc3RzIjpbeyJuYW1lIjoiRmluZCBpdGVtIDEwMCIsImNvZGUiOiJjb25zdCBpdGVtcyA9IHt9XG5kYXRhLmZvckVhY2goKHgsIGkpID0%2BIHtcbiAgaXRlbXNbaV0gPSBgJHt4fSR7aX1gXG59KSIsInJ1bnMiOls5MDAwLDEwMzMzLDc2NjYsNjAwMCw5NjY2LDEyMDAwLDkzMzMsNDMzMywxMzY2NiwxMzAwMCwxNzY2Niw4NjY2LDExMzMzLDE2MDAwLDE4MDAwLDcwMDAsOTMzMyw4NjY2LDgwMDAsODAwMCwxMTY2NiwxNzMzMywxMDMzMywxMjAwMCwxMTY2Niw5MzMzLDExMDAwLDEyMzMzLDEzNjY2LDEzMzMzLDEyNjY2LDgzMzMsMTU2NjYsMTIzMzMsMTMwMDAsMTAzMzMsODAwMCw5MDAwLDEyMzMzLDE0MzMzLDE1MzMzLDEwMzMzLDEwNjY2LDEwMDAwLDgzMzMsMTA2NjYsOTY2Niw5NjY2LDkwMDAsMTAwMDAsODMzMywxMDMzMyw4MzMzLDExMzMzLDEwMzMzLDkwMDAsMTAwMDAsMTAzMzMsODY2Niw2MzMzLDExMzMzLDkwMDAsNzY2NiwxMDMzMyw5MzMzLDEwMzMzLDExMzMzLDEyMDAwLDkzMzMsMTE2NjYsMTEwMDAsODY2Niw5MzMzLDEzNjY2LDE0MDAwLDM2NjYsMTAwMDAsMTU2NjYsMTAzMzMsNDMzMywxMDMzMywxMjY2Niw4MDAwLDEzMDAwLDEyMDAwLDEwNjY2LDk2NjYsOTY2Niw4NjY2LDkzMzMsMTEzMzMsMTAzMzMsOTY2Niw4MDAwLDEzMDAwLDEzMzMzLDc2NjYsMTEzMzMsMTMzMzMsMTIzMzNdLCJvcHMiOjEwNjAzfSx7Im5hbWUiOiJGaW5kIGl0ZW0gMjAwIiwiY29kZSI6ImNvbnN0IGl0ZW1zID0gbmV3IE1hcCgpXG5kYXRhLmZvckVhY2goKHgsIGkpID0%2BIHtcbiAgaXRlbXMuc2V0KGksIGAke3h9JHtpfWApXG59KSIsInJ1bnMiOlszMzMzLDQwMDAsMjY2NiwyMDAwLDMzMzMsNDMzMywzMzMzLDEzMzMsNDMzMyw0MzMzLDUzMzMsMzAwMCw0MzMzLDQ2NjYsNTY2NiwyMzMzLDMzMzMsMzMzMywzMDAwLDI2NjYsNDMzMyw1MzMzLDQwMDAsNDMzMyw0MzMzLDMzMzMsNDMzMyw0MzMzLDQzMzMsNDMzMyw0MzMzLDMwMDAsNDY2Niw0MzMzLDQzMzMsMzY2NiwyNjY2LDMzMzMsNDMzMyw0MzMzLDQzMzMsNDAwMCwzNjY2LDMzMzMsMzAwMCwzNjY2LDQzMzMsMzMzMywzMzMzLDMzMzMsMzAwMCwzNjY2LDMwMDAsNDAwMCwzNjY2LDMzMzMsMzY2NiwzNjY2LDMwMDAsMjMzMyw0MDAwLDMzMzMsMzAwMCwzMzMzLDMzMzMsMzY2Niw0MzMzLDQzMzMsMzAwMCw0MzMzLDQwMDAsMjY2NiwzMzMzLDQzMzMsNDMzMywxMzMzLDQwMDAsNDY2NiwzNjY2LDEzMzMsMzY2Niw0MzMzLDMwMDAsNDMzMyw0MzMzLDQwMDAsMzMzMywzMzMzLDMwMDAsMzMzMyw0MzMzLDM2NjYsMzMzMywyMzMzLDQzMzMsNDMzMywyMzMzLDQwMDAsNDMzMyw0MzMzXSwib3BzIjozNjY2fV0sInVwZGF0ZWQiOiIyMDIyLTAxLTI2VDA4OjExOjQ1LjYxOFoifQ%3D%3D), поэтому я решил пока этот пункт никак не указывать, чтобы не вводить в заблуждение. Но еще порисёрчить конечно можно

2022-01-26 11:03 UTC, nlopin commented
Надо еще удаление смотреть, думаю там может быть бутылочное горлышко

2022-01-26 13:48 UTC, bespoyasov commented
> Если у тебя есть идеи, в каких ситуациях удобнее применять Map вместо объекта, то классно добавить это в блок «На практике». @bespoyasov у тебя есть хорошие примеры?

Как вариант, его можно использовать для кэширования операций со сложными структурами.

```js
function createTree(arbitraryDataStructure) {
  // ...Magic.
  return tree
}

function withCache(transformation) {
  const cache = new Map();
  
  return function perform(structure) {
    if (cache.has(structure)) {
      console.log('Found in cache!');
      return cache.get(structure);
    }

    const result = transformation(structure);
    cache.set(structure, result);
    return result;
  }
}

// ...

const a = {hello: 'world'}
const b = {hiThere: 'General Kenobi'}

const cachedCreateTree = withCache(createTree)

cachedCreateTree(a)
cachedCreateTree(a)
// Found in cache!

cachedCreateTree(b)
cachedCreateTree(b)
// Found in cache!
```

Только надо предупредить, что декоратор не получится универсальным, потому что мы не можем передавать весь список аргументов. (Потому что это каждый раз новый массив.)

2022-02-04 15:33 UTC, vitalybaev commented on js/map/index.md
> +### Работа с коллекцией
Добавил 👌

2022-02-04 15:34 UTC, vitalybaev commented on js/map/index.md
> +map.forEach((key, value) => {
Добавил его, но что-то с формулировками сомневаюсь

2022-02-04 15:34 UTC, vitalybaev commented on js/map/index.md
> +description: "Коллекция для хранения данных"
Обновил 👌

2022-02-04 15:35 UTC, vitalybaev commented on js/map/index.md
> +`Map` - коллекция для хранения данных любого типа в виде пар `[ключ, значение]`. Причём в качестве ключей тоже принимаются значения любого типа.
Обновил

2022-02-04 15:35 UTC, vitalybaev commented on js/map/index.md
> +А можно сразу передать начальные значения. Для этого нужно передать первым аргументом конструктора массив, состоящий из других массивов (каждый длиной ровно в 2 элемента), каждый из которых описывает
Да, я свой мозг сломал, пытаясь упростить его, но как видишь... 😅

2022-02-04 15:36 UTC, vitalybaev commented on js/map/index.md
> +Получить значение можно при помощи метода `get()` единственным аргументом которого передаём ключ, данные которого хотим получить:
Добавил упоминание

2022-02-04 15:36 UTC, vitalybaev commented on js/map/index.md
> +Удалять конкретное значение можно методом `delete()`, который также принимает ключ в качестве аргумента, а полностью очищает коллекцию метод `clear()`:
Добавил

2022-02-04 15:36 UTC, vitalybaev commented on js/map/index.md
> +### Особенности ключей
Обновил

2022-02-04 15:36 UTC, vitalybaev commented on js/map/index.md
> +// Мы на самом деле в двух разных переменных ссылаемся на один и тот же объект в памяти
Обновил

2022-02-04 15:36 UTC, vitalybaev commented on js/map/index.md
> +- `forEach(callback)` — перебирает ключи и значения коллекции
Добавил их упоминание

2022-02-04 15:37 UTC, vitalybaev commented
Закрыл бОльшую часть обсуждение, но не всё. Планирую в выходные закончить все пункты

2022-02-07 08:12 UTC, bespoyasov commented on js/map/index.md
> +map.forEach((key, value) => {
LGTM :–)

2022-02-07 08:12 UTC, bespoyasov commented on js/map/index.md
> +`Map` использует строгое сравнение для проверки ключей, привидение типов не происходит. Поэтому, число и строковое представление этого же числа будут являться двумя разными ключами:
Тут можно запутать читателей. При строгом сравнении `NaN !== NaN`, но в `Map` его использовать как ключ можно. Возможно, при описании `key identity` стоит упомянуть [sameValueZero](https://www.ecma-international.org/ecma-262/7.0/#sec-samevaluezero).

2022-02-07 08:34 UTC, vitalybaev commented on js/map/index.md
> +`Map` использует строгое сравнение для проверки ключей, привидение типов не происходит. Поэтому, число и строковое представление этого же числа будут являться двумя разными ключами:
Да, sameValueZero обязательно упомяну, в выходные не успел, но допишу в ближайшее время

2022-02-07 15:27 UTC, vitalybaev commented on js/map/index.md
> +## Как понять
Я вижу в такой формулировке один подводный камень - мы говорим, что "у `Map` только те ключи, которые мы явно добавляем". Но мне кажется, что лучше явно сказать что ключи `Map`  про которые мы говорим в статье **это не то же самое, что и ключи обычного объекта**. Более того, все эти правила ключей объектов относятся и к Map, потому что он сам является объектом. Причём я бы добавил это колаутом вначале секции "Отличия от объектов"

Что думаете?

2022-02-07 17:05 UTC, vitalybaev commented on js/map/index.md
> +`Map` использует строгое сравнение для проверки ключей, привидение типов не происходит. Поэтому, число и строковое представление этого же числа будут являться двумя разными ключами:
@bespoyasov @nlopin 
Добавил пункт про SameValueZero, посмотрите, пожалуйста, ок или слишком?

Единственное, смотрю вложенный список не завелся.

2022-02-07 17:10 UTC, vitalybaev commented
Все мелкие комментарии исправил. Я попрошу вас закрыть обсуждения, по которым ок с вашей стороны, чтобы не висели :)

Про `SameValueZero` упомянул. Следующей правкой доработаю раздел отличий от объектов, добавлю наглядную таблицу.

В итоге у нас останется решить что-нибудь в обсуждении касательно ключей `Map`. В общем, финиш уже близко :)

2022-02-08 07:30 UTC, nlopin commented on js/map/index.md
> +const map = new Map([['key1', 'значение для key1'], ['key2', 'значение для key2']])
давай тут осмысленные ключи сделаем? сериал — год выхода или что-то такое

2022-02-08 07:48 UTC, nlopin commented on js/map/index.md
> +const map = new Map([['key1', 'значение для key1'], ['key2', 'значение для key2']])
сам залил

2022-02-08 07:51 UTC, nlopin commented on js/map/index.md
> +## Как понять
мне норм. @bespoyasov ?

2022-02-08 08:11 UTC, nlopin commented on js/map/index.md
> +`Map` использует строгое сравнение для проверки ключей, привидение типов не происходит. Поэтому, число и строковое представление этого же числа будут являться двумя разными ключами:
поправил

2022-02-08 08:11 UTC, nlopin approved these changes

2022-02-08 08:20 UTC, bespoyasov commented on js/map/index.md
> +## Как понять
Да, так лучше.

2022-02-08 08:51 UTC, merged

2022-02-08 08:52 UTC, nlopin commented
Виталий, спасибо за помощь! Статья получилась офигенная. Приходи писать ещё, мы будем оперативнее

2022-02-08 09:39 UTC, vitalybaev commented
Спасибо! Всё в порядке, я сам пропадал почти на месяц :)
Обязательно приду писать еще - во-первых, самому полезен такой опыт, заставляет лучше изучить какие-то моменты, а во-вторых, вы очень клёвые 🚀