Пробный рецепт
doka-guide/content pull request #2671
Opened 2022-01-16 11:40 UTC by solarrust

@pepelsbey @tachisis @nlopin написала пробный рецепт. Взяла за основу наши снежинки.

Обсуждаемо абсолютно всё: от названия папки до  структуры. 
Единственное, что пока не добавляла демку (-ки) потому что пока не поняла надо ли на каждый шаг делать отдельную демку или хватит пары _финальных_.

2022-01-17 06:56 UTC, skorobaeus commented on recipes/snow/index.md
> +В начале 2000-х было очень можно добавлять на сайты падающий снег. Тогда это была нетривиальная задача, требовала много усилий разработчика и сильно нагружала и без того слабые компьютеры пользовател
```suggestion
В начале 2000-х было очень модно добавлять на сайты падающий снег. Тогда это была нетривиальная задача, требовала много усилий разработчика и сильно нагружала и без того слабые компьютеры пользователей.
 ```

2022-01-17 06:59 UTC, skorobaeus commented on recipes/snow/index.md
> +Напишем оптимизированный и производительный падающий снег для сайта.
Я здесь запнулась об резкий переход с "я" на "мы". Можно написать последнюю фразу от первого лица, например: 

```suggestion
Первым делом я пошла искать готовые решения. Нашла несколько заготовок, но все они были сложными и тяжёлыми. Для простых падающих снежинок подключались целые библиотеки анимации и были написаны сотни строк JavaScript.

Поэтому я решила написать оптимизированный и производительный падающий снег для сайта сама.
```

А дальше, после подзаголовка, уже путь идёт "мы".

2022-01-17 07:00 UTC, skorobaeus commented on recipes/snow/index.md
> +Создадим разметку для снежинок. Понадобиться родительский контейнер с классом `snow`. Внутри будут блоки с классом `snow__flake` и символом `﹡` в контенте.
```suggestion
Создадим разметку для снежинок. Понадобится родительский контейнер с классом `snow`. Внутри будут блоки с классом `snow__flake` и символом `﹡` в контенте.
```

2022-01-17 07:07 UTC, skorobaeus commented on recipes/snow/index.md
> +  will-change: transform;
Вау, не знала о нём! Дока образовательная <3

2022-01-17 07:14 UTC, furtivite commented on recipes/snow/index.md
> +  - doka
Вот тут я немного сомневаюсь, что нужен именно тег `doka`. Кажется, тут совсем не дока, а скорее `recipes`, но пока платформа их не принимает и надо обсудить с @monochromer, и командой, чтобы просто не перемешивать рецепты с доками.

2022-01-17 07:16 UTC, skorobaeus commented on recipes/snow/index.md
> +Последний шаг. Добавим обработчик события на изменение записей в локальном хранилище. Как только запись меняется, так сразу вызывается функция изменения анимации, передавая в неё текущее значение из
Напомнило ироничное "как только, так сразу", мне кажется, здесь это не очень нужно :)

```suggestion
Последний шаг. Добавим обработчик события на изменение записей в локальном хранилище. Как только запись меняется, сразу вызывается функция изменения анимации, передавая в неё текущее значение из хранилища:
```

2022-01-17 07:17 UTC, furtivite commented on recipes/snow/index.md
> +```
Вот тут, кажется, можно было бы добавить врезку о том, что не обязательно повторять снежинку именно в HTML, а можно сделать цикл, например в Доке (на nunjucks) он был написан так:

```njk
{% for i in range(0, 90) -%}
    <div class="snow__flake">﹡</div>
{%- endfor %}
```

Но для большинства проектов можно добавить и при помощи JS.

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +В начале 2000-х было очень модно добавлять на сайты падающий снег. Тогда это была нетривиальная задача, требовала много усилий разработчика и сильно нагружала и без того слабые компьютеры пользовател
```suggestion
В начале 2000-х было очень модно добавлять на сайты падающий снег. Тогда это была нетривиальная задача, она требовала много усилий разработчика и сильно нагружала и без того слабые компьютеры пользователей.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Напишем оптимизированный и производительный падающий снег для сайта.
Плюсую

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Для начала сделаем блок `.snow` флекс-контейнером чтобы все вложенные блоки встали в один ряд. Используем свойство [`justify-content`](/css/justify-content) чтобы все снежинки распределились на всю ш
```suggestion
Для начала сделаем блок `.snow` флекс-контейнером, чтобы все вложенные блоки встали в один ряд. Используем свойство [`justify-content`](/css/justify-content), чтобы снежинки распределились на всю ширину экрана:
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Расположим весь блок со снегом поверх страницы при помощи [`position: fixed`](/css/position/) и прижмём ко всем четырём краям окна. Чтобы снег шёл поверх всех блоков добавим [`z-index: 100`](/css/z-i
```suggestion
Расположим весь блок со снегом поверх страницы при помощи [`position: fixed`](/css/position/) и прижмём ко всем четырём краям окна. Чтобы снег шёл поверх всех блоков, добавим [`z-index: 100`](/css/z-index/):
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Поднимем снежинки чуть выше края экрана. Чтобы не мозолили глаза пользователю пока не начнут своё движение:
```suggestion
Поднимем снежинки чуть выше края экрана. Чтобы не мозолили глаза пользователю, пока не начнут своё движение:
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Элемент, к которому мы применим эту анимацию будет при помощи [трансформации](/css/transform) перемещаться по вертикали от верхнего края до 100 единиц [высоты экрана](/css/vw-vh/) и ещё плюс 1.5 em,
```suggestion
Элемент, к которому мы применим эту анимацию, будет при помощи [трансформации](/css/transform) перемещаться по вертикали от верхнего края до 100 единиц [высоты экрана](/css/vw-vh/) и ещё плюс 1.5 em, чтобы снежинки скрывались за нижним краем страницы.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Заодно зададим свойство [`animation-timing-function`](/css/animation-timing-function/) со значением `ease-in-out` чтобы снежинки начинали и заканчивали своё падение медленно, а посередине ускорялись.
```suggestion
Заодно зададим свойство [`animation-timing-function`](/css/animation-timing-function/) со значением `ease-in-out`, чтобы снежинки начинали и заканчивали своё падение медленно, а посередине ускорялись.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Свойство [`animation-iteration-count`](/css/animation-iteration-count/) со значением `infinite` означает что анимация будет повторяться бесконечно.
```suggestion
Свойство [`animation-iteration-count`](/css/animation-iteration-count/) со значением `infinite` означает, что анимация будет повторяться бесконечно.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Чтобы браузер заранее подготовил ресурсы для анимации сообщим ему о том, какое конкретно CSS-свойство будет анимировано. Сделать это можно при помощи свойства `will-change`.
```suggestion
Чтобы браузер заранее подготовил ресурсы для анимации, сообщим ему о том, какое конкретно CSS-свойство будет анимировано. Сделать это можно при помощи свойства `will-change`.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Чтобы добавить лёгкого рандома и заставить снежинки падать с разной скоростью и разной задержкой используем JS. Потому что в CSS пришлось бы написать довольно много строк кода для достижения того же
```suggestion
Чтобы добавить лёгкого рандома и заставить снежинки падать с разной скоростью и разной задержкой, используем JS. Потому что в CSS пришлось бы написать довольно много строк кода для достижения того же результата.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Нам понадобятся две функции рандома. Первая будет возвращать целое значение в указанном диапазоне включая конечные точки:
```suggestion
Нам понадобятся две функции рандома. Первая будет возвращать целое значение в указанном диапазоне, включая конечные точки:
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Обратите внимание, что CSS-свойство [`animation-duration`](/css/animation-duration) пишется не через тире. Это особенность [работы со стилями](/js/element-style/) в JavaScript.
```suggestion
Обратите внимание, что CSS-свойство [`animation-duration`](/css/animation-duration) пишется не через дефис. Это особенность [работы со стилями](/js/element-style/) в JavaScript.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Теперь все снежинки падают с разной скоростью, но начинают своё движение в одно время. Добавим рандомности и в этом. Каждой снежинке пропишем свойство [`animation-delay`](/css/animation-delay/) со зн
```suggestion
Теперь все снежинки падают с разной скоростью, но начинают своё движение в одно время. Добавим рандомности и в этом. Каждой снежинке пропишем свойство [`animation-delay`](/css/animation-delay/) со значением от -1 до числа, равного количеству блоков со снежинками, делённому на два. Тут можно смело экспериментировать и подбирать разные значения.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Используем в качестве переключателей радио-кнопки. Обязательно обернём их [`<label>`](/html/label/) чтобы кнопки были доступными для пользователей со [скринридерами](/html/screenreaders/).
```suggestion
Используем в качестве переключателей радио-кнопки. Обязательно обернём их [`<label>`](/html/label/), чтобы кнопки были доступными для пользователей со [скринридерами](/html/screenreaders/).
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Чтобы радио-кнопки знали о состоянии друг друга важно задать им одинаковое значение свойства `name`. Значение свойства `value` тоже важно. Мы будем манипулировать им при помощи JS. По умолчанию снег
```suggestion
Чтобы радио-кнопки знали о состоянии друг друга, важно задать им одинаковое значение свойства `name`. Значение свойства `value` тоже важно. Мы будем манипулировать им при помощи JS. По умолчанию снег будет идти, поэтому первой радиокнопке добавим атрибут `checked`.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Кажется, что всё супер. Снег теперь можно включать и выключать. Но засада в том, что после перехода на другую страницу или после перезагрузки снежинки снова начнут падать. Значит нужно сохранять куда
```suggestion
Кажется, что всё супер. Снег теперь можно включать и выключать. Но засада в том, что после перехода на другую страницу или после перезагрузки снежинки снова начнут падать. Значит, нужно сохранять куда-то выбранное пользователем состояние.
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +## Сохраняем выбора
```suggestion
## Сохраняем выбор
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Добавим ещё один обработчик события. На этот раз будем _слушать_ полную загрузку HTML-разметки страницы. После загрузки проверим текущее значение свойства анимации в хранилище. Если пользователь уже
```suggestion
Добавим ещё один обработчик события. На этот раз будем _слушать_ полную загрузку HTML-разметки страницы. После загрузки проверим текущее значение свойства анимации в хранилище. Если пользователь уже заходил на сайт и нажал на одну из кнопок переключателя, то в хранилище будет это записано, и мы включим выбранный режим:
```

2022-01-18 18:53 UTC, tachisis commented on recipes/snow/index.md
> +Теперь поменяем состояние радио-кнопок переключателей в соответствии с тем, что записано в хранилище. Ищем кнопку с классом `snow-toggle__control` и значением атрибута `value`, совпадающим с текущим
```suggestion
Теперь поменяем состояние радиокнопок переключателей в соответствии с тем, что записано в хранилище. Ищем кнопку с классом `snow-toggle__control` и значением атрибута `value`, совпадающим с текущим значением из хранилища, и задаём ей атрибут `checked` со значением `true`. Технически значение этому атрибуту не нужно, но в JS иначе не получится. Предварительно при помощи [`if`](/js/if-else/) проверим, что значение переменной `currentStorage` не [`undefined`](/js/undefined/):
```

2022-01-18 18:54 UTC, tachisis commented
Мне нравится, что получилось, и по форме, и по содержанию!

2022-01-19 20:58 UTC, nlopin commented
Мне нравится рецепт, очень классно получилось.

## Вопросики
Хочу обсудить две темы. Сначала их сформулирую, потом по каждой напишу своё мнение:
- нужно выработать критерии, какие рецепты мы хотим видеть и готовы принимать, а какие — нет. Чётко описать критерии, при попадании в которые можно писать рецепт
- определить структуру рецпета

## Про критерии

Я сформулировал несколько критериев, давайте обсуждать и дополнять их. 

Во-первых, рецепт должен решать проблему, которая возникает регулярно у многих.

Во-вторых, рецепт должен иметь сложность, чтобы его написать нужно провести исследование и выработать подход — «Как написать перебор массива десятью способами» для меня не рецепт.

В-третьих, рецепт можно скопировать и вставить в свой код и он заработает.

## Про структуру

Структура, как мне кажется, зависит от критериев, которые мы выберем. Если мы говорим, что рецепт можно скопировать и вставить, то это и должно быть на первом месте в совете — код и инструкция, как его использовать.

Дальше можно детально объяснить, почему этот рецепт именно такой — как мы пришли к нему.

В итоге получаем такую структуру: Вопрос/Проблема → Решение → Почему так

Давайте подискутируем

2022-01-27 06:58 UTC, solarrust commented on recipes/snow/index.md
> +```
Мы договорились использовать чистые технологии. Если что-то захочет, то может подогнать под свои технологии.

2022-01-27 07:22 UTC, furtivite commented on recipes/snow/index.md
> +```
> Мы договорились использовать чистые технологии. Если что-то захочет, то может подогнать под свои технологии.

Я имел в виду написать JS-цикл, он будет везде работать, кажется, это чистая технология, а nunjucks для примера привёл. Как думаешь? Если нет, то нет 🙂

2022-01-27 07:39 UTC, solarrust commented on recipes/snow/index.md
> +```
Зачем менять структуру страницы после её загрузки, когда можно отдать чистый HTML на изначальную отрисовку? Приведи свои доводы, пожалуйста.

2022-01-27 07:58 UTC, furtivite commented on recipes/snow/index.md
> +```
Просто сократить количество HTML-кода повторяемого. Кажется, читателю тут будет интересно, либо как это сделать, либо почему предлагается именно HTML, а не JS.

2022-01-30 11:43 UTC, nlopin commented on recipes/snow/index.md
> +<div class="snow">
нужно ли дать рекомендации, куда вставлять этот код? Судя по `z-index` его можно закинуть в `body` в конец страницы?

2022-01-30 12:11 UTC, nlopin requested changes
Заметил несколько неточностей, но в остальном всё классно 👍

2022-01-30 12:11 UTC, nlopin commented on recipes/snow/index.md
> +```
Согласен с Алёной — чем меньше добавленной сложности, тем легче

2022-01-30 12:11 UTC, nlopin commented on recipes/snow/index.md
> +  display: flex;
Потерялось свойство
```suggestion
  display: flex;
  justify-content: space-between;
```

2022-01-31 09:24 UTC, solarrust commented on recipes/snow/index.md
> +const snowToggle = document.querySelector('.snow-toggle')
Забыла про тогглы, добавила.

2022-01-31 09:24 UTC, solarrust commented on recipes/snow/index.md
> +  display: flex;
Спасибо за внимательность 🖤

2022-01-31 09:41 UTC, solarrust commented
@nlopin спасибо большое за твои комментарии. Добавила тогглы в верхний код, дописала потеряно свойство, добавила рекомендации по месту вставки кода. Поправила мелочи в тексте и разметку демок.

2022-01-31 10:53 UTC, nlopin commented
@solarrust я ещё подумал, что надо бы aria-hidden поставить диву, а то он наверное зачитается ридером

2022-02-11 15:55 UTC, solarrust commented
Этот пул-реквест закрываю в пользу #2752

2022-02-11 15:55 UTC, closed without merging