Update index.md
doka-guide/content pull request #2698
Opened 2022-01-26 06:50 UTC by Dubrovskiy40

2022-01-26 13:49 UTC, bespoyasov commented on js/fetch/index.md
> +Если ответом на запрос `fetch` была ошибка (например HTTP-код 400, 404 или 500), то `Promise` попадёт в состояние _rejected_. Promise выполнится с ошибкой только если запрос не случился из-за сбоя се
@nlopin, что-то я запутался, что тут изначально хотели сказать :–/

2022-01-26 13:56 UTC, Dubrovskiy40 commented on js/fetch/index.md
> +Если ответом на запрос `fetch` была ошибка (например HTTP-код 400, 404 или 500), то `Promise` попадёт в состояние _rejected_. Promise выполнится с ошибкой только если запрос не случился из-за сбоя се
Если ошибка. то она же попадает в reject...

2022-01-30 11:19 UTC, nlopin commented on js/fetch/index.md
> +Если ответом на запрос `fetch` была ошибка (например HTTP-код 400, 404 или 500), то `Promise` попадёт в состояние _rejected_. Promise выполнится с ошибкой только если запрос не случился из-за сбоя се
Мне кажется, что в изначальной версии всё верно. Мы хотим сказать, что код ошибки не учитывается при решении, как резолвить промис. Любой ответ от сервера ведёт к `resolve`. К `reject` приводят только случаи, когда мы вообще не получили ответа от сервера по причине отказа сети.

На англйиском вот так пишут:
> The promise does not reject on HTTP errors — it only rejects on network errors. You must use then handlers to check for HTTP errors.

2022-01-30 11:32 UTC, nlopin commented on js/fetch/index.md
> +Если ответом на запрос `fetch` была ошибка (например HTTP-код 400, 404 или 500), то `Promise` попадёт в состояние _rejected_. Promise выполнится с ошибкой только если запрос не случился из-за сбоя се
Вот [пример](https://codesandbox.io/s/promise-resolves-on-any-status-code-l8def), где эндпоинт возвращает 404, но промис резолвится

2022-01-30 11:33 UTC, nlopin commented on js/fetch/index.md
> +Если ответом на запрос `fetch` была ошибка (например HTTP-код 400, 404 или 500), то `Promise` попадёт в состояние _rejected_. Promise выполнится с ошибкой только если запрос не случился из-за сбоя се
@Dubrovskiy40 сможешь переформулировать абзац так, чтобы это было чётче с твоей точки зрения? Сейчас мы сформулировали плохо

2022-01-30 11:35 UTC, nlopin requested changes
Исправление неверное, но предлагаю в рамках этого PR улучшить абзац так, чтобы он читался максимально ясно

2022-09-09 17:43 UTC, nlopin commented on js/fetch/index.md
> +Если ответом на запрос `fetch` была ошибка (например HTTP-код 400, 404 или 500), то `Promise` попадёт в состояние _rejected_. Promise выполнится с ошибкой только если запрос не случился из-за сбоя се
```suggestion
Любой ответ на запрос через `fetch()` (например HTTP-код 400, 404 или 500) резолвит `Promise` в состояние _fulfilled_. Промис зарезолвится в состояние _rejected_ только если запрос не случился из-за сбоя сети или что-то помешало выполнению `fetch()`.
```

2022-09-09 17:43 UTC, nlopin approved these changes

2022-09-09 17:46 UTC, nlopin commented on js/fetch/index.md
> +Любой ответ на запрос через `fetch()` (например HTTP-код 400, 404 или 500) резолвит `Promise` в состояние _fulfilled_. Промис зарезолвится в состояние _rejected_ только если запрос не случился из-за
```suggestion
Любой ответ на запрос через `fetch()` (например HTTP-код 400, 404 или 500) переводит `Promise` в состояние _fulfilled_. Промис перейдёт в состояние _rejected_ только если запрос не случился из-за сбоя сети или что-то помешало выполнению `fetch()`.
```

2022-09-09 18:09 UTC, merged