Добавляет документацию про советы
doka-guide/content pull request #2707
Opened 2022-02-01 12:05 UTC by tachisis

2022-02-01 12:19 UTC, furtivite commented on docs/practice.md
> +💡 Если ваш совет очень маленький, скорее подсказка, то для этого у нас есть блок «Подсказки» в теле статьи. Добавьте подсказку туда, а свой ник на «Гитхабе» — в контрибьюторы в шапке.
Вот тут у меня возник бы вопрос: «Если мы добавляем „Подсказку“ или просто дополняем материал, то надо завести себя в контрибьюторы. А надо ли добавлять себя в контрибьюторы, если дал совет из практики?». 

Я понимаю, что не надо, но кажется, про это можно написать, чтобы не было двойного толкования, а у нас была ссылка на документацию, когда человека из контрибьюторов удаляют.

2022-02-01 12:23 UTC, tachisis commented on docs/practice.md
> +💡 Если ваш совет очень маленький, скорее подсказка, то для этого у нас есть блок «Подсказки» в теле статьи. Добавьте подсказку туда, а свой ник на «Гитхабе» — в контрибьюторы в шапке.
Мне кажется, это переусложнение документации. «На случай, если тебе вдруг взбредет в голову странное, не делай этого» — но это редкий случай. Думаю, большинство людей способны прочитать документацию и сделать ровно то, что там сказано: завести файл с советом и файл в папке people.

2022-02-01 15:56 UTC, solarrust reviewed
В целом — совершенно огненно! 
Оставила буквально парочку комментов.

2022-02-01 15:56 UTC, solarrust commented on docs/practice.md
> +В конце каждого нашего материала есть раздел «На практике». Здесь авторы и контрибьюторы могут поделиться своим личным опытом по теме. Ведь теория — это хорошо, но что такое теория без практики? Авто
Не каждого, к сожалению =(

2022-02-01 15:56 UTC, solarrust commented on docs/practice.md
> +💡 Если ваш совет очень маленький, скорее подсказка, то для этого у нас есть блок «Подсказки» в теле статьи. Добавьте подсказку туда, а свой ник на Гитхабе — в контрибьюторы в шапке.
Не факт, что подсказка будет на столько ценная и полезная, что заслужит упоминания в контрибьюторах статьи. Это каждый раз индивидуально решается

2022-02-01 16:20 UTC, bespoyasov reviewed
👍

2022-02-01 19:16 UTC, tachisis commented on docs/practice.md
> +В конце каждого нашего материала есть раздел «На практике». Здесь авторы и контрибьюторы могут поделиться своим личным опытом по теме. Ведь теория — это хорошо, но что такое теория без практики? Авто
Я убрала слово «каждый», но в этом случае лучше поступиться стопроцентным соответствием истине ради ясного смысла.

2022-02-01 19:17 UTC, tachisis commented on docs/practice.md
> +💡 Если ваш совет очень маленький, скорее подсказка, то для этого у нас есть блок «Подсказки» в теле статьи. Добавьте подсказку туда, а свой ник на Гитхабе — в контрибьюторы в шапке.
Убрала все предложения добавить себя в контрибьюторы, в конце концов, фокус этих абзацев не в том, чтобы дать инструкцию, что делать, а в том, чтобы разделить виды контента.

2022-02-04 11:00 UTC, solarrust approved these changes

2022-02-07 09:08 UTC, solarrust approved these changes

2022-02-07 09:22 UTC, igsekor requested changes
Очень классно получилось! 👍

2022-02-07 09:22 UTC, igsekor commented on docs/practice.md
> +Главный фокус этого раздела — ваш личный опыт разработчика. Применяли описанное статье каким-то интересным образом? Знаете хороший трюк? У вас есть мнение о плюсах и минусах явления? Ура, этим стоит
```suggestion
Главный фокус этого раздела — ваш личный опыт разработчика. Применяли описанное в статье каким-то интересным образом? Знаете хороший трюк? У вас есть мнение о плюсах и минусах явления? Ура, этим стоит поделиться!
```

2022-02-07 09:22 UTC, igsekor commented on docs/practice.md
> +Если вы впервые контрибьютите в Доку, создайте ещё собственную директорию в папке _people_ репозитория _content_ и расскажите о себе [по примеру в документации](people.md). Это нужно, чтобы к вашему
```suggestion
Если вы впервые контрибьютите в Доку, создайте ещё собственную директорию в папке _people_ репозитория _content_ и расскажите о себе [по примеру в документации](people.md). Это нужно, чтобы к вашему совету сгенерировался корректный заголовок с вашим именем.
```

Может так точнее? 😇 А может и нет 🙃

2022-02-07 12:57 UTC, tachisis commented on docs/practice.md
> +Если вы впервые контрибьютите в Доку, создайте ещё собственную директорию в папке _people_ репозитория _content_ и расскажите о себе [по примеру в документации](people.md). Это нужно, чтобы к вашему
Спасибо!

2022-02-07 13:14 UTC, nlopin approved these changes

2022-02-07 15:18 UTC, igsekor approved these changes

2022-02-07 15:20 UTC, merged