Добавляет доку про where
doka-guide/content pull request #2715
Opened 2022-02-02 17:44 UTC by kotosha-real

Fix #486

2022-02-04 10:59 UTC, solarrust reviewed
Очень классная получилась статья. Спасибо большое!
Оставила несколько предложений по упрощению формулировок. Глянь, пожалуйста. 
Может быть добавим ещё одну-две демки для наглядности?

2022-02-04 10:59 UTC, solarrust commented on people/kotosha-real/index.md
> +name: 'kotosha-real'
Не хочешь добавить тут имя-фамилию? Не настаиваю, как тебе комфортнее )

2022-02-04 10:59 UTC, solarrust commented on css/where/index.md
> +В то время как подобная запись не возымеет успеха, потому что неподдерживаемое свойство `:some-unsupported-feature` приведёт к игнорированию всех селекторов в перечислении:
Кажется, можно попроще написать:

```suggestion
Если указать неподдерживаемое свойство `:some-unsupported-feature` в перечислении, то всё сломается, не сработает ни один из селекторов:
```

Как думаешь, так ок?

2022-02-04 10:59 UTC, solarrust commented on css/where/index.md
> +💡 Псевдоклассы `:where()` и `:is()` относится к [«прощающему списку селекторов»](https://drafts.csswg.org/selectors-4/#typedef-forgiving-selector-list). Это значит, что невалидный селектор в списке п
```suggestion
💡 Псевдоклассы `:where()` и `:is()` относится к [«прощающему списку селекторов»](https://drafts.csswg.org/selectors-4/#typedef-forgiving-selector-list). Невалидный селектор в списке аргументов _не приведёт_ к игнорированию валидных селекторов.
```

2022-02-04 10:59 UTC, solarrust commented on css/where/index.md
> +Рассмотрим пример. Стили ниже применятся к [`<span>`](/html/span/):
```suggestion
Стили ниже применятся к [`<span>`](/html/span/), а нерабочий селектор `:some-unsupported-feature` будет проигнорирован:
```

2022-02-04 10:59 UTC, solarrust commented on css/where/index.md
> +Без использования `:where()` пришлось бы прибегнуть к [перечислению селекторов](/css/selector-list/):
```suggestion
Без использования `:where()` пришлось бы [перечислять селекторы](/css/selector-list/):
```

2022-02-05 07:51 UTC, kotosha-real commented
Cпасибо большое за комменты!
Сегодня поправлю формулировки и накидаю демки

2022-02-05 08:00 UTC, kotosha-real commented on css/where/index.md
> +В то время как подобная запись не возымеет успеха, потому что неподдерживаемое свойство `:some-unsupported-feature` приведёт к игнорированию всех селекторов в перечислении:
Да, написал так: «А вот если указать неподдерживаемое свойство `:some-unsupported-feature` в перечислении, то всё сломается, не сработает ни один из селекторов:». Не хочется терять акцент на том, что предыдущие два примера работают, а _вот этот_ разваливается

2022-02-05 08:07 UTC, kotosha-real commented on people/kotosha-real/index.md
> +name: 'kotosha-real'
И правда, не подумал об этом сразу, спасибо)

2022-02-07 10:57 UTC, solarrust commented
@kotosha-real внесла небольшие оформительские правки. Посчитала, что то, что было в подсказках достойно отдельных подразделов. 
Позову @skorobaeus на помощь, чтобы _причесать_ твои бомбические демки!

2022-02-07 15:47 UTC, kotosha-real commented
@solarrust спасибо за тёплые слова)
Использвал блок подсказок, потому что хотел сделать максимально похоже на разделы существующих статей, буду знать, что можно дать себе немного воли в этом вопросе. А дескрипшен выглядит отлично)

2022-02-08 10:42 UTC, skorobaeus requested changes
Привет! Демки безумно крутые! Классика про стрелу в колене угодила мне в самое сердечко :)

Предлагаю немного поменять структуру демок, чтобы они говорили сами за себя. Сделать такую: Текст — Код (центр внимания) — Кнопка.

Basic:
![image](https://user-images.githubusercontent.com/29401439/152969594-34ed8670-28b9-4124-ae6d-f1f0af64eea3.png)

Я поменяла хэдер и футер на заголовок и список, потому что заголовок и список очевидно отличаются внешне, и нам не требуется пояснять, где что находится. 

Комментарий "Спасибо :where() за нулевую специфичность и возможность легко перебить получившийся с его помощью селектор." было бы здорово перефразировать и вынести в текст статьи.

Specificity-battle:
![image](https://user-images.githubusercontent.com/29401439/152970410-47773c9c-dfff-432d-9514-867131da2644.png)

Та же структура и та же логика, но здесь я добавила HTML-код тоже, чтобы было видно, что он не меняется.

Текст про котов, конечно, можно сменить на любой другой :D

2022-02-08 18:08 UTC, kotosha-real commented
@skorobaeus спасибо большое)
Подтащу демки с твоими предложениями отдельным коммитом завтра. По цветам всё ок, оставить так?
Ещё есть вопрос — как Дока выбирает тему (светлая-тёмная)? Мб как-то можно прорастить это в айфрейм, что белый фон не резал глаза на тёмной теме?

2022-02-09 11:15 UTC, skorobaeus commented
> @skorobaeus спасибо большое) Подтащу демки с твоими предложениями отдельным коммитом завтра. По цветам всё ок, оставить так? Ещё есть вопрос — как Дока выбирает тему (светлая-тёмная)? Мб как-то можно прорастить это в айфрейм, что белый фон не резал глаза на тёмной теме?

Да, цвета пусть остаются. Т.к. гайд по стилям для демок пока не готов, я просто не могу просить соблюдать то, чего нет.

Дока не выбирает тему, финальные версии демок и иллюстраций выполняются в тёмной теме. Так они не режут глаза ночью и выделяются в тексте статьи днём :)

2022-02-13 19:08 UTC, kotosha-real commented
@skorobaeus текст про котов оставил твой)
Ещё раз спасибо за советы по демкам, залил правки

2022-02-14 11:44 UTC, solarrust approved these changes
Спасибо! Получилось классно 🔥

Проигнорировала тыгыдык, на котором ломалась проверка орфографии и докинула микро-правки.

Пиши ещё! У тебя хорошо получается 🙌

2022-02-14 11:45 UTC, merged