Добавил статью про генераторы
doka-guide/content pull request #2719
Opened 2022-02-03 11:10 UTC by Windrushfarer

Fixes #2370 
На меня снизошло вдохновение и идея статьи, когда я увидел ишью про генераторы :)

2022-02-04 12:16 UTC, bespoyasov reviewed
Огонь статья!

Возможно, стоит ещё рассказать о том, как себя ведёт `throw` внутри генератора и что `yield` должен быть непосредственно внутри функции-генератора (не в колбеке, например).

Я там ещё оставил несколько комментариев, но кажется для вводной статьи этого вполне достаточно.

2022-02-04 12:16 UTC, bespoyasov commented on js/generators/index.md
> +const set = new Set(nums()) // Set { 1, 2 }
```suggestion
const set = new Set(nums()) // Set { 1, 2, 3 }
```

2022-02-04 12:16 UTC, bespoyasov commented on js/generators/index.md
> +У объект-генератор помимо метода `.next()` есть методы `.return()` и `.throw()`, которые позволяют завершить генератор после вызова.
```suggestion
У объекта-генератора помимо метода `.next()` есть методы `.return()` и `.throw()`, которые позволяют завершить генератор после вызова.
```

2022-02-04 12:16 UTC, bespoyasov commented on js/generators/index.md
> +Если по аналогии с генератором добавить звездочку `*` к вызову оператора `yield`, то так можно перенаправлять выполнение в другой генератор.
```suggestion
Если к вызову оператора `yield` добавить звездочку `*`, то можно перенаправить выполнение в другой генератор.
```

2022-02-04 12:16 UTC, bespoyasov commented on js/generators/index.md
> +Чтобы создать функцию-генератор нужно добавить знак звёздочки между ключевым словом `function` и названием функции. При этом возможны любые варианты постановки и где поставить звёздочку лишь дело вку
```suggestion
Чтобы создать функцию-генераторб нужно добавить знак звёздочки между ключевым словом `function` и названием функции. При этом возможны любые варианты постановкиб и где поставить звёздочку — дело вкуса.
```

2022-02-04 12:16 UTC, bespoyasov commented on js/generators/index.md
> +Чтобы вернуть значение используется оператор `yield`.
```suggestion
Чтобы вернуть значение, используется оператор `yield`.
```

2022-02-04 12:20 UTC, bespoyasov commented on js/generators/index.md
> +☝️ Не забывайте, что вызов `.next()` выполняет содержимое функции **до** следующего `yield`. Потому мы не можем передать значение в `isFavorite` в первом вызове `.next()`. Это как заранее сказать, чт
Тут, вероятно, стоит точнее выразить мысль об асимметричности метода `next()`. Может быть, даже стоит нарисовать схему того, в какой `yield` от передаёт значение «извне» и из какого `yield ` возвращает новое 🤔

2022-02-04 12:20 UTC, bespoyasov commented on js/generators/index.md
> +generator.throw(new Error("Too many OOP. Brain is melted")) // Error: Too many OOP. Brain is melted
```suggestion
generator.throw(new Error("Too much OOP. Brain is melted")) // Error: Too much OOP. Brain is melted
```

2022-02-15 09:16 UTC, Windrushfarer commented on js/generators/index.md
> +Генератор – это специальная функция, которая возвращает [объект-генератор](/js/iterator/). Объект-генератор это расширенная версия объекта-итератора. Можно сказать, что генератор – это функция, котор
Я не очень понимаю как тут что вывернуть, потому что в "Кратко" в моем представлении должно лежать выжатое описание из подробных частей ниже. Т.е это не статья, которую надо читать последовательно чтобы понять, в доке мы же хотим дать представление сразу.

2022-02-15 16:27 UTC, Windrushfarer commented on js/generators/index.md
> +☝️ Не забывайте, что вызов `.next()` выполняет содержимое функции **до** следующего `yield`. Потому мы не можем передать значение в `isFavorite` в первом вызове `.next()`. Это как заранее сказать, чт
Попробовал еще подробнее раскрыть :)

2022-02-16 08:13 UTC, bespoyasov approved these changes

2022-02-16 08:13 UTC, bespoyasov commented on js/generators/index.md
> +Сначала может показаться нелогичным, что при первом вызову `.next()` значение аргумента не запишется. Однако это является особенностью генераторов, из-за того что генераторы ленивые первый вызов `.ne
```suggestion
Сначала может показаться нелогичным, что при первом вызове `.next()` значение аргумента не запишется. Однако это является особенностью генераторов, из-за того что генераторы ленивые первый вызов `.next()` можно считать инициализацией. 

Если представить генератор как закрытую коробку, то первый вызов `.next()` – это как вытянуть первый предмет вслепую. Вам неизвестно заранее, что вы получите, потому нельзя заранее сказать, что предмет нам понравится. Аналогично и в примере выше, сначала мы хотим получить результат, а затем на его основе можем решить какой аргумент передать в следующий вызов `.next().
```

2022-02-16 08:13 UTC, bespoyasov commented on js/generators/index.md
> +Чтобы создать функцию-генераторб нужно добавить знак звёздочки между ключевым словом `function` и названием функции. При этом возможны любые варианты постановкиб и где поставить звёздочку — дело вкус
```suggestion
Чтобы создать функцию-генератор, нужно добавить знак звёздочки между ключевым словом `function` и названием функции. При этом возможны любые варианты постановки, и где поставить звёздочку — дело вкуса.
```

2022-02-16 08:13 UTC, bespoyasov commented on js/generators/index.md
> +При наличии `return` в поле `value` будет находится указанное значение.
```suggestion
При наличии `return` в поле `value` будет находиться указанное значение.
```

2022-02-16 08:17 UTC, bespoyasov reviewed
Поправил орфографию и «ё».

2022-02-16 08:17 UTC, bespoyasov commented on js/generators/index.md
> +Чтобы объявить фукнцию-генератор к названию функции в начале добавляют символ звездочки `*`.
```suggestion
Чтобы объявить функцию-генератор к названию функции в начале добавляют символ звёздочки `*`.
```

2022-02-16 08:17 UTC, bespoyasov commented on js/generators/index.md
> +Функция-генератор во время вызова не вернёт значение сразу, а вместо этого вернёт специальный объект-генератор. Из этого объекта мы можем получить ожидаемый результат, вызывая метод `next()`. При это
```suggestion
Функция-генератор во время вызова не вернёт значение сразу, а вместо этого вернёт специальный объект-генератор. Из этого объекта мы можем получить ожидаемый результат, вызывая метод `next()`. При этом выполнение функции в буквальном смысле остановится.
```

2022-02-16 08:17 UTC, bespoyasov commented on js/generators/index.md
> +Генераторы по умолчанию ленивые, и до тех пор пока не будет вызван метод `.next()`, у возвращаемого объекта-генератора никакие вычисления не будут происходить. Но даже после вызова `.next()` выполнен
```suggestion
Генераторы по умолчанию ленивые, и до тех пор пока не будет вызван метод `.next()`, у возвращаемого объекта-генератора никакие вычисления не будут происходить. Но даже после вызова `.next()` выполнение функции произойдёт только до первого вызова `yield`. Если вызвать `.next()` ещё раз, то выполнение продолжится до следующего `yield` и так далее. Продолжим пример выше.
```

2022-02-16 08:17 UTC, bespoyasov commented on js/generators/index.md
> +Немного изменими пример с языками выше и добавим условие, что если первый язык программирования нам понравился, то мы учим другой похожий язык вместо JavaScript.
```suggestion
Немного изменим пример с языками выше и добавим условие, что если первый язык программирования нам понравился, то мы учим другой похожий язык вместо JavaScript.
```

2022-02-16 08:17 UTC, bespoyasov commented on js/generators/index.md
> +Используя возможность передачи данных в генератор можно по ходу его выполнения менять возвращаемые значения и создавать очень гибкие конструкии.
```suggestion
Используя возможность передачи данных в генератор можно по ходу его выполнения менять возвращаемые значения и создавать очень гибкие конструкции.
```

2022-02-16 08:17 UTC, bespoyasov commented on js/generators/index.md
> +Генераторы возвращают объект-генератор, который являвется просто расширенной версией объекта-итератора, потому результат вызова можно использовать для создания коллекций, например `Array` или `Set`.
```suggestion
Генераторы возвращают объект-генератор, который является просто расширенной версией объекта-итератора, потому результат вызова можно использовать для создания коллекций, например `Array` или `Set`.
```

2022-02-16 08:17 UTC, bespoyasov commented on js/generators/index.md
> +description: "Генератор – это специальная функция, которая может приостанавливать свое выполнение и возвращает в результате объект-итератор"
```suggestion
description: "Генератор – это специальная функция, которая может приостанавливать своё выполнение и возвращает в результате объект-итератор"
```

2022-02-16 08:17 UTC, bespoyasov commented on js/generators/index.md
> +Генератор – это специальная функция, которая возвращает [объект-генератор](/js/iterator/). Объект-генератор это расширенная версия объекта-итератора. Можно сказать, что генератор – это функция, котор
```suggestion
Генератор – это специальная функция, которая возвращает [объект-генератор](/js/iterator/). Объект-генератор это расширенная версия объекта-итератора. Можно сказать, что генератор – это функция, которая создаёт итератор.
```

2022-02-16 20:45 UTC, nlopin commented on js/generators/index.md
> +  - Генератор
В ключевиках нужно указывать только слова, которых нет в тексте или заголовках
```suggestion
```

2022-02-16 20:55 UTC, nlopin commented on js/generators/index.md
> +Генератор – это специальная функция, которая возвращает [объект-генератор](/js/iterator/). Объект-генератор это расширенная версия объекта-итератора. Можно сказать, что генератор – это функция, котор
В кратко должна содержаться сжатая ментальная модель концепции.  Мне кажется важно сказать обе вещи — и понятную, и точную. Может так?

```suggestion
Генератор — это специальная функция, которая возвращает [объект-генератор](/js/iterator/). Объект-генератор это расширенная версия объекта-итератора для обхода или получения значений.

По сути, функция-генератор — это фабрика по производству особого вида итераторов. Логика работы этих итераторов и содержится в функции-генераторе. С помощью ключевого слова `yield` генератор может возвращать промежуточные значения.
```

2022-02-16 20:57 UTC, nlopin commented on js/generators/index.md
> +Чтобы вернуть значение, внутри генератора используется оператор `yield`. Вызов `return` завершит перебор объекта-итератора.
я бы тут обязательно говорил про «промежуточные значения», хотя это и не совсем верно. Так можно хоть как-то уложить в голову разницу между `yield` и `return`. Что думаете?

2022-02-16 20:58 UTC, nlopin commented on js/generators/index.md
> +Далее вызываем метод `.next()`, чтобы получить по одному получить значения.
```suggestion
Далее вызываем метод `.next()`, чтобы получать значения по одному:
```

2022-02-16 20:58 UTC, nlopin commented on js/generators/index.md
> +Если нужно получать значений в цикле, то можно подставить результат вызова функции-генератора в `for..of`.
```suggestion
Если нужно получать значения в цикле, то можно подставить результат вызова функции-генератора в `for..of`:
```

2022-02-16 20:59 UTC, nlopin commented on js/generators/index.md
> +const fullName = createFullName("Анна", "Каренина")
```suggestion
const fullName = createFullName("Анна", "Каренина")
console.log(fullName)
// Анна Каренина
```

2022-02-16 21:01 UTC, nlopin commented on js/generators/index.md
> +В самом начале генератор находится в состоянии `suspended`, т.е он приостановлен. Дальнейшие вызовы `.next()` тоже будут переводить генератор в то же состояние пока генератор не вернул все значения (
```suggestion
В самом начале генератор находится в состоянии `suspended`, т.е он приостановлен. Дальнейшие вызовы `.next()` тоже будут переводить генератор в это состояние до тех пор, пока генератор не вернёт все значения (пройдёт все вызовы `yield`). Генератор закроется, только когда вызов метода `.next()` вернет объект с полем `done: true`.
```

2022-02-16 21:04 UTC, nlopin commented on js/generators/index.md
> +## Как пишется
По текущим договоренностям, раздел «Как пишется» должен быть между разделами «Пример» и «Как понять». Подними его, пожалуйста

2022-02-16 21:05 UTC, nlopin commented on js/generators/index.md
> +У объекта-генератора помимо метода `.next()` есть методы `.return()` и `.throw()`, которые позволяют завершить генератор после вызова.
```suggestion
Помимо метода `next()`, у объекта-генератора есть методы `.return()` и `.throw()`, которые позволяют завершить генератор после вызова.
```

2022-02-16 21:06 UTC, nlopin commented on js/generators/practice/windrusfarer.md
> +🛠 Можно использовать в качестве последовательных ленивых вычислений
```suggestion
🛠 Можно использовать генератор для последовательных ленивых вычислений
```

2022-02-16 21:18 UTC, nlopin requested changes
* нужно дополнировать раздел «Кратко»
* у меня ощущение, что мы очень официально подходим к объяснению, особенно в разделе «как понять». Давай придумаем запоминающуюся аналогию. У меня в голову приходит только видеомагнитофон с паузой, но это для стариков

2022-02-18 13:43 UTC, Windrushfarer commented
> * нужно дополнировать раздел «Кратко»
> * у меня ощущение, что мы очень официально подходим к объяснению, особенно в разделе «как понять». Давай придумаем запоминающуюся аналогию. У меня в голову приходит только видеомагнитофон с паузой, но это для стариков

Я бы мог попробовать сравнить с трубопроводом. Можно ставить заслонки (`yield`), который открываются когда мы поворачиваем кран. Что-то такое.

2022-02-22 20:18 UTC, nlopin commented
про трубопровод не очень секси звучит, конечно

2022-02-23 13:42 UTC, Windrushfarer commented
Можно попробовать реальный бытовой генератор (дает ток `yield`) и т.д. У меня в голове все аналогии очень похоже на принцип действия, но кажется что не сильно дают понять суть 🤷‍♂️

2022-02-23 13:56 UTC, nlopin commented
давай пока забьем на аналогию

2022-10-25 20:07 UTC, HellSquirrel commented
@Windrushfarer привет! Утаскиваю у @nlopin этот PR. Ты планируешь тут какую-то дальнейшую работу или лучше мне перехватить?

2023-08-09 18:38 UTC, SergeyKrasnolobov commented
А какой статус по статье?) что еще нужно доделать ?

2023-08-10 07:33 UTC, HellSquirrel commented
@SergeyKrasnolobov привет. Сейчас разделом занимаюсь я. Я в течении пары дней посмотрю что есть в статье и напишу тебе что именно нужно сделать, если хочешь этим заняться

2023-08-10 08:11 UTC, SergeyKrasnolobov commented
@HellSquirrel привет. Да, давай попробую добить то что уже есть. Я же правильно понимаю что, то что уже написано рабочий вариант статьи?

2023-08-13 11:08 UTC, SergeyKrasnolobov commented
@HellSquirrel Привет! Что насчет статьи, удалось посмотреть чего не достает?)

2023-08-18 16:25 UTC, HellSquirrel commented
@SergeyKrasnolobov Приветик. Прости за долгое ожидание. Тут нужно 
1. Пересмотреть пример, убедиться что он все еще работает
2. Попробовать упростить раздел "кратко" переформулировать его простыми словами
3. *опционально* Добавить немножко инфы про внутреннюю структуру объекта генератора
4. Подробнее расписать про разницу между генераторами и итераторами
5. Сделать факт чек утверждения про состояние генераторов

2023-08-18 16:34 UTC, SergeyKrasnolobov commented
@HellSquirrel Принято!)

2023-09-05 23:48 UTC, HellSquirrel commented
продолжение вот тут https://github.com/doka-guide/content/pull/4682

2023-09-05 23:48 UTC, closed without merging