Исправление комментария под условие ветвления
doka-guide/content pull request #2772
Opened 2022-02-16 04:26 UTC by haritonov-roman

2022-02-16 08:19 UTC, bespoyasov approved these changes
Спасибо!

2022-02-16 08:24 UTC, bespoyasov requested changes
Упс, кажется, изменилось имя файла, и линтеру это не нравится. Предлагаю откатить, как было.

2022-02-18 04:23 UTC, nlopin approved these changes
Спасибо!

Откати только имя файла, пожалуйста

2022-02-22 20:39 UTC, merged

2022-02-22 20:39 UTC, nlopin commented
@bespoyasov не стал тебя дожидаться, минорная правка