Добавляет доку для тега samp
doka-guide/content pull request #2784
Opened 2022-02-17 17:05 UTC by webdb81

Fix #2776

2022-02-18 17:26 UTC, solarrust reviewed
Привет!

Спасибо огромное за чудесную доку 🖤
Оставила несколько предложений по улучшению. Кажется, что задача вёрстки имитации терминала встречается не часто. Подумай, пожалуйста, над последним примером.

2022-02-18 17:26 UTC, solarrust commented on html/samp/index.md
> +  - оформление данных
```suggestion
```

Все ключевые слова встречаются в статье. Можно их дополнительно не указывать. Если вдруг будут идеи, по каким словосочетаниям или словам могут искать эту доку, но их нет в статье — можно будет добавить сюда.

2022-02-18 17:26 UTC, solarrust commented on html/samp/index.md
> +</div>
```suggestion
<p>
  После завершения всех активных сеансов на экране появится сообщение:
  <samp>Теперь питание компьютера можно отключить.</samp>
</p>
```

2022-02-18 17:26 UTC, solarrust commented on html/samp/demos/basic/index.html
> +    <samp>Теперь питание компьютера можно отключить.</samp>
```suggestion
    <p>
      После завершения всех активных сеансов на экране появится сообщение:
      <samp>Теперь питание компьютера можно отключить.</samp>
    </p>
```

2022-02-18 17:26 UTC, solarrust commented on html/samp/index.md
> +</div>
```suggestion
<div>
  <p>
    В ходе выполнения программы вам будет предложено указать расстояние:
    <samp>Введите значение для переменной <var>Distance</var>:</samp>
  </p>
</div>

<div>
  <p>Неправильно введённая команда не будет выполнена и в консоли отобразится ошибка:</p>
  <samp>
    <span class="console-name">user@machine:~$</span> <kbd>ckear</kbd>
    <br>
    ckear: The term 'ckear' is not recognized as a name of a cmdlet, function, script file, or executable program.
    <br>
    <span class="console-name">user@machine:~$</span> <span class="console-cursor">█</span>
  </samp>
</div>
```

2022-02-18 17:26 UTC, solarrust commented on html/samp/demos/complex/index.html
> +  <title>Совместное использование — <samp> — Дока</title>
```suggestion
  <title>Пример использования с <var> и <kbd> — <samp> — Дока</title>
```

2022-02-18 17:54 UTC, webdb81 commented on html/samp/index.md
> +</div>
В верхней части предлагаю оставить разделение `<p>` и `<samp>`. Идёт как бы общение с читателем документации по работе с программой: смотри, в такой-то ситуации ты увидишь это.
При объединении текст отображается одной строкой.
![screen-samp_with_text](https://user-images.githubusercontent.com/58950679/154735774-2783d511-9cd5-4190-a0ee-140760b0559c.png)

2022-02-22 08:09 UTC, solarrust reviewed
Класс, спасибо за правки!

Ещё было бы хорошо добавить блок про отличие от тега `<output>` ведь он тоже нужен для вывода _ответа_ компьютера =)
Что думаешь?

2022-02-22 08:09 UTC, solarrust commented on html/samp/index.md
> +## Как пишется
```suggestion
## Пример
```

2022-02-22 08:09 UTC, solarrust commented on html/samp/index.md
> +## Пример
```suggestion
## Комбинация с `<var>` и `<kbd>`
```

2022-02-22 08:09 UTC, solarrust commented on html/samp/demos/complex/index.html
> +      <span class="console-name">user@machine:~$</span> <span class="console-cursor">█</span>
Ровно такой же курсор нарисован в примере на MDN =)
Давай лучше ориентироваться на пример в спецификации, если он покажется удачным. А лучше придумать полностью свой.

2022-02-22 09:15 UTC, webdb81 commented on html/samp/demos/complex/index.html
> +      <span class="console-name">user@machine:~$</span> <span class="console-cursor">█</span>
По примеру из спецификации смотрится хорошо - сделаю так.

2022-02-22 09:35 UTC, webdb81 commented
> Ещё было бы хорошо добавить блок про отличие от тега `<output>`

Может тогда небольшим предложением - по примеру спецификации.
Каким элементом статьи лучше оформить: простым предложением или подразделом с названием?

2022-02-23 06:46 UTC, solarrust commented
Я бы провела чуть более глубокое исследование разницы смыслов этих двух тегов. Например, `<samp>` видится технологиями спец.возможностей как просто текст, без каких-то доп.смыслов. А вот `<output>` имеет смысловую нагрузку «Статус».
![CleanShot 2022-02-23 at 09 45 02](https://user-images.githubusercontent.com/13676514/155272562-34db5a76-dc3d-483b-92b6-d0a3f8b28211.png)
Было бы круто описать все найденые различия и дать пример, когда вместо использовать один, а когда лучше второй.

2022-02-23 10:50 UTC, webdb81 commented
В кратком описании `<samp>` я бы добавил, что эти данные показываются/распознаются программами как простой текст.

Предлагаю для упоминания `<output>` такой вариант:

Если надо сразу ("на ходу") показать пользователю **результат** выполнения программы, используется тег [`<output>`](/html/output/), например:
- информация, которую пользователь вводит или изменяет в форме;
- вывод расчётов по данным, которые указал пользователь (калькулятор, гороскоп и т. п.).

> Было бы круто описать все найденые различия и дать пример, когда вместо использовать один, а когда лучше второй.

Дока всё-таки про `<samp>` и не совсем правильно перегружать её информацией о других тегах. Если ставить задачу объяснить элементы, которые выполняют похожие функции, но отличаются по сути - для этого лучше подойдёт отдельная статья. В такой статье можно будет подробно рассказать про отличия подобных элементов, рецепты использования, доступность, схемы взаимодействия с другими элементами и т. д.

2022-03-01 09:37 UTC, solarrust commented
Да, согласна с твоим предыдущим комментарием. Давай дадим краткое упоминание про `<output>`

2022-03-10 14:12 UTC, pepelsbey requested changes
Предложил поправить некоторые формулировки. А ещё в спеке есть хороший пример:

```
<pre>
<code class="language-javascript">console.log(2.3 + 2.4)</code>
<samp>4.699999999999999</samp>
</pre>
```

Думаю, можно его добавить, получится хорошая и релевантная иллюстрация.

2022-03-10 14:12 UTC, pepelsbey commented on html/samp/index.md
> +Внутри тега `<samp>` размещается информация, которую пользователь может получить в процессе взаимодействия с программным обеспечением:
```suggestion
Внутри тега `<samp>` размещается информация, которую пользователь может получить в процессе взаимодействия с программой:
```

2022-03-10 14:12 UTC, pepelsbey commented on html/samp/index.md
> +💡 Если надо сразу ("на ходу") показать пользователю **результат** работы программы, используется тег [`<output>`](/html/output/), например:
```suggestion
💡 Если нужно показать пользователю **результат** работы программы в реальном времени, лучше использовать тег [`<output>`](/html/output/), например:
```

2022-03-10 14:12 UTC, pepelsbey commented on html/samp/index.md
> +При оформлении выходных данных `<samp>` часто комбинируют с тегами [`<var>`](/html/var/) и [`<kbd>`](/html/kbd/):
```suggestion
При оформлении вывода данных `<samp>` часто комбинируют с тегами [`<var>`](/html/var/) и [`<kbd>`](/html/kbd/):
```

2022-03-10 14:12 UTC, pepelsbey commented on html/samp/index.md
> +Тег `<samp>` используется для оформления выходных данных, которые показываются пользователю в результате выполнения программы. Содержимое этого элемента воспринимается устройствами как простой текст.
```suggestion
Тег `<samp>` используется для оформления вывода данных, которые показываются пользователю в результате выполнения программы. Содержимое этого элемента воспринимается устройствами как простой текст.
```

2022-03-15 07:50 UTC, solarrust approved these changes
Мне всё нравится =)

2022-03-17 22:02 UTC, pepelsbey approved these changes

2022-03-17 22:02 UTC, merged

2022-03-17 22:02 UTC, pepelsbey commented
Спасибо!