Добавляет совет в статью visibility
doka-guide/content pull request #2785
Opened 2022-02-17 19:29 UTC by Semigradsky

2022-02-19 11:36 UTC, pepelsbey requested changes
Спасибо за совет! Я бы только лучше описал суть явления и ещё можно пример сделать менее абстрактным, чтобы было понятна его польза. Придумать какой-нибудь компонент из родителя и двух вложенных частей.

2022-02-19 11:36 UTC, pepelsbey commented on css/visibility/practice/semigradsky.md
> +🛠 Важной особенностью свойства является то, что элемент со значением `visible` будет виден даже внутри контейнера со значением `hidden`. Это можно использовать для кастомизации разметки, сгенерирован
```suggestion
🛠 Важная особенность свойства, что оно, в отличие от `display: none` или `opacity: 0`, не просто прячет родителя, а наследуется на все дочерние элементы. Это значит, что это поведение можно переписать и вложенный элемент с `visibility: visible` будет видно. Это можно использовать для кастомизации разметки, сгенерированной сторонней библиотекой:
```

2022-02-20 09:35 UTC, Semigradsky commented
@solarrust @pepelsbey Спасибо за советы! Добавил интерактивный пример.

2022-02-21 11:51 UTC, pepelsbey approved these changes

2022-02-22 08:14 UTC, solarrust approved these changes
Прекрасно! Спасибо большое!

2022-02-22 08:14 UTC, merged