Приветствую, добавил описание тега optgroup, атрибутов и стилизации.
doka-guide/content pull request #2788
Opened 2022-02-18 14:51 UTC by Granondo

В целом, немного добавил общего описания для чего и как используется тег. 
Также разобрал два основных атрибута.
И варианты стилизации в различных браузерах и операционных системах.
Если есть корректировки, замечания, буду рад добавить.

2022-02-18 18:47 UTC, solarrust reviewed
Привет!

Спасибо большое за контрибьютинг. Много полезной информации! 🙌
Оставила несколько предложений по улучшению.

2022-02-18 18:47 UTC, solarrust commented on html/optgroup/index.md
> +Внутри тега `<optgroup>` стандартно используется тег `<option>`.
```suggestion
Внутри тега `<optgroup>` стандартно используется один или несколько тегов `<option>`.
```

2022-02-18 18:47 UTC, solarrust commented on html/optgroup/index.md
> +- `label` — обязательный атрибут. Имя группы будет отображено в выпадающем списке. Теоретически мы можем оставить тег пустым или не использовать его вообще, но в таком случае мы получим пустое простр
```suggestion
- `label` — обязательный атрибут. Имя группы будет отображено в выпадающем списке. Теоретически мы можем оставить атрибут пустым или не использовать его вообще, но в таком случае над списком будет пустое пространство.
```

Кстати, а это никак не решается при помощи CSS?

2022-02-18 18:47 UTC, solarrust commented on html/optgroup/practice/granondo.md
> +При использовании атрибута `disabled`, все элементы внутри данного списка нельзя будет выбрать.
```suggestion
🛠 При использовании атрибута `disabled` все элементы внутри группы нельзя будет выбрать.
```

2022-02-18 18:47 UTC, solarrust commented on html/optgroup/practice/granondo.md
> + </optgroup>
```suggestion
```

2022-02-18 18:47 UTC, solarrust commented on html/optgroup/practice/granondo.md
> + <optgroup disabled label=" Необычные цветы">
```suggestion
 <optgroup disabled label="Необычные цветы">
```

2022-02-18 18:47 UTC, solarrust commented on html/optgroup/practice/granondo.md
> +При использовании атрибута `disabled`, все элементы внутри данного списка нельзя будет выбрать.
В принципе мы эту информацию даём и в самой статье. Стоит добавить какую-то интересную фишку, связанную с этим, если она есть.

2022-02-18 18:47 UTC, solarrust commented on people/granondo/index.md
> +name: 'Владимир'
Просто интересуюсь: не хочешь добавить фамилию? Абсолютно ок, если нет =)

2022-02-18 18:47 UTC, solarrust commented on html/optgroup/practice/granondo.md
> +### Стили
Про стили было бы классно рассказать в самой статье. Это важная информация. Можно ограничиться короткой выжимкой о работоспособности стилей, не добавлять таблицы =)
Например, можно сказать «На Windows стили работают во всех браузерах. А вот на macOS не работают почти нигде. Проверяйте на Can I use(ссылка).»

2022-02-19 10:48 UTC, Granondo commented on html/optgroup/index.md
> +Тег `<optgroup>` позволяет группировать опции внутри элемента [`<select>`](/html/select/). Таким образом он становится заголовком списка. При этом сам заголовок нельзя выбрать.
Да, так лучше читается.

2022-02-19 10:49 UTC, Granondo commented on html/optgroup/index.md
> +Внутри тега `<optgroup>` стандартно используется тег `<option>`.
Согласен, важное уточнение.

2022-02-19 10:59 UTC, Granondo commented on html/optgroup/index.md
> +- `label` — обязательный атрибут. Имя группы будет отображено в выпадающем списке. Теоретически мы можем оставить тег пустым или не использовать его вообще, но в таком случае мы получим пустое простр
Ты имеешь ввиду, чтобы вместо пустого пространства было что то другое? Если зададим цвет фона, то получим цветное пустое пространство, еще поищу есть ли варианты.

2022-02-19 11:00 UTC, Granondo commented on html/optgroup/practice/granondo.md
> +При использовании атрибута `disabled`, все элементы внутри данного списка нельзя будет выбрать.
окей, поищу еще.

2022-02-19 11:02 UTC, Granondo commented on people/granondo/index.md
> +name: 'Владимир'
не, спасибо, так привык)

2022-02-19 11:07 UTC, Granondo commented on html/optgroup/practice/granondo.md
> +### Стили
хорошо, переделаю, добавлю в статью

2022-02-19 11:52 UTC, pepelsbey requested changes
Спасибо за развитие доки и совет!

Я бы только перевёз совет про disabled в тело статьи, это всё-таки часть документации. А про стилизацию на отдельных платформах уже можно рассказать в совете. Там немного не хватает примера кода, который проверяется в разных браузерах, чтобы было понятно, что такое цвет/фон. Даже встроить демку было бы хорошо, чтобы читатель мог оценить как в его браузере это отобразится.

2022-02-22 09:16 UTC, solarrust commented
@Granondo @pepelsbey привет!
Я подправила текст статьи и совет, добавила пример и чуть подшаманила форматирование. Давайте вместе посмотрим всё ли ок?

2022-02-22 09:57 UTC, Granondo commented
> @Granondo @pepelsbey привет!
> Я подправила текст статьи и совет, добавила пример и чуть подшаманила форматирование. Давайте вместе посмотрим всё ли ок?

да, отлично, я думал убрать таблицы и текстом описать про совместимость с браузерами, в последнем коммите добавил текст, но не убрал таблицы, но можем сделать и так
демка отлично смотрится, изначально не понял, что она должна таким образом выглядеть

2022-02-22 10:39 UTC, pepelsbey requested changes
Не уверен насчёт таблиц, но демка какая-то совсем плохая по контрасту в Firefox на macOS. Может выбрать цвета, на которые не так больно смотреть?

<img width="385" alt="image" src="https://user-images.githubusercontent.com/105274/155115535-1fd6ca3d-2b3a-46a2-94bf-9eb833fbc45a.png">

2022-02-23 06:56 UTC, solarrust commented
Поменяла цвета в демке, поиграла с оттенками. Теперь с контрастом всё ок =)

![CleanShot 2022-02-23 at 09 54 55](https://user-images.githubusercontent.com/13676514/155273547-76fa7c7c-82e2-4918-b176-d73ea4d32874.png)

2022-02-23 23:57 UTC, pepelsbey approved these changes

2022-02-24 07:42 UTC, solarrust approved these changes
Класс! Получилось круто!
Пиши ещё =)

2022-02-24 07:43 UTC, merged

2022-02-24 13:59 UTC, Granondo commented
> Класс! Получилось круто!
> 
> Пиши ещё =)

Спасибо, тоже понравилось, приятно с создавать с вами что-то новое, буду ещё писать обязательно)