Добавляет доку про unload/beforeunload
doka-guide/content pull request #2790
Opened 2022-02-19 12:27 UTC by kotosha-real

Fix #2718

2022-02-21 07:50 UTC, bespoyasov reviewed
Хорошая статья! 👍 
Отдельное спасибо за ссылки на спецификацию :–) 

У меня есть пара предложений, но это в основном оформление.

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/index.md
> +title: "События `unload` и `beforeunload`"
Добавим поле `description`? Оно используется для карточки статьи в соцсетях и облегчения жизни поисковикам.

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/index.md
> +Когда пользователь уходит со страницы, генерируется событие `unload`. Обработать это можно, [подписавшись на это событие](/js/events/) у объекта `window`.
```suggestion
Когда пользователь уходит со страницы, генерируется событие `unload`. Мы можем отреагировать на него, [подписавшись на это событие](/js/events/) у объекта `window`.
```

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/index.md
> +В современном вебе всё увешано трекингом: клики, переходы, прокрутка до определённых секций и ещё куча всего. Почему бы не <!-- yaspeller ignore:start -->трекать<!-- yaspeller ignore:end --> уход пол
Думаю, лучше добавить это слово в [словарь исключений](https://github.com/doka-guide/content/blob/main/docs/speller.md#словарь-исключений).

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/index.md
> +Что происходит в коде выше? Когда пользователь покинет страницу, будет собрана некоторая информация и будет отправлена на некоторый эндпоинт. `sendBeacon` — это неблокирующий метод отправки данных, п
```suggestion
Что происходит в коде выше? Когда пользователь покинет страницу, функция `getSomeUsefulData` соберёт аналитическую анформацию, а метод `sendBeacon` отправит её по адресу `/some-endpoint`. Метод `sendBeacon` — это неблокирующий метод отправки данных, почитать про него подробнее можно [тут](https://w3c.github.io/beacon/). А [вот](https://caniuse.com/?search=sendbeacon) его поддержка.
```

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/index.md
> +Что происходит в коде выше? Когда пользователь покинет страницу, будет собрана некоторая информация и будет отправлена на некоторый эндпоинт. `sendBeacon` — это неблокирующий метод отправки данных, п
Здесь, думаю, стоит рассказать о том, что такое неблокирующий метод отправки. Можно поверхностно, без деталей, и можно сделать коллаут.

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/index.md
> +1. Нетленная классика с зависшим Word и несохранённой курсовой
```suggestion
1. Нетленная классика с зависшим Word и несохранённой курсовой.
```

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/index.md
> +2. Случайный свайп влево на ноутбуках Apple, который вместо горизонтальной прокрутки возвращает на предыдущую страницу
```suggestion
2. Случайный свайп влево на ноутбуках Apple, который вместо горизонтальной прокрутки возвращает на предыдущую страницу.
```

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/practice/kotosha-real.md
> +🛠 Как бы это очевидно ни звучало, помните, что обработка `beforeunload` может отменить уход со страницы. На одном из проектов это использовалось для предотвращения случайного выхода со страницы с анк
Думаю, эти слова тоже можно добавить в словарь :–)

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/practice/kotosha-real.md
> +🛠 Как бы это очевидно ни звучало, помните, что обработка `beforeunload` может отменить уход со страницы. На одном из проектов это использовалось для предотвращения случайного выхода со страницы с анк
Возможно, ещё стоит превратить последовательность действий в список — он будет легче считываться, им проще управлять вниманием пользователя.

2022-02-21 07:50 UTC, bespoyasov commented on js/event-unload-and-beforeunload/practice/kotosha-real.md
> +🛠 Не полагайтесь на события `unload` и `beforeunload` для определения завершения пользовательской сессии. Например, в следующем сценарии в ни одно из них не наступит: пользователь посещает страницу в
Тут тоже можно превратить последовательность в список.

2022-02-22 20:54 UTC, nlopin requested changes
Привет! Спасибо, что взялся за эти события, у нас никак не доходят руки 👍

У меня радикальное предложение, поэтому я не стал комментировать отдельные детали статьи, Саша их подметил точно, обрати на них внимание.

Предлагаю:

- [x] разбить статью на две — «Событие `beforeunload`» и «Событие `unload`» (по факту они уже разделены в структуре и нужно только разнести по файлам)
- [ ] добавить объяснение, как этот `beforeunload` выглядит в интерфейсе (do you want to leave...)
- [ ] у меня демка сработала только один раз, вот [показываю на видео](https://www.loom.com/share/5821589f92154f41a5c797391942b719)

2022-02-24 08:23 UTC, kotosha-real commented
Спасибо за комменты!
Постараюсь в выходные засесть и всё поправить

2022-02-28 07:49 UTC, tachisis commented on .yaspeller.json
> +    "окирпиченн(ый|ого|ому|ая|ой|ую|ое|ых|ым)",
Давайте оставим это слово ровно с тем окончанием, которое используется в статье.

2022-03-14 08:38 UTC, tachisis approved these changes
Апрув на словарь

2022-03-18 07:50 UTC, nlopin commented
@kotosha-real извини, война выбила из колеи :(

Я вижу, что ты разбил статью на две. Значит ли это, что я могу удалить объединённую?

2022-03-18 08:03 UTC, nlopin commented on js/event-beforeunload/practice/kotosha-real.md
> +🛠 Как бы это очевидно ни звучало, помните, что обработка `beforeunload` может отменить уход со страницы. На одном из проектов это использовалось для предотвращения случайного выхода со страницы с анк
я не смог осознать этот совет. Мне не хватило контеста ситуации и понимания, что происходит при `document.body.innerHTML = document.body.innerHTML` (я так подозреваю, сбрасываются все обработчики из-за того, что страница по сути генерируется заново)

2022-03-18 08:06 UTC, nlopin commented on js/event-unload-and-beforeunload/demos/beforeunload/index.html
> +<!doctype html>
Демка огонь 🔥

2022-03-18 08:08 UTC, nlopin reviewed
Стало в разы лучше. Несколько комментариев оставил. 

Думаю раз у нас теперь две отдельные статьи, то стоит сделать предложение, чтобы их связать

2022-03-18 08:08 UTC, kotosha-real commented on js/event-beforeunload/practice/kotosha-real.md
> +🛠 Как бы это очевидно ни звучало, помните, что обработка `beforeunload` может отменить уход со страницы. На одном из проектов это использовалось для предотвращения случайного выхода со страницы с анк
Да, всё верно, сбрасываются обработчики. Давай я попробую перефразировать

2022-03-18 08:09 UTC, kotosha-real commented on js/event-unload-and-beforeunload/demos/beforeunload/index.html
> +<!doctype html>
Спасибо)

2022-03-18 08:10 UTC, nlopin commented on js/event-beforeunload/index.md
> +Когда пользователь уходит со страницы, мы можем спросить его, точно ли он хочет уйти. За это отвечает обработка события `beforeunload`.
Может что-то такое сделать?

```suggestion
Когда пользователь уходит со страницы, мы можем спросить его, точно ли он хочет уйти. За это отвечает обработка события `beforeunload`.

Событие происходит перед [событием выгрузки страницы `unload`](/js/event-unload/).
```

2022-03-18 08:13 UTC, kotosha-real commented on js/event-beforeunload/index.md
> +Когда пользователь уходит со страницы, мы можем спросить его, точно ли он хочет уйти. За это отвечает обработка события `beforeunload`.
Да, выглядит хорошо

2022-03-18 08:14 UTC, kotosha-real commented
@nlopin всё понимаю, самому не до статьи было.

Объединённую можно удалять, сохранил на случай, если решим оставить её, а не 2 разные)

2022-03-19 10:04 UTC, nlopin approved these changes
Всё хорошо, жду только обновления совета.

- [x] Уточнить совет

2022-03-19 13:57 UTC, kotosha-real commented
@nlopin затащил доформулированный совет

2022-03-20 22:28 UTC, merged