Совет для js/function-arguments-object/  — Объект arguments
doka-guide/content pull request #2791
Opened 2022-02-19 13:19 UTC by app

Остаточные параметры и деструктуризация массива когда не нужны лидирующие параметры.
С ситуацией встретился при написании серверных резолверов (resolvers) GraphQL.

2022-02-19 21:40 UTC, pepelsbey requested changes
Спасибо за совет! Я предложил выравнять стиль кода с нашим. А ещё можно для лучшей связности сослаться на доку по [Спред-синтаксис `...`](https://doka.guide/js/spread/).

2022-02-19 21:40 UTC, pepelsbey commented on js/function-arguments-object/practice/app.md
> +myHandler(1, 2, 3);
```suggestion
function myHandler(...[, second, third]) {
  console.log(`Второй параметр = ${second}`)
  console.log(`Третий параметр = ${third}`)
}

myHandler(1, 2, 3)
```

2022-02-20 10:32 UTC, app commented on js/function-arguments-object/practice/app.md
> +myHandler(1, 2, 3);
Вадим, при всем уважении к вашим pixel perfect инстинктам. Кстати, я так же делал некоторое время назад )
Мне теперь кажется разумным смириться с правилами prettier как дефолтным стандартом форматирования js кода.

```bash
$ cat test.js 
```
```js
function myHandler(...[, second, third]) {
  console.log(`Второй параметр = ${second}`)
  console.log(`Третий параметр = ${third}`)
}
myHandler(1, 2, 3)
```
```bash
$ prettier test.js | cat -ljs
```
```js
function myHandler(...[, second, third]) {
  console.log(`Второй параметр = ${second}`);
  console.log(`Третий параметр = ${third}`);
}
myHandler(1, 2, 3);
```

2022-02-20 10:44 UTC, app commented
> Спасибо за совет! Я предложил выравнять стиль кода с нашим. А ещё можно для лучшей связности сослаться на доку по [Спред-синтаксис `...`](https://doka.guide/js/spread/).

Честно говоря, это мой второй PR в content.  Первый, где я добавил совет как раз по указанному вами адресу, я сам закрыл, решив, что помещать этот совет в статью про спреад синтаксис  не совсем уместно, так как тут как бы rest syntax а там spread syntax :)  

Думаю, у меня недостаточно квалификации обосновывать одинаковость концепции этих двух синтаксисов :)  
Они, конечно, выглядят одинаково, но по смыслу несколько разнятся, на мой взгляд.  
Ссылку, тем не менее, могу добавить :) Только комментарий к ней какой сделать? :)

2022-02-20 23:57 UTC, pepelsbey commented
> Попробуйте убрать точку с запятой вот из этого кода и получите ошибку.

Тут такое дело, что это наш стиль кода. Если вы хотите, то можете завести дискуссию об этом и мы вместе обсудим, стоит ли его менять. Будем рады выслушать ваши аргументы. А в рамках этого ПР мы ждём кода в том же стиле, что и во всех остальных примерах. Это последовательность помогает читателям.

2022-02-21 00:00 UTC, pepelsbey commented
> Они, конечно, выглядят одинаково, но по смыслу несколько разнятся, на мой взгляд

Если вы считаете, что читателя лучше не путать ссылкой на похожий, но другой элемент языка, то можно и не добавлять ссылку. Тут уже ваше дело, я только подсказал, что есть такая возможность.

2022-02-21 05:34 UTC, app commented
> > Попробуйте убрать точку с запятой вот из этого кода и получите ошибку.
> 
> Тут такое дело, что это наш стиль кода. Если вы хотите, то можете завести дискуссию об этом и мы вместе обсудим, стоит ли его менять. Будем рады выслушать ваши аргументы. А в рамках этого ПР мы ждём кода в том же стиле, что и во всех остальных примерах. Это последовательность помогает читателям.

Согласен. Поэтому уже принял предложенные изменения.

2022-02-21 07:08 UTC, app commented
@pepelsbey 
>Тут такое дело, что это наш стиль кода.

Хорошо бы дать ссылку на этот стиль. Мне не удалось найти её в https://github.com/doka-guide/content/blob/main/docs/contributing.md

Подозреваю, что лучше всего задают стиль кода сейчас вот эти два файла

https://github.com/doka-guide/platform/blob/main/.prettierrc.json
https://github.com/doka-guide/platform/blob/main/.eslintrc.json

Как минимум там выключены требования по использованию точки с запятой и перечислены используемые правила 
`"extends": ["eslint:recommended", "prettier", "plugin:prettier/recommended"]`

Думаю, для контрибьютера будет достаточно сказать: 
> Для соответствия вашего кода принятому у  нас стилю форматирования воспользуйтесь prettier c вот этим [файлом конфигурации](https://github.com/doka-guide/platform/blob/main/.prettierrc.json).

2022-02-21 07:13 UTC, bespoyasov approved these changes
Полезно, спасибо!

Я предложу ещё добавить пример вывода, чтобы читателям сразу было видно, что будет в каждой из переменных.

2022-02-21 07:13 UTC, bespoyasov commented on js/function-arguments-object/practice/app.md
> +myHandler(1, 2, 3)
```suggestion
myHandler(1, 2, 3)

// Второй параметр = 2
// Третий параметр = 3
```

2022-02-21 07:25 UTC, nlopin approved these changes
Огонь 👍 первый раз вижу такое применение, интересно.

Про ссылку на спред-синтаксис я с тобой согласен, это разные понятия. Нужно написать статью про rest syntax тожу

2022-02-21 11:50 UTC, pepelsbey approved these changes

2022-02-21 11:52 UTC, merged

2022-02-21 11:52 UTC, pepelsbey commented
Спасибо!