Добавляет совет в доку про логические операторы
doka-guide/content pull request #2793
Opened 2022-02-19 14:47 UTC by cergmin

Совет на страницу https://doka.guide/js/logic-operators/

2022-02-19 21:43 UTC, pepelsbey requested changes
Спасибо за совет!

Я бы привёл стиль JS-кода к нашему (без точек с запятой) и подумал, как бы привести менее противоречивый пример: не очень хочется называть другие справочники устаревшими.

2022-02-21 07:12 UTC, nlopin requested changes
Давай чуть поменяем структуру совета. Сейчас первый и второй совет взаимосвязаны и чтобы их осознать, нужно прочитать их полностью. 

Предлагаю добавить в каждый из советов по предложению. В этом предложении конденсировать осоновную мысль. Типа «Оператор `||` можно использовать для установки значения по умолчанию. Это возможно из-за следующей особенности...» и со вторым советом так же, если получится

2022-02-21 11:49 UTC, pepelsbey approved these changes
Лайк!

2022-02-22 14:14 UTC, bespoyasov approved these changes

2022-02-22 14:14 UTC, bespoyasov commented on js/logic-operators/practice/cergmin.md
> +❗ Нужно помнить, что если в переменную записать `undefined`, `null`, `NaN`, `0`, пустую строку или любое другое значение, которое JavaScript сможет привести к `false`, то данная конструкция перезапиш
```suggestion
❗ Нужно помнить, что если в переменную записать `undefined`, `null`, `NaN`, `0`, пустую строку или любое другое значение, которое JavaScript сможет привести к `false`, то данная конструкция перезапишет его значением по умолчанию.
```

2022-02-22 19:55 UTC, nlopin approved these changes
огонь

2022-02-22 19:55 UTC, merged