First review VIM article
doka-guide/content pull request #2794
Opened 2022-02-19 15:28 UTC by anatoly-kor

Первое ревью статьи о VIM(Как выйти из VIM). Resolve #2482 issues

2022-02-21 07:14 UTC, nlopin commented
Привет! Ревью чуть припозднится, потому что сейчас идет конкурс советов и все силы направлены на него. 

Если твоя цель была поучастовать в конкурсе, то нужно написать совет, а это — статья. Советы пишутся к уже существующим материалам

2022-02-21 07:39 UTC, bespoyasov reviewed
Статья классная, и примеры — огонь! 👍 

У меня по контенту замечаний нет, только несколько предложений по оформлению и вопросы к редакции по стилю.

2022-02-21 07:39 UTC, bespoyasov commented on tools/how_to_quit_vim/index.md
> +Основная идея vim заключается в том, что редактирование текста(в нашем случае кода) более сложная задача чем его создание. С нуля писать просто - сосредоточился и тыкаешь правильные кнопочки в правил
```suggestion
Основная идея vim заключается в том, что редактирование текста (в нашем случае кода) более сложная задача чем его создание. С нуля писать просто - сосредоточился и тыкаешь правильные кнопочки в правильной последовательности. А для редактирования приходится отследить где вносить правки, навести мышь на эту часть кода, начать удалять буквы удерживая Backspace, и только тогда уже можно будет вводить другой код. Повторить до успешного результата.
```

2022-02-21 07:39 UTC, bespoyasov commented on tools/how_to_quit_vim/index.md
> +Все мы с вами сталкиваемся с vim: при создании коммита или при работе на удалённом сервере. Однако, мало кто задумывался почему этот инструмент настолько популярен. Его поклонники до сих пор существу
@nlopin, @pepelsbey, @tachisis, а мы только в советах говорим от первого лица или в статьях тоже?

2022-02-21 07:39 UTC, bespoyasov commented on tools/how_to_quit_vim/index.md
> +Иногда важно расположение курсора для той или иной команды. Например, если курсор находится в середине слова, то <kbd>dw</kbd> отработает не совсем ожидаемо: удалится часть слова после курсора **вклю
```suggestion
Иногда важно расположение курсора для той или иной команды. Например, если курсор находится в середине слова, то <kbd>dw</kbd> отработает не совсем ожидаемо: удалится часть слова после курсора _включая букву под курсором_. Чтобы достичь желаемого поведения, достаточно вспомнить, что мы находимся в середине слова и поэтому нам понадобиться команда <kbd>diw</kbd>.
```

2022-02-21 07:39 UTC, bespoyasov commented on tools/how_to_quit_vim/index.md
> +![diw_di](demos/diw_di.gif)
Предлагаю гифки конвертнуть в `mp4` и добавить их на сайт через `video`, как в [статье о `debounce`](https://doka.guide/js/debounce/). Гифки получаются тяжёлыми и сильно «нагружают» браузер.

2022-02-21 07:39 UTC, bespoyasov commented on tools/how_to_quit_vim/index.md
> +Этот заголовок вызывает вопросы, однако это основные команды для движения по открытому файлу в визуальном режиме(_более подробно про режимах vim смотри [тут](##режимы-vim)_). Использование именно эти
```suggestion
Этот заголовок вызывает вопросы, однако это основные команды для движения по открытому файлу в визуальном режиме(_более подробно про режимах vim смотрите [тут](##режимы-vim)_). Использование именно этих клавиш это историческая особенность. Когда [Bill Joy](https://ru.wikipedia.org/wiki/Джой,_Билл) создавал редактор vi на его машине [ADM-3](https://ru.wikipedia.org/wiki/ADM-3) стрелочки были именно на этих кнопках.
```

2022-02-21 07:39 UTC, bespoyasov commented on tools/how_to_quit_vim/index.md
> +![diw_di](demos/diw_di.gif)
Тогда, к тому же, мы сможем переименовать папку `demos` в `video`, чтобы не создавать путаницы: `demos` используется для приложений-демок, которые вставляются айфреймами в статью и которые можно запустить в отдельном окне.

2022-02-21 10:42 UTC, anatoly-kor commented
> Привет! Ревью чуть припозднится, потому что сейчас идет конкурс советов и все силы направлены на него.
> 
> Если твоя цель была поучастовать в конкурсе, то нужно написать совет, а это — статья. Советы пишутся к уже существующим материалам

Я целенаправленно статью. Могу подождать, не проблема 👍🏻

2022-02-21 10:45 UTC, anatoly-kor commented on tools/how_to_quit_vim/index.md
> +![diw_di](demos/diw_di.gif)
Я конвертил из mov в gif, но так чтобы gif выглядел читабельно. Могу поэкспериментировать с параметрами конвертации чтобы добиться нужного размера, скажите только какой размер оптимальный. Или просто сделать mp4, как скажете.

2022-02-22 13:23 UTC, tachisis commented on tools/how_to_quit_vim/index.md
> +Все мы с вами сталкиваемся с vim: при создании коммита или при работе на удалённом сервере. Однако, мало кто задумывался почему этот инструмент настолько популярен. Его поклонники до сих пор существу
В статье (не доке) вполне можно говорить от первого лица, это авторский текст.

2022-02-22 20:58 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +VIM - сложный, но очень интересный инструмент. Он позволяет сильно ускорить вашу работу с текстом. В этой статье познакомимся с общими принципами работы в VIM, изучим режимы работы, посмотрим на неко
давай ссылку бахнем на официальный сайт https://www.vim.org/

2022-02-22 21:02 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +Основная идея vim заключается в том, что редактирование текста(в нашем случае кода) более сложная задача чем его создание. С нуля писать просто - сосредоточился и тыкаешь правильные кнопочки в правил
```suggestion
Основная идея vim заключается в том, что редактирование текста (в нашем случае кода) более сложная задача чем его создание. С нуля писать просто — сосредоточился и тыкаешь правильные кнопочки в правильной последовательности. А для редактирования нужно понять, куда вносить правки, навести мышь на эту часть кода, начать удалять буквы удерживая Backspace, и только после этого уже можно будет вводить другой код. Повторить до успешного результата.
```

2022-02-22 21:02 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +Однако перемещение и редактирование может происходить гораздо быстрее в случае, если не придётся трогать мышь или trackpad. Подумал и бац, уже редактируешь код в правильном месте. Магия вне Хогвартса
```suggestion
Однако перемещение и редактирование может происходить гораздо быстрее в случае, если не придётся трогать мышь или трекпад. Подумал и бац, уже редактируешь код в правильном месте. Магия вне Хогвартса - не иначе.
```

2022-02-22 21:02 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +- заменить 2 слова - change 2 word - <kbd>c2w</kbd>
```suggestion
- заменить два слова - change 2 word - <kbd>c2w</kbd>
```

2022-02-22 21:06 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +Этот заголовок вызывает вопросы, однако это основные команды для движения по открытому файлу в визуальном режиме(_более подробно про режимах vim смотри [тут](##режимы-vim)_). Использование именно эти
Сашин suggestion не принят, накину свой с его правками. Нужно чекнуть, что теги нормально отображаются

```suggestion
Клавиши <kbd>h</kbd><kbd>j</kbd><kbd>k</kbd><kbd>l</kbd> — это основные команды для движения по открытому файлу в визуальном режиме (подробнее о режимах vim смотрите поговорим ниже). Использование именно этих клавиш это историческая особенность. Когда [Билл Джой](https://ru.wikipedia.org/wiki/Джой,_Билл) создавал редактор vi, стрелочки на его машине [ADM-3](https://ru.wikipedia.org/wiki/ADM-3) были именно на этих кнопках.
```

2022-02-22 21:07 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +Этот заголовок вызывает вопросы, однако это основные команды для движения по открытому файлу в визуальном режиме(_более подробно про режимах vim смотри [тут](##режимы-vim)_). Использование именно эти
я бы даже фотку поставил

2022-02-22 21:07 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +- <kbd>R</kbd> - replace - режим замены текста **перед** курсором
```suggestion
- normal - обычный режим. Позволяет перемещаться по файлу используя кнопки, которые мы изучили ранее;
- <kbd>i</kbd> - insert - режим ввода текста;
- <kbd>v</kbd> - visual - режим выделения текста;
- <kbd>:</kbd> - command - режим ввода команд bash;
- <kbd>R</kbd> - replace - режим замены текста **перед** курсором.
```

2022-02-22 21:09 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +Как и было сказано ранее все в vim это глаголы и существительные английского языка. Сохранение и выход не исключение.
```suggestion
Как было сказано ранее, все в vim это глаголы и существительные английского языка. Сохранение и выход не исключение.
```

2022-02-22 21:10 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +- выйти и сохранить - <kbd>wq</kbd>
Поменяем, чтобы сохранить структуру как в списке выше:

```suggestion
- <kbd>w</kbd> — write, сохранить;
- <kbd>q</kbd> — quit, выйти;
- <kbd>q!</kbd> — выйти без сохранения изменений;
- <kbd>wq</kbd> — выйти и сохранить.
```

2022-02-22 21:11 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +## Передвижение в vim
мне тут не хватило еще перехода на конкретную строку и что-то типа page up/page down

2022-02-22 21:12 UTC, nlopin commented on tools/how_to_quit_vim/index.md
> +С примером конфигурации вы можете ознакомиться в моем [.dotfiles](https://github.com/anatoly-kor/dotfiles).
Давай это унесём в практику, заодно скажем, что такое дотфайлы

2022-02-22 21:14 UTC, nlopin reviewed
Классная статья будет 🔥

Откомментировал некоторые вещи, ну и с видео нужно решить по аналогии с теми видяшками, что у нас есть. @bespoyasov кто их создавал?

Обратил внимание, что некоторые правки были зарезолвлены, но не приняты. Для того, чтобы их принять, нужно кликнуть commit suggestion или как-то договориться, что с ними делает

2022-02-23 06:52 UTC, bespoyasov commented
> кто их создавал?

@nlopin, кто-то из команды дизайнеров. Точнее не скажу, у меня нет доступов к дизайнерским логам работы :–( 

> Могу поэкспериментировать с параметрами конвертации чтобы добиться нужного размера, скажите только какой размер оптимальный. Или просто сделать mp4, как скажете.

Думаю, можно начать с видео в 720p. (У нас всё равно выключен автоплей.)

Что думаете, @nlopin, @pepelsbey?

2022-02-23 09:02 UTC, anatoly-kor commented
> Классная статья будет 🔥
> 
> Откомментировал некоторые вещи, ну и с видео нужно решить по аналогии с теми видяшками, что у нас есть. @bespoyasov кто их создавал?
> 
> Обратил внимание, что некоторые правки были зарезолвлены, но не приняты. Для того, чтобы их принять, нужно кликнуть commit suggestion или как-то договориться, что с ними делает

Это я ссори, там простые правки синтаксиса были. Я правки сделал, но не коммиттил, ждал рекомендации про видео. Сделаю mp4 👍🏻

2022-02-23 09:06 UTC, anatoly-kor commented on tools/how_to_quit_vim/index.md
> +Все мы с вами сталкиваемся с vim: при создании коммита или при работе на удалённом сервере. Однако, мало кто задумывался почему этот инструмент настолько популярен. Его поклонники до сих пор существу
Это весомый аргумент о котором я не подумал :) Уберем

2022-02-23 21:27 UTC, pepelsbey requested changes
Спасибо за статью! У меня несколько соображений:

## Скрины

Справедливо заметили, что стоит сделать видео вместо GIF. Но я бы добавил, что сам формат этого видео можно улучшить:

- Записать не просто целый экран в привычном разрешении, а поменяет разрешение экрана на крупное (так увеличатся и подсказки с клавишами) или увеличить размер шрифта в консоли и записать так, чтобы было видно, что там происходит. Идеально — чтобы даже на экране смартфона. Размер видео не больше HD, может вполне хватить SD.
- Выбрать тему редактора более контрастную: сейчас очень болезненно смотреть на красное на чёрном и чёрное на красном.
- Положить картинки в images, в папке demos мы храним демки. Если будет видео, то в папку video.

## Название

Название редактора, как и все юниксовые утилиты, пишется со строчной. Vim в начале предложения и vim в середине предложения, как обычное слово.

## Алиас статьи

У нас принят кебаб-кейс, то есть how-to-quit-vim. Аналогично с названиями файлов и расширениями файлов — сейчас есть wq.JPG и diw_di.gif.

2022-02-24 00:05 UTC, pepelsbey commented
Есть идея про название статьи. У нас вообще справочник и есть вероятность, что ироничное название воспримут буквально, как руководство по выходу из программы. Можно оставить иронию, но повернуть её иначе и сделать более явной:

> Как войти в vim

То есть буквально введение. И отсылает к шутке про выход.

@tachisis что скажешь?

2022-02-28 07:48 UTC, tachisis commented
@pepelsbey по-моему, отличная идея для названия!

2022-02-28 10:08 UTC, anatoly-kor commented
@pepelsbey @nlopin закоммитил все замечания

2022-03-08 08:04 UTC, nlopin commented on tools/how-to-enter-to-vim/practice/anatoly-kor.md
> +  <source src="video/example.mp4" type="video/mp4">
@anatoly-kor я посмотрел видос, но не понял, что в нём показано. Нужно или описание сделать, либо дропнуть

2022-03-08 08:05 UTC, anatoly-kor commented on tools/how-to-enter-to-vim/practice/anatoly-kor.md
> +  <source src="video/example.mp4" type="video/mp4">
Как пример работы флоу в vim если поставить мой конфиг.

2022-03-08 08:09 UTC, nlopin commented on tools/how-to-enter-to-vim/practice/anatoly-kor.md
> +  <source src="video/example.mp4" type="video/mp4">
Предлагаю опустить потому что сложно визуально показать различие. Ну либо делать его в формате:
* вот так стандартно работает
* я применил дотфайлы
* стало работать как мне надо

2022-03-08 08:10 UTC, nlopin approved these changes

2022-03-08 08:11 UTC, anatoly-kor commented on tools/how-to-enter-to-vim/practice/anatoly-kor.md
> +  <source src="video/example.mp4" type="video/mp4">
Думаю лучше опустить тогда. Дотфайл ставиться совсем не быстро, видео длинною в 30 минут точно никто смотреть не будет. Да и до установки расширений это просто обычный редактор без каких либо плюшек

2022-03-08 08:20 UTC, nlopin commented on tools/how-to-enter-to-vim/practice/anatoly-kor.md
> +  <source src="video/example.mp4" type="video/mp4">
Супер, тогда ждем только благословления от @pepelsbey

2022-03-13 22:14 UTC, pepelsbey approved these changes

2022-03-13 22:16 UTC, pepelsbey commented
@nlopin поредачил немного, всё же Vim чаще называют с прописной, а не просто как юникс-утилиту. Ну и всякие мелочи: уровни заголовков, форматирование списков и прочее.

2022-03-14 08:41 UTC, merged