Дополняет доку <kbd>
doka-guide/content pull request #2795
Opened 2022-02-19 19:57 UTC by webdb81

Fix #577

2022-03-01 09:35 UTC, solarrust reviewed
Привет!
Спасибо за классную доку 🖤
Оставила пару комментариев. 
@pepelsbey приходи посмотреть

2022-03-01 09:35 UTC, solarrust commented on html/kbd/index.md
> +  - webdb81
```suggestion
  - webdb81
```

2022-03-01 09:35 UTC, solarrust commented on html/kbd/index.md
> +Содержимое тега `<kbd>` можно визуально оформлять с помощью [css-правил](/css/css-rule/). Например, для обрамления комбинаций клавиш рамкой определим такое правило для класса:
```suggestion
Содержимое тега `<kbd>` можно визуально оформлять с помощью CSS. Например, для обрамления комбинаций клавиш рамкой определим такое правило для класса `shortcut-key`:
```

2022-03-01 09:35 UTC, solarrust commented on html/kbd/index.md
> +При совместном использовании тегов [`<code>`](/html/code/) и [`<pre>`](/html/pre/) необходимо соблюдать порядок вложенности: тег [`<code>`](/html/code/) можно размещать внутри тега [`<pre>`](/html/pr
```suggestion
💡 При совместном использовании тегов [`<code>`](/html/code/) и [`<pre>`](/html/pre/) необходимо соблюдать порядок вложенности: тег [`<code>`](/html/code/) можно размещать внутри тега [`<pre>`](/html/pre/). А вот [`<pre>`](/html/pre/) внутри тега [`<code>`](/html/code/) - это уже нарушение правила вложенности, в чём можно убедиться на сайте [Can I Include](https://caninclude.glitch.me/caninclude?child=pre&parent=code).
```

2022-03-03 14:21 UTC, webdb81 commented
Добрый день.
Может бытьтекст подсказки добавить также в доки тегов `<code>` и `<pre>`?

2022-03-10 13:06 UTC, solarrust commented
Внесла микро-правки и позвала поревьюить @pepelsbey 🙏

2022-03-10 14:19 UTC, pepelsbey requested changes

2022-03-10 14:19 UTC, pepelsbey commented on html/kbd/index.md
> +Содержимое тега `<kbd>` можно визуально оформлять с помощью [css-правил](/css/css-rule/). Например, для обрамления комбинаций клавиш рамкой определим такое правило для класса:
```suggestion
Содержимое тега `<kbd>` можно визуально оформлять с помощью [CSS-правил](/css/css-rule/). Например, для обрамления комбинаций клавиш рамкой определим такое правило для класса:
```

2022-03-10 14:19 UTC, pepelsbey commented on html/kbd/index.md
> +```
Мне кажется, что можно без части «добавляем класс», это не очень релевантно теме. Как и в демке, так и в примере можно повесить стили просто на селектор по тегу и сделать всё проще.

2022-03-10 14:19 UTC, pepelsbey commented on html/kbd/demos/complex-kbd/index.html
> +    <p>Пример листинга программы для ввода данных в консоли:</p>
Мне кажется, что подписи стоит выносить за пределы демки. Это как будто поясняет демку, а не является её частью.

2022-03-10 14:19 UTC, pepelsbey commented on html/kbd/demos/complex-kbd/index.html
> +    }
Эти стили можно повесить прямо на body и избавиться от обёртки.

2022-03-15 07:54 UTC, solarrust approved these changes
Класс! 🙌

2022-03-17 22:25 UTC, pepelsbey approved these changes
[Поправил и упростил демки](https://github.com/doka-guide/content/pull/2795/commits/ce55ff510f8afb648841ee2c4e406ae145ae9d60), чтобы не было лишних отступов, тегов и сложностей. Добавил забытый тег. Теперь красота :)

2022-03-17 22:26 UTC, merged

2022-03-17 22:26 UTC, pepelsbey commented
Спасибо!