Дополняет статью про пакетные менеджеры
doka-guide/content pull request #2798
Opened 2022-02-20 20:44 UTC by vitalybaev

Три ключевых момента:

1. Добавил pnpm в популярные менеджеры пакетов - я считаю, что он уже достаточно популярный, чтобы стоять рядом с Yarn.
2. Добавил немного предыстории, какую боль вообще решают менеджеры пакетов.
3. Добавил раздел про лок-файл. Считаю, что информация очень важная, но как называть я не знаю :) Поэтому согласно руководству по стилю Доки - написал так, как я слышу это везде сам.

Комментарии и правки приветствуются

2022-02-21 07:17 UTC, nlopin commented on tools/package-managers/index.md
> +Как уже упоминалось, при установке и обновлении пакетов создаётся дерево зависимостей. Пакетный менеджер записывает его в специальный файл — лок-файл (от английского __lock__ — зафиксировать). В этом
> По этой причине лок-файл обязательно нужно фиксировать в [системе контроля версий](/tools/version-control/) вместе с другим кодом.

Давай в калаут вытащим:
«Обязательно фиксируйте лок-файлы в системе контроля версий. Это поможет вам создавать воспроизводимые сборки приложения»

2022-02-21 07:18 UTC, nlopin commented on tools/package-managers/index.md
> +Как уже упоминалось, при установке и обновлении пакетов создаётся дерево зависимостей. Пакетный менеджер записывает его в специальный файл — лок-файл (от английского __lock__ — зафиксировать). В этом
у меня тут ещё микро замечание. при стандартном `npm install` лок-файл не используется (надо факт чекнуть, конечно). Лок файл используется при вызове `npm ci` чтобы собирать проект для прода с теми же версиями, что и у разраба

2022-02-21 07:19 UTC, nlopin requested changes
Класс, спасибо за дополнение. Я оставил несколько замечаний, но ничего критичного

2022-02-21 07:20 UTC, nlopin commented on tools/package-managers/index.md
> +В мире JavaScript есть три популярных менеджера зависимостей — npm, pnpm и Yarn. Они очень похожи по функциональности, но у каждого есть свои особенности.
давай ссылки на официальные сайты сюда бахнем?

2022-02-21 07:24 UTC, bespoyasov reviewed
Спасибо!
Предложил пару правок :–)

2022-02-21 07:24 UTC, bespoyasov commented on tools/package-managers/index.md
> +Как уже упоминалось, при установке и обновлении пакетов создаётся дерево зависимостей. Пакетный менеджер записывает его в специальный файл — лок-файл (от английского __lock__ — зафиксировать). В этом
Возможно, стоит добавить в коллаут примеры редких исключений, чтобы читателям были понятны все ограничения.

2022-02-21 07:24 UTC, bespoyasov commented on tools/package-managers/index.md
> +Разные пакетные менеджеры называют этот файл по-разному: в npm это __package-lock.json__, в pnpm это __pnpm-lock.yaml__ а в Yarn — __yarn.lock__. Не рекомендуется использовать разные пакетные менедже
```suggestion
Разные пакетные менеджеры называют этот файл по-разному: в npm это __package-lock.json__, в pnpm это __pnpm-lock.yaml__ а в Yarn — __yarn.lock__. Не рекомендуется использовать разные пакетные менеджеры в одном проекте — один пакетный менеджер может не понять другой лок-файл и установить другие версии библиотек, что может привести к ошибкам в вашем коде.
```

2022-02-21 07:57 UTC, vitalybaev commented
Спасибо за ревью! Скоро запушу правки.
По поводу проверки орфографии я правильно понимаю, что просто добавить `лок` в исключения?

2022-02-21 08:07 UTC, bespoyasov commented
> По поводу проверки орфографии я правильно понимаю, что просто добавить лок в исключения?

Ага. Лучше прямо в словарь: мы его уже используем дважды, я думаю, оно всплывёт где-то ещё в будущем 😃

2022-02-21 15:32 UTC, vitalybaev commented on tools/package-managers/index.md
> +Как уже упоминалось, при установке и обновлении пакетов создаётся дерево зависимостей. Пакетный менеджер записывает его в специальный файл — лок-файл (от английского __lock__ — зафиксировать). В этом
Вообще про `npm ci` я хотел в практике написать, мне кажется полезный совет как раз для этого кейса.
Насчёт того, что лок-файл не испльзуется - интересный момент, возможно сказывается то, что я в основном варюсь в мире Yarn/pnpm. Уточню

2022-02-21 15:44 UTC, vitalybaev commented
@bespoyasov @nlopin у нас тут назревает конфликт колаутов 😀
От вас пришли предложения разместить два колаута в соседних предложениях:
1. Про то, что лок-файл обязательно нужно коммитить в vcs.
2. Про случаи, когда лок-файл будет обновлен  при установке.

100% нужно выбрать один, потому что колаут штука такая, не должна быть такой частой. Если выбирать, то я бы выбрал кейс про лок-файл и VCS, как мне кажется - это более важный поинт, который стоит подсветить для разработчиков.

2022-02-21 15:44 UTC, vitalybaev commented on tools/package-managers/index.md
> +В мире JavaScript есть три популярных менеджера зависимостей — npm, pnpm и Yarn. Они очень похожи по функциональности, но у каждого есть свои особенности.
Добавил 👌

2022-02-22 13:28 UTC, tachisis approved these changes
Апрув на добавление исключения в словарь

2022-02-22 14:20 UTC, bespoyasov commented
> Если выбирать, то я бы выбрал кейс про лок-файл и VCS, как мне кажется - это более важный поинт, который стоит подсветить для разработчиков.

Да, поддерживаю.

2022-02-22 14:41 UTC, vitalybaev commented
Добавил колаут про фиксацию лок-файлов в VCS.
Также указал про рассинхрон лок-файла и _package.json_.

Что-то еще важно дополнить/поправить?

2022-02-22 20:01 UTC, nlopin approved these changes
all good

2022-02-22 20:24 UTC, merged