Add new practice, margin and flexbox
doka-guide/content pull request #2799
Opened 2022-02-20 21:36 UTC by andzhr

2022-02-21 09:13 UTC, solarrust reviewed
Привет!

Спасибо большое за совет. Расскажи, пожалуйста, а почему выравнивание при помощи автоматических отступов лучше чем `justify-content/alugn-items: center` или `justify-content: space-between`, например?
В каких ситуациях действительно стоит использовать этот приём?

2022-02-21 09:13 UTC, solarrust commented on css/flexbox-guide/practice/andzhr.md
> +Свойство ```margin``` со значением ```auto``` позволяет очень гибко управлять выравниванием flex элементов. Например если необходимо, чтобы логотип и заголовок были в левой части контейнера, а наприм
```suggestion
🛠 Свойство `margin` со значением `auto` позволяет очень гибко управлять выравниванием flex элементов. Например если необходимо, чтобы логотип и заголовок были в левой части контейнера, а например кнопка меню прижата к правой части, то достаточно задать кнопке меню значение `margin-left: auto`, в этом случае отступ займёт всё свободное пространство flex контейнера и элемент с кнопкой меню окажется прижат к правой части. Так же можно задать нескольким элементам свойство `margin-*: auto`, в этом случае всё свободное пространство контейнера разделится в равных частях между отступами элементов, у которых задано это свойство.
```

2022-02-21 11:02 UTC, andzhr commented
@solarrust
Дополнил совет, описал в чём отличие от ```justify-content```

2022-02-21 11:48 UTC, pepelsbey requested changes
Чуть поредачил, а так нравится. Спасибо!

2022-02-21 11:48 UTC, pepelsbey commented on css/flexbox-guide/practice/andzhr.md
> +Свойство `margin` со значением `auto` позволяет очень гибко управлять выравниванием flex элементов. Например если необходимо, чтобы логотип и заголовок были в левой части контейнера, а например кнопк
```suggestion
Свойство `margin` со значением `auto` позволяет очень гибко управлять выравниванием флек-элементов. Например если необходимо, чтобы логотип и заголовок были в левой части контейнера, а например кнопка меню прижата к правой части, то достаточно задать кнопке меню значение `margin-left: auto`, в этом случае отступ займёт всё свободное пространство flex контейнера и элемент с кнопкой меню окажется прижат к правой части. Отличие от `justify-content:  space-between` здесь в том, что нет необходимости в дополнительной обёртке для логотипа и заголовка. Так же можно задать нескольким элементам свойство `margin-*: auto`, в этом случае всё свободное пространство контейнера разделится в равных частях между отступами элементов, у которых задано это свойство. Данный приём расширяет ту функциональность, которую нам даёт свойство `justify-content`, мы можем задавать отступы только между необходимыми элементами, а не всеми сразу.
```

2022-02-21 11:55 UTC, andzhr commented on css/flexbox-guide/practice/andzhr.md
> +Свойство `margin` со значением `auto` позволяет очень гибко управлять выравниванием flex элементов. Например если необходимо, чтобы логотип и заголовок были в левой части контейнера, а например кнопк
"флек-элементов" > "флекс-элементов"?

2022-02-22 10:40 UTC, pepelsbey approved these changes

2022-02-22 11:45 UTC, solarrust approved these changes
Класс! Спасибо за отличный совет!
Пиши ещё =)

2022-02-22 11:46 UTC, merged