Добавляет практику про after
doka-guide/content pull request #2802
Opened 2022-02-21 16:50 UTC by furtivite

Вспомнил интересный, кажется, способ использования `::after`. 

В конкурсе «Я люблю фронтенд» эта практика не участвует.

2022-02-22 09:51 UTC, solarrust reviewed
Пример хороший, но есть пара вопросов =)

2022-02-22 09:51 UTC, solarrust commented on css/after/demos/print/index.html
> +  <title>Добавления в ::after ссылки — Дока</title>
```suggestion
  <title>Добавления в ::after ссылки — ::after — Дока</title>
```

2022-02-22 09:51 UTC, solarrust commented on css/after/demos/print/index.html
> +  <a href="https://www.doka.guide/css/pseudoelements/" class="link">Узнать больше про псевдоэлементы в Доке</a>
В примере всего одна ссылку. Точно ли для стилизации нужен класс?

2022-02-22 09:51 UTC, solarrust commented on css/after/practice/furtivite.md
> +}
Не распарсила эту сложную конструкцию 🤔

2022-02-22 09:58 UTC, furtivite commented on css/after/demos/print/index.html
> +  <a href="https://www.doka.guide/css/pseudoelements/" class="link">Узнать больше про псевдоэлементы в Доке</a>
@solarrust тут я копипастил из другой демки в той же статье, так что наследовал. Уберу.

2022-02-22 10:01 UTC, furtivite commented on css/after/practice/furtivite.md
> +}
О! Я пропустил. Убрал.

2022-02-22 13:30 UTC, tachisis approved these changes

2022-02-23 07:01 UTC, solarrust reviewed
Чуть порефакторила =)

2022-02-23 07:01 UTC, solarrust commented on css/after/demos/print/index.html
> +      content: ' (ссылка: ' attr(href) ') ';;
```suggestion
      content: " (ссылка: " attr(href) ")";
```

2022-02-24 00:17 UTC, pepelsbey requested changes
Полезный совет :) Но есть вопросы:

1. Думаю нам не нужен www в ссылках
2. Что будет, если кликнуть по ссылке в демке внутри фрейма? Вероятно, ссылка откроется во фрейме, а это нужно? Может быть туда какой-то target или подумать, как лучше.
3. Высота 100vh проблематичная на мобильных: это весь экран устройства, а не просто от панели до панели, как на десктопе. То есть будет прокрутка. Есть более простой и надёжный способ сделать всё нужной высоты:

```css
html, body {
  height: 100%;
  margin: 0;
}
```

2022-03-28 06:46 UTC, solarrust commented
@pepelsbey @furtivite внесла правки, упростила пример, запретила клик по ссылке (мы же имитируем печатный текст). Гляньте, пожалуйста, и давайте сливать, если всё ок

2022-03-28 07:46 UTC, tachisis approved these changes

2022-04-06 08:13 UTC, solarrust approved these changes

2022-04-06 08:13 UTC, merged