Дизайнерские правки в статье: Виды веб-приложений
doka-guide/content pull request #2820
Opened 2022-02-28 09:34 UTC by furtivite

- Заменил все картинки, кроме гифки
- Добавил отступ (строчку) перед картинкой

2022-03-01 14:16 UTC, bespoyasov approved these changes

2022-03-03 07:45 UTC, nlopin requested changes
Нужно немного поменять, чтобы стало понятнее
- CSR нужно показать чётче, откуда там появляется HTML. Предлагаю словами прямо написать 
<img width="921" alt="image" src="https://user-images.githubusercontent.com/1469636/156519531-5115f142-2c99-4de1-ba61-8d66ef302bec.png">

- SSR сейчас выглядит так, будто пользователь вообще ничего не получает после запроса. Вот скетч как это вижу я. Ключевой момент — показать, что сначала присылаем HTML, а только затем JS 
![IMAGE 2022-03-03 08:39:34](https://user-images.githubusercontent.com/1469636/156518578-ef894eae-71c1-4792-8070-50f6b20fef15.jpg)

-  в схеме динамических страниц нужно сделать стрелку, что HTML уходит назад пользователю 
<img width="921" alt="image" src="https://user-images.githubusercontent.com/1469636/156518919-8789f8af-5d5c-4d54-b681-5f53726ce224.png">

2022-04-25 20:55 UTC, nlopin commented
@furtivite не вижу использования картинки _js/web-app-types/images/dynamic-pages_2.png_. Мне помочь?

2022-04-26 08:38 UTC, furtivite commented
@nlopin кажется, это новая картинка и я не совсем понимаю куда она подходит лучше всего. И нужна ли. Было бы классно, если бы ты помог.

2022-04-28 19:40 UTC, nlopin approved these changes
все поправил

2022-04-28 19:40 UTC, merged