Рецепт загрузки с прогрессбаром
doka-guide/content pull request #2834
Opened 2022-03-16 11:57 UTC by webdb81

Fix #2734

2022-03-16 18:24 UTC, solarrust reviewed
Классно получилось. Я с большим интересом прочитала получившийся рецепт. Спасибо!

Докинула несколько мелких правочек, в основном по форматированию кода. 

Ждём @nlopin чтобы он тоже почитал =)

2022-03-16 18:24 UTC, solarrust commented on recipes/progress/index.md
> +Загрузка пользователем файлов на сервер — задача, с которой разработчики часто встречаются при создании web-ресурсов или приложений. При этом хорошие практики организации взаимодействия с пользовател
```suggestion
Загрузка пользователем файлов на сервер — часто встречающаяся задача при создании сайтов и приложений. Хорошей практикой организации взаимодействия с пользователем является информирование его о ходе и результате выполнения процесса. Можно использовать прогресс-бар, который покажет пользователю процесс обработки и передачи файла на сервер.
```

2022-03-16 18:24 UTC, solarrust commented on recipes/progress/index.md
> +💡 Для каждого элемента внутри формы указывается атрибут [`id`](/html/global-attrs/#id/) — это позволит JS-коду обращаться к нужным элементам для выполнения необходимых действий.
```suggestion
Для каждого элемента внутри формы указывается атрибут [`id`](/html/global-attrs/#id/) — это позволит JS-коду обращаться к нужным элементам для выполнения необходимых действий.
```

2022-03-16 18:24 UTC, solarrust commented on recipes/progress/index.md
> +В Firefox эти стили не затронут бегунок, поэтому дополнительно потребуется использовать браузерный префикс `-moz`. Для стилизации в Chrome и Safari как самого элемента, так и его бегунка, необходимо
```suggestion
В Firefox эти стили не затронут бегунок, поэтому дополнительно потребуется использовать [вендорный префикс](/css/vendor-prefixes/) `-moz`. Для стилизации в Chrome и Safari как самого элемента, так и его бегунка, необходимо использовать браузерные префиксы `-webkit`.
```

2022-03-16 18:24 UTC, solarrust commented on recipes/progress/index.md
> +});
```suggestion
document.getElementById('uploadForm_File').addEventListener('change', function () {
  let fileCheckAmount = this.files[0]
  if (fileCheckAmount.size > 5242880) {
    alert('Принимается файл до 5 МБ')
    this.value = null
  }
})
```

2022-03-16 18:24 UTC, solarrust commented on recipes/progress/index.md
> +}
```suggestion
if (fileFormField.files.length > 0) {
  formSent.append('uploadForm_File', fileToLoad)

  xhr.upload.addEventListener('progress', progressHandler, false)
  xhr.addEventListener('load', loadHandler, false)
  xhr.open('POST', 'upload_processing.php')
  xhr.send(formSent)
} else {
  alert('Сначала выберите файл')
}
```

2022-03-16 18:24 UTC, solarrust commented on recipes/progress/index.md
> +}
```suggestion
function progressHandler(event) {
  let percentLoading = (event.loaded / event.total) * 100

  document.getElementById('uploadForm_Size').innerHTML = "Загружено " + (event.loaded/1048576).toFixed(1) + " МБ из " + (event.total/1048576).toFixed(1) + " МБ"
  document.getElementById('progressBar').value = Math.round(percentLoading)
  document.getElementById('uploadForm_Status').innerHTML = Math.round(percentLoading) + '% загружено...'
}
```

Функция `loadHandler()` показывает пользователю в текстовом элементе принятый ответ сервера о результатах загрузки файла. После этого значение прогресс-бара обнуляется.

```javascript
function loadHandler(event) {
  document.getElementById('uploadForm_Status').innerHTML = event.target.responseText
  document.getElementById('progressBar').value = 0
}
```

2022-03-16 18:26 UTC, solarrust commented on recipes/progress/demos/single-file/index.html
> +  <title>Прогресс бар загрузки файла — Рецепты — Дока</title>
```suggestion
  <title>Прогресс-бар загрузки файла — Рецепты — Дока</title>
```

2022-03-16 18:26 UTC, solarrust commented on recipes/progress/demos/single-file/index.html
> +
```suggestion
```

2022-03-16 18:26 UTC, solarrust commented on recipes/progress/demos/single-file/index.html
> +    <h2>Загрузка изображения с индикацией процесса</h2>
```suggestion
    <h2>Загрузка изображения с прогресс-баром</h2>
```

2022-03-16 19:22 UTC, webdb81 commented on recipes/progress/index.md
> +![Пример загрузки файла на сервер](images/progress_example.gif)
Видео вставлять синтаксисом картинки?

Например: `![Some alt-text](images/some_video.mp4)`

2022-03-18 07:05 UTC, solarrust commented on recipes/progress/index.md
> +![Пример загрузки файла на сервер](images/progress_example.gif)
Для вставки видео можно использовать синтаксис HTML

```css
<video controls width="700">
  <source src="video/tab-focus.mp4" type="video/mp4">
</video>
```

2022-03-22 22:18 UTC, nlopin requested changes
Мне нравится! Оставил комментарии, но ничего критичного

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +Загрузка пользователем файлов на сервер — часто встречающаяся задача при создании сайтов и приложений. Хорошей практикой организации взаимодействия с пользователем является информирование его о ходе
Чуть облегчил, но последнее слово за редактором, конечно: 
```suggestion
Загрузка пользователем файлов на сервер — часто встречающаяся задача при создании сайтов и приложений. Если файлы большие, то хорошей практикой будет показывать пользователю прогресс и результат загрузки файла. Для этого можно использовать прогресс-бар.
```

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +Реализовать полный процесс загрузки файла возможно только с использованием серверной части. Поэтому в статье будет рассмотрена организация отправки файла на стороне клиента: HTML-разметка, стилизация
У меня вот тут не очень склеиваются первое и второе предложение. Читаю так: «чтобы написать загрузку, нужен севрер, поэтому мы напишем HTML и JS код». 

Что мы хотим сообщить абзацем? что нужен сервер, но он за рамками этой статьи? если так, то думаю стоит явно добавить такую фразу

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +Более подробно про обработку файлов на стороне сервера с использованием языка программирования PHP можно узнать [в разделе документации PHP](https://www.php.net/manual/ru/features.file-upload.php).
Можно ещё докинуть предложение, что обработку файлов на сервере можно написать на любом языке, например, на PHP
```suggestion
Подробнее про обработку файлов на стороне сервера с использованием языка программирования PHP можно узнать [в разделе документации PHP](https://www.php.net/manual/ru/features.file-upload.php).
```

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +  document.getElementById('uploadForm_Size').innerHTML = "Загружено " + (event.loaded/1048576).toFixed(1) + " МБ из " + (event.total/1048576).toFixed(1) + " МБ"
Давай магическое число вынесем в константу

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +  document.getElementById('uploadForm_Status').innerHTML = Math.round(percentLoading) + '% загружено...'
`innerHTML` это опасная штука, не стоит учить вставлять обычный текст как html, кто-нибудь случайно сделает уязвимость

```suggestion
  document.getElementById('uploadForm_Status').textContent = Math.round(percentLoading) + '% загружено...'
```

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +  document.getElementById('uploadForm_Status').innerHTML = event.target.responseText
```suggestion
  document.getElementById('uploadForm_Status').innerHTML = event.target.textContent
```

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +![Внешний вид прогресс-бара в macOS и Windows](images/default_progressbar.webp)
я могу ошибаться, но мы пока предпочитаем png. @solarrust ?

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +Для обеспечения взаимодействия между клиентом и сервером будет использоваться `XMLHttpRequest` — набор механизмов для обмена данными без перезагрузки страницы. Более подробно о нём можно почитать на
```suggestion
Чтобы отправить файл на сервер без перезагрузки страницы воспользуется `XMLHttpRequest` — набором механизмов для обмена данными между клиентом и сервером без перезагрузки. Более подробно о нём можно почитать на [странице документации MDN](https://developer.mozilla.org/ru/docs/Web/API/XMLHttpRequest).
```

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +Загрузка файлов большого размера увеличивает нагрузку на сервер, поэтому установим максимальный размер файла в 5 МБ. Проверку размера файла выполним на этапе его выбора пользователем:
давай ещё добавим про `this.files[0]` пару слов, что это такое (у нас ещё ниже используется `fileFormField.files[0]`. Мы точно не хотим это унифицировать)

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +- добавляется обработчик события `load` для отслеживания статуса загрузки;
тут давай укажем, что это события, которые происходят на `XMLHttpRequest`, чтобы их случайно не приняли за события DOM

2022-03-22 22:18 UTC, nlopin commented on recipes/progress/index.md
> +Округление значений загруженного объёма данных выполняется с использованием метода `Math.round()`.
тут хочется услышать про `1048576`

2022-03-25 08:54 UTC, solarrust commented
@webdb81 привет! Скажи, пожалуйста, когда планируешь вернуться к статье? =) 
Мы бы очень хотели запустить раздел Рецептов в конце марта-начале апреля. Было бы круто успеть закончить к этому моменту. Статья окажется в центре внимания! 🤍

2022-03-25 09:23 UTC, webdb81 commented
@solarrust Добрый день.
Сегодня, после 16:00 (МСК) займусь доработкой =)

2022-03-25 09:30 UTC, solarrust commented on recipes/progress/index.md
> +![Внешний вид прогресс-бара в macOS и Windows](images/default_progressbar.webp)
Да, мы в данный момент в качестве исходника картинки загружаем PNG. А потому во время сборки трансформируем картинку в разные форматы.

2022-03-28 21:31 UTC, nlopin commented on recipes/progress/index.md
> +  const amountFile_Measure = 1048576
Давай назовём `BYTES_IN_MB`, а то сейчас стиль именования и не константа, и не переменная

2022-03-28 21:31 UTC, nlopin approved these changes
Все норм, давай только имя константы исправим

2022-03-29 11:56 UTC, solarrust commented
Ура! Финишная прямая!
Приглашаю нашего редактора @tachisis чтобы она взглянула на текст и @skorobaeus чтобы она поколдовала с демками.

2022-03-30 12:41 UTC, nlopin approved these changes

2022-03-31 09:21 UTC, skorobaeus commented
Привет! Я добавила диз:

- В HTML все элементы прежние, сменила их места относительно друг друга, и заменила заголовок на label;
- Больше всего дописала в CSS;
- Не меняла JS, кроме форматирования текста о статусе загрузки (Загружено % МБ из МБ);
- Цитаты кода в статье обновила.

Видео дошлю след. коммитом

2022-03-31 11:55 UTC, skorobaeus approved these changes

2022-03-31 12:02 UTC, solarrust approved these changes
Буквально последние косметические правки:
- немного отформатировала код, чтобы он помещался на экран
- переставила местами атрибуты ради однообразия

Спасибо огромное за крутую работу! ♥️

2022-03-31 14:30 UTC, merged