Добавляет шаблон пул реквеста
doka-guide/content pull request #2846
Opened 2022-03-21 22:28 UTC by nlopin

Эксперименты показали, что сделать несколько шаболонов пул реквестов удобными нельзя, поэтому я собрал один шаблон, оставив самый минимум. Давайте обсуждать.

Посмотреть вживую шаблон можно в [тестовом репозитории](https://github.com/doka-guide/pr-template-example). Попробуйте добавить или изменить README.md и при коммите выберите опцию внесения изменения через пул реквест. 

## Медиа

Скриншот пул реквеста:
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/1469636/159373366-4a695757-d61e-4ea8-9d3d-54714a804a2b.png">

Рассказ:
<a href="https://www.loom.com/share/7193e5a535564ee28fee03497ea89a12">
    <p>Doka · PR template demo - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/7193e5a535564ee28fee03497ea89a12-with-play.gif">
  </a>

2022-03-22 06:54 UTC, solarrust reviewed
Спасибо большое! 
Предложила пару микро-правочек =)

2022-03-22 06:54 UTC, solarrust commented on .github/pull_request_template.md
> +<!-- Список для самопроверки поможет вам подготовить пул реквест так, чтобы его быстро смёржили. Часть пунктов может быть неактуальна для вашей задачи, просто отметьте их как сделанные -->
```suggestion
<!-- Список для самопроверки. Поможет вам подготовить пул-реквест для быстро мёрджа. Часть пунктов может быть неактуальна для вашей задачи, просто отметьте их как сделанные -->
```

2022-03-22 06:54 UTC, solarrust commented on .github/pull_request_template.md
> +Closes #<!-- проставьте номер ишью, которая решает задача или удалите строку, если ишью нет-->
```suggestion
Closes #<!-- проставьте номер ишью, которое решает задача или удалите строку, если ишью нет -->
```

2022-03-22 06:54 UTC, solarrust commented on .github/pull_request_template.md
> +- [ ] Текст оформлен [по руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
```suggestion
- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
```

2022-03-24 12:38 UTC, pepelsbey reviewed
Красота :) Предложил небольшие правки в одном файле, аналогичные в другом.

2022-03-24 12:38 UTC, pepelsbey commented on .github/checklist_new_article.md
> +- [ ] Если в `title` есть код, то он завёрнут в бэктики
```suggestion
- [ ] Код в поле `title` завёрнут в бэктики
```

2022-03-24 12:38 UTC, pepelsbey commented on .github/checklist_new_article.md
> +- [ ] `keywords` содержат ключевые слова, которых нет в тексте статьи
```suggestion
- [ ] Поле `keywords` содержит ключевые слова, которых нет в тексте статьи
```

2022-03-24 12:38 UTC, pepelsbey commented on .github/checklist_new_article.md
> +- [ ] В поле `authors` указан автор. Файл автора есть в папке `people`
```suggestion
- [ ] В поле `authors` указан автор. Файл автора есть в папке _people_
```

2022-03-24 12:38 UTC, pepelsbey commented on .github/checklist_new_article.md
> +- [ ] Демки написаны согласно [рекомендациям](https://github.com/doka-guide/content/blob/main/docs/demos.md)
```suggestion
- [ ] Демки написаны по [рекомендациям](https://github.com/doka-guide/content/blob/main/docs/demos.md)
```

2022-03-24 12:38 UTC, pepelsbey commented on .github/checklist_new_article.md
> +- [ ] У картинок заполнен `alt`, у демок — `title`
```suggestion
- [ ] У картинок есть описание в `alt`, у фреймов демок название в `title`
```

2022-03-24 12:56 UTC, nlopin commented
@pepelsbey @solarrust правки приняты

2022-03-25 08:49 UTC, solarrust approved these changes

2022-03-30 06:28 UTC, furtivite approved these changes
👍

2022-03-30 06:52 UTC, igsekor approved these changes
Отлично! 👍

2022-03-30 11:45 UTC, pepelsbey requested changes
Вижу правки в одном файле, но аналогичный текст и во втором. Я поленился саджестить два раза, сорри.

2022-03-30 12:34 UTC, nlopin commented
@pepelsbey я невнимательно прочитал, поэтому во втором файле их не появилось. Теперь они там

2022-04-01 22:07 UTC, pepelsbey approved these changes

2022-04-01 22:07 UTC, merged