Добавляет рецепт про короткие ссылки на NJS
doka-guide/content pull request #2849
Opened 2022-03-23 11:47 UTC by igsekor

2022-03-25 14:20 UTC, solarrust reviewed
Звучит убедительно 😆
С точки зрения текста и структуры у меня особо нет замечаний. 
Разве что я с радостью бы почитала пояснение к скрипту.
А есть ли возможность перелинковать рецепт с какими-то нашими статьями? Есть что-то подходящее по теме?

2022-03-28 07:44 UTC, tachisis reviewed
Немного правочек

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Рано или поздно практически перед каждым разработчиком вставала задача использования сервиса коротких ссылок. Чаще всего такой сервис используется для публикации в социальных сетях или сбора специаль
```suggestion
Рано или поздно практически перед каждым разработчиком встаёт задача использования сервиса коротких ссылок. Чаще всего такой сервис нужен для публикации постов в социальных сетях или сбора маркетинговой статистики. У разработчика есть два пути — использовать готовый сервис или написать свой. Я выбираю второй вариант!

Использовать я буду Nginx.
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Задача, которая стоит передо мной, — генерация короткого варианта ссылки на главную страницу с набором GET-параметров, которая лежит на моём же домене. Пример:
```suggestion
Задача, которая стоит передо мной, — генерация короткого варианта ссылки на главную страницу с набором GET-параметров. Страница лежит на моём же домене. Пример:
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +- Короткая ссылка: `https://mysite.dev/get/72cbb2d3`
```suggestion
- Короткая ссылка: `https://mysite.dev/get/72cbb2d3`.
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Установить модуль NJS для Nginx согласно [официальной документации](https://nginx.org/ru/docs/njs/install.html).  Подробнее о модуле можно почитать в [официальной документации](https://nginx.org/en/d
```suggestion
Установим модуль NJS для Nginx по [инструкции из документации](https://nginx.org/ru/docs/njs/install.html). Подробнее о модуле можно почитать в [официальной документации](https://nginx.org/en/docs/njs/) или в статье «[Ма­гия вне Хо­гварт­са: NJS](https://web-standards.ru/articles/magic-njs/)».
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Включить модуль NJS и подключить нужный скрипт, добавив соответствующие строки в основной файл конфигурации:
```suggestion
Включим модуль NJS и подключим нужный скрипт, добавив соответствующие строки в основной файл конфигурации:
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Добавить строчки в конфигурацию для вашего сайта Nginx:
```suggestion
Добавим строчки в конфигурацию для вашего сайта Nginx:
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Добавить в поддиректорию _scripts_ в директории _nginx_ следующий скрипт:
```suggestion
Добавим в поддиректорию _scripts_ в директории _nginx_ следующий скрипт:
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Все файлы со ссылками будут лежать в папке _/links_, не забудьте выставить правильные права на папку.
```suggestion
Все файлы со ссылками будут лежать в папке _/links_, не забудьте выставить ей правильные права доступа.
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Какая задача сразу встаёт перед разработчиком при создании сервиса коротких ссылок? Нужно выбрать способ создания коротких ссылок. Можно использовать заранее заготовленные короткие ссылки. Например,
```suggestion
Какая задача сразу встаёт перед разработчиком при создании сервиса коротких ссылок? Нужно выбрать способ создания коротких ссылок. Можно использовать заранее заготовленные короткие ссылки. Например, для своей статьи на Доке можно сделать ссылку `https://mysite.dev/docker`. Такой подход позволяет сделать ссылки понятными человеку, что очень удобно. Однако перечень «разумных» названий будет быстро исчерпан, необходимо заранее продумать о масштабировании. Зато такой подход легко реализовать на уровне сервера обычным перенаправлением. Для Nginx перенаправление можно прописать прямо в секции `server` файла конфигурации:
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +- выбираете набор символов, которые вы будете использовать, исходя из кодировки или иных соображений (например, цифры, то есть 10 символов);
```suggestion
- выбираете набор символов, которые вы будете использовать, исходя из кодировки или иных соображений (например, цифры, то есть, 10 символов);
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Если вы являетесь единственным человеком, который генерирует ссылки, ссылок у вас немного, а генерировать эти ссылки нужно не часто, вполне может подойти способ с ручной настройкой сервера.
```suggestion
Если вы — единственный человек, который генерирует ссылки, ссылок у вас немного, а генерировать эти ссылки нужно не часто, вполне может подойти способ с ручной настройкой сервера.
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +Ссылки можно хранить в одном файле в виде, например JSON-объекта или простых строчек в формате ключ значение. Ссылки можно хранить в отдельных директориях или файлах. Мой вариант — использовать отдел
```suggestion
Ссылки можно хранить в одном файле в виде, например, JSON-объекта или простых строчек в формате «ключ-значение». Ссылки можно хранить в отдельных директориях или файлах. Мой вариант — использовать отдельные файлы в формате JSON.
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +В отличие от варианта с базой данных, есть определённые ограничения на количество поддиректорий, которые могут быть созданы внутри директории (например, для ext4 максимальное количество — 65535). Так
```suggestion
В отличие от варианта с базой данных, есть определённые ограничения на количество поддиректорий, которые могут быть созданы внутри директории (например, для ext4 максимальное количество — 65535). Также есть ограничение на максимальное количество файлов на диске (для ext4 максимальное количество ограничено ~4 миллиардами). Внимательно следите, чтобы не выйти за пределы диапазонов.
```

2022-03-28 07:44 UTC, tachisis commented on recipes/short-links/index.md
> +  - igsekor
```suggestion
  - igsekor
editors:
  - tachisis
```

2022-03-29 07:38 UTC, nlopin commented on recipes/short-links/index.md
> +Все файлы со ссылками будут лежать в папке _/links_, не забудьте выставить правильные права на папку.
давай тут ещё дадим команду на установку правил

2022-03-29 07:41 UTC, nlopin commented on recipes/short-links/index.md
> +
тут просится формула или картинка с формулой

10*10*10 = 10^3 = 1000

2022-03-29 07:47 UTC, nlopin requested changes
У меня сложилось впечатление, что совет незакончен. Как-то резко он обрывается. Что смутило:
* говорится про хранение в JSON, но я не увидел пример такого файла
* хочется комментариев в JS коде или какого-то его разбора

Если я попробую сейчас воспроизвести совет, то кажется формат JSONа это то, где я остановлюсь

2022-03-29 18:35 UTC, igsekor commented
> У меня сложилось впечатление, что совет незакончен. Как-то резко он обрывается. Что смутило:
> 
> * говорится про хранение в JSON, но я не увидел пример такого файла
> * хочется комментариев в JS коде или какого-то его разбора
> 
> Если я попробую сейчас воспроизвести совет, то кажется формат JSONа это то, где я остановлюсь

Добавил пояснения.

2022-03-30 12:41 UTC, nlopin reviewed
Ко мне пришло осознание, что я неправльно понимал совет. Получается чтобы создать ссылку мне нужно в сервер запрос кинуть?

2022-03-30 15:02 UTC, igsekor commented
> Ко мне пришло осознание, что я неправльно понимал совет. Получается чтобы создать ссылку мне нужно в сервер запрос кинуть?

Да.

2022-03-31 11:11 UTC, nlopin approved these changes

2022-03-31 12:17 UTC, solarrust approved these changes

2022-03-31 12:46 UTC, merged