Добавляет рецепт Let's Encrypt для nginx
doka-guide/content pull request #2851
Opened 2022-03-23 16:21 UTC by igsekor

В рецепте рассмотрен пример настройки HTTPS на основе сертификатов от Let's Encrypt для веб-сервера Nginx.

2022-03-23 20:18 UTC, solarrust reviewed
Спасибо за рецепт! 🍜

Кажется, что в данном случае надо слегка поменять структуру. «Готовое решение» по факту и является всем решением. А абзацы из разбора решения можно перенести во вступление или в тело решения.

2022-03-23 20:18 UTC, solarrust commented on recipes/lets-encrypt-nginx/index.md
> +Настроить протокол HTTPS для веб-сервера Nginx на основе сертификатов [Let's Encrypt](https://letsencrypt.org/docs/).
Я бы добавила буквально 1-2 предложения о том, что теперь все сайты без HTTPS считаются ненадёжными.

2022-03-23 20:18 UTC, solarrust commented on recipes/lets-encrypt-nginx/index.md
> +Этот сертификат валиден в течение 90 дней после генерации. После истечения срока, его необходимо будет сгенерировать заново (это можно сделать, например, с помощью службы cron). Само собой, у вас дол
А может заодно настроить демона, который будет сам обновлять сертификат по истечению времени?

2022-03-28 07:29 UTC, tachisis reviewed
Прекрасно! По структуре, в целом, согласна с предложением Алёны.

2022-03-28 07:29 UTC, tachisis commented on recipes/lets-encrypt-nginx/index.md
> +После установки базовой конфигурации, необходимо проверить её корректность и перезапустить веб-сервер:
```suggestion
После установки базовой конфигурации необходимо проверить её корректность и перезапустить веб-сервер:
```

2022-03-28 07:29 UTC, tachisis commented on recipes/lets-encrypt-nginx/index.md
> +Этот сертификат валиден в течение 90 дней после генерации. После истечения срока, его необходимо будет сгенерировать заново (это можно сделать, например, с помощью службы cron). Само собой, у вас дол
```suggestion
Этот сертификат валиден в течение 90 дней после генерации. После истечения срока его необходимо будет сгенерировать заново (это можно сделать, например, с помощью службы cron). Само собой, у вас должен быть доступ к серверу, на котором ваш сайт находится.
```

2022-03-28 07:45 UTC, tachisis commented on recipes/lets-encrypt-nginx/index.md
> +  - igsekor
```suggestion
  - igsekor
editors:
  - tachisis
```

2022-03-31 11:27 UTC, furtivite requested changes

2022-03-31 11:27 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +В зависимости от операционной системы и её настроек, установка веб-сервера и настройка файервола будет отличаться, но базовые принципы сохранятся.
Давай тут предложение заменим на такое: 

«Решение ниже подходит для Linux-дистрибутивов, использующих RPM-пакеты: Fedora, RedHat, Oracle Linux и других — если вы используете Ubuntu, Debian или другие дистрибутивы с deb-пакетами, обратите внимание на команды в комментариях»

2022-03-31 11:27 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +sudo dnf -y install firewalld
// для deb-дистрибутивов
// sudo apt install firewalld

2022-03-31 11:27 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +sudo dnf -y install firewalld
// для deb-дистрибутивов
// sudo apt install firewalld

2022-03-31 11:27 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +sudo dnf -y install snapd
// sudo apt install snapd

2022-03-31 11:27 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +sudo dnf -y install snapd
// sudo apt install snapd

2022-03-31 11:27 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +sudo dnf -y install firewalld
Вообще вот тут вопрос, а не хотим ли мы добавить установку SNAP-репозиториев чуть раньше, тогда дальше можно тащить все установки через SNAP (как бы я его не любил), но это будет более универсальное решение.

2022-03-31 11:31 UTC, furtivite requested changes

2022-03-31 11:31 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +В зависимости от операционной системы и её настроек, установка веб-сервера и настройка файервола будет отличаться, но базовые принципы сохранятся.
Давай тут предложение заменим на такое: 

«Решение ниже подходит для Linux-дистрибутивов, использующих RPM-пакеты: Fedora, RedHat, Oracle Linux и других — если вы используете Ubuntu, Debian или другие дистрибутивы с deb-пакетами, обратите внимание на команды в комментариях»

2022-03-31 11:31 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +В зависимости от операционной системы и её настроек, установка веб-сервера и настройка файервола будет отличаться, но базовые принципы сохранятся.
Но если мы установим SNAP там, где его нет, изначально, то можно написать:

«Для более универсального решения, мы будем устанавливать приложения как SNAP-пакеты и добавим SNAP-репозиторий там, где его нет.

2022-03-31 12:18 UTC, solarrust approved these changes

2022-03-31 12:48 UTC, nlopin commented on recipes/lets-encrypt-nginx/index.md
> +👆 Пакетный менеджер `dnf` используется для операционных систем семейства Red Heat. Если вы используете Linux из семейства Debian, то замените эту команду, например, на `apt`.
Red Hat?

2022-03-31 13:41 UTC, igsekor commented
Сделал по-другому. Посмотрите, кажется, так лучше.

2022-03-31 13:52 UTC, furtivite commented on recipes/lets-encrypt-nginx/index.md
> +Если этот файервол не установлен, на Linux, использующих RPM-пакеты (Fedora, RedHat, Oracle Linux и других) это можно сделать командой:
```suggestion
Если этот файервол не установлен, на системах Linux, использующих RPM-пакеты (Fedora, RedHat, Oracle Linux и других) это можно сделать командой:
```

Но тут как скажет уважаемая редакция.

2022-03-31 13:52 UTC, furtivite approved these changes
👍

2022-03-31 14:26 UTC, nlopin approved these changes

2022-03-31 14:27 UTC, merged