Уточнение про em при расчете width, height и т.д.
doka-guide/content pull request #2855
Opened 2022-03-25 10:16 UTC by anvartdinovtimurlinux

Margin и padding и прочие свойства (кроме font-size) в em всегда рассчитываются от размера шрифта своего элемента

2022-03-28 12:54 UTC, pepelsbey requested changes
Спасибо за идею объяснить рассчёт емов понятнее. Мне кажется, что это можно объяснить чуть иначе, через наследование свойства `font-size`. Плюс я упростил селектор до `.block__elem`, чтобы это выглядело как настоящий БЭМ.

Что скажете?

2022-03-28 12:54 UTC, pepelsbey commented on css/rem-em/index.md
> +Поэтому ширина вложенного элемента с классом `block__elem` будет равна 24px × 2 × 5 = 240px:
````suggestion
Значение в единицах `em` всегда рассчитывается от размера шрифта элемента: оно либо наследуется от родителя, либо задаётся на самом элементе. Продолжая наш пример, если элементу блока просто задать ширину `5em`, то для рассчёта будет использован унаследованный размер шрифта: 16px × 1,5 × 5 = 120px.

```css
.block__elem {
  width: 5em;
}
```

Но самому элементу задать размер шрифта `2em`, то к унаследованному размеру добавится множитель: 16px × 1,5 × 5 × 2 = 240px.
````

2022-03-28 12:54 UTC, pepelsbey commented on css/rem-em/index.md
>  .block .block__elem {
```suggestion
.block__elem {
```

2022-03-28 13:17 UTC, anvartdinovtimurlinux commented on css/rem-em/index.md
> +Поэтому ширина вложенного элемента с классом `block__elem` будет равна 24px × 2 × 5 = 240px:
Мне нравится)

2022-03-31 16:20 UTC, anvartdinovtimurlinux reviewed
опять орфография

2022-04-01 06:06 UTC, solarrust approved these changes
Большое спасибо за ценное уточнение! 🙌

2022-04-05 16:18 UTC, pepelsbey approved these changes

2022-04-05 16:18 UTC, merged

2022-04-05 16:18 UTC, pepelsbey commented
Красота, спасибо!