initial commit
doka-guide/content pull request #2874
Opened 2022-04-03 09:53 UTC by Khlebovsky

## Описание

Closes #

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные и заканчиваются слэшем (`/css/color/`, `/tools/json/`)
- [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-04-03 09:55 UTC, Khlebovsky commented
Есть у меня один вопрос по поводу статьи. Изначально я планировал писать код в примерах на основе PHP-либы для работы с ElasticSearch, но, если я правильно понимаю, то статьи должны обладать универсальностью - то есть я не должен привязываться в данном контексте к какому-то конкретному языку? Будет ли лучше описать работу с ES на основе чего-то более универсального (CURL, к примеру)?

2022-04-07 09:23 UTC, nlopin commented
Расскажи, что должно остаться в голове у читателя после статьи? По заголовку я ожидал, что мы расскажем что-то типа ментальной модели того, как работает эластик.

Если нужна либа, то я бы писал примеры на JS

2022-04-07 15:02 UTC, Khlebovsky commented
Так и должно быть, читатель должен понять, что такое эластик и как с ним работать.
В целом я думаю, не принципиально, на каком ЯП показывать примеры, в конце концов есть куча официальной доки и официальные либы под большинство языков. Но учитывая то, что Doka в большей степени рассчитана на фронтов, думаю, что действительно лучше будет написать на JS.

2022-05-24 20:11 UTC, Khlebovsky commented
Статья немножко затянулась. Готово к ревью.

2022-05-25 07:24 UTC, bespoyasov reviewed
У меня тут не очень много экспертизы, чтобы ревьюить, но читать было интересно. Спасибо! 😃 

Я добавил комментарии к логике повествования. Готов обсудить, если с чем-то не согласны, @Khlebovsky, @nlopin.

2022-05-25 07:24 UTC, bespoyasov commented on tools/elasticsearch/index.md
> +ES написан на Java, использует JSON REST API для работы с данными и Lucene для полнотекстового поиска. Подобные движки используются для сложного поиска по документам (релевантность, морфология, даты,
Я бы дал ссылки на ES и Lucene, как на первоисточники.

2022-05-25 07:24 UTC, bespoyasov commented on tools/elasticsearch/index.md
> +Если говорить коротко про архитектуру ES, то она такая: есть поисковые индексы, их можно делить на части - шарды. На каждом запущенном процессе (узле) ES может быть несколько шардов. Каждый узел деле
Вот тут без схемы или диаграммы очень сложно. Каждое понятие (кластер, шард, узел) для читателя, вероятно, ново. 

Их, думаю, стоит объяснить словами или на схеме.

2022-05-25 07:24 UTC, bespoyasov commented on tools/elasticsearch/index.md
> +Здесь 'search_index' выступает в роли названия нашего индекса, не более того.
```suggestion
Здесь `'search_index'` выступает в роли названия нашего индекса, не более того.
```

2022-05-25 07:24 UTC, bespoyasov commented on tools/elasticsearch/index.md
> +Давайте разберём. В блоке **analysis** мы описываем наши настройки анализатора. **char_filter** - символьный фильтр, его задача заменить указанные символы. **analyzer** - анализатор текста, который и
```suggestion
Давайте разберём. В блоке **analysis** мы описываем наши настройки анализатора. **char_filter** - символьный фильтр, его задача заменить указанные символы. **analyzer** - анализатор текста, который использует фильтры из блока **filter**. Фильтр `"shingle"` отвечает за расстояние между двумя словами для поиска искомой фразы, в нашем случае от 2 до 4. Про остальные понятно: стоп-слова и стемминг.
```

2022-05-25 07:24 UTC, bespoyasov commented on tools/elasticsearch/index.md
> +Давайте разберём. В блоке **analysis** мы описываем наши настройки анализатора. **char_filter** - символьный фильтр, его задача заменить указанные символы. **analyzer** - анализатор текста, который и
> Про остальные понятно: стоп-слова и стемминг.

О стоп-словах выше было сказано, а о стемминге — нет 😃 

Я бы всё же развернул термин, потому что он встречается здесь впервые.

2022-05-25 07:24 UTC, bespoyasov commented on tools/elasticsearch/index.md
> +Теперь текстовые данные будут обработаны нашим кастомным анализатором.
Вероятно, новичкам будет непонятно, когда данные будут обработаны (сразу после добавления мапинга, при добавлении новых данных, по расписанию?), может быть, стоит тоже добавить деталей.

2022-05-25 07:24 UTC, bespoyasov commented on tools/elasticsearch/index.md
> +Значительная часть работы уже сделана - мы описали наш поисковый индекс и можем с ним работать. Давайте добавим парочку товаров в наш индекс:
Я бы начал раздел про индексацию с описания, что такое индекс и зачем он нужен.

(Возможно, в посте о поисковой тулзе это лишнее, я не уверен.)

2022-05-25 17:10 UTC, Khlebovsky commented
Спасибо за обратную связь, на выходных допилю статью.

2022-05-29 17:53 UTC, nlopin reviewed
Класс, огненная статья получается! Я оставил комментарии, но это детали. Из большого хочется схему масштабирования

2022-05-29 17:53 UTC, nlopin commented on tools/elasticsearch/index.md
> +Если говорить коротко про архитектуру ES, то она такая: есть поисковые индексы, их можно делить на части - шарды. На каждом запущенном процессе (узле) ES может быть несколько шардов. Каждый узел деле
Да, нарисуй в [excalidraw](https://excalidraw.com/) диаграмку, я её под наши цвета потом обновлю

2022-05-29 17:53 UTC, nlopin commented on tools/elasticsearch/index.md
> +Для использования ES нужно установить [Java 8+ версии](https://www.java.com/ru/download/manual.jsp). Инструкция установки самого ES
а есть докер контейнер, который можно сразу стартануть?

2022-05-29 17:53 UTC, nlopin commented on tools/elasticsearch/index.md
> +Рассмотрим на практике создание индекса, его настройку, индексацию и поиск записей. Для работы используется фреймворк Express JS.
Давай тут добавим чуть про зависимости, которые понадобятся для старта демки. Абзац в стиле: «Для работы нам потребуется пустой проект, созданный через `npm init` с добавляенными зависимостями `npm i express @elastic/elasticsearch`»

2022-05-29 17:53 UTC, nlopin commented on tools/elasticsearch/index.md
> +Это самый простой пример маппинга - название и типы полей. Но давайте добавим анализатор и фильтр, чтобы нормализация текста была лучше. Для этого нужно добавить в наш индекс настройки:
Вот тут хочется пару слов, зачем нам заботиться о нормализации. Что-то в стиле «Но давайте добавим анализатор и фильтр, нормализация текста будет лучше. Это сделает наш поиск точнее»

2022-05-29 17:53 UTC, nlopin commented on tools/elasticsearch/index.md
> +Дальше нам нужно дополнить наш метод для создания маппинга:
я тут потерялся. Зачем нам это нужно? это мы применяем настройки выше?

2022-05-29 17:53 UTC, nlopin commented on tools/elasticsearch/index.md
> +Значительная часть работы уже сделана - мы описали наш поисковый индекс и можем с ним работать. Давайте добавим парочку товаров в наш индекс:
я бы добавил пару слов

2022-05-29 17:53 UTC, nlopin commented on tools/elasticsearch/index.md
> +ES написан на Java, использует JSON REST API для работы с данными и Lucene для полнотекстового поиска. Подобные движки используются для сложного поиска по документам (релевантность, морфология, даты,
Я бы ещё чуть развернул и сказал, что имеется ввиду под документом (тупо набор полей)

2022-06-02 17:35 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +ES написан на Java, использует JSON REST API для работы с данными и Lucene для полнотекстового поиска. Подобные движки используются для сложного поиска по документам (релевантность, морфология, даты,
Ссылки на первоисточники добавил, про документы написал подробнее

2022-06-02 17:57 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +Если говорить коротко про архитектуру ES, то она такая: есть поисковые индексы, их можно делить на части - шарды. На каждом запущенном процессе (узле) ES может быть несколько шардов. Каждый узел деле
Простую схемку накидал и описал, вот ссылка на редактирование: https://excalidraw.com/#room=13d9c551c59db35e640a,DTjG7A1JNmJJdvE7hrDbMg

2022-06-02 18:01 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +Давайте разберём. В блоке **analysis** мы описываем наши настройки анализатора. **char_filter** - символьный фильтр, его задача заменить указанные символы. **analyzer** - анализатор текста, который и
Добавил описание термина

2022-06-02 18:01 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +Теперь текстовые данные будут обработаны нашим кастомным анализатором.
Уточнил

2022-06-02 18:06 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +Значительная часть работы уже сделана - мы описали наш поисковый индекс и можем с ним работать. Давайте добавим парочку товаров в наш индекс:
Добавил

2022-06-02 18:15 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +Для использования ES нужно установить [Java 8+ версии](https://www.java.com/ru/download/manual.jsp). Инструкция установки самого ES
На данный момент ничего приличного нет, если найдется время, соберу и добавлю

2022-06-02 18:23 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +Рассмотрим на практике создание индекса, его настройку, индексацию и поиск записей. Для работы используется фреймворк Express JS.
Добавил блок со стартом

2022-06-02 18:25 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +Это самый простой пример маппинга - название и типы полей. Но давайте добавим анализатор и фильтр, чтобы нормализация текста была лучше. Для этого нужно добавить в наш индекс настройки:
Добавил

2022-06-02 18:25 UTC, Khlebovsky commented on tools/elasticsearch/index.md
> +Дальше нам нужно дополнить наш метод для создания маппинга:
Да, это применяет настройки. Дописал предложение про это

2022-06-02 18:44 UTC, Khlebovsky commented
@nlopin @bespoyasov предложения по статье учел, к проверке готово

2022-06-03 07:18 UTC, bespoyasov approved these changes
Лайк :—)

2022-06-08 16:04 UTC, Khlebovsky commented
@igsekor какие дальнейшие этапы работы со статьей?

2022-06-08 16:10 UTC, igsekor requested changes
Мне понравилось. Только вот можно всё таки указать способ без установки Java (с помощью Docker или с помощью облачной платформы). Так можно точно, почему бы и нет?

2022-06-08 16:10 UTC, igsekor commented on tools/elasticsearch/index.md
> +Для использования ES нужно установить [Java 8+ версии](https://www.java.com/ru/download/manual.jsp). Инструкция установки самого ES
А самый [официальный](https://hub.docker.com/_/elasticsearch)?

2022-06-08 16:16 UTC, Khlebovsky commented
> Мне понравилось. Только вот можно всё таки указать способ без установки Java (с помощью Docker или с помощью облачной платформы). Так можно точно, почему бы и нет? Облако вряд ли наш вариант, хоть и есть период без оплаты (

Достаточно будет просто упомянуть про докер или написать инструкцию по тому, как развернуть и настроить?

2022-06-08 16:20 UTC, igsekor commented
> Достаточно будет просто упомянуть про докер или написать инструкцию по тому, как развернуть и настроить?

Мне кажется, правильно было бы написать короткую инструкцию по настройке образа / контейнера. Нужно бы сослаться на [статью о Докере](https://doka.guide/tools/docker/) у нас, можно описать только применение.

2022-06-08 16:31 UTC, Khlebovsky commented
> > Достаточно будет просто упомянуть про докер или написать инструкцию по тому, как развернуть и настроить?
> 
> Мне кажется, правильно было бы написать короткую инструкцию по настройке образа / контейнера. Нужно бы сослаться на [статью о Докере](https://doka.guide/tools/docker/) у нас, можно описать только применение.

Добавил абзац про докер - закинул ссылки на статью про работу с докером, официальный образ и официальную инструкцию по запуску и настройке эластика в докере (неожиданно, но да, и такое бывает)

2022-06-08 17:07 UTC, igsekor approved these changes
Полетели!

2022-06-08 17:26 UTC, Khlebovsky commented
> Полетели!

Далее нужно, чтобы все комментарии были закрыты (решены)?

2022-06-09 09:01 UTC, nlopin commented
Привет! Я сегодня всё просмотрю и сольём 👍

2022-06-10 15:55 UTC, Khlebovsky commented
@nlopin ну как, что-то еще дополнить?

2022-06-10 20:22 UTC, nlopin commented
Все ок, мержу в выходные

2022-06-12 18:41 UTC, nlopin commented on tools/elasticsearch/index.md
> +Создаём любой файл для работы и начинаем писать код.
вот тут не пойдёт. Я решил попытаться собрать твой пример. Какой файл мне создавать? что значит «любой файл»? куда его поместить?

Давай чётко напишем, «Создайте файл Y.js в директории X». Да, на самом деле можно называть как угодно, но наш пример должен чётко собираться по написанному.

Дальше по коду мы добавляем функции, там всё хорошо, но вот когда мы начинаем эти функции вызывать, как на это посмотреть из нашего примера? Сейчас совсем непонятно. Нужно либо рассказывать как какие-то ручки из `express` дергать, либо вообще отойти от express, потому что я совсем не вижу, где мы его используем.

Если задача — собрать на коленке, то чем нам не подходит пустой `node init -y` проект? там же можно написать все функции и вызывать их из консоли простым запуском `node имя_файла.js` и смотреть на результат

2022-06-12 18:46 UTC, nlopin requested changes
@Khlebovsky у меня не сошёлся пример, я не понял, как его собрать по текущей инструкции и как выполнять описанный код (поиск и добавление в индекс). Оставил комментарий в статье.

Если я что-то упустил, то тыкни меня в текст, пожалуйста

2022-06-12 19:06 UTC, nlopin commented
Я перенёс скетч схемы в наши цвета и немного её переделал. Скажи, это адекватная картинка или лучше ничего не менять из того, что ты нарисовал?

![schema](https://user-images.githubusercontent.com/1469636/173249215-8821fb5c-13f3-4743-83a0-2f5fe43b338e.png)

Я попытался как-то подчернуть, что дата узлы разные шарды хранят, но не уверен, что это так с точки зрения эластика

2022-06-13 19:45 UTC, Khlebovsky commented
> @Khlebovsky у меня не сошёлся пример, я не понял, как его собрать по текущей инструкции и как выполнять описанный код (поиск и добавление в индекс). Оставил комментарий в статье.
> 
> Если я что-то упустил, то тыкни меня в текст, пожалуйста

Прочитал, спасибо. Опишу процесс подробнее

2022-06-13 19:46 UTC, Khlebovsky commented
> Я перенёс скетч схемы в наши цвета и немного её переделал. Скажи, это адекватная картинка или лучше ничего не менять из того, что ты нарисовал?
> 
> ![schema](https://user-images.githubusercontent.com/1469636/173249215-8821fb5c-13f3-4743-83a0-2f5fe43b338e.png)
> 
> Я попытался как-то подчернуть, что дата узлы разные шарды хранят, но не уверен, что это так с точки зрения эластика

В целом для базового понимания этой схемы будет достаточно, в сложную архитектуру лезть смысла нет

2022-06-25 09:46 UTC, Khlebovsky commented
@nlopin, добро времени! Извиняюсь, что так долго, только вчера руки дошли. Сессию в универе закрываю.
Переработал статью, немного изменил порядок изложения и переписал код. Теперь стало проще и понятнее, пометки что и где запускать добавил. Всё еще раз протестировал - работает. Если будут какие-то вопросы или рекомендации по допилу статьи, то на связи.

2022-06-27 23:19 UTC, Khlebovsky commented
Да, всё окей

2022-06-28 07:27 UTC, merged