Дока про `queueMicrotask`
doka-guide/content pull request #2915
Opened 2022-04-25 18:37 UTC by corocoto

## Описание

Добавляет доку про [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask), включая возможности его использования.

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные и заканчиваются слэшем (`/css/color/`, `/tools/json/`)

2022-04-26 08:43 UTC, nlopin requested changes
Спасибо за доку! 

Микро и макрозадачи очень интересная тема и важная тема. Структура хорошая, предложил несколько улучшений.

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +Браузерное API, которое может быть использовано для конвертации синхронного кода в асинхронный.
Меня смуает слово «конвертация кода», мы ведь по факту код не меняем, он просто выполняется асинхронно. Может лучше стоит сказать, что этот `queueMicrotask` выполняет переданный код асинхронно?

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +Код выше схож со сценарием использования [`setTimeout`](../settimeout/index.md/):
Мы используем абсолютные пути до других статей:
```suggestion
Код выше схож со сценарием использования [`setTimeout`](/js/settimeout/). Оба выполнят код асинхронно:
```

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +`queueMicrotask` добавляет переданную функцию в _очередь микрозадач_. И каждая функция выполняется одна за другой (_FIFO: First in First Out_) после того, как текущая задача завершила свою работу.
Тут нужно доточить формулировку, сейчас функция и задача используются взаимозаменяемо и это звучит непоследовательно. Предлагаю так:

```suggestion
`queueMicrotask` добавляет переданную функцию в _очередь микрозадач_. Функции в этой очереди выполняются одна за другой (_FIFO: First in First Out_) — когда текущая функция выполнилась, запускается следующая функция в очереди.
```

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +Микрозадачи будут выполнены только после того, как текущий _[стек вызовов](../async-in-js/index.md#stek-vyzovov/)_ окажется пустым, но перед выполнением _[цикла событий](../async-in-js/index.md#cikl-
```suggestion
Микрозадачи будут выполнены только после того, как текущий _[стек вызовов](/js/async-in-js/#stek-vyzovov)_ окажется пустым, но перед выполнением _[цикла событий](/js/async-in-js/#cikl-sobytiy)_.
```

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +Микрозадачи будут выполнены только после того, как текущий _[стек вызовов](../async-in-js/index.md#stek-vyzovov/)_ окажется пустым, но перед выполнением _[цикла событий](../async-in-js/index.md#cikl-
тут бы схему или картинку с приоритетами (или может сравнением microtask vs macrostask). Можешь набросать скетч такой схемы? а мы красиво нарисуем

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +Поэтому, если вызвать `queueMicrotask` после `setTimeout`, или наоборот - функция, переданная в `queueMicrotask` запустит своё выполнение первой.
замутим демку? По нажатию кнопки выполним и queueMicrotask и setTimeout которые добавляют текст в какой-нибудь элемент. Так можно будет наглядно показать, что микрозадачи выполняются раньше

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +Поэтому, если вызвать `queueMicrotask` после `setTimeout`, или наоборот - функция, переданная в `queueMicrotask` запустит своё выполнение первой.
```suggestion
Поэтому, если вызвать `queueMicrotask` после `setTimeout`, или наоборот - функция, переданная в `queueMicrotask` начнёт свое исполнение первой.
```

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +Представим, что у нас есть поисковая строка. Получается, что поиск элемента будет выполняться всякий раз, когда пользователь вводит что-то в эту строку. Таким образом, обработчик события будет вызван
тут я немного запутался:

> поиск элемента будет выполняться всякий раз, когда пользователь вводит что-то в эту строку

Думаю это связано с тем, что задача, которую ты рассказываешь — гипотетическая и её не видно в коде. Предлагаю либо добавить какой-то код про поиск (добавление обработчика и вызов `addAndSort()`, либо отказаться от описания задачи и сосредоточиться на самом примере: «Вот есть такая штука, она будет соритровать синхронно и долго на каждый вызов функции...»

2022-04-26 08:43 UTC, nlopin commented on js/queueMicrotask/index.md
> +```
тут хочется какое-то заключение. Что в итоге получится?

2022-04-26 08:44 UTC, nlopin commented
Есть ли у тебя идеи, что стоит рассказать в разделе «На практике»?

2022-04-26 08:45 UTC, nlopin commented
## Чек-лист для новой доки

### Метаданные

- [ ] Код в поле `title` завёрнут в бэктики
- [ ] Есть поле `description` с описанием
- [ ] Проставлен тег `doka`
- [ ] Поле `keywords` содержит ключевые слова, которых нет в тексте статьи
- [ ] В поле `authors` указан автор. Файл автора есть в папке _people_

### Дока

- [ ] Структура совпадает с [шаблоном](https://github.com/doka-guide/content/blob/main/docs/examples/doka.md)
- [ ] Демки написаны по [рекомендациям](https://github.com/doka-guide/content/blob/main/docs/demos.md)
- [ ] У картинок есть описание в `alt`, у фреймов демок название в `title`
- [ ] Дока добавлена в содержание раздела

2022-04-26 10:13 UTC, corocoto commented on js/queueMicrotask/index.md
> +Браузерное API, которое может быть использовано для конвертации синхронного кода в асинхронный.
@nlopin,  ага, предложенный вариант лучше. Поправлю вечером

2022-04-26 10:15 UTC, corocoto commented on js/queueMicrotask/index.md
> +Микрозадачи будут выполнены только после того, как текущий _[стек вызовов](../async-in-js/index.md#stek-vyzovov/)_ окажется пустым, но перед выполнением _[цикла событий](../async-in-js/index.md#cikl-
@nlopin, ага, попробую

2022-04-26 10:15 UTC, corocoto commented on js/queueMicrotask/index.md
> +Поэтому, если вызвать `queueMicrotask` после `setTimeout`, или наоборот - функция, переданная в `queueMicrotask` запустит своё выполнение первой.
@nlopin, да, давай. Займусь этим в свободное время

2022-04-26 19:36 UTC, corocoto commented
> Есть ли у тебя идеи, что стоит рассказать в разделе «На практике»?

@nlopin, пока ничего на ум не приходит. Но уверен, что идеи появятся 😌

2022-05-03 15:47 UTC, corocoto commented on js/queueMicrotask/index.md
> +Микрозадачи будут выполнены только после того, как текущий _[стек вызовов](../async-in-js/index.md#stek-vyzovov/)_ окажется пустым, но перед выполнением _[цикла событий](../async-in-js/index.md#cikl-
@nlopin, в процессе формирования схемы понял, что лучше описание микро и макрозадач вынести в отдельную статью. И по хорошему, схемы сравнений должны быть именно там.

Предлагаю предварительно оставить сравнение в этой статье, но в будущем подредактировать, и ссылаться на соответствующую статью (после того, как она появится)

2022-05-03 20:13 UTC, nlopin commented
@corocoto нужна ли помощь?

2022-05-04 06:08 UTC, corocoto commented
> @corocoto нужна ли помощь?

Пока что нет. Если возникнут вопросы - дам знать.

2022-05-04 19:54 UTC, corocoto commented
@nlopin, учел ряд твоих замечаний. По остальным - займусь в ближайшее время.

2022-05-04 19:59 UTC, corocoto commented on js/queueMicrotask/index.md
> +![схема событийного цикла](/js/queueMicrotask/images/event-loop-schema.png)
@nlopin, глянь пожалуйста схему, и информацию, располагающуюся ниже. Старался сделать все емко, но понятно. Если нужно расширить что-то - можем обсудить

2022-05-07 12:50 UTC, tachisis approved these changes
Апрув на словарь

2022-05-08 12:38 UTC, corocoto commented on js/queueMicrotask/index.md
> +Представим, что у нас есть поисковая строка. Получается, что поиск элемента будет выполняться всякий раз, когда пользователь вводит что-то в эту строку. Таким образом, обработчик события будет вызван
Привел другой пример с демками

2022-05-09 20:06 UTC, nlopin commented on js/queueMicrotask/index.md
> +Микрозадачи будут выполнены только после того, как текущий _[стек вызовов](../async-in-js/index.md#stek-vyzovov/)_ окажется пустым, но перед выполнением _[цикла событий](../async-in-js/index.md#cikl-
Хорошая идея, создашь ишью на такую статью?

2022-05-10 05:46 UTC, corocoto commented on js/queueMicrotask/index.md
> +Микрозадачи будут выполнены только после того, как текущий _[стек вызовов](../async-in-js/index.md#stek-vyzovov/)_ окажется пустым, но перед выполнением _[цикла событий](../async-in-js/index.md#cikl-
Ага

2022-05-10 20:48 UTC, nlopin commented on js/queueMicrotask/index.md
> +![схема событийного цикла](/js/queueMicrotask/images/event-loop-schema.png)
@bespoyasov подключись, пожалуйста.

Мне кажется мы сейчас не сосем корректно рассказываем, что может создать неверную картинку в голове читающего.
Не уверен, что здесь мы даем такую же картинку, как в статье про асинхронный JS, нужно их синхронизировать.

В моей голове сложилась картинка, что эти очереди просто выполняются последовательно, но не совсем понятно кем. Я думаю стоит тут как минимум сказать про event loop, что именно он управляет всем JS, а стек вызовов это задача, которая выполняется прямо сейчас. Может как-то так?

2022-05-10 20:52 UTC, nlopin commented on js/queueMicrotask/index.md
> +Предотвратим стандартное поведение формы при отправке данных:
Предлагаю поместить всю обработку из `handleSubmitButtonClick` в `handleFormSubmit`. Тогда и рассказывать про заглушку не придётся да и в целом это хорошая практика, слушать не только кнопку

2022-05-10 21:02 UTC, nlopin commented on js/queueMicrotask/index.md
> +Давайте посмотрим, к каким результатам это может привести. Для этого необходимо нажать на кнопку получения данных 2 раза:
в коде выше не видно, где происходит печать, поэтому сложно связать пример ниже с кодом. Давай добавим часть про вывод в textarea

2022-05-10 21:03 UTC, nlopin commented
Статья сложная, поэтому выходит долго. Думаю мы должны закончить в следующей итерации 💪 

я досыпал стилей, чтобы всё выглядело как в остальных демках

2022-05-10 21:30 UTC, nlopin commented
Я поправил одну демку, вот так теперь выглядит:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/1469636/167725036-1324d375-206b-41c0-ace8-f95954ec2352.png">

- заменил textarea на параграф
- принёс стили кнопок из https://doka.guide/js/array-every/
- срабатывает теперь на submit формы

Надо вторую тоже пофиксить, но я думаю ты всё равно её будешь описывать в статье, может как раз сможешь отрефакторить. Если нет, то дай знать и я сделаю

2022-05-10 21:38 UTC, nlopin commented on js/queueMicrotask/index.md
> +Предотвратим стандартное поведение формы при отправке данных:
это я сделал

2022-05-11 06:25 UTC, corocoto commented on js/queueMicrotask/index.md
> +![схема событийного цикла](/js/queueMicrotask/images/event-loop-schema.png)
> В моей голове сложилась картинка, что эти очереди просто выполняются последовательно, но не совсем понятно кем.

@nlopin, хотел сделать акцент только на 3-ех элементах, дабы не переусложнять схему. Но раз возникают вопросы, то да, действительно схему нужно сформировать более расширенную и информативную.

2022-05-11 07:12 UTC, bespoyasov commented on js/queueMicrotask/practice/corocoto.md
> +#### 🛠️ «Возможные риски»
Мне кажется, здесь не хватает какого-то ключевого слова: «бесконечный цикл» или «рекурсия». Сейчас это есть, но оно зашифровано, и сложно понять, какая именно проблема может возникнуть.

«Бесконечный цикл» же мгновенно вызывает ассоциации с «5 потраченными когда-то на дебаг часами», сразу становится понятно, что за проблема.

2022-05-11 07:12 UTC, bespoyasov commented on js/queueMicrotask/index.md
> +Браузерное API, которое выполняет переданный код асинхронно.
Я не уверен, но возможно, лучше сформулировать как «“откладывает” выполнение переданного кода»?

2022-05-11 07:12 UTC, bespoyasov commented on js/queueMicrotask/index.md
> +Микрозадачи будут выполнены только после того, как текущий _[стек вызовов](/js/async-in-js/#stek-vyzovov)_ окажется пустым, но перед выполнением _[цикла событий](/js/async-in-js/#cikl-sobytiy)_.
Вероятно, точнее будет сказать «перед следующей итерацией»?

2022-05-11 07:12 UTC, bespoyasov commented on js/queueMicrotask/index.md
> +```
@nlopin, не знаю, важно ли это, но пример очень похож на MDN. Мы хотим это как-то исправить?

2022-05-11 07:12 UTC, bespoyasov commented on js/queueMicrotask/practice/corocoto.md
> +`queueMicrotask()` — полезная вещь когда у вас есть потребность отложить запуск задачи на наиближайшее время. Но также не стоит забывать о том, что выполнение больших объёмов работы на стороне микроз
```suggestion
`queueMicrotask()` — полезная вещь когда у вас есть потребность отложить запуск задачи на ближайшее время. Но также не стоит забывать о том, что выполнение больших объёмов работы на стороне микрозадач может стать проблемной точкой для интерактивности вашего приложения. Поэтому подходите к выбору с умом. Возможно, что для решения вашей проблемы стоит рассмотреть [`setTimeout()`](/js/settimeout/) или [`requestAnimationFrame()`](https://developer.mozilla.org/ru/docs/Web/API/window/requestAnimationFrame).
```

2022-05-11 07:12 UTC, bespoyasov commented on js/queueMicrotask/practice/corocoto.md
> +`queueMicrotask()` — полезная вещь когда у вас есть потребность отложить запуск задачи на наиближайшее время. Но также не стоит забывать о том, что выполнение больших объёмов работы на стороне микроз
Добавим деталей или примеров про «проблемы с интерактивностью»?

2022-05-11 17:54 UTC, corocoto commented on js/queueMicrotask/practice/corocoto.md
> +`queueMicrotask()` — полезная вещь когда у вас есть потребность отложить запуск задачи на наиближайшее время. Но также не стоит забывать о том, что выполнение больших объёмов работы на стороне микроз
@bespoyasov, ага

2022-05-23 19:34 UTC, corocoto commented on js/queueMicrotask/index.md
> +Браузерное API, которое выполняет переданный код асинхронно.
@bespoyasov, можно сделать и так, но по ощущениям, необходимо будет сослаться на раздел ниже. И получается что "Кратко" превращается не в особо емкое описание😄

Но предлагаю выслушать и @nlopin, чтобы принять коллективное решение

2022-05-26 21:27 UTC, nlopin approved these changes
Думаю мы достаточно поработали для того, чтобы статью слить 💪 Если что-то забыли или недоделали, то давай отдельным пиаром оформим (например, рассказ про микро/макро очереди).

2022-05-26 21:36 UTC, nlopin commented on js/queueMicrotask/index.md
> +Браузерное API, которое выполняет переданный код асинхронно.
Давайте оставим как есть

2022-05-26 21:39 UTC, nlopin commented on js/queueMicrotask/index.md
> +```
хороший пойнт, думаю стоит отойти от `this` и станет менее MDN-alike

2022-05-26 21:50 UTC, nlopin commented on js/queueMicrotask/index.md
> +    this.data = this.cache[url]
поправил

2022-05-26 21:56 UTC, merged

2022-05-27 06:22 UTC, corocoto commented
> Думаю мы достаточно поработали для того, чтобы статью слить 💪 Если что-то забыли или недоделали, то давай отдельным пиаром оформим (например, рассказ про микро/макро очереди). 

@nlopin, что-то в последние пару недель свободного времени не так много было. Спасибо тебе и @bespoyasov за помощь в правках.

2022-05-27 06:32 UTC, corocoto commented
Да, конечно, будем улучшать постепенно🙂