Добавляет доку по FormData
doka-guide/content pull request #2927
Opened 2022-05-01 11:12 UTC by vitalybaev

## Описание

Увидел, что ишью снова стал ничем и находится в горящем бэклоге. Пока что драфт, после вычитки на свежую голову, обновлю.

Closes #2135

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные и заканчиваются слэшем (`/css/color/`, `/tools/json/`)
- [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-05-01 16:06 UTC, nlopin requested changes
Огонь! Я приду ещё поправить description, мы стали писать их по-другому

2022-05-01 16:06 UTC, nlopin commented on js/form-data/index.md
> +`FormData` просто даёт нам возможность использовать такой способ отправки информации на сервер программно. В отличие от другого популярного способа кодирования данных `"application/json"`, в котором
Мне кажется вот этот параграф надо разворачивать, может даже в отдельный подзаголовок, и говорить больше о том, зачем такая штука нужна, в чём её отличие от отправки руками в `fetch`. У читателя должна сложиться картинка, почему и в каких случаях `FormData` нужна

2022-05-01 16:06 UTC, nlopin commented on js/form-data/index.md
> +// В переменной data будет храниться пустой объект FormData
давай выносить по максимуму комментарии из кода в текст

2022-05-01 16:06 UTC, nlopin commented on js/form-data/index.md
> +const data = new FormData(form)
фигасе, не знал

2022-05-01 16:06 UTC, nlopin commented on js/form-data/index.md
> +Для добавления данных в коллекцию, есть метод `append()`:
```suggestion
Для добавления данных в коллекцию есть метод `append()`:
```

2022-05-01 16:06 UTC, nlopin commented on js/form-data/index.md
> +☝️ `FormData` может хранить только строки или файлы в качестве значений. Поэтому все данные других типов будут [преобразованы](/js/typecasting/) в строку.
я бы это в разделе «Кратко» тоже упомнянул

2022-05-01 16:06 UTC, nlopin commented on js/form-data/index.md
> +// Объявляем функцию загрузки файла
тут тоже надо попытаться перед кодом рассказать, что будем делать. Тогда половину комментариев сможем удалить

2022-05-01 16:08 UTC, nlopin commented on js/form-data/index.md
> +## Как пишется
Кажется это пример
```suggestion
## Пример
```

2022-05-01 16:08 UTC, nlopin commented
## Чек-лист для новой доки

### Метаданные

- [ ] Код в поле `title` завёрнут в бэктики
- [ ] Есть поле `description` с описанием
- [ ] Проставлен тег `doka`
- [ ] Поле `keywords` содержит ключевые слова, которых нет в тексте статьи
- [ ] В поле `authors` указан автор. Файл автора есть в папке _people_

### Дока

- [ ] Структура совпадает с [шаблоном](https://github.com/doka-guide/content/blob/main/docs/examples/doka.md)
- [ ] Демки написаны по [рекомендациям](https://github.com/doka-guide/content/blob/main/docs/demos.md)
- [ ] У картинок есть описание в `alt`, у фреймов демок название в `title`
- [ ] Дока добавлена в содержание раздела

2022-05-01 16:23 UTC, vitalybaev commented on js/form-data/index.md
> +    // Для корректной работы необходимо задать заголовок `Content-Type` в "multipart/form-data"
![CleanShot 2022-05-01 at 20 19 46@2x](https://user-images.githubusercontent.com/724423/166154900-ad148e20-5f02-4c03-a450-3b30f5b23ab6.png)

Да, ты прав, наверное, единственный момент который я не факт-чекал.

2022-05-01 17:00 UTC, vitalybaev commented on js/form-data/index.md
> +`FormData` — это специальная коллекция данных, которая позволяет передавать данные в виде пар `[ключ, значение]` на сервер при помощи [`fetch()`](/js/fetch/) или `XMLHttpRequest`. При этом использует
Только вот `<form>` по умолчанию имеет всё же [`application/x-www-form-urlencoded`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/enctype)

2022-05-09 14:01 UTC, vitalybaev commented on js/form-data/index.md
> +### Загрузка файлов
Сделал 👌

2022-05-09 14:01 UTC, vitalybaev commented on js/form-data/index.md
> +## Как понять
Да, хорошая мысль, обновил 👌

2022-05-09 14:03 UTC, vitalybaev commented on js/form-data/index.md
> +`FormData` просто даёт нам возможность использовать такой способ отправки информации на сервер программно. В отличие от другого популярного способа кодирования данных `"application/json"`, в котором
Тоже об этом думал, теперь добавил больше контекста - про форматы кодирования данных между сервером и клиентом, короткий обзор популярных, их плюсы и минусы. Перечитал несколько раз - по мне стало лучше, но свежий взгляд будет полезен

2022-05-09 14:04 UTC, vitalybaev commented on js/form-data/index.md
> +// Объявляем функцию загрузки файла
Обновил 👌

2022-05-09 14:07 UTC, vitalybaev commented
Так, вроде по всем пунктам прошелся, жду комментариев 🙂

2022-05-09 14:51 UTC, bespoyasov reviewed
Огонь!

Я пришёл уже под конец вечеринки, поэтому особо добавить мне нечего :–)

2022-05-09 17:12 UTC, vitalybaev commented on js/form-data/index.md
> +// В переменной data будет храниться пустой объект FormData
Согласен, обновил

2022-05-15 16:31 UTC, nlopin approved these changes

2022-05-15 16:31 UTC, merged