Обновляет инструкцию для контрибьюторов
doka-guide/content pull request #2941
Opened 2022-05-11 13:55 UTC by furtivite

## Описание

Рассказывает о возможности добавить фотографию и краткое описание себя. 

Было: [читать](https://github.com/doka-guide/content/blob/main/docs/people.md)

Стало: [читать](https://github.com/doka-guide/content/blob/docs/update-people/docs/people.md)

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-05-11 17:03 UTC, igsekor requested changes
Мне кажется, что так понятнее. Но это лишь предложение.

2022-05-11 17:03 UTC, igsekor commented on docs/people.md
> +    Если фотографии не будет, мы покажем малый логотип Доки, тогда пункт `photo:` добавлять не нужно.
```suggestion
   Аватар по умолчанию — малый логотип Доки. Он отображается, если файла с изображением нет или пункт `photo:` в мете отсутствует.
```

2022-05-11 20:11 UTC, solarrust commented on docs/people.md
> +    Если фотографии не будет, мы покажем малый логотип Доки, тогда пункт `photo:` добавлять не нужно.
Я бы ещё пункт тегом обозвала

2022-05-13 10:56 UTC, solarrust approved these changes

2022-05-13 18:02 UTC, tachisis approved these changes

2022-05-14 19:25 UTC, nlopin approved these changes

2022-05-15 17:31 UTC, merged