Добавляет изменения в документацию и чеклисты, связанные с полем `related`
doka-guide/content pull request #3197
Opened 2022-06-07 11:22 UTC by furtivite

## Описание

Мы проводили хакатон по добавлению связанных статей в поле `related`, необходимо описать, что делает это поле в документации.

1. Описывает в документации
1. Добавляет в примеры статей и док
1. Добавляет в скрипт для создания новой статьи (чтобы новые контрибьюторы не забывали про это поле)
1. Правит чеклисты

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-06-07 15:47 UTC, solarrust reviewed
Спасибо! 🙏
Предложила правки в формулировки. Когда мы не знаем о каком типе идёт речь — дока или статья — договаривались называть это материалом.

2022-06-07 15:47 UTC, solarrust commented on .github/checklist_new_article.md
> +- [ ] Для статьи указаны три связанные страницы
```suggestion
- [ ] Для статьи указаны три материала для дальнейшего чтения
```

2022-06-07 15:47 UTC, solarrust commented on .github/checklist_new_doka.md
> +- [ ] В поле `related` есть список из трёх связанных страниц по теме
```suggestion
- [ ] В поле `related` есть три ссылки на материалы, которые стоит прочитать дальше
```

2022-06-07 15:47 UTC, solarrust commented on .github/checklist_new_doka.md
> +- [ ] Для Доки указаны три связанные страницы
```suggestion
- [ ] Для доки указаны три материала для дальнейшего чтения
```

2022-06-07 15:47 UTC, solarrust commented on docs/contributing.md
> +<!-- предлагаемые статьи к чтению: сюда добавляем три ссылки на статьи со связанной тематикой из любого раздела. Сюда не стоит добавлять статьи, которые идут следующей или предыдущей в списке -->
```suggestion
<!-- материалы для дальнейшего чтения: сюда добавляем три ссылки на статьи со связанной тематикой из любого раздела. Сюда не стоит добавлять статьи, которые идут следующей или предыдущей в списке -->
```

2022-06-07 15:47 UTC, solarrust commented on docs/examples/article.md
> +8. В related упомянуты статьи по теме, которые будут предлагаться в конце статьи. Не добавляем следующую или предыдущую статью в группе
```suggestion
8. В related добавлено три ссылки на материалы, которые будут предлагаться в конце статьи. Не добавляем следующий или предыдущий материал в разделе
```

2022-06-07 15:47 UTC, solarrust commented on docs/examples/doka.md
> +  - Относительная ссылка на статью по теме
```suggestion
  - Относительная ссылка на материал по теме
```

2022-06-07 15:47 UTC, solarrust commented on docs/examples/doka.md
> +8. В related упомянуты статьи по теме, которые будут предлагаться в конце статьи. Не добавляем следующую или предыдущую статью в группе
```suggestion
8. В related добавлено три ссылки на материалы, которые будут предлагаться в конце доки. Не добавляем следующий или предыдущий материал в разделе
```

2022-06-07 15:47 UTC, solarrust commented on new.sh
> +8. В related упомянуты статьи по теме, которые будут предлагаться в конце статьи. Не добавляем следующую или предыдущую статью в группе
```suggestion
8. В related добавлено три ссылки на материалы, которые будут предлагаться в конце. Не добавляем следующий или предыдущий материал в разделе
```

2022-06-08 12:05 UTC, tachisis approved these changes

2022-06-09 07:06 UTC, solarrust approved these changes

2022-06-12 18:17 UTC, nlopin commented on docs/examples/article.md
> +  - Относительная ссылка на материал по теме
она не относительная вроде. Может лучше сказать "ссылка на материал по теме, в формате раздел/статья"

2022-06-12 18:17 UTC, nlopin approved these changes

2022-06-13 13:39 UTC, solarrust approved these changes

2022-06-14 09:58 UTC, igsekor requested changes
Мне кажется, так требование будет однозначным

2022-06-14 09:58 UTC, igsekor commented on .github/checklist_new_article.md
> +- [ ] В поле `related` есть три ссылки на материалы, которые стоит прочитать дальше
```suggestion
- [ ] В поле `related` есть ссылки на материалы Доки, интересные в контексте данного (не более трёх)
```

Может так?

2022-06-14 09:58 UTC, igsekor commented on .github/checklist_new_article.md
> +- [ ] Для статьи указаны три материала для дальнейшего чтения
```suggestion
- [ ] Для статьи указаны материалы Доки, интересные для дальнейшего чтения
```

2022-06-14 09:58 UTC, igsekor commented on .github/checklist_new_doka.md
> +- [ ] Для доки указаны три материала для дальнейшего чтения
```suggestion
- [ ] Для доки указаны материалы Доки, интересные для дальнейшего чтения
```

2022-06-14 09:58 UTC, igsekor commented on docs/contributing.md
> +<!-- материалы для дальнейшего чтения: сюда добавляем три ссылки на статьи со связанной тематикой из любого раздела. Сюда не стоит добавлять статьи, которые идут следующей или предыдущей в списке -->
```suggestion
<!-- материалы для дальнейшего чтения: сюда добавляем три ссылки на материалы Доки со связанной тематикой из любого раздела. Сюда не стоит добавлять материалы, которые идут следующей или предыдущей в списке -->
```

2022-06-14 09:58 UTC, igsekor commented on docs/examples/article.md
> +  - Относительная ссылка на материал по теме
```suggestion
  - Ссылка на материал Доки по теме
```

2022-06-14 09:58 UTC, igsekor commented on docs/examples/article.md
> +8. В related добавлено три ссылки на материалы, которые будут предлагаться в конце статьи. Не добавляем следующий или предыдущий материал в разделе
```suggestion
8. В related добавлено три ссылки на материалы Доки, которые будут предлагаться в конце статьи. Не добавляем следующий или предыдущий материал в разделе
```

2022-06-14 09:58 UTC, igsekor commented on docs/examples/doka.md
> +  - Относительная ссылка на материал по теме
```suggestion
  - Ссылка на материал Доки по теме
```

2022-06-14 09:58 UTC, igsekor commented on new.sh
> +8. В related добавлено три ссылки на материалы, которые будут предлагаться в конце. Не добавляем следующий или предыдущий материал в разделе
```suggestion
8. В related добавлено три ссылки на материалы Доки, которые будут предлагаться в конце. Не добавляем следующий или предыдущий материал в разделе
```

2022-06-14 10:00 UTC, furtivite commented on .github/checklist_new_article.md
> +- [ ] В поле `related` есть три ссылки на материалы, которые стоит прочитать дальше
Надо бы проверить, а что сделает платформа, если ссылок будет больше трёх? Просто, если две, выглядит не то чтобы супер. Кажется, что чего-то не хватает. Поэтому мы пока договаривались с Алёной и Колей ставить всегда три.

2022-06-14 10:03 UTC, igsekor commented on .github/checklist_new_article.md
> +- [ ] В поле `related` есть три ссылки на материалы, которые стоит прочитать дальше
Она просто обрезает три.

2022-07-18 07:49 UTC, furtivite commented
Дока подзадержалась, принял предложения Игоря. Если не будет ошибок по трём статьям в `related`, так и оставим.

2022-07-18 07:52 UTC, furtivite commented
Три аппрува есть, мёржу.

2022-07-18 07:52 UTC, merged