Дока о preventDefault методе
doka-guide/content pull request #3555
Opened 2022-08-10 22:42 UTC by G-Milevski

## Описание

добавлена дока об preventDefault методе

Closes  #3338

## Чек-лист

- [x ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ x] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ x] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-08-12 10:06 UTC, nlopin commented on js/event-prevent-default/index.md
> +description: "данный метод позволяет отменить действие по умолчанию"
```suggestion
description: "Отменяет действие по умолчанию для события."
```

2022-08-12 11:22 UTC, G-Milevski commented on js/event-prevent-default/index.md
> +description: "данный метод позволяет отменить действие по умолчанию"
исправил

2022-08-12 11:43 UTC, G-Milevski commented
Только не понимаю почему статья не попала в нужынй раздел
<img width="350" alt="image" src="https://user-images.githubusercontent.com/25174255/184347311-7b2754aa-2ff5-4521-9157-49c8bab54c08.png">

2022-08-13 10:05 UTC, nlopin commented
> Только не понимаю почему статья не попала в нужный раздел 

добавил 👍

2022-08-13 11:16 UTC, nlopin requested changes
Отличная работа. Я чуть подредачил, посмотри, пожалуйста, ничего ли я не сломал.

У нас появилось [руководство по оформлению демо](https://github.com/doka-guide/content/blob/main/docs/demos/style.md), я перетащил стили из него. Немного усложнил демку, потому что в базовой реализации можно было устроить race-condition, если кликнуть по инпуту несколько раз подряд. Плюс добавил визуальную реакцию на нажатие:

[![](https://cdn.loom.com/sessions/thumbnails/460146fdc6fc4bf6a2c0e0931b28f2a8-with-play.gif)](https://www.loom.com/share/460146fdc6fc4bf6a2c0e0931b28f2a8)

Что осталось доделать:

- [ ] добавь информацию о себе в раздел `people`
- [ ] будет классно, если добавишь раздел «На практике» (нужно создать папку `practice` и файлик с твоим ником в нём). Например, рассказать, что нам всегда нужно вызывать `preventDefault()` при обработке форм с помощью JS, чтобы форма не улетела на сервер (за подробностями можно отправить в [статью про работу с формами](https://doka.guide/js/deal-with-forms/))

2022-08-13 22:18 UTC, G-Milevski commented
Демка супер, спасибо.

[x] добавил информацию о себе
[x] добавишь раздел «На практике»

2022-08-14 07:05 UTC, nlopin approved these changes
Супер! Сливаем

2022-08-14 07:55 UTC, merged