Добавляет лендинг для Летучек
doka-guide/content pull request #3557
Opened 2022-08-11 09:02 UTC by solarrust

Собрала посадочную для летучек, добавила туда описание, планы, форму для вопросов.

Фил фри поредачить или предложить правки — весь текст чистый экспромт. Фром май харт, как говорится ♥️

2022-08-11 09:19 UTC, nlopin commented
а можно картиночку?

2022-08-11 09:35 UTC, nlopin commented on pages/letuchka/index.md
> +    - Поменяли принцип фичеринга статей на главное
```suggestion
    - Поменяли принцип фичеринга статей на главной
```

2022-08-11 09:36 UTC, nlopin commented
Предлагаю не описывать детально план летучки. Например, убрать детали из «Фичи платформы». Так будет интереснее приходить на трансляцию. 

После трансляции можно добавить, если захотим

2022-08-11 10:15 UTC, nlopin approved these changes

2022-08-11 10:19 UTC, furtivite requested changes

2022-08-11 10:19 UTC, furtivite commented on pages/letuchka/index.md
> +  [Посмотреть](https://youtu.be/696nZzgPpZo)
```suggestion
  [Посмотреть на YouTube](https://youtu.be/696nZzgPpZo)
```

Мы уводим пользователя с сайта Доки, поэтому, кажется, стоит сказать, где он будет смотреть прошлую трансляцию.

2022-08-11 10:23 UTC, igsekor commented on pages/letuchka/index.md
> +## Что такое Летучка
```suggestion
## Кратко
```

Может так?

2022-08-11 10:24 UTC, igsekor commented on pages/letuchka/index.md
> +Летучка — это прямой эфир с редакцией. На нём мы рассказываем о внутренней кухне Доки, хвастаемся новыми фичами, показываем статистику и общаемся с сообществом.
```suggestion
Летучка — это прямой эфир с редакцией. Мы рассказываем о внутренней кухне Доки, хвастаемся новыми фичами, показываем статистику и общаемся с сообществом.
```

Наверное так?

2022-08-11 10:24 UTC, igsekor commented on pages/letuchka/index.md
> +Цель летучки — сделать Доку максимально прозрачной. Нам важно, чтобы сообщество понимало, что происходит внутри редакции, как выстраиваются процессы и принимаются решения. Каждый заинтересованный мож
```suggestion
Цель летучки — сделать Доку максимально прозрачной. Нам важно, чтобы сообщество понимало, что происходит внутри редакции, как выстраиваются процессы и принимаются решения. Каждый может задать вопрос или поучаствовать в обсуждении.
```

Может так?

2022-08-11 10:25 UTC, igsekor commented on pages/letuchka/index.md
> +Ближайшую летучку мы всегда заранее анонсируем в наших соц.сетях. Следите за постами!
```suggestion
Ближайшую летучку мы заранее анонсируем в наших соц.сетях. Следите за постами!
```

2022-08-11 10:25 UTC, igsekor commented on pages/letuchka/index.md
> +- [Fcbk](https://www.facebook.com/dokaguide) 🫣
```suggestion
```

2022-08-11 10:26 UTC, igsekor commented on pages/letuchka/index.md
> +Ниже будем выкладывать план следующей летучки, чтобы вы были в курсе основных тем и могли подумать над вопросами или предложениями.
```suggestion
Вот план следующей летучки, чтобы вы были в курсе основных тем и могли подумать над вопросами или предложениями.
```

2022-08-11 10:26 UTC, igsekor commented on pages/letuchka/index.md
> +Это примерный план летучки. Мы будем его уточнять.
```suggestion
План уточняется
```

2022-08-11 10:27 UTC, igsekor commented on pages/letuchka/index.md
> +Нам очень важен диалог, нам не хочется быть «говорящими головами». Знаем, что вам интересно многое в Доке. Задайте свои вопросы в форме ниже и мы ответим на них на ближайшей летучке!
```suggestion
Нам очень важен диалог, нам не хочется быть «говорящими головами». Знаем, что вам интересно многое в Доке. Задайте свои вопросы в форме ниже, и мы ответим на них на ближайшей летучке!
```

2022-08-11 10:28 UTC, igsekor reviewed
Предлагаю следующие правки 😇

2022-08-11 11:59 UTC, solarrust commented on pages/letuchka/index.md
> +## Что такое Летучка
Может вообще убрать этот заголовок?

2022-08-11 12:15 UTC, furtivite approved these changes
💛

2022-08-11 13:37 UTC, igsekor commented on pages/letuchka/index.md
> +## Что такое Летучка
Можно и так :)

2022-08-11 13:48 UTC, igsekor commented on pages/letuchka/index.md
> +- Челленджи, которые решаем
```suggestion
- <!-- yaspeller ignore:start -->Челленджи, которые решаем<!-- yaspeller ignore:end -->
```

2022-08-11 13:49 UTC, igsekor commented on pages/letuchka/index.md
> +  - Интро:
```suggestion
  - <!-- yaspeller ignore:start -->Интро<!-- yaspeller ignore:end -->:
```

2022-08-11 13:50 UTC, igsekor commented on pages/letuchka/index.md
> +    - [Ченджлог в репозитории контента](https://github.com/doka-guide/content/blob/main/CHANGELOG.md)
```suggestion
    - [<!-- yaspeller ignore:start -->Ченджлог<!-- yaspeller ignore:end --> в репозитории контента](https://github.com/doka-guide/content/blob/main/CHANGELOG.md)
```

2022-08-11 13:50 UTC, igsekor commented on pages/letuchka/index.md
> +    - Поменяли принцип фичеринга статей на главной
```suggestion
    - Поменяли принцип <!-- yaspeller ignore:start -->фичеринга<!-- yaspeller ignore:end --> статей на главной
```

2022-08-11 13:50 UTC, igsekor reviewed
Обнаружил проблемы со спеллером 😇

2022-08-11 19:52 UTC, solarrust commented on pages/letuchka/index.md
> +## Что такое Летучка
```suggestion
```

2022-08-11 20:27 UTC, igsekor approved these changes

2022-08-15 09:59 UTC, pa7lux commented
Привет

Немного бы переформулировал текст. Постарался перейти в плоскость того, что это не мероприятие редакции, а мероприятие для сообщества. Еще надо решить, ставим ли точки в конце пунктов списка ил инет. и сделать одинаково

```
# Летучка

Это прямой эфир с редакцией. Мы обсуждаем жизнь Доки: новые фичи, планы, рост и развитие нашего сообщества.

Цель летучки — быть прозрачными. Нам важно говорить о том, что происходит внутри редакции, как выстраиваются процессы и принимаются решения, получать обратную связь от читателей и участников. Каждый может задать вопрос или высказаться.

## Когда и где проходят летучки?

Проводим трансляции на Youtube. О дате и времени пишем на этой странице и в соц.сетях. Подписывайтесь и следите за новостями.

- Twitter
- VK
- Telegram
- YouTube

## Что обсуждаем?

Вот план следующей летучки. Вы можете на него повлиять. Для этого присылайте ваши вопросы или предложения (тут ссылка на якорь с формой), или просто приходите на стрим и пишите в чат.

### 27 августа 2022

План уточняется

- Привет, это Дока.
- Цели и план встречи.
- Про команду. Кто мы, где мы.
- Цифры и факты.
- Стратегические решения.
- Гость.
- Над чем сейчас работаем.
- Ближайшие планы.
- Говорим спасибо!
- Отвечаем на вопросы.
- Обсуждаем комментарии.

## Задайте нам вопрос

Нам важен диалог c вами. Летучка не может быть вебинаром. Напишите, что вам интересно узнать про Доку. Или предложите любую идею. Мы на связи. Увидимся на летучке!
```

2022-08-15 10:03 UTC, furtivite commented
> Привет
> 
> Немного бы переформулировал текст. Постарался перейти в плоскость того, что это не мероприятие редакции, а мероприятие для сообщества. Еще надо решить, ставим ли точки в конце пунктов списка ил инет. и сделать одинаково
> 

Предлагаю сделать первый все пункты, кроме последнего, обозначить точкой с запятой, а последний точкой, как это указано [в нашем стайлгайде](https://github.com/doka-guide/content/blob/main/docs/styleguide.md#списки) от Оли.

2022-08-15 10:04 UTC, solarrust commented
Если пункт начинается с большой буквы, то в конце ставится точка.

2022-08-16 16:48 UTC, igsekor commented
Для реализации формы нужно слить вот [этот PR](https://github.com/doka-guide/platform/pull/968) в платформе.

2022-08-17 07:10 UTC, solarrust commented
Попросила @skorobaeus добавить в дизайн лейблы для полей ввода. После этого вернусь с правками для формы. Видимо, в https://github.com/doka-guide/platform/pull/968

2022-08-17 22:43 UTC, solarrust commented
Формочка теперь выглядит так

<img width="1113" alt="CleanShot 2022-08-18 at 02 41 45@2x" src="https://user-images.githubusercontent.com/13676514/185256309-822c5ec4-62c1-464b-8899-952f48b9d5e8.png">


<img width="548" alt="CleanShot 2022-08-18 at 02 42 28@2x" src="https://user-images.githubusercontent.com/13676514/185256361-3d682251-ed5c-4a3c-a683-7012c592c6a9.png">


@skorobaeus я немного отошла от твоего дизайна в плане размеров. Использовала существующие в нашей системе переменные для размера шрифтов. Но в целом смысл тот же =)

2022-08-18 08:00 UTC, skorobaeus commented
> Формочка теперь выглядит так
> 
> <img alt="CleanShot 2022-08-18 at 02 41 45@2x" width="1113" src="https://user-images.githubusercontent.com/13676514/185256309-822c5ec4-62c1-464b-8899-952f48b9d5e8.png">
> 
> <img alt="CleanShot 2022-08-18 at 02 42 28@2x" width="548" src="https://user-images.githubusercontent.com/13676514/185256361-3d682251-ed5c-4a3c-a683-7012c592c6a9.png">
> 
> @skorobaeus я немного отошла от твоего дизайна в плане размеров. Использовала существующие в нашей системе переменные для размера шрифтов. Но в целом смысл тот же =)

Правильно сделала! Я специально использую существующие размеры и стили везде, где это возможно :)

2022-08-18 08:01 UTC, skorobaeus approved these changes

2022-08-18 08:05 UTC, igsekor commented
Такое ощущение, что стало совсем круто! 🙃

2022-08-18 09:47 UTC, solarrust commented
@igsekor кажется, для «совсем круто» надо сделать текстареа с подстраивающейся высотой. Я вчера пробовала, но посчитала, что для такой микро-формы это оверинжиниринг и не критично. 

Мёржу!

2022-08-18 09:47 UTC, merged

2022-08-18 11:31 UTC, igsekor commented
> @igsekor кажется, для «совсем круто» надо сделать текстареа с подстраивающейся высотой. Я вчера пробовала, но посчитала, что для такой микро-формы это оверинжиниринг и не критично.

Ну так-то можно)