Обновляет демки в JSON
doka-guide/content pull request #3558
Opened 2022-08-11 10:45 UTC by skorobaeus

## Описание

Обновляет демки в статье JSON, closes #3436

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-08-14 07:28 UTC, nlopin commented
Сейчас можно race-condition сделать в демке:

[![](https://cdn.loom.com/sessions/thumbnails/0ccaf7540afe4155a2b14e695b9852d7-with-play.gif)](https://www.loom.com/share/0ccaf7540afe4155a2b14e695b9852d7)

Предлагаю дизейблить кнопки с покемонами, пока запрос обрабатывается

2022-08-14 07:29 UTC, nlopin requested changes
Сейчас можно race-condition сделать в демке:

[![](https://cdn.loom.com/sessions/thumbnails/0ccaf7540afe4155a2b14e695b9852d7-with-play.gif)](https://www.loom.com/share/0ccaf7540afe4155a2b14e695b9852d7)

Предлагаю дизейблить кнопки с покемонами, пока запрос обрабатывается

2022-08-26 14:06 UTC, skorobaeus commented
> Предлагаю дизейблить кнопки с покемонами, пока запрос обрабатывается

@nlopin Я задизейблила кнопки на время, которое работает скрипт. Не уверена, что в нужном месте включаю их обратно, правда :D

2022-08-26 14:40 UTC, nlopin approved these changes
Всё круто 🔥

2022-08-26 14:40 UTC, merged