Добавляет доку про объект `Date`
doka-guide/content pull request #3586
Opened 2022-08-19 05:36 UTC by kseniaSs

## Описание

Добавляем доку про `Date`. Расписаны основные фукнции, альтернативы. Также добавила примеры с ISO форматом и с установленной timezone.

Closes #2418

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-08-20 06:53 UTC, nlopin commented on js/date/index.md
> +Также в наследство от UNIX досталось измерение времени. Количество прошедших секунд/минут/часов ведётся от 1 января 1970 года.
Тут не очень понятно, к чему это относится. Может сказать, что внутри Date хранит данные в этом формате? (надо проверить этот факт)

и сказать, что это называется таймстэмп (timestamp)

2022-08-20 06:54 UTC, nlopin commented on js/date/index.md
> +`Date` - объект для работы со временем. В основном используется для отображения и вычисления.
Тут у нас ООП, чтобы работать с `Date` нужно его создать через конструктор, так что я бы говорил, что `Date` — это класс
```suggestion
`Date` - класс для работы со временем. В основном используется для отображения и вычисления.
```

2022-08-20 06:54 UTC, nlopin commented on js/date/index.md
> +Создаём объект даты (обязательно в ISO формате)
ссылочку на ISO формат хочется
```suggestion
Создаём объект даты (обязательно в ISO формате):
```

2022-08-20 06:55 UTC, nlopin commented on js/date/index.md
> +Получаем различные метрики
Метрики как-то не очень в контексте времени. Может попробуем «части даты»

```suggestion
Получаем различные части даты:
```

2022-08-20 06:56 UTC, nlopin commented on js/date/index.md
> +💡 Установленная дата и метод toISOString имеют разные значения из-за timezone автора текста
```suggestion
💡 Установленная дата и метод `toISOString()` имеют разные значения из-за timezone автора текста
```

2022-08-20 06:59 UTC, nlopin commented on js/date/index.md
> +#### Математические операции
```suggestion
### Математические операции
```

2022-08-20 07:00 UTC, nlopin commented on js/date/index.md
> +const options = {
после примера хочется расшифровки, какие опции бывают

2022-08-20 07:00 UTC, nlopin commented on js/date/index.md
> +#### Некорректная время и дата
```suggestion
### Некорректная время и дата
```

2022-08-20 07:01 UTC, nlopin commented on js/date/index.md
> +Date исправляет некорректно введённые данные, но это касается только целых чисел.
из примера непонятно, что я ввел некорректно. Использовал не тот метод?

2022-08-20 07:02 UTC, nlopin commented on js/date/index.md
> +#### Moment
Раз сейчас не рекомендуется использование момента, давай сделаем этот заголовок «Библиотеки» и скажем про рекомендуемые. Я бы указал в первую очередь на day.js или date-fns и всамом конце упомянул бы moment.js фразой, что это раньше было стандартом, но сейчас не используйте

2022-08-20 07:05 UTC, nlopin commented on js/date/index.md
> +- В поддержке браузеров. Intl.DateTimeFormat поддерживается не всеми браузерами. Например, IE10 не поддерживает совсем,
IE уже в могиле, давай не будем даже его упоминать. Если его выкинуть из рассмотрения, то я не вижу причин не использовать `DateTimeFormat` везде где только можно.

2022-08-20 07:06 UTC, nlopin commented on js/date/index.md
> +#### Что использовать Intl.DateTimeFormat или toLocaleDateString ?
Давай это вынесем в твой авторский совет?

2022-08-20 07:16 UTC, nlopin requested changes
Привет! Отличный старт 👍

У меня есть ощущение, что статьи недостаточно, чтобы человек смог использовать `Date` в своих проектах. 

Чтобы пофиксить, давай сделаем список всех методов класса с кратким описанием в разделе «Как пишется» (посмотри, как сделано в [Map](https://doka.guide/js/map/))

По мелочи:
- [ ] завернуть все кусочки кода в тексте в одинарные бэктики
- [ ] timezone → таймзона (надо будет добавить в словарь исключений) и таймстемп

2022-08-20 07:16 UTC, nlopin commented on js/date/index.md
> +<!--
это можно выкинуть

2022-08-20 11:52 UTC, kseniaSs commented
Хорошо, поняла. Поправлю в ближайшее дни, я правда приболела, но за пару дней, думаю, справлюсь

2022-08-24 16:47 UTC, kseniaSs commented
Поправила основные замечания.
Решила убрать блок про библиотеки в небольшой совет, так как информации итак много для прочтения, а это не особо значимый пункт.
Также добавила блок про методы, но алгоритмы не стала расписывать, так как это еще сразу миллионы информации, а она также некритичная, имхо.

2022-08-24 20:40 UTC, nlopin approved these changes
Класс, отличная работа!

Обратил внимание, что в твоем тексте много ручных переносов строк из-за которых текст некрасиво рендерится. Я поправил, чтобы локально у тебя текст не вытягивался в длинные нечитаемые строки, рекомендую включить soft wrap

2022-08-24 20:41 UTC, nlopin commented on .yaspeller.json
> +    "таймзон(е|ы|а|ой|)",
@solarrust тебе ок, если мы такой термин? или часовые пояса лучше?

У тебя в статьях я видел «часовые пояса».

2022-08-25 05:59 UTC, solarrust commented on .yaspeller.json
> +    "таймзон(е|ы|а|ой|)",
Да, в тегах `<input>` и `<time>` мы пишем «часовой пояс». 
Если идти по этому пути, то, по-хорошему, надо и локаль назвать русским словом.

2022-08-25 06:23 UTC, nlopin commented on .yaspeller.json
> +    "таймзон(е|ы|а|ой|)",
никогда не слышал русской версии слова «локаль»

2022-08-25 07:03 UTC, solarrust commented on .yaspeller.json
> +    "таймзон(е|ы|а|ой|)",
Up to you 🤗

2022-08-25 16:41 UTC, merged

2022-08-25 17:05 UTC, nlopin commented
!()[https://media.giphy.com/media/AiF8ZsTESrDwRjEcIU/giphy.gif]