Меняет @skorobaeus должность
doka-guide/content pull request #3587
Opened 2022-08-19 12:48 UTC by solarrust

Правит должность у @skorobaeus так, чтобы она совпадала с реальностью.

2022-08-19 14:26 UTC, skorobaeus approved these changes
<3

2022-08-19 14:34 UTC, furtivite approved these changes
💛

2022-08-19 19:56 UTC, nlopin approved these changes

2022-08-19 23:22 UTC, igsekor requested changes

2022-08-19 23:22 UTC, igsekor commented on pages/about/index.md
> +- <!-- yaspeller ignore:start -->[Саша Беспоясов](/people/bespoyasov/)<!-- yaspeller ignore:end --> — за статьи и ревью.
```suggestion
- [<!-- yaspeller ignore:start -->Саша Беспоясов<!-- yaspellerignore:end -->](/people/bespoyasov/) — за статьи и ревью.
```
Вот так будет правильно собираться сайт

2022-08-20 12:41 UTC, solarrust commented on pages/about/index.md
> +- <!-- yaspeller ignore:start -->[Саша Беспоясов](/people/bespoyasov/)<!-- yaspeller ignore:end --> — за статьи и ревью.
И в итоге тесты валяться после этой правки 🤔

2022-08-20 17:14 UTC, igsekor commented on pages/about/index.md
> +- [<!-- yaspeller ignore:start -->Саша Беспоясов<!-- yaspellerignore:end -->](/people/bespoyasov/) — за статьи и ревью.
```suggestion
- [<!-- yaspeller ignore:start -->Саша Беспоясов<!-- yaspeller ignore:end -->](/people/bespoyasov/) — за статьи и ревью.
```

2022-08-20 17:15 UTC, igsekor requested changes
Вот так всё должно быть хорошо

2022-08-20 17:16 UTC, igsekor approved these changes

2022-08-20 17:19 UTC, merged