Добавляет статью про сравнение клиентского и серверного рендеринга
doka-guide/content pull request #3608
Opened 2022-08-28 18:15 UTC by vtcaregorodtcev

## Описание

Статья про сравнение CSR и SSR, с теоретической и практической точек зрения.

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-08-30 06:04 UTC, nlopin commented
Привет! Спасибо за статью. Расскажи, пожалуйста, чем она отличается от статьи о [видах веб приложений](https://doka.guide/js/web-app-types/)? Что должен читатель вынести из неё?

2022-08-30 06:56 UTC, vtcaregorodtcev commented
@nlopin привет!

Сори, не увидел статью раньше. В целом статьи пересекаются немного, но есть отличия. 

в существующей статье
- про плюсы и минусы говорится вскользь, без акцента почему появился тот или иной способ 
- используется отличный от flow chart график для описания взаимодействия клиента и сервера (мне кажется в разрезе времени именно flow chart лучше подходит, чтобы сравнивать на каких этапах что происходит)
- говорится про производительность, но про метрики lighthouse, например, не упоминается
- отсутствует блок с практикой (в добавляемой статье есть небольшой практический блок как переизобрести csr и ssr, и какие проблемы для этого нужно будет решить)

2022-09-01 10:35 UTC, nlopin commented
Привет! Сегодня вернусь с идеями, как нам встроить эту статью и не повториться

2022-09-01 19:57 UTC, nlopin commented
@vtcaregorodtcev привет! 

Перечитал твою статью и наши материалы по теме.

1. Предлагаю сосредоточиться именно на практической части статьи. В ней очень много полезного, но из-за объема статьи, много вещей подразумевается, а хочется там разжевать поподробнее.
1. Часть про плюсы и минусы CSR и SSR перенести в статью про виды веб-приложений.
1. В целом отжать статью — сократить формулировки, сделать текст чётче (оставлю комментарии)

2022-09-01 20:41 UTC, nlopin requested changes
думаю получится охрененно

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +## Краткая история возникновения
У нас есть структура, которой мы придерживаемся в материалах. Для статей они минимальна — первым идёт раздел «Кратко» который содержит TL;DR статьи

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Фронтенд бросает в разные стороны последние лет 10, что нельзя охарактеризовать как плохо или хорошо. Доступность образования в сфере IT и в частности веб разработки повысило число желающих принять а
Давай этот раздел опустим и сошлёмся на статью о видах веб-приложений.

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +![Последовательность шагов при клиентском рендеринге](./images/csr-flow.png)
я думаю мы в этой flow диаграме неточны. Клиенту показывается страница, просто она пустая. Получается, нам нужно сделать примерно, как `ssr-flow.png`, но вместо «пользователь видит сайт» будет «пользователь видит пустую старницу», а последним пунктом «пользователь видит сайт и может по нему кликать»

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Данный подход имел один большой плюс. При такой расстановке сил была возможна параллельная разработка приложения. Можно было собрать две команды и начать делать приложение с разных концов, согласовыв
Тут нужно уточнить. Почему в SSR нельзя параллельно разрабатывать?

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Но это был организационный момент. С технической же стороны, данный подход приносил больше минусов чем плюсов.
Плюсы тоже хочется увидеть.

* проще разработка
* пользователь ждёт, но потом приложение сразу доступно для работы
* проще сделать поддержку offline?

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +- Поскольку клиент брал на себя больше обязанностей, нужно было грузить больше кода и первоначальная загрузка скриптов блокировала дальнейшую загрузку данных и собственно отображение контента. Пользо
Давай отожмём тут. Что-то типа:
```suggestion
- Браузеру нужно загрузить больше кода. Так как страница рисуется из JavaScript, нужно его загрузить перед тем, как пользователь сможет увидеть содержание страницы. До этого нужно смотреть на белый экран, пока все загрузится.
```

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +- Поскольку теперь фронтенд и бэкенд делали отдельно друг от друга, их также деплоили отдельно. Запросы к серверному АПИ могли быть очень долгими и нужно было отдельно решать эту задачу.
Этот пункт мне показался притянутым. Как связаны время запросов к API и CSR? Из гибридных приложений или после гидратации я тоже могу пульнуть запрос и он будет обрабатываться долго. Кажется это проблема API, а не того, что мы рендерим страницу в браузере

Может минус — это бОльшее количество запросов по сранению с SSR? типа в SSR мы можем данные уже получить и встроить в html. После гидратации нам не нужно этот запрос отправлять

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +- Также, поскольку клиент делал все сам, то это больно било по SEO оптимизации. Роботы и веб пауки, которые пытались прочитать странички приложения, на все запросы получали просто index файл без како
тут тоже надо отжать. Вариант:
```suggestion
- Ухудшение поисковой оптимизации. Для индексации в поиковиках используются роботы, которые читают страницу и индексируют её содержимое. Такие роботы обычно смотрят только на статический контент и не запускают JavaScript. В CSR робот не может понять содержание страницы, поэтому для команий, которым важно быть высоко в поиске CSR не подходит.
```

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Поделав приложения в таком состоянии еще 5-6 лет, разработчики пришли к мысли что это можно исправить, вернув все как было 🤡 Но к тому моменту фронтенд и бэкенд уже сильно обособлились друг от друга,
Мне кажется причина не совсем в этом. Причина скорее в том, что SSR не вписывается в микросервисную архитектуру. Поэтому мы пишем свой микросервис, который отвечает только за SSR. Вообще предлагаю этот абзац убрать, потому что наша задача — показать, что есть.

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Какие плюсы мы получаем при этом?
Какие минусы получаем?

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Мы не будем использовать готовые инструменты так как мы знаем что они имеют свойство заканчиваться, а нам нужно разобраться именно в концепции, без привязки к конкретному решению, поэтому инструмент
Кажется три абзаца можно сжать до: «Давайте напишем свой мини-фреймворк, который будет уметь рендерить CSR и SSR . Так мы на практике разберёмся, какая между ними разница»

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Так вот, почему бы нам сразу не взять некоторое подобие такого дерева и сказать, что это уже синтаксис нашего псевдофреймворка, если в итоге все всегда к этому и сводится?
Я не совсем понял подводку. Если мы хотим сказать, что наш фреймворк будет выглядеть, как показано ниже, то можно не рассказывать про бабель и AST. Мы рассчитываем на начинающих разработчиков и если уж и рассказывать про AST, то абзаца на это явно не хватит.

Думаю, если просто сказать, «давайте представим HTML в виде объектов JS»

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Пример приложения и реализация псевдофреймворка доступна [по этой ссылке](./demo.zip). Нужно распаковать архив и установить пакеты командой `pnpm i`. Для этого, конечно, нужно чтобы [пакетный менедже
мы же можем и в виде демки сделать, как ты считаешь?

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +## Переизобретаем CSR
```suggestion
## Реализуем клиентский ренденринг, CSR
```

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Для приложения с клиентским рендерингом нам потребуется всего два файла. Страница index.html и сам код нашего приложения. Мы будем использовать _dist/javascript_ файл для создания псевдонагрузки, пос
>Мы будем использовать _dist/javascript_ файл для создания псевдонагрузки, поскольку наш фреймворк весит всего несколько сотен байт.

с третьего раза понял. Типа у нас куча джаваскрипта только для того, чтобы заметить задержку? Есть ли ещё какой-то способ это сделать?

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Согласитесь, код выглядит знакомо? Давайте теперь реализуем функцию _render()_.
Для некоторых читателей это может не выглядеть знакомо. Давай лучше расскажем, что функция `render` должна делать.

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +В функции _render()_ воспользуемся старой доброй рекурсией, чтобы пробежать все узлы нашего дерева и создать из них DOM элементы, после чего на финальном этапе, добавим нашу структуру в главный элеме
тут хочется более детального рассказа. Представь, что объясняешь джуну. Нужно рассказать чуть ближе к коду, менее абстрактно

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +На этом наше приложение закончено. Из корня скачанной директории запускаем команду `pnpm csr`, переходим на `localhost:8080` и видим наше рабочее приложение. Все события работают и приложение функцио
можно ещё сказать, чтобы перед запуском читатель открыл девтулзы и смотрел на html-код

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +![Пример работы приложения при CSR](./images/app-example.png)
давай видосик лучше сделаем? помочь?

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Теперь очередь серверного рендеринга. Для этого напишем небольшой сервер на [fastify](https://www.fastify.io/), который будет отдавать нам верстку в виде строки и соотвественно нам также понадобится
> который будет отдавать нам верстку в виде строки

разве он не отдаёт нам просто вёрстку? типа `index.html`? в CSR нам базовую вёрстку вроде тоже в виде строки отдают 🤔

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Изначально ни _document_ ни _window_ на NodeJs не реализованы, поэтому если мы запустим просто _render()_ функцию и попытаемся получить из этого строку, у нас ничего не выйдет.
Мне кажется тут нужно чуть довернуть, чтобы стало понятнее → В реализации CSR мы полагаемся на DOM API, который есть только в браузере, а на его сервере нет. Воспользуемся библиотекой JSDOM...

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Также мы немного модифицировали саму функцию _render()_, добавив возможность динамически запрашивать текущую имплементацию _document_. Такой код будет работать на любой платформе.
тут хочется чуть побольше, зачем нам это понадобилось. Но если слишком сложно, то можно забить

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Теперь, если запустить команду `pnpm ssr` и перейти на `localhost:4321` то мы снова увидим наше приложение, но оно потеряло интерактивность. Все дело в том, что нам нужно провести гидратацию приложен
Боюсь не все поймут, что такое «завести интерактивность заново». Давай в явном виде проговорим, что на сервере мы только отрисовали html, а события нужно навешивать уже в браузере. Вот для этого нужна гидратация.

2022-09-01 20:41 UTC, nlopin commented on js/csr-vs-ssr/index.md
> +Далее, чтобы убедиться, что SSR действительно нам помогает раньше увидеть контент, запустим проверку _Lighthouse_ из Google Chrome DevTools и сравним метрику FCP (First Contentful Paint) между разным
Это огонь

2022-09-02 08:54 UTC, vtcaregorodtcev commented
@nlopin привет! Спасибо за ревью!

Хотел уточнить по поводу новой структуры. 

1. Мы хотим из блока про _"CSR под капотом"_ и блока _"SSR под капотом"_ взять список плюсов и минусов и добавить в статью про виды веб-приложений? 
2. Что тогда сделать с графиком? Исправить немного и также в оригинальную статью перенести? 
3. Тогда в добавляемой статье оставляем такие блоки как (Кратко, Реализация CSR, Реализация SSR, Как проверить)?

По исправлениям, наверно, выпаду на пару недель, после отпуска все доделаю :)

2022-09-05 11:31 UTC, nlopin commented
Да, всё верно. 

График я предлагаю оставить здесь, чтобы у нас в начале всё-таки был небольшой контекст того, что мы тут делаем. 

По структуре думаю так:
* Кратко
* Вводная часть с графиками
* Пишем CSR
* Пишем SSR
* Смотрим метрики

2022-10-19 11:38 UTC, nlopin commented
@vtcaregorodtcev вернёшься дополировать статью или нам её взять на себя?

2022-10-19 18:39 UTC, vtcaregorodtcev commented on js/csr-vs-ssr/index.md
> +Данный подход имел один большой плюс. При такой расстановке сил была возможна параллельная разработка приложения. Можно было собрать две команды и начать делать приложение с разных концов, согласовыв
уйдет в статью про типы приложений

2022-10-19 18:48 UTC, vtcaregorodtcev commented
@nlopin привет!

По оставленным комментариям переработал текст, про плюсы и минусы убрал часть, как договаривались перенесем в типы приложений.

2022-10-19 18:50 UTC, vtcaregorodtcev commented on js/csr-vs-ssr/index.md
> +Пример приложения и реализация псевдофреймворка доступна [по этой ссылке](./demo.zip). Нужно распаковать архив и установить пакеты командой `pnpm i`. Для этого, конечно, нужно чтобы [пакетный менедже
не совсем представляю как именно в виде интерактивной демки сделать, так как у нас еще серверная часть есть

2022-10-24 18:22 UTC, vtcaregorodtcev commented
> ## Чек-лист для новой статьи
> ### Метаданные
> * [x]  Код в поле `title` завёрнут в бэктики
> * [x]  Есть поле `description` с описанием
> * [x]  Проставлен тег `article`
> * [x]  Поле `keywords` содержит ключевые слова, которых нет в тексте статьи
> * [x]  В поле `authors` указан автор. Файл автора есть в папке _people_
> * [ ]  В поле `related` есть ссылки на материалы Доки, интересные в контексте данного (не более трёх)
> 
> ### Статья
> * [x]  Структура совпадает с [шаблоном](https://github.com/doka-guide/content/blob/main/docs/examples/article.md)
> * [x]  Демки написаны по [рекомендациям](https://github.com/doka-guide/content/blob/main/docs/demos/index.md)
> * [x]  У картинок есть описание в `alt`, у фреймов демок название в `title`
> * [x]  Статья добавлена в содержание раздела
> * [x]  Для статьи указаны материалы Доки, интересные для дальнейшего чтения

2022-10-29 18:33 UTC, vtcaregorodtcev commented
@nlopin привет!

Будет время посмотреть?

2022-10-29 20:53 UTC, HellSquirrel commented
@vtcaregorodtcev  приветик. Я посмотрю вместо Коли (на следующей неделе приблизительно)

2022-10-29 20:54 UTC, HellSquirrel commented
@vtcaregorodtcev  приветик. Я посмотрю вместо Коли (на следующей неделе приблизительно)

2022-11-02 09:00 UTC, HellSquirrel reviewed
Первая порция правок и предложений :) Будет еще

2022-11-02 09:00 UTC, HellSquirrel commented on js/csr-vs-ssr/index.md
> +1. Пользователь хочет открыть приложение и вводит его адрес в строке браузера.
Можно использовать ленивую нумерацию (всегда ставить 1)

2022-11-02 12:00 UTC, HellSquirrel reviewed
Добавила вторую часть правок и предложений

2022-11-04 08:27 UTC, HellSquirrel commented
@vtcaregorodtcev глянь правочки :)

2022-11-04 08:28 UTC, vtcaregorodtcev commented
> @vtcaregorodtcev глянь правочки :) 

Да, да, на выходных постараюсь поправить)

2022-11-19 16:02 UTC, vtcaregorodtcev commented
Привет!

сори, не смогу, к сожалению, закончить статью. Не хватает сейчас времени. Удалю пока, чтобы глаз мозолил.

2022-11-19 16:02 UTC, closed without merging