Редактирует доку про событие keydown
doka-guide/content pull request #3617
Opened 2022-09-01 16:21 UTC by Inventoris

#1321

Перебрал доку, в итоге почти всё поменял. Автора и контрибьютеров не трогать? 

По самой доке:

- Убрал всё про `keyup`;
- Поменял главу «Как понять». Есть предложение сделать issue на тему `Свойства и методы объекта события`, например, `Свойства и методы объекта события KeyboardEvent`. Раздел как раз и был об этом, а не про понимание этого конкретного свойства, так что я решил сократить;
- Переделал пример, поскольку он, на мой взгляд, слишком мудрёный и при этом не показывает смысл события, а именно что при зажатии оно происходит и не прекращается, как keyup.

2022-09-05 11:26 UTC, nlopin commented on js/element-keydown/index.md
> +[Событие](/js/events/) `keydown` фиксирует момент нажатия клавиши ещё до того, как эта клавиша будет отпущена, что, по сути, является первой фазой нажатия. Продолжением является событие `keyup` — мом
нужна ссылка на `keyup`

2022-09-05 11:28 UTC, nlopin requested changes
Нужно добавить статью в оглавление `/js/index.md` в раздел с событиями

Давай создадим ишью для описание `KeyboardEvent`, хорошая идея

2022-09-05 11:28 UTC, nlopin commented on js/element-keydown/index.md
> +[Событие](/js/events/) `keydown` фиксирует момент нажатия клавиши ещё до того, как эта клавиша будет отпущена, что, по сути, является первой фазой нажатия. Продолжением является событие `keyup` — мом
Предлагаю убрать про первую фазу. 
```suggestion
[Событие](/js/events/) `keydown` фиксирует момент нажатия клавиши ещё до того, как эта клавиша будет отпущена. Продолжением является событие `keyup` — момент, когда клавиша будет отпущена.
```

2022-09-05 15:17 UTC, Inventoris commented
Добавил ишью #3630

2022-09-05 19:33 UTC, nlopin approved these changes
Супер, сливаем

2022-09-05 19:34 UTC, merged

2023-02-19 14:59 UTC, skorobaeus commented
=\