Добавляет доку про skip-link
doka-guide/content pull request #3777
Opened 2022-09-14 20:29 UTC by xpleesid

Closes #2985

2022-09-15 09:30 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +description: "Удобный пропуск ссылок при навигации с помощью клавиатуры"
```suggestion
description: "Удобный пропуск ссылок при навигации с помощью клавиатуры."
```

2022-09-15 12:17 UTC, TatianaFokina requested changes
Привет! Огромное спасибо за такую полезную доку, да ещё за такую оперативность! 🤗

Оставила комментарии и предложения по улучшению. В основном причесала текст и добавила ссылки.

От тебя требуется сделать ещё более крутыми демки и довить немного уточнений, если хочешь, на основе моих комментариев.

Ещё хочу спросить о том, что думаешь насчёт того, чтобы не склонять слово скип-линк? Кажется, что это не самая подходящая транслитерация для склонений. Если не против, то тогда можешь удалить исключение из спелера и заменить термин в тексте.

2022-09-15 12:17 UTC, TatianaFokina commented on a11y/skip-link/demos/basic/index.html
> +</html>
Начала приводить всё к стилям доки, поменяла цвета, добавила недостающие стили, включая стиль с цветом для кнопки, выровняла всё по центру горизонтальной оси, так как в Доке принято так делать.

Можешь, пожалуйста, подправить всё остальное? Нужно:
- Добавить `<main>`, навесить `id` на него.
- Добавить в `<main>` заголовок первого уровня и завернуть текст в `<p>`.
- Скопировать стили для кнопки и полей — [Форма в сборе](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D0%BF%D0%BE%D0%BB%D1%8F-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0) и [кнопки](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8).
- Можно привести меню к рекомендуемым стилям, если хочешь — [Навигация](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D1%8F).
- Избавиться от `</br>` и паддингов у `<section>`, это не очень хорошая практика.
- Добавить вспомогательные контейнеры и отступы между ними в помощью `margin` вместо `</br>`.

Ещё было бы клёво, если бы демка была с более реальными данными. Можно скопировать немного текста из любимой статьи на Википедии или что-то более забавное написать. И такая же история с полем и кнопкой. Пусть это будет электронная почта и подписка или ещё что-то.

Когда подправишь эту демку, то можно будет легко перенести это всё во вторую со ссылкой 🙂

2022-09-15 12:17 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +Skip links (далее — скип-линки) — специальный элемент на странице, который позволяет быстро перейти к контенту при использовании клавиатуры, пропустив блок с навигацией.
Можешь ещё дополнить, что skip link может вести не только к основному содержимому страницы, но и к другой навигации или области поиска. Но главное, чтобы таких ссылок было не очень много, максимум 2–3.

2022-09-15 12:17 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +<img src="./images/github.png" alt="Скип-линка в интерфейсе GitHub" width="826" height="192">
```suggestion
<img src="/images/github.png" alt="Скип-линка в интерфейсе GitHub" width="826" height="192">
```

2022-09-15 17:10 UTC, xpleesid commented
@TatianaFokina поправил, спасибо за комменты! насчет скип-линки, мне кажется правильнее будет именно так оставить. по крайней мере, чаще всего я слышал по поводу ссылок именно такие склонения ("дай линку", "по этой линке ничего нет"). но если это режет слух, то можно убрать склонения, мне не принципиально :)

2022-09-16 10:46 UTC, TatianaFokina reviewed
Всё почти идеально, спасибо за исправления и дополнения!

Кажется, что слишком режет глаз склонение линк :( Если не сложно, можешь всё же везде использовать скип-линк или английский термин?

Добавила ещё больше лоска демкам, расставила новые ссылки и слегка поправила текст. Посмотри всё ли хорошо с демками, и можно будет мёрджить.

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/demos/basic/index.html
> +</html>
Слегка поправила разметку и в этой демке, и в следующей. Добавила вспомогательные классы для формы, недостающие стили, стили для мобилок, слегка уменьшила текст, а ещё добавила ориентир формы.

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/demos/with-skip-link/index.html
> +</html>
```suggestion
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Пример со скип-линкой — Skip link — Дока</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
  <style>
    *, *::before, *::after {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      min-height: 100vh;
      padding: 50px;
      display: flex;
      justify-content: center;
      font-family: Roboto, sans-serif;
      font-size: 20px;
      background-color: #18191c;
      color: #FFFFFF;
    }

    h1 {
      margin-bottom: 17px;
      font-weight: 500;
      font-size: 2.2rem;
    }

    p {
      margin: 7px 0;
      font-size: 1.2rem;
      line-height: 1.4;
    }

    ul {
      display: flex;
      align-items: center;
      list-style: none;
    }

    li {
      height: 40px;
      line-height: 40px;
      margin: 0 20px;
    }

    li:first-child {
      margin-left: 0;
    }

    main {
      margin-top: 40px;
    }

    a {
      border-radius: 3px;
      color: inherit;
      -webkit-text-decoration-color: #10F3AF;
      text-decoration-color: #10F3AF;
      text-decoration-thickness: 2px;
      transition: background-color 0.2s linear;
    }

    a:hover, a:focus {
      color: #000000;
      background-color: #10F3AF;
      transition: background-color 0.2s linear;
      outline-width: 0;
    }

    .button {
      display: block;
      width: 100%;
      border: 2px solid transparent;
      border-radius: 6px;
      padding: 9px 15px;
      color: #000000;
      font-size: 18px;
      font-weight: 300;
      font-family: inherit;
      transition: background-color 0.2s linear;
    }

    .button:hover {
      background-color: #FFFFFF;
      cursor: pointer;
      transition: background-color 0.2s linear;
    }

    .button:focus-visible {
      border: 2px solid #FFFFFF;
      outline: none;
    }

    .button:focus {
      border: 2px solid #FFFFFF;
      outline: none;
    }

    .button-aqua {
      background-color: #10F3AF;
    }

    form {
      width: 600px;
      margin-top: 30px;
    }

    input {
      width: 100%;
      margin-bottom: 25px;
      border: 1px solid #FFFFFF;
      border-radius: 6px;
      padding: 10px 15px;
      background-color: transparent;
      color: #FFFFFF;
      font-size: 18px;
      font-weight: 300;
      font-family: inherit;
      -webkit-appearance: none;
      appearance: none;
    }

    input:focus {
      border-color: #10F3AF;
      outline: none;
    }

    label {
      margin-right: 55px;
      font-size: 24px;
      font-weight: 500;
      line-height: 1;
    }

    .form-row {
      display: flex;
      justify-content: space-between;
    }

    .container {
      width: 350px;
    }

    .skip-link {
      display: block;
      position: absolute;
      top: 0;
      left: 0;
      padding: 10px 15px;
      background: #10F3AF;
      transform: translateY(-100%);
    }

    .skip-link:focus {
      transform: translateY(0);
      color: #18191c;
    }

    @media (max-width: 768px) {
      body {
        padding: 30px;
      }

      ul {
        flex-direction: column;
      }

      li:first-child {
        margin-left: 20px;
      }

      label {
        display: inline-block;
        margin: 0 0 10px;
      }

      .form-row {
        display: block;
      }

      form, .container {
        width: 100%;
      }
  </style>
</head>
<body>
  <div>
    <a class="skip-link" href="#main">
      Перейти к контенту
    </a>
    <nav>
      <ul>
        <li>
          <a href="#">Главная</a>
        </li>
        <li>
          <a href="#">О леммингах</a>
        </li>
        <li>
          <a href="#">Фотографии</a>
        </li>
        <li>
          <a href="#">О нас</a>
        </li>
        <li>
          <a href="#">Контакты</a>
        </li>
      </ul>
    </nav>
    <main id="main">
      <h1>Лемминги</h1>
      <p>
        Лeмминги — группа из нескольких близкородственных родов подсемейства полёвковых (Arvicolinae) семейства хомяков (Cricetidae) отряда грызунов.
        К леммингам близки пеструшки.
        Лемминг питается семенами, листьями и корнями.
        В спячку он не впадает и поэтому летом припрятывает еду в расщелинах земли, а зимой роет в снегу ходы и отыскивает свои запасы.
        Лемминги весьма плодовиты, у самки бывает от 3 до 4 помётов в год, в каждом по 5-6 детёнышей.
      </p>
      <p>
        Интересуетесь леммингами? Оставьте свою почту, и мы будем каждый день присылать вам интересные факты про леммингов.
      </p>
      <form>
        <div class="form-row">
          <label for="input">
            Email:
          </label>
          <div class="container">
            <input type="email" id="input"></input>
            <button class="button button-aqua">Подписаться на рассылку</button>
          </div>
        </div>
      </form>
    </main>
  </div>
</body>
</html>
```

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +Skip links (далее — скип-линки) — специальный элемент на странице в виде гиперссылки, который позволяет быстро перейти к контенту при использовании клавиатуры, пропустив блок с навигацией. Обычно это
```suggestion
Skip links (далее скип-линки) — специальные элементы на странице в виде гиперссылок, которые помогают быстро перейти к контенту при использовании клавиатуры, пропустив блок с навигацией.

Обычно скип-линку используют для пропуска меню навигации вверху страницы, но можно добавлять её в любые места. Например, чтобы из начала секции с комментариями сразу перейти к полю ввода нового комментария. Главное — не переборщить. Большое число ссылок может запутать пользователя.
```

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +Skip links (далее — скип-линки) — специальный элемент на странице в виде гиперссылки, который позволяет быстро перейти к контенту при использовании клавиатуры, пропустив блок с навигацией. Обычно это
Разбила на два абзаца и слегка причесала текст. Всё же, для skip links использовать множественное число, а когда skip link — единственное.

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +<img src="images/github.png" alt="Скип-линка в интерфейсе GitHub" width="826" height="192">
```suggestion
![Скип-линка в интерфейсе GitHub](images/github.png)
```

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +<img src="images/github.png" alt="Скип-линка в интерфейсе GitHub" width="826" height="192">
Что-то сама пропустила этот момент. В текст вставляем картинки просто как в `markdown`.

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +<iframe title="Пример с простой навигацией без skip link" src="demos/basic/" height="600" sandbox></iframe>
```suggestion
<iframe title="Пример с простой навигацией без skip link" src="demos/basic/" height="610"></iframe>
```

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +<iframe title="Пример со скип-линкой" src="demos/with-skip-link/" height="600" sandbox></iframe>
```suggestion
<iframe title="Пример со скип-линкой" src="demos/with-skip-link/" height="610"></iframe>
```

2022-09-16 10:46 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +<iframe title="Пример с простой навигацией без skip link" src="demos/basic/" height="600" sandbox></iframe>
Убрала атрибут и слегка изменила размер демки, чтобы не было скрола.

2022-09-16 20:20 UTC, xpleesid commented
@TatianaFokina  Готово

2022-09-17 06:39 UTC, TatianaFokina approved these changes

2022-09-17 06:39 UTC, TatianaFokina commented on .yaspeller.json
> +    "псевдосписок",
```suggestion
    "псевдоспис(ок|ка|)",
```

2022-09-17 06:39 UTC, TatianaFokina commented on .yaspeller.json
> +    "линк(и|ой|)",
```suggestion
    "линк(и|)",
```

2022-09-17 06:39 UTC, TatianaFokina commented on a11y/skip-link/demos/with-skip-link/index.html
> +  <title>Пример со скип-линкой — Skip link — Дока</title>
```suggestion
  <title>Пример со скип-линк — Skip link — Дока</title>
```

2022-09-17 06:39 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +```
```suggestion
```html
<body>
<a class="skip-link" href="#main">
  Перейти к контенту
</a>
<!-- Навигация -->
<main id="main">
  <!-- Остальной контент страницы -->
</main>
</body>
```
```

2022-09-17 06:39 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +```
```suggestion
```css
.skip-link {
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  padding: 10px 15px;
  background: #F498AD;
  transform: translateY(-100%);
}
```
```

2022-09-17 06:39 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +```
```suggestion
```css
.skip-link:focus {
  transform: translateY(0);
}
```
```

2022-09-17 06:39 UTC, TatianaFokina commented on a11y/skip-link/index.md
> +Когда ссылка в фокусе, покажем её, вернув дефолтное значение `transform`:
```suggestion
Когда ссылка в фокусе, покажем её, вернув значение по умолчанию `transform`:
```

2022-09-17 06:48 UTC, TatianaFokina commented
Большое спасибо за замечательную доку 🙂

2022-09-17 06:48 UTC, merged