Добавляет доку по Intersection Observer
doka-guide/content pull request #3780
Opened 2022-09-16 07:34 UTC by zizi-shoot

## Описание

Closes #2539

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-09-20 19:37 UTC, nlopin commented
Привет, извиняюсь, что долго нет ответа. Был в отпуске

2022-09-25 15:57 UTC, qweered approved these changes

2022-09-25 18:19 UTC, nlopin requested changes
очень мясистая статья вышла! отметил важные структурные моменты

2022-09-25 18:19 UTC, nlopin commented on js/intersection-observer/index.md
> +## Как пишется
В «Как пишется» нужно рассказать про сигнатуру метода. Ты это делаешь ниже. Давай мы этот параграф поднимем в раздел «Пример»

Тогда «Какие есть параметры» можно будет убрать.

2022-09-25 18:19 UTC, nlopin commented on js/intersection-observer/index.md
> +Наблюдатель создаётся конструкцией `new IntersectionObserver(callback, options?)`
Мне кажется, что сейчас мы упускаем главное. Первичен обзёрвер и про него стоит рассказывать в начале

2022-09-25 18:19 UTC, nlopin commented on js/intersection-observer/index.md
> +## Как понять
Очень классно рассказаны практические моменты. Мне не хватает принципиальной схемы того, как работает паттерн наблюдатель. Давай коротко расскажем и дадим ссылку на doka.guide/js/design-patterns-behaviorial/#nablyudatel

А то сейчас мы начинаем будто с середины

2022-09-25 18:19 UTC, nlopin commented on js/intersection-observer/index.md
> +## Преимущества
```suggestion
### Преимущества
```

содержание раздела больше похоже на применение. может переименуем?

2022-10-03 19:21 UTC, nlopin commented
@zizi-shoot понимаю, что сейчас тяжелое время. Дай знать, если хочешь додделать сам

2022-10-03 19:29 UTC, zizi-shoot commented
> @zizi-shoot понимаю, что сейчас тяжелое время. Дай знать, если хочешь додделать сам

@nlopin  привет! Не поверишь, но буквально 20 мин назад сел, чтобы пройтись по твоим замечаниям и исправить. Извиняюсь, что молчал так долго, думаю причины объяснять не надо...

2022-10-05 18:28 UTC, nlopin approved these changes
когонь

2022-10-05 18:37 UTC, merged