Добавляет статью о css функции max()
doka-guide/content pull request #3885
Opened 2022-10-08 19:14 UTC by denisputnov

## Описание

Добавляет новую статью о `css` функции `max()`

Closes #2497

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-10-10 11:32 UTC, TatianaFokina reviewed
Спасибо за доку и такую наглядную демку. Оставила пару предложений по правкам.

2022-10-10 11:32 UTC, TatianaFokina commented on css/max/index.md
> +В примере выше использованы значения `max(4.5vw, 18px)`, что буквально означает: размер текста составляет 4.5% ширины [вьюпорта](/css/vw-vh/#vw), но не менее 18 px. Чем больше ширина экрана, тем боль
```suggestion
В примере использованы значения `max(4.5vw, 18px)`. Это означает, что размер текста составляет 4.5% от ширины [вьюпорта](/css/vw-vh/#vw), но не менее 18 px. Чем больше ширина экрана, тем больше текст.
```

2022-10-10 11:32 UTC, TatianaFokina commented on css/max/index.md
> +💡 Очень удобно с помощью функции `max()` ограничивать ширину компонента в зависимости от ширины родителя.
```suggestion
💡 С помощью функции `max()` очень удобно ограничивать ширину компонента в зависимости от ширины родителя.
```

2022-10-10 11:32 UTC, TatianaFokina commented on css/max/index.md
> +В примере выше использованы значения `max(4.5vw, 18px)`, что буквально означает: размер текста составляет 4.5% ширины [вьюпорта](/css/vw-vh/#vw), но не менее 18 px. Чем больше ширина экрана, тем боль
Лучше стараться избегать в текстах указание на низ, верх, право, лево и так далее. Для пользователей, которые слушают интерфейсы, это очень неудобный способ подачи материала. И без этого слова тут вполне понятно, о чём речь.

2022-10-10 11:32 UTC, TatianaFokina commented on css/max/index.md
> +## Как это понять
```suggestion
## Как понять
```

2022-10-10 12:18 UTC, TatianaFokina commented on css/max/demos/view/index.html
> +    <span class="current"></span>
Может сделаем этот элемент с результатом `<output>`?

2022-10-14 11:32 UTC, skorobaeus commented on css/max/demos/view/index.html
> +    }
```suggestion
    .rectangle {
      height: 200px;
      width: 460px;
      color: #ffffff;
      background-color: #2E9AFF;
      display: grid;
      font-size: max(4.5vw, 18px);
      place-content: center;
      margin: 16px 0;
    }
```

Скругление не нужно.

2022-10-14 11:36 UTC, skorobaeus commented on css/max/demos/view/index.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap">
```suggestion
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&family=Roboto+Mono&display=swap">
```

2022-10-14 11:38 UTC, skorobaeus commented on css/max/demos/view/index.html
> +      font-family: "Roboto Mono", monospace;
```suggestion
      font-family: "Roboto", sans-serif;
```

2022-10-14 11:39 UTC, skorobaeus commented on css/max/demos/view/index.html
> +      font-size: 0.8em;
```suggestion
      font-size: calc(1em - 1px);
      font-family: "Roboto Mono", monospace;
```

2022-10-14 11:42 UTC, skorobaeus commented on css/max/demos/view/index.html
> +    }
```suggestion
    input {
      margin: auto;
      display: block;
      width: 300px;
      cursor: grab;
    }
```

2022-10-14 11:44 UTC, skorobaeus requested changes
Привет! Спасибо за доку! Я причесала стили демки :)

2022-10-14 12:02 UTC, denisputnov commented
Спасибо за комментарии!
Поправлю всё до конца за эти выходные

2022-10-15 10:38 UTC, TatianaFokina approved these changes

2022-10-16 14:20 UTC, skorobaeus approved these changes

2022-10-16 21:19 UTC, denisputnov commented
Привет, от меня требуются ещё какие-то правки?

2022-10-17 07:40 UTC, merged

2022-10-17 07:40 UTC, TatianaFokina commented
Спасибо ещё раз за доку!