Добавляет .gitignore
doka-guide/content pull request #3909
Opened 2022-10-14 16:43 UTC by StarHamster

## Описание

Closes #3908

2022-10-17 13:37 UTC, HellSquirrel commented
Приветик! Я думаю что нам пока не нужен .gitignore
Папки, которые ты предлагаешь игнорировать в некоторых случаях полезно добавлять в git
Я обычно добавляю все IDE-специфическое в глобальный .gitignore, это можно сделать так:
* создаешь где-нибудь файлик, например `~/.gitignore`. В него складываешь все, что хочется глобально заигнорить
* выполняешь команду `git config --global core.excludesfile [путь до твоего файлика]`

2022-10-17 13:56 UTC, StarHamster commented
Давай обсудим это в ишью) Было бы круто услышать автора запроса

2022-10-18 15:40 UTC, kxnkxv commented
Глобальный gitignore это не повсеместная практика, её мало кто использует.
Я лично первый раз услышал про глобальный gitignore, за все те годы, сколько я работаю.
Давайте делать "как у всех"?

2022-10-19 07:44 UTC, solarrust commented
Привет!
В редакции горела жаркая дискуссия, мы разделились на два лагеря, каждый стоял до конца на своём.
Но всё же аргументы стороны ЗА оказались более весомыми. 
Было решено всё же добавить гитигнор в репозиторий контента.

Но давай сделаем его максимально подробным, чтобы позже не возвращаться к нему.
Можно взять за основу тот гитигнор, что генерирует GitHub автоматом, и посмотреть, всё ли из списка релевантно для нас. Как минимум нужно добавить Thumbs.db, node_modules.

2022-10-19 09:13 UTC, igsekor requested changes
Предлагаю такой вариант. Наверное, придётся ещё дополнить чем-то. Сложно всё в голове удержать...

2022-10-19 09:13 UTC, igsekor commented on .gitignore
> +**/.DS_Store
```suggestion
# Служебные директории macOS
**/.DS_Store

# Для NodeJS
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json
pids
*.pid
*.seed
*.pid.lock
lib-cov
coverage
*.lcov
.nyc_output
.grunt
bower_components
.lock-wscript
build/Release
node_modules/
jspm_packages/
web_modules/
*.tsbuildinfo
.npm
.eslintcache
.stylelintcache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/
.node_repl_history
*.tgz
.yarn-integrity
.env
.env.development.local
.env.test.local
.env.production.local
.env.local
.cache
.parcel-cache
.next
out
.nuxt
dist
.cache/
.vuepress/dist
.temp
.docusaurus
.serverless/
.fusebox/
.dynamodb/
.tern-port
.vscode-test
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*
.webpack/
.svelte-kit

## Для редактора VSCode
.vscode/*
.history/
*.vsix
.history
.ionide

# Для редакторов от JetBrains
.idea/**/workspace.xml
.idea/**/tasks.xml
.idea/**/usage.statistics.xml
.idea/**/dictionaries
.idea/**/shelf
.idea/**/aws.xml
.idea/**/contentModel.xml
.idea/**/dataSources/
.idea/**/dataSources.ids
.idea/**/dataSources.local.xml
.idea/**/sqlDataSources.xml
.idea/**/dynamic.xml
.idea/**/uiDesigner.xml
.idea/**/dbnavigator.xml
.idea/**/gradle.xml
.idea/**/libraries
.idea/artifacts
.idea/compiler.xml
.idea/jarRepositories.xml
.idea/modules.xml
.idea/*.iml
.idea/modules
*.iml
*.ipr
cmake-build-*/
.idea/**/mongoSettings.xml
*.iws
out/
.idea_modules/
atlassian-ide-plugin.xml
.idea/replstate.xml
.idea/sonarlint/
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties
.idea/httpRequests
.idea/caches/build_file_checksums.ser
modules.xml
.idea/misc.xml
.idea/**/sonarlint/
.idea/**/sonarIssues.xml
.idea/**/markdown-navigator.xml
.idea/**/markdown-navigator-enh.xml
.idea/**/markdown-navigator/
.idea/$CACHE_FILE$
.idea/codestream.xml
.idea/**/azureSettings.xml

### Для редактора SublimeText ###
*.tmlanguage.cache
*.tmPreferences.cache
*.stTheme.cache
*.sublime-workspace
*.sublime-project
sftp-config.json
sftp-config-alt*.json
Package Control.last-run
Package Control.ca-list
Package Control.ca-bundle
Package Control.system-ca-bundle
Package Control.cache/
Package Control.ca-certs/
Package Control.merged-ca-bundle
Package Control.user-ca-bundle
oscrypto-ca-bundle.crt
bh_unicode_properties.cache
GitHub.sublime-settings

### Для редактора Vim ###
[._]*.s[a-v][a-z]
!*.svg  # comment out if you don't need vector files
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]sw[a-p]
Session.vim
Sessionx.vim
.netrwhist
tags
[._]*.un~

# Для редактора Emacs
*~
\#*\#
/.emacs.desktop
/.emacs.desktop.lock
*.elc
auto-save-list
tramp
.\#*
.org-id-locations
*_archive
*_flymake.*
/eshell/history
/eshell/lastdir
/elpa/
*.rel
/auto/
.cask/
flycheck_*.el
/server/
.projectile
.dir-locals.el
/network-security.data
```

2022-10-19 09:26 UTC, StarHamster commented on .gitignore
> +**/.DS_Store
А зачем для JetBrains так много подпапок _.idea_? Разве добавить один раз просто `.idea` недостаточно?

2022-10-19 09:40 UTC, igsekor commented on .gitignore
> +**/.DS_Store
Здесь указано только то, что точно не нужно в проекте. Если что-то попадёт, то это будет осознанный выбор. В этих подпапках может понадобится что-то в будущем. Пока мы не готовы хранить ничего кроме контента и базовых скриптов, но условия меняются... Правильнее так. Если посмотреть на автогенерацию GitHub для Node, то там тоже много всего, как правило, ненужного. Такой файл содержит разные условия, но тотально не перекрывает всё. Впрочем, есть и альтернативная точка зрения, когда запрещаем всё, а потом по факту ориентируемся. Это лишь предложение.

2022-10-19 10:40 UTC, HellSquirrel commented on .gitignore
> +**/.DS_Store
Давайте возьмем вот этот вариант

2022-10-19 11:37 UTC, nlopin commented
что-то много получилось. Давайте выберем только то, что явно может оказаться в проекте?

Думаю базово должно хватить папок разных IDE + .DS_Store

2022-10-21 00:30 UTC, solarrust reviewed
Предложила правки, сокращающие файл

2022-10-21 00:30 UTC, solarrust commented on .gitignore
> +**/.DS_Store
```suggestion
.DS_Store
Thumbs.db
```

Если я ничего не путаю, то такого правила будет достаточно, для игнора этого файла где угодно. Заодно добавила ещё один системный файл

2022-10-21 00:30 UTC, solarrust commented on .gitignore
> +.idea/**/azureSettings.xml
```suggestion
.idea/**/*
*.iml
*.ipr
cmake-build-*/
*.iws
out/
.idea_modules/
atlassian-ide-plugin.xml
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties
modules.xml
```

Предлагаю сократить до таких правил. Нам точно не нужны любые файлы из папки `.idea/`.

2022-10-21 00:30 UTC, solarrust commented on .gitignore
> +GitHub.sublime-settings
```suggestion
*.tmlanguage.cache
*.tmPreferences.cache
*.stTheme.cache
*.sublime-workspace
*.sublime-project
sftp-config.json
sftp-config-alt*.json
Package Control.*
Package Control.*/*
oscrypto-ca-bundle.crt
bh_unicode_properties.cache
GitHub.sublime-settings
```

2022-10-21 00:30 UTC, solarrust commented on .gitignore
> +[._]*.un~
```suggestion
[._]*.s[a-v][a-z]
[._]*.sw[a-p]
[._]s[a-rt-v][a-z]
[._]ss[a-gi-z]
[._]sw[a-p]
Session.vim
Sessionx.vim
.netrwhist
tags
[._]*.un~
```

Убрала правило про SVG, они у нас в проекте встречаются.

2022-10-21 00:30 UTC, solarrust commented on .gitignore
> +/network-security.data
```suggestion
/.emacs.desktop
/.emacs.desktop.lock
*.elc
auto-save-list
tramp
.org-id-locations
*_archive
*_flymake.*
/eshell/history
/eshell/lastdir
/elpa/
*.rel
.cask/
flycheck_*.el
/server/
.projectile
.dir-locals.el
/network-security.data
```

Убрала очень общие правила. Опасаюсь, что они покромсают рефреном нужное

2022-10-24 05:57 UTC, solarrust commented
@StarHamster закончим с этим пиаром?

2022-10-24 07:32 UTC, StarHamster commented
Вроде стало выглядеть отлично 🙌

2022-10-24 11:27 UTC, igsekor approved these changes

2022-10-25 06:43 UTC, HellSquirrel approved these changes
🚀 давайте пробовать :)

2022-10-25 07:31 UTC, merged