Article/polyfill promise all
doka-guide/content pull request #3923
Opened 2022-10-15 22:14 UTC by walborn

Добавляет вопрос "Реализуйте полифил для Promise.all" в раздел "на собесе"

2022-10-18 09:37 UTC, HellSquirrel requested changes

2022-10-18 09:37 UTC, HellSquirrel commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +Он принимает на вход массив промисов и начинает выполнять их одновременно, все сразу. Ждёт, пока все промисы не выполнятся, и только тогда возвращает массив результатов. Но если какой-то промис вылет
Давай тут немного уточним: Promise.all не возвращает массив результатов. Эта функция возвращает `Promise`. Этот `Promise` асинхронно завершается либо ошибкой либо массивом результатов

2022-10-18 09:37 UTC, HellSquirrel commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +2. Мы должны как-то понять, что все промисы выполнились, чтобы разрешить промис с полученными результатами. Я предлагаю использовать переменную `left`, где будем хранить количество ещё не выполненных
> чтобы разрешить промис с полученными результатами

Тут не совсем понятно какой именно промис имеется ввиду

2022-10-18 09:37 UTC, HellSquirrel commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +3. Наша функция должна возвращать промис, внутри которого мы проходимся по всем промисам. И если  - какой-то промис завершился успешно - добавляем его в `results`, причём под тем же индексом, который
Не совсем понимаю что имеется ввиду под "промис, внутри которого мы проходимся по всем промисам"

2022-10-18 09:37 UTC, HellSquirrel commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +  let left = promises.length
Это полнейшай вкусвщина, так что можно игнорировать этот коммент, но, кажется, что left это не совсем корректное название.
Наши промисы могут успешно завершаться в любом порядке, а эта переменная это просто счетчик завершенных. Я бы назвала `counter`

2022-10-18 09:37 UTC, HellSquirrel commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +const fetchUsers = () => delay(1000).then(() => [ 'Маша', 'Петя', 'Оля' ])
Возможно этот пример кого-то запутает. Кто-то может ожидать что финальный результат будет `[ 'Маша', 'Петя', 'Оля' , 'Lorem ipsum dolor sit amet' ]`

2022-10-18 09:59 UTC, walborn commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +  let left = promises.length
Согласен, тут лучше использовать другое слово. Переназову как `rest`.
`counter` я не хочу, потому это, обычно, счетчик, который увеличивается. Нужно тогда все переписать и сравнивать с `promises.length` каждый раз

2022-10-19 10:34 UTC, HellSquirrel commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +Он принимает на вход массив промисов и начинает выполнять их одновременно. Все сразу! Ждёт... Пока не выполнятся все промисы, и только тогда отдаёт массив с результатами, причём в том же порядке, в к
```suggestion
Он принимает коллекцию промисов, начинает одновременно их выполнять и возвращает новый промис. Если все переданные промисы выполнятся, возвращаемые промис тоже выполнится и в нем будет лежать массив результатов. Но! Если какой-то промис вылетел с ошибкой, то `Promise.all` прекращает работу раньше и возвращаемый промис будет отклонен. ```

2022-10-19 12:03 UTC, walborn commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +Он принимает на вход массив промисов и начинает выполнять их одновременно. Все сразу! Ждёт... Пока не выполнятся все промисы, и только тогда отдаёт массив с результатами, причём в том же порядке, в к
Тут нужно поставить `й`: 
Если все переданные промисы выполнятся, возвращаемы`й` промис тоже выполнится

2022-10-19 12:04 UTC, walborn commented on interviews/polyfill-promise-all/answers/walborn/index.md
> +Он принимает на вход массив промисов и начинает выполнять их одновременно. Все сразу! Ждёт... Пока не выполнятся все промисы, и только тогда отдаёт массив с результатами, причём в том же порядке, в к
и в нем - нужно поменять на н`ё`м

2022-10-19 12:25 UTC, HellSquirrel approved these changes

2022-10-19 12:26 UTC, HellSquirrel commented
Отлично! Спасибо 🚀

2022-10-19 12:42 UTC, merged