Добавляет рецепт для генератора шрифтов
doka-guide/content pull request #3970
Opened 2022-10-26 23:21 UTC by igsekor

## Описание

Написал рецепт для того, чтобы облегчить старт проекта для фронтенд разработчика

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-10-27 07:13 UTC, HellSquirrel reviewed
Огонь! Добавила мелкие правочки

2022-10-27 07:13 UTC, HellSquirrel commented on recipes/font-script/index.md
> +Существует множество практических советов, как реализовать эту задачу максимально круто. Но все они сводятся к большому количеству рутинных действий. Причём ежедневно подготовкой шрифтов не занимаетс
```suggestion
Существует множество практических советов, как реализовать эту задачу максимально круто. Но все они сводятся к большому количеству рутинных действий. Причём ежедневно подготовкой шрифтов никто не занимается. Нужно время на то, чтобы вспомнить, как использовать инструменты. Наверняка пару раз что-то пойдёт не так. Я предлагаю максимально сосредоточится на процессе разработки, а не на скучных и однообразных действиях. Если есть возможность что-то автоматизировать, то я удержаться не могу.
```

2022-10-27 07:13 UTC, HellSquirrel commented on recipes/font-script/index.md
> +Я использую заранее заготовленный скрипт для проектов. Например, если в проекте нужно, чтобы была широкая поддержка семейства шрифтов _Fira_ для поддержки латиницы и кириллицы, кода и математических
```suggestion
Я использую заранее заготовленный скрипт для проектов. Например, если в проекте нужно использовать несколько вариаций шрифтов _Fira_  с поддержкой латиницы, кириллицы, кода и математических выражений, я использую вот такой скрипт _font.sh_:
```

2022-10-27 07:13 UTC, HellSquirrel commented on recipes/font-script/index.md
> +# Набор названий для сабсетов
Тут бы пояснить что такое сабсет

2022-10-27 07:13 UTC, HellSquirrel commented on recipes/font-script/index.md
> +Такой скрипт позволяет любому участнику проекта быстро сгенерировать или обновить набор шрифтов проекта. Исходники лежат в _ ./service/fonts/\<Название-Шрифта\>_, скрипт создаст нужные шрифты и полож
Но если у тебя формат 'otf' все же сломается?

2022-10-27 07:13 UTC, HellSquirrel commented on recipes/font-script/index.md
> +Существует множество практических советов, как реализовать эту задачу максимально круто. Но все они сводятся к большому количеству рутинных действий. Причём ежедневно подготовкой шрифтов не занимаетс
А для вариативных шрифтов (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide) флоу такой же?

2022-10-27 07:13 UTC, HellSquirrel commented on recipes/font-script/index.md
> +GENERATE_FONT() {
Кажется тут мы повторяем большой кусочек скрипта. Может лучше добавить коммент в исходных скрипт?

2022-10-27 07:13 UTC, HellSquirrel commented on recipes/font-script/index.md
> +Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии можно автоматизировано сжать картинки или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https:/
Ты имеешь ввиду [CLI](https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli) ?
Если хочется что-то из терминала можно заменить на vips

2022-10-27 07:13 UTC, HellSquirrel commented on recipes/font-script/index.md
> +Такую функцию можно использовать в интерактивных скриптах, которые взаимодействуют с командной строкой. Достаточно считать аргументы, в которых можно передать значения, например, имена директорий для
Вроде то что выше это не функция, а кусочек скрипта. И еще не совсем понятно на какую функцию ты ссылаешься

2022-10-27 07:13 UTC, skorobaeus commented on recipes/font-script/index.md
> +Вам понадобиться:
```suggestion
Вам понадобится:
```

2022-10-27 07:17 UTC, solarrust reviewed
Я уже хочу этот пакет в свой проект! ♥️
Поревьюила, предложила в паре мест упростить формулировки, чуть подправила, нашла места для уточнений и улучшений.

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +Я использую заранее заготовленный скрипт для проектов. Например, если в проекте нужно, чтобы была широкая поддержка семейства шрифтов _Fira_ для поддержки латиницы и кириллицы, кода и математических
В тексте отрендереной статьи _font.sh_ выделяется как ссылка. Предлагаю не бороться с этим, а положить файлик рядом со статьёй и дать возможность его скачать. Что думаешь?

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +description: "Начните следующий проект с подготовки набора шрифтов"
```suggestion
description: "Начните следующий проект с подготовки набора шрифтов."
```

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +title: "Скрипт для генерации набора шрифтов"
```suggestion
title: "Собственный конвертор шрифтов"
```

Как тебе такое, более завлекательное название?

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +Каждый разработчик сталкивается с большим количеством рутинных задач. Одной из них является подготовка шрифтов. В зависимости от дизайна, требованиям к скорости загрузки, возможной поддержки нескольк
```suggestion
В работе разработчика много рутинных задач. Например, подготовка шрифтов. В зависимости от дизайна, требований к скорости загрузки, возможной поддержки нескольких языков и прочих условий, эта работа может занимать много времени.
```

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +Существует множество практических советов, как реализовать эту задачу максимально круто. Но все они сводятся к большому количеству рутинных действий. Причём ежедневно подготовкой шрифтов не занимаетс
```suggestion
Разработчик не готовит шрифты для проекта ежедневно. Нужно время чтобы вспомнить, как использовать инструменты, наверняка пару раз что-то пойдёт не так.

Предлагаю максимально сосредоточится на процессе разработки, а не на скучных и однообразных действиях. В этом рецепте я расскажу, как сделать эту задачу максимально круто, без рутины. Если есть возможность что-то автоматизировать, то я удержаться не могу.
```

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +
```suggestion
1. Терминал, который поддерживает команды Unix-подобных операционных систем: терминал на macOS или Linux, WSL под Windows.
1. Node.js — среда выполнения для языка JavaScript, о которой подробнее написано в статье «[Что такое Node.js](/tools/nodejs/)».
1. [Glyphanger](https://www.npmjs.com/package/glyphhanger) — популярный инструмент для работы со шрифтами, который можно установить глобально командой: `npm install -g glyphhanger`.

```

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +Я использую заранее заготовленный скрипт для проектов. Например, если в проекте нужно, чтобы была широкая поддержка семейства шрифтов _Fira_ для поддержки латиницы и кириллицы, кода и математических
Ещё бы тут добавить, что файлик должен лежать внутри проекта на момент его исполнения, как я понимаю.

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +# Набор названий для сабсетов
Может быть ниже, в разборе, пояснить, что такое сабсеты?

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +
Тут ещё можно сказать про скачанные шрифты в формате ttf

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +Основой для работы является функция, которая позволяет сгенерировать набор файлов с помощью утилиты Glyphhanger:
```suggestion
Основой для работы является функция, которая генерирует набор файлов с помощью утилиты Glyphhanger:
```

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии можно автоматизировано сжать картинки или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https:/
```suggestion
Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии можно автоматизировано оптимизировать или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https://squoosh.app).
```

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +Такую функцию можно использовать в интерактивных скриптах, которые взаимодействуют с командной строкой. Достаточно считать аргументы, в которых можно передать значения, например, имена директорий для
```suggestion
Такую функцию можно использовать в интерактивных скриптах, которые взаимодействуют с командной строкой. Достаточно считать аргументы, в которых передаются значения, например, имена директорий для исходных и конечных файлов. Обработать аргументы можно так:
```

2022-10-27 07:17 UTC, solarrust commented on recipes/font-script/index.md
> +```
Тут ниже бы финальное пояснение ключей и слов. Чтобы закрепить =)

2022-10-27 07:22 UTC, skorobaeus commented
Не перестаю тобой восхищаться! От себя добавила пару мягких знаков и запятых :D

2022-10-27 07:27 UTC, TatianaFokina commented on recipes/font-script/index.md
> +Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии, можно автоматизированно сжать картинки или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https
```suggestion
Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии, можно автоматизировано сжать картинки или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https://squoosh.app/).
```

2022-10-27 07:28 UTC, skorobaeus commented on recipes/font-script/index.md
> +Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии, можно автоматизированно сжать картинки или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https
Как же трудно без литературного редактора! Не верю, что здесь нужна одна "н". Можно заменить на "автоматически", чтобы не биться лбом о вечную дилемму :D

```suggestion
Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии, можно автоматически сжать картинки или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https://squoosh.app).
```

2022-10-27 07:31 UTC, TatianaFokina commented on recipes/font-script/index.md
> +Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии, можно автоматизированно сжать картинки или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https
Кажется, что это страдательное причастие. В его случае должна одна буква быть.

2022-10-27 07:43 UTC, skorobaeus requested changes

2022-10-27 07:43 UTC, skorobaeus commented on recipes/font-script/index.md
> +Вы всегда сможете вместо этой утилиты использовать какую-то другую. По аналогии, можно автоматизированно сжать картинки или подготовить картинки в разных форматах и размерах с помощью [Squoosh](https
Я рассуждала, что это наречие, образованное от прилагательного "автоматизированный", и тогда количество букв "н" должно сохраняться. Одна "н" точно была бы, будь это глагол: что было сделано? — автоматизировано. (Но я не настоящий сварщик).

2022-10-27 08:19 UTC, igsekor commented on recipes/font-script/index.md
> +Такой скрипт позволяет любому участнику проекта быстро сгенерировать или обновить набор шрифтов проекта. Исходники лежат в _ ./service/fonts/\<Название-Шрифта\>_, скрипт создаст нужные шрифты и полож
Да вот работает по счастью :)

2022-10-27 08:20 UTC, igsekor commented on recipes/font-script/index.md
> +# Набор названий для сабсетов
Надо бы

2022-10-27 08:20 UTC, igsekor commented on recipes/font-script/index.md
> +# Набор названий для сабсетов
Да, скорее всего, именно там

2022-10-27 09:06 UTC, igsekor commented on recipes/font-script/index.md
> +```
Решил добавить комменты...

2022-10-27 10:19 UTC, igsekor commented on recipes/font-script/index.md
> +Существует множество практических советов, как реализовать эту задачу максимально круто. Но все они сводятся к большому количеству рутинных действий. Причём ежедневно подготовкой шрифтов не занимаетс
Да, кажется. От набора символов-то ничего не меняется. Вариативность в начертании только.

2022-10-27 10:22 UTC, igsekor commented on recipes/font-script/index.md
> +Такую функцию можно использовать в интерактивных скриптах, которые взаимодействуют с командной строкой. Достаточно считать аргументы, в которых можно передать значения, например, имена директорий для
Это функция в контексте bash-скриптов

2022-10-27 10:24 UTC, igsekor commented on recipes/font-script/index.md
> +
Я описал дальше во флоу

2022-10-27 12:49 UTC, HellSquirrel commented on recipes/font-script/index.md
> +GENERATE_FONT() {
мне немножко резануло глаз. Так как фрагмент кода длинный :)

2022-10-27 12:52 UTC, HellSquirrel approved these changes

2022-10-28 07:43 UTC, TatianaFokina approved these changes

2022-10-28 18:13 UTC, solarrust approved these changes

2022-10-28 18:16 UTC, skorobaeus approved these changes

2022-10-28 18:17 UTC, merged