Правит примеры относительных ссылок
doka-guide/content pull request #3982
Opened 2022-10-29 09:55 UTC by StarHamster

## Описание

Поправил примеры для относительных ссылок в PR шаблоне: добавил пример с картинкой и добавил указание пути до папки демки вместо пути до файла.

2022-10-30 10:43 UTC, solarrust commented on .github/pull_request_template.md
> -- [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)
Двоеточие в начале второй ссылки имело значение — именно так нужно указывать ссылку на демо в рубрике «На практике». Иначе работать не будет.

2022-10-30 11:19 UTC, StarHamster commented on .github/pull_request_template.md
> -- [ ] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)
Не знал, что демки для рубрик нужно класть в корень статьи... думал, что нужно рядом с файлом рубрики. Добавил пример 😉

2022-10-31 15:26 UTC, solarrust approved these changes

2022-11-02 13:34 UTC, solarrust commented
@igsekor ждём твоего ревью

2022-11-02 20:52 UTC, igsekor requested changes
На мой взгляд пример со словом `cracking` не уместен в документации, а описание PR — часть документации. Пример с картинкой тоже отсылает к какой-то отдельной статье. Обезличенная форма лучше.

2022-11-02 20:52 UTC, igsekor commented on .github/pull_request_template.md
> +- [ ] Ссылки на картинки, видео и демки относительные (`images/box-model.png`, `demos/cracking/`, `../demos/example/`)
```suggestion
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)
```

2022-11-03 04:06 UTC, StarHamster commented on .github/pull_request_template.md
> +- [ ] Ссылки на картинки, видео и демки относительные (`images/box-model.png`, `demos/cracking/`, `../demos/example/`)
Но ведь примеры абсолютных ссылок тоже не были обезличены 🤔

2022-11-03 04:09 UTC, StarHamster commented on .github/pull_request_template.md
> +- [ ] Ссылки на картинки, видео и демки относительные (`images/box-model.png`, `demos/cracking/`, `../demos/example/`)
Давай там тогда тоже вместо названий статей _color_, _json_ и _gulp_ вставим example?

2022-11-03 07:37 UTC, igsekor commented on .github/pull_request_template.md
> +- [ ] Ссылки на картинки, видео и демки относительные (`images/box-model.png`, `demos/cracking/`, `../demos/example/`)
> Но ведь примеры абсолютных ссылок тоже не были обезличены 🤔

В этом предложении ключевое слово не «абсолютные», а «внутренние». Логика в том, что материал уже существует, то есть известен Доке.

В пункте, в котором Вы исправили примеры, через слово `example` было показано, что демки могут лежать в разных файлах, но в папке `demos`. Это действительно надо было поправить, мы по всей видимости не отследили этот пункт, когда поменялся флоу работы с демками.

Мы не знаем, что привнесёт автор. Не надо указывать автору, как называть картинки или демки, не надо приносить удачные названия, не надо влиять на творческий процесс. Обезличенная форма здесь максимально уместна.

Документация итак максимально дружелюбна, зачем её намеренно избыточно персонифицировать?

2022-11-03 07:38 UTC, igsekor commented on .github/pull_request_template.md
> +- [ ] Ссылки на картинки, видео и демки относительные (`images/box-model.png`, `demos/cracking/`, `../demos/example/`)
> Давай там тогда тоже вместо названий статей _color_, _json_ и _gulp_ вставим example?

В этих изменениях необходимости нет.

2022-11-03 07:51 UTC, StarHamster commented on .github/pull_request_template.md
> +- [ ] Ссылки на картинки, видео и демки относительные (`images/box-model.png`, `demos/cracking/`, `../demos/example/`)
Я ничего не понял 😓

Сделаю так, как ты говоришь, как только доберусь до компа

2022-11-03 10:40 UTC, StarHamster commented
@igsekor, кст, я не с неба взял cracking. Оно есть в [документации демок](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).

2022-11-03 11:27 UTC, igsekor commented
> @igsekor, кст, я не с неба взял cracking. Оно есть в [документации демок](https://github.com/doka-guide/content/blob/main/docs/demos/index.md).

В этом документе `cracking` связано по смыслу с `eggs-cooking`. А здесь название этой папки появляется абсолютно из ниоткуда.

2022-11-03 20:00 UTC, igsekor approved these changes

2022-11-04 07:44 UTC, merged