Интерактивные демо для гайда по flexbox
doka-guide/content pull request #3984
Opened 2022-10-29 12:17 UTC by uxDimon

## Описание

Интерактивные демо для страницы [Гайд по flexbox](https://doka.guide/css/flexbox-guide/)

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`demos/index.html`, `../demos/example.html`)

2022-10-30 10:40 UTC, solarrust reviewed
Привет!
Невероятная работа, я искренне восхищена!
Оставила несколько комментариев по организации файлов и по внутреннему устройству демок на примере первой.
Пожалуйста, поправь эти моменты во всех файлах.

Твой вклад в эту статью очень большой. Хотелось бы отменить тебя в авторах. Добавь, пожалуйста, в папку _people/_ подпапку со своим ником. Внутри, в файле _index.md_, можно написать любую комфортную для тебя информацию.

2022-10-30 10:40 UTC, solarrust commented on css/flexbox-guide/demos/flex-demo/README.md
> +### [Репозиторий демо на github](https://github.com/uxDimon/doka-flex-demo)
Для чего эта строчка?

2022-10-30 10:40 UTC, solarrust commented on css/flexbox-guide/demos/flex-demo/align_items.html
> +		<title>Демо align-items</title>
Обрати, пожалуйста, внимание, что у нас принято называть каждое демо в формате «Название демо — название статьи — Дока».

2022-10-30 10:40 UTC, solarrust commented on css/flexbox-guide/demos/flex-demo/align_items.html
> +		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
```suggestion
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

Мы не закрываем одиночные теги.

2022-10-30 10:40 UTC, solarrust commented on css/flexbox-guide/demos/flex-demo/align_items.html
> +		<link rel="stylesheet" href="./assets/demo.476fbb88.css">
Стили и JS мы пишем прямо в HTML. Чтобы каждое демо было отдельной, независимой единицей.

2022-10-30 10:40 UTC, solarrust commented on css/flexbox-guide/index.md
> +<iframe title="Пример свойства flex-direction" src="demos/flex-demo/flex_direction.html" height="584"></iframe>
Каждое демо лучше класть в свою папку, а основной файл называть _index.html_. В фрейме можно будет ссылаться только на папку, без указания HTML-файла.

2022-10-30 10:40 UTC, solarrust commented on css/flexbox-guide/index.md
> +<iframe title="Пример свойства flex-direction" src="demos/flex-demo/flex_direction.html" height="584"></iframe>
Каждое демо лучше класть в свою папку, а основной файл называть _index.html_. В фрейме можно будет ссылаться только на папку, без указания HTML-файла.

2022-10-30 10:41 UTC, solarrust commented
@skorobaeus приходи поревьюить демки.

2022-11-01 06:36 UTC, uxDimon commented on css/flexbox-guide/demos/flex-demo/README.md
> +### [Репозиторий демо на github](https://github.com/uxDimon/doka-flex-demo)
Просто сейчас у демки есть сборщик и отдельный репозиторий. Наверное лучше совсем избавится от сборщика, что бы вообще не было зависимостей.

2022-11-01 07:05 UTC, skorobaeus requested changes
Привет! 

@uxDimon спасибо, что хочешь подарить столько контента Доке! Мы придерживаемся определённой файловой структуры и стиля оформления, чтобы справочник выглядел оригинально консистентно. Пожалуйста, посмотри руководство [по демкам](https://github.com/doka-guide/content/blob/main/docs/demos/index.md) (там описана файловая структура и принцип именования файлов, которые нужно применить) и [их стилю](https://github.com/doka-guide/content/blob/main/docs/demos/style.md) (из него потребуется взять шрифты и цвета).

2022-11-01 08:07 UTC, uxDimon commented
> Привет!
> 
> Прошу прощения, если я неправа, но у меня сложилось впечатление, что эти демки принадлежат откуда-то извне. Мы не размещаем в Доке контент, созданный другими людьми для других платформ.
> 
> @uxDimonесли это твой контент и ты хочешь подарить его Доке, то, пожалуйста, посмотри руководство [по демкам](https://github.com/doka-guide/content/blob/main/docs/demos/index.md) (там описанная структура файлов, которую нужно применить) и [их стиль](https://github.com/doka-guide/content/blob/main/docs/demos/style.md) (из-за этого получается набор шрифта и цвета).

Добрый день. 

Концепцию я взял [отсюда](https://html5.by/blog/flexbox/) она мне кажется очень понятной и наглядной. Но саму демку делал с нуля сам. И [дизайн](https://www.figma.com/file/bOTtKQJ2z3cBYKgCUteSLP/doka?node-id=0%3A1) тоже сам придумывал. Основная идея в том чтобы максимально приблизить демку к реальным условием и в тоже время было легко легко добавлять элементы и менять стили. Я намерено оставил возможность сломать верстку на демке если добавить слишком много элементов. 

А техническую часть и стили я подтяну под требования.

2022-11-01 08:38 UTC, solarrust commented on css/flexbox-guide/demos/flex-demo/README.md
> +### [Репозиторий демо на github](https://github.com/uxDimon/doka-flex-demo)
Да, мы стараемся упрощать демки максимально, не использовать дополнительные зависимости и то, без чего можно обойтись. Ванильные HTML, CSS и JS.

2022-11-05 21:17 UTC, uxDimon commented
Вроде как все исправил, подогнал под стандарты, немного поменял цвета. 
Делать каждую демку не зависимой мне кажется плохой идеей потому что они используют общие ресурсы.
Если есть какие то идеи как её можно улучшить пишите.

2022-11-07 08:11 UTC, skorobaeus requested changes
Привет!

Я поменяла цвета на доковские, а также шрифт для `item__name`. Нужно подключить Roboto без засечек в link'и, вот новый url на замену: `https://fonts.googleapis.com/css2?family=Roboto&family=Roboto+Mono&display=swap`

И пофиксить высоту iframe'ов, т.к. паддинг главного контейнера тоже стал побольше :)

2022-11-07 08:11 UTC, skorobaeus commented on css/flexbox-guide/demos/flex-demo/main.css
> +	padding: 16px;
```suggestion
	padding: 50px;
```

2022-11-07 13:14 UTC, uxDimon commented
Вроде как все поправил

2022-11-08 09:55 UTC, solarrust reviewed
Есть пара моментов, которые хочется обсудить

2022-11-09 08:52 UTC, skorobaeus commented
> Вроде как все поправил @skorobaeus Спасибо за цвета. Я честно говоря не очень в них разобрался, мне показалось что можно использовать только те которые относятся к текущий категории.

Супер, спасибо! За правки и за фидбек тоже. Подумаем, как понятнее написать по цвета в гайде :)

2022-11-09 08:56 UTC, skorobaeus commented on css/flexbox-guide/index.md
> +<iframe title="Пример свойства flex-direction" src="demos/flex-demo/flex_direction/" height="640"></iframe>
Я за то, чтобы сохранить эту схему. Схема и демка здесь друг друга не дублируют, статья выигрывает от присутствия их обеих.

2022-11-10 12:02 UTC, uxDimon commented on css/flexbox-guide/demos/flex-demo/main.css
> +	background-color: hsla(0, 0%, 100%, 0.4);
А это не так уж и просто сделать) 

Было бы не плохо в [руководство по стилю демок](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D1%86%D0%B2%D0%B5%D1%82%D0%B0) указать цвета в новом синтаксисе hsl

2022-11-10 12:04 UTC, uxDimon commented on css/flexbox-guide/index.md
> +<iframe title="Пример свойства flex-direction" src="demos/flex-demo/flex_direction/" height="640"></iframe>
Да, давайте попробуем

2022-11-11 07:41 UTC, uxDimon commented
Я вроде все поправил)

2022-11-14 07:41 UTC, solarrust reviewed
Очень крутая работа, конечно. Большое спасибо от души 🙌

Оставила пару комментов по коду.

Есть два предложения:
1. Очень хотелось бы демок для `flex-grow` и `flex-shrink`. Реализуемо ли это?
2. Можно ли добавить интерактивным элементам в «коде» демок какую-то обводку, чтобы показать, что на них можно нажать? Сейчас появляется только фокус уже после нажатия. Но читатель может не сразу понять, куда нажимать.
@skorobaeus подскажешь, как изящнее это сделать?

В конце останется добавить тебя в контрибьюторы. Чтобы твоё имя выводилось на странице статьи нужно будет добавить папку с ником внутрь _people/_. Тут подробнее → https://github.com/doka-guide/content/blob/main/docs/people.md

2022-11-14 07:41 UTC, solarrust commented on css/flexbox-guide/demos/flex-demo/flex_wrap/index.html
> +  <title>Пример свойства flex-wrap — Гайд по flexbox — Дока</title>
В этом демо хорошо бы сделать изначально больше элементов и установить значение `wrap` для `flex-wrap`. Точно визуально будет видно, что элементы переносятся. Сейчас на первый взгляд это и предыдущее демо ничем не отличаются.

2022-11-14 07:41 UTC, solarrust commented on css/flexbox-guide/demos/flex-demo/justify_content/index.html
> +  <title>Пример свойства justify-content — Гайд по flexbox — Дока</title>
Тут тоже бы задала какое-то нестандартное значение, например, `space-between` чтобы глаз цеплялся.

2022-11-14 07:41 UTC, solarrust commented on css/flexbox-guide/demos/flex-demo/justify_content/index.html
> +  <title>Пример свойства justify-content — Гайд по flexbox — Дока</title>
Коммент относится в целом к остальным демкам. Если есть возможность привлечь дополнительное внимание, сделать их непохожими друг на друга — лучше делать.
Я понимаю, что смысл в том, чтобы стояло значение по умолчанию. Но таким образом все демки будут одинаковые и быстро сформируется _слепота_ на них. Читатель будет просто пролистывать их.

2022-11-14 08:08 UTC, uxDimon commented on css/flexbox-guide/demos/flex-demo/justify_content/index.html
> +  <title>Пример свойства justify-content — Гайд по flexbox — Дока</title>
Хорошо я понял идею. 
`flex-grow` и `flex-shrink` да это можно реализовать но когда у меня появится по больше свободного времени.

2022-11-24 08:46 UTC, skorobaeus commented
> 2. Можно ли добавить интерактивным элементам в «коде» демок какую-то обводку, чтобы показать, что на них можно нажать? Сейчас появляется только фокус уже после нажатия. Но читатель может не сразу понять, куда нажимать.
>    @skorobaeus подскажешь, как изящнее это сделать?

Можно заливку добавить и инвертировать цвета:

![image](https://user-images.githubusercontent.com/29401439/203734552-c3226fbd-7bda-489d-b92d-ffd4322b2715.png)

(`border-radius: 6px`)

---

Пока отвечала на вопрос, нашла баг в демо о flex-direction :) При `column` и `column-reverse` контейнер переполняется. При `column` это не страшно, но при `column-reverse` элементы загораживают код:

![image](https://user-images.githubusercontent.com/29401439/203735074-3aaf816f-6127-4b8e-a4b1-0e9bb1756709.png)

2022-12-05 16:20 UTC, solarrust commented
Привет!
Нужна помощь с этим пиаром? Очень хотелось бы его закончить и получить в статье шикарные демки =)

2022-12-07 20:26 UTC, uxDimon commented
Вроде все исправил и переделал как простили. Текущее свойство демки подсветил синеньким цветом чтобы сразу было понятно где свойство о котором шла речь.

По поводу `flex-grow` и `flex-shrink` займусь немного позже, сейчас просто катастрофически не хватает свободного времени(

2022-12-12 13:46 UTC, skorobaeus approved these changes
Получилось крутейше :)

2022-12-21 08:52 UTC, solarrust reviewed
Очень круто, спасибо огромное за проделанную работу и неоценимый вклад ♥️

Добавь себя, пожалуйста, в контрибьюторы статьи. И будем мёржить =) 
Маленький момент: у нас принято использовать только маленькие буквы в юзернейме. В том числе в названии папки внутри _people/_.

2022-12-21 18:55 UTC, uxDimon commented
@solarrust Я не знаю почему не проходит PR Preview / prepare (pull_request_target)
А в остальном всё добавил

2023-01-13 10:42 UTC, solarrust approved these changes
Привет!
Прости, пожалуйста, что немного задержались с мёрджем. 

Спасибо огромное за твой вклад! Очень ценю это, получилось реально круто. Приходи контрибьютить ещё =)

2023-01-13 10:43 UTC, merged