Article/js
doka-guide/content pull request #4035
Opened 2022-11-04 21:01 UTC by bellabzhu

Добавлен плейсхолдер для метода removeProperty.

Closes #3927

2022-11-05 07:10 UTC, HellSquirrel requested changes
Отлично, спасибо! Добавь себя еще, пожалуйста, в папку `peopele`

2022-11-05 07:10 UTC, HellSquirrel commented on js/remove-property/index.md
> +  - js/element-style/
Тут надо удалить конечные слеши `js/element-style/`

2022-11-05 07:10 UTC, HellSquirrel commented on js/remove-property/index.md
> +<iframe title="Демонстрация работы — removeProperty() — Дока" src="demos/index.html" height="180"></iframe>
Давай сделаем высоту побольше, чтобы квадрат не приходилось скролить :)

2022-11-05 07:10 UTC, HellSquirrel commented on js/remove-property/index.md
> +В целом для управления стилями лучше использовать CSS. Можно использовать классы-модификаторы, чтобы придавать какие-то наборы стилей элементу. Но бывает, когда изменять стили инлайново становится не
Хорошо бы (но не обязательно) привести пример такой необходимости :)

2022-11-05 15:27 UTC, bellabzhu commented on js/remove-property/index.md
> +  - js/element-style/
Сделано

2022-11-05 15:28 UTC, bellabzhu commented on js/remove-property/index.md
> +В целом для управления стилями лучше использовать CSS. Можно использовать классы-модификаторы, чтобы придавать какие-то наборы стилей элементу. Но бывает, когда изменять стили инлайново становится не
Не смогла придумать с ходу, если честно, где это лучше, чем классы.

2022-11-05 17:49 UTC, bellabzhu commented on js/remove-property/index.md
> +В целом для управления стилями лучше использовать CSS. Можно использовать классы-модификаторы, чтобы придавать какие-то наборы стилей элементу. Но бывает, когда изменять стили инлайново становится не
Таки нашла идею, добавлю.

2022-11-06 10:31 UTC, HellSquirrel approved these changes
Отлично, спасибо. Мержу :)

2022-11-06 13:24 UTC, merged