window-open was added
doka-guide/content pull request #4037
Opened 2022-11-05 10:49 UTC by TanuGlagkih

Добавлено описание метода window.open() 

Closes #3926

2022-11-05 12:14 UTC, HellSquirrel commented on js/window-open/index.md
> +Метод `open()` открывает ссылки в новом окне, в новой вкладке или в iframe.
```suggestion
Метод `open()` объекта `window` позволяет открывать ссылки в новом окне, в новой вкладке или в iframe.
```

2022-11-05 12:55 UTC, HellSquirrel requested changes
Отлично, добавь еще себя, пожалуйста в папку `people`

2022-11-05 12:55 UTC, HellSquirrel commented on js/window-open/index.md
> +строка, которая содержит url или путь к ресурсу
Не смотря на то что это же написано на MDN, что такое путь к ресурсу?
Так же `url` -> `URL`

2022-11-05 17:25 UTC, TanuGlagkih commented on js/window-open/index.md
> +строка, которая содержит url или путь к ресурсу
Исправлено!

2022-11-09 07:41 UTC, HellSquirrel approved these changes

2022-11-09 07:53 UTC, merged

2022-11-09 07:53 UTC, HellSquirrel commented
@TanuGlagkih  спасибо :)