написал материал по input
doka-guide/content pull request #4059
Opened 2022-11-06 14:54 UTC by Maxi-Mini

## Описание

Closes #

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы абсолютные, заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2022-11-09 09:36 UTC, HellSquirrel requested changes
Приветик! Добавила несколько правок.
Еще, добавь себя пожалуйста в папку [people](https://github.com/doka-guide/content/tree/main/people)

2022-11-09 09:36 UTC, HellSquirrel commented on js/input/demos/index.html
> +    <title>Демонстрация работы — removeProperty() — Дока</title>
А почему `removeProperty`?

2022-11-09 09:36 UTC, HellSquirrel commented on js/input/index.md
> +<!--
Давай уберем комментарий

2022-11-09 09:36 UTC, HellSquirrel commented on js/input/index.md
> +  - doka
```suggestion
  - doka
  - placeholder
```

2022-11-11 12:20 UTC, HellSquirrel approved these changes
Спасибо! Мержу

2022-11-11 12:20 UTC, merged

2022-11-11 12:32 UTC, Maxi-Mini commented
Вам спасибо)