Добавляет плейсхолдер для `Rollup`
doka-guide/content pull request #4067
Opened 2022-11-06 19:51 UTC by bellabzhu

Добавляет плейсхолдер для `Rollup`

Closes #1951

2022-11-09 15:46 UTC, HellSquirrel requested changes
@bellabzhu  Спасибо за чудесную статью. Мне очень грустно что у нас так мало контента про сборщики. Но мы это обязательно исправим :) 

Я добавила несколько комментов и правок. Если хочешь внеси изменения сама. Или их могу внести я :)

2022-11-09 15:46 UTC, HellSquirrel commented on tools/rollup/index.md
> +[`Rollup`](https://rollupjs.org/guide/en) это [`сборщик проекта`](/tools/bundlers/) для JavaScript. Он менее популярный, чем [`Webpack`](/tools/webpack/), но имеет свои преимущества.
А вот не факт что менее популярный :) [смотри какая штука](https://2021.stateofjs.com/en-US/libraries/build-tools/)

2022-11-09 15:46 UTC, HellSquirrel commented on tools/rollup/index.md
> +`--global` делает установку глобальной, это значит, что команды `Rollup` доступны из любой папки проекта.
```suggestion
`--global` делает установку глобальной, это значит, что команды `Rollup` будут доступны из любой папки проекта.
```

2022-11-09 15:46 UTC, HellSquirrel commented on tools/rollup/index.md
> +  - использует разделение кода;
Давай добавим английский термин в скобочках. Он привычнее :)

2022-11-09 15:46 UTC, HellSquirrel commented on tools/rollup/index.md
> +Есть поддержка [`Tree Shaking`](https://en.wikipedia.org/wiki/Tree_shaking) - метода оптимизации, при котором удаляется весь неиспользуемый код. Когда приложение разрастается до приличных размеров, т
Я бы не сказала что удаляется _весь_ неиспользуемый код. Более того, `tree shaking` работает в достаточно ограниченном наборе случаев и ни один сборщик не дает гаранитий что код тришейкнется. Я бы попробовала как-то это отразить в описании.

2022-11-09 20:23 UTC, bellabzhu commented
> @bellabzhu  Спасибо за чудесную статью. Мне очень грустно что у нас так мало контента про сборщики. Но мы это обязательно исправим :) 
> 
> 
> 
> Я добавила несколько комментов и правок. Если хочешь внеси изменения сама. Или их могу внести я :) 

Спасибо за комментарии, на днях я все поправлю и запушу.

2022-11-10 10:52 UTC, bellabzhu commented on tools/rollup/index.md
> +[`Rollup`](https://rollupjs.org/guide/en) это [`сборщик проекта`](/tools/bundlers/) для JavaScript. Он менее популярный, чем [`Webpack`](/tools/webpack/), но имеет свои преимущества.
Хм, но вот по твоей ссылке здесь по awareness webpack занимает первое место, а Rollup 5-е. Судя по графикам Rollup вызывает больше интереса и к нему хочется возвращаться, но больше людей слышали про webpaсk, он более раскручен. Попробую это отразить.

2022-11-10 17:11 UTC, bellabzhu commented
Постаралась учесть все комментарии, добавила по мелочи еще предложений, кое-что переделала.

2022-11-11 08:16 UTC, HellSquirrel commented
Отлично! спасибо большое. Внесла небольшие правки и мержу :)

2022-11-11 08:22 UTC, HellSquirrel approved these changes

2022-11-11 08:25 UTC, merged