Добавил ответ на вопрос о разнице forEach() и map()
doka-guide/content pull request #4123
Opened 2022-11-27 10:52 UTC by punkmachine

## Описание

Постарался понятно и подробно описать ответ на вопрос. 

Единственное, возможно стоит сначала принять мой первый пулл реквест -- https://github.com/doka-guide/content/pull/4117

Т.к. в *people/* я создал профиль именно в том пулл реквесте, в этом решил не повторяться. 

Closes #4122 

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)

2022-11-27 12:04 UTC, heboq requested changes
Привет! Исправил 2 опечатки :)

2022-11-27 12:04 UTC, heboq commented on interviews/foreach-map/answers/punkmachine/index.md
> +Благодаря такой разницы в поведении, на массиве, после вызова `map()` мы можем вызывать и другие методы массива, которые не можем вызвать после `forEach()`. Пример:
```suggestion
Благодаря такой разнице в поведении, на массиве, после вызова `map()` мы можем вызывать и другие методы массива, которые не можем вызвать после `forEach()`. Пример:
```

2022-11-27 12:05 UTC, punkmachine commented
> Привет! Исправил 2 опечатки :)

Спасибо большое! Вроде проверял, но не заметил.

2022-11-28 20:58 UTC, HellSquirrel reviewed
Отличный ответ! Спасибо тебе большое 🤗 
Давай немножко подправим?)

2022-11-28 20:58 UTC, HellSquirrel commented on interviews/foreach-map/answers/punkmachine/index.md
> +Оба метода массива принимают колбэк, который вызывается для каждого элемента массива. Разница заключается в том, что колбэк в `forEach()` не должен ничего возвращать, а в `map()` наоборот - предусмат
Давай тут уточним, что понимается под "не должен ничего возвращать"
Вот такой код `[1,2,3].forEach(a => a + 3)` не упадет с ошибкой.

2022-11-28 20:58 UTC, HellSquirrel commented on interviews/foreach-map/answers/punkmachine/index.md
> +const myArray2 = myArray.map(item => item*2).sort((a, b) => a - b);
```suggestion
const myArray2 = myArray.map(item => item * 2).sort((a, b) => a - b);
```

2022-11-28 20:58 UTC, HellSquirrel commented on interviews/foreach-map/answers/punkmachine/index.md
> +Благодаря такой разнице в поведении, после выполнения `map()` мы можем продолжить цепочку вызова методов массива, чего не получится сделать с помощью `forEach()`.
Давай уточним что именно возвращает функция `map`

2022-11-28 20:58 UTC, HellSquirrel commented on interviews/foreach-map/answers/punkmachine/index.md
> +Оба метода массива принимают колбэк, который вызывается для каждого элемента массива. Разница заключается в том, что колбэк в `forEach()` не должен ничего возвращать, а в `map()` наоборот - предусмат
А почему именно массива?) Что насчет других вариантов? [вот, например](https://tc39.es/ecma262/multipage/keyed-collections.html#sec-map.prototype.foreach)

2022-11-28 20:58 UTC, HellSquirrel commented on interviews/foreach-map/answers/punkmachine/index.md
> +Как мы видим из примера, исходный массив остался не тронутым, а `myArray2` преобразился: каждый его элемент был умножен на два, а после завершения преобразования массива он был ещё и отсортирован. Ис
Можно убрать. Тут, мне кажется, очевидно из примера что произошло

2022-11-28 20:58 UTC, HellSquirrel commented on interviews/foreach-map/answers/punkmachine/index.md
> +  myArray2.push(item*2);
```suggestion
  myArray2.push(item * 2);
```

2022-11-30 03:55 UTC, punkmachine commented on interviews/foreach-map/answers/punkmachine/index.md
> +Благодаря такой разнице в поведении, после выполнения `map()` мы можем продолжить цепочку вызова методов массива, чего не получится сделать с помощью `forEach()`.
Хм. 

> В результате выполнения `map()` мы получим совершенно новый массив.

Могу переписать на:
В результате выполнения `map()` мы получим совершенно новый массив с таким же количеством элементов, как в том, на котором `map()` был вызван. Замечу, что новый массив не содержит ссылок на элементы прошлого массива. 

Что-то вроде такого. Честно говоря, не знаю, как по-другому написать😅.

2022-11-30 03:58 UTC, punkmachine commented on interviews/foreach-map/answers/punkmachine/index.md
> +Оба метода массива принимают колбэк, который вызывается для каждого элемента массива. Разница заключается в том, что колбэк в `forEach()` не должен ничего возвращать, а в `map()` наоборот - предусмат
Хм. 

Могу изменить эту формулировку:
> Оба метода массива принимают колбэк

На:
> Оба метода, при вызове их на массиве, принимают колбэк 

Но сомневаюсь, что "на массиве" будет правильным выражением, но оно довольно понятное, как мне кажется.

2022-11-30 17:03 UTC, HellSquirrel commented on interviews/foreach-map/answers/punkmachine/index.md
> +Оба метода массива принимают колбэк, который вызывается для каждого элемента массива. Разница заключается в том, что колбэк в `forEach()` не должен ничего возвращать, а в `map()` наоборот - предусмат
Я имела ввиду, что в ответе, возможно, нужно подсветить, что это не только методы массива, но ты будешь говорить именно о разнице этих методов для массива

2022-12-01 02:11 UTC, punkmachine commented on interviews/foreach-map/answers/punkmachine/index.md
> +Оба метода массива принимают колбэк, который вызывается для каждого элемента массива. Разница заключается в том, что колбэк в `forEach()` не должен ничего возвращать, а в `map()` наоборот - предусмат
Все. Понял.

2022-12-01 02:19 UTC, punkmachine commented on interviews/foreach-map/answers/punkmachine/index.md
> +Благодаря такой разнице в поведении, после выполнения `map()` мы можем продолжить цепочку вызова методов массива, чего не получится сделать с помощью `forEach()`.
Хм. Да. Спасибо!

2022-12-01 10:36 UTC, HellSquirrel approved these changes
Спасибо большое! Чуть-чуть подредактировала и мержу :)

2022-12-01 10:36 UTC, merged