Добавил ответ на вопрос: Напишите свой класс, который бы являлся стратегией к функции split, используя Symbol
doka-guide/content pull request #4127
Opened 2022-11-28 17:17 UTC by kyzinatra

Добавил ответ на вопрос: Напишите свой класс, который бы являлся стратегией к функции split, используя Symbol

## Описание

Добавил ответ на вопрос о модификации поведения `split()` метода с использованием символов.

Closes #4120

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2022-11-28 21:16 UTC, HellSquirrel reviewed
Ух ты! Шаблончики :) 
Спасибо за такой интересный вопрос. Давай чуть-чуть подправим ответ :)

2022-11-28 21:16 UTC, HellSquirrel commented on interviews/symbol/answers/kyzinatra/index.md
> +Для написания такого класса нам понадобится специальный **well-known** символ `[Symbol.split]`.
Давай добавим сюда краткое описание шаблона "стратегия". Кажется, что не все наши читатели с ним знакомы. Я вот честно пошла читать википедию и с первого раза ничего не поняла :)

2022-11-28 21:16 UTC, HellSquirrel commented on interviews/symbol/answers/kyzinatra/index.md
> +Для написания такого класса нам понадобится специальный **well-known** символ `[Symbol.split]`.
А точно-ли он **well-known**? Можешь привести какой-то пруф?

2022-11-28 21:16 UTC, HellSquirrel commented on interviews/symbol/answers/kyzinatra/index.md
> +Он работает как прослойка в методе `split()`. У строк он реализован по умолчанию и выполняет знакомое поведение этой функции:
Не совсем поняла смысл этого предложения (что значит "работает как прослойка"). Давай попробуем перефразировать?

2022-11-28 21:16 UTC, HellSquirrel commented on interviews/symbol/answers/kyzinatra/index.md
> +  [Symbol.split](string) { // принимаем строку-аргумент (которую будем сплитить)
А если без `return`, что произойдет?

2022-11-28 21:16 UTC, HellSquirrel commented on interviews/symbol/answers/kyzinatra/index.md
> +Если вам задают этот вопрос, то, обычно, хотят, чтобы вы продемонстрировали владения символами (не обязательно именно `Symbol.split`) и то, как их использовать.
```suggestion
Этот вопрос проверяет умеете ли вы использовать символы
```

2022-11-28 21:16 UTC, HellSquirrel commented on interviews/symbol/answers/kyzinatra/index.md
> +На практике такие вопросы задают редко, из-за специфичности темы, но такие нюансы могут сильно разнообразить ваш инструментарий и возможность находить элегантные решения.
```suggestion
Хотя такие вопросы задают редко, из-за специфичности темы, умение пользоваться символами – полезный инструмент, который поможет вам элегантно решать некоторые задачи
```

2022-11-29 09:40 UTC, kyzinatra commented on interviews/symbol/answers/kyzinatra/index.md
> +Для написания такого класса нам понадобится специальный **well-known** символ `[Symbol.split]`.
Ну вроде как спецификация говорит, что не вру)
https://262.ecma-international.org/6.0/#sec-well-known-symbols
![image](https://user-images.githubusercontent.com/51288221/204494016-66a6229a-0f30-4fe8-8a2f-3bb5e751e3d4.png)

2022-11-29 12:31 UTC, HellSquirrel commented on interviews/symbol/answers/kyzinatra/index.md
> +Для написания такого класса нам понадобится специальный **well-known** символ `[Symbol.split]`.
давай тогда так: 
```suggestion
Для написания такого класса нам понадобится специальный [**well-known** символ](https://262.ecma-international.org/6.0/#sec-well-known-symbols) `[Symbol.split]`.
```

2022-11-29 13:29 UTC, StarHamster requested changes
Привет. Не стоит ломать абзацы, потому что парсер так и парсит — переносом строки `<br>`. Так что нужно либо добавлять пустую строку, чтобы сделать два абзаца, либо писать в одну строку

2022-11-29 13:29 UTC, StarHamster commented on interviews/symbol/answers/kyzinatra/index.md
> +К примеру:
```suggestion
Стратегия _(Strategy)_ — это ООП поведенческий паттерн проектирования, который позволяет расширять базовый класс (метод) новыйм функционалом, если передать в него, так называемый, **конкретный класс**. К примеру:
```

2022-11-29 13:29 UTC, StarHamster commented on interviews/symbol/answers/kyzinatra/index.md
> +Хотя такие вопросы задают редко, из-за специфичности темы, умение пользоваться символами – полезный инструмент, который поможет вам элегантно решать некоторые задачи
```suggestion
Этот вопрос проверяет умеете ли вы использовать символы. Хотя такие вопросы задают редко, из-за специфичности темы, умение пользоваться символами – полезный инструмент, который поможет вам элегантно решать некоторые задачи
```

2022-11-29 13:29 UTC, StarHamster commented on interviews/symbol/index.md
> +```js
```suggestion
Напишите свой класс, который бы являлся [стратегией](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)) к функции split, используя Symbol. Пример:

```js
```

2022-11-29 13:29 UTC, StarHamster commented on interviews/symbol/answers/kyzinatra/index.md
> +Метод `split()` вызывает `[Symbol.split](str)`, а результат этой функции возвращает как результат `split()`. У строк он реализован по умолчанию и выполняет знакомое поведение этой функции:
```suggestion
Для написания такого класса нам понадобится специальный [**well-known** символ](https://262.ecma-international.org/6.0/#sec-well-known-symbols) `[Symbol.split]`. Метод `split()` вызывает `[Symbol.split](str)`, а результат этой функции возвращает как результат `split()`. У строк он реализован по умолчанию и выполняет знакомое поведение этой функции:
```

2022-11-30 16:31 UTC, HellSquirrel commented
@kyzinatra спасибо большое! внесла небольшие правки и мержу

2022-11-30 16:32 UTC, HellSquirrel approved these changes

2022-11-30 17:00 UTC, merged