Дополнил описание псевдоэлемента first-line
doka-guide/content pull request #4190
Opened 2023-01-08 08:02 UTC by punkmachine

## Описание

Статья уже была написана, я добавил демо, добавил одну подсказку. Переписал раздел "как пишется", вытащив из статьи first-letter его по сути, и удалив то, что не актуально под псевдоэлемент. У обоих статей это описание изначально было одинаково, first-letter меня тоже я. 

Closes #417 

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-01-09 09:06 UTC, solarrust reviewed
Круто, спасибо! 🔥

Оставила пару мелких косметических правочек.

2023-01-09 09:06 UTC, solarrust commented on css/first-line/demos/first-line/index.html
> +    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam consectetur, fuga optio cumque atque itaque harum veniam voluptates, delectus aut, impedit repellat quas perspiciatis. Distinctio mi
Давай заменим лорем ипсум на что-то более увлекательное? Можно взять что-то из классики =)

2023-01-09 10:53 UTC, skorobaeus requested changes

2023-01-09 10:53 UTC, skorobaeus commented on css/first-line/demos/first-line/index.html
> +      letter-spacing: 0.04rem;
`letter-spacing: 0.04rem;` служит какой-то цели или можно убрать?

2023-01-09 10:53 UTC, skorobaeus commented on css/first-line/demos/first-line/index.html
> +      color: deepPink;
```suggestion
      color: #2E9AFF;
```

Цвет раздела CSS для цветового акцента.

2023-01-09 10:53 UTC, skorobaeus commented on css/first-line/demos/first-line/index.html
> +      font-size: 16px;
```suggestion
      font-size: 18px;
```

Т.к. текста мало, лучше сделать размер шрифта побольше :)

2023-01-09 10:57 UTC, skorobaeus commented
Привет! Спасибо :) Оставила пару мелких комментов по стилю демки :)

2023-01-09 12:05 UTC, punkmachine commented on css/first-line/demos/first-line/index.html
> +      letter-spacing: 0.04rem;
можно убрать, у меня просто был один шаблон демки уже готовый, который я в свою очередь взял со статьи кого-то из редакции доки, когда писал свою первую.

2023-01-09 12:15 UTC, punkmachine commented on css/first-line/demos/first-line/index.html
> +    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam consectetur, fuga optio cumque atque itaque harum veniam voluptates, delectus aut, impedit repellat quas perspiciatis. Distinctio mi
Я надеюсь, проверка орфографии пропустит цитаты из Гарри Поттера.

2023-01-09 13:33 UTC, skorobaeus commented on css/first-line/demos/first-line/index.html
> +      letter-spacing: 0.04rem;
Так и подумала! Спасибо :)

2023-01-10 07:03 UTC, solarrust commented on css/first-line/demos/first-line/index.html
> +    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam consectetur, fuga optio cumque atque itaque harum veniam voluptates, delectus aut, impedit repellat quas perspiciatis. Distinctio mi
Почти получилось! Проверка споткнулась только об «Дурсь». Добавишь его в исключения (файл _.yaspeller.json_)?

2023-01-10 07:04 UTC, punkmachine commented on css/first-line/demos/first-line/index.html
> +    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam consectetur, fuga optio cumque atque itaque harum veniam voluptates, delectus aut, impedit repellat quas perspiciatis. Distinctio mi
Оке. Добавлю. Спасибо).

2023-01-10 07:27 UTC, solarrust approved these changes
Спасибо! 🙌

2023-01-10 07:31 UTC, solarrust approved these changes

2023-01-10 07:39 UTC, skorobaeus approved these changes

2023-01-10 07:41 UTC, merged