Исправляет ошибку в статье Дескрипторы
doka-guide/content pull request #4212
Opened 2023-01-15 21:11 UTC by mukhindev

## Описание

В статье сказано, что `Object.freeze()` замораживает объект и возвращает **новый** объект. На самом деле возвращается тот же объект.

```javascript
const foo = {}
const bar = Object.freeze(foo)
foo === bar // true
```

Также смущают остальные фразы начинающиеся с "создаёт * объект". 

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-01-16 07:12 UTC, HellSquirrel requested changes
Привет! Большое спасибо за наблюдение.
Думаю, тут подразумевалось что функция `freeze` возвращает объект
Например так
```const frozen = Object.freeze({ foo: 'bar' })```
Давай попробуем еще немножко исправить чтобы это учесть?)

2023-01-17 08:10 UTC, mukhindev commented
@HellSquirrel хорошо, попробую переписать с однозначным смыслом)

2023-02-03 08:46 UTC, HellSquirrel commented
@mukhindev приветик. Хочешь чуть изменить (см комменты выше) ?

2023-02-07 21:54 UTC, mukhindev commented
@HellSquirrel привет! Забегался что-то и упустил. Поправил как смог). Не хотелось сильно менять, так как это авторская секция "AntonGorelov советует"

2023-04-12 11:00 UTC, HellSquirrel commented
Порезолвила конфликты и радостно мержу! Спасибо большое <3

2023-04-12 11:00 UTC, HellSquirrel approved these changes

2023-04-12 11:01 UTC, merged