Псевдоэлементы и JS-события
doka-guide/content pull request #4219
Opened 2023-01-17 21:34 UTC by reaferon

## Описание

Closes #

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-01-18 09:56 UTC, solarrust commented
Спасибо большое!

Я немного поредачила текст и код примера. Посмотри, пожалуйста, не потерялся ли смысл, ок ли правки. 

Добавь, пожалуйста, в папку _people/_ папку со своим ником и опиши комфортную для тебя информацию во вложенном файлике. Подробнее о формате можно почитать в документе про [подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

2023-01-18 10:16 UTC, solarrust commented
@skorobaeus приходи глянуть на демку, пожалуйста.

2023-01-18 11:13 UTC, reaferon commented
> Спасибо большое!
> 
> Я немного поредачила текст и код примера. Посмотри, пожалуйста, не потерялся ли смысл, ок ли правки.
> 
> Добавь, пожалуйста, в папку _people/_ папку со своим ником и опиши комфортную для тебя информацию во вложенном файлике. Подробнее о формате можно почитать в документе про [подпись автора](https://github.com/doka-guide/content/blob/main/docs/people.md).

Правки ок. _people сделаю сегодня вечером.

2023-01-18 15:16 UTC, skorobaeus requested changes
Привет! Классная демка :) Я покрасила кирпичик и сделала его покрупнее.

Ещё предложила бы, пожалуй, избавиться от `<section>` в разметке.

2023-01-18 15:16 UTC, skorobaeus commented on css/pseudoelements/demos/javascript-events/index.html
> +        content: '-';
```suggestion
        content: '–';
```

Меняет минус на короткое тире, он по размеру больше похож на плюс.

2023-01-18 15:16 UTC, skorobaeus commented on css/pseudoelements/demos/javascript-events/index.html
> +      }
```suggestion
    .quantity-change {
      display: flex;
      align-items: center;
      justify-content: space-between;    
      width: 160px;
      height: 44px;
      border-radius: 6px;
      background-color: #2E9AFF;
      color: #000000;
      font-size: 24px;
      cursor: text;
      user-select: none;
    }
```

2023-01-18 15:16 UTC, skorobaeus commented on css/pseudoelements/demos/javascript-events/index.html
> +      }
```suggestion
      .quantity-change::before, .quantity-change::after {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 40px;        
        font-size: 34px;
        cursor: pointer;        
      }
```

2023-01-18 15:16 UTC, skorobaeus commented on css/pseudoelements/practice/reaferon.md
> +<iframe title="JavaScript-события для псевдоэлементов" src="../demos/javascript-events/" height="420"></iframe>
```suggestion
<iframe title="JavaScript-события для псевдоэлементов" src="../demos/javascript-events/" height="200"></iframe>
```

2023-01-18 16:17 UTC, reaferon commented on css/pseudoelements/demos/javascript-events/index.html
> +        content: '-';
Привет. Я пока еще не все понимаю, мне так и не удалось отображать содержимое iframe в markdown.
Если отсутствие section ничего не сломает в отображении iframe, то можно и убрать.

2023-02-03 07:23 UTC, solarrust commented
Внесла правки в код демок, добавила значок за первый контрибьюшен.

@skorobaeus скажи финальное ОК и будем мёржить =)

2023-02-03 07:24 UTC, solarrust approved these changes

2023-02-06 08:56 UTC, skorobaeus approved these changes
Финальный ОК! @solarrust

2023-02-07 03:54 UTC, merged