Адаптирует демки из `HTMLCollection и NodeList` и `Set` к тёмной теме
doka-guide/content pull request #4246
Opened 2023-02-02 23:07 UTC by rakleed

## Описание

Адаптирует демки из `HTMLCollection и NodeList` и `Set` к тёмной теме.

Closes #4172.

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-02-03 08:54 UTC, HellSquirrel commented
@solarrust  глянь сюда пжлст. Тут, кажется, по твоему разделу больше

2023-02-06 09:25 UTC, skorobaeus requested changes
@HellSquirrel демки это ко мне :D

2023-02-06 09:25 UTC, skorobaeus commented on js/htmlcollection-and-nodelist/demos/Lopinopulos-xNOBow/index.html
>  <!DOCTYPE html>
Привет!

Назови, пожалуйста, папку одним-двумя английскими словами. `Lopunopulos-xNOBow` это старое название, которое осталось ещё со времён, когда демки мы собирали в codepen. Во время редизайна мы их переименовываем.

2023-02-06 09:25 UTC, skorobaeus commented on js/htmlcollection-and-nodelist/demos/Lopinopulos-xNOBow/index.html
> +  <h1>Живая коллекция</h1>
Для заголовка нужно задать размер шрифта и жирность шрифта в соответствии со [стайлгайдом](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D1%82%D0%B5%D0%BA%D1%81%D1%82-%D0%B8-%D1%82%D0%B8%D0%BF%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B0).

2023-02-06 09:25 UTC, skorobaeus commented on js/htmlcollection-and-nodelist/demos/Lopinopulos-xNOBow/index.html
> +  <h2>Сейчас в коллекции: <span id="counter"></span></h2>
При редизайне старых демок я также обращаю внимание на семантичность вёрстки и при необходимости вношу изменения.

С точки зрения семантики это не заголовки, а два параграфа, поэтому желательно заменить эти теги.

Однако JS демки манипулирует тегами `<p>`. Чтобы демка не потеряла смысл и продолжила работать, я бы заменила манипулируемые элементы —  `<p>Это параграф #1</p>` и `<p>Это параграф #2</p>` — например, на [ссылки](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D0%B8%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD%D0%BE%D0%B2%D1%8B%D0%B5-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%8B). И переписала текст с соответствии с этим изменением.

2023-02-06 09:25 UTC, skorobaeus commented on js/htmlcollection-and-nodelist/demos/Lopinopulos-xNOBow/index.html
> +  <h3>При загрузке страницы мы один раз получили все параграфы на странице с помощью getElementsByTagName, их список поддерживается актуальным автоматически</h3>
Подстроку `getElementsByTagName` нужно обернуть в тег `<code>` и задать шрифт [Roboto Mono](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D1%81%D1%82%D0%B8%D0%BB%D0%B8-%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BA%D0%BE%D0%B4%D0%B0).

2023-02-06 09:25 UTC, skorobaeus commented on js/htmlcollection-and-nodelist/demos/Lopinopulos-xNOBow/index.html
> +  <button id="remove">Удалить параграф</button>
Для кнопок нужно задать стили в соответствии со [стайлгайдом](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8). Цвет раздела JS — жёлтый.

2023-02-06 09:25 UTC, skorobaeus commented on js/set/demos/index.html
>      }
Для [поля ввода](https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D0%BF%D0%BE%D0%BB%D1%8F-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0) и кнопки нужно задать стили в соответствии со стайлгайдом.

2023-02-12 23:58 UTC, rakleed commented on js/htmlcollection-and-nodelist/demos/Lopinopulos-xNOBow/index.html
> +  <h2>Сейчас в коллекции: <span id="counter"></span></h2>
Поменял на ссылки, но в Safari некорректно работает демка (добавлять новые ссылки начинает с номера 56, а удаление не работает), хотя в Chrome и Firefox всё корректно работает.

2023-02-13 00:00 UTC, rakleed commented
Стили поправил. Изначально вообще только на шаблон посмотрел, не думал, что и стили тоже нужно сильно править 😀

2023-02-13 12:21 UTC, skorobaeus commented on js/htmlcollection-and-nodelist/demos/Lopinopulos-xNOBow/index.html
> +  <h2>Сейчас в коллекции: <span id="counter"></span></h2>
У меня не воспроизводится эта ошибка в сафари 🤔 Я бы начала с выяснения, какие аргументы попадают в `createLinkElement`, ведь 56 генерится там.

Но можно, конечно, использовать любой другой тег :)

2023-02-13 12:26 UTC, skorobaeus commented
Получается круто :) Пара финальных штрихов:

* В `HTMLCollection и NodeList` кнопки "Добавить ссылку" и "Удалить ссылку" лучше поставить в ряд, места там хватает;
* В `Set` также в ряд ставим инпут и кнопку "Добавить";
* В обеих демках весь синий `#2E9AFF` меняем на жёлтый `#FFD829`;
* В завершение всё содержимое обеих демок лучше выровнять по центру по вертикали и по горизонтали.

По стилям это всё, останется только разобраться с мистическим числом `56` и будет готово ✌

2023-02-15 00:39 UTC, rakleed commented on js/htmlcollection-and-nodelist/demos/Lopinopulos-xNOBow/index.html
> +  <h2>Сейчас в коллекции: <span id="counter"></span></h2>
Проблемы была из-за расширения Mate Translate.

2023-02-15 00:41 UTC, rakleed commented
Всё поправил, 56 появлялось из-за браузерного расширения Mate Translate. В Chrome в превью также стало появляться 56, хотя при открытии через локальный сервер этой проблемы не было. Надо будет разработчику расширения написать о проблеме.

Можно мержить!

2023-02-17 13:06 UTC, skorobaeus approved these changes
Поменяла поэлементное центрирование на центрирование всего контейнера и добавила адаптив. Вжух! ✨

2023-02-20 21:40 UTC, HellSquirrel commented
Классно! @rakleed а добавь еще себя в контрибьюторы для этой статьи :) 
@skorobaeus можно смело мержить

2023-02-20 21:42 UTC, rakleed commented
То есть для обоих статей?

2023-02-21 08:14 UTC, merged