Дописать про justify-content в Гайд по гридам #4295
doka-guide/content pull request #4397
Opened 2023-04-16 17:06 UTC by FilimonovAlexey

## Описание

В гайде по гридам дописал про свойство justify-content.

Closes #4295

## Чек-лист
- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-04-19 08:56 UTC, StarHamster requested changes
В Доке не работает такое форматирование 😔. Парсер расставит там `<br>` и будет некрасиво

2023-04-19 10:41 UTC, skorobaeus commented
Привет! Спасибо большое за ПР! 

Мы сейчас переоформляем схемы в этом гайде, чтобы они были в стиле Доки, и хотели бы заодно оформить и твои схемы тоже, если ты не против. Тебе не нужно заново ничего рисовать! :) Но я прошу оформить сниппеты кода как во всём остальном гайде, а именно:

- назвать контейнер классом `.container` вместо `.section`;
- назвать элементы классом `.item` вместо `.div`;
- убрать CSS-свойства, отвечающие за оформление, такие border, background, свойства текста, и оставить только те, что отвечают за гриды.

В качестве образца можно использовать раздел [justify-items](https://doka.guide/css/grid-guide/#justify-items), он похож по смыслу. С единым именованием в примерах статья проще воспринимается, и обновление дизайна тоже пройдёт безболезненно.

2023-04-19 11:50 UTC, StarHamster commented on css/grid-guide/index.md
> +его столбцы слева или справа.
Так тоже не получится( Надо, чтобы весь абзац был на одной строке, иначе будут на сайте тоже будут переносы 👀

2023-04-19 12:08 UTC, FilimonovAlexey commented on css/grid-guide/index.md
> +его столбцы слева или справа.
> Так тоже не получится( Надо, чтобы весь абзац был на одной строке, иначе на сайте тоже будут переносы 👀

Подправил, сейчас вроде неплохо выглядит))

2023-04-19 12:08 UTC, FilimonovAlexey commented
> Привет! Спасибо большое за ПР!
> 
> Мы сейчас переоформляем схемы в этом гайде, чтобы они были в стиле Доки, и хотели бы заодно оформить и твои схемы тоже, если ты не против. Тебе не нужно заново ничего рисовать! :) Но я прошу оформить сниппеты кода как во всём остальном гайде, а именно:
> 
> * назвать контейнер классом `.container` вместо `.section`;
> * назвать элементы классом `.item` вместо `.div`;
> * убрать CSS-свойства, отвечающие за оформление, такие border, background, свойства текста, и оставить только те, что отвечают за гриды.
> 
> В качестве образца можно использовать раздел [justify-items](https://doka.guide/css/grid-guide/#justify-items), он похож по смыслу. С единым именованием в примерах статья проще воспринимается, и обновление дизайна тоже пройдёт безболезненно.

Учел замечания!

2023-04-19 12:27 UTC, StarHamster commented on css/grid-guide/index.md
> +его столбцы слева или справа.
Смотри, вот тут стоит перенос строки `<br>`. А хотелось бы его избежать, ставя абзацы на одну строку

![image](https://user-images.githubusercontent.com/91747573/233072373-a07b3ebc-c7f7-4e43-ad4e-cba9d3e0da0f.png)

Сейчас у тебя этот абзац на двух строках:

https://github.com/doka-guide/content/blob/8e1e08e3f45d06a50dba0d248b4d59c3808584bc/css/grid-guide/index.md?plain=1#L503-L504

P.S. Молюсь всем контрибьютерам платформы Доки, чтобы они вразумили парсер и такие танцы с абзацами закончились 🙏. Кст, надо бы ищью отрыть по этому поводу

2023-04-19 14:27 UTC, StarHamster commented
йоу, а может перенести эту главу чуть выше, перед `justify-items`? логика такая: `justify-items` и `align-items` отвечают за выравнивание элементов в грид-ячейке, а `justify-content` отвечает за выравнивание колонок. так что было бы круто поставить `justify-content` перед `justify-items`. что думаете?

2023-04-19 14:31 UTC, FilimonovAlexey commented
> йоу, а может перенести эту главу чуть выше, перед `justify-items`? логика такая: `justify-items` и `align-items` отвечают за выравнивание элементов в грид-ячейке, а `justify-content` отвечает за выравнивание колонок. так что было бы круто поставить `justify-content` перед `justify-items`. что думаете?

Да, это логично! Щас сделаю

2023-04-19 16:47 UTC, FilimonovAlexey commented
> йоу, а может перенести эту главу чуть выше, перед `justify-items`? логика такая: `justify-items` и `align-items` отвечают за выравнивание элементов в грид-ячейке, а `justify-content` отвечает за выравнивание колонок. так что было бы круто поставить `justify-content` перед `justify-items`. что думаете?

подправил

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +`start` — выравнивает сетку по левой стороне grid-контейнера.
```suggestion
`start` — выравнивает сетку по левой стороне грид-контейнера.
```

Мы не стесняемся писать кириллицей =)

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +`end` — выравнивает сетку по правой стороне grid-контейнера.
```suggestion
`end` — выравнивает сетку по правой стороне грид-контейнера.
```

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +`center` — выравнивает сетку по центру grid-контейнера.
```suggestion
`center` — выравнивает сетку по центру грид-контейнера.
```

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +![Пример реализации свойства justify-content со значением center.](images/30.png)
````suggestion
```

![Пример реализации свойства justify-content со значением center.](images/30.png)
````

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +`stretch` — масштабирует элементы, чтобы сетка могла заполнить всю ширину grid-контейнера.
```suggestion
`stretch` — масштабирует элементы, чтобы сетка могла заполнить всю ширину грид-контейнера.
```

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +![Пример реализации свойства justify-content со значением stretch.](images/31.png)
````suggestion
```

![Пример реализации свойства justify-content со значением stretch.](images/31.png)
````

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +![Пример реализации свойства justify-content со значением space-around.](images/32.png)
````suggestion
```

![Пример реализации свойства justify-content со значением space-around.](images/32.png)
````

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +![Пример реализации свойства justify-content со значением space-between.](images/33.png)
````suggestion
```

![Пример реализации свойства justify-content со значением space-between.](images/33.png)
````

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +`space-evenly` — одинаковое пространство между элементами, и полноразмерные отступы по краям.
```suggestion
`space-evenly` — одинаковое пространство между элементами и полноразмерные отступы по краям.
```

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +![Пример реализации свойства justify-content со значением space-evenly.](images/34.png)
````suggestion
```

![Пример реализации свойства justify-content со значением space-evenly.](images/34.png)
````

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +`space-between` — одинаковое пространство между элементами, без отступов по краям.
```suggestion
`space-between` — одинаковое пространство между элементами без отступов по краям.
```

2023-04-21 17:45 UTC, solarrust commented on css/grid-guide/index.md
> +`space-around` — одинаковое пространство между элементами, и полуразмерные отступы по краям.
```suggestion
`space-around` — одинаковое пространство между элементами и полуразмерные отступы по краям.
```

2023-04-21 18:04 UTC, solarrust commented
Привет! 

Спасибо за классный пиар, этого блока сильно не хватало в гайде.

Я подправила всякие оформительские мелочи, поджала картинки и добавила слово «полуразмерные» в исключения, чтобы спеллер не ругался. 

Пока ждём обновлённых схем от Светы, добавь, пожалуйста, себя в контрибьюторы этой статьи (тег `contributors` в самом начале файла. Если ещё не «представился» в папке _poeple/_, то тоже нужно будет добавить. Короткая инструкция тут → [тыц](https://github.com/doka-guide/content/blob/main/docs/people.md).

2023-04-21 19:15 UTC, skorobaeus commented
@solarrust схемы будут отдельным ПРом, этот можно мерджить :)

2023-04-22 03:23 UTC, FilimonovAlexey commented
> Привет!
> 
> Спасибо за классный пиар, этого блока сильно не хватало в гайде.
> 
> Я подправила всякие оформительские мелочи, поджала картинки и добавила слово «полуразмерные» в исключения, чтобы спеллер не ругался.
> 
> Пока ждём обновлённых схем от Светы @skorobaeus , добавь, пожалуйста, себя в контрибьюторы этой статьи (тег `contributors` в самом начале файла. Если ещё не «представился» в папке _poeple/_, то тоже нужно будет добавить. Короткая инструкция тут → [тыц](https://github.com/doka-guide/content/blob/main/docs/people.md).

добавил информацию о себе))

2023-04-24 14:49 UTC, skorobaeus approved these changes

2023-04-24 23:37 UTC, solarrust approved these changes
У нас принято именовать папки с участниками маленькими буквами. Я переименовала твою папку и поправила юзернейм в статье. 

Спасибо тебе большое за твой вклад! Получилось супер 🔥

2023-04-24 23:59 UTC, merged