Добавляет статью о том, что такое CMS
doka-guide/content pull request #4424
Opened 2023-04-29 12:40 UTC by punkmachine

## Описание

Добавил статью о том, что такое CMS. Постарался не допускать тех ошибок, что были в прошлой статье о SEO. alt-текста заполнил максимально подробно, как делали в прошлом пулл реквесте, а также постарался с меньшим количеством тавтологии. 

Closes #4207 

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Создание сайта**. CMS предоставляет инструменты для создания сайта без знания программирование. С помощью шаблонов и визуальных редакторов можно быстро настроить внешний вид, функционал и работу
```suggestion
- **Создавать веб-страницы**. CMS предоставляет инструменты для создания страниц без написания код. С помощью шаблонов и визуальных редакторов можно быстро настроить внешний вид, функционал и работу с контентом на сайте.
```

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Настройка внешнего вида**. В большинстве CMS есть встроенные настройки типографики, цветовой палитры, макета сайта и так далее. С помощью систем управления контентом можно легко создавать стандар
Кажется, внешний вид уже упоминался в предыдущем пункте

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Полное управление контентом**. CMS предоставляет интерфейс для добавления, изменение и удаление контента. Админ-панель упрощает публикацию статей, загрузку изображений и видео на сайт. Это ускоря
```suggestion
- **Управление контентом**. CMS позволяет изменять, добавлять и удалять текст, видео и изображения. Например, чтобы добавить пост в блог, сделанный на WordPress, понадобится нажать всего одну кнопку «Добавить запись», а чтобы опубликовать написанную статью кнопку «Опубликовать». Удобно? Безусловно.
```

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Базовая настройка.** Использование CMS помогает быстро настроить сайт с помощью готовых плагинов. Плагины предоставляют дополнительные функциональные возможности, такие как формы обратной связи,
Тут наверное надо сказать про систему плагинов чуть-чуть

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Лёгкость в освоение.** Для того, чтобы научиться использовать CMS не понадобятся специальное техническое образование и навыки программирования.
```suggestion
- Для того, чтобы использовать CMS не требуются навыки программирования.
```

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Расширяемость**. CMS создаются с учётом возможности использования дополнительных плагинов. Они в свою очередь расширяют базовый функционал. Благодаря этому, большинство необходимых функциональных
Давай фактчекнем что большинство CMS поддерживают плагины :)

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Низкие затраты.** CMS является более доступным вариантом, чем индивидуальная разработка сайта. Кроме того, многие системы управления сайтом бесплатны, что также снижает затраты на создание проект
Тут очень спорно. Надо обязательно проговорить какие именно приложения можно создавать при помощи CMS. Также, кажется, CMS можно использовать не только для создания своего собственного сайта, но и подключать ее к уже готовому приложению

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Ограниченные возможности.** Системы управления контентом имеют ограничения. Несмотря на большое количество доступных плагинов, вам может не хватить имеющихся возможностей. На системе управления м
```suggestion
- **Ограниченные возможности.**  Несмотря на большое количество доступных плагинов, вам может не хватить имеющихся возможностей. При помощи CMS легко создать блог, сайт-визитку, магазин, но создать уникальный проект с сложным функционалом уже вряд ли получится.
```

2023-05-02 17:11 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Ограниченные возможности.** Системы управления контентом имеют ограничения. Несмотря на большое количество доступных плагинов, вам может не хватить имеющихся возможностей. На системе управления м
опять же, вспоминаем историю про CMS как система управлением контентом сложного приложения

2023-05-02 18:27 UTC, StarHamster requested changes
Ссылки на картинки должны быть относительные 😉

2023-05-02 18:27 UTC, StarHamster commented on tools/cms/index.md
> +![Админ-панель WordPress с открытой страницей создания новой записи на сайте. Красная стрелка указывает на кнопку «Опубликовать», после нажатия которой, запись должна будет опубликоваться в блоге](/i
```suggestion
![Админ-панель WordPress с открытой страницей создания новой записи на сайте. Красная стрелка указывает на кнопку «Опубликовать», после нажатия которой, запись должна будет опубликоваться в блоге](images/publication-post.png)
```

2023-05-02 18:27 UTC, StarHamster commented on tools/cms/index.md
> +![На скриншоте показана таблица статистических данных о популярности CMS. WordPress занимает 43.2% доли рынка всех сайтов и 63.3% доли рынка CMS, другие системы управления контентом занимают очень не
```suggestion
![На скриншоте показана таблица статистических данных о популярности CMS. WordPress занимает 43.2% доли рынка всех сайтов и 63.3% доли рынка CMS, другие системы управления контентом занимают очень незначительную долю рынка](images/cms-statistics.png)
```

2023-05-03 23:58 UTC, punkmachine commented
Все остальные комментарии на днях сделаю, про них не забыл, не проигнорировал.

2023-05-06 01:06 UTC, punkmachine commented on tools/cms/index.md
> +- **Расширяемость**. CMS создаются с учётом возможности использования дополнительных плагинов. Они в свою очередь расширяют базовый функционал. Благодаря этому, большинство необходимых функциональных
Я хотел найти статистику какую-то, но кажется такой статистики вообще никто не делал.. Немного дописал с примером.

2023-05-06 01:10 UTC, punkmachine commented on tools/cms/index.md
> +- **Низкие затраты.** CMS является более доступным вариантом, чем индивидуальная разработка сайта. Кроме того, многие системы управления сайтом бесплатны, что также снижает затраты на создание проект
Хм. По идее виды сайтов на CMS я описал дальше.. 

Подключение к готову сайту, ты имела в виду Headless CMS? Или о том, чтобы подключать условный WP к уже готовому сайту?

2023-05-06 01:11 UTC, punkmachine commented
Изменил:
- Возможности CMS. Создавать веб-страницы.
- Возможности CMS. Базовая настройка.
- Преимущества CMS. Расширяемость.

2023-05-09 11:23 UTC, TatianaFokina reviewed
Вау, вот это статья!

Закинула предложения по правкам. Все стилистические.

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +Хотя CMS предлагают широкий диапазон функций и возможностей для создания и управления сайтом, они не всегда подходят для создания сайта.
```suggestion
Хотя у CMS есть много функций и возможностей для создания и управления сайтом, они не всегда подходят для его создания.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +- **Лэндинг.** Лэндинг — это одна страница, задачей которой является рекламирование продукта. Такие сайты должны быстро загружаться, обладать ярким и уникальным дизайном, на CMS будет сложно организо
```suggestion
- **Лендинг.** Это одна страница для рекламы продукта. Такие сайты должны быстро загружаться и обладать ярким и уникальным дизайном, так что на CMS это сложно сделать. Обычно на лендингах нет динамических страниц, поэтому можно смотреть в сторону конструкторов сайтов, таких как Tilda.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +- **Высоконагруженные ресурсы.** Если сайт должен выдерживать большое количество пользователей, одновременных запросов к базе данных — стоит задуматься о индивидуальной реализации.
```suggestion
- **Высоконагруженные ресурсы.** Если сайт должен выдерживать большое количество пользователей и одновременных запросов к базе данных, то подумайте про индивидуальную реализацию.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +- **Индивидуальные проекты.** Существуют категории сайтов, которые сложно или невозможно сделать с помощью типовой CMS: поисковые системы, социальные сети, форумы, CRM для бизнеса и так далее.
```suggestion
- **Индивидуальные проекты.** Есть категории сайтов, которые сложно или невозможно сделать с помощью типовой CMS. Например, поисковые системы, социальные сети, форумы, CRM (системы управления взаимоотношениями с клиентами) для бизнеса и так далее.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +Теперь поговорим о популярных CMS. Я могу выделить несколько, которые используются чаще всего для создания сайтов в последние 5-6 лет и вкратце рассказать о них.
```suggestion
Теперь поговорим о популярных CMS. Выделю и кратко расскажу о нескольких, исходя из того, какие системы чаще всего используют для создания сайтов в последние 5–6 лет.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +- **WordPress**. Самая популярная CMS на данный момент. У WordPress имеется достаточно преимуществ, которые сделали его таким популярным. Обладает огромным количеством плагинов и тем расширяющих функ
```suggestion
- **WordPress**. Самая популярная CMS на данный момент. У WordPress есть много преимуществ, которые сделали его таким популярным. Обладает большим количеством плагинов и тем, расширяющих функционал, прост в освоение и не требует практически никаких технических знаний от администратора сайта. Его используют для построения любых сайтов, но из коробки — это блог с базовым функционалом.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +- **Joomla**. Популярная CMS, которая постепенно уступает позиции WordPress-у. Из преимуществ Joomla стоит выделить гибкость и расширяемость. Но, недостатков у неё гораздо больше, относительно WordPr
```suggestion
- **Joomla**. Популярная CMS, которая постепенно уступает позиции WordPress. Преимущества — гибкость и расширяемость, но у неё больше недостатков по сравнению с WordPress. К примеру, сложный интерфейс админ-панели и меньшее количество плагинов. Используют также для построения любых типов сайтов.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +- **Drupal**. Ещё одна популярная CMS. Drupal не так известен, и уступает в популярности WordPress. Его сложно использовать, у него не такой большой выбор плагинов и тем, как у WordPress. Из преимуще
```suggestion
- **Drupal**. Ещё одна популярная CMS. Drupal не так известен и уступает в популярности WordPress. Его сложно использовать, у него не такой большой выбор плагинов и тем. Из преимуществ у этой CMS более продвинутый функционал, большая гибкость и производительность.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +- **Настройка внешнего вида**. В большинстве CMS есть встроенные настройки типографики, цветовой палитры, макета сайта и так далее. С помощью систем управления контентом можно легко создавать стандар
```suggestion
- **Настройка внешнего вида**. В большинстве CMS есть встроенные настройки типографики, цветовой палитры, макета сайта и так далее. С их помощью можно легко создавать стандартные элементы пользовательского интерфейса, например, вкладки, аккордеоны, слайдеры и другие.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +- **Управление контентом**. CMS позволяет изменять, добавлять и удалять текст, видео и изображения. Например, чтобы добавить пост в блог, сделанный на WordPress, понадобится нажать всего одну кнопку
```suggestion
- **Управление контентом**. CMS позволяет изменять, добавлять и удалять текст, видео и изображения. Например, чтобы добавить пост в блог на WordPress, нужно нажать всего одну кнопку «Добавить запись», а чтобы опубликовать написанную статью — кнопку «Опубликовать». Удобно? Безусловно.
```

2023-05-09 11:23 UTC, TatianaFokina commented on tools/cms/index.md
> +Страница редактора записей в WordPress
```suggestion
Страница редактора записей в WordPress.
```

2023-05-11 02:16 UTC, punkmachine commented on tools/cms/index.md
> +- **Трудности с a11y.** Многие CMS не обладают встроенными инструментов, которые позволили бы настроить сайт для улучшения доступности. Скорее всего, у вас не будет и плагинов для решения этой пробле
Всё время забываю слово "доступность" и пишу только a11y :(.

2023-05-11 07:44 UTC, TatianaFokina approved these changes
От меня остался только один комментарий по пункту списка, а так всё хорошо!

2023-05-12 08:33 UTC, StarHamster commented
Произошёл ддос уведами 🙈

Лови лайфхак: в гитхабе есть возможность складывать все предложения в один коммит. Делается это во вкладке «**Files changed**», кнопочка «**Add suggestion to batch**», а затем «**Commit suggestions**». Подробнее [здесь](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes) 😉

2023-05-13 20:32 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Настройка внешнего вида**. В большинстве CMS есть встроенные настройки типографики, цветовой палитры, макета сайта и так далее. С их помощью легко создавать стандартные элементы пользовательского
Тут нужно согласовать форму. (первая лучше мне кажется) 
* Создавать
* Настраивать
* Управлять

или
* Создание
* Настройка
* Управление

2023-05-13 20:49 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Базовая настройка.** Использование CMS помогает быстро настроить сайт с помощью готовых плагинов. Плагины предоставляют дополнительные функциональные возможности, такие как формы обратной связи,
угу. Можно сказать что-то вроде 
Дополнять функциональность веб-страниц при помощи плагинов

2023-05-13 20:49 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Низкие затраты.** CMS является более доступным вариантом, чем индивидуальная разработка сайта. Кроме того, многие системы управления сайтом бесплатны, что также снижает затраты на создание проект
Headless. 
По поводу низких затрат, я имела ввиду что для некоторых приложений CMS просто не стработают (например твоя страница это графический редактор фрактальных патернов :)
Т.е тут все окей, но надо как-то более обтекаемо, типа "для некоторых приложений это дешевле"

По поводу хостинга - тоже не совсем верно. Чтобы хостить проект не обязательно выделенный сервер. Раздавашки статики типа Netlify, Vercel и Github Pages тоже бесплатные 

А вот то что деплой в CMS не нужнен можно рассмартивать как достоинство

2023-05-13 20:49 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Поддержка версий.** Обновления CMS важны, так как решают баги и затыкают дыры в безопасности системы управления контентом. При этом каждое обновление движка сайта может сломать установленные плаг
```suggestion
- **Поддержка версий.** Обновления CMS важны, так как чинят баги и затыкают дыры в безопасности. При этом каждое обновление движка сайта может сломать установленные плагины и темы. Чтобы восстановить сайт, быстро откатиться не получится.
```

2023-05-13 20:49 UTC, HellSquirrel commented on tools/cms/index.md
> +- **Доступность расширений.** Выбирайте CMS с широким выбором расширений. Они понадобятся для улучшения функционала сайта.
```suggestion
- **Доступность расширений.** Лучше использовать CMS с широким выбором расширений. Они понадобятся для улучшения функционала сайта.
```

2023-05-13 20:49 UTC, HellSquirrel commented on tools/cms/index.md
> +Типа проекта влияет и на то, какую именно CMS стоит выбрать.
```suggestion
Тип проекта влияет и на то, какую именно CMS стоит выбрать.
```

2023-05-13 20:49 UTC, HellSquirrel commented on tools/cms/index.md
> +Хотя у CMS есть много функций и возможностей для создания и управления сайтом, они не всегда подходят для его создания.
```suggestion
CMS очень полезны, но подходят не для всех сайтов. 
```

2023-05-14 02:39 UTC, punkmachine commented on tools/cms/index.md
> +- **Низкие затраты.** CMS является более доступным вариантом, чем индивидуальная разработка сайта. Кроме того, многие системы управления сайтом бесплатны, что также снижает затраты на создание проект
Хм. О деплое добавил, о видах сайтов тут тоже добавил. 

О Headless добавить отдельный заголовок лучше или в преимуществах вкратце описать, что и такая возможность есть? Как лучше будет?

2023-05-14 02:49 UTC, punkmachine commented
За ддос извиняюсь, забыл о дискорде😅.

Закинул: 
- Новый пункт в преимущества, про деплой. 
- Поправил низкие затраты. 
- Поменял стиль списка в возможностях. 
- Поменял порядок пунктов в списке с возможностями. 

Вопросы:
1. Может "Возможности CMS" сменить на "Что может CMS?", учитывая новый формат списка с "создавать", "настраивать"?
2. И остался вопрос по поводу Headless, добавлять ли их отдельным заголовком или вкратце в возможностях рассказать о них.

2023-05-22 13:35 UTC, HellSquirrel commented
@punkmachine пересматриваю еще раз, вношу последние редакторские правки и катим?) Или ты хотел тут что-то еще допилить?

2023-05-22 14:05 UTC, punkmachine commented
@HellSquirrel нет, можем выкатывать. Добавить больше нечего. Спасибо!

2023-06-04 12:32 UTC, punkmachine commented
Привет! Всё окей? Правки ещё какие-то требуются?

2023-06-04 15:35 UTC, HellSquirrel commented
Приветик! Все отлично. Я просто немного приболела и как только вернусь все замержим :)

2023-06-07 01:48 UTC, punkmachine commented
> Приветик! Все отлично. Я просто немного приболела и как только вернусь все замержим :)

Выздоравливай❤️.

2023-06-08 20:37 UTC, HellSquirrel commented
@punkmachine погнали :)

2023-06-08 20:37 UTC, merged