Добавляет доку по `Intl.DateTimeFormat`
doka-guide/content pull request #4488
Opened 2023-05-29 15:14 UTC by AntonGorelov

## Описание

Closes #2417

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-05-29 17:56 UTC, HellSquirrel reviewed
Ура-ура!
Спасибо тебе большое за доку. Я принесла немножко правок и еще
давай папку переназовем через `-`.  Например intl-datetimeformat

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +`new Intl.DateTimeFormat([locales[, options]])`
Тут я бы написала чуть подробнее или наоборот удалила этот раздел :) все примеры были выше

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +`Intl.DateTimeFormat.prototype.format()` - геттер, который форматирует дату, в соответствии с языковым стандартом и параметрами форматирования этого объекта DateTimeFormat. Возвращает текущую дату в
Можно тут убрать prototype

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +`Intl.DateTimeFormat.prototype.format()` - геттер, который форматирует дату, в соответствии с языковым стандартом и параметрами форматирования этого объекта DateTimeFormat. Возвращает текущую дату в
Также я бы уточнила тип возвращаемого значения. Например - строку с текущей датой

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +`Intl.DateTimeFormat.prototype.formatToParts()` - форматирует передаваемую строку по частям с учётом `DateTimeFormat`. Возвращает массив объектов, представляющих строку даты в частях, которые можно и
Тут тоже лишний prototype

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +  console.log(part);
Было бы здорово добавить пример вывода

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +```js
... а, он просто отдельно. Давай попробуем связать как-то два этих кусочка кода. Например так:
В консоли мы получим следующее:

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +Объект [`Date`](/js/date) содержит метод [`toISOString()`](/js/date/#avtokorrekciya-daty), который возвращает строку в формате ISO (расширенный формат [ISO 8601](https://www.iso.org/iso-8601-date-and
```suggestion
У объекта [`Date`](/js/date) есть метод [`toISOString()`](/js/date/#avtokorrekciya-daty), который возвращает строку в [расширенном ISO формате](https://www.iso.org/iso-8601-date-and-time-format.html) – `YYYY-MM-DDTHH:mm:ss.sssZ`. Часовой пояс всегда равен UTC, что обозначено суффиксом "Z".
```

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +Объект `Intl.DateTimeFormat` не содержит подобного метода. При попытке указать формат `iso8601` возникает следующая ошибка:
```suggestion
Но `Intl.DateTimeFormat` почему-то не позволяет выбрать в качестве формата `iso8601`. Код, приведенный ниже, упадет с ошибкой
```

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +Идея, реализуемая Intl, в том, чтобы вернуть дату в формате, который соответствует условиям указанной локали. Intl не предоставляет способа указать определённые шаблоны форматирования. Другими словам
```suggestion
Дело в том, что Intl работает только с локалью. Так как в формате [ISO-8601](https://www.iso.org/iso-8601-date-and-time-format.html) нет никакой локали, то и отформатировать его не получится.
```

2023-05-29 17:56 UTC, HellSquirrel commented on js/Intl.DateTimeFormat/index.md
> +Следовательно, преобразовать можно вручную.
```suggestion
Но можно, преобразовать можно вручную:
```

2023-05-29 18:01 UTC, AntonGorelov commented
@HellSquirrel Полина, спасибо тебе за классное ревью! Исправлю недочеты и обновлю пр. Скажи, переименование папки не повлечет последствий или нужно содержание или что-то подобное исправить?

2023-05-29 18:06 UTC, AntonGorelov commented on js/Intl.DateTimeFormat/index.md
> +
Чуть выше написано, что этот пример иллюстрирует: `Стандартное форматирование, в зависимости от локали:`

2023-05-29 19:25 UTC, StarHamster requested changes
Привет! Крутая дока получилась! Я позволил себе тоже предложить несколько технических изменений.

P.S. А ещё лови лайфхак: в гитхабе есть возможность складывать все предложения в один коммит. Делается это во вкладке «**Files changed**», кнопочка «**Add suggestion to batch**», а затем «**Commit suggestions**». Подробнее [здесь](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes) 😉

2023-05-29 19:25 UTC, StarHamster commented on js/Intl.DateTimeFormat/index.md
> +  - AntonGorelov
в папке *people* используются только строчные буквы

```suggestion
  - antongorelov
```

2023-05-29 19:25 UTC, StarHamster commented on js/Intl.DateTimeFormat/index.md
> +`Intl.DateTimeFormat` - объект, содержащий функции форматирования даты и времени с учётом локали.
```suggestion
`Intl.DateTimeFormat` — объект, содержащий функции форматирования даты и времени с учётом локали.
```

2023-05-29 19:25 UTC, StarHamster commented on js/Intl.DateTimeFormat/index.md
> +  - `best fit` - (наилучший подходящий) позволяет среде выполнения выбрать локаль.
```suggestion
- `timeZone` — значение часового пояса: `UTC`, `America/New_York`, `Europe/Paris` и т.д.
- `calendar` — значение выбранного календаря: `chinese`, `gregory`, `indian` и т.д.
- `numberingSystem` — используемая система счисления: `arab`, `beng`, `latin` и т.д.
- `localeMatcher` — алгоритм для согласования выбранной локали:
  - `lookup` — поиск следует алгоритму поиска, определённому в [BCP 47](https://tools.ietf.org/html/rfc4647#section-3.4),
  - `best fit` — (наилучший подходящий) позволяет среде выполнения выбрать локаль.
```

2023-05-29 19:25 UTC, StarHamster commented on js/Intl.DateTimeFormat/index.md
> +`Intl.DateTimeFormat.prototype.format()` - геттер, который форматирует дату, в соответствии с языковым стандартом и параметрами форматирования этого объекта DateTimeFormat. Возвращает текущую дату в
```suggestion
`Intl.DateTimeFormat.prototype.format()` — геттер, который форматирует дату, в соответствии с языковым стандартом и параметрами форматирования этого объекта DateTimeFormat. Возвращает текущую дату в кратком виде (`dateStyle: short`).
```

2023-05-29 19:25 UTC, StarHamster commented on js/Intl.DateTimeFormat/index.md
> +`Intl.DateTimeFormat.prototype.formatToParts()` - форматирует передаваемую строку по частям с учётом `DateTimeFormat`. Возвращает массив объектов, представляющих строку даты в частях, которые можно и
```suggestion
`Intl.DateTimeFormat.prototype.formatToParts()` — форматирует передаваемую строку по частям с учётом `DateTimeFormat`. Возвращает массив объектов, представляющих строку даты в частях, которые можно использовать для настраиваемого форматирования с учётом локали.
```

2023-05-29 19:25 UTC, StarHamster commented on js/Intl.DateTimeFormat/index.md
> +`Intl.DateTimeFormat.prototype.resolvedOptions()` - возвращает новый объект со свойствами, отражающими локаль и параметры форматирования, которые вычислены при инициализации объекта.
```suggestion
`Intl.DateTimeFormat.prototype.resolvedOptions()` — возвращает новый объект со свойствами, отражающими локаль и параметры форматирования, которые вычислены при инициализации объекта.
```

2023-05-29 19:25 UTC, StarHamster commented on js/Intl.DateTimeFormat/index.md
> +получает две даты и форматирует диапазон дат наиболее кратким образом на основе языкового стандарта и параметров, предоставленных при создании экземпляра `DateTimeFormat`.
```suggestion
`Intl.DateTimeFormat.prototype.formatRange()` — получает две даты и форматирует диапазон дат наиболее кратким образом на основе языкового стандарта и параметров, предоставленных при создании экземпляра `DateTimeFormat`.
```

2023-05-29 19:25 UTC, StarHamster commented on js/Intl.DateTimeFormat/index.md
> +получает две даты и возвращает массив объектов, содержащих токены, зависящие от языкового стандарта, представляющие каждую часть отформатированного диапазона дат. Возвращает формат, аналогичный `form
```suggestion
`Intl.DateTimeFormat.prototype.formatRangeToParts()` — получает две даты и возвращает массив объектов, содержащих токены, зависящие от языкового стандарта, представляющие каждую часть отформатированного диапазона дат. Возвращает формат, аналогичный `formatToParts(date)`.
```

2023-06-08 20:53 UTC, HellSquirrel commented
> Полина, спасибо тебе за классное ревью! Исправлю недочеты и обновлю пр. Скажи, переименование папки не повлечет последствий или нужно содержание или что-то дополнительно исправить?

Не повлечет :) Прошу прощения что этот прекрасный PR провисел так долго. Пересмотрю его в ближайшее время

2023-06-25 08:47 UTC, HellSquirrel commented
@AntonGorelov приветик. Прости что долго ревьюила твой замечательный PR. Я чуть-чуть подправила текст и сейчас мы его помержим :)

2023-06-25 08:54 UTC, HellSquirrel approved these changes

2023-06-25 08:55 UTC, merged