Добавляет совет в статью про Nginx
doka-guide/content pull request #4570
Opened 2023-07-14 16:41 UTC by pa7lux

## Описание

Понял, что пора вынести эти два конфига из заметок и ходить в Доку за ними.

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-07-14 18:40 UTC, igsekor requested changes
Спасибо, Саша!

2023-07-14 18:40 UTC, igsekor commented on tools/nginx-web-server/practice/pa7lux.md
> +```
```suggestion
```nginxconf
```

2023-07-14 18:40 UTC, igsekor commented on tools/nginx-web-server/practice/pa7lux.md
> +```
```suggestion
```nginxconf
```

2023-07-14 18:40 UTC, igsekor commented on tools/nginx-web-server/practice/pa7lux.md
> +По URL-адресу `https://mydomain.com/about` откроется страница `about.html`, а по адресу `https://mydomain.com/posts` — странца `/posts/index.html`.
```suggestion
По URL-адресу `https://mydomain.com/about` откроется страница `about.html`, а по адресу `https://mydomain.com/posts` — страница `/posts/index.html`.
```

2023-07-14 18:40 UTC, igsekor commented on tools/nginx-web-server/practice/pa7lux.md
> +  server_name yourdomain.com www.yourdomain.coom;
```suggestion
  server_name mydomain.com www. mydomain.com;
```

2023-07-14 18:40 UTC, igsekor commented on tools/nginx-web-server/practice/pa7lux.md
> +  server_name yourdomain.com www.yourdomain.coom;
```suggestion
  server_name mydomain.com www. mydomain.com;
```

2023-07-14 18:41 UTC, igsekor commented on tools/nginx-web-server/practice/pa7lux.md
> +  server_name yourdomain.com www.yourdomain.coom;
Для консистентности с текстом

2023-07-14 18:41 UTC, igsekor commented on tools/nginx-web-server/practice/pa7lux.md
> +  server_name yourdomain.com www.yourdomain.coom;
Для консистентности с текстом

2023-07-15 01:42 UTC, igsekor approved these changes

2023-07-15 14:54 UTC, HellSquirrel reviewed
Чуть-чуть понакоментила :)

2023-07-15 14:54 UTC, HellSquirrel commented on tools/nginx-web-server/practice/pa7lux.md
> +1. Если приложение запускается с определённого порта, нужен ревёрс-прокси с локального хоста. Подходит, чтобы крутить на сервере NodeJS-приложения и отдавать результаты по запросу на определённый дом
```suggestion
1. Если приложение слушает определённый порт и нужен обратный прокси (reverse proxy) с локального хоста. Это решение подходит, чтобы крутить на сервере Node.js-приложения и отдавать результаты по запросу на определённый домен. Подходит, чтобы запускать Next, Nuxt, Express и всё подобное на собственном домене.
```

2023-07-15 14:54 UTC, HellSquirrel commented on tools/nginx-web-server/practice/pa7lux.md
> +
Мб добавим что-то типа
Эта конфигурация позволит обращаться к приложению, которое слушает порт 3000 по адресу yourdomain.com (без порта)

2023-07-15 14:54 UTC, HellSquirrel commented on tools/nginx-web-server/practice/pa7lux.md
> +Для простоты тут описан 80 порт, но вы, конечно же настроите себе HTTPS-сертификаты, и порт изменится. Приложение тоже может работать не на `:3000`.
```suggestion
Для простоты тут описан 80 порт, но вы, конечно же настроите себе HTTPS-сертификаты, и порт изменится на 443. Приложение тоже может использовать любой другой порт,  не обязательно `:3000`.
```

2023-07-15 14:54 UTC, HellSquirrel commented on tools/nginx-web-server/practice/pa7lux.md
> +2. Если у вас статика с HTML-страницами, бывает хочется, чтобы к HTML-страницам на сайте можно было обращаться без указания расширения. Вот так: `https://mydomain.com/hello`, а не так `https://mydoma
```suggestion
2. Бывает хочется, чтобы к вашим HTML-страницам на сайте можно было обращаться без указания расширения. Вот так: `https://mydomain.com/hello`, а не так `https://mydomain.com/hello.html`. При этом, если в дочерней директории окажется файл с именем `index.html`, нужно чтобы этот файл вызывался без указания своего имени внутри директории. Другими словами, нужен конфиг, который обслуживает такую структуру файлов:
```

2023-07-15 15:41 UTC, pa7lux commented on tools/nginx-web-server/practice/pa7lux.md
> +
ага, добавил

2023-07-16 15:29 UTC, furtivite approved these changes

2023-07-16 16:29 UTC, HellSquirrel commented
Эмейзинг. Спасибо ❤️

2023-07-16 16:29 UTC, merged