Исправляет и уточняет статью про :has()
doka-guide/content pull request #4621
Opened 2023-07-29 14:45 UTC by wonder-SMA

## Описание

Исправляет неточность про вес селектора и уточняет набором подсказок статью про :has() 

Closes #4619

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-07-29 15:16 UTC, StarHamster requested changes
Привет, я тут мимо крокодил и заметил твой замечательный пулреквест. Парсер доки не умеет в такое форматирование строк и ставит перенос строки `<br>`. Поэтому предложил пару косметических изменений

^_~

2023-07-29 15:16 UTC, StarHamster commented on css/has/index.md
> +`:where()` правило применится только к тому селектору, который был описан **до** `:has()`.
```suggestion
Функция-псевдокласс `:has()` принимает один или несколько селекторов в качестве аргумента. В отличие от `:is()` и `:where()` правило применится только к тому селектору, который был описан **до** `:has()`.
```

2023-07-29 15:16 UTC, StarHamster commented on css/has/index.md
> +selector2)` и применит стили в случае валидности селекторов selector2 и selector3:
```suggestion
💡 Использование псевдокласса `:has()` влияет на [специфичность](/css/specificity/), т. е. при расчёте веса селектора учитывается как целевой селектор, так переданный в аргументах.

💡 Переданные через запятую селекторы `:has(selector1, selector2)` браузер проверяет аналогично `(selector1 OR selector2)`. Если действительным является только один из переданных селекторов, то браузер выберет его. Но если передано несколько валидных селекторов, то браузер выберет селектор с наибольшим весом.

💡 Есть возможность соединять селекторы. Такую запись браузер интерпретирует аналогично `(selector1 AND selector2)` и применит стили в случае валидности селекторов selector2 и selector3:
```

2023-07-29 15:16 UTC, StarHamster commented on css/has/index.md
> +выполнении поиска селектора.
```suggestion
💡 Псевдокласс `:has()` не может быть вложен в другой `:has()`, так как это может привести к циклическим запросам при выполнении поиска селектора.
```

2023-07-29 15:40 UTC, wonder-SMA commented
> Привет, я тут мимо крокодил и заметил твой замечательный пулреквест. Парсер доки не умеет в такое форматирование строк и ставит перенос строки `<br>`. Поэтому предложил пару косметических изменений
> 
> ^_~

Привет. Ага, спасибо, не знал про это. Подправил.

2023-08-01 12:44 UTC, wonder-SMA commented
> Спасибо за очень полезный пиар!
> 
> Оставила пару комментариев и вопрос =)

Спасибо) Поправил статью. Все-таки посчитал оставить двоеточие в подсказках, так как ниже подсказки идет пример. В Доке видел такое же)

2023-08-01 17:34 UTC, solarrust reviewed
Супер! Мы на финишной прямой! Остался буквально один момент и можно в продакшен =)

2023-08-01 17:34 UTC, solarrust commented on css/has/index.md
> +Функция-псевдокласс `:has()`позволяет уточнить основной селектор дополнительным.
А уточнить чтобы что? Это же по факту единственный способ стилизовать родителя через условие ребёнка в CSS. Кажется, это заслуживает внимания

2023-08-02 17:04 UTC, solarrust approved these changes
Амэйзинг! 💫

Пиши ещё, у тебя отлично получается =)

2023-08-07 09:09 UTC, solarrust approved these changes

2023-08-07 09:40 UTC, merged