Актуализирует доку про `text-align`
doka-guide/content pull request #4637
Opened 2023-08-01 14:06 UTC by reznikovAndrey

## Описание

Актуализировал доку про `text-align`, убрав лишнее и добавив раздел "На практике" и интерактивное демо.

Closes #4316 

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-08-07 09:37 UTC, solarrust reviewed
Спасибо большое за твой вклад! Получилось хорошо =)

Предложила несколько небольших правок.

@skorobaeus, пожалуйста, загляни сюда поревьюить демки.

2023-08-07 09:37 UTC, solarrust commented on css/text-align/index.md
> +`text-align` регулирует то, как линейное содержимое (к примеру текст) будет выравниваться по горизонтали в блоке родительского элемента.
```suggestion
`text-align` управляет выравниванием контента (к примеру текста) по горизонтали внутри родительского элемента.
```

Не встречала раньше термин «линейное содержимое». Немного упростила предложение. Посмотри, пожалуйста, ок ли так?

2023-08-07 09:37 UTC, solarrust commented on css/text-align/index.md
> +Если это свойство не задано, то выравнивание определяется правилами текущего языка (значение атрибута `lang` у тега [`<html>`](/html/html/)), либо значением свойства `direction` (`ltr` - слева направ
```suggestion
Если это свойство не задано, то выравнивание определяется правилами текущего языка (значение атрибута `lang` у тега [`<html>`](/html/html/)), либо значением свойства `direction` (`ltr` — слева направо, `rtl` — справа налево).
```

2023-08-07 09:37 UTC, solarrust commented on css/text-align/index.md
> +Возможные значения:
```suggestion
```

2023-08-07 09:37 UTC, solarrust commented on css/text-align/index.md
> +## Интерактивный пример
```suggestion
```

2023-08-07 09:37 UTC, solarrust commented on css/text-align/practice/reznikovandrey.md
> +Тэг [`img`](/html/img/) является строчным (`display: inline`).
```suggestion
Тег [`<img>`](/html/img/) является строчным (`display: inline`).
```

2023-08-07 09:37 UTC, solarrust commented on css/text-align/practice/reznikovandrey.md
> +Чтобы выровнять его по горизонтали необходимо:
```suggestion
Один из вариантов выравнивания картинки по горизонтали:
```

Тут чуть уточнила, потому что можно выровнять по горизонтали при помощи флексов или гридов, не только предложенным способом.

2023-08-07 09:37 UTC, solarrust commented on css/text-align/practice/reznikovandrey.md
> +1. Чтобы родитель был блочным элементом (`display: block`).
```suggestion
1. Убедиться, что родитель является блочным элементом (`display: block`).
```

2023-08-07 10:01 UTC, skorobaeus requested changes
Привет! Ого, даже свойство `text-align` не стоит на месте :) Спасибо большое!

Я чутка поредактировала стили, сделала солиднее размеры текста и отступов ✌

Единственное, о чём попрошу, это заменить `Lorem ipsum...` на какой-нибудь текст на русском языке. Я обычно использую цитаты из классики, многие контрибьюторы пишут там шутки. Так душевнее :)

2023-08-08 13:34 UTC, reznikovAndrey commented on css/text-align/index.md
> +`text-align` регулирует то, как линейное содержимое (к примеру текст) будет выравниваться по горизонтали в блоке родительского элемента.
да, вполне)

2023-08-09 10:03 UTC, skorobaeus approved these changes

2023-08-15 08:42 UTC, solarrust approved these changes
Спасибо большое за актуализацию доки ♥️
Пожалуйста, пиши ещё!

2023-08-15 08:42 UTC, merged