Обновляет демки в `aspect-ratio`
doka-guide/content pull request #4646
Opened 2023-08-03 07:16 UTC by StarHamster

## Описание

Немного поменял радио-кнопки, добавил Roboto Mono для кода

Было:

![Screen Shot 2023-08-03 at 14 11 37](https://github.com/doka-guide/content/assets/91747573/7b0f37c7-6226-493e-aa12-941cc488cb6e)

Стало:

![Screen Shot 2023-08-03 at 14 07 22](https://github.com/doka-guide/content/assets/91747573/b543647b-7908-4cdd-920b-4bebe206c97c)

Было2:

![Screen Shot 2023-08-03 at 14 12 44](https://github.com/doka-guide/content/assets/91747573/eb2592c7-f497-4555-9bd7-f3e921b3ae5c)

Стало2:

![Screen Shot 2023-08-03 at 14 14 56](https://github.com/doka-guide/content/assets/91747573/e24dd8b4-263e-4e5e-970f-2feb48c299f5)

## Ссылк

https://content-4646.dev.doka.guide/css/aspect-ratio/

2023-08-03 11:51 UTC, skorobaeus requested changes
Вот мы и добрались до радиокнопок :) Ура!

По кнопкам у меня вопросов нет. Пока есть возможность, хочется доработать плашки с aspect-ratio. Так как это идентичные по смыслу элементы в обеих демках, то и оформлять их лучше одинаково. Также инвертировала цвета, чтобы плашка хорошо читалась и поверх картинки, и поверх градиента.

2023-08-03 11:51 UTC, skorobaeus commented on css/aspect-ratio/demos/aspect-ratio-auto/index.html
> +    }
```suggestion
    .block code {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: #000000;
      color: #FFFFFF;
      border-radius: 5px;
      padding: 5px 10px;
      font-family: "Roboto Mono", monospace;
      font-size: calc(1em - 1px);
      white-space: nowrap;
    }
```

2023-08-03 11:51 UTC, skorobaeus commented on css/aspect-ratio/demos/aspect-ratio-auto/index.html
> +    }
```suggestion
    .block img {
      display: block;
      width: 100%;
    }
```

2023-08-03 11:51 UTC, skorobaeus commented on css/aspect-ratio/demos/variants/index.html
> +    }
```suggestion
    code {
      background-color: #000000;
      color: #FFFFFF;
      border-radius: 5px;
      padding: 5px 10px;
      font-family: "Roboto Mono", monospace;
      font-size: calc(1em - 1px);
    }
```

2023-08-03 11:51 UTC, skorobaeus commented on css/aspect-ratio/demos/variants/index.html
> +    }
```suggestion

    .block {
      display: grid;
      place-items: center;
      width: 420px;
      transition: all 300ms ease-in-out;
      background: linear-gradient(
        225deg,
        #B5F5EC 0%,
        #2E9AFF 100%
      );
    }
```

2023-08-04 05:36 UTC, StarHamster commented
Да, так действительно гораздо лучше, спасибо за предложения 🤩

2023-08-04 09:13 UTC, skorobaeus approved these changes

2023-08-07 09:11 UTC, solarrust approved these changes

2023-08-07 09:11 UTC, merged