Улучшает `border-radius`
doka-guide/content pull request #4664
Opened 2023-08-10 15:25 UTC by StarHamster

## Описание

Потрогал демки, удалил часть статьи (#4657). Получилось спорно во всём: и в удалении части статьи (@solarrust), и в огромных демках (@skorobaeus) — одна высотой 840 пикселей и другая 610 😐

Поэтому давайте обсуждать 😉

Closes #4657

## Демки

Было:

![Screen Shot 2023-08-10 at 22 17 04](https://github.com/doka-guide/content/assets/91747573/0ad6db31-e8f0-4223-999c-bb7c1db87aa3)

Стало:

![Screen Shot 2023-08-10 at 22 17 15](https://github.com/doka-guide/content/assets/91747573/87a31ca9-fc3e-4e71-a41e-a2e42ffb9a88)

Было2:

![Screen Shot 2023-08-10 at 22 17 53](https://github.com/doka-guide/content/assets/91747573/4791df53-13a6-4579-abe6-5665a40748e8)

Стало2:

![Screen Shot 2023-08-10 at 22 18 17](https://github.com/doka-guide/content/assets/91747573/36cc981a-2175-4126-bf9a-3fa89809a53f)

Было3:

![Screen Shot 2023-08-10 at 22 18 45](https://github.com/doka-guide/content/assets/91747573/6c406160-eaab-438f-bbea-841447255925)

Стало3:

![Screen Shot 2023-08-10 at 22 19 02](https://github.com/doka-guide/content/assets/91747573/57ca819c-14c9-4503-9711-9842c9024e9a)

Было4:

![Screen Shot 2023-08-10 at 22 19 49](https://github.com/doka-guide/content/assets/91747573/3ef32280-09e5-4d3e-bfb8-25b7d71fb33d)

Стало4:

![Screen Shot 2023-08-10 at 22 20 06](https://github.com/doka-guide/content/assets/91747573/81c6b92d-2217-43f1-affd-28febcb03e93)

## Ссылка

https://content-4664.dev.doka.guide/css/border-radius/

2023-08-11 10:29 UTC, skorobaeus requested changes
Привет!

Пришла развеять твои сомнения :)

2023-08-11 10:29 UTC, skorobaeus commented on css/border-radius/demos/different-blocks/index.html
>        height: 200px;
Дока не боится высоких демок, но тут, и правда, столько места занимать ни к чему. Простое решение — сделать блоки меньше размером. Если вынести из них текст и разместить его сбоку (как в демке "half-radius"), то они смогут быть ещё меньше :)

Однако, я бы где-нибудь в демке написала значение `border-radius`, чтобы она была понятной сама по себе, даже будучи вырванной из контекста.

По итогу этих двух правок мы, скорее всего, останемся при той же высоте демки, но она станет лучше доносить информацию, а это главный приоритет :)

2023-08-11 10:29 UTC, skorobaeus commented on css/border-radius/demos/different-blocks/index.html
> +      border-radius: 5em / 50%;
Кажется, если задать примерно `border-radius: 2em / 50%;`, то становится лучше видно, как работает такое значение `border-radius`.

2023-08-11 10:29 UTC, skorobaeus commented on css/border-radius/demos/notification/index.html
> +      background-image: url(../../images/doka.svg);
Ой какая славная иконка получилась ^_^

Если нужно вписать булочку в квадрат, лучше оставить только глазки и носик, или даже только носик. И их можно писать символами: •ᴥ•

2023-08-11 10:29 UTC, skorobaeus commented on css/border-radius/index.md
> -Если при нажатии добавлять кнопке внутреннюю тень такого же цвета, что и фон, она будет «нажиматься» — получится привлекательно и современно 😉
Это одна из старых док и тут, и правда, стиль повествования немного не совпадает с нынешним. Чтобы не удалять, я бы перенесла в "На практику", наверное.

2023-08-11 10:29 UTC, skorobaeus commented on css/border-radius/demos/half-radius/index.html
> +      height: 150px;
Здесь, опять же, можно уменьшить блоки без потери смысла. Давай сделаем этот размерами 125 на 125.

А двух его напарников снизу сделаем явно прямоугольными — 125 на 250.

2023-08-13 16:00 UTC, StarHamster commented on css/border-radius/demos/notification/index.html
> +      background-image: url(../../images/doka.svg);
Точно-точно не хотим оставить svg картинку с ушками? 🥹🥹

![image](https://github.com/doka-guide/content/assets/91747573/baa53364-b41c-4d23-9975-ce34e4d26274)

![image](https://github.com/doka-guide/content/assets/91747573/fe449814-94b5-4605-9139-feb5c48344e0)

![image](https://github.com/doka-guide/content/assets/91747573/9e87891b-2759-4c85-bedf-3851a2c2e039)

2023-08-15 14:44 UTC, StarHamster commented on css/border-radius/index.md
> -Если при нажатии добавлять кнопке внутреннюю тень такого же цвета, что и фон, она будет «нажиматься» — получится привлекательно и современно 😉
Даже если переносить в раздел «На практику», то не в эту доку. Ну совсем не подходит описанное под тему статьи

2023-08-28 11:50 UTC, skorobaeus commented on css/border-radius/demos/notification/index.html
> +      background-image: url(../../images/doka.svg);
Точно-точно :) Это кусок из фирстиля, можно сказать :)

2023-08-28 11:51 UTC, skorobaeus commented on css/border-radius/index.md
> -Если при нажатии добавлять кнопке внутреннюю тень такого же цвета, что и фон, она будет «нажиматься» — получится привлекательно и современно 😉
@solarrust а что ты думаешь?

2023-08-28 15:57 UTC, solarrust commented on css/border-radius/index.md
> -Если при нажатии добавлять кнопке внутреннюю тень такого же цвета, что и фон, она будет «нажиматься» — получится привлекательно и современно 😉
Давайте это обсудим в отдельном пиаре, а тут сосредоточимся на демке. Ок?

2023-09-04 12:38 UTC, StarHamster commented on css/border-radius/index.md
> -Если при нажатии добавлять кнопке внутреннюю тень такого же цвета, что и фон, она будет «нажиматься» — получится привлекательно и современно 😉
Т.е. в этом ПР мне вернуть этот кусок как есть?

2023-09-04 12:40 UTC, StarHamster commented on css/border-radius/demos/notification/index.html
> +      background-image: url(../../images/doka.svg);
Так, давай проясним: а можно ли тогда svg носик? Или его обязательно символами (ещё раз упомяну проблему отсутствия нужного шрифта)?

2023-09-05 12:18 UTC, solarrust commented on css/border-radius/index.md
> -Если при нажатии добавлять кнопке внутреннюю тень такого же цвета, что и фон, она будет «нажиматься» — получится привлекательно и современно 😉
Ага, тут не трогать его, принести отдельный пиар.

2023-09-05 16:54 UTC, skorobaeus commented on css/border-radius/demos/notification/index.html
> +      background-image: url(../../images/doka.svg);
Да можно, конечно, svg-носик! Тем более, если нет нужного шрифта))))

2023-09-13 15:27 UTC, skorobaeus approved these changes

2023-09-27 19:21 UTC, solarrust approved these changes
Прости за задержку с ревью 🫣
Спасибо большое за твой вклад =)

2023-09-27 19:21 UTC, merged