Добавляет ответ на вопрос о разнице между операторами == и ===
doka-guide/content pull request #4683
Opened 2023-08-22 13:00 UTC by AndreiDetenkov

## Описание

Добавил ответ на вопрос о разнице между операторами == и ===

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-08-22 13:11 UTC, HellSquirrel reviewed
Супер! Добавила небольшой комментарий
Если тебя еще нет в папке [people](https://github.com/doka-guide/content/tree/main/people) добавься пжлст прямо в этом PR

2023-08-22 13:11 UTC, HellSquirrel commented on interviews/strict-equal/answer/andreidetenkov/index.md
> +которые мы используем, чтобы определить, равны или нет два значения.
```suggestion
которые проверяют равенство своих операндов
```

2023-08-22 13:11 UTC, HellSquirrel commented on interviews/strict-equal/answer/andreidetenkov/index.md
> +При сравнении переменных сначала проверяется, отличаются ли их типы.
Очень круто! 1 в 1 как в спецификации

2023-08-22 15:56 UTC, AndreiDetenkov commented on interviews/strict-equal/answer/andreidetenkov/index.md
> +которые мы используем, чтобы определить, равны или нет два значения.
не уверен на счет операндов =)

2023-08-22 15:59 UTC, AndreiDetenkov commented
> Супер! Добавила небольшой комментарий Если тебя еще нет в папке [people](https://github.com/doka-guide/content/tree/main/people) добавься пжлст прямо в этом PR

вроде добавил папкой в people

2023-08-23 10:04 UTC, StarHamster requested changes
Я тут мимо крокодил и решил заглянуть в этот замечательный ПРчик. Принёс пару технических правок:

1. Переместил мету из файла ответа в файл вопроса и поправил её.
2. Убрал перенос строки у абзацев, потому что парсер Доки немного глуповат и расставит там `<br>`.
3. Убрал разделители строк: обычно мы их не используем в Доке.

P.S. Если хочешь, чтобы все предложенные изменения уместились в один коммит, то во вкладке «Files changed» нажми на кнопку «Add suggestion to batch» у нужных предложений, а затем — «Commit suggestions». А можешь забить, история коммитов в ПР не так принципиальна 🤪

2023-08-23 10:17 UTC, HellSquirrel approved these changes

2023-08-23 10:17 UTC, HellSquirrel commented
Все супер, сейчас соберется и раскатаем. Спасибо тебе большое. Приходи еще обязательно :)

2023-08-23 10:25 UTC, StarHamster requested changes
На финишной прямой 🏁

Осталось папку *answer* переименовать в *answers* и всё починится

2023-08-23 10:33 UTC, StarHamster approved these changes
🔥🔥

2023-08-27 20:38 UTC, merged

2023-08-27 20:39 UTC, HellSquirrel commented
Отличная работа! Спасибо вам