Добавляет описание второго аргумента метода .include()
doka-guide/content pull request #4764
Opened 2023-10-08 05:18 UTC by ScrabyQ

## Описание

Добавлена информация про второй аргумент метода .include() с примером использования.

Closes #4756

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-10-08 14:45 UTC, levinside commented on js/includes/index.md
> +- При указании отрицательного значения аргумента поиск все равно будет производиться от начала и до конца массива/строки.
Нет, при указании отрицательного значения - будет рассчёт позиции с которой начать поиск.

2023-10-08 14:50 UTC, levinside commented on js/includes/index.md
> +- При указании отрицательного значения аргумента поиск все равно будет производиться от начала и до конца массива/строки.
И если вычисленное значение <0 — тогда с начала стоки, иначе с полученного значения.
Пример:
– длинна массива =3, значение второго параметра = (-2).
– вычисленная позиция = 3 + (-2) = 1
→ поиск будет производиться начиная со второго элемента массива (помним что позиции элемента в массиве начинается с 0)

2023-10-14 10:00 UTC, HellSquirrel reviewed
Приветик! Большое спасибо за правки. Давай чуть подправим по моим комментариям и помержим :)

2023-10-16 21:02 UTC, levinside commented
@HellSquirrel Интересно - а в чей-то PR, добавлять новые комиты могет только автор PR + владелец репозитория?

2023-10-24 20:41 UTC, HellSquirrel commented
> 
@HellSquirrel Интересно - а в чей-то PR, добавлять новые комиты могет только автор PR + владелец репозитория?
Все так, но ты можешь сделать форк в форк кажется :)

2023-10-25 16:42 UTC, HellSquirrel approved these changes

2023-10-26 11:40 UTC, levinside requested changes
Сделал PR в репозиторий @ScrabyQ с парой правок орфографии. Не уверен в том как это работает, но.. судя по всему если PR будет принят, то и тут появится дополнительный комит...

2023-10-27 09:40 UTC, ScrabyQ commented
Смержил изменения @levinside в свой репо
Изменения тут появились, но коммит с мержем оформлен не по правилам. 
Норм?

2023-11-02 18:49 UTC, HellSquirrel commented
все оке, спасибо большое :)

2023-11-02 18:50 UTC, HellSquirrel approved these changes

2023-11-02 18:50 UTC, merged