Add demo and practice guide for performance measurement
doka-guide/content pull request #4770
Opened 2023-10-10 14:52 UTC by meded90

## Описание

Добавил пример и мненее эксперта как исползовать chrome devtool c  performance

Closes #

## Чек-лист

- [+] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [+] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [+] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-10-14 09:25 UTC, HellSquirrel reviewed
Приветик! Спасибо большое за этот PR. Как ты смотришь на то чтобы перенести этот пример в раздел рецепты? Кажется там он будет очень органично смотреться :)

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/demos/meded90/index.html
> +  <title>Измерение времени работы иерархий медленных  функций – Performance – Doka</title>
Давай немного подправим заголовок. Раскроем термин "иерархия медленных функций"

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/demos/meded90/index.html
> +        <li> Откройте devtools -> Performance  </li>
```suggestion
        <li>Откройте developer tools и перейдите в раздел Performance </li>
```

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/demos/meded90/index.html
> +        <li> Кликтие на круглу  кнопку  для начла записи или <code>ctrl+e</code></li>
```suggestion
        <li>Нажмите круглую  кнопку  для начла записи или <code>ctrl+e</code></li>
```

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/demos/meded90/index.html
> +    const slow = function() {
давай переназовем эту функцию, например так + сделаем единообразно либо function expression либо declaration
```suggestion
    const performSlowCalculation = function() {
```

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/demos/meded90/index.html
> +      performance.mark('function_1 start')
Давай попробуем сделать mark более читаемыми, например так: 
```suggestion
      performance.mark('first slow iteration')
```

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/demos/meded90/index.html
> +      function_1()
Давай попробуем использовать camelCase для названия функций

```suggestion
      function_1()
```

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/practice/meded90.md
> +Так же удобно отлаживать производительность через вкладку chorome ->  devtools -> Performance,
```suggestion
Удобно анализировать производительность при помощ вкладки Performance в инструментах разработчика.
```

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/practice/meded90.md
> +потому что вызовы `performance.mark()` и `performance.measure()` будут отбросаться в разделе `Timings` после записи
```suggestion
Вызовы `performance.mark()` и `performance.measure()` будут отбросаться в разделе `Timings` после записи.
```

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/practice/meded90.md
> +![панель отладки производительности с performance.mark](images/img.png)
```suggestion
![панель отладки производительности с `performance.mark`](images/img.png)
```

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/practice/meded90.md
> +Может появиться желание написать декоратор или функцию обертку для `performance.mark()` и `performance.measure()`,
Можешь немного раскрыть что тут имеется ввиду и привести какие-нибудь измерения. Например так: 
Если вы используете performance.measure не добавляя дополнительных оберток будет так-то...
Если вы используете обертку значения изменятся так-то...

2023-10-14 09:25 UTC, HellSquirrel commented on js/performance/practice/meded90.md
> +Например react все компоненты были обернуты в подобный декоратор в dev режиме, но в react 17 версии они убрали его из проблем с производительностью.
Давай тут тоже немного раскроем? Можешь привести ссылку-пример с тем как именно использовались эти обертки?

2023-10-16 14:49 UTC, skorobaeus requested changes
Привет! Спасибо за ПР :) Я поревьюю демки и буковки :)

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/demos/meded90/index.html
Папки мы стараемся называть парой английских слов, примерно отражающих то, что написано в `<title></title>`, где, в свою очередь, отражаем суть демки :) Т.к. эта демка про отладку при помощи devtools, можно папку назвать, например, `functions-measure-devtools`.

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/demos/meded90/index.html
> +    <main>
Main можно убрать из разметки, в демке не очень много содержимого и всё оно важное, так что этот тег семантики особо не придаёт.

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/demos/meded90/index.html
> +    <div id="container">
Давай выровняем этот контейнер по центру по вертикали и по горизонтали? Флексами, гридами — любым удобным тебе способом :)

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/demos/meded90/index.html
> +        <li> Кликтие на круглу  кнопку  для начла записи или <code>ctrl+e</code></li>
Наш стайлгайд велит писать через пробел, а не через плюс :)

```suggestion
        <li>Нажмите круглую кнопку для начала записи или <code>Ctrl E</code></li>
```

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/demos/meded90/index.html
> +          Нажмите для старта мелденых  функций - <button id="start-button" class="button">Запустить</button>
```suggestion
          Нажмите для старта медленных функций — <button id="start-button" class="button">Запустить</button>
```

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/demos/meded90/index.html
> +        <li> Нжамите красную кнопку для остоновки записи или <code>ctrl+e</code></li>
```suggestion
        <li>Нажмите красную кнопку для остановки записи или <code>Ctrl E</code></li>
```

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/practice/meded90.md
> +Так же удобно отлаживать производительность через вкладку chorome ->  devtools -> Performance,
```suggestion
Удобно анализировать производительность при помощи вкладки Performance в инструментах разработчика.
```

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/practice/meded90.md
> +потому что вызовы `performance.mark()` и `performance.measure()` будут отбросаться в разделе `Timings` после записи
```suggestion
Вызовы `performance.mark()` и `performance.measure()` будут отображаться в разделе `Timings` после записи.
```

2023-10-16 14:49 UTC, skorobaeus commented on js/performance/demos/meded90/index.html
> +    }
У нас есть стили для кнопок, можно скопировать отсюда: https://github.com/doka-guide/content/blob/main/docs/demos/style.md#%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8

2023-11-02 18:49 UTC, HellSquirrel commented
@meded90 посмотришь правки или мне перехватить этот PR?

2023-12-10 11:35 UTC, TatianaFokina commented
Чуть-чуть попричёсывала демку и поредачила текст.

Что осталось:

- [] подправить заголовок демки: раскрыть термин «иерархия медленных функций»;
- [] немного раскрыть, что имеется в виду в части про желание добавить функцию-обёртку и привести какие-нибудь измерения. Например, так: «Если вы используете performance.measure не добавляя дополнительных оберток будет так-то...» или «Если вы используете обертку значения изменятся так-то...»;
- [] Немного раскрыть про то, как раньше было в React: можно привести ссылку-пример с тем, как именно использовались обёртки.

2023-12-12 11:32 UTC, skorobaeus approved these changes

2023-12-16 22:53 UTC, HellSquirrel commented on js/performance/demos/functions-measure-devtools/index.html
> +  <title>Измерение времени работы иерархий медленных функций – performance – Дока</title>
```suggestion
  <title>Анализ производительности приложения – performance – Дока</title>
```

2023-12-16 23:16 UTC, HellSquirrel commented on js/performance/practice/meded90.md
> +Может появиться желание написать декоратор или функцию-обёртку для `performance.mark()` и `performance.measure()` и обернуть в неё всё приложение. Этого не стоит делать, потому что затраты на `perfor
Может возникнуть желание написать обёртку вокруг `performance.mark()` и `performance.measure()` и поместить в неë все приложение. Например так:
```js
const withPerformanceMeasure = (markName, functionToAudit) => {
      performance.mark(`${markName}-before`)
      functionToAudit()
      performance.mark(`${markName}-after`)
      performance.measure(`${markName}-before`,`${markName}-after`)
}

// ...
withPerformanceMeasure(myApp)
```
Этого не стоит делать. Затраты на выполнение функции `performance.mark()` минимальны, но не нулевые. Например, раньше в React все компоненты были обёрнуты в подобную функцию в dev-режиме, но в React версии 17 эту функциональность убрали из-за проблем с производительностью.


Еще пруфчекнула историю про 17 реакт, но ничего там не нашла. Вот тут по ссылке https://github.com/facebook/react/blob/main/CHANGELOG.md покажите куда смотреть :)

2023-12-19 10:12 UTC, TatianaFokina commented on js/performance/practice/meded90.md
> +Может появиться желание написать декоратор или функцию-обёртку для `performance.mark()` и `performance.measure()` и обернуть в неё всё приложение. Этого не стоит делать, потому что затраты на `perfor
Я тоже не нашла. @meded90, поможешь найти в ченджлоге, где они там это исправили?

2023-12-20 11:58 UTC, TatianaFokina commented on js/performance/practice/meded90.md
> +Может появиться желание написать декоратор или функцию-обёртку для `performance.mark()` и `performance.measure()` и обернуть в неё всё приложение. Этого не стоит делать, потому что затраты на `perfor
Я поискала за пределами ченджлога и тоже ничего не нашла. Предлагаю либо удалить упоминание про React, либо привести другой пример, если есть.

2023-12-29 16:16 UTC, HellSquirrel approved these changes

2023-12-29 16:17 UTC, merged