Добавляет рецепт с написанием попапа и демку к нему
doka-guide/content pull request #4805
Opened 2023-10-24 15:00 UTC by AnnaBaraulina

## Описание

Добавляет рецепт с реализацией попапа на <dialog> и демку к нему

Closes #2733

## Чек-лист

- [y] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [y ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [y ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2023-10-24 16:52 UTC, TatianaFokina commented on recipes/popup/demos/popup-demo/index.html
> +  <dialog class="child" id="myDialog">
Всё круто! Можно немного улучшить только вот как: модалку, всё же, располагать после кнопки, которая её открывает. А ещё навесить на кнопочку для открытия попапа `aria-haspopup="dialog"` и `aria-controls` с любой строкой текста без слеша. Модалке же нужно задать `id` с таким же значением, как у `aria-controls`.

2023-10-24 19:29 UTC, AnnaBaraulina commented on recipes/popup/demos/popup-demo/index.html
> +  <dialog class="child" id="myDialog">
> Всё круто! Можно немного улучшить только вот как: модалку расположить в коде после кнопки, которая её открывает. А ещё навесить на кнопочку для открытия попапа `aria-haspopup="dialog"` и `aria-controls` с любой строкой текста без слеша. Модалке нужно задать `id` с таким же значением, как у `aria-controls`.
> 
> `aria-controls` устанавливает программную связь между кнопкой и попапом, которая полезна для вспомогательных технологий. `aria-haspopup` даёт таким технологиям знать, что у элемента есть диалог, то есть рассказывает о типе попапа.
> 
> Ещё можно расположить попап по центру и не показывать, что всё заблокировано с ним. И, если есть силы, добавить внутрь попапа что-то фановое. Можно какую-нибудь шуточную просьбу о подписке или типа того 😄

Спасибо!) Все сделаю! Я только не поняла про "не показывать, что всё заблокировано с ним" - не нужно блокировать скролл?

2023-10-24 20:14 UTC, TatianaFokina commented on recipes/popup/demos/popup-demo/index.html
> +  <dialog class="child" id="myDialog">
Имею в виду, что можно отпозиционировать кнопочку по центру без зелёной рамки вместе с попапом и подправить высоту демки в тексте под это дело.

2023-10-29 08:08 UTC, AnnaBaraulina commented
@TatianaFokina привет! Я хотела посоветоваться насчет демки, мне она не очень нравится в нынешнем варианте. Если не открывать ее в отдельной вкладке, не очевидно, что там вообще что-то есть, так как до кнопки приходится скроллить вниз. При этом мне хотелось показать в статье, как с помощью модалки заблокировать скролл страницы. Может быть мне сделать две демки: в начале статьи оставить нынешнюю , но удалив у body высоту, а в том месте, где пишу про блокировку скролла добавить демку как у меня была изначально?

2023-10-30 09:59 UTC, solarrust commented
Привет! Подкину идею. Можно добавить на «страницу» демки какой-то контент. Например, несколько фотографий котиков. А кнопку открытия попапа, например, фиксированным позиционированием повесить в нижнем правом углу. Тогда и страница будет скроллиться и кнопка открытия всегда будет «под рукой».

2023-10-30 10:03 UTC, AnnaBaraulina commented
> Привет! Подкину идею. Можно добавить на «страницу» демки какой-то контент. Например, несколько фотографий котиков. А кнопку открытия попапа, например, фиксированным позиционированием повесить в нижнем правом углу. Тогда и страница будет скроллиться и кнопка открытия всегда будет «под рукой».

Это без проблем, только Таня перед этим наоборот попросила спозиционировать кнопку по центру (изначально была в верхнем левом углу). Делаю в правом нижнем тогда?

2023-10-30 10:08 UTC, AnnaBaraulina commented
Фиксированным будет симпатичнее всего,конечно, так и сделаю, спасибо

2023-10-30 10:29 UTC, TatianaFokina commented
> Это без проблем, только Таня перед этим наоборот попросила спозиционировать кнопку по центру (изначально была в верхнем левом углу). Делаю в правом нижнем тогда?

Таня перед этим тупанула 😅 Мне нравится идея Алёны.

2023-10-31 08:52 UTC, StarHamster requested changes
Привет! Линтер ругается на отсутствие пустой строки в конце файла 😉

2023-10-31 08:52 UTC, StarHamster commented on recipes/popup/demos/popup-demo/index.html
> +</html>
```suggestion
</html>

```

2023-11-14 12:57 UTC, AnnaBaraulina commented
Привет, всем! От меня нужны какие-то еще доработки? 
Вижу конфликт файлов, но не могу понять, откуда взялся .yaspeller.json

2023-11-14 14:23 UTC, TatianaFokina commented
@AnnaBaraulina, я там слегка переделала демку. Пока, наверное, лучше не заменять примеры в тексте на более актуальные, Света может что-то добавить и изменить.

Пока предлагаю выбрать топ-4 самых мемных котика, а остальные картинки удалить.

2023-11-15 07:45 UTC, skorobaeus commented
Ребята, вы такие классные 🥺

Поддерживаю Таню, четырёх котиков достаточно, чтобы скролл был даже на исполинском десктопе.

От себя предлагаю на мобилках кнопку выровнять по центру по горизонтали, всё-таки. А то при малой ширине экрана такой сдвиг выглядит странно:

![image](https://github.com/doka-guide/content/assets/29401439/5eeb81ce-078f-4331-9517-cdc7bfc4ddbd)

2023-11-16 14:49 UTC, TatianaFokina approved these changes

2023-11-16 14:49 UTC, TatianaFokina commented
Я добавила папочку автора, можешь что-то написать о себе в файлике, если хочешь.

2023-11-16 15:53 UTC, AnnaBaraulina commented
> Я добавила папочку автора, можешь что-то написать о себе в файлике, если хочешь.

Я написала там чуть,  спасибо!:)

2023-11-16 17:26 UTC, TatianaFokina commented
@solarrust, посмотришь этот пиар?

2023-11-18 17:07 UTC, StarHamster approved these changes
Турбо-пушка! Можно только мемы через tinypng прогнать и вообще будет супер

2023-11-21 14:12 UTC, solarrust approved these changes
🤩

2023-11-21 14:13 UTC, merged