Добавляет статью про media
doka-guide/content pull request #508
Opened 2021-05-11 12:30 UTC by lenaryan

Просьба посмотреть тот огромный список параметров, там есть вопросики по формулировке. Перевести я перевела, а нормально сформулировать оказалось сложновато.

Close https://github.com/Y-Doka/y-doka.site/issues/88

2021-05-12 08:37 UTC, solarrust reviewed
Обрати, пожалуйста, внимание, что код и абзацы мы всегда отбиваем пустыми строками. 

Все «media-запросы» нужно заменить на «медиавыражение» [ибо так правильно](https://github.com/web-standards-ru/dictionary/blob/main/dictionary.md#media-query)

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +name: media
```suggestion

```

В этом репо параметр `name` нам не нужен. Ссылочки создаются на основании папки

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +@-правило, которое помогает применять разные стили для разных параметров экрана — ширины, высоты, ориентации и даже типа устройства.
```suggestion
Директива, которая помогает применять разные стили для разных параметров экрана — ширины, высоты, ориентации и даже типа устройства.
```

[Словарь веб-стандартов](https://github.com/web-standards-ru/dictionary/blob/main/dictionary.md#at-rule) говорит, что такие at-rule переводятся как **директивы**.

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +Сделаем блок флекс-контейнером для ширины экрана от 900 пикселей включительно:
```suggestion
Сделаем элемент с классом `block` флекс-контейнером на экранах, чья ширина равна или больше 900 пикселей:
```

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +Иногда нам нужно, чтобы какой-то набор стилей применился только в определённый момент — например, чтобы текст стал зелёным только при горизонтальной ориентации смартфона. Или блок стал занимать всю ш
```suggestion
При вёрстке адаптивных сайтов часто нужно чтобы какой-то набор стилей применился только при соблюдении определённых параметров. Например, должен стать зелёным только при горизонтальной ориентации смартфона. Или блок занял всю ширину родителя, если ширина экрана больше или равна 1500 пикселям. Для подобных действий и существуют медиавыражения. Они помогают адаптировать вёрстку под разные экраны и устройства и при этом не писать лишний код.
```

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +@media [тип устройства] [параметры запроса] {
Давай постараемся не использовать псевдокод, а разберём синтаксис на реальном примере

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +Есть четыре типа, которые мы можем указать:
```suggestion
Есть четыре типа устройств, которые мы можем указать:
```

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +- all — media-запрос применится ко всем устройствам. Если не прописать никакой тип, то по умолчанию применится этот;
```suggestion
- `all` — медиавыражение применится ко всем устройствам. Если не прописать никакой тип, то по умолчанию применится этот;
```

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +- print — применится на устройствах, делающих разбивку контента на страницы — например, в режиме предпросмотра страницы для печати;
```suggestion
- `print` — стили внутри такого медиавыражения применятся при печати на принтерах, в том числе в режиме предпросмотра документа перед печатью;
```

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +- screen — для компьютерных экранов;
```suggestion
- `screen` — для компьютерных экранов;
```

Не только компьютерных, но любых девайсов с экранами. Телефоны и планшеты сюда же

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +- speech — для синтезаторов речи.
```suggestion
- `speech` — для синтезаторов речи.
```

Кажется, что термин скринридеры будет более понятен чем синтезаторы речи. Как считаешь?

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +```css
Получился нерабочий код. Стоит избегать такого. Лучше словами объяснить порядок чтения браузером

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +Возможные параметры запроса:
Ниже все ключевые слова нужно завернуть в бэктики

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +Возможные параметры запроса:
Лучше не писать, в какой редакции спецификации ключевое слово было добавлено. Это не особо нужная информация. Гораздо важнее написать если не поддерживается в каком-то браузере.

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +Возможные параметры запроса:
На CSS-tricks классно разбиты доступные ключевые слова на блоки по темам: интерактив, цвет, вьюпорт. 
Кажется, что в таком виде получатся более читабельные небольшие списки

https://css-tricks.com/a-complete-guide-to-css-media-queries/

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +Если мы пишем и тип устройства, и указываем параметры, то после типа обязательно пишется `and`.
Может быть вынесем ключевые слова `only`, `not` и `and` в отдельный блок?

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +💡 для `mobile-first` вёрстки лучше использовать media-запросы с `min-width`, и располагать их в порядке увеличения ширины экрана; для `desktop-first` - `max-width`, и располагать запросы в обратном п
mobile-first — это не кусочек кода, а парадигма вёрстки =) Лучше Mobile first

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +💡 для `mobile-first` вёрстки лучше использовать media-запросы с `min-width`, и располагать их в порядке увеличения ширины экрана; для `desktop-first` - `max-width`, и располагать запросы в обратном п
Аналогично с desktop-first

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +## В работе
Блок «В работе» мы теперь выносим в отдельную папку practice. Внутри папки создаём MD-файлик со своим логином. Подгляди, пожалуйста, в соседних статьях структуру =)

2021-05-12 08:37 UTC, solarrust commented on css/doka/media/index.md
> +🛠 можно вкладывать в другие at-правила:
```suggestion
🛠 можно вкладывать в другие директивы:
```

2021-05-26 14:04 UTC, pepelsbey requested changes
Если говорить высокоуровнево, то я бы заменил все «запросы» на «выражения». Плюс нужно избавиться от всех `screen and` и `all and` там, где они не нужны.

2021-05-26 14:06 UTC, pepelsbey commented
Предлагаю здесь продолжить использовать перевод «Mobile First» и «Desktop First» как «от мобильных» и «от десктопа», соответственно. И уже в скобках пояснять, при первом употреблении.

2021-06-15 07:34 UTC, solarrust commented
@lenaryan пинг. Когда сможешь закончить?

2021-06-16 15:37 UTC, lenaryan commented
Вот и что мне делать с этим спеллером?((((

2021-06-16 15:40 UTC, solarrust commented
> Вот и что мне делать с этим спеллером?((((

1. Прогнать тест локально или нажать Details напротив упавшего теста. 
2. Найти на какие слова ругается. 
3. Поправить ошибки, если это ошибки
4. Внести исключения в файл .yaspeller если это правильно слово и спеллеру на него не следует ругаться

2021-06-16 16:58 UTC, pepelsbey commented
<img width="960" alt="image" src="https://user-images.githubusercontent.com/105274/122261571-378cca00-cedd-11eb-8a9e-1f44d0d9753b.png">

2021-06-16 17:02 UTC, lenaryan commented
Я это видела. Исправлять-то это как? У меня же всё правильно и по фэншую 😐

2021-06-16 17:51 UTC, tachisis reviewed
Я внесла исключения, на которых ломается спеллер, в словарь. Потом это можно делать самостоятельно по аналогии) @lenaryan

2021-06-16 17:51 UTC, tachisis commented on css/doka/media/index.md
> +tag:
```suggestion
tags:
```

2021-06-16 17:51 UTC, tachisis commented on css/doka/media/index.md
> +💡 для вёрстки от мобильных лучше использовать медиавыражения с `min-width`, и располагать их в порядке увеличения ширины экрана; для вёрстки от десктопа — `max-width`, и располагать выражения в обрат
```suggestion
💡 Для вёрстки от мобильных (mobile first) лучше использовать медиавыражения с `min-width` и располагать их в порядке увеличения ширины экрана; для вёрстки от десктопа (desktop first) — `max-width`, и располагать выражения в обратном порядке.
```

2021-06-16 17:52 UTC, lenaryan commented
@tachisis спасибо 💜

2021-06-16 18:13 UTC, pepelsbey commented on css/doka/media/practice/lenaryan.md
> +🛠 медиавыражения можно располагать как внутри селекторов, так и снаружи. Например, код:
Нельзя, это сработает только в Sass 🤔

```scss
.block {
  font-size: 20px;
  @media (max-width: 480px) {
    font-size: 15px;
  }
}
```

К сожалению, весь совет мимо.

2021-06-16 18:15 UTC, pepelsbey commented
[Отформатировал списки](https://github.com/doka-guide/content/pull/508/commits/a24f4f5baa23c8246b78d084c5574e3a264bbd08), чтобы было компактнее, без отступов — в общем, как везде.

2021-06-16 21:59 UTC, lenaryan commented on css/doka/media/practice/lenaryan.md
> +🛠 медиавыражения можно располагать как внутри селекторов, так и снаружи. Например, код:
Но я же это где-то видела... Перепроверю... А про другие директивы у меня, кажется, было написано.

2021-06-16 22:16 UTC, pepelsbey commented on css/doka/media/practice/lenaryan.md
> +🛠 медиавыражения можно располагать как внутри селекторов, так и снаружи. Например, код:
`@media` на уровне свойств точно-преточно не работает в браузере. Только в препроцессорах, до компиляции.

Будет полезно именно что показать вложенные `@media`. Это значительно проще, чем комбинировать сложные условия в одной директиве — то есть очень полезная техника.

2021-06-17 16:36 UTC, lenaryan commented on css/doka/media/practice/lenaryan.md
> +🛠 медиавыражения можно располагать как внутри селекторов, так и снаружи. Например, код:
Всё, я убрала это позорище...))

2021-06-17 21:48 UTC, pepelsbey requested changes
~Предлагаю склеить предложения, которые разрываются одним-двумя блоками кода и их потом сложно склеить в единое высказывание.~ Готово.

Плюс я заметил, что мы перешли на «медиавыражения», но в остальных местах всё ещё «запросы», когда речь заходит про параметры.

Я бы посмотрел [на группу терминов media в словаре](https://github.com/web-standards-ru/dictionary/blob/main/dictionary.md#media-query) и нашёл бы подходящие.

2021-06-17 21:48 UTC, pepelsbey commented on css/doka/media/index.md
> +тип устройства — `screen`, а параметр запроса — `min-width: 900px`.
```suggestion
Например:

```css
@media screen and (min-width: 900px) {
  .block {
    display: flex;
  }
}
```

Здесь тип устройства — `screen`, а параметр запроса — `min-width: 900px`.
```

Лучше не разбивать предложение примером, а показать его и потом описать. Иначе очень странно выглядит предложение со строчной и легко теряется начало.

2021-06-17 21:48 UTC, pepelsbey commented on css/doka/media/index.md
> +то запрос сработает на всех устройствах с альбомной ориентацией экрана или на всех устройствах с шириной экрана менее 960 пикселей.
```suggestion
В медиавыражении может быть перечислено несколько условий через запятую. В таком случае стили применятся для любого из указанных условий. Например:

```css
@media (orientation: landscape), (max-width: 960px) {
  .text {
    color: tomato;
  }
}
```

Такой код применится на всех устройствах с альбомной ориентацией экрана или на всех устройствах с шириной экрана менее 960 пикселей.
```

Склеивает предложение обратно.

2021-06-17 21:48 UTC, pepelsbey commented on css/doka/media/index.md
> +```
````suggestion
Ключевое слово `not` используется для отрицания выражения. Оно имеет низкий приоритет и применяется в последнюю очередь. Например:

```css
@media not screen and (min-width: 380px) {
  .block {
    display: flex;
  }
}
```

Здесь сначала вычислится выражение «для всех экранов с минимальной шириной 380 пикселей», а потом оно инвертируется — «для всех устройств, кроме устройств с экранами с минимальной шириной 380 пикселей». То есть будет читаться браузером как:

```css
@media not (screen and (min-width: 380px)) {
  .block {
    display: flex;
  }
}
```
````

Склеивает предложения обратно.

2021-06-17 21:48 UTC, pepelsbey commented on css/doka/media/index.md
> +```
````suggestion
При использовании `not` в медиавыражениях с запятой инвертируется только та часть выражения, где указан `not`. Например:

```css
@media not screen and (height: 500px), print and (height: 700px) {
  .text {
    color: tomato;
  }
}
```

Чтобы лучше понять, как выполнится этот пример, можно добавить дополнительные группирующие скобки:

```css
@media (not (screen and (height: 500px))), print and (height: 700px) {
  .text {
    color: tomato;
  }
}
```
````

Склеивает предложение и объясняет, что изменилось во втором примере.

2021-06-18 09:45 UTC, tachisis approved these changes

2021-06-22 20:59 UTC, lenaryan commented
> Плюс я заметил, что мы перешли на «медиавыражения», но в остальных местах всё ещё «запросы», когда речь заходит про параметры.
> 
> Я бы посмотрел [на группу терминов media в словаре](https://github.com/web-standards-ru/dictionary/blob/main/dictionary.md#media-query) и нашёл бы подходящие.

@pepelsbey там подходит слово "медиафича" вместо "параметров запроса"... Пока меняю на "характеристики устройства", это как-то посерьёзнее смотрится.

2021-06-22 22:42 UTC, pepelsbey requested changes
Предложил обезопасить читателей от использования типа устройства и уточнил значения некоторых медиафич.

2021-06-22 22:42 UTC, pepelsbey commented on css/media/index.md
> +```
````suggestion
Сделаем элемент с классом `.block` флекс-контейнером на экране шириной 900 пикселей или больше:

```css
@media (min-width: 900px) {
  .block {
    display: flex;
  }
}
```
````

Предлагаю упростить базовый пример, чтобы там был ровно тот код, который используется в 99% случаев и ничего больше. Чтобы новички привыкали, что медиавыражения нужно писать без указания типа устройства. Дальше уже можно рассказывать про полный синтаксис.

2021-06-22 22:42 UTC, pepelsbey commented on css/media/index.md
> +Здесь тип устройства — `screen`, а характеристика устройства — `min-width: 900px`.
````suggestion
Например:

```css
@media print and (orientation: landscape) {
  .block {
    font-size: 25pt;
  }
}
```

Здесь тип устройства — `print` (принтер), а характеристика устройства — `orientation: landscape` (альбомная ориентация). То есть при альбомной ориентации устройства (листа) размер шрифта у блока будет 25 пунктов.
````

Заменяет пример на тот, где полезно будет указывать тип устройства.

2021-06-22 22:42 UTC, pepelsbey commented on css/media/index.md
> +- `speech` — для скринридеров.
```suggestion
Есть четыре типа устройств, которые мы можем указать:

- `all` — медиавыражение применится ко всем устройствам. Если не прописать никакой тип, то по умолчанию применится этот;
- `print` — стили внутри такого медиавыражения применятся при печати на принтерах или экспорте в PDF, в том числе в режиме предпросмотра документа;
- `screen` — для устройств с экранами;
- `speech` — для синтезаторов речи (пока не поддерживается ни одним браузером).

В большинстве случаев, когда вы пишете стили только для экрана, указывать `screen` или `all` смысла нет. Реальное практическое использование есть только у медиатипа `print`.
```

Уточнил про `print` и `speech`, добавил про ненужность медиатипов.

2021-06-22 22:42 UTC, pepelsbey commented on css/media/index.md
> +- `orientation` — ориентация устройства (альбомная или портретная);
```suggestion
- `orientation` — ориентация устройства: `landscape` (альбомная, горизонтальная) или `portrait` (портретная, вертикальная);
```

Значения лучше не переводить, их захочется использовать.

2021-06-22 22:42 UTC, pepelsbey commented on css/media/index.md
> +- `display-mode` — проверка режима отображения; включает в себя полноэкранный режим (не браузерный), автономность (автономное приложение), минимальный пользовательский интерфейс (автономное приложени
```suggestion
- `display-mode` — проверка режима браузера, используется в PWA: `fullscreen` (полноэкранный режим без интерфейса браузера), standalone (как нативное приложение), `minimal-ui` (минимальный интерфейс браузера) и `browser` (обычное окно браузера);
```

Возвращает ключевые слова и объясняет их.

2021-06-22 22:42 UTC, pepelsbey commented on css/media/index.md
> +- `grid` — проверка, является ли устройство сеткой или растровым изображением;
```suggestion
- `grid` — проверка, является ли экран растровым (все современные экраны) или сеточным (как старые телефоны или текстовые терминалы);
```

2021-06-22 22:42 UTC, pepelsbey commented on css/media/index.md
> +- `update` — проверка, как быстро устройство вывода может изменить внешний вид контента.
```suggestion
- `update` — скорость обновления экрана: `none` (не обновляется), `slow` (медленно), `fast` (быстро).
```

2021-06-25 12:52 UTC, pepelsbey approved these changes

2021-06-25 13:36 UTC, solarrust approved these changes

2021-06-25 13:37 UTC, merged