Упрощает диалог  в new.sh
doka-guide/content pull request #5130
Opened 2024-01-18 20:23 UTC by vitya-ne

## Описание

В текущей версии `new.sh` используется логика получения github-логина с использованием запроса:

```bash
LOGIN=$(echo $(curl -s https://api.github.com/search/users\?q\=$(echo $(git config --get user.email)) | jsonValue login))
```
Этот код имеет недостатки по двум причинам:
1. Запрос ничего не даст, в случае если в настройках github установлена опция `Keep my email addresses private` и в репозитории используется email вида `USER@users.noreply.github.com`. (Мне кажется, это довольно распространённая практика).
Вот что происходит в моём случае:
```bash
$ curl -s https://api.github.com/search/users\?q\=9317613+vitya-ne@users.noreply.github.com
{
  "total_count": 0,
  "incomplete_results": false,
  "items": [

  ]
}
```
2. Зачем вообще делать какой-то запрос на github, когда мы можем использовать `.env` файл для хранения переменных `LOGIN` или сразу `AUTHOR`.

### Предлогаю
Моё исправление даёт возможность:

1. Использовать опциональный файл `.env` для хранения переменных `LOGIN` или `AUTHOR`.
2. Если в файле установть переменную LOGIN:
```bash
LOGIN="имя автора в Доке"
```
Скрипт попросит подтвердить это значение или ввести другое.
3. Если в файле установть переменную AUTHOR:
```bash
AUTHOR="имя автора в Доке"
```
Скрипт считывает это имя и переходит к следующему вопросу.

### Приемущеста

1. Не делаем ненужный запрос.
2. Задаём меньше вопросов.

## Чек-лист

- [x] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [x] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [x] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2024-01-23 16:55 UTC, igsekor requested changes
Спасибо! Предложение дельное!

Однако, данное поле в `.env`, если мы его используем, необходимо описать и в документации, и в этом скрипте. Предлагаю сделать это уже в рамках этого PR. В документации — в пункте 2 основной документации кратко и [тут](https://github.com/doka-guide/platform/blob/main/docs/how-to-run.md) в полном объёме, а в скрипте его нужно добавлять с разрешения пользователя.

2024-01-23 17:56 UTC, vitya-ne commented
> Спасибо! Предложение дельное!
> 
> ..., а в скрипте поле нужно добавлять с разрешения пользователя.

Привет, я не понял последнюю фразу. Добавлять скриптом ?
Я думал описать что `.env`-файл можно использовать и как использовать. А использовать его или нет решает сам пользователь и вручную его добавляет.

2024-01-23 19:22 UTC, igsekor commented
> Привет, я не понял последнюю фразу. Добавлять скриптом ? Я думал описать что `.env`-файл можно использовать и как использовать. А использовать его или нет решает сам пользователь и вручную его добавляет.

Фраза означала следующее: если пользователь не имеет подобной настройки, было бы хорошо пользователю об этом сообщить, ну и предложить добавить сразу на этапе первичной настройки. Можно и просто сообщить, но автоматизировать хочется ещё, раз уж мы взялись за это нелёгкое дело ☺️

2024-01-25 17:58 UTC, vitya-ne commented
> Фраза означала следующее: если пользователь не имеет подобной настройки, было бы хорошо пользователю об этом сообщить, ну и предложить добавить сразу на этапе первичной настройки. Можно и просто сообщить, но автоматизировать хочется ещё, раз уж мы взялись за это нелёгкое дело ☺️

@igsekor, привет!
Скрипт я доработал: после получения или ввода ника будет предложено его сохранить.
Я посмотрел пункт 2 [основной документации](https://github.com/doka-guide/content/blob/main/README.md) и не уверен что его нужно дополнять и перегружать дополнительной информацией. Скрипт работает как и описано: задаёт несколько вопросов. После первого запуска файл `.env` будет создан автоматически (если пользователь дал согласие), так что вручную ничего делать не нужно.
Как думаешь ?

[Подробную инструкцию](https://github.com/doka-guide/platform/blob/main/docs/how-to-run.md) дополню отдельным мержем в платформу.

2024-01-31 06:41 UTC, vitya-ne commented
@igsekor ping

2024-02-07 10:51 UTC, igsekor approved these changes

2024-02-07 10:55 UTC, igsekor commented
> @igsekor, привет! Скрипт я доработал: после получения или ввода ника будет предложено его сохранить. Я посмотрел пункт 2 [основной документации](https://github.com/doka-guide/content/blob/main/README.md) и не уверен что его нужно дополнять и перегружать дополнительной информацией. Скрипт работает как и описано: задаёт несколько вопросов. После первого запуска файл `.env` будет создан автоматически (если пользователь дал согласие), так что вручную ничего делать не нужно. Как думаешь ?

Нормальный вариант!

> В [подробной инструкции](https://github.com/doka-guide/platform/blob/main/docs/how-to-run.md) описано как запускать саму платформу. Там нет описания порядка создания статей с помощью `new.sh`

Подумал-подумал, наверное, и не надо нам дополнять эту доку....

2024-02-07 10:56 UTC, igsekor commented
> @igsekor ping

Забегался.... Пламенный привет!

2024-02-07 11:50 UTC, TatianaFokina commented
Мне всё нравится. И правда, стало лучше и менее напряжно.

2024-02-07 11:50 UTC, TatianaFokina approved these changes

2024-02-07 12:10 UTC, furtivite approved these changes

2024-02-07 12:55 UTC, merged