Content slider
doka-guide/content pull request #5351
Opened 2024-05-27 08:11 UTC by AnnaBaraulina

## Описание

Рецепт доступного слайдера

Closes #2730 

## Чек-лист
не срабатывает скрипт npx yaspeller --only-errors --file-extensions ".md,.html" *

2024-05-28 09:56 UTC, solarrust commented
Привет! Кажется, в этот пулреквест попали лишние коммиты. 

![CleanShot 2024-05-28 at 10 55 34@2x](https://github.com/doka-guide/content/assets/13676514/3ebebd66-a4a9-4051-bb6d-ae5c96b643f6)

Давай попробуем оставить тут только те коммиты, которые относятся к текущему материалу?

2024-05-29 11:07 UTC, skorobaeus requested changes
Привет! Я почистила историю коммитов 💪 Проверь, пожалуйста, чтобы ничего не пропало.

А теперь можно спокойно переходить к дизайн-ревью :) Сориентироваться по стилю демок можно здесь, в [стайлгайде](https://github.com/doka-guide/content/blob/main/docs/demos/style.md), но для простоты я просто напишу, что поменять:

- применить "тёмную тему", задав фоновый цвет `#18191C` и белый цвет текста;
- подключить шрифт Roboto;
- убрать скругление краёв у картинки.

Ещё было бы здорово придумать осмысленные подписи вместо "Первый слайд", "Второй слайд" и т.д., а сами эти подписи можно даже разместить поверх изображений. Демки это место, где можно шутить, если есть настроение :)

2024-05-29 11:29 UTC, AnnaBaraulina commented on recipes/slider/demos/slider-demo/images/left-arrow-svgrepo-com.svg
Хорошо!

2024-05-29 11:29 UTC, AnnaBaraulina commented on recipes/slider/demos/slider-demo/images/IMG_1945.JPG
Сделаю!

2024-05-29 11:30 UTC, AnnaBaraulina commented
> Привет! Я почистила историю коммитов 💪 Проверь, пожалуйста, чтобы в файлах ничего не пропало.
> 
> А теперь можно спокойно переходить к дизайн-ревью :) Сориентироваться по стилю демок можно здесь, в [стайлгайде](https://github.com/doka-guide/content/blob/main/docs/demos/style.md), но для простоты я просто напишу, что поменять:
> 
> * применить "тёмную тему", задав фоновый цвет `#18191C` и белый цвет текста;
> * подключить шрифт Roboto;
> * убрать скругление краёв у картинок.
> 
> Ещё было бы здорово придумать осмысленные подписи вместо "Первый слайд", "Второй слайд" и т.д., а сами эти подписи можно даже разместить поверх изображений. Демки это место, где можно шутить, если есть настроение :)

Спасибо! Я вчера не успела! Я все поправлю на неделе!

2024-06-03 11:40 UTC, AnnaBaraulina commented
Не понимаю, что с этим реквестом. И код залила новый, но в опубликованном ревью демо выглядит по-старому

2024-06-03 14:38 UTC, skorobaeus commented
> Не понимаю, что с этим реквестом

Если я правильно понимаю происходящее, твоя ветка либо ветвится от старой ветки восьмимесячной давности с попапом, либо это и есть та ветка, но переименованная. 

Для того, чтобы очистить этот пулл-реквест от старых коммитов, я использовала [интерактивный rebase](https://ru.stackoverflow.com/questions/740179/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D0%BD%D0%B5%D0%BD%D1%83%D0%B6%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D1%8B). Можешь попробовать сделать это ещё раз, и потом можно будет продолжить работать в этом ПРе.

Альтернативно, можно закрыть этот ПР и создать новый, чистый. Схема будет такая: скачать актуальную версию репо [content](https://github.com/doka-guide/content), ветку main, сделать новую твою ветку под работу над слайдером, и черри-пикнуть в неё нужные коммиты из этой ветки.

2024-06-04 08:08 UTC, closed without merging