Text wrap
doka-guide/content pull request #5445
Opened 2024-07-17 08:55 UTC by nasty23-star

## Описание

Добавила статью о свойстве text-wrap и набросок демки

Closes #5170 

## Чек-лист

- [ ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2024-07-17 11:23 UTC, skorobaeus requested changes
Привет! Спасибо за новый материал :)

Для подобных CSS-свойств нагляднее всего работают демки, которые показывают все значения свойства на примере одного и того же текста. Например, `balance` балансирует количество символов в строке, будет о-о-очень круто дать возможность это увидеть.

В качестве шаблона для демки используй, пожалуйста, [аналогичную демку](https://doka.guide/css/white-space/demos/every/) из статьи [white-space](https://doka.guide/css/white-space/). Там даже есть решение для вёрстки непоместившегося в контейнер текста :)

2024-07-22 11:00 UTC, skorobaeus approved these changes
Решила показать, что такое "сбалансированный вид заголовков", при помощи иллюстрации, надеюсь, ты не против :) 

По визуалу от меня аппрув 👍

2024-07-24 17:21 UTC, solarrust reviewed
Привет!
Предложила несколько небольших уточнений по тексту. Посмотри, пожалуйста, со всем ли ты согласна. Давай обсуждать =)

Дока получается супер, спасибо. Её не хватало!

2024-07-24 17:21 UTC, solarrust commented on css/text-wrap/demos/basic/index.html
> +
```suggestion
```

2024-07-24 17:21 UTC, solarrust commented on css/text-wrap/index.md
> +- `nowrap` — текст не переносится по строкам. Он переполнит содержащий его элемент и выйдет за его пределы, а не перейдёт на новую строку;
```suggestion
- `nowrap` — текст не переносится по строкам. Он переполнит родительский элемент и выйдет за его пределы, а не перейдёт на новую строку;
```

2024-08-08 08:22 UTC, nasty23-star commented on css/text-wrap/index.md
> +- `balance` — текст переносится таким образом, чтобы наилучшим образом сбалансировать количество символов в каждой строке, улучшая качество и разборчивость. Поскольку подсчёт символов и их балансиров
чуть переформулировала

2024-08-14 10:48 UTC, solarrust reviewed
Дока почти готова =) Предложила ещё несколько небольших правок по тексту.

2024-08-14 10:48 UTC, solarrust commented on css/text-wrap/index.md
> +Значения `wrap`, `nowrap` и `balance` поддерживаются основными браузерами, `pretty` и `stable` не поддерживаются Safari и Firefox. Проверяйте поддержку на [Can I use](https://caniuse.com/text-size-ad
`stable` наоборот, поддерживается только в Safari и FF https://share.cleanshot.com/PZtkyrhq

Может быть мы можем написать про поддержку в разделе со значениями?

2024-08-14 10:48 UTC, solarrust commented on css/text-wrap/index.md
> +- `wrap` — значение по умолчанию. Текст переносится по строкам через соответствующие символы (например пробелы или символы Unicode: `U+2010 (HYPHEN)` ("жёсткий дефис") и `U+00AD (SHY)` (невидимый "мя
```suggestion
- `wrap` — значение по умолчанию. Текст переносится по строкам через соответствующие символы (например, пробелы или символы Unicode: `U+2010 (HYPHEN)` («жёсткий дефис») и `U+00AD (SHY)` (невидимый «мягкий» перенос)), чтобы минимизировать переполнение элемента.
```

2024-08-14 10:48 UTC, solarrust commented on css/text-wrap/index.md
> +- `stable` — результат аналогичен `wrap`, но при редактировании текста, строки, идущие выше, остаются неподвижными, в то время как при значении по умолчанию будет перерисовываться всё содержимое.
```suggestion
- `nowrap` — текст не переносится по строкам. Он переполнит родительский элемент и выйдет за его пределы, а не перейдёт на новую строку.
- `balance` — текст переносится так, чтобы наилучшим образом сбалансировать количество символов в каждой строке, улучшая разборчивость и читаемость.
- `pretty` — результат будет таким же, как и при использовании `wrap`, за исключением того, что браузер будет использовать более медленный алгоритм, который отдает предпочтение лучшему виду, а не скорости. Предназначается для текста, где хорошая типографика предпочтительнее производительности.

Про этот алгоритм можно почитать у разработавшего его инженера [по ссылке](https://docs.google.com/document/d/1jJFD8nAUuiUX6ArFZQqQo8yTsvg8IuAq7oFrNQxPeqI/edit#heading=h.cqq9czoal00g).
Пожалуй, самое популярное преимущество этого свойства — предотвращение «сирот» («сирота» в типографике — это слово, которое переносится на новую строку, чем делает текст менее гармоничным внешне).
- `stable` — результат аналогичен `wrap`, но при редактировании текста, строки, идущие выше, остаются неподвижными, в то время как при значении по умолчанию будет перерисовываться всё содержимое.
```

2024-08-14 10:48 UTC, solarrust commented on css/text-wrap/index.md
> +Про этот алгоритм можно почитать у разработавшего его инженера [по ссылке](https://docs.google.com/document/d/1jJFD8nAUuiUX6ArFZQqQo8yTsvg8IuAq7oFrNQxPeqI/edit#heading=h.cqq9czoal00g).
Блок про алгоритм я бы перенесла под список, чтобы не прерывать его.

2024-08-14 10:48 UTC, solarrust commented on css/text-wrap/index.md
> +Поскольку подсчёт символов и их балансировка по нескольким строкам требует больших вычислительных затрат, это значение поддерживается только для блоков текста с ограниченным количеством строк (шесть
```suggestion
Поскольку подсчёт символов и их балансировка по нескольким строкам требует больших вычислительных затрат, это значение поддерживается только для блоков текста с ограниченным количеством строк (шесть или меньше для Chromium и десять или меньше для Firefox).
```

2024-08-14 10:48 UTC, solarrust commented on css/text-wrap/index.md
> +## `balance` и `pretty`: производительность
```suggestion
## Производительность
```

2024-08-14 10:48 UTC, solarrust commented on css/text-wrap/index.md
> +Не рекомендуется применять значение `balance` для больших блоков текста. Несмотря на то, что это значение оказывает видимый эффект только на ограниченное число строк, браузер всё равно будет пытаться
```suggestion
Не рекомендуется применять значение `balance` для больших блоков текста. Несмотря на то, что это значение оказывает видимый эффект только на ограниченное число строк, браузер всё равно будет пытаться рассчитать баланс для всех остальных, и это скажется на скорости рендеринга страницы. Лучше применять его для заголовков, цитат и других визуально значимых блоков текста.
```

2024-08-27 11:59 UTC, solarrust commented
Пинг в этом пиаре ✨

2024-09-20 09:42 UTC, solarrust approved these changes

2024-09-20 09:43 UTC, solarrust commented
Спасибо тебе большое за ещё одну замечательную Доку 💫

2024-09-20 09:43 UTC, merged