feat: Create article about virtual variables
doka-guide/content pull request #5577
Opened 2024-12-06 06:14 UTC by Alex-Andr-19

## Описание

Создание статьи в раздел Рецепты про перенос миксинов SASS'а на переменные CSS в атомарных классах

## Чек-лист

- [ x ] Текст оформлен [согласно руководству по стилю](https://github.com/doka-guide/content/blob/main/docs/styleguide.md)
- [ ] Ссылки на внутренние материалы начинаются со слеша и заканчиваются слэшем либо якорем на заголовок (`/css/color/`, `/tools/json/`, `/tools/gulp/#kak-ponyat`)
- [ ] Ссылки на картинки, видео и демки относительные (`images/example.png`, `demos/example/`, `../demos/example/`)

2024-12-06 08:19 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +  --_text-color: var(--text-color, #ddd);
Это так называемые sudo кастомные свойства  / псевдо приватные кастомные свйоства

[Видео Кевина Повелла](https://youtu.be/_2LwjfYc1x8?si=BvJFLYqov2LHI01X)
[Оригинальный рецепт](https://lea.verou.me/blog/2021/10/custom-properties-with-defaults/#:~:text=pseudo%2Dprivate%20custom%20properties)

2024-12-06 08:22 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +Но этот пункт относительно давно перестал быть уникальной частью этих библиотек – были созданы `custom variables` в CSS'е:
Душнота:
Всё таки называть кастомные свойства кастомными переменными не совесм  корректно. Посколько это именно свойства. Они наследуются и позволяют делать вещи, которые не мсогут сделать препроцессоры так же изящн. [Старое видео ](https://youtu.be/nbN22yqEgM0?si=qC7nyJhBUykY4fH4) Макеева по теме

2024-12-06 08:30 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +    @media (max-width: 509px) {
статья всё-таки про развитие css
```suggestion
    @media (width <= 1024px) and (width >= 510px) {
        --font-size: 18px;
        --line-height: 22px;
    }

    @media (width < 510px) {
```

2024-12-06 08:43 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +    --line-height: 26px;
Вне контекста этот код выглядит перегруженным и нарушением принципа KISS.

Не понятно что мешает сделать так
```html
<span class="static-font another-class">Lorem ipsum</span>
```

```css
.static-font {
    font-size: 1em;
    line-height: calc(1em + 4px);
}

.another-class {
    font-size: 20px;
    line-height: 26px;
}
``` 
То есть старый добрый каскад даёт тот же эффект при меньшем коде. 

Обычно приватные кастомные свойства нужны для компонентных фреймворков, где ты не можешь быть на 100% уверен в каком порядке сборщик соберёт стили. И в итоге тебе, чтобы гарантировано перебить внутренние стили компонента нужно либо перебивать вес селектора, либо делать кастомные свойства с дефолтом (в том числе и псевдо приватные), либо разбить по css слоям, если браузерная поддержка позволяет.

2024-12-06 09:09 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +Но этот пункт относительно давно перестал быть уникальной частью этих библиотек – были созданы `custom variables` в CSS'е:
Душнота:
Всё таки называть кастомные свойства кастомными переменными не совсем  корректно. Посколько это именно свойства. Они наследуются и позволяют делать вещи, которые не мсогут сделать препроцессоры так же изящно. [Старое видео ](https://youtu.be/nbN22yqEgM0?si=qC7nyJhBUykY4fH4) Макеева по теме

2024-12-06 09:09 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +  --_text-color: var(--text-color, #ddd);
Это так называемые sudo кастомные свойства  / псевдо приватные кастомные свойства

[Видео Кевина Повелла](https://youtu.be/_2LwjfYc1x8?si=BvJFLYqov2LHI01X)
[Оригинальный рецепт](https://lea.verou.me/blog/2021/10/custom-properties-with-defaults/#:~:text=pseudo%2Dprivate%20custom%20properties)

2024-12-06 09:09 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +.static-font__M {
Вне контекста этот код выглядит перегруженным и нарушением принципа KISS.

Не понятно, что мешает сделать так
```html
<span class="static-font another-class">Lorem ipsum</span>
```

```css
.static-font {
    font-size: 1em;
    line-height: calc(1em + 4px);
}

.another-class {
    font-size: 20px;
    line-height: 26px;
}
``` 
То есть старый добрый каскад даёт тот же эффект при меньшем коде. 

Обычно приватные кастомные свойства нужны для компонентных фреймворков, где ты не можешь быть на 100% уверен в каком порядке сборщик соберёт стили. И в итоге тебе, чтобы гарантировано перебить внутренние стили компонента нужно либо перебивать вес селектора, либо делать кастомные свойства с дефолтом (в том числе и псевдо приватные), либо разбить по css слоям, если браузерная поддержка позволяет.

2024-12-06 09:09 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +    @media (max-width: 509px) {
nit: статья всё-таки про развитие css, можно использовать более понятный синтаксис 
```suggestion
    @media (width <= 1024px) and (width >= 510px) {
        --font-size: 18px;
        --line-height: 22px;
    }

    @media (width < 510px) {
```

2024-12-06 15:14 UTC, Alex-Andr-19 commented on recipes/virtual-variables/index.md
> +Но этот пункт относительно давно перестал быть уникальной частью этих библиотек – были созданы `custom variables` в CSS'е:
Спасибо, обязательно исправлю

2024-12-06 15:19 UTC, Alex-Andr-19 commented on recipes/virtual-variables/index.md
> +.static-font__M {
Таким образом, как описал я, в проект может зайти новый разработчик, увидеть все стандартные размеры текста, которые описаны в дизайн системе и легко их применить, воткнув всего один класс.
Так же, если понадобиться создать что-то отличающееся от стандартных шрифтов ему достаточно создать класс который будет иметь в своем названии `static-font`, реализовать два свойства и все будет работать

2024-12-06 15:20 UTC, Alex-Andr-19 commented on recipes/virtual-variables/index.md
> +    @media (max-width: 509px) {
Спасибо большое, сам не знал, теперь буду использовать

2024-12-06 18:00 UTC, ra1nbow1 commented on recipes/virtual-variables/index.md
> +Раньше такая технология была только в препроцессорах и позволяла весьма удобно работать с БЭМом:
```suggestion
Раньше такая технология была только в [препроцессорах](/tools/preprocessors/) и позволяла весьма удобно работать с БЭМом:
```

Привет! Предлагаю добавить ссылочку сюда

2024-12-06 18:06 UTC, ra1nbow1 commented
@solarrust @HellSquirrel @TatianaFokina девочки, привет! Может покажусь каким-то негативно настроенным, но вам не кажется, что повествование от первого лица выглядит не совсем уместно? 😁

2024-12-06 20:07 UTC, baileys-li commented on recipes/virtual-variables/index.md
> +    @media (max-width: 509px) {
да не за что

2024-12-09 06:00 UTC, Alex-Andr-19 commented
> @solarrust @HellSquirrel @TatianaFokina девочки, привет! Может покажусь каким-то негативно настроенным, но вам не кажется, что повествование от первого лица выглядит не совсем уместно? 😁

Жду обратной связи. Если надо – поправлю. Сам думаю, что не уместно было делать акцент на первом лице.

2024-12-10 14:15 UTC, Inventoris requested changes
@Alex-Andr-19 Привет! 

Во-первых, большое спасибо тебе за статью 🌟

Во-вторых, вот что думаю: я пробежался по изменениям, и там довооольно много чего стоит пересмотреть. Я предлагаю тебе для начала взглянуть на [документацию](https://github.com/doka-guide/content/blob/main/docs/contributing.md), особенно заострить внимание на структуре статьи и стайлгайде. Затем прочесть 5-10 любых статей на Доке, лучше из раздела [рецепты](https://doka.guide/recipes/) (ты ведь туда хочешь сделать вклад?), и обратить внимание на общий вайб, на подход к изложению итд. А потом оценить материал самостоятельно ещё раз, хорошо?

2024-12-24 06:07 UTC, Alex-Andr-19 commented
Всем привет, сейчас решил изменить подход к объяснению технологии ( как и говорил @Inventoris ), но долго не мог найти достойный пример. Понимаю, что статья далеко не в финальной версии, но хочу получить обратную связь по примеру и, возможно, советы по улучшению демонстрационного показателя примера, чтобы читателю было понятно в каких случаях она пригодится.

2024-12-25 19:10 UTC, TatianaFokina commented
> Всем привет, сейчас решил изменить подход к объяснению технологии, но долго не мог найти достойный пример.

Кажется, это этакий синтаксический сахар, который не добавляет новой функциональности, а улучшает старую. Так что можно показать, как псевдоприватные свойства работают в каком-нибудь популярном кастомном компонентике, о котором ещё нет рецепта. @solarrust, @skorobaeus, есть какие-то идеи, что за копонент можно сделать для рецепта?

Другой вариант — перенести материал в раздел CSS, тут @solarrust лучше подскажет, как его лучше обозвать там и в какой подразделе лучше хранить.

2024-12-26 08:02 UTC, Alex-Andr-19 commented
@TatianaFokina Согласен на счёт возможности переноса в тему CSS. Думаю в том виде, к которому пришла статья, она действительно будет более уместна.

2025-01-02 10:48 UTC, solarrust reviewed
Как круто! Я не знала про такой подход, спасибо =)

Оставила пару предложений по тексту.

Согласна полностью с тем, что статью можно перенести в раздел CSS. Она там хорошо впишется.

Надо будет только немного объяснить что такое псевдоприватность, показать такой же пример на миксинах в противовес нативным возможностям. И получится хорошо =)

2025-01-02 10:48 UTC, solarrust commented on recipes/pseudo-private-custom-property/index.md
> +В силу перехода CSS к нативному нестингу, а также из-за естественного развития CSS многие преимущества препроцессоров стали отходить на второй план. Сначала появились кастомные свойства, следом произ
```suggestion
В силу перехода CSS к нативному нестингу, а также из-за естественного развития CSS многие преимущества препроцессоров стали отходить на второй план. Появились [кастомные свойства](/css/custom-properties/), произошёл взрыв CSS-функций (`color-mix`, [`counter`](/css/css-counters/), тригонометрические функции и другие).
```

Тут меня слегка смущает фраза «нативный нестинг». У нас пока об этом нет статьи в Доке чтобы просто объяснить, что это такое. А начинающий разработчик может быть с этим незнаком. Давай поищем синонимы? Например, промежуточный вариант «нативная вложенность» или совсем просто «встроенная вложенность».

2025-01-02 10:48 UTC, solarrust commented on recipes/pseudo-private-custom-property/index.md
> +С появление таких возможностей некоторым разработчикам хочется отказаться и от других технологий из препроцессоров – миксины. Некоторые особенности миксинов всё ещё заменить невозможно, но есть решен
```suggestion
Миксины — последняя причина держаться за препроцессоры. Некоторые особенности миксинов всё ещё заменить не получится. Но есть решение, которое заменит собой большую часть миксинов – _псевдоприватные кастомные свойства_.
```

Немного перефразировала этот абзац.

2025-01-17 13:32 UTC, Alex-Andr-19 commented
@solarrust Переработал статью под формат CSS статей. За основу взял [кастомные свойства](https://doka.guide/css/custom-properties/). Надеюсь в этот раз получилось по лучше.

2025-01-31 00:32 UTC, solarrust approved these changes
Принесла небольшие правки по тексту. Ничего глобального, смысл не должен был нарушиться.

Получилось очень круто! Спасибо тебе =)

От меня аппрув.
Зову @skorobaeus помочь с демками 🧚‍♀️

2025-01-31 14:17 UTC, skorobaeus requested changes
Привет! С демками всё хорошо :) К ним только нужно прикрутить стили отсюда: https://github.com/doka-guide/content/blob/main/docs/demos/style.md

Нам потребуются цвета и шрифты. Если возникнут сложности, я сделаю всё сама, но, видимо, уже после того, как уйдёт рассылка :)

2025-02-10 12:10 UTC, skorobaeus requested changes
Привет ещё раз!

Я покрутила демки, прочитала текст, прочитала обсуждение выше и у меня возникло много вопросов. При этом цель любого материала в Доке обратная: отвечать на вопросы, а не порождать новые.

У [док](https://github.com/doka-guide/content/blob/main/docs/examples/doka.md) и [статей](https://github.com/doka-guide/content/blob/main/docs/examples/article.md) есть типовая структура, давай попробуем её соблюсти.

Эту статью очень украсит вводная часть, но не формальная, для галочки, а по существу. В такой вводной части первым делом стоит объяснить простыми словами что такое псевдоприватные кастомные свойства. Рассказать, зачем они нужны: чтобы изолировать стили, избегать конфликтов, давать пользователям рычаги для настройки компонентов, не трогая внутреннюю логику, и т.д. И наконец, отметить, что это синтаксический сахар и показать, как пишется. Чем чётче и яснее здесь пример кода, тем лучше; он не обязан быть связан с демкой.

После вводной части переходим к разбору практического примера: ставим задачу (вёрстка карточек), обозначаем проблему (код раздувается до нечитаемости, из-за взаимозависимостей стилей его становится очень легко сломать), опционально (!) нагнетаем ситуацию (если прикрутить миксины, то получится жесть ваще бррр), даём решение проблемы (показываем идентичный результат на чистом CSS).

Наконец, завершаем статью: договариваем всё, о чём не договорили, делаем выводы.

Прости, пожалуйста, за такую простыню фидбека 😅 Я очень обрадовалась возможности избавиться от миксинов и теперь очень хочу, чтобы из этой статьи получилась конфетка :)

2025-02-10 12:10 UTC, skorobaeus commented on css/pseudo-private-custom-property/index.md
> +1. Внутренняя переменная — псевдоприватное кастомное свойство.
Это завершающая часть статьи: проводим аналогии и подводим итог.

2025-02-11 19:26 UTC, Alex-Andr-19 commented
@solarrust Спасибо большое за такую крутую обратную связь! Мне это действительно важно – нужно учиться писать красиво)

2025-02-13 05:44 UTC, Alex-Andr-19 commented
@solarrust Добавил вводную часть. Надеюсь вышло по-лучше)

2025-02-17 07:28 UTC, Alex-Andr-19 commented
@skorobaeus Извини, что лишний раз пишу, но я очень жду ревью.

2025-02-17 11:17 UTC, skorobaeus reviewed
Привет! Спасибо тебе большое за быстрый отклик!

Мне кажется, стало очень последовательно и понятно ❤ Я немного покомментировала и позадавала последние вопросы. Надо с ними разобраться, а дальше только с запятыми пройдусь и будет огонь!

2025-02-17 11:17 UTC, skorobaeus commented on css/pseudo-private-custom-property/index.md
> +```
Эта часть текста сейчас немного оторвана по смыслу от предыдущей, где мы рассуждаем о том, что тащить препроцессоры ради перекраски карточек это чересчур. Просится подзаголовок, что-то вроде: `Решаем задачу при помощи псевдоприватности`. И тогда нужно фрагменты кода привести в соответствие с фрагментами выше, чтобы читатель мог следить, как преобразуется код.

2025-02-17 14:03 UTC, Alex-Andr-19 commented on css/pseudo-private-custom-property/index.md
> +Например, в JavaScript и Python принято писать нижнее подчёркивание перед самим именем поля или метода:
Мне кажется в данном случае есть речевая ошибка – обычно причастные обороты нужны для уточнеения информации и их можно пропустить. Здесь если пропустить `, которые не имеют в своём движке инкапсуляцию полей и методов`, то будет звучать `В языках программирования для их защиты`.
Возможно, стоит написать:

В языках программирования, **которые не имеют в своём движке инкапсуляцию, для защиты полей и методов от внешнего вмешательства** принято использовать соглашение о нейминге.

2025-02-17 14:05 UTC, Alex-Andr-19 commented on css/pseudo-private-custom-property/index.md
> +Если разработчик захочет напрямую обратиться к полям с подобным названием, то TypeScript будет выбрасывать ошибки.
Я думаю вообще убрать этот блок, чтобы не было дизинфы для тех, у кого такое может не работать.

2025-02-17 14:07 UTC, Alex-Andr-19 commented on css/pseudo-private-custom-property/index.md
> +  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi odio minima ullam asperiores molestias. Ullam eaque repudiandae fugit, vitae, ipsum veritatis, in eligendi autem iste non eveniet opti
Понял, добавлю

2025-02-17 14:09 UTC, Alex-Andr-19 commented on css/pseudo-private-custom-property/index.md
> +Создание квадратного блока
псевдоприватность позволяет делать защищённые утилитарные классы и оставлять "снаружи" только "_аргумент_" ?

2025-02-17 14:10 UTC, skorobaeus commented on css/pseudo-private-custom-property/index.md
> +Например, в JavaScript и Python принято писать нижнее подчёркивание перед самим именем поля или метода:
Отлично!

2025-02-17 14:11 UTC, skorobaeus commented on css/pseudo-private-custom-property/index.md
> +Если разработчик захочет напрямую обратиться к полям с подобным названием, то TypeScript будет выбрасывать ошибки.
Хорошая мысль. Так как речь всё же про CSS, можно здесь не углубляться.

2025-02-17 14:12 UTC, skorobaeus commented on css/pseudo-private-custom-property/index.md
> +Создание квадратного блока
Да, идеально!

2025-02-21 05:18 UTC, Alex-Andr-19 commented
@skorobaeus Внёс все нужные правки

2025-02-24 12:36 UTC, skorobaeus approved these changes
Ура, получилось шикарно! Спасибо тебе огромное за работу ❤

2025-02-25 05:34 UTC, Alex-Andr-19 commented
@ra1nbow1 @Inventoris @baileys-li Жду ваших ревью)

2025-02-25 06:13 UTC, ra1nbow1 requested changes
Привет! Оставил пару комментариев

2025-02-25 06:13 UTC, ra1nbow1 commented on css/pseudo-private-custom-property/index.md
> +descriptioin: "Удобный способ работать с кастомными свойствами и использовать их как аргументы миксинов у препроцессоров."
```suggestion
description: "Удобный способ работать с кастомными свойствами и использовать их как аргументы миксинов у препроцессоров."
```

2025-02-25 06:13 UTC, ra1nbow1 commented on css/pseudo-private-custom-property/index.md
> +Чтобы защитить свойства от чтения и записи и возникает необходимость **псевдоприватности кастомных свойств**.
Немного переформулировал
```suggestion
Чтобы защитить свойства от чтения и записи, возникает необходимость использовать **псевдоприватность кастомных свойств**.
```

2025-02-25 06:13 UTC, ra1nbow1 commented on css/pseudo-private-custom-property/demos/pseudo-privates/index.html
> +        --_lighter-color: hsl(from var(--_background-color) h s calc(l * 1.3));
Здесь используется `l`, давай в коде ее объявим

2025-02-25 06:59 UTC, Alex-Andr-19 commented on css/pseudo-private-custom-property/demos/pseudo-privates/index.html
> +        --_lighter-color: hsl(from var(--_background-color) h s calc(l * 1.3));
Так работает функция `hsl`, я же не объявлял `h` и `s`. Функция предоставляет интерфейс работы с цветом, который передан первым аргументом, через пространство hsl, где `h`, `s`, `l` будут конкретными числами

2025-02-25 08:39 UTC, ra1nbow1 commented on css/pseudo-private-custom-property/demos/pseudo-privates/index.html
> +        --_lighter-color: hsl(from var(--_background-color) h s calc(l * 1.3));
Понял, хорошо

2025-02-25 09:00 UTC, skorobaeus commented
@solarrust готово к мержу :)

2025-02-25 14:15 UTC, Alex-Andr-19 commented
@skorobaeus  А сколько необходимо апрувов набрать?

2025-02-28 05:43 UTC, Alex-Andr-19 commented
@solarrust Что мне необходимо доработать для апрува на мёрж?

2025-03-03 17:28 UTC, merged