Добавляет статью про единицы измерения CSS
doka-guide/content pull request #717
Opened 2021-05-26 08:09 UTC by ezhkov

Закрывает #405

2021-05-27 06:51 UTC, solarrust reviewed
Статья огонь получилась! 🤟

Давай в конце дадим короткий итог о том, какие же единицы в вебе применять.

2021-05-27 06:51 UTC, solarrust commented on css/articles/numeric-types/index.md
> +Каждое правило CSS состоит из пары «свойство-значение». В зависимости от свойства значение может быть целым числом, или ключевым словом, или несколькими числами с единицами измерения (например, `45de
```suggestion
Каждое CSS-правило состоит из одной или нескольких пар «свойство-значение». В зависимости от свойства значение может быть целым числом, или ключевым словом, или несколькими числами с единицами измерения (например, `45deg` или `100px`) или без них. Рассмотрим основные единицы измерения.
```

2021-05-27 06:51 UTC, solarrust commented on css/articles/numeric-types/index.md
> +## Единицы измерения длины / расстояния
```suggestion
## Единицы измерения длины или расстояния
```

2021-05-27 06:51 UTC, solarrust commented on css/articles/numeric-types/index.md
> +Используются для задания размера / расстояния относительно чего-либо. Например, `vh`считается относительно высоты вьюпорта (области просмотра страницы в окне браузера).
```suggestion
Используются для задания размера или расстояния относительно чего-либо. Например, `vh`считается относительно высоты вьюпорта (области просмотра страницы в окне браузера).
```

2021-05-27 06:51 UTC, solarrust commented on css/articles/numeric-types/index.md
> +```css
Код и айфрейм отбиваем пустыми строками.

2021-05-27 06:51 UTC, solarrust commented on css/articles/numeric-types/index.md
> +- `cm` — сантиметры. `1cm` = `96px / 2.54`;
@tachisis как нам тут правильно записать математические выражения?

2021-05-27 06:51 UTC, solarrust commented on css/articles/numeric-types/index.md
> +```css
Стоит пояснить, что в этом примере происходит

2021-05-27 06:51 UTC, solarrust commented on css/articles/numeric-types/index.md
> +Например, при указании `width: 50%` ширина элемента будет высчитана как 50% (половина) от ширины родителя. Но если мы укажем в процентах положение фона `background-position-x: 30%`, это значение буде
```suggestion
Например, при указании `width: 50%` ширина элемента будет высчитана как 50% (половина) от ширины родителя. Но если мы укажем в процентах положение фона `background-position-x: 30%`, это значение будет высчитано относительно ширины самого элемента.
```

2021-05-27 15:10 UTC, tachisis commented on css/articles/numeric-types/index.md
> +- `cm` — сантиметры. `1cm` = `96px / 2.54`;
```suggestion
- `cm` — сантиметры. `1 cm` = `96px / 2.54`;
```

2021-06-05 10:00 UTC, ezhkov commented on css/articles/numeric-types/index.md
> +- `cm` — сантиметры. `1cm` = `96px / 2.54`;
Не очень согласен с правкой. `1cm` - это такое же указание значения в CSS, как и `1px`

2021-06-07 12:51 UTC, solarrust commented
Подправила чуть-чуть форматирование и убрала «в CSS» из заголовка. Статья и так находится в разделе CSS =)

@tachisis @pepelsbey заглядывайте на огонёк =)

2021-06-08 09:57 UTC, tachisis reviewed
Немного правочек

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +  - ezhkov_d
```suggestion
  - ezhkov_d
editors:
  - tachisis
```

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +Каждое CSS-правило состоит из одной или нескольких пар «свойство-значение». В зависимости от свойства значение может быть целым числом, или ключевым словом, или несколькими числами с единицами измере
```suggestion
Каждое CSS-правило состоит из одной или нескольких пар «свойство-значение». В зависимости от свойства значение может быть, например, числом, или ключевым словом, или несколькими числами с единицами измерения (например, `45deg` или `100px`). Рассмотрим основные единицы измерения.
```

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +Абсолютные величины ни от чего не зависят и привязаны к физическим единицам измерения: дюймам или сантиметрам. Этот факт имеет исторические предпосылки. Когда появились первые программы предпечатной
```suggestion
Абсолютные величины ни от чего не зависят и привязаны к физическим единицам измерения: дюймам или сантиметрам. Этот факт имеет исторические предпосылки. Когда появились первые программы предпечатной подготовки, возникла необходимость понимать, как картинка на экране будет соответствовать напечатанному варианту. Экраны мониторов в то время были примерно одинаковые, и оказалось, что одному дюйму на экране соответствуют 72 экранных точки. Именно это соотношение зафиксировано в единице измерения `pt`. С развитием технологий улучшались экраны и их разрешение, в один дюйм стало умещаться 96 точек, и это было зафиксировано в `px`.
```

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +- `deg` — градусы угла. Полная окружность содержит 360 градусов. В тригонометрии 0° соответствует пересечению окружности с осью _x_ и градусы отсчитываются против часовой стрелки. В CSS `0deg` соотве
```suggestion
- `deg` — градусы угла. Полная окружность содержит 360 градусов. В тригонометрии 0° соответствует пересечению окружности с осью _x_, и градусы отсчитываются против часовой стрелки. В CSS `0deg` соответствует пересечению окружности с осью _y_, а градусы отсчитываются по часовой стрелке:
```

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +Используются для указания плотности пикселей (разрешения экрана) в медиа-запросах.
```suggestion
Используются для указания плотности пикселей (разрешения экрана) в медиавыражениях.
```

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +- `px` соответствуют пикселям на экране. `1px` интерпретируется как 1/96 дюйма.
```suggestion
- `px` соответствуют пикселям на экране. `1 px` интерпретируется как 1/96 дюйма.
```

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +- `in` — дюймы. `1in` = `96px` = `2.54cm`.
```suggestion
- `in` — дюймы. `1 in` = `96 px` = `2.54 cm`.
```

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +- `cm` — сантиметры. `1cm` = `96px / 2.54`.
```suggestion
- `cm` — сантиметры. `1 cm` = `96 px / 2.54`.
```

2021-06-08 09:57 UTC, tachisis commented on css/articles/numeric-types/index.md
> +- `s` — секунда. `1s` = `1000ms`.
```suggestion
- `s` — секунда. `1 s` = `1000 ms`.
```

2021-06-08 10:11 UTC, solarrust commented on css/articles/numeric-types/index.md
> +- `pc` — пики. `1pc` = `1/16in`.
Я обратила внимание на то, что если мы пишем текст в бэктиках, то это код и тогда единицы измерения отделять от числа не нужно. Если же достаём текст из бэктиков, то отделяем единицы измерения пробелом. Но тогда надо переводить их на русский, кмк. 

Активно обсуждаем с @pepelsbey и @tachisis

2021-06-08 12:44 UTC, pepelsbey requested changes

2021-06-08 12:44 UTC, pepelsbey commented on css/articles/numeric-types/demos/ex.html
> +    }
```suggestion
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
  <style>
    body {
      margin: 0;
      background: #000000;
      font-family: "Roboto", sans-serif;
    }

    .element {
      width: 200px;
      height: 200px;
      display: flex;
      align-items: center;
      justify-content: center;
      background: #fff;
    }

    p {
      margin: 0;
      font-size: 24px;
      width: 100%;
      text-align: center;
      position: relative;
      color: #000;
    }
```

Думаю, подход «задать шрифт всей странице» ближе к реальности, плюс не нужны сложные настройки шрифта при подключении.

2021-06-08 12:44 UTC, pepelsbey commented on css/articles/numeric-types/index.md
> +Используются для задания размера или расстояния относительно чего-либо. Например, `vh`считается относительно высоты вьюпорта (области просмотра страницы в окне браузера).
```suggestion
Используются для задания размера или расстояния относительно чего-либо. Например, `vh` считается относительно высоты вьюпорта (области просмотра страницы в окне браузера).
```

2021-06-08 12:44 UTC, pepelsbey commented on css/articles/numeric-types/index.md
> +- `ic` — это эквивалент `ch` в восточных языках (китайском, корейском, японском). задаёт размер относительно размера иероглифа `水` («вода»).
@tachisis обновил твоё предложение: убрал бэктики с иероглифа и кавычки из «воды», кажется тут достаточно скобок. Согласна?

2021-06-08 12:45 UTC, pepelsbey commented
@tachisis почистил твои комментарии по мотивам обсуждения, дополнительно заведу дискуссию :)

2021-06-15 07:34 UTC, solarrust commented
@ezhkov пинг, когда закончишь с этой статьёй?

2021-06-25 06:25 UTC, solarrust commented
@tachisis очень нужен твой зоркий глаз чтобы привести наконец в порядок инлайн-код =)

2021-06-25 12:45 UTC, pepelsbey approved these changes

2021-06-25 13:42 UTC, solarrust approved these changes

2021-06-25 13:44 UTC, merged