Добавляет статью про object-position
doka-guide/content pull request #729
Opened 2021-05-30 10:40 UTC by lenaryan

2021-05-31 06:13 UTC, solarrust commented on css/doka/object-position/demos/index.html
> +  <link rel="preconnect" href="https://fonts.gstatic.com">
Если в демке нет текста, то и шрифт подключать не за чем =)

2021-05-31 06:13 UTC, solarrust commented on css/doka/object-position/demos/index.html
> +  <img src="https://cataas.com/cat/says/hello%20world!" alt="Кот" class="image" width="500" height="500">
картиночки кладём в папку статьи, в подпапку `images/`

2021-05-31 06:13 UTC, solarrust commented on css/doka/object-position/index.md
> +Свойство помогает спозиционировать картинки `<img>` или видео `<video>`, выставленные прямо в разметку.
```suggestion
Свойство помогает спозиционировать картинки `<img>` или видео `<video>`, вставленные прямо в разметку.
```

А как ещё могут быть вставлены эти теги? 🤔
Спозиционировать картинку (видео) относительно чего?

2021-05-31 06:13 UTC, solarrust commented on css/doka/object-position/index.md
> +
Сюда нужно вынести блок CSS-кода, делающий то, что описано.

2021-05-31 06:13 UTC, solarrust commented on css/doka/object-position/index.md
> +Представьте, что вам нужно вставить в разметку изображение размером 500х300 пикселей, а по макету места хватит только для размера 300х300 пикселей. В таком случае вам поможет [`object-fit`](/css/doka
«Замостить» ассоциируется с многократным повторением чего-то.

2021-05-31 06:13 UTC, solarrust commented on css/doka/object-position/index.md
> +Представьте, что вам нужно вставить в разметку изображение размером 500х300 пикселей, а по макету места хватит только для размера 300х300 пикселей. В таком случае вам поможет [`object-fit`](/css/doka
```suggestion
Представьте, дизайнер предусмотрел блок для картинки размером 300 на 300 пикселей. А клиент прислал изображение размером 500 на 300 пикселей. В таком случае вам поможет [`object-fit`](/css/doka/object-fit), где вы можете указать, каким способом замостить картинку, чтобы она не выглядела искажённой. А `object-position` как раз спозиционирует её относительно размера, заданного в разметке — чтобы выглядело красиво.
```

Красиво — субъективная величина.

2021-05-31 06:13 UTC, solarrust commented on css/doka/object-position/practice/lenaryan.md
> +🛠 Принимает отрицательные значения.
Это скорее советы, чем «В работе»

2021-06-07 14:31 UTC, solarrust commented
@pepelsbey @tachisis заглядывайте =)

2021-06-08 17:36 UTC, pepelsbey requested changes

2021-06-08 17:36 UTC, pepelsbey commented on css/doka/object-position/index.md
> +Свойство помогает спозиционировать картинки `<img>` или видео `<video>`, вставленные прямо в разметку.
```suggestion
Свойство помогает спозиционировать отрисовку картинки `<img>` или видео `<video>` внутри контейнера, если к нему применили свойство [`object-fit`](/css/doka/object-fit).
```

Уточняет работу свойства и упоминает важный нюанс сразу.

2021-06-08 17:36 UTC, pepelsbey commented on css/doka/object-position/index.md
> +Представьте, дизайнер предусмотрел блок для картинки размером 300 на 300 пикселей. А клиент прислал изображение размером 500 на 300 пикселей. В таком случае вам поможет [`object-fit`](/css/doka/objec
Это объясняет принципы работы свойства `object-fit` и очень мало говорит про само свойство `object-position`. Я бы объяснил это иначе, через позиционирование значимой части картинки.

Вот демка https://codepen.io/pepelsbey/pen/eYvjgNd?editors=1100

2021-06-09 21:56 UTC, tachisis reviewed
Призовите меня еще раз, плз, когда будут внесены правки по сути, которые запрашивает @pepelsbey

2021-06-09 21:56 UTC, tachisis commented on css/doka/object-position/index.md
> +По применению и доступным значениям свойство похоже на [`background-position`](/css/doka/background-position).  Оно может принимать как значения в единицах измерения (пикселях, процентах и т. д.), та
```suggestion
По применению и доступным значениям свойство похоже на [`background-position`](/css/doka/background-position). Оно может принимать как значения в единицах измерения (пикселях, процентах и т. д.), так и с указанием расположения относительно границы элемента — `bottom`, `top`, `center`, `left` или `right`. Кроме того, как и в `background-position`, мы можем указать значения отдельно по вертикали и по горизонтали — первое значение обозначает ось _x_, второе — ось _y_. По умолчанию свойство позиционирует контент по центру элемента.
```

2021-06-10 21:18 UTC, lenaryan commented on css/doka/object-position/index.md
> +Представьте, дизайнер предусмотрел блок для картинки размером 300 на 300 пикселей. А клиент прислал изображение размером 500 на 300 пикселей. В таком случае вам поможет [`object-fit`](/css/doka/objec
@pepelsbey а шо, таки можно демку стырить?

2021-06-10 23:58 UTC, pepelsbey commented on css/doka/object-position/index.md
> +Представьте, дизайнер предусмотрел блок для картинки размером 300 на 300 пикселей. А клиент прислал изображение размером 500 на 300 пикселей. В таком случае вам поможет [`object-fit`](/css/doka/objec
@lenaryan я сделал её специально для этой статьи, что значит стырить ) Оригинал картинки допушу сейчас в images, а то там варварское дублирование.

2021-06-11 00:02 UTC, pepelsbey commented
Добавил картинку [для демки](https://codepen.io/pepelsbey/pen/eYvjgNd?editors=1100).

2021-06-12 13:31 UTC, tachisis approved these changes

2021-06-13 08:19 UTC, solarrust commented
@lenaryan работа над этой статьёй закончена? Не могу понять, разобрались ли вы с демкой =)

2021-06-13 08:20 UTC, lenaryan commented
@solarrust остался только момент с демкой, в течение 2-3 часов доделаю

2021-06-13 12:23 UTC, pepelsbey commented on css/doka/object-position/demos/understand.html
> +  <img src="../images/dog.jpeg" alt="Собака">
```suggestion
  <img src="../images/dog.png" alt="Собака">
  <img src="../images/dog.png" alt="Сжатая собака">
  <img src="../images/dog.png" alt="Половина собаки">
  <img src="../images/dog.png" alt="Собака">
```

2021-06-13 12:30 UTC, lenaryan commented on css/doka/object-position/demos/understand.html
> +  <img src="../images/dog.jpeg" alt="Собака">
Рукалицо

2021-06-15 07:46 UTC, solarrust commented
@lenaryan пинг! Когда сможем смёржить эту статью? 
Тут ещё конфликтик образовался =)

2021-06-15 09:09 UTC, lenaryan commented
@solarrust конфликт в спеллере, я не уметь в него

2021-06-15 09:10 UTC, lenaryan commented
А в остальном я закончила

2021-06-15 09:42 UTC, pepelsbey approved these changes

2021-06-15 16:06 UTC, merged