Добавляет статью «Многозадачность и управление процессами»
doka-guide/content pull request #748
Opened 2021-06-03 08:54 UTC by igsekor

Статья связана с #323

2021-06-03 10:48 UTC, pepelsbey reviewed
«Управление процессами» это не практика, это отдельная статья. Нам стоит лучше определить рамки практического совета.

2021-06-03 13:35 UTC, bespoyasov commented on tools/articles/process-management/index.md
> +В современных многопоточных многопользовательских операционных системах для многопроцессорной архитектуры компьютера существуют различные механизмы для управления процессами. Под процессом чаще всего
Вот сюда бы, наверное, было хорошо добавить гифку-видео с тем, как процессор переключается между задачами из разных процессов? 🤔

2021-06-03 13:35 UTC, bespoyasov commented on tools/articles/process-management/index.md
> +Состояние «заблокирован» соответствует случаю, когда процесс, например, ожидает ответа от внешнего устройства: ввод с клавиатуры или ответ от накопителя. Количество состояний увеличивается, если в вв
```suggestion
Состояние «заблокирован» соответствует случаю, когда процесс, например, ожидает ответа от внешнего устройства: ввод с клавиатуры или ответ от накопителя. Количество состояний увеличивается, если ввести возможность приостанавливать процесс в момент того, как он, например, заблокирован или готов продолжить свою работу:
```

2021-06-03 13:35 UTC, bespoyasov commented on tools/articles/process-management/index.md
> +Для того чтобы можно было управлять процессами на уровне операционной системы, существует механизм прерываний. Когда происходит прерывание, выполнение процесса прерывается и совершается какое-то дейс
```suggestion
Чтобы можно было управлять процессами на уровне операционной системы, существует механизм прерываний. Когда происходит прерывание, выполнение процесса прерывается и совершается какое-то действие. Например, можно приостановить процесс или переместить из одной очереди в другую. Часть прерываний обрабатываются только операционной системой, другую часть можно слушать и реагировать на них, аналогично событиям в DOM. Прерывания делятся на две группы: прерывания на уровне железа, и программные прерывания.
```

2021-06-03 16:07 UTC, igsekor commented on tools/articles/process-management/index.md
> +В современных многопоточных многопользовательских операционных системах для многопроцессорной архитектуры компьютера существуют различные механизмы для управления процессами. Под процессом чаще всего
@bespoyasov, я боюсь, что тогда надо будет ещё про операционные системы писать прямо тут, а это же не очень. Процессор сам тоже многое делает (и кэш, и менеджмент операций, и предсказания поведения программ, и многое что ещё), но на это тоже нужны статьи, причём отдельные. Я не знаю, сделать-то недолго 🤷

2021-06-03 16:27 UTC, igsekor commented
> «Управление процессами» это не практика, это отдельная статья. Нам стоит лучше определить рамки практического совета.

@pepelsbey, почему не практика?

2021-06-03 17:29 UTC, bespoyasov commented on tools/articles/process-management/index.md
> +В современных многопоточных многопользовательских операционных системах для многопроцессорной архитектуры компьютера существуют различные механизмы для управления процессами. Под процессом чаще всего
Хм, тогда может и правда не стоит. 

Хочется просто как-то схематично весь процесс отобразить 🤔

2021-06-03 19:40 UTC, igsekor commented on tools/articles/process-management/index.md
> +В современных многопоточных многопользовательских операционных системах для многопроцессорной архитектуры компьютера существуют различные механизмы для управления процессами. Под процессом чаще всего
Что думаешь, @nlopin?

2021-06-05 09:44 UTC, bespoyasov reviewed
У меня больше глаз ни на что не упал. 
@nlopin?

2021-06-06 12:05 UTC, ValyaBro requested changes
- tools/articles/process-management/images/1.png
обрати, пожалуйста, внимание на высоты файлов. Хочется попробовать оставаться в трёх высотах (как в гайде). Кажется, эту схему можно закомпоновать в высоту 800px

- tools/articles/process-management/images/2.png + 3.png
схема стала намного чётче и чище! Давай попробуем использовать версию с крупным заголовком в блоках с подвалом? Так величина заголовков будет равновесной. Плюс хочется использовать более разнящиеся по светлоте цвета. Голубой и жёлтый в монохроме почти не различимы. Для аксессабилити будет лучше использовать более контрастные друг к другу цвета. 

 

- tools/articles/process-management/images/4.png
супер! Отлично работает выделение полупрозрачностью, красивое выделение группы объектов, многоточия, всё очень сбалансированно. Можно поднять чуть выше всю схему целиком вместе с заголовком, сейчас немного прижато к нижнему краю.

- tools/articles/process-management/images/5.png
Сейчас большие поля сверху и снизу, можно сделать высоту меньше (800). Есть излом стрелки в одном месте, лучше будет поправить это, будет чище. 
![Group 1326](https://user-images.githubusercontent.com/42911440/120923538-bdd42f80-c6d7-11eb-83be-cdcc4c204797.png)

- tools/articles/process-management/images/6.png
очень красивая схема получилась! Чистая, графичная, сбалансированая, сразу прослеживаются первостепенные и второстепенные элементы. можно сделать высоту фрейма чуть меньше (1000)

2021-06-07 09:59 UTC, igsekor commented
> * tools/articles/process-management/images/1.png + 2.png + 3.png

@ValyaBro я всё сделал (почти). Но есть проблемы надписями. Я выбрал не крупные заголовки в блоках с подвалом, а мелкие, потому что заголовки не помещаются, а по ширине эти блоки не трансформируются (так задумано). Может, у тебя возникнут идеи как быть?

2021-06-07 10:19 UTC, bespoyasov approved these changes

2021-06-08 16:40 UTC, pepelsbey commented
Ну что, сделаем по успешному примеру «Веб-сервера» из «Управление процессами» отдельную статью? Это объёмный материал с примерами управления процессами. Абсолютно типичный «лонгрид», как мы их раньше называли. Ну или «статья», как называем сейчас.

2021-06-08 20:09 UTC, igsekor commented
> Ну что, сделаем по успешному примеру «Веб-сервера» из «Управление процессами» отдельную статью? Это объёмный материал с примерами управления процессами. Абсолютно типичный «лонгрид», как мы их раньше называли. Ну или «статья», как называем сейчас.

Делаем! 😇

2021-06-10 14:38 UTC, ValyaBro requested changes
Зафиналила все схемы, лежат в доковской фигме, в песочнице. 
Вычистила углы наклона линий, привела всё к цветам, расширила текстовое поле в блоке с подвалом, выровнила блоки относительно друг друга.
прикладываю сюда финальные версии.
<img width="1800" alt="1" src="https://user-images.githubusercontent.com/42911440/121544640-8f758d80-ca12-11eb-80cc-81d0588d4c1f.png">
<img width="1800" alt="2" src="https://user-images.githubusercontent.com/42911440/121544655-913f5100-ca12-11eb-9612-04a379cefa8c.png">
<img width="1800" alt="3" src="https://user-images.githubusercontent.com/42911440/121544663-92707e00-ca12-11eb-86c1-59718ac5614f.png">
<img width="1800" alt="5" src="https://user-images.githubusercontent.com/42911440/121544667-93a1ab00-ca12-11eb-809b-21b1d3fc819c.png">
<img width="1800" alt="6" src="https://user-images.githubusercontent.com/42911440/121544670-93a1ab00-ca12-11eb-8356-c629da7f8f3f.png">

2021-06-10 14:40 UTC, ValyaBro commented
@tachisis чекни, пожалуйста, тексты в схемах-картинках, всё ли там ок

2021-06-10 14:46 UTC, tachisis commented
@ValyaBro 3 картинка, несколько раз повторяется: «Процессы, ожидающие в события ...» — непонятно, что имеется в виду? Они ожидают события? Или они ожидают во время события? Чего ожидают? Надо как-то переформулировать. Остальное в порядке.

2021-06-10 14:49 UTC, ValyaBro commented
@igsekor выше коммент по редактуре, посмотри, плиз.

2021-06-10 17:11 UTC, igsekor commented
> @igsekor выше коммент по редактуре, посмотри, плиз.

Посмотрел, замечания все учёл. Посмотрите, пожалуйста, @ValyaBro @tachisis

2021-06-12 13:28 UTC, tachisis approved these changes
Спасибо, теперь формулировка понятная.

2021-06-12 23:59 UTC, pepelsbey approved these changes

2021-06-15 10:58 UTC, nlopin approved these changes
Отличная работа

2021-06-15 10:58 UTC, nlopin commented on tools/articles/multitasking-and-processes/index.md
> +В современных многопоточных многопользовательских операционных системах для многопроцессорной архитектуры компьютера существуют различные механизмы для управления процессами. Под процессом чаще всего
Мне не очень нравится тяжелое начало: «В современных многопоточных многопользовательских операционных системах для многопроцессорной архитектуры компьютера существуют различные механизмы для управления процессами.»

Есть ли современные немногопоточные многопользовательские операционные системы? Не будет ли ок разбить это предложение на два и опустить некоторые детали? Мы пытаемся сказать много мыслей сразу. Думаю, будет лучше разделить мысли:
* современные ОС многопользовательские и многопоточные
* чтобы всё это работало, нужно уметь обрабатывать и управлять кучей процессов одновременно

2021-06-15 10:58 UTC, nlopin commented on tools/articles/multitasking-and-processes/index.md
> +- после этого выполняется блок первой программы, пока не программа не отправит данные на печать;
```suggestion
- после этого выполняется блок первой программы, пока программа не отправит данные на печать;
```

2021-06-15 10:58 UTC, nlopin commented on tools/articles/multitasking-and-processes/index.md
> +Следующим шагом было внедрение специального диспетчера операционной системы. Главная задача диспетчера — максимально эффективно использовать процессор. Для этого все программы бились уже не на блоки,
Тут кажется имелась ввиду команда:
```suggestion
Следующим шагом было внедрение специального диспетчера операционной системы. Главная задача диспетчера — максимально эффективно использовать процессор. Для этого все программы бились уже не на блоки, а на отдельные операции (команды для процессора). Процессор заблокирован, пока команда не выполнится полностью. На схеме показано, как диспетчер использует очередь готовых к запуску программ (процессов в терминах операционной системы):
```

2021-06-15 10:58 UTC, nlopin commented on tools/articles/multitasking-and-processes/index.md
> +Диспетчер операционной системы распределяет операции процессов в очереди в порядке приоритетов. Такая очередь называется _очередью готовых к запуску_. Приоритет служит основанием для постановки проце
Вот тут я очень долго думал, не ошибка ли. Прочитал два раза, чтобы картинка сложилась. Ниже вопросы, которые у меня возникали при чтении.

Диспетчер расставляет операции процессов в порядке приоритетов.(_приоритетов операций? приоритетов процессов?_). Приоритет служит основанием для постановки процесса в очередь. (_я думал, что здесь ошибка, потому что в первом предложении мы начали говорить про операции_)...

Давай может пойдем от большего к меньшему? 

1.  Всем процессам которые попадают в очередь, присваивается приоритет. Например, у системных процессов он наивысший
2. Диспетчер предпочитает выполнять команды из проиоритетных процессов, тем самым они выполняются быстрее
3. В некоторых ОС можно рулить приоритетами

Как тебе ?

2021-06-15 10:58 UTC, nlopin commented on tools/articles/multitasking-and-processes/index.md
> +В операционной системе процесс — это не просто совокупность операций, то есть код программы. Для того чтобы процессор мог возвращаться к выполнению программы, в операционной системе должны хранится п
```suggestion
Процесс для операционной системы — это не просто совокупность операций или код программы. Для того чтобы процессор мог возвращаться к выполнению программы, в операционной системе должны хранится промежуточные результаты выполнения программы, состояние процессора на момент перехода к другому процессу (контекст) и значения переменных (данные программы):
```

2021-06-15 10:58 UTC, nlopin commented on tools/articles/multitasking-and-processes/index.md
> +У процесса всегда есть приоритет, который позволяет помещать процесс в нужное место очереди. В первую очередь выполняются процессы, имеющие в операционной системе наивысший приоритет. Операционная си
Мне этот абзац показался не на своём месте. Не будет ли лучше добавить его в после абзаца, начинающегося на «Диспетчер операционной системы распределяет операции процессов в очереди в порядке приоритетов...»?

2021-06-15 10:58 UTC, nlopin commented on tools/articles/multitasking-and-processes/index.md
> +Каждому процессу соответствует набор состояний. В современных операционных системах набор состояний сводиться к следующим пяти:
```suggestion
Каждому процессу соответствует набор состояний. В современных операционных системах набор состояний сводится к следующим пяти:
```

2021-06-15 10:58 UTC, nlopin commented on tools/articles/multitasking-and-processes/index.md
> +Состояние «заблокирован» соответствует случаю, когда процесс, например, ожидает ответа от внешнего устройства: ввод с клавиатуры или ответ от накопителя. Количество состояний увеличивается, если ввес
Поменял название состояния на то, что указано схеме выше
```suggestion
Состояние «блокирован» соответствует случаю, когда процесс, например, ожидает ответа от внешнего устройства: ввод с клавиатуры или ответ от накопителя. Количество состояний увеличивается, если ввести возможность приостанавливать процесс в момент того, когда он, например, заблокирован или готов продолжить свою работу:
```

2021-06-15 11:44 UTC, igsekor commented on tools/articles/multitasking-and-processes/index.md
> +У процесса всегда есть приоритет, который позволяет помещать процесс в нужное место очереди. В первую очередь выполняются процессы, имеющие в операционной системе наивысший приоритет. Операционная си
Ну контекст же из структуры процесса, а там мы пишем о диспетчере процессов. То есть, диспетчер использует контекст, чтобы создать то же окружение для процесса, которое было после постановки процесса на паузу... Мне кажется, что нет.

2021-06-15 12:01 UTC, nlopin approved these changes

2021-06-15 13:11 UTC, ValyaBro approved these changes
все картинки ок
@igsekor ты вроде бы хотел перекрасить какие-то блоки в схемах?

2021-06-15 13:16 UTC, igsekor commented
> все картинки ок
> 
> @igsekor ты вроде бы хотел перекрасить какие-то блоки в схемах?

@ValyaBro это уже перекрашенный вариант :)

2021-06-15 13:17 UTC, ValyaBro commented
тогда всё супер

2021-06-15 13:19 UTC, merged