Добавляет статью «Работа с сетью»
doka-guide/content pull request #749
Opened 2021-06-03 08:57 UTC by igsekor

Статья связана с #342

2021-06-03 10:44 UTC, pepelsbey reviewed
На мой взгляд «Мониторинг сети» вываливается из понятия «практика» просто из-за его объёма. Нам будет очень сложно добавить к статье «заметку», которая больше самой статьи. Мне кажется, её нужно выделить в отдельную статью.

2021-06-03 13:15 UTC, bespoyasov reviewed
Я там немного перефразировал примеры протоколов с проверкой целостности и без. Показалось, что если сделать упор на разницу, будет лучше связь с предыдущим параграфом.

Всё остальное (в пределах моей неширокой осведомлённости о сетях 😅) нравится 👍

2021-06-03 13:15 UTC, bespoyasov commented on tools/articles/network/practice/igsekor.md
> +Операционная система Linux постоянно обновляется, обновляются и утилиты. Например, вместо `netstat` лучше использовать `ss`, а вместо `ifconfig` — утилиту `ip`.
❤️

2021-06-03 13:15 UTC, bespoyasov commented on tools/articles/network/index.md
> +Для передачи веб-страниц или файлов по сети используются [TCP](https://ru.wikipedia.org/wiki/Transmission_Control_Protocol) (Transmission Control Protocol — протокол управления передачей) или [TLS](h
```suggestion
Протоколы с проверкой целостности данных используют для передачи веб-страниц или файлов. Они проверяют целостность данных, запрашивают утерянные пакеты или пакеты, в которых была найдена ошибка. Самые распространённые — [TCP](https://ru.wikipedia.org/wiki/Transmission_Control_Protocol) (Transmission Control Protocol — протокол управления передачей) и [TLS](https://ru.wikipedia.org/wiki/TLS) (Transport Layer Security — протокол защиты транспортного уровня).
```

2021-06-03 13:15 UTC, bespoyasov commented on tools/articles/network/index.md
> +Для передачи видео или аудио часто применяется [UDP](https://ru.wikipedia.org/wiki/UDP) (User Datagram Protocol — протокол пользовательских датаграмм), который не обращает внимание на утерянные пакет
```suggestion
Протоколы без проверки целостности используют для передачи видео или аудио, потому что они позволяют передавать больше данных, но с потерями. Пример такого протокола — это [UDP](https://ru.wikipedia.org/wiki/UDP) (User Datagram Protocol — протокол пользовательских датаграмм), который не обращает внимание на утерянные пакеты или пакеты с ошибками.
```

2021-06-03 13:15 UTC, bespoyasov commented on tools/articles/network/index.md
> +:::callout 📚
Спасибо ^_^

2021-06-03 16:29 UTC, igsekor commented
> На мой взгляд «Мониторинг сети» вываливается из понятия «практика» просто из-за его объёма. Нам будет очень сложно добавить к статье «заметку», которая больше самой статьи. Мне кажется, её нужно выделить в отдельную статью.

Не понятно тогда, зачем нужно было убирать раздел «В работе»? Или его можно использовать? Что, если практическая часть больше основной? Что делать? В некоторых темах по инфраструктуре так бывает.

2021-06-03 22:32 UTC, pepelsbey commented
> Не понятно тогда, зачем нужно было убирать раздел «В работе»?

Я не следил за развитием этой статьи, так что не знаю, как появился раздел в работе. Я смотрю на финальную версию этой и других статей и понимаю, что у нас кажется нет окончательно сформулированного понимания, как работают и как выводятся блоки «В работе».

Но если посмотеть [на совет к тегу `<address>`](https://github.com/Y-Doka/content/blob/main/html/doka/address/practice/ezhkov.md), то становится понятно, что здесь что-то не так: это два разных типа контента.

2021-06-06 11:42 UTC, ValyaBro requested changes
- tools/articles/network/images/1.png

сейчас связи получились довольно хаотичными и трудно воспринимаемыми. Давай попробуем добавить больше привязки к сетке и сделать все стрелки или прямыми, или под углом 45 без изломов, или с изломом под 90 градусов? по моим ощущениям должна сработать компоновка всех сетевых устройств в одну вертикаль. + давай сделаем заголовок к схеме заголовком (Roboto Bold 64, в верхней части изображения, по центру). Прикладываю скетч

- tools/articles/network/images/2.png
стало намного лучше1 Теперь хорошо читаются все блоки, связи чётче видны. Кажется есть опечатка в нумерации запросов и блоков (задвоение под номером 2)

- tools/articles/network/images/3.png
можно смело убрать ещё половину высоты полей сверху и снизу. По ширине как встанет 
![2021-05-31 12 34 11](https://user-images.githubusercontent.com/42911440/120923110-6fbe2c80-c6d5-11eb-8eb8-89324754ab5f.jpg)

2021-06-06 17:59 UTC, igsekor commented
> * tools/articles/network/images/1.png
> 
> сейчас связи получились довольно хаотичными и трудно воспринимаемыми. Давай попробуем добавить больше привязки к сетке и сделать все стрелки или прямыми, или под углом 45 без изломов, или с изломом под 90 градусов? по моим ощущениям должна сработать компоновка всех сетевых устройств в одну вертикаль. + давай сделаем заголовок к схеме заголовком (Roboto Bold 64, в верхней части изображения, по центру). Прикладываю скетч

@ValyaBro как раз смысл в том, чтобы подчеркнуть хаотичность связей. Важно, чтобы читатель понимал, что пакеты по сети могут пойти любым путём. Если выстроить в вертикаль, то мы покажем, что сетевые узлы — это слои. Тем более у нас получится один слой. Но это не так на практике. Какой-то пакет может проходить множество сетевых узлов, а какой-то всего несколько. Важно это подчеркнуть. Я понимаю, что мы выходим за рамки предусмотренной логики в дизайн-системе, но здесь пока ничего другого я не вижу, чтобы правильно подать читателю абстракцию того, о чём он в этой статье читает. Что думаешь?

> * tools/articles/network/images/2.png
>   стало намного лучше1 Теперь хорошо читаются все блоки, связи чётче видны. Кажется есть опечатка в нумерации запросов и блоков (задвоение под номером 2)

Переделал 😇.

> * tools/articles/network/images/3.png
>   можно смело убрать ещё половину высоты полей сверху и снизу. По ширине как встанет

Переделал 😇.

2021-06-09 21:46 UTC, nlopin commented on tools/articles/network/practice/igsekor.md
> +### Мониторинг пакетов
Мне кажется это очень технической темой, важной для админов и девопсов,а не для разработчиков. Такую тему невозможно объяснить двумя короткими разделами. Нужно не только суметь запустить wireshark или tcpdump, но и знать, как читать их выдачу, для этого верхнеуровневых знаний из статьи не хватит. 

Предлагаю убрать раздел в черновики, чтобы вернуться к нему позже.

2021-06-09 22:14 UTC, igsekor commented on tools/articles/network/practice/igsekor.md
> +### Мониторинг пакетов
> «Мониторинг» мне кажется это очень технической темой, важной для админов и девопсов,а не для разработчиков. Такую тему невозможно объяснить двумя короткими разделами. Нужно не только суметь запустить wireshark или tcpdump, но и знать, как читать их выдачу, для этого верхнеуровневых знаний из статьи не хватит.

@nlopin у разработчиков, админов и девопсов абсолютно разные задачи, когда они смотрят на пакеты. Пакеты разбираются на второй же лекции по сетям после модели OSI. Разработчикам это крайне важно, поскольку позволяет устранить огромное количество багов, повысить производительность приложения и обеспечить комфорт пользователя. Понимание пакетов очень важно. Сделал коротко только из-за формата практики. Модель сети предлагаю освятить в отдельной статье (уже есть #708), а про пакеты предлагаю сделать в ближайшее время с точки зрения производительности фронтенда.

> Предлагаю убрать раздел в черновики, чтобы вернуться к нему позже.

Можно и такой вариант: убрать / сократить пока практику и вернуть / добавить её целиком вместе с двумя статьями про пакеты и модель сети. Что думаешь?

2021-06-09 22:20 UTC, nlopin commented on tools/articles/network/practice/igsekor.md
> +### Мониторинг пакетов
А можешь развернуть про необходимость этого для разработчиков? Я заглядывал в дамп один раз в моей жизни — когда учил, что это такое. Может я упускаю кучу ценной информации

2021-06-09 22:45 UTC, igsekor commented on tools/articles/network/practice/igsekor.md
> +### Мониторинг пакетов
> А можешь развернуть про необходимость этого для разработчиков? Я заглядывал в дамп один раз в моей жизни — когда учил, что это такое. Может я упускаю кучу ценной информации

Да, конечно. Например, можно оптимизировать загрузку страницы. HTTP 1 / 2 / 3 – это не предел. Можно оптимизировать на уровне пакетов. С момента начала загрузки можно существенно улучшить перформанс, отдавая то, что нужно пользователю в первую очередь. Например, критический CSS и JS. Отладка prefetch и preload. Работа с сертификатами на уровне пакетов, там можно многое оптимизировать. Приведу пример из конференции. Есть доклад Никиты Дубко об оптимизации загрузки CSS, которую они применяют в СЕРПе ([ссылка](https://youtu.be/kATRlMrtaaY) на последнюю, наверное, редакцию, смотреть с 14:00). Чтобы полноценно понимать даже о чём Никита рассказывает, понимание того, как работает сеть очень важно. Нужно ли это новичку? Да, чтобы расти, понимать доклады хотя бы, понимать веб-платформу. А Chrome Dev Tools детальной информации, а соответственно и детального понимания не даёт.

2021-06-10 06:05 UTC, nlopin commented on tools/articles/network/practice/igsekor.md
> +### Мониторинг пакетов
Класс, даже не задумывался об этом. Давай это вынесем в отдельную статью, где расскажем, зачем это нужно и на примере разберем?

2021-06-10 06:24 UTC, igsekor commented on tools/articles/network/practice/igsekor.md
> +### Мониторинг пакетов
> Класс, даже не задумывался об этом. Давай это вынесем в отдельную статью, где расскажем, зачем это нужно и на примере разберем?

@nlopin здесь практику оставляем тогда и ссылку поставим на отдельную статью?

2021-06-10 14:43 UTC, ValyaBro requested changes
Картинка не в нашем стиле. Это скриншот с реального сервиса и надо сохранить стилистику и подписать сущности? 
или это пример кода? В обоих случаях надо переоформить.

2021-06-10 17:12 UTC, igsekor commented
> Картинка не в нашем стиле. Это скриншот с реального сервиса и надо сохранить стилистику и подписать сущности?
> или это пример кода? В обоих случаях надо переоформить.

Тогда просто жду помощи 🙃

2021-06-15 15:48 UTC, igsekor commented on tools/articles/network/practice/igsekor.md
> +### Мониторинг пакетов
> Давай лучше здесь сделаем тизер «очень важно уметь мониторить пакеты, чтобы делать приложения быстрее» и ссылку на статью, а эти разделы перенесём в новую статью.

Сделал, кажется 😇

2021-06-15 19:51 UTC, nlopin approved these changes

2021-06-15 20:53 UTC, pepelsbey approved these changes

2021-06-16 06:04 UTC, bespoyasov approved these changes

2021-06-16 12:23 UTC, tachisis approved these changes
Одна правочка и аппрув

2021-06-16 12:23 UTC, tachisis commented on tools/network/index.md
> +В этой статье рассматриваются не все инструменты для работы с сетевым окружением. Существует утилиты для анализа трафика, мониторинга состояния сетевых интерфейсов. Для быстродействия веб-приложения
```suggestion
В этой статье рассматриваются не все инструменты для работы с сетевым окружением. Существует утилиты для анализа трафика, мониторинга состояния сетевых интерфейсов. Для быстродействия веб-приложения важен детальный анализ не только структуры сети, но и пакетов, которые передаются по сети. Инструменты для проведения такого анализа рассмотрены в статье «[Работа веб-приложения на уровне TCP/UDP](/tools/tcp-udp)».
```

2021-06-16 15:19 UTC, tachisis approved these changes

2021-06-16 18:07 UTC, ValyaBro approved these changes
Картинки ок. Потом будет замена первой картинки на анимацию

2021-06-16 18:25 UTC, pepelsbey commented
@nlopin :shipit:

2021-06-16 22:19 UTC, merged