Добавляет статью про CSS-переменные
doka-guide/content pull request #813
Opened 2021-06-05 06:24 UTC by ezhkov

Закрывает #797

2021-06-07 15:39 UTC, solarrust commented
Почти всё было поправлено в старом репо (https://github.com/Y-Doka/y-doka.site/pull/706).
Давайте финально глянем @pepelsbey @tachisis

2021-06-07 16:52 UTC, pepelsbey requested changes
Я бы выровнял терминологию, @tachisis что скажешь?

2021-06-07 16:52 UTC, pepelsbey commented on css/articles/css-variables/index.md
> +Кастомных свойств не существует в спецификации CSS. По способам применения они больше всего похожи на переменные в языках программирования, поэтому их часто называют **CSS-переменные**. Если мы опред
> **кастомные свойства** (чаще их называют **CSS-переменные**).
> поэтому их часто называют **CSS-переменные**

Мне кажется, что одного раза хватит.

Также в статье они немного непоследовательно называются то так, то иначе. Я бы выбрал подходящее название (я бы за кастомные свойства, это подсказывает принцип работы) и использовал бы его везде, а в начале проговорил бы все другие вариации названия.

2021-06-09 20:43 UTC, tachisis commented on css/articles/css-variables/index.md
> +Кастомных свойств не существует в спецификации CSS. По способам применения они больше всего похожи на переменные в языках программирования, поэтому их часто называют **CSS-переменные**. Если мы опред
@solarrust плюсую к Вадиму. Предлагаю взять «Кастомные свойства» и в заголовок в том числе.

2021-06-15 07:48 UTC, solarrust commented
@ezhkov пинг! Когда сможем смёржить эту статью?

2021-06-25 06:39 UTC, solarrust commented
@tachisis @pepelsbey заменила CSS-переменные на кастомные свойства + переименовала папку. 
Чекните, плиз =)

2021-06-25 06:58 UTC, pepelsbey approved these changes

2021-06-25 13:50 UTC, solarrust approved these changes

2021-06-25 13:51 UTC, merged

2023-04-17 16:48 UTC, reinadiez commented
@ezhkov, привет! Я Настя, развиваю Доку, и мы хотим познакомиться с авторами поближе :) 

Если ты не против поговорить о том, почему решил делиться знаниями, оставь, пожалуйста, ссылку на свой Телеграм, напишу.

2023-04-17 16:51 UTC, ezhkov commented
> @ezhkov, привет! Я Настя, развиваю Доку, и мы хотим познакомиться с авторами поближе :) 
> 
> 
> 
> Если ты не против поговорить о том, почему решил делиться знаниями, оставь, пожалуйста, ссылку на свой Телеграм, напишу. 
> 
> 

Привет. Такой же ник в телеграмме: "@ezhkov"