Добавляет статью об организации потоков данных
doka-guide/content pull request #823
Opened 2021-06-07 09:19 UTC by bespoyasov

Закрывает https://github.com/Y-Doka/content/issues/524.

2021-06-07 17:57 UTC, Windrushfarer commented on js/articles/architecture-data-flow/index.md
> +То, как одна часть программы получает и передаёт данные другим, называется потоком данных (data-flow) и может определить архитектурное устройство всей системы.
А точно нужно тире а data-flow?

2021-06-07 17:57 UTC, Windrushfarer commented on js/articles/architecture-data-flow/index.md
> +Саамый известный пример архитектуры с однонаправленным потоком данных — это [Flux](https://facebook.github.io/flux/) и, как его реализация, [Redux](https://redux.js.org).
```suggestion
Самый известный пример архитектуры с однонаправленным потоком данных — это [Flux](https://facebook.github.io/flux/) и, как его реализация, [Redux](https://redux.js.org).
```

2021-06-07 17:57 UTC, Windrushfarer commented on js/articles/architecture-data-flow/index.md
> +Задача представления — представить данные в понятном для пользователя виде, нарисовать пользовательский интерфейс.
Может лучше так? _представь_ -> _показать_

```suggestion
Задача представления — показать данные в понятном для пользователя виде, нарисовать пользовательский интерфейс.
```

2021-06-07 17:57 UTC, Windrushfarer commented on js/articles/architecture-data-flow/index.md
> +Чаще всего это используется для связывания модели и представления, чтобы обновление, например, текста в поле ввода сразу обновило данные в модели — это называется двунаправленным связыванием данных (
Мне кажется здесь тоже правильнее а два слова

```suggestion
Чаще всего это используется для связывания модели и представления, чтобы обновление, например, текста в поле ввода сразу обновило данные в модели — это называется двунаправленным связыванием данных (two-way data binding).
```

2021-06-07 17:57 UTC, Windrushfarer commented on js/articles/architecture-data-flow/index.md
> +У такого «шортката» есть и плюсы, и минусы. Из плюсов:
Шортката -> способа? :)

2021-06-07 17:58 UTC, Windrushfarer commented
Классно! Оставил парочку комментариев, часть опциональны

2021-06-07 18:43 UTC, bespoyasov reviewed
Спасибо! 🚀

2021-06-07 18:43 UTC, bespoyasov commented on js/articles/architecture-data-flow/index.md
> +Саамый известный пример архитектуры с однонаправленным потоком данных — это [Flux](https://facebook.github.io/flux/) и, как его реализация, [Redux](https://redux.js.org).
Спасибо!

P.S. Клавиши на ноутбуке уже всё, залипают через раз :–(

2021-06-07 18:43 UTC, bespoyasov commented on js/articles/architecture-data-flow/index.md
> +У такого «шортката» есть и плюсы, и минусы. Из плюсов:
Перефразировал 🙂

2021-06-07 18:43 UTC, bespoyasov commented on js/articles/architecture-data-flow/index.md
> +То, как одна часть программы получает и передаёт данные другим, называется потоком данных (data-flow) и может определить архитектурное устройство всей системы.
А и правда!

2021-06-07 20:08 UTC, Windrushfarer approved these changes

2021-06-08 09:49 UTC, igsekor requested changes
Отличная статья! 👍

Отметил пару моментов 😇

2021-06-08 09:49 UTC, igsekor commented on js/articles/architecture-data-flow/index.md
> +Программы — это преобразователи данных. Мы даём программе задачу: вводим исходные, начальные данные и ожидаем получить какой-то результат после их преобразования.
```suggestion
Программы — это преобразователи данных. Мы даём программе задачу: вводим начальные данные и ожидаем получить какой-то результат после их преобразования.
```

Может это слово лишнее? 😇

2021-06-08 09:49 UTC, igsekor commented on js/articles/architecture-data-flow/index.md
> +Чтобы программа выполнила исходную задачу целиком, её части должны работать сообща. Они общаются друг с другом промежуточных результатов работы — тоже данных.
```suggestion
Чтобы программа выполнила исходную задачу целиком, её части должны работать сообща. Они общаются друг с другом с помощью промежуточных результатов работы — тоже данных.
```

Кажется, что слова не хватает 😇

2021-06-08 09:49 UTC, igsekor commented on js/articles/architecture-data-flow/index.md
> +Это автоматическое изменение значения в третьей ячейке — и есть реактивность. Аажется, что это ничем не отличается от простого двойного связывания, но разница есть.
```suggestion
Это автоматическое изменение значения в третьей ячейке — и есть реактивность. Кажется, что это ничем не отличается от простого двойного связывания, но разница есть.
```

2021-06-08 12:29 UTC, igsekor approved these changes
😎

2021-06-10 09:38 UTC, bespoyasov commented
Сорри за уведомления о ревью, на мобильном пальцы не всегда тапают туда, куда хочется 😬

2021-06-12 16:12 UTC, nlopin reviewed
оставил несколько комментариев, давай обсудим

2021-06-12 16:12 UTC, nlopin commented on js/architecture-data-flow/index.md
> +Когда пользователи совершают какие-то действия, например, нажимают на кнопки, представление вызывает экшен (action) — объект-команду, который говорит, что надо сделать с данными, как их преобразовать
я тут уточню, что экшен не говорит, что надо делать с данными. Экшен это объект-команда, которая описывает что произошло с точки зрения логики приложения (addTodo, removeItem, и так далее). Как это влияет на стор, знает только редьюсер

Диспетчер же просто показывает новые экшены всем редьюсерам, которые есть

2021-06-12 16:12 UTC, nlopin commented on js/architecture-data-flow/index.md
> +## Что выбрать
может всё-таки напишем какие факторы скорее будут склонять к двунаправленной, а какие к однонаправленной?

У меня в голову приходит:
* в больших или сложных приложениях хочется меньше магии, чтобы чётко понимать, что происходит. Я бы склонялся к однонаправленным
* в больших командах тоже бы думал об однонаправленном, потому что меньше вероятность «вася поправил поле и все разломалось»
* двунаправленные отлично работают в небольших проектах и экономят много времени

2021-06-13 12:42 UTC, bespoyasov commented on js/architecture-data-flow/index.md
> +Когда пользователи совершают какие-то действия, например, нажимают на кнопки, представление вызывает экшен (action) — объект-команду, который говорит, что надо сделать с данными, как их преобразовать
Переписал.

2021-06-13 12:44 UTC, bespoyasov commented on js/architecture-data-flow/index.md
> +## Что выбрать
Добавил.

2021-06-13 19:32 UTC, tachisis reviewed
Аппрув на изменения в словаре

2021-06-15 11:29 UTC, nlopin approved these changes

2021-06-15 11:33 UTC, tachisis approved these changes

2021-06-15 11:55 UTC, merged