Element.innerHTML
doka-guide/content pull request #905
Opened 2021-06-09 18:43 UTC by Windrushfarer

Closes #744

2021-06-09 19:38 UTC, tachisis approved these changes
Изменения в словаре аппрувнуты.

2021-06-10 09:04 UTC, bespoyasov requested changes
Лайк за примеры с XSS! 
Поднял несколько вопросов про написание и примеры.

2021-06-10 09:04 UTC, bespoyasov commented on js/doka/element-innerhtml/index.md
> +Несмотря на то, что с помощью `Element.innerHTML` вставить любой html, есть некоторые ограничения, связанные с [безопасностью веб-приложений](js/articles/web-security). Если вставить в элемент html в
Тут немного не понял мысль, давай упростим?

2021-06-10 09:04 UTC, bespoyasov commented on js/doka/element-innerhtml/index.md
> +Обращение к свойству `Element.innerHTML` вернёт html элемента в виде строки. Просмотреть или изменить HTML можно у всех элементов, включая `<html>` и `<body>`. Присвоение нового значения к свойству о
Мне кажется, нам надо условиться, как мы пишем HTML: в нижнем или верхнем кейсе, когда говорим о кусках кода или фрагментах, чтобы везде было последовательно. Ну или придумать правила, по которым написание будет различаться 😃 

@nlopin, что думаешь?

2021-06-10 09:04 UTC, bespoyasov commented on js/doka/element-innerhtml/index.md
> +Обращение к свойству `Element.innerHTML` вернёт html элемента в виде строки. Просмотреть или изменить HTML можно у всех элементов, включая `<html>` и `<body>`. Присвоение нового значения к свойству о
```suggestion
Обращение к свойству `Element.innerHTML` вернёт содержимое элемента в виде html-строки. Просмотреть или изменить содержимое можно у всех элементов, включая `<html>` и `<body>`. Присвоение нового значения к свойству очистит всё текущее содержимое и заменит его новым html.
```

2021-06-10 09:04 UTC, bespoyasov commented on js/doka/element-innerhtml/index.md
> +Если передать в `Element.innerHTML` строку с невалидным html, то будет выброшена ошибка.
Давай дадим пример ошибки?

2021-06-10 09:46 UTC, Windrushfarer commented on js/doka/element-innerhtml/index.md
> +Если передать в `Element.innerHTML` строку с невалидным html, то будет выброшена ошибка.
Я к сожалению потратил час в попытках сформировать, но так и не смог сделать. Кажется как-будто современный браузер кажется готов съесть какой угодно html, лишь бы не сломаться.

2021-06-10 09:58 UTC, bespoyasov commented on js/doka/element-innerhtml/index.md
> +Если передать в `Element.innerHTML` строку с невалидным html, то будет выброшена ошибка.
Хм 🤔 

Может тогда перефразировать? Сказать, что браузер не даст этого сделать?

2021-06-10 15:52 UTC, Windrushfarer commented on js/doka/element-innerhtml/index.md
> +Если передать в `Element.innerHTML` строку с невалидным html, то будет выброшена ошибка.
Да, я подумаю, просто в спецификации написано об этом и MDN тоже упоминает.

2021-06-10 18:56 UTC, Windrushfarer commented on js/doka/element-innerhtml/index.md
> +Свойство `Element.innerHTML` позволяет считать содержимое элемента в виде html-строки или установить новый html. Новое значение html необходимо передавать в виде строки и оно заменит текущее содержим
Я наверное подробности лучше добавлю в часть "Как понять", все-таки кратко должен быть кратким :)

2021-06-11 07:28 UTC, bespoyasov approved these changes

2021-06-11 07:28 UTC, bespoyasov commented on js/doka/element-innerhtml/index.md
> +Свойство `Element.innerHTML` позволяет считать содержимое элемента в виде html-строки или установить новый html. Новое значение html необходимо передавать в виде строки и оно заменит текущее содержим
```suggestion
Свойство `Element.innerHTML` позволяет считать содержимое элемента в виде html-строки или установить новый html. Новое значение html необходимо передавать в виде строки и оно заменит текущее содержимое элемента. При передаче невалидной html-строки будет выброшена ошибка. Html-строкой является строка, которая содержит валидную html-разметку, в `Element.innerHTML` нельзя передать DOM-элемент.
```

2021-06-11 07:28 UTC, bespoyasov commented on js/doka/element-innerhtml/index.md
> +Так как в `div` находится объект DOM-элемента, то при присовении в `Element.innerHTML` он приведется к строке, в результате в элемент вставится строка `"[object HTMLDivElement]"`.
Отличный пример!

2021-06-11 07:57 UTC, nikolai-shabalin commented on js/doka/element-innerhtml/index.md
> +Обращение к свойству `Element.innerHTML` вернёт html элемента в виде строки. Просмотреть или изменить HTML можно у всех элементов, включая `<html>` и `<body>`. Присвоение нового значения к свойству о
Обычно пишут прописными, когда говорят о технологии: HTML-элемент,  HTML-строка, добавим в HTML, также как с DOM. Никто же не пишет "Dom".
А вот теги имеет смысл писать как они пишутся на самом деле `<html>`, `<span>`, чтобы проще визуально отделять селектор `html`, `span` от тега.

2021-06-14 08:38 UTC, bespoyasov approved these changes

2021-06-15 11:32 UTC, nlopin commented on js/doka/element-innerhtml/index.md
> +Обращение к свойству `Element.innerHTML` вернёт html элемента в виде строки. Просмотреть или изменить HTML можно у всех элементов, включая `<html>` и `<body>`. Присвоение нового значения к свойству о
Уточнил у Оли, HTML всегда пишем в верхнем регистре

2021-06-15 12:51 UTC, nlopin approved these changes

2021-06-15 12:51 UTC, merged