Статья по yaml
doka-guide/content pull request #915
Opened 2021-06-10 16:34 UTC by KognitivnayaBuena

2021-06-11 08:10 UTC, bespoyasov reviewed
Хорошее описание базового синтаксиса 👍 

Я так предложил несколько изменений и идей, большая часть опциональна.

2021-06-11 08:10 UTC, bespoyasov commented on js/doka/yaml/index.md
> +  Якорь - это приспособление для создания переменных, на которые можно ссылаться. Якорь позволяет нам избежать дублирования конфига при наличия разных частей конфига в зависимости от переменной. Чтоб
> Символы `<<` показывают что мы просто вставим элементы без привязки к значению ключа.

Как вариант, можно тоже использовать аналогию со spread-оператором в JS. (Или перегрузкой аргументов из других языков.)

2021-06-11 08:10 UTC, bespoyasov commented on js/doka/yaml/practice/KognitivnayaBuena.md
> +Один из способов использования это настройка github actions. Это очень полезная штука, которая позволяет нам проверять наши пул реквесты. Можно и линтер и тесты проставить на определнное действие, чт
```suggestion
Один из способов использования это настройка github actions. Это очень полезная штука, которая позволяет проверять пул-реквесты по заданным в YAML-конфигах правилам. 

Если в правилах описать запуск линтера и тестов в ответ на событие в репозитории (например, pull-request), то они будут запускаться каждый раз при появлении этого события. Так мы можем оградить главную ветку репозитория от сломанного кода.

Базовый список для минимального action это имя, в каком случае он будет выполняться (на какое событие), где запускать (операционная система) и шаги которые необходимо выполнить.
```

2021-06-11 08:10 UTC, bespoyasov commented on js/doka/yaml/practice/KognitivnayaBuena.md
> +on: [push]
```suggestion
on: [pull_request]
```

2021-06-11 08:10 UTC, bespoyasov commented on js/doka/yaml/practice/KognitivnayaBuena.md
> +      # в нашем случае ${{ github.event_name }} будет то, что перечислено по ключу on -это значение push
```suggestion
      # в нашем случае ${{ github.event_name }} будет то, что перечислено по ключу on — это значение pull_request
```

2021-06-13 00:03 UTC, pepelsbey requested changes
Давайте оставим в ПР только то, что относится к статье, а правки других статей и случайный файл уберём:

- js/doka/array-find/demos/index.html
- js/doka/array-find/index.md 
- node_modules/.yarn-integrity

2021-06-13 00:11 UTC, pepelsbey commented on js/doka/yaml/index.md
> +## Cтруктуры данных которые нам доступны в YAML.
Давай попробуем для организации структуры этого раздела использовать заголовки вместо списков:

```md
### Строки

### Числа

### Списки и массивы

### Якорь или ссылочная переменная
```

Большой плюс заголовков, что на них можно дать ссылку. И они более явно отделяют части друг от друга.

Также у нас принято разделять все блоки пустой строкой (списки, заголовки, параграфы) — это помогает понять, как они на самом деле отрендерятся. Для того же не стоит делать переносов внутри параграфа — они всё равно склеятся в один блок текста.

2021-06-14 08:37 UTC, bespoyasov reviewed
Финальные штрихи 👌

2021-06-14 08:37 UTC, bespoyasov commented on js/doka/yaml/index.md
> +Расширение файла может быть `*.yaml` или `*.yml`- это все YAML.
Давай перенесём в «Коротко», чтобы было в начале статьи. Кажется, что там это будет логичнее, потому что описывает «мета-информацию» о YAML.

2021-06-14 08:37 UTC, bespoyasov commented on js/doka/yaml/index.md
> +  <<: *base
```suggestion
  # Добавляем все значения из base:
  <<: *base
```

2021-06-14 08:37 UTC, bespoyasov commented on js/doka/yaml/index.md
> +  age: 7
```suggestion
  # «Перезаписываем» значение для поля `age`:
  age: 7
```

2021-06-14 08:37 UTC, bespoyasov commented on js/doka/yaml/index.md
> +
```suggestion

::: callout 📚

Это немного похоже на работу оператора [spread](/js/doka/object/) в JavaScript.

:::

```

2021-06-14 08:37 UTC, bespoyasov commented on js/doka/yaml/index.md
> +Один из способов использования это настройка github actions. Это очень полезная штука, которая позволяет проверять пул-реквесты по заданным в YAML-конфигах правилам.
```suggestion
Один из способов использования — это настройка github actions. Это очень полезная штука, которая позволяет проверять пул-реквесты по заданным в YAML-конфигах правилам.
```

2021-06-14 08:37 UTC, bespoyasov commented on js/doka/yaml/index.md
> +   Якорь - это приспособление для создания переменных, на которые можно ссылаться. Якорь позволяет нам избежать дублирования конфига при наличия разных частей конфига в зависимости от переменной. Что
```suggestion
   Якорь - это приспособление для создания переменных, на которые можно ссылаться. Якорь позволяет вынести повторяющиеся части конфига и использовать ссылку на них в других местах. Так мы можем уменьшить дублирование кода. 
   
Чтобы обозначить якорь используем символ `&`. Чтобы задать значение ссылочной переменной нужно использовать символ `*`. Символы `<<` показывают что мы просто вставим элементы без привязки к значению ключа.
```

2021-06-14 08:37 UTC, bespoyasov commented on js/doka/yaml/index.md
> +   Якорь - это приспособление для создания переменных, на которые можно ссылаться. Якорь позволяет нам избежать дублирования конфига при наличия разных частей конфига в зависимости от переменной. Что
Я попробовал перефразировать, чтобы стало попроще. Не потерялся ли смысл? А то вдруг я факт-чек сейчас не пройду 😅

2021-06-14 15:25 UTC, pepelsbey commented on .yaspeller.json
> +  "ignoreText": ["(\\d+|n)-(го|е|й|м|ми|му|х|ю|я)", ""],
Лучше стейджить только смысловые правки, это настройки редактора или самоуверенный форматтер )

2021-06-14 15:31 UTC, pepelsbey commented on js/doka/yaml/index.md
> +```
Лучше не писать длинные комментарии в коде: их сложно читать на узких экранах, они подсвечиваются бледным, чтобы не мешать читать код. Можно после блока с кодом описать всё нужное:

````suggestion
```yaml
name: GitHub Actions Example
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ура! Я запустился на ${{ github.event_name }}."
      - run: echo "Я работаю на ОС - ${{ runner.os }}"
```

В экшенах можно пользоваться переменными, например, операционная система `${{ runner.os }}` описана выше одноименным ключом `runs-on` и мы получим значение Linux. В случае `${{ github.event_name }}` выведет значение ключа `on` — `pull_request`.
````

2021-06-15 20:44 UTC, pepelsbey commented on js/doka/yaml/index.md
> +```
У маркдауна есть свои особенности, из которых складывается разметка, которая потом рендерится. Например, в этом случае будет не список с кодом, а списки с одним пунктов и примеры кода между ними:

```html
<p>Ниже примеры:</p>

<ul>
<li>без лишних кавычек</li>
</ul>

<pre><code class="yaml">name: insertYourCatName
</code></pre>

<ul>
<li>вариант с несколькими словами</li>
</ul>

<pre><code class="yaml">name: insert Your Cat Name
</code></pre>

<ul>
<li>с использованием двойных или одинарных кавычек (в данном случае двойные)</li>
</ul>

<pre><code class="yaml">name: &quot;insertYourCatName&quot;
</code></pre>
```

Это просто по смыслу не подходит. Лучше либо вот так, широко, с параграфами:

````md
Можно использовать с кавычками и без, в одно и несколько слов. Все в вашей власти! Ниже примеры:

Без лишних кавычек:

```yaml
name: insertYourCatName
```

Вариант с несколькими словами

```yaml
name: insert Your Cat Name
```

С использованием двойных или одинарных кавычек (в данном случае двойные):

```yaml
name: "insertYourCatName"
```
````

Лучше либо так, компактнее со списком:

````md
Можно использовать с кавычками и без, в одно и несколько слов. Все в вашей власти! Например:

- `name: insertYourCatName` — без лишних кавычек;
- `name: insert Your Cat Name` — вариант с несколькими словами;
- `name: "insertYourCatName"` — c двойными или одинарными кавычками.
````

2021-06-16 06:11 UTC, bespoyasov approved these changes
👌 

Я там ниже написал ограничение про пустые стороки в коллаутах, которые надо добавить. Всё остальное хорошо.

2021-06-16 06:11 UTC, bespoyasov commented on js/doka/yaml/index.md
> +Это немного похоже на работу оператора [spread](/js/doka/object/) в JavaScript.
```suggestion

Это немного похоже на работу оператора [spread](/js/doka/object/) в JavaScript.

```

2021-06-16 06:11 UTC, bespoyasov commented on js/doka/yaml/index.md
> +Это немного похоже на работу оператора [spread](/js/doka/object/) в JavaScript.
В коллауатах надо обязательно ставить пустые строки между `:::callout`, текстом и `:::`. Иначе парсер не сможет понять, что это коллаут, и преобразовать его. Автоматизировать это мы пока не знаем как 😞

2021-06-16 12:25 UTC, tachisis approved these changes
Аппрув на изменения в словаре.

2021-06-16 22:31 UTC, nlopin commented on js/doka/yaml/index.md
> +## В работе
Я бы ещё что-нибудь сказал о сравнении yaml с json. Чем он лучше? Почему не json?

2021-06-16 22:31 UTC, nlopin commented on js/doka/yaml/index.md
> +Для разделения в файле используются отступы - пробелы. Табы не допускаются, поэтому лучше настроить себе линтер на проверку и правку. Пара похожа на json и работает по принципу ключ-значение. Определ
Вот тут мне кажется важным сказать четко, о каком разделении идет речь. Отступы говорят нам о вложенности. Можно попробовать сравнить с джейсоном

2021-06-16 22:32 UTC, nlopin commented
- [ ] Перенести в новую структуру @nlopin

2021-06-16 22:32 UTC, nlopin commented
- [ ] Перенести в новую структуру @nlopin

2021-06-17 20:31 UTC, nlopin approved these changes

2021-06-17 20:32 UTC, merged