Редактирует статьи про hover, link, visited, active
doka-guide/content pull request #920
Opened 2021-06-12 15:16 UTC by tachisis

2021-06-14 21:20 UTC, pepelsbey requested changes

2021-06-14 21:20 UTC, pepelsbey commented on css/visited/practice/solarrust.md
> +🛠 Если вы задаёте стили для разных состояний ссылок, следует придерживаться определённого порядка в объявлении: `:link` — `:visited` — `:hover` — `:active`.
Если уж порядок, то упорядоченный список и так больше на селектор похоже.

```suggestion
🛠 Если вы задаёте стили для разных состояний ссылок, следует придерживаться определённого порядка в объявлении:

 1. `:link`
 1. `:visited`
 1. `:hover`
 1. `:active`
```

2021-06-14 21:20 UTC, pepelsbey commented on css/visited/index.md
>  .link:visited:before {
```suggestion
.link:visited::before {
```

2021-06-14 21:20 UTC, pepelsbey commented on css/active/index.md
>  .link:before:active {
```suggestion
.link::before:active {
```

2021-06-14 21:20 UTC, pepelsbey commented on css/hover/index.md
>  .link:before:hover {
```suggestion
.link::before:hover {
```

2021-06-14 21:20 UTC, pepelsbey commented
В момент создания этой ветки, тесты были сломаны, так что я локально прогнал и подмёржил словарь из мейна.

2021-06-16 16:53 UTC, pepelsbey approved these changes

2021-06-18 03:52 UTC, solarrust approved these changes

2021-06-18 03:52 UTC, merged